import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';
const file=path.join(process.env.VEXA_CANDIDATE,'packages/connectors/comparability.mjs');
const mod=await import(pathToFileURL(file)).catch(()=>({}));
const money={USD:{amountMinor:'30000',knownSubtotalMinor:'30000',knownCount:2,totalCount:2,status:'complete'}};
const snapshot=(id,over={})=>({id,scope:{dateStart:'2026-09-01T00:00:00.000Z',dateEnd:'2026-10-01T00:00:00.000Z',timezone:'UTC',currency:'USD',dateBasis:'conversation',sources:[],channels:[]},method:{pipelineVersion:'canonical-source-v1',mappingVersions:['map-v1'],taxonomyVersion:'not-applied'},watermark:'2026-09-20T00:00:00.000Z',inputHash:'a'.repeat(64),summary:{conversations:4,sourceConversations:5,messages:7,orders:2,channels:{email:3,chat:1},money,warnings:[]},...over});
test('F03-06 pure comparison contract',async t=>{
 assert.equal(typeof mod.compareSnapshots,'function','COMPARABILITY_IMPLEMENTATION_MISSING');
 await t.test('alias counts are descriptive; global order exposure stays30000 and never savings',()=>{const a=snapshot('a'),b=snapshot('b',{summary:{...a.summary,sourceConversations:6}});const c=mod.compareSnapshots(a,b);assert.equal(c.state,'comparable');assert.equal(c.money.USD.deltaMinor,'0');assert.equal(c.savings,null);assert.equal(c.causallyAttributed,false);});
 await t.test('lost channel denies business deltas even with fewer tickets',()=>{const a=snapshot('a'),b=snapshot('b',{summary:{...a.summary,conversations:3,channels:{email:3}}});const c=mod.compareSnapshots(a,b);assert.equal(c.state,'no_comparable');assert.ok(c.reasons.includes('channel_coverage_changed'));assert.equal(c.money.USD.deltaMinor,null);assert.deepEqual(c.channels.find(x=>x.channel==='chat'),{channel:'chat',before:1,after:0,delta:-1});});
 await t.test('channel names inherited from Object.prototype are exact own keys',()=>{
  for(const channel of ['constructor','__proto__','toString','hasOwnProperty']){
   const a=snapshot('a'),b=snapshot('b');a.summary={...a.summary,channels:Object.fromEntries([['email',3],[channel,1]])};b.summary={...b.summary,channels:{email:3}};
   const c=mod.compareSnapshots(a,b);assert.equal(c.state,'no_comparable','PROTOTYPE_CHANNEL_MUST_BLOCK');assert.ok(c.reasons.includes('channel_coverage_changed'));assert.deepEqual(c.channels.find(x=>x.channel===channel),{channel,before:1,after:0,delta:-1});assert.equal(c.money.USD.deltaMinor,null);
   const reverse=mod.compareSnapshots(b,a);assert.equal(reverse.state,'no_comparable');assert.deepEqual(reverse.channels.find(x=>x.channel===channel),{channel,before:0,after:1,delta:1});
  }
 });
 await t.test('a method explanation never grants permission to compare different taxonomy',()=>{const a=snapshot('a'),b=snapshot('b',{method:{...a.method,taxonomyVersion:'v2'},explanation:'SYN: reclasificación'});const c=mod.compareSnapshots(a,b);assert.equal(c.state,'no_comparable');assert.ok(c.reasons.includes('taxonomy_changed'));assert.equal(c.money.USD.deltaMinor,null);});
 await t.test('scope, pipeline, mapping and currency are frozen independently',()=>{for(const field of ['pipelineVersion','mappingVersions']){const a=snapshot('a'),b=snapshot('b',{method:{...a.method,[field]:field==='mappingVersions'?['map2']:'v2'}});assert.equal(mod.compareSnapshots(a,b).state,'no_comparable');}const a=snapshot('a');assert.equal(mod.compareSnapshots(a,snapshot('b',{scope:{...a.scope,currency:'EUR'}})).state,'no_comparable');});
 await t.test('same currency code with different minor-unit exponent is not comparable',()=>{const a=snapshot('a'),b=snapshot('b');a.method={...a.method,currencyExponents:{USD:2}};b.method={...b.method,currencyExponents:{USD:0}};const c=mod.compareSnapshots(a,b);assert.equal(c.state,'no_comparable');assert.ok(c.reasons.includes('currency_unit_changed'));assert.equal(c.money.USD.deltaMinor,null);});
 await t.test('unknown amount never becomes zero and bigint stays exact',()=>{const a=snapshot('a'),b=snapshot('b',{summary:{...a.summary,money:{USD:{...money.USD,amountMinor:null,knownCount:1,status:'partial'}}}});assert.equal(mod.compareSnapshots(a,b).money.USD.deltaMinor,null);const huge='900719925474099312345';a.summary={...a.summary,money:{USD:{...money.USD,amountMinor:huge,knownSubtotalMinor:huge}}};const z=snapshot('b',{summary:{...a.summary,money:{USD:{...a.summary.money.USD,amountMinor:'900719925474099312346'}}}});assert.equal(mod.compareSnapshots(a,z).money.USD.deltaMinor,'1');});
 await t.test('invalid calendar days cannot silently roll into another comparison window',()=>{assert.throws(()=>mod.comparisonScope({dateStart:'2026-02-30T00:00:00Z',dateEnd:'2026-03-05T00:00:00Z',timezone:'UTC',currency:'USD',dateBasis:'conversation',sources:[],channels:[]}),/COMPARISON_DATE_INVALID/);});
});
