import {record,page,adapter,windowSpec} from '../F03-sync/fixtures.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import path from 'node:path';import {q} from './harness.mjs';
import {insert} from '../F01-03/matrix.mjs';
export const scope={dateStart:'2026-09-01T00:00:00Z',dateEnd:'2026-10-01T00:00:00Z',timezone:'UTC',currency:'USD',dateBasis:'conversation',sources:[],channels:[]};
function seed(h,a){a.account='SYN-account-'+randomUUID();h.sql(`UPDATE connections SET source='zendesk',account_id=${q(a.account)} WHERE id=${q(a.connection)}`);const orders=[],conversations=[],messages=[];
 function version(id,type,external){const rid=randomUUID(),provenance={source:'zendesk',account_id:a.account,synthetic:true};h.sql(insert('source_revisions',{id:rid,tenant_id:a.tenant,connection_id:a.connection,entity_type:type,external_id:external,source_revision:'SYN-1',content_hash:'a'.repeat(64),fingerprint:'b'.repeat(64),mapping_version:'SYN-mapping-v1',snapshot:[{fixture:true}],canonical_id:id,[type+'_id']:id,provenance}));h.sql(insert('source_heads',{id,tenant_id:a.tenant,connection_id:a.connection,entity_type:type,external_id:external,version:1,state:'unique',selected_revision_id:rid}));}
 for(let n=0;n<2;n++){const id=randomUUID();orders.push(id);h.sql(insert('orders',{id,tenant_id:a.tenant,connection_id:a.connection,external_id:'O'+n,amount_minor:String((n+1)*10000),currency:'USD',exponent:2,occurred_at:'2026-09-05T12:00:00Z'}));version(id,'order','O'+n);}
 for(let n=0;n<5;n++){const id=randomUUID();conversations.push(id);h.sql(insert('conversations',{id,tenant_id:a.tenant,connection_id:a.connection,source:'zendesk',external_id:'T'+n,channel:n===4?'chat':'email',started_at:'2026-09-05T12:00:00Z',order_id:orders[n%2],provenance:{source:'zendesk',account_id:a.account,synthetic:true}}));version(id,'conversation','T'+n);const mid=randomUUID();messages.push(mid);h.sql(insert('messages',{id:mid,tenant_id:a.tenant,connection_id:a.connection,conversation_id:id,external_id:'M'+n,role:'customer',occurred_at:'2026-09-05T12:05:00Z'}));version(mid,'message','M'+n);}
 return {orders,conversations,messages};}
export async function domain(t,h){const a=seed(h,h.A),b=seed(h,h.B),ra=h.repository(h.A),rb=h.repository(h.B);let before,aliased,lost;
 await t.test('capture freezes a published SQL snapshot with unique money and stable idempotency',async()=>{before=await ra.comparison.capture(scope);assert.equal(before.summary.conversations,5);assert.equal(before.summary.messages,5);assert.equal(before.summary.money.USD.amountMinor,'30000','EXPOSURE_UNION_NOT_CONVERSATION_SUM');assert.deepEqual(before.summary.warnings,[]);assert.equal((await ra.comparison.capture(scope)).id,before.id,'IDENTICAL_INPUT_REUSES_FROZEN_CUT');h.frozen=h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(before.id)}`);assert.equal((await rb.comparison.list()).snapshots.length,0,'NO_B_SNAPSHOT');});
 await t.test('real explicit alias changes unique identity count and preserves30000 plus prior snapshot',async()=>{await ra.aliases.confirm({sourceConversationId:a.conversations[1],targetConversationId:a.conversations[0],expectedVersion:0,evidenceRef:'SYN-crosswalk',reason:'SYN human approval',approved:true});aliased=await ra.comparison.capture(scope);const result=await ra.comparison.compare({beforeId:before.id,afterId:aliased.id});assert.equal(result.state,'comparable');assert.equal(result.counts.conversations.after,4);assert.equal(result.money.USD.deltaMinor,'0');assert.equal(result.money.USD.after.amountMinor,'30000');assert.equal(result.savings,null);assert.equal(h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(before.id)}`),h.frozen,'BASELINE_NOT_REWRITTEN');});
 await t.test('channel loss is coverage loss and never tickets saved',async()=>{h.sql(`UPDATE conversations SET deleted_at=now() WHERE id=${q(a.conversations[4])}`);lost=await ra.comparison.capture(scope);const result=await ra.comparison.compare({beforeId:before.id,afterId:lost.id});assert.equal(result.state,'no_comparable');assert.ok(result.reasons.includes('channel_coverage_changed'));assert.equal(result.money.USD.deltaMinor,null);assert.equal(result.channels.find(c=>c.channel==='chat').after,0);});
 await t.test('SQL denies modifying or deleting every published baseline',async()=>{await assert.rejects(ra.database.transaction('import',s=>s.query("UPDATE metric_snapshots SET provenance='{}' WHERE tenant_id=$1 AND id=$2",[s.tenantId,before.id])));await assert.rejects(ra.database.transaction('retain',s=>s.query('DELETE FROM metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,before.id])));assert.equal(h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(before.id)}`),h.frozen);});
 await t.test('tenant selector, untrusted body and foreign snapshot identifiers cannot leak B',async()=>{const bs=await rb.comparison.capture(scope);await assert.rejects(ra.comparison.compare({beforeId:before.id,afterId:bs.id}));const dual={...h.bot,tenant:h.A.tenant};const response=await h.request(dual,'/api/migrations?tenant_id='+h.B.tenant);assert.equal(response.status,200);assert.ok(response.data.snapshots.every(s=>s.id!==bs.id));assert.ok(!JSON.stringify(response.data).includes(h.B.account));assert.equal((await h.request(h.A,'/api/migrations',{...scope,tenant_id:h.B.tenant})).status,400);assert.equal((await h.request(h.A,'/api/migrations/compare?'+new URLSearchParams({before:before.id,after:bs.id}))).status,409);assert.equal(b.conversations.length,5);});
 await t.test('viewer reads but cannot capture, membership revocation affects stale sessions and CSRF is required',async()=>{const bot={...h.bot,tenant:h.A.tenant};h.sql(`UPDATE memberships SET role='viewer' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);try{assert.equal((await h.request(bot,'/api/migrations')).status,200);assert.equal((await h.request(bot,'/api/migrations',scope)).status,403);h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);assert.ok([401,403].includes((await h.request(bot,'/api/migrations')).status));}finally{h.sql(`UPDATE memberships SET role='analyst',status='active' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);}const res=await fetch(h.base+'/api/migrations',{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify(scope)});assert.equal(res.status,403);});
 await t.test('database unavailable returns503, never a successful empty snapshot list',async()=>{await h.stopWeb();await h.startWeb(true);try{assert.equal((await h.request(h.A,'/api/migrations')).status,503);}finally{await h.stopWeb();await h.startWeb();}});
 await t.test('real browser selects frozen cuts, refreshes and reports lost channels without savings',async()=>{const browser=await h.browser(),ctx=await browser.newContext();ctx.setDefaultTimeout(15000);try{await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const n=v.indexOf('=');return{name:v.slice(0,n),value:v.slice(n+1),url:h.base};}));const p=await ctx.newPage();const nav=await p.goto(h.base+'/migrations');fs.writeFileSync(path.join(h.evidence,'browser-before-select.json'),JSON.stringify({status:nav.status(),url:p.url(),body:await p.locator('body').innerText(),labels:await p.locator('label').allTextContents()}));await p.screenshot({path:path.join(h.evidence,'browser-before-select.png'),fullPage:true});await p.getByLabel('Antes',{exact:true}).selectOption(before.id);await p.getByLabel('Después',{exact:true}).selectOption(lost.id);const response=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/migrations/compare');await p.getByRole('button',{name:'Comparar cortes',exact:true}).click();assert.equal((await response).status(),200);await p.getByRole('heading',{name:'No comparable',exact:true}).waitFor();assert.match(await p.locator('body').innerText(),/Cambió la cobertura de canales/);await p.getByRole('button',{name:'Actualizar cortes',exact:true}).click();await p.screenshot({path:path.join(h.evidence,'comparison-lost-channel.png'),fullPage:true});}finally{await ctx.close();}});
 await t.test('keyset pages retain every frozen cut sharing a microsecond timestamp',async()=>{
  h.sql("ALTER TABLE metric_snapshots ALTER COLUMN created_at SET DEFAULT '2026-09-01T12:00:00.123456Z'::timestamptz");
  const created=[];try{for(let n=1;n<=52;n++)created.push((await ra.comparison.capture({...scope,dateEnd:new Date(Date.parse(scope.dateEnd)+n*1000).toISOString()})).id);}finally{h.sql('ALTER TABLE metric_snapshots ALTER COLUMN created_at SET DEFAULT now()');}
  const received=[];let cursor=null;do{const data=await ra.comparison.list({cursor});received.push(...data.snapshots.map(s=>s.id));cursor=data.nextCursor;}while(cursor);
  assert.equal(received.length,new Set(received).size,'PAGINATION_NO_DUPLICATES');assert.ok(created.every(id=>received.includes(id)),'PAGINATION_NO_SUBMILLISECOND_OMISSIONS');
 });

 await t.test('SQL immutability mutant is detected without rewriting the frozen evidence',async()=>{
  const check=()=>assert.rejects(ra.database.transaction('import',async tx=>{await tx.query('SAVEPOINT mutation_probe');await tx.query("UPDATE metric_snapshots SET provenance='{}'::jsonb WHERE tenant_id=$1 AND id=$2",[tx.tenantId,before.id]);await tx.query('ROLLBACK TO mutation_probe');}),undefined,'SNAPSHOT_IMMUTABLE_ORACLE');
  await check();let detected=false;h.sql('ALTER TABLE metric_snapshots DISABLE TRIGGER snapshot_guard');try{await check().catch(e=>{assert.equal(e.code,'ERR_ASSERTION');detected=true;});}finally{h.sql('ALTER TABLE metric_snapshots ENABLE TRIGGER snapshot_guard');}assert.ok(detected,'SNAPSHOT_MUTANT_CAUGHT');await check();assert.equal(h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(before.id)}`),h.frozen);fs.writeFileSync(path.join(h.evidence,'sql-mutants.json'),JSON.stringify(['snapshot_immutability:0-1-0']));
 });
 await t.test('API capture and paged reads are real and never expose internal inputs',async()=>{
  const response=await h.request(h.A,'/api/migrations',{...scope,dateStart:'2026-09-02T00:00:00Z'});assert.equal(response.status,201);assert.equal(response.data.snapshot.summary.money.USD.amountMinor,'30000');
  const first=await h.request(h.A,'/api/migrations');assert.equal(first.status,200);assert.equal(first.data.snapshots.length,50);assert.ok(first.data.nextCursor);const next=await h.request(h.A,'/api/migrations?'+new URLSearchParams({cursor:first.data.nextCursor}));assert.equal(next.status,200);assert.ok(next.data.snapshots.length>0);assert.ok(!next.data.snapshots.some(s=>first.data.snapshots.some(x=>x.id===s.id)));for(const x of ['inputs','account_id','source_conversation_id',h.A.account,h.B.account,h.A.token])assert.ok(!JSON.stringify(first.data).includes(x),'SNAPSHOT_API_ALLOWLIST');
  const raw=await fetch(h.base+'/api/migrations',{headers:{cookie:h.cookie(h.A)}});assert.match(raw.headers.get('cache-control'),/private/);assert.match(raw.headers.get('cache-control'),/no-store/);
 });
 await t.test('browser captures a new immutable cut and loads older pages',async()=>{
  const browser=await h.browser(),ctx=await browser.newContext();ctx.setDefaultTimeout(15000);try{await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const n=v.indexOf('=');return{name:v.slice(0,n),value:v.slice(n+1),url:h.base};}));const p=await ctx.newPage();await p.goto(h.base+'/migrations');await p.getByLabel('Inicio UTC',{exact:true}).fill('2026-09-03');await p.getByLabel('Fin UTC exclusivo',{exact:true}).fill('2026-10-01');const created=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/migrations'&&r.request().method()==='POST');await p.getByRole('button',{name:'Congelar corte',exact:true}).click();const response=await created;assert.equal(response.status(),201,'BROWSER_CAPTURE_REAL');const data=await response.json();await p.getByLabel('Después',{exact:true}).selectOption(data.snapshot.id);const next=p.waitForResponse(r=>new URL(r.url()).searchParams.has('cursor'));await p.getByRole('button',{name:'Cargar cortes anteriores',exact:true}).click();assert.equal((await next).status(),200,'BROWSER_PAGINATION_REAL');assert.equal(h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(before.id)}`),h.frozen);}finally{await ctx.close();}
 });

 await t.test('real sync preserves provider channel lineage in a snapshot without rewriting canonical history',async()=>{
  const actor={...h.A,source:'zendesk'},ticket=record(h.ingestion,actor,'SYN-channel-origin',{type:'ticket'});ticket.payload.via={channel:'email'};ticket.envelope=h.ingestion.createEnvelope(ticket.envelope,ticket.envelope,ticket.payload);
  await h.sync.runSync({repository:h.sync.createSyncRepository({database:ra.database}),connectionId:actor.connection,mode:'live',window:{...windowSpec,version:'SYN-channel-origin'},adapterFactory:async()=>adapter([page([ticket],'SYN-end',{done:true})])});
  const canonicalBefore=h.sql(`SELECT to_jsonb(c) FROM conversations c WHERE tenant_id=${q(actor.tenant)} AND external_id='SYN-channel-origin'`),rawBefore=h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM sync_raw_objects r WHERE tenant_id=${q(actor.tenant)} AND connection_id=${q(actor.connection)}`);
  const hub={...h.A,source:'hubspot',connection:randomUUID(),account:'SYN-hub-'+randomUUID()};h.sql(insert('connections',{id:hub.connection,tenant_id:hub.tenant,source:hub.source,account_id:hub.account}));const payload={id:'HS-T1',createdAt:'2026-02-01T00:00:00Z',originalChannelId:'1000'},envelope=h.ingestion.createEnvelope({tenant_id:hub.tenant,connection_id:hub.connection,source:hub.source,source_account_id:hub.account},{entity_type:'thread',external_id:'HS-T1',source_revision:'SYN-r1',occurred_at:'2026-02-01T00:00:00Z',observed_at:'2026-09-01T00:00:00Z',payload_ref:'SYN-thread'},payload);
  await h.sync.runSync({repository:h.sync.createSyncRepository({database:ra.database}),connectionId:hub.connection,mode:'live',window:{...windowSpec,version:'SYN-hub-channel'},adapterFactory:async()=>adapter([page([{envelope,payload}],'SYN-hub-end',{done:true})])});
  const snapshot=await ra.comparison.capture({...scope,dateStart:'2026-01-01T00:00:00Z'});assert.equal(snapshot.summary.channels.zendesk_email,1,'COMMITTED_PROVIDER_CHANNEL_VISIBLE');assert.equal(snapshot.summary.channels.hubspot_1000,1,'HUBSPOT_CHANNEL_ID_NOT_INVENTED_EQUIVALENCE');assert.equal(h.sql(`SELECT to_jsonb(c) FROM conversations c WHERE tenant_id=${q(actor.tenant)} AND external_id='SYN-channel-origin'`),canonicalBefore,'CHANNEL_PROJECTION_NO_SOURCE_REWRITE');assert.equal(h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM sync_raw_objects r WHERE tenant_id=${q(actor.tenant)} AND connection_id=${q(actor.connection)}`),rawBefore,'CHANNEL_PROJECTION_RAW_IMMUTABLE');
 });

 await t.test('malformed pagination cursor is a client error, not a database outage',async()=>{assert.equal((await h.request(h.A,'/api/migrations?cursor=%%%')).status,400,'MALFORMED_CURSOR_400');});

 await t.test('oversize synchronous capture fails closed instead of publishing partial counts',async()=>{
  const previous=h.sql(`SELECT count(*) FROM metric_snapshots WHERE tenant_id=${q(h.A.tenant)}`),prefix='SYN-limit-'+randomUUID();
  h.sql(`INSERT INTO conversations(tenant_id,connection_id,source,external_id,provenance) SELECT ${q(h.A.tenant)},${q(h.A.connection)},'zendesk',${q(prefix)}||g::text,'{}'::jsonb FROM generate_series(1,10001) g`);
  try{await assert.rejects(ra.comparison.capture(scope));assert.equal(h.sql(`SELECT count(*) FROM metric_snapshots WHERE tenant_id=${q(h.A.tenant)}`),previous,'NO_PARTIAL_SNAPSHOT');}finally{h.sql(`DELETE FROM conversations WHERE tenant_id=${q(h.A.tenant)} AND connection_id=${q(h.A.connection)} AND external_id LIKE ${q(prefix+'%')}`);}
 });

}
