'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Recommendation,RecommendationList} from '../../../../../packages/recommendations/index.mjs';
import type {Scope} from '../../lib/workspace/contracts';
import {SharedFilters} from '../workspace/shared-filters';
import {DataState} from '../workspace/data-state';
type Filters=Scope & {basis:string;exponent?:number};
type Operation=(url:string,body:unknown)=>Promise<boolean>;
function cleanQuery(value:string){const q=new URLSearchParams(value);for(const key of ['problem_id','detail_hash','resource','format','cursor','limit','root_kind','root_id','component_id','event_id'])q.delete(key);return q;}
function initialScope(value:string):Filters{const q=cleanQuery(value),now=new Date(),start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)),end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));return {date_start:q.get('date_start')??start.toISOString(),date_end:q.get('date_end')??end.toISOString(),timezone:'UTC',date_basis:q.get('date_basis')??'occurred_at',currency:q.get('currency')??'USD',basis:q.get('basis')??'net',sku:q.getAll('sku'),source:q.getAll('source'),snapshot_id:q.get('snapshot_id'),...(q.has('exponent')?{exponent:Number(q.get('exponent'))}:{})};}
function pinnedQuery(scope:Scope,snapshot:string,hash:string){const q=new URLSearchParams({date_start:scope.date_start.slice(0,10),date_end:scope.date_end.slice(0,10),timezone:scope.timezone,date_basis:scope.date_basis,currency:scope.currency,basis:scope.basis??'net',snapshot_id:snapshot,scope_hash:hash});if(scope.exponent!==null&&scope.exponent!==undefined)q.set('exponent',String(scope.exponent));for(const sku of scope.sku)q.append('sku',sku);for(const source of scope.source)q.append('source',source);return q;}
function failure(status:number){return status===401||status===403?'Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.':status===404?'No hay una recomendación o evidencia autorizada para este alcance.':status===409?'La versión o la evidencia cambió. Actualiza y revisa la propuesta antes de continuar.':status===400?'Revisa los campos y el alcance de la solicitud.':'No se pudo verificar la operación. Conserva tu borrador y reintenta; no se confirma ningún cambio.';}
function RecommendationCard({item,members,busy,conflict,operate}:{item:Recommendation;members:RecommendationList['members'];busy:boolean;conflict:boolean;operate:Operation}){
 const [action,setAction]=useState(item.action),[conditions,setConditions]=useState(item.preconditions.join('\n')),[rationale,setRationale]=useState(item.rationale),[owner,setOwner]=useState(item.ownerId??''),[reason,setReason]=useState(''),[stateReason,setStateReason]=useState('');
 const draftKey=useRef<string|null>(null);const locked=busy||conflict||!item.canMutate;const endpoint='/api/recommendations/'+item.id;
 const create=()=>{draftKey.current??=crypto.randomUUID();void operate(endpoint+'/interventions',{expectedVersion:item.version,requestKey:draftKey.current});};
 const evidenceQuery=pinnedQuery(item.scope,item.snapshotId,item.scopeHash);evidenceQuery.set('detail_hash',item.detailHash);
 return <article className="record-card" aria-label={'Recomendación: '+item.title}><header><span className="status">{item.status==='dismissed'?'Descartada':'Propuesta'} · v{item.version}</span><h2>{item.title}</h2></header>
  <p><strong>Acción recomendada:</strong> {item.action}</p><p>{item.rationale}</p><p>Prioridad: {item.priority==='critical'?'Revisión humana urgente':item.priority==='high'?'Alta':'Normal'} · Esfuerzo: revisión diagnóstica</p><p>Estado causal: {item.causalState}. Esta propuesta no demuestra causalidad ni garantiza un ahorro.</p>
  <p>Responsable: {item.ownerId??'Sin asignar'} · Problema v{item.problemVersion}</p><p className="snapshot">Publicación: {item.snapshotId} · Alcance: {item.scopeHash}</p>
  <h3>Condiciones para considerar esta acción</h3><ul>{item.preconditions.map((v,i)=><li key={i}>{v}</li>)}</ul>
  {item.stale&&<p role="status">El problema o su evidencia ha cambiado. Esta versión se conserva como historial y requiere una propuesta vigente antes de actuar.</p>}
  <p><Link href={'/problems/'+item.problemId+'?'+evidenceQuery.toString()}>Ver problema y evidencia de esta recomendación</Link></p>
  <details><summary>Evidencia de la recomendación ({item.evidenceRefs.length})</summary>{item.evidenceRefs.map((e,i)=><figure key={e.runId+':'+e.messageRevisionId+':'+i}><blockquote>{e.quote}</blockquote><figcaption>{e.role} · Revisión {e.messageRevisionId} · {e.category}</figcaption></figure>)}</details>
  {item.canMutate&&<><form className="action-form" aria-label="Revisar recomendación" onSubmit={e=>{e.preventDefault();if(!locked)void operate(endpoint,{operation:'revise',expectedVersion:item.version,action,preconditions:conditions.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),rationale,ownerId:owner||null,reason});}}>
   <label htmlFor={item.id+'-action'}>Acción propuesta</label><textarea id={item.id+'-action'} required minLength={20} maxLength={2000} value={action} onChange={e=>setAction(e.target.value)} disabled={busy}/>
   <label htmlFor={item.id+'-conditions'}>Condiciones previas, una por línea</label><textarea id={item.id+'-conditions'} required value={conditions} onChange={e=>setConditions(e.target.value)} disabled={busy}/>
   <label htmlFor={item.id+'-rationale'}>Justificación de la recomendación</label><textarea id={item.id+'-rationale'} required minLength={20} maxLength={4000} value={rationale} onChange={e=>setRationale(e.target.value)} disabled={busy}/>
   <label htmlFor={item.id+'-owner'}>Responsable de la recomendación</label><select id={item.id+'-owner'} value={owner} onChange={e=>setOwner(e.target.value)} disabled={busy}><option value="">Sin asignar</option>{members.map(m=><option key={m.id} value={m.id}>{m.id} · {m.role}</option>)}</select>
   <label htmlFor={item.id+'-reason'}>Razón del cambio</label><textarea id={item.id+'-reason'} required minLength={20} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/>
   <button disabled={locked}>Guardar revisión</button>
  </form><form className="action-form" aria-label="Cambiar estado de la recomendación" onSubmit={e=>{e.preventDefault();if(!locked)void operate(endpoint,{operation:'state',expectedVersion:item.version,status:item.status==='dismissed'?'proposed':'dismissed',reason:stateReason});}}>
   <label htmlFor={item.id+'-state-reason'}>Razón para cambiar el estado</label><textarea id={item.id+'-state-reason'} required minLength={20} maxLength={2000} value={stateReason} onChange={e=>setStateReason(e.target.value)} disabled={busy}/>
   <button disabled={locked}>{item.status==='dismissed'?'Reabrir recomendación':'Descartar recomendación'}</button>
  </form>{item.status==='proposed'&&<button disabled={locked||item.drafts.length>0} onClick={create}>Crear intervención borrador</button>}</>}
  {!item.canMutate&&<p>Esta versión es de consulta con tus permisos y la evidencia vigentes.</p>}
  {item.drafts.length>0&&<section aria-label="Borradores de intervención"><h3>Intervención guardada como borrador</h3><p>El borrador aún no autoriza ejecución. Conserva la recomendación, su responsable y su publicación de referencia.</p><ul>{item.drafts.map(d=><li key={d.id}>{d.id} · {d.status} · Recomendación v{d.recommendationVersion} · {d.hypothesis}</li>)}</ul></section>}
  <details><summary>Historial de versiones ({item.history.length})</summary><ol>{item.history.map(v=><li key={v.version}><strong>v{v.version} · {v.status==='dismissed'?'Descartada':'Propuesta'}</strong><p>{v.action}</p><p>{v.reason}</p><p>Responsable: {v.ownerId??'Sin asignar'} · Registrado por {v.actorId} · <time>{v.createdAt}</time></p></li>)}</ol></details>
 </article>;
}
export function RecommendationsPanel({initialQuery}:{initialQuery:string}){
 const [query,setQuery]=useState(cleanQuery(initialQuery).toString()),[scope,setScope]=useState<Filters>(()=>initialScope(initialQuery)),[view,setView]=useState<RecommendationList|null>(null),[busy,setBusy]=useState(true),[empty,setEmpty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false),[problem,setProblem]=useState(new URLSearchParams(initialQuery).get('problem_id')??'');
 const generation=useRef(0),controller=useRef<AbortController|null>(null),resolved=useRef(query),inFlight=useRef(false),generateKey=useRef<{fingerprint:string;key:string}|null>(null);
 const invalidate=useCallback(()=>{controller.current?.abort();generation.current++;inFlight.current=false;},[]);
 const load=useCallback(async(input:string)=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;inFlight.current=true;setBusy(true);setView(null);setError('');setEmpty(false);setNotice('');setConflict(false);
  try{const p=cleanQuery(input);p.set('resource','problems');const snapshot=await fetch('/api/workspace?'+p.toString(),{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!snapshot.ok)throw Error(failure(snapshot.status));const envelope=await snapshot.json();if(abort.signal.aborted||epoch!==generation.current)return;const meta=envelope.data?.meta;if(!meta?.scope)throw Error('No se pudo verificar la publicación solicitada.');setScope({...meta.scope,exponent:meta.scope.exponent??undefined});if(!meta.snapshot_id||!meta.scope_hash){setEmpty(true);return;}
   const fixed=pinnedQuery(meta.scope,meta.snapshot_id,meta.scope_hash);const response=await fetch('/api/recommendations?'+fixed.toString(),{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(failure(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const data=json.data as RecommendationList;if(!data||!Array.isArray(data.items)||!Array.isArray(data.problemOptions)||!Array.isArray(data.members)||data.snapshotId!==meta.snapshot_id||data.scopeHash!==meta.scope_hash)throw Error('No se pudo verificar el alcance de las recomendaciones.');resolved.current=fixed.toString();window.history.replaceState(null,'',window.location.pathname+'?'+fixed.toString());setView(data);
  }catch(e){if(!abort.signal.aborted&&epoch===generation.current){setView(null);setError(e instanceof Error?e.message:'No se pudo consultar las recomendaciones.');}}
  finally{if(!abort.signal.aborted&&epoch===generation.current){inFlight.current=false;setBusy(false);}}
 },[]);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)void load(query);});return()=>{active=false;invalidate();};},[query,load,invalidate]);
 useEffect(()=>{const back=()=>{invalidate();const next=cleanQuery(window.location.search.slice(1)).toString();resolved.current=next;setProblem('');if(next===query)void load(next);else setQuery(next);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[invalidate,load,query]);
 const apply=(next:URLSearchParams)=>{invalidate();const changed=['date_start','date_end','currency','basis','exponent'].some(k=>{const old=new URLSearchParams(resolved.current).get(k)??'';return(next.get(k)??'')!==old;});if(changed&&next.get('snapshot_id')===scope.snapshot_id)next.delete('snapshot_id');next.delete('scope_hash');setView(null);setProblem('');setError('');setBusy(true);const value=cleanQuery(next.toString()).toString();resolved.current=value;window.history.pushState(null,'',window.location.pathname+'?'+value);if(value===query)void load(value);else setQuery(value);};
 const operate:Operation=async(url,body)=>{if(inFlight.current)return false;inFlight.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;setBusy(true);setError('');setNotice('');let saved=false;
  try{const response=await fetch(url,{method:'POST',cache:'no-store',signal:abort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(abort.signal.aborted||epoch!==generation.current)return false;if(!response.ok){if([401,403,404].includes(response.status)){setView(null);setProblem('');}if(response.status===409)setConflict(true);throw Error(failure(response.status));}const result=await response.json();if(abort.signal.aborted||epoch!==generation.current)return false;if(!result.data)throw Error('No se pudo verificar el resultado de la operación.');saved=true;
   const refreshed=await fetch('/api/recommendations?'+resolved.current,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return false;if(!refreshed.ok){if([401,403,404].includes(refreshed.status))setView(null);throw Error('La operación se guardó, pero no se pudo verificar la vista actual. Actualiza antes de continuar.');}const json=await refreshed.json();if(abort.signal.aborted||epoch!==generation.current)return false;const next=json.data as RecommendationList;const fixed=new URLSearchParams(resolved.current);if(!next||!Array.isArray(next.items)||next.snapshotId!==fixed.get('snapshot_id')||next.scopeHash!==fixed.get('scope_hash'))throw Error('La operación se guardó, pero la vista recibida no coincide con su alcance.');setView(next);setNotice('Cambio guardado y verificado.');return true;
  }catch(e){if(!abort.signal.aborted&&epoch===generation.current){if(saved)setConflict(true);setError(e instanceof Error?e.message:failure(503));}return false;}
  finally{if(!abort.signal.aborted&&epoch===generation.current){inFlight.current=false;setBusy(false);}}
 };
 const generate=()=>{if(!view||!problem||busy||conflict)return;const fingerprint=JSON.stringify({query:resolved.current,problemId:problem,problemVersion:view.problemOptions.find(p=>p.id===problem)?.version});if(generateKey.current?.fingerprint!==fingerprint)generateKey.current={fingerprint,key:crypto.randomUUID()};void operate('/api/recommendations',{operation:'generate',query:resolved.current,problemId:problem,requestKey:generateKey.current.key});};
 return <section aria-label="Recomendaciones con evidencia"><p className="eyebrow">Decisiones y seguimiento</p><h1>Recomendaciones</h1><p>Propuestas condicionadas a la evidencia de una publicación. Revisa sus condiciones y asigna un responsable antes de crear una intervención.</p>
  <SharedFilters key={JSON.stringify(scope)} scope={scope} onApply={apply}/><button disabled={busy} onClick={()=>void load(resolved.current)}>Actualizar recomendaciones</button>
  {busy&&<p role="status">Verificando recomendaciones…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{empty&&<DataState state={{kind:'empty'}}/>}
  {empty&&<p>Publica un corte financiero para proponer acciones sobre evidencia verificable. <Link href="/economics">Revisar publicaciones</Link></p>}
  {view&&<><p className="snapshot">Publicación: {view.snapshotId} · Alcance: {view.scopeHash}</p>{view.unavailableCount>0&&<p role="status">Hay recomendaciones que no pueden mostrarse con la evidencia y los permisos actuales.</p>}
   {view.canPropose?<form className="action-form" onSubmit={e=>{e.preventDefault();generate();}}><label htmlFor="recommendation-problem">Problema para recomendar</label><select id="recommendation-problem" required disabled={busy} value={problem} onChange={e=>setProblem(e.target.value)}><option value="">Seleccionar problema</option>{view.problemOptions.map(p=><option key={p.id} value={p.id}>{p.label} · v{p.version}</option>)}</select><button disabled={busy||conflict||!view.problemOptions.some(p=>p.id===problem)}>Proponer recomendación</button><small>La propuesta se genera con reglas explícitas y evidencia autorizada. Requiere revisión humana.</small></form>:<p>Tu rol permite consultar las recomendaciones. Proponer o modificar requiere permisos de analista, operador o propietario.</p>}
   {!view.items.length&&<p>No hay recomendaciones publicadas para este alcance.</p>}{view.items.map(item=><RecommendationCard key={item.id+':'+item.version} item={item} members={view.members} busy={busy} conflict={conflict} operate={operate}/>)}
  </>}
 </section>;
}
