import {aggregateMoney,revenueRiskScenario} from '../economics/index.mjs';
const money=x=>x===null?null:BigInt(x);
export function separateComponents({entries,sources,scope,asOf}){
 const complete=type=>{const relevant=sources.filter(s=>s.evidenceType===type);return relevant.length>0&&relevant.every(s=>s.active&&s.complete&&s.windowStart<=scope.start&&s.windowEnd>=scope.end&&s.watermark>=scope.end&&scope.end<=asOf);};
 const compatible=e=>e.currency===scope.currency&&e.exponent===scope.exponent&&e.basis===scope.basis&&e.effectiveAt>=scope.start&&e.effectiveAt<scope.end;
 const aggregate=(kind,type,amount,divisor=1n)=>{const rows=entries.filter(e=>e.kind===kind&&compatible(e)&&['settled','modeled','unknown'].includes(e.status));const result=aggregateMoney(rows.map(e=>({id:e.id,currency:e.currency,amountMinor:e.status==='unknown'?null:amount(e)})))[scope.currency];const round=value=>value===null?null:((BigInt(value)+divisor/2n)/divisor).toString();const isComplete=complete(type),known=round(result?.knownSubtotalMinor??'0');return {amountMinor:isComplete?(result?round(result.amountMinor):'0'):null,knownSubtotalMinor:rows.length?known:isComplete?'0':null,knownCount:result?.knownCount??0,totalCount:rows.length,status:!isComplete?(rows.length?'partial':'unavailable'):result?.status??'complete',currency:scope.currency,exponent:scope.exponent,basis:scope.basis,window:{start:scope.start,end:scope.end},evidenceRefs:rows.map(r=>r.rowId),missingReasons:isComplete?rows.some(e=>e.status==='unknown'||amount(e)===null)?['unknown_amount']:[]:['source_incomplete_or_absent']};};
 const replacement=aggregate('replacement','replacement_invoice',e=>e.amountMinor);
 const supportModel=aggregate('support_model','support_timesheet',e=>{const d=e.details;if(d.durationSeconds===null||d.rateMinorPerMinute===null)return null;return (money(d.durationSeconds)*money(d.rateMinorPerMinute)).toString();},60n);
 const futureScenarios=entries.filter(e=>e.kind==='future_scenario'&&e.status==='modeled'&&e.currency===scope.currency&&e.exponent===scope.exponent&&e.basis===scope.basis&&e.effectiveAt<=asOf).map(e=>{const d=e.details;const valid=Date.parse(d.validFrom)<=Date.parse(asOf)&&Date.parse(d.validUntil)>Date.parse(asOf);const calculated=!valid||d.affectedCustomers===null?{kind:'scenario',amountMinor:null,status:'unavailable'}:revenueRiskScenario({affectedCustomers:d.affectedCustomers,relevantRevenueMinor:d.relevantRevenueMinor,probabilityBps:d.probabilityBps,currency:e.currency,horizonDays:d.horizonDays,assumptionId:d.assumptionId});return {...calculated,horizonDays:d.horizonDays,id:e.id,currency:e.currency,exponent:e.exponent,basis:e.basis,start:asOf,end:new Date(Date.parse(asOf)+d.horizonDays*86400000).toISOString(),evidenceEffectiveAt:e.effectiveAt,cohort:{affectedCustomers:d.affectedCustomers,relevantRevenueMinor:d.relevantRevenueMinor,frozenAt:asOf},missingReasons:valid?[]:['assumption_not_valid_as_of'],assumptions:d.assumptionReport,evidenceRef:e.rowId,intervalKind:'scenario',causallyAttributed:false};});
 return {replacement,supportModel,futureScenarios,combinedTotal:null,notice:'Componentes no aditivos. Exposición no es pérdida; soporte es modelado; escenarios no son pronósticos calibrados ni ahorro.'};
}
