import {randomUUID,createHash} from 'node:crypto';
import {adaptLedger} from '../economics/adapter.mjs';
import {separateComponents} from './components.mjs';
import {evidence} from '../problems/repository.mjs';
import {DomainError} from '../problems/contracts.mjs';
import {EconomicError} from './repository.mjs';
const uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(x);
const requireValue=(ok,code,status=409)=>{if(!ok)throw new EconomicError(code,status);};
const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
const hash=x=>createHash('sha256').update(canonical(x)).digest('hex');
const iso=x=>new Date(x).toISOString();
const instant=x=>{if(typeof x!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(x)||!Number.isFinite(Date.parse(x)))return false;return iso(x)===(x.includes('.')?x.replace(/\.(\d{1,3})Z$/,(_,n)=>'.'+n.padEnd(3,'0')+'Z'):x.replace('Z','.000Z'));};
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];
const latestRows=async(s,table,key)=>(await s.query(`SELECT DISTINCT ON(${key}) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.${table} WHERE tenant_id=$1 ORDER BY ${key},version DESC`,[s.tenantId])).rows;
const kinds=['order','refund','reversal','replacement','support_model'];
const report=q=>typeof q.report==='string'&&q.report.length>=20&&q.report.length<=4000&&q.attested===true&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0;
const keys=(q,allowed)=>q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>allowed.includes(k));
const common=['expectedVersion','report','attested'];
function normalizeScope(q){requireValue(keys(q,['start','end','timezone','dateBasis','currency','exponent','basis'])&&instant(q.start)&&instant(q.end)&&Date.parse(q.start)<Date.parse(q.end)&&q.timezone==='UTC'&&q.dateBasis==='occurred_at'&&/^[A-Z]{3}$/.test(q.currency)&&Number.isInteger(q.exponent)&&q.exponent>=0&&q.exponent<=4&&typeof q.basis==='string'&&q.basis.trim()&&q.basis.length<=200,'scope_invalid',400);return {...q,start:iso(q.start),end:iso(q.end)};}
async function problemState(s,p){
 const snap=p.provenance?.snapshot;
 if(!snap||snap.state!=='active'||!Array.isArray(snap.embeddingIds)||!snap.embeddingIds.length)return {valid:false,reason:'problem_evidence_unavailable'};
 try{for(const id of snap.embeddingIds){const m=await one(s,'SELECT extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1 AND embedding_id=$2 AND problem_id=$3',[s.tenantId,id,p.problem_id]);requireValue(m,'problem_evidence_unavailable');await evidence(s,m.extraction_run_id);}return {valid:true,reason:null};}
 catch(e){if(e instanceof EconomicError||e instanceof DomainError&&e.code==='source_unavailable'||e.message==='EVIDENCE_UNAVAILABLE')return {valid:false,reason:'problem_evidence_unavailable'};throw e;}
}
const entry=r=>({id:r.entity_id,rowId:r.id,revision:r.revision,sourceId:r.source_id,actorId:r.actor_id,actorActive:r.actor_active,externalId:r.external_id,kind:r.kind,status:r.status,effectiveAt:iso(r.effective_at),recordedAt:iso(r.recorded_at),currency:r.currency,exponent:r.exponent,basis:r.basis,amountMinor:r.amount_minor===null?null:String(r.amount_minor).replace(/\.0+$/,''),orderId:r.order_id,reversalOf:r.reversal_of,details:r.details});
const source=r=>({id:r.source_id,version:r.version,active:r.active&&r.actor_active,actorActive:r.actor_active,evidenceType:r.evidence_type,complete:r.complete,windowStart:iso(r.window_start),windowEnd:iso(r.window_end),watermark:iso(r.watermark)});
const compatible=(a,b)=>a&&b&&['currency','exponent','basis','amountMinor','status','effectiveAt'].every(k=>a[k]===b[k]);
async function state(s){
 const sources=(await latestRows(s,'economic_source_versions','source_id')).map(source);
 const entries=(await s.query('SELECT DISTINCT ON(entity_id) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.economic_ledger_entries WHERE tenant_id=$1 ORDER BY entity_id,revision DESC',[s.tenantId])).rows.map(entry);
 const byId=new Map(entries.map(e=>[e.id,e])),sourceById=new Map(sources.map(r=>[r.id,r]));
 const usable=e=>!!e&&e.actorActive&&sourceById.get(e.sourceId)?.active;
 const problems=(await s.query("SELECT DISTINCT ON(problem_id) * FROM public.problem_versions WHERE tenant_id=$1 AND provenance->>'kind'='vector-problem-v1' ORDER BY problem_id,version DESC",[s.tenantId])).rows;
 for(const p of problems)Object.assign(p,await problemState(s,p));
 const problemById=new Map(problems.map(p=>[p.problem_id,p]));
 const rawLinks=await latestRows(s,'economic_problem_links','problem_id,entity_id');
 const relations=rawLinks.map(r=>{const e=byId.get(r.entity_id),valid=!!(r.actor_active&&usable(e)&&problemById.get(r.problem_id)?.valid);return {id:r.id,problemId:r.problem_id,entityId:r.entity_id,ledgerRowId:r.ledger_row_id,kind:e?.kind??'unknown',version:r.version,active:r.active,valid,reason:valid?null:'relation_evidence_unavailable',report:valid?r.report:null};});
 const rawAliases=await latestRows(s,'economic_order_aliases','alias_entity_id');
 const aliases=rawAliases.map(r=>{const a=byId.get(r.alias_entity_id),b=byId.get(r.canonical_entity_id);const valid=!!(r.actor_active&&usable(a)&&usable(b)&&compatible(a,b));return {id:r.id,aliasEntityId:r.alias_entity_id,canonicalEntityId:r.canonical_entity_id,aliasRowId:r.alias_row_id,canonicalRowId:r.canonical_row_id,version:r.version,active:r.active,valid,reason:valid?null:'alias_identity_unavailable_or_conflicting',report:valid?r.report:null};});
 const rawCustomers=await latestRows(s,'economic_order_customers','entity_id');
 const customerBindings=rawCustomers.map(r=>{const valid=!!(r.actor_active&&usable(byId.get(r.entity_id)));return {id:r.id,entityId:r.entity_id,orderRowId:r.order_row_id,customerKey:valid?r.customer_key:null,version:r.version,valid,reason:valid?null:'customer_evidence_unavailable',report:valid?r.report:null};});
 return {sources,entries,byId,usable,problems,problemById,relations,aliases,customerBindings,rawLinks,rawAliases,rawCustomers};
}
const baseRow=(s,e)=>({id:e.id,tenantId:s.tenantId,sourceAccount:e.sourceId,externalId:e.externalId,sourceRevision:String(e.revision),occurredAt:e.effectiveAt,recordedAt:e.recordedAt,currency:e.currency,exponent:e.exponent,basis:e.basis,amountMinor:e.amountMinor,status:e.status,provenance:'approved_manual',evidenceRef:e.rowId});
const gateMetric=(m,reason,identity=false)=>{m.amountMinor=null;m.status=identity?'unavailable':m.totalCount?'partial':'unavailable';if(identity)m.knownSubtotalMinor=null;m.missingReasons=[...new Set([...m.missingReasons,reason])].sort();return m;};
const uniq=x=>[...new Set(x)].sort();
/** Pure approved adapter arithmetic; repository supplies authorized canonical identities. */
export function calculateExposure(input){const result=adaptLedger(input);return {canonicalAllOrders:result.metrics.allOrders,...result.metrics.exposure,membership:input.links.map(l=>({problemId:l.problemId,orderId:l.orderId})),warning:'Las filas por problema no son aditivas. El global usa la unión de órdenes.'};}
async function build(s,scope,st){
 const asOf=iso((await one(s,'SELECT transaction_timestamp() AS now',[])).now);
 const inputHash=hash({scope,entries:st.entries.map(e=>[e.rowId,e.actorActive]),sources:st.sources,relations:st.relations.map(r=>[r.id,r.valid]),aliases:st.aliases.map(r=>[r.id,r.valid]),customers:st.customerBindings.map(r=>[r.id,r.valid]),problems:st.problems.map(p=>[p.problem_id,p.version,p.valid])});
 const cov=await one(s,'SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.economic_relation_coverage WHERE tenant_id=$1 AND scope_key=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,hash(scope)]);
 const current=!!(cov&&cov.actor_active&&cov.input_hash===inputHash&&canonical(cov.scope)===canonical(scope));
 const coverage=cov?{version:cov.version,complete:cov.complete,current,report:cov.actor_active?cov.report:null,reason:current?cov.complete?null:'relations_not_complete':'coverage_stale_or_revoked'}:null;
 const covered=!!(current&&cov.complete);
 const aliases=new Map(st.aliases.filter(a=>a.active&&a.valid).map(a=>[a.aliasEntityId,a.canonicalEntityId]));
 const canonicalId=id=>{const seen=new Set();while(aliases.has(id)){requireValue(!seen.has(id),'alias_cycle');seen.add(id);id=aliases.get(id);}return id;};
 const allOrders=st.entries.filter(e=>e.kind==='order'&&st.usable(e));const canonicalOrders=new Map();for(const e of allOrders){const id=canonicalId(e.id);canonicalOrders.set(id,st.byId.get(id));}
 const validRelations=st.relations.filter(r=>r.active&&r.valid);
 const linkMap=new Map();for(const r of validRelations.filter(r=>r.kind==='order')){const l={tenantId:s.tenantId,problemId:r.problemId,orderId:canonicalId(r.entityId),evidenceRef:r.id,relationVersion:String(r.version)};linkMap.set(l.problemId+':'+l.orderId,l);}
 const links=[...linkMap.values()].sort((a,b)=>canonical(a).localeCompare(canonical(b)));
 const familySources=type=>st.sources.filter(x=>x.evidenceType===type&&x.active).map(x=>({sourceAccount:x.id,watermark:x.watermark,complete:x.complete&&x.windowStart<=scope.start&&x.windowEnd>=scope.end&&x.watermark>=scope.end}));
 const input={authorization:{tenantId:s.tenantId,permissionsVersion:String(s.permissionsVersion)},snapshot:{tenantId:s.tenantId,id:'economic-exposure:'+inputHash,asOf,sources:familySources('order_export')},scope,orders:[...canonicalOrders.values()].map(e=>baseRow(s,e)),events:[],links};
 const {canonicalAllOrders,...metrics}=calculateExposure(input);
 const badIdentity=st.aliases.some(a=>a.active&&!a.valid),badRelations=st.relations.some(r=>r.active&&!r.valid);
 if(badIdentity)gateMetric(canonicalAllOrders,'alias_identity_unavailable_or_conflicting',true);if(st.sources.some(x=>x.evidenceType==='order_export'&&!x.active)||st.entries.some(e=>e.kind==='order'&&!st.usable(e)))gateMetric(canonicalAllOrders,'order_evidence_unavailable');if(!familySources('order_export').length)canonicalAllOrders.knownSubtotalMinor=null;
 for(const m of [metrics.global,...Object.values(metrics.byProblem)]){if(!covered)gateMetric(m,'relation_coverage_unconfirmed');if(badRelations)gateMetric(m,'relation_evidence_unavailable');if(badIdentity)gateMetric(m,'alias_identity_unavailable_or_conflicting',true);}
 const selectedOrders=[...canonicalOrders.values()].filter(e=>e.currency===scope.currency&&e.exponent===scope.exponent&&e.basis===scope.basis&&e.effectiveAt>=scope.start&&e.effectiveAt<scope.end&&e.recordedAt<=asOf&&!['pending','cancelled'].includes(e.status));
 const selectedIds=new Set(selectedOrders.map(e=>e.id));metrics.membership=links.filter(l=>selectedIds.has(l.orderId)).map(l=>({problemId:l.problemId,orderId:l.orderId}));
 const customerMap=new Map();for(const c of st.customerBindings.filter(c=>c.valid&&c.customerKey!==null)){const id=canonicalId(c.entityId);const set=customerMap.get(id)??new Set();set.add(c.customerKey);customerMap.set(id,set);}
 const orderFamily=st.sources.filter(x=>x.evidenceType==='order_export');const orderIdentityCoverage=orderFamily.length>0&&orderFamily.every(x=>x.active&&x.complete&&x.windowStart<=scope.start&&x.windowEnd>=scope.end&&x.watermark>=scope.end)&&scope.end<=asOf;
 const customers=ids=>{const customerKeys=new Set();let knownOrderCount=0;for(const id of ids){const set=customerMap.get(id);if(set?.size===1){knownOrderCount++;customerKeys.add([...set][0]);}}const known=uniq([...customerKeys]),complete=covered&&orderIdentityCoverage&&!badIdentity&&!badRelations&&knownOrderCount===ids.length;return {count:complete?known.length:null,knownCount:known.length,knownOrderCount,totalOrderCount:ids.length,status:complete?'complete':ids.length?'partial':'unavailable',customerKeys:known};};
 const problemIds=uniq(validRelations.map(r=>r.problemId));const orderIdsFor=p=>uniq(metrics.membership.filter(l=>p===null||l.problemId===p).map(l=>l.orderId));
 metrics.customerExposure={global:customers(orderIdsFor(null)),byProblem:Object.fromEntries(problemIds.map(p=>[p,customers(orderIdsFor(p))]))};
 const eventFor=p=>{const orderIds=new Set(orderIdsFor(p)),ids=new Set(validRelations.filter(r=>r.kind!=='order'&&(p===null||r.problemId===p)).map(r=>r.entityId));for(const e of st.entries.filter(e=>kinds.includes(e.kind)&&e.kind!=='order'&&e.orderId&&orderIds.has(canonicalId(e.orderId))))ids.add(e.id);
 // Reversal membership follows its original, and directly linked reversals retain originals.
 let changed=true;while(changed){changed=false;for(const e of st.entries.filter(e=>e.kind==='reversal')){if(ids.has(e.id)&&e.reversalOf&&!ids.has(e.reversalOf)){ids.add(e.reversalOf);changed=true;}if(ids.has(e.reversalOf)&&!ids.has(e.id)){ids.add(e.id);changed=true;}}}
 const chosen=st.entries.filter(e=>ids.has(e.id)&&st.usable(e));const financial=chosen.filter(e=>['refund','reversal'].includes(e.kind));const rb=adaptLedger({...input,snapshot:{...input.snapshot,sources:familySources('payment_ledger')},orders:[],links:[],events:financial.map(e=>({...baseRow(s,e),kind:e.kind,reversalOf:e.reversalOf}))}).metrics.refunds;
 const components=separateComponents({entries:chosen,sources:st.sources,scope,asOf});for(const m of [rb,components.replacement,components.supportModel]){if(!covered)gateMetric(m,'relation_coverage_unconfirmed');if(badRelations||chosen.length<ids.size)gateMetric(m,'event_evidence_unavailable');if(chosen.some(e=>e.orderId&&(!st.usable(st.byId.get(e.orderId))||st.byId.get(e.orderId).kind!=='order'||st.byId.get(e.orderId).currency!==e.currency||st.byId.get(e.orderId).exponent!==e.exponent||st.byId.get(e.orderId).basis!==e.basis)))gateMetric(m,'event_order_reference_unavailable_or_incompatible');if(badIdentity)gateMetric(m,'alias_identity_unavailable_or_conflicting',true);}
 return {refunds:rb,replacement:components.replacement,supportModel:components.supportModel,eventIds:uniq(chosen.filter(e=>e.currency===scope.currency&&e.exponent===scope.exponent&&e.basis===scope.basis&&e.effectiveAt>=scope.start&&e.effectiveAt<scope.end&&e.recordedAt<=asOf&&!['pending','cancelled'].includes(e.status)).map(e=>e.id))};};
 metrics.eventUnion={global:eventFor(null),byProblem:Object.fromEntries(problemIds.map(p=>[p,eventFor(p)])),problemRowsAreAdditive:false};
 return {inputHash,scope,canonicalAllOrders,coverage,relations:st.relations,aliases:st.aliases,customerBindings:st.customerBindings,problemOptions:st.problems.filter(p=>p.valid).map(p=>({id:p.problem_id,label:p.provenance.snapshot.label,version:p.version})),metrics};
}
export async function readExposure(s,{scope}){scope=normalizeScope(scope);return build(s,scope,await state(s));}
const writeLock=async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':economic-ledger']);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':economic-relations']);};
export function createExposureRepository({database}){
 const transact=async work=>{let own;try{return await database.transaction('configure',async s=>{await writeLock(s);try{return await work(s);}catch(e){if(e instanceof EconomicError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}};
 const recordRow=async(s,id,allowed,active=true)=>{const r=await one(s,'SELECT * FROM public.economic_ledger_entries WHERE tenant_id=$1 AND id=$2',[s.tenantId,id]);requireValue(r&&allowed.includes(r.kind),'ledger_row_unavailable',404);if(active){const valid=await one(s,'SELECT public.economic_record_current($1,$2,$3::text[]) AS valid',[s.tenantId,id,allowed]);requireValue(valid.valid,'ledger_row_not_current_or_authorized');}return r;};
 const version=(previous,q)=>requireValue((previous?.version??0)===q.expectedVersion,'relation_version_conflict');
 const api={
 async record(q){requireValue(keys(q,[...common,'problemId','ledgerRowId','active'])&&report(q)&&uuid(q.problemId)&&uuid(q.ledgerRowId)&&typeof q.active==='boolean','relation_invalid',400);return transact(async s=>{const row=await recordRow(s,q.ledgerRowId,kinds,q.active);if(q.active){const p=await one(s,"SELECT * FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 AND provenance->>'kind'='vector-problem-v1' ORDER BY version DESC LIMIT 1",[s.tenantId,q.problemId]);requireValue(p,'problem_unavailable',404);requireValue((await problemState(s,p)).valid,'problem_evidence_unavailable');}const previous=await one(s,'SELECT version FROM public.economic_problem_links WHERE tenant_id=$1 AND problem_id=$2 AND entity_id=$3 ORDER BY version DESC LIMIT 1',[s.tenantId,q.problemId,row.entity_id]);version(previous,q);const r=await one(s,'INSERT INTO public.economic_problem_links(tenant_id,problem_id,entity_id,ledger_row_id,version,active,actor_id,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) RETURNING *',[s.tenantId,q.problemId,row.entity_id,row.id,q.expectedVersion+1,q.active,s.userId,q.report]);return {id:r.id,problemId:r.problem_id,entityId:r.entity_id,ledgerRowId:r.ledger_row_id,kind:row.kind,version:r.version,active:r.active,valid:true,reason:null,report:r.report};});},
 async recordAlias(q){requireValue(keys(q,[...common,'aliasRowId','canonicalRowId','active'])&&report(q)&&uuid(q.aliasRowId)&&uuid(q.canonicalRowId)&&typeof q.active==='boolean','alias_invalid',400);return transact(async s=>{const a=await recordRow(s,q.aliasRowId,['order'],q.active),b=await recordRow(s,q.canonicalRowId,['order'],q.active);requireValue(a.entity_id!==b.entity_id,'alias_self_invalid',400);if(q.active)requireValue(compatible(entry({...a,actor_active:true}),entry({...b,actor_active:true})),'alias_financial_conflict');const previous=await one(s,'SELECT version FROM public.economic_order_aliases WHERE tenant_id=$1 AND alias_entity_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,a.entity_id]);version(previous,q);const r=await one(s,'INSERT INTO public.economic_order_aliases(tenant_id,alias_entity_id,canonical_entity_id,alias_row_id,canonical_row_id,version,active,actor_id,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true) RETURNING *',[s.tenantId,a.entity_id,b.entity_id,a.id,b.id,q.expectedVersion+1,q.active,s.userId,q.report]);return {id:r.id,aliasEntityId:r.alias_entity_id,canonicalEntityId:r.canonical_entity_id,aliasRowId:r.alias_row_id,canonicalRowId:r.canonical_row_id,version:r.version,active:r.active,valid:true,reason:null,report:r.report};});},
 async recordCustomer(q){requireValue(keys(q,[...common,'orderRowId','customerKey'])&&report(q)&&uuid(q.orderRowId)&&(q.customerKey===null||typeof q.customerKey==='string'&&q.customerKey.trim()===q.customerKey&&q.customerKey.length>0&&q.customerKey.length<=200),'customer_invalid',400);return transact(async s=>{const a=await recordRow(s,q.orderRowId,['order'],q.customerKey!==null);const previous=await one(s,'SELECT version FROM public.economic_order_customers WHERE tenant_id=$1 AND entity_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,a.entity_id]);version(previous,q);const r=await one(s,'INSERT INTO public.economic_order_customers(tenant_id,entity_id,order_row_id,customer_key,version,actor_id,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,true) RETURNING *',[s.tenantId,a.entity_id,a.id,q.customerKey,q.expectedVersion+1,s.userId,q.report]);return {id:r.id,entityId:r.entity_id,orderRowId:r.order_row_id,customerKey:r.customer_key,version:r.version,valid:true,reason:null,report:r.report};});},
 async recordCoverage(q){requireValue(keys(q,[...common,'scope','expectedInputHash','complete'])&&report(q)&&typeof q.expectedInputHash==='string'&&/^[a-f0-9]{64}$/.test(q.expectedInputHash)&&typeof q.complete==='boolean','coverage_invalid',400);const scope=normalizeScope(q.scope);return transact(async s=>{const view=await readExposure(s,{scope});requireValue(view.inputHash===q.expectedInputHash,'coverage_input_conflict');version(view.coverage,q);requireValue(!q.complete||Date.parse(scope.end)<=Date.now(),'coverage_window_open');await s.query('INSERT INTO public.economic_relation_coverage(tenant_id,scope_key,input_hash,scope,version,complete,actor_id,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true)',[s.tenantId,hash(scope),q.expectedInputHash,JSON.stringify(scope),q.expectedVersion+1,q.complete,s.userId,q.report]);return {version:q.expectedVersion+1,complete:q.complete,current:true,report:q.report,reason:q.complete?null:'relations_not_complete'};});}
 };return api;
}
