import type {EconomicScope} from './repository.mjs';
import type {Money} from './money.mjs';
export type PriorityPolicy={id:string;version:number;name:string;weights:{impact:number;frequency:number;severity:number;actionability:number};frequencyBaseline:number;impactBaselineMinor:string;currency:string;exponent:number;formulaVersion:string;report:string;createdAt:string};
export type Actionability={id:string;problemId:string;problemVersion:number;version:number;level:'unknown'|'low'|'medium'|'high';report:string;createdAt:string};
export type PriorityEntry={problemId:string;problemVersion:number;label:string;rank:number;criticalLane:boolean;scoreKnownBps:number;scoreUpperBps:number;status:'complete'|'partial';contributions:{impact:number|null;frequency:number;severity:number|null;actionability:number|null};inputs:{impact:Money|null;uniqueIssueCount:number;severity:string;actionability:string};reasons:string[];delta:{previousScoreKnownBps:number|null;scoreKnownChange:number|null;reasons:string[]};evidenceRunIds:string[]};
export type PriorityRun={id:string;version:number;snapshotId:string;scopeHash:string;policyId:string;inputHash:string;contentHash:string;formulaVersion:string;createdAt:string;previousRunId:string|null;entries:PriorityEntry[];kind:'heuristic-not-probability'};
export type PriorityView={snapshotId:string;scopeHash:string;scope:EconomicScope;policies:PriorityPolicy[];policyVersion:number;actionability:Actionability[];problemOptions:{id:string;version:number;label:string;criticalLane:boolean;actionabilityVersion:number}[];latestRun:PriorityRun|null;latestRunUnavailable:boolean;expectedPreviousRunId:string|null;stale:boolean;canWrite:boolean};
export function priority(problem:any,policy:any):any;
export function createPriorityRepository(options:{database:any}):{recordPolicy(input:any):Promise<PriorityPolicy>;recordActionability(input:any):Promise<Actionability>;rank(input:{snapshotId:string;policyId:string;expectedPreviousRunId:string|null}):Promise<PriorityRun>;view(input:{snapshotId:string}):Promise<PriorityView>};
