import {randomUUID} from 'node:crypto';
import {hash,stableId,DomainError} from '../problems/contracts.mjs';
import {EconomicError} from './repository.mjs';
import {createSnapshotRepository} from './snapshots.mjs';
import {createProblemRepository,evidence} from '../problems/repository.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
const FORMULA='weighted-priority-v1';
const check=(ok,code,status=409)=>{if(!ok)throw new EconomicError(code,status);};
const uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(x);
const keys=(q,a)=>q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>a.includes(k));
const text=(v,n=4000)=>typeof v==='string'&&v.trim().length>=20&&v.length<=n;
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];const versionHead=async(s,kind,id=null)=>(await one(s,'SELECT public.priority_version_head($1,$2,$3) AS head',[s.tenantId,kind,id])).head;const scoped=s=>({transaction:async(_a,fn)=>fn(s)});const iso=x=>new Date(x).toISOString();
// Reused ordinal severity and distinct-issue frequency from reviewed bank 5fbf2230.
const SEVERITY={unknown:null,low:10,medium:25,high:45,critical:60};
const order=['unknown','low','medium','high','critical'];
const ratio=(value,baseline,weight)=>Number((BigInt(value)>=BigInt(baseline)?BigInt(weight):BigInt(value)*BigInt(weight)/BigInt(baseline)));
export function priority(problem,policy){check(Object.hasOwn(SEVERITY,problem.severity),'priority_severity_invalid',400);const count=new Set(problem.issueIds).size,weights=policy.weights,amount=problem.impact?.amount_minor??null,subtotal=problem.impact?.known_subtotal??null;const compatible=problem.impact?.currency===policy.currency&&problem.impact?.exponent===policy.exponent;const known=compatible?(amount??(problem.impact?.coverage?.known_n>0?subtotal:null)):null;const impact=known===null?null:ratio(known,policy.impactBaselineMinor,weights.impact);const severity=SEVERITY[problem.severity]===null?null:Math.floor(weights.severity*SEVERITY[problem.severity]/60);const actionability={unknown:null,low:2500,medium:5000,high:10000}[problem.actionability];check(actionability!==undefined,'priority_actionability_invalid',400);const contributions={impact,frequency:ratio(count,policy.frequencyBaseline,weights.frequency),severity,actionability:actionability===null?null:Math.floor(weights.actionability*actionability/10000)};const missing={impact:amount===null||!compatible,severity:severity===null,actionability:actionability===null};const scoreKnownBps=Object.values(contributions).reduce((n,v)=>n+(v??0),0),scoreUpperBps=scoreKnownBps+Object.entries(missing).reduce((n,[k,v])=>n+(v?weights[k]-(contributions[k]??0):0),0);return {criticalLane:problem.criticalLane,scoreKnownBps,scoreUpperBps,status:Object.values(missing).some(Boolean)?'partial':'complete',contributions,reasons:[`severity:${problem.severity}`,`unique_issues:${count}`,`frequency_baseline:${policy.frequencyBaseline}`,`impact_baseline:${policy.impactBaselineMinor}:${policy.currency}:${policy.exponent}`,`actionability:${problem.actionability}`,...(missing.impact?['impact_unknown_or_partial_no_zero_imputation']:[]),...(problem.criticalLane?['human_safety_review_independent_of_money']:[])],kind:'heuristic-not-probability'};}
const policyView=r=>({id:r.id,version:r.version,name:r.name,weights:r.weights,frequencyBaseline:r.frequency_baseline,impactBaselineMinor:String(r.impact_baseline_minor),currency:r.currency,exponent:r.exponent,formulaVersion:r.formula_version,report:r.report,createdAt:iso(r.created_at)});
const actionView=r=>({id:r.id,problemId:r.problem_id,problemVersion:r.problem_version,version:r.version,level:r.level,report:r.report,createdAt:iso(r.created_at)});
async function inputs(s,snapshot){const list=await createProblemRepository({database:scoped(s)}).list(),items=[];const actions=(await s.query(`SELECT DISTINCT ON(problem_id) * FROM public.priority_actionability_versions WHERE tenant_id=$1 AND id=(public.priority_version_head(tenant_id,'actionability',problem_id)->>'id')::uuid ORDER BY problem_id,version DESC`,[s.tenantId])).rows;for(const p of list.filter(p=>p.state==='active')){const members=(await s.query('SELECT m.extraction_run_id,e.message_revision_id FROM public.problem_embedding_members m JOIN public.embeddings e ON e.tenant_id=m.tenant_id AND e.id=m.embedding_id WHERE m.tenant_id=$1 AND m.embedding_id=ANY($2::uuid[]) ORDER BY m.extraction_run_id,e.message_revision_id',[s.tenantId,p.embeddingIds])).rows;const runIds=[...new Set(members.map(m=>m.extraction_run_id))].sort(),issueIds=[],severities=[],categories=[];for(const id of runIds){const result=await evidence(s,id);const revisions=new Set(members.filter(m=>m.extraction_run_id===id).map(m=>m.message_revision_id));const relevant=result.issues.filter(issue=>issue.evidence.some(span=>revisions.has(span.message_revision_id)));for(const issue of relevant){severities.push(issue.severity);categories.push(issue.category);}
 const rows=(await s.query('SELECT DISTINCT i.id,i.category,i.severity FROM public.issues i JOIN public.evidence_spans e ON e.tenant_id=i.tenant_id AND e.issue_id=i.id WHERE i.tenant_id=$1 AND i.extraction_run_id=$2 AND e.message_revision_id=ANY($3::uuid[]) ORDER BY i.id',[s.tenantId,id,[...revisions]])).rows;for(const row of rows)if(relevant.some(i=>i.category===row.category&&i.severity===row.severity))issueIds.push(row.id);}
 const severity=order.filter(level=>severities.includes(level)).at(-1)??'unknown',criticalLane=['high','critical'].includes(severity)||categories.some(c=>/safety|privacy|fraud|seguridad|privacidad|humo|smoke|fire|incendio|quemadura/i.test(c));const action=actions.find(a=>a.problem_id===p.id&&a.problem_version===p.version);const impact=snapshot.components.find(c=>c.metric==='exposure.'+p.id&&c.currency===snapshot.scope.currency&&!c.conversion)?.money??null;items.push({problemId:p.id,problemVersion:p.version,label:p.label,issueIds:[...new Set(issueIds)].sort(),severity,criticalLane,actionability:action?.level??'unknown',actionabilityId:action?.id??null,evidenceRunIds:runIds,impact});}return {items,actions:actions.map(actionView)};}
async function snapshotFor(s,id){const snap=await createSnapshotRepository({database:scoped(s)}).get({snapshotId:id});check(snap.status==='published','priority_published_snapshot_required');return snap;}
async function loadRun(s,id,snapshot){const run=await one(s,"SELECT * FROM public.priority_runs WHERE tenant_id=$1 AND id=$2 AND status='published'",[s.tenantId,id]);check(run&&run.snapshot_id===snapshot.id&&run.scope_hash===snapshot.scopeHash,'priority_run_unavailable',404);const policy=await one(s,'SELECT * FROM public.priority_policy_versions WHERE tenant_id=$1 AND id=$2',[s.tenantId,run.policy_id]);check(policy,'priority_policy_unavailable',403);const rows=(await s.query('SELECT * FROM public.priority_entries WHERE tenant_id=$1 AND run_id=$2 ORDER BY rank',[s.tenantId,id])).rows;check(rows.length===run.entry_count,'priority_integrity_failed');const digest=await one(s,'SELECT public.priority_digest($1,$2) AS hash',[s.tenantId,id]);check(digest.hash===run.content_hash,'priority_integrity_failed');const repo=createEvidenceRepository({database:scoped(s)});for(const row of rows){for(const runId of row.evidence_run_ids){try{await repo.get(runId);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')throw new EconomicError('priority_evidence_unavailable',403);throw e;}}if(row.actionability_id)check(await one(s,'SELECT id FROM public.priority_actionability_versions WHERE tenant_id=$1 AND id=$2',[s.tenantId,row.actionability_id]),'priority_assessment_unavailable',403);}
 return {id:run.id,version:run.version,snapshotId:run.snapshot_id,scopeHash:run.scope_hash,policyId:run.policy_id,inputHash:run.input_hash,contentHash:run.content_hash,formulaVersion:policy.formula_version,createdAt:iso(run.created_at),previousRunId:run.previous_run_id,entries:rows.map(r=>({problemId:r.problem_id,problemVersion:r.problem_version,label:r.label,rank:r.rank,criticalLane:r.critical_lane,scoreKnownBps:r.score_known_bps,scoreUpperBps:r.score_upper_bps,status:r.status,contributions:r.contributions,inputs:r.inputs,reasons:r.reasons,delta:r.delta,evidenceRunIds:r.evidence_run_ids})),kind:'heuristic-not-probability'};
}
export function createPriorityRepository({database}){const tx=async(action,work)=>{let domain;try{return await database.transaction(action,async s=>{try{return await work(s);}catch(e){if(e instanceof EconomicError||e instanceof DomainError)domain=e;throw e;}});}catch(e){if(domain)throw domain;throw e;}};return {
 async recordPolicy(q){check(keys(q,['expectedVersion','name','weights','frequencyBaseline','impactBaselineMinor','currency','exponent','report','attested'])&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&typeof q.name==='string'&&q.name.trim()&&q.name.length<=200&&keys(q.weights,['impact','frequency','severity','actionability'])&&Object.keys(q.weights).length===4&&Object.values(q.weights).every(x=>Number.isInteger(x)&&x>=0&&x<=10000)&&Object.values(q.weights).reduce((a,b)=>a+b,0)===10000&&Number.isInteger(q.frequencyBaseline)&&q.frequencyBaseline>0&&q.frequencyBaseline<=1000000&&typeof q.impactBaselineMinor==='string'&&/^[1-9][0-9]{0,4095}$/.test(q.impactBaselineMinor)&&/^[A-Z]{3}$/.test(q.currency)&&Number.isInteger(q.exponent)&&q.exponent>=0&&q.exponent<=4&&text(q.report)&&q.attested===true,'priority_policy_invalid',400);return tx('configure',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':priority-policy']);const previous=await versionHead(s,'policy');check((previous?.version??0)===q.expectedVersion,'priority_policy_conflict');return policyView(await one(s,'INSERT INTO public.priority_policy_versions(tenant_id,version,actor_id,name,weights,frequency_baseline,impact_baseline_minor,currency,exponent,formula_version,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true) RETURNING *',[s.tenantId,q.expectedVersion+1,s.userId,q.name,JSON.stringify(q.weights),q.frequencyBaseline,q.impactBaselineMinor,q.currency,q.exponent,FORMULA,q.report]));});},
 async recordActionability(q){check(keys(q,['problemId','expectedProblemVersion','expectedVersion','level','report','attested'])&&uuid(q.problemId)&&Number.isInteger(q.expectedProblemVersion)&&q.expectedProblemVersion>0&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&['unknown','low','medium','high'].includes(q.level)&&text(q.report)&&q.attested===true,'priority_assessment_invalid',400);return tx('configure',async s=>{const p=await createProblemRepository({database:scoped(s)}).detail({problemId:q.problemId});check(p.version===q.expectedProblemVersion&&p.state==='active','priority_problem_version_conflict');const row=await one(s,'INSERT INTO public.priority_actionability_versions(tenant_id,problem_id,problem_version,version,actor_id,level,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,true) RETURNING *',[s.tenantId,p.id,p.version,q.expectedVersion+1,s.userId,q.level,q.report]);return actionView(row);});},
 async view(q){check(keys(q,['snapshotId'])&&uuid(q.snapshotId),'priority_snapshot_invalid',400);return tx('read',async s=>{const snapshot=await snapshotFor(s,q.snapshotId),policies=(await s.query('SELECT * FROM public.priority_policy_versions WHERE tenant_id=$1 ORDER BY version DESC',[s.tenantId])).rows.map(policyView),current=await inputs(s,snapshot),latest=await versionHead(s,'run',snapshot.id),policyHead=await versionHead(s,'policy');let run=null,unavailable=false;if(latest){try{run=await loadRun(s,latest.id,snapshot);}catch(e){if(e instanceof EconomicError&&[403,404].includes(e.status))unavailable=true;else throw e;}}const nowHash=run?hash({snapshotId:snapshot.id,contentHash:snapshot.contentHash,policyId:run.policyId,items:current.items,formula:FORMULA}):null;const options=[];for(const p of current.items)options.push({id:p.problemId,version:p.problemVersion,label:p.label,criticalLane:p.criticalLane,actionabilityVersion:(await versionHead(s,'actionability',p.problemId))?.version??0});return {snapshotId:snapshot.id,scopeHash:snapshot.scopeHash,scope:snapshot.scope,policies,policyVersion:policyHead?.version??0,actionability:current.actions,problemOptions:options,latestRun:run,latestRunUnavailable:unavailable,expectedPreviousRunId:latest?.id??null,stale:!!(run&&(run.inputHash!==nowHash||policyHead?.id!==run.policyId)),canWrite:s.role==='owner'};});},
 async rank(q){check(keys(q,['snapshotId','policyId','expectedPreviousRunId'])&&uuid(q.snapshotId)&&uuid(q.policyId)&&(q.expectedPreviousRunId===null||uuid(q.expectedPreviousRunId)),'priority_rank_invalid',400);return tx('import',async s=>{check(s.role==='owner','priority_owner_required',403);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':priority-rank:'+q.snapshotId]);const snapshot=await snapshotFor(s,q.snapshotId),policyRow=await one(s,'SELECT * FROM public.priority_policy_versions WHERE tenant_id=$1 AND id=$2',[s.tenantId,q.policyId]);check(policyRow,'priority_policy_unavailable',404);const policy=policyView(policyRow);check(policy.currency===snapshot.scope.currency&&policy.exponent===snapshot.scope.exponent,'priority_policy_currency_mismatch');const current=await inputs(s,snapshot),inputHash=hash({snapshotId:snapshot.id,contentHash:snapshot.contentHash,policyId:policy.id,items:current.items,formula:FORMULA});const previousRow=await versionHead(s,'run',snapshot.id);let previous=null;if(previousRow){try{previous=await loadRun(s,previousRow.id,snapshot);}catch(e){if(!(e instanceof EconomicError&&[403,404].includes(e.status)))throw e;}}if(previous?.inputHash===inputHash)return previous;check((previousRow?.id??null)===q.expectedPreviousRunId,'priority_run_version_conflict');const id=stableId({tenant:s.tenantId,snapshot:snapshot.id,inputHash,previousRunId:previousRow?.id??null});const scored=current.items.map(p=>({...p,...priority(p,policy)})).sort((a,b)=>Number(b.criticalLane)-Number(a.criticalLane)||b.scoreKnownBps-a.scoreKnownBps||a.problemId.localeCompare(b.problemId));await s.query("INSERT INTO public.priority_runs(id,tenant_id,snapshot_id,scope_hash,policy_id,previous_run_id,version,actor_id,input_hash,content_hash,status,entry_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'draft',$11)",[id,s.tenantId,snapshot.id,snapshot.scopeHash,policy.id,previousRow?.id??null,(previousRow?.version??0)+1,s.userId,inputHash,'0'.repeat(64),scored.length]);
 for(let index=0;index<scored.length;index++){const p=scored[index],old=previous?.entries.find(x=>x.problemId===p.problemId);const delta={previousScoreKnownBps:old?.scoreKnownBps??null,scoreKnownChange:old?p.scoreKnownBps-old.scoreKnownBps:null,reasons:[...(previousRow&&!previous?['previous_ranking_evidence_unavailable']:[]),...(previous&&previous.policyId!==policy.id?['policy_version_changed']:[]),...(old&&old.problemVersion!==p.problemVersion?['problem_evidence_version_changed']:[]),...(!old?['new_problem_in_ranking']:[]),...(old&&old.inputs.actionability!==p.actionability?['human_actionability_changed']:[])]};await s.query('INSERT INTO public.priority_entries(id,tenant_id,run_id,problem_id,problem_version,rank,critical_lane,score_known_bps,score_upper_bps,status,contributions,inputs,reasons,delta,label,evidence_run_ids,actionability_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)',[stableId({id,problem:p.problemId}),s.tenantId,id,p.problemId,p.problemVersion,index+1,p.criticalLane,p.scoreKnownBps,p.scoreUpperBps,p.status,JSON.stringify(p.contributions),JSON.stringify({impact:p.impact,uniqueIssueCount:p.issueIds.length,issueIds:p.issueIds,severity:p.severity,actionability:p.actionability}),JSON.stringify(p.reasons),JSON.stringify(delta),p.label,p.evidenceRunIds,p.actionabilityId]);}
 check(hash({snapshotId:snapshot.id,contentHash:snapshot.contentHash,policyId:policy.id,items:(await inputs(s,snapshot)).items,formula:FORMULA})===inputHash,'priority_inputs_changed');await s.query("UPDATE public.priority_runs SET content_hash=public.priority_digest(tenant_id,id),status='published' WHERE tenant_id=$1 AND id=$2",[s.tenantId,id]);return loadRun(s,id,snapshot);});}
 };}
