import {randomUUID,createHash} from 'node:crypto';
import {adaptLedger} from '../economics/adapter.mjs';
import {separateComponents} from './components.mjs';
export class EconomicError extends Error{constructor(code,status=409){super(code);this.code=code;this.status=status;}}
const check=(ok,code,status=400)=>{if(!ok)throw new EconomicError(code,status);};
const uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(x);
const text=(x,max=200)=>typeof x==='string'&&x.trim().length>0&&x.length<=max;
const instant=x=>{if(typeof x!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(x)||!Number.isFinite(Date.parse(x)))return false;const normalized=x.includes('.')?x.replace(/\.(\d{1,3})Z$/,(_,n)=>'.'+n.padEnd(3,'0')+'Z'):x.replace('Z','.000Z');return new Date(x).toISOString()===normalized;};
const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
const hash=x=>createHash('sha256').update(canonical(x)).digest('hex');const reportHash=x=>createHash('sha256').update(x).digest('hex');
const stable=x=>{const h=hash(x);return h.slice(0,8)+'-'+h.slice(8,12)+'-5'+h.slice(13,16)+'-a'+h.slice(17,20)+'-'+h.slice(20,32);};
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];
const iso=x=>new Date(x).toISOString();
const sourceView=r=>({id:r.source_id,version:r.version,name:r.name,evidenceType:r.evidence_type,active:r.active,complete:r.complete,windowStart:iso(r.window_start),windowEnd:iso(r.window_end),watermark:iso(r.watermark),actorId:r.actor_id,report:r.report});
const entryView=r=>({id:r.entity_id,rowId:r.id,revision:r.revision,sourceId:r.source_id,externalId:r.external_id,kind:r.kind,status:r.status,effectiveAt:iso(r.effective_at),recordedAt:iso(r.recorded_at),currency:r.currency,exponent:r.exponent,basis:r.basis,amountMinor:r.amount_minor===null?null:String(r.amount_minor).replace(/\.0+$/,''),orderId:r.order_id,reversalOf:r.reversal_of,details:r.details,report:r.report,actorId:r.actor_id});
const typeFor={order:'order_export',refund:'payment_ledger',reversal:'payment_ledger',replacement:'replacement_invoice',support_model:'support_timesheet',future_scenario:'scenario_assumption'};
const integerMoney=x=>x===null||typeof x==='string'&&/^(0|[1-9][0-9]{0,36})$/.test(x);
const exactKeys=(x,allowed)=>{check(x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).every(k=>allowed.includes(k)),'unsupported_field');};
function validateDetails(q){const d=q.details;if(q.kind==='support_model'){exactKeys(d,['durationSeconds','rateMinorPerMinute','rateVersion','unit','validFrom','validUntil','rateEvidence','approved']);check(integerMoney(d.durationSeconds)&&integerMoney(d.rateMinorPerMinute)&&text(d.rateVersion)&&d.unit==='minute'&&instant(d.validFrom)&&instant(d.validUntil)&&Date.parse(d.validFrom)<=Date.parse(q.effectiveAt)&&Date.parse(d.validUntil)>Date.parse(q.effectiveAt)&&text(d.rateEvidence,2000)&&d.approved===true&&q.amountMinor===null&&q.status==='modeled','support_rate_invalid');}else if(q.kind==='future_scenario'){exactKeys(d,['affectedCustomers','relevantRevenueMinor','probabilityBps','horizonDays','assumptionId','assumptionReport','unit','validFrom','validUntil','approved']);check((d.affectedCustomers===null||Number.isSafeInteger(d.affectedCustomers)&&d.affectedCustomers>=0)&&integerMoney(d.relevantRevenueMinor)&&(d.probabilityBps===null||Number.isInteger(d.probabilityBps)&&d.probabilityBps>=0&&d.probabilityBps<=10000)&&Number.isInteger(d.horizonDays)&&d.horizonDays>0&&d.horizonDays<=3650&&text(d.assumptionId)&&text(d.assumptionReport,2000)&&d.unit==='customer'&&instant(d.validFrom)&&instant(d.validUntil)&&Date.parse(d.validFrom)<=Date.parse(q.effectiveAt)&&Date.parse(d.validUntil)>Date.parse(q.effectiveAt)&&d.approved===true&&q.amountMinor===null&&q.status==='modeled','scenario_invalid');}else{exactKeys(d,[]);check(q.kind==='order'?['recorded','pending','cancelled','unknown'].includes(q.status):['settled','pending','cancelled','unknown'].includes(q.status),'status_invalid');}}
export function createEconomicRepository({database}){
 const underlying=database;database={transaction:async(action,work)=>{let domain;try{return await underlying.transaction(action,async s=>{try{return await work(s);}catch(e){if(e instanceof EconomicError)domain=e;throw e;}});}catch(e){if(domain)throw domain;throw e;}}};
 const lock=s=>s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':economic-ledger']);
 const sources=s=>s.query('SELECT DISTINCT ON(source_id) * FROM public.economic_source_versions WHERE tenant_id=$1 ORDER BY source_id,version DESC',[s.tenantId]);
 return {
 async recordSource(q){exactKeys(q,['sourceId','expectedVersion','name','evidenceType','active','complete','windowStart','windowEnd','watermark','report','attested']);check((q.sourceId===undefined||uuid(q.sourceId))&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&text(q.name)&&Object.values(typeFor).includes(q.evidenceType)&&typeof q.active==='boolean'&&typeof q.complete==='boolean'&&instant(q.windowStart)&&instant(q.windowEnd)&&Date.parse(q.windowStart)<Date.parse(q.windowEnd)&&instant(q.watermark)&&Date.parse(q.watermark)<=Date.now()&&text(q.report,8000)&&q.report.length>=20&&q.attested===true,'source_invalid');q={...q,windowStart:iso(q.windowStart),windowEnd:iso(q.windowEnd),watermark:iso(q.watermark)};return database.transaction('configure',async s=>{await lock(s);const id=q.sourceId??randomUUID(),old=await one(s,'SELECT * FROM public.economic_source_versions WHERE tenant_id=$1 AND source_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,id]);check((old?.version??0)===q.expectedVersion,'source_version_conflict',409);if(old)check(old.evidence_type===q.evidenceType,'source_type_immutable',409);const r=await one(s,'INSERT INTO public.economic_source_versions(tenant_id,source_id,version,actor_id,name,evidence_type,active,complete,window_start,window_end,watermark,report,report_hash,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,true) RETURNING *',[s.tenantId,id,q.expectedVersion+1,s.userId,q.name,q.evidenceType,q.active,q.complete,q.windowStart,q.windowEnd,q.watermark,q.report,reportHash(q.report)]);return sourceView(r);});},
 async record(q){exactKeys(q,['sourceId','sourceVersion','expectedRevision','externalId','kind','effectiveAt','currency','exponent','basis','amountMinor','status','orderId','reversalOf','details','report','attested']);check(uuid(q.sourceId)&&Number.isInteger(q.sourceVersion)&&q.sourceVersion>0&&Number.isInteger(q.expectedRevision)&&q.expectedRevision>=0&&text(q.externalId)&&Object.hasOwn(typeFor,q.kind)&&instant(q.effectiveAt)&&/^[A-Z]{3}$/.test(q.currency)&&Number.isInteger(q.exponent)&&q.exponent>=0&&q.exponent<=4&&text(q.basis)&&text(q.report,8000)&&q.report.length>=20&&q.attested===true&&(q.orderId===null||uuid(q.orderId))&&(q.reversalOf===null||uuid(q.reversalOf)),'entry_invalid');check(q.kind==='reversal'?(q.amountMinor===null||typeof q.amountMinor==='string'&&/^(0|-[1-9][0-9]{0,36})$/.test(q.amountMinor))&&q.reversalOf!==null:integerMoney(q.amountMinor)&&q.reversalOf===null,'amount_or_reversal_invalid');validateDetails(q);q={...q,effectiveAt:iso(q.effectiveAt)};return database.transaction('configure',async s=>{await lock(s);const source=await one(s,'SELECT * FROM public.economic_source_versions WHERE tenant_id=$1 AND source_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,q.sourceId]);check(source&&source.active&&source.version===q.sourceVersion&&source.evidence_type===typeFor[q.kind],'source_unavailable',409);const id=stable([s.tenantId,q.sourceId,q.kind,q.externalId]);const old=await one(s,'SELECT * FROM public.economic_ledger_entries WHERE tenant_id=$1 AND entity_id=$2 ORDER BY revision DESC LIMIT 1',[s.tenantId,id]);if(old&&old.revision===q.expectedRevision+1){const previous=entryView(old);const same=['sourceId','externalId','kind','effectiveAt','currency','exponent','basis','amountMinor','status','orderId','reversalOf','details','report'].every(k=>canonical(previous[k])===canonical(q[k]));if(same)return previous;}
 check((old?.revision??0)===q.expectedRevision,'entry_version_conflict',409);const r=await one(s,'INSERT INTO public.economic_ledger_entries(tenant_id,entity_id,source_id,source_version,revision,actor_id,external_id,kind,effective_at,currency,exponent,basis,amount_minor,status,order_id,reversal_of,details,report,report_hash,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,true) RETURNING *',[s.tenantId,id,q.sourceId,q.sourceVersion,q.expectedRevision+1,s.userId,q.externalId,q.kind,q.effectiveAt,q.currency,q.exponent,q.basis,q.amountMinor,q.status,q.orderId,q.reversalOf,JSON.stringify(q.details),q.report,reportHash(q.report)]);return entryView(r);});},
 async list({scope}){exactKeys(scope,['start','end','timezone','dateBasis','currency','exponent','basis']);check(instant(scope.start)&&instant(scope.end)&&Date.parse(scope.start)<Date.parse(scope.end)&&scope.timezone==='UTC'&&scope.dateBasis==='occurred_at'&&/^[A-Z]{3}$/.test(scope.currency)&&Number.isInteger(scope.exponent)&&scope.exponent>=0&&scope.exponent<=4&&text(scope.basis),'scope_invalid');scope={...scope,start:iso(scope.start),end:iso(scope.end)};return database.transaction('read',async s=>{const allSources=(await sources(s)).rows.map(sourceView),active=new Set(allSources.filter(x=>x.active).map(x=>x.id));const history=(await s.query('SELECT * FROM public.economic_ledger_entries WHERE tenant_id=$1 ORDER BY entity_id,revision',[s.tenantId])).rows.map(entryView);const latest=new Map();for(const e of history)latest.set(e.id,e);const entries=[...latest.values()].filter(e=>active.has(e.sourceId));const asOf=iso((await one(s,'SELECT transaction_timestamp() AS now',[])).now),sourceAccounts=allSources.filter(x=>x.active).map(x=>({sourceAccount:x.id,watermark:x.watermark,complete:x.complete&&x.windowStart<=scope.start&&x.windowEnd>=scope.end&&x.watermark>=scope.end}));
 const row=e=>({id:e.id,tenantId:s.tenantId,sourceAccount:e.sourceId,externalId:e.externalId,sourceRevision:String(e.revision),occurredAt:e.effectiveAt,recordedAt:e.recordedAt,currency:e.currency,exponent:e.exponent,basis:e.basis,amountMinor:e.amountMinor,status:e.status,provenance:'approved_manual',evidenceRef:e.rowId});
 const authorized={authorization:{tenantId:s.tenantId,permissionsVersion:String(s.permissionsVersion)},snapshot:{tenantId:s.tenantId,id:'ledger:'+hash(entries.map(e=>[e.rowId,e.revision])),asOf,sources:sourceAccounts},scope,orders:entries.filter(e=>e.kind==='order').map(row),events:entries.filter(e=>['refund','reversal'].includes(e.kind)).map(e=>({...row(e),kind:e.kind,reversalOf:e.reversalOf})),links:[]};
 const orderSources=sourceAccounts.filter(x=>allSources.some(s=>s.id===x.sourceAccount&&s.evidenceType==='order_export')),paymentSources=sourceAccounts.filter(x=>allSources.some(s=>s.id===x.sourceAccount&&s.evidenceType==='payment_ledger'));const orderBundle=adaptLedger({...authorized,snapshot:{...authorized.snapshot,sources:orderSources},events:[]});const refundBundle=adaptLedger({...authorized,snapshot:{...authorized.snapshot,sources:paymentSources},orders:[],links:[]});const basic={...orderBundle,inputHash:hash([orderBundle.inputHash,refundBundle.inputHash]),metrics:{...orderBundle.metrics,refunds:refundBundle.metrics.refunds},issues:[...orderBundle.issues,...refundBundle.issues]};for(const [metric,relevant] of [[basic.metrics.allOrders,orderSources],[basic.metrics.refunds,paymentSources]])if(!relevant.length){metric.amountMinor=null;metric.knownSubtotalMinor=null;metric.status='unavailable';metric.missingReasons.push('family_source_absent');}basic.metrics.exposure={global:{...basic.metrics.allOrders,amountMinor:null,knownSubtotalMinor:null,status:'unavailable',missingReasons:['problem_relations_not_measured']},byProblem:{},problemRowsAreAdditive:false};const knownOrders=new Map(entries.filter(e=>e.kind==='order').map(e=>[e.id,e]));for(const e of entries.filter(e=>['refund','reversal','replacement'].includes(e.kind)&&e.orderId)){const order=knownOrders.get(e.orderId);if(!order||order.currency!==e.currency||order.exponent!==e.exponent){basic.issues.push({code:'order_reference_unavailable_or_incompatible',entityType:'event',id:e.id});if(['refund','reversal'].includes(e.kind)){basic.metrics.refunds.amountMinor=null;basic.metrics.refunds.status='unavailable';basic.metrics.refunds.missingReasons.push('order_reference_unavailable_or_incompatible');}}}const extra=separateComponents({entries,sources:allSources,scope,asOf});return {canWrite:s.role==='owner',sources:allSources,entries,history,bundle:{...basic,components:extra},state:history.length?'ready':'empty',notice:'Consulta del ledger actual; no es un snapshot publicado. No hay total de pérdida ni ahorro. Las fuentes manuales requieren evidencia operacional y aprobación del propietario.'};});}
 };
}
