import {createHash} from 'node:crypto';
import {createEconomicRepository,EconomicError} from './repository.mjs';
import {readExposure} from './exposure.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
const hash=x=>createHash('sha256').update(canonical(x)).digest('hex');
const stable=x=>{const h=hash(x);return h.slice(0,8)+'-'+h.slice(8,12)+'-5'+h.slice(13,16)+'-a'+h.slice(17,20)+'-'+h.slice(20,32);};
const uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(x);
const check=(ok,code,status=409)=>{if(!ok)throw new EconomicError(code,status);};
const keys=(q,a)=>q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>a.includes(k));
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];const iso=x=>new Date(x).toISOString();
const POLICY='economic-policy-f05-05-v1',SCHEMA='economic-snapshot-v1';
const tables=[['economic_source_versions','source_id','version'],['economic_ledger_entries','entity_id','revision'],['economic_problem_links','problem_id,entity_id','version'],['economic_order_aliases','alias_entity_id','version'],['economic_order_customers','entity_id','version'],['economic_relation_coverage','scope_key','version'],['economic_currency_versions','currency','version'],['economic_fx_versions','rate_id','version']];
function scopeInput(q){check(keys(q,['scope','fxRateId'])&&q.scope,'snapshot_input_invalid',400);const scope=q.scope;check(keys(scope,['start','end','timezone','dateBasis','currency','exponent','basis']),'snapshot_scope_invalid',400);for(const t of ['start','end']){check(typeof scope[t]==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(scope[t])&&Number.isFinite(Date.parse(scope[t])),'snapshot_scope_invalid',400);const expected=scope[t].includes('.')?scope[t].replace(/\.(\d{1,3})Z$/,(_,n)=>'.'+n.padEnd(3,'0')+'Z'):scope[t].replace('Z','.000Z');check(iso(scope[t])===expected,'snapshot_scope_invalid',400);}check(Date.parse(scope.start)<Date.parse(scope.end)&&scope.timezone==='UTC'&&scope.dateBasis==='occurred_at'&&/^[A-Z]{3}$/.test(scope.currency)&&Number.isInteger(scope.exponent)&&scope.exponent>=0&&scope.exponent<=4&&typeof scope.basis==='string'&&scope.basis.trim()&&scope.basis.length<=200&&(q.fxRateId===undefined||uuid(q.fxRateId)),'snapshot_scope_invalid',400);return {scope:{...scope,start:iso(scope.start),end:iso(scope.end)},fxRateId:q.fxRateId??null};}
async function capture(s,selection){const refs=[],times=[],watermarks=[];for(const [table,key,version] of tables){const rows=(await s.query(`SELECT DISTINCT ON(${key}) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.${table} WHERE tenant_id=$1 ORDER BY ${key},${version} DESC`,[s.tenantId])).rows;for(const r of rows){refs.push({table,id:r.id,actorId:r.actor_id,authorized:r.actor_active,active:r.active??true,sourceId:r.source_id??null,version:r[version],rowHash:hash(r)});for(const k of ['created_at','recorded_at','watermark'])if(r[k])times.push(iso(r[k]));if(table==='economic_source_versions')watermarks.push({sourceId:r.source_id,version:r.version,watermark:iso(r.watermark),complete:r.complete,active:r.active&&r.actor_active});}}
 const exposure=await readExposure(s,{scope:selection.scope});const contributing=new Set(exposure.relations.filter(r=>r.active&&r.valid).map(r=>r.problemId));const problems=exposure.problemOptions.filter(p=>contributing.has(p.id));const runs=[];for(const p of problems){const rows=(await s.query(`SELECT DISTINCT e.id,e.model_id,e.prompt_hash,e.schema_hash,e.provenance,e.created_at FROM public.extraction_runs e JOIN public.problem_embedding_members m ON m.tenant_id=e.tenant_id AND m.extraction_run_id=e.id JOIN public.problem_versions p ON p.tenant_id=m.tenant_id AND p.problem_id=m.problem_id AND p.version=$3 WHERE m.tenant_id=$1 AND m.problem_id=$2 AND m.embedding_id IN(SELECT value::uuid FROM jsonb_array_elements_text(p.provenance->'snapshot'->'embeddingIds')) ORDER BY e.id`,[s.tenantId,p.id,p.version])).rows;for(const r of rows){runs.push({id:r.id,model:r.model_id,promptHash:r.prompt_hash,schemaHash:r.schema_hash,policy:r.provenance.policy_hash??null,taxonomy:r.provenance.taxonomy??null});times.push(iso(r.created_at));}}
 const models=[...new Map(runs.map(r=>[r.id,r])).values()].sort((a,b)=>a.id.localeCompare(b.id));const manifest={refs,watermarks,models,exposureInputHash:exposure.inputHash,selection,policy:POLICY,schema:SCHEMA};return {manifest,inputHash:hash(manifest),asOf:times.sort().at(-1)??'1970-01-01T00:00:00.000Z'};}
async function authorizeCaptured(s,snap){check(await one(s,'SELECT 1 AS ok WHERE public.economic_contributor_active($1,$2)',[s.tenantId,snap.created_by]),'snapshot_contributor_unavailable',403);if(snap.published_by)check(await one(s,'SELECT 1 AS ok WHERE public.economic_contributor_active($1,$2)',[s.tenantId,snap.published_by]),'snapshot_contributor_unavailable',403);
 for(const r of snap.input_manifest.refs){check(tables.some(t=>t[0]===r.table),'snapshot_manifest_invalid');const row=await one(s,`SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.${r.table} WHERE tenant_id=$1 AND id=$2`,[s.tenantId,r.id]);check(row,'snapshot_evidence_unavailable',403);if(r.authorized)check(row.actor_active,'snapshot_contributor_unavailable',403);if(r.table==='economic_source_versions'&&r.active&&r.authorized){const latest=await one(s,'SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.economic_source_versions WHERE tenant_id=$1 AND source_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,row.source_id]);check(latest?.active&&latest.actor_active,'snapshot_source_unavailable',403);}if(['economic_currency_versions','economic_fx_versions'].includes(r.table)&&r.active&&r.authorized){const key=r.table==='economic_currency_versions'?'currency':'rate_id';const latest=await one(s,`SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.${r.table} WHERE tenant_id=$1 AND ${key}=$2 ORDER BY version DESC LIMIT 1`,[s.tenantId,row[key]]);check(latest?.active&&latest.actor_active,'snapshot_configuration_unavailable',403);}}
 const repo=createEvidenceRepository({database:{transaction:async(_a,fn)=>fn(s)}});for(const run of snap.input_manifest.models){try{await repo.get(run.id);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')throw new EconomicError('snapshot_evidence_unavailable',403);throw e;}}
}
const normalizeMoney=(money,inputHash)=>money?{...money,provenance:money.provenance.map(p=>p.source==='authorized_economic_ledger'?{...p,reference:inputHash}:p)}:null;
function components(data,id,inputHash){const result=[];for(const bundle of data.monetary.nativeBundles)for(const e of bundle.metrics){const money=normalizeMoney(e.money,inputHash);result.push({id:stable([id,bundle.currency,e.key,'native']),metric:e.key,label:e.label,currency:bundle.currency,exponent:bundle.exponent,amountMinor:money?.amount_minor??(money?null:e.native.amountMinor),knownSubtotalMinor:money?.known_subtotal??(money?null:e.native.knownSubtotalMinor),money,display:e.display,configurationStatus:e.configurationStatus,modeled:e.modeled,conversion:null});}for(const e of data.monetary.conversion?.items??[]){const money=normalizeMoney(e.converted,inputHash);result.push({id:stable([id,money.currency,e.key,'converted']),metric:e.key+':converted',label:e.label+' · Conversión explícita',currency:money.currency,exponent:money.exponent,amountMinor:money.amount_minor,knownSubtotalMinor:money.known_subtotal,money,display:e.display,configurationStatus:'ready',modeled:e.modeled,conversion:{original:normalizeMoney(e.original,inputHash),converted:money,fx:e.conversion}});}return result.sort((a,b)=>(a.metric+a.currency+a.id).localeCompare(b.metric+b.currency+b.id));}
async function load(s,id,allowDraft=false){const snap=await one(s,'SELECT * FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2 AND economic_schema_version=$3',[s.tenantId,id,SCHEMA]);check(snap,'snapshot_not_found',404);check(snap.status==='published'||allowDraft&&s.role==='owner','snapshot_not_published',403);await authorizeCaptured(s,snap);const rows=(await s.query('SELECT * FROM public.components WHERE tenant_id=$1 AND snapshot_id=$2 ORDER BY metric,currency,id',[s.tenantId,id])).rows;const digest=await one(s,'SELECT public.economic_snapshot_digest($1,$2) AS hash',[s.tenantId,id]);check(rows.length===snap.component_count&&digest.hash===snap.content_hash,'snapshot_integrity_failed');return {id:snap.id,status:snap.status,scopeHash:snap.scope_hash,inputHash:snap.input_hash,contentHash:snap.content_hash,asOf:iso(snap.as_of),watermark:snap.input_manifest.watermarks.length?iso(snap.watermark):null,scope:snap.provenance.scope,exposure:snap.provenance.exposure,versions:{schema:snap.economic_schema_version,policy:snap.policy_version,models:snap.input_manifest.models},components:rows.map(r=>({...r.provenance.component,amountMinor:r.amount_minor===null?null:String(r.amount_minor).replace(/\.0+$/,''),knownSubtotalMinor:r.known_subtotal_minor===null?null:String(r.known_subtotal_minor).replace(/\.0+$/,'')})),publishedAt:snap.published_at?iso(snap.published_at):null};}
export function createSnapshotRepository({database,hooks={}}){const transact=async(action,fn)=>{let domain;try{return await database.transaction(action,async s=>{try{return await fn(s);}catch(e){if(e instanceof EconomicError)domain=e;throw e;}});}catch(e){if(domain)throw domain;throw e;}};const lock=async s=>{for(const key of ['economic-snapshots','economic-ledger','economic-relations','money-config'])await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':'+key]);};return {
 async stage(q){const selection=scopeInput(q),scopeHash=hash(selection);const result=await transact('import',async s=>{check(s.role==='owner','snapshot_owner_required',403);await lock(s);const captured=await capture(s,selection);const id=stable([s.tenantId,scopeHash,captured.inputHash,POLICY]);const existing=await one(s,'SELECT * FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,id]);if(existing)return load(s,id,true);const asOf=existing?iso(existing.as_of):iso((await one(s,'SELECT transaction_timestamp() AS now',[])).now);const data=await createEconomicRepository({database:{transaction:async(_a,fn)=>fn(s)},snapshotAsOf:asOf}).list({scope:selection.scope,...(selection.fxRateId?{fxRateId:selection.fxRateId}:{})});const items=components(data,id,captured.inputHash);if(!existing){await s.query('INSERT INTO public.metric_snapshots(id,tenant_id,scope_hash,input_hash,policy_version,watermark,status,date_start,date_end,timezone,currency,date_basis,economic_schema_version,as_of,content_hash,input_manifest,component_count,created_by,provenance) VALUES($1,$2,$3,$4,$5,$6,\'draft\',$7,$8,$9,$10,\'order\',$11,$12,$13,$14,$15,$16,$17)',[id,s.tenantId,scopeHash,captured.inputHash,POLICY,captured.manifest.watermarks.map(x=>x.watermark).sort()[0]??asOf,selection.scope.start,selection.scope.end,selection.scope.timezone,selection.scope.currency,SCHEMA,asOf,'0'.repeat(64),JSON.stringify(captured.manifest),items.length,s.userId,JSON.stringify({scope:selection.scope,fxRateId:selection.fxRateId,exposure:{membership:data.exposure.metrics.membership,customerExposure:data.exposure.metrics.customerExposure,problemRowsAreAdditive:false}})]);}else{await authorizeCaptured(s,existing);await s.query('DELETE FROM public.components WHERE tenant_id=$1 AND snapshot_id=$2',[s.tenantId,id]);}
 for(let index=0;index<items.length;index++){const c=items[index];await s.query('INSERT INTO public.components(id,tenant_id,snapshot_id,metric,kind,amount_minor,known_subtotal_minor,currency,exponent,known_count,total_count,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[c.id,s.tenantId,id,c.metric,c.modeled?'modeled':'observed',c.amountMinor,c.knownSubtotalMinor,c.currency,c.exponent,c.money?.coverage.known_n??null,c.money?.coverage.eligible_n??null,JSON.stringify({component:c})]);await hooks.afterComponent?.({index,snapshotId:id});}
 check((await capture(s,selection)).inputHash===captured.inputHash,'snapshot_input_changed');await s.query('UPDATE public.metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id),component_count=$3 WHERE tenant_id=$1 AND id=$2',[s.tenantId,id,items.length]);return load(s,id,true);});await hooks.afterStage?.(result);return result;},
 async publish(q){check(keys(q,['snapshotId','expectedContentHash'])&&uuid(q.snapshotId)&&/^[a-f0-9]{64}$/.test(q.expectedContentHash),'snapshot_publish_invalid',400);return transact('import',async s=>{check(s.role==='owner','snapshot_owner_required',403);await lock(s);const view=await load(s,q.snapshotId,true);check(view.contentHash===q.expectedContentHash,'snapshot_version_conflict');if(view.status==='published')return view;await s.query("UPDATE public.metric_snapshots SET status='published',published_by=$3,published_at=transaction_timestamp(),bundle_ref=$4 WHERE tenant_id=$1 AND id=$2",[s.tenantId,view.id,s.userId,'canonical:'+view.contentHash]);await s.query('INSERT INTO public.economic_snapshot_heads(tenant_id,scope_hash,snapshot_id,version) VALUES($1,$2,$3,1) ON CONFLICT(tenant_id,scope_hash) DO UPDATE SET snapshot_id=EXCLUDED.snapshot_id,version=public.economic_snapshot_heads.version+1',[s.tenantId,view.scopeHash,view.id]);return load(s,view.id);});},
 async latest(q){const selection=scopeInput(q);return transact('read',async s=>{const head=await one(s,'SELECT snapshot_id FROM public.economic_snapshot_heads WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,hash(selection)]);return {snapshot:head?await load(s,head.snapshot_id):null,canPublish:s.role==='owner'};});},
 async get(q){check(keys(q,['snapshotId','scopeHash'])&&uuid(q.snapshotId)&&(q.scopeHash===undefined||/^[a-f0-9]{64}$/.test(q.scopeHash)),'snapshot_id_invalid',400);return transact('read',async s=>{const view=await load(s,q.snapshotId,true);check(q.scopeHash===undefined||q.scopeHash===view.scopeHash,'snapshot_scope_conflict');return view;});}
 };}
export function snapshotCsv(snapshot){const headers=['snapshotId','scopeHash','inputHash','contentHash','asOf','metric','currency','exponent','amountMinor','knownSubtotalMinor','status','windowStart','windowEnd','timezone'];const cell=(x,column)=>{const v=x==null?'':String(x);return '"'+(![7,8,9].includes(column)&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';};return [headers,...snapshot.components.map(c=>[snapshot.id,snapshot.scopeHash,snapshot.inputHash,snapshot.contentHash,snapshot.asOf,c.metric,c.currency,c.exponent,c.amountMinor,c.knownSubtotalMinor,c.money?.status??c.configurationStatus,c.money?.window.start??snapshot.scope.start,c.money?.window.end??snapshot.scope.end,c.money?.window.timezone??snapshot.scope.timezone])].map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n';}
