import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
const candidate=process.env.VEXA_CANDIDATE;
assert.ok(candidate,'VEXA_CANDIDATE required');
const modulePath=path.join(candidate,'packages/briefs/index.mjs');
const purePath=path.join(candidate,'packages/briefs/build.mjs');
const available=fs.existsSync(purePath);
const uuid=n=>`aaaaaaaa-aaaa-4aaa-8aaa-${String(n).padStart(12,'0')}`;
const hash=n=>String(n).repeat(64);
const metric=(kind,amount,extra={})=>({label:'SYN '+kind,kind,amount_minor:amount,known_subtotal:amount,currency:'USD',exponent:2,source_ref:'SYN-ledger-physical',status:'complete',coverage:{known_n:2,eligible_n:2},missing_reasons:[],...extra});
function fixture(){const scope={date_start:'2026-01-01',date_end:'2026-02-01',timezone:'UTC',date_basis:'occurred_at',currency:'USD',basis:'net-no-tax',exponent:2,sku:[],source:[],snapshot_id:uuid(1),scope_hash:hash(1)};const problem=(n,count,critical=false)=>({id:uuid(n),version:1,title:'SYN '+n,metrics:[metric('exposure',n===12?'10000':'30000')],critical,rank:null,rankingBasis:'evidence_count',evidenceCount:count,evidence:Array.from({length:count},(_,i)=>({runId:uuid(n*1000+i),messageRevisionId:uuid(n*2000+i),quote:'SYN quoted evidence '+i,quoteHash:hash(3),role:'customer',category:critical?'smoke':'delivery',severity:critical?'critical':'low'})),href:'/problems/'+uuid(n)});return {snapshotId:uuid(1),scopeHash:hash(1),baseScopeHash:hash(2),scope,asOf:'2026-02-02T00:00:00.000Z',watermark:'2026-02-01T00:00:00.000Z',coverage:'2/3',metrics:[metric('allOrders',null,{known_subtotal:'9007199254740993',status:'partial',coverage:{known_n:2,eligible_n:3},missing_reasons:['AMOUNT_UNKNOWN']}),metric('exposure','30000'),metric('refunds','1500'),metric('replacement','1200'),metric('support_model','500')],problems:[problem(11,20),problem(12,10),problem(13,10),problem(14,1,true)],actions:[{id:uuid(70),version:2,kind:'recommendation',title:'SYN action',status:'proposed',ownerId:null,summary:'SYN human decision required',href:'/recommendations'}],comparison:{status:'not_requested',snapshotId:null,scopeHash:null,reasons:['COMPARISON_NOT_REQUESTED'],metrics:[],causalClaim:false}};}
const load=()=>import(pathToFileURL(purePath).href);
test('F06-06 durable brief implementation is required',()=>{for(const file of ['packages/briefs/index.mjs','supabase/migrations/0027_briefs.sql'])assert.ok(fs.existsSync(path.join(candidate,file)),'BRIEF_IMPLEMENTATION_MISSING:'+file);});
test('F06-06 pure brief preserves exact money unknown coverage and financial families',{skip:!available},async()=>{const {buildBrief}=await load(),input=fixture(),before=structuredClone(input),doc=buildBrief(input);assert.deepEqual(input,before,'BRIEF_INPUT_MUTATION');assert.deepEqual(doc.metrics,input.metrics,'BRIEF_FINANCIAL_COPY_MISMATCH');assert.equal(doc.metrics[0].amount_minor,null,'BRIEF_UNKNOWN_NOT_ZERO');assert.equal(doc.metrics[0].known_subtotal,'9007199254740993','BRIEF_BIGINT_LOSS');assert.equal(doc.metrics[1].amount_minor,'30000','BRIEF_GLOBAL_NOT_SUM_ROWS');assert.equal(doc.problemRowsAreAdditive,false);assert.equal(doc.causalClaim,false);assert.equal(doc.sent,false);assert.equal(doc.generatedBy,'deterministic-template-no-LLM');assert.equal(doc.forecast.status,'not_estimable');});
test('F06-06 stable top3 and independent critical lane',{skip:!available},async()=>{const {buildBrief}=await load(),input=fixture(),doc=buildBrief(input);assert.deepEqual(doc.top3.map(p=>p.id),[uuid(11),uuid(12),uuid(13)],'BRIEF_TOP3_STABLE_TIE');assert.deepEqual(doc.critical.map(p=>p.id),[uuid(14)],'BRIEF_CRITICAL_NOT_TRUNCATED');assert.deepEqual(buildBrief({...input,problems:[...input.problems].reverse()}),doc,'BRIEF_DETERMINISTIC_INPUT_ORDER');const priority=buildBrief({...input,problems:input.problems.map((p,i)=>({...p,rank:4-i,rankingBasis:'published_priority'}))});assert.deepEqual(priority.top3.map(p=>p.id),[uuid(14),uuid(13),uuid(12)],'BRIEF_CAPTURED_PRIORITY');});
test('F06-06 comparison remains explicit exact and never causal',{skip:!available},async()=>{const {buildBrief}=await load(),input=fixture();const absent=buildBrief(input);assert.equal(absent.comparison.status,'not_requested');assert.equal(absent.comparison.metrics.length,0);const comparison={status:'available',snapshotId:uuid(2),scopeHash:hash(4),reasons:[],metrics:[{kind:'allOrders',currency:'USD',exponent:2,previousAmountMinor:'9007199254740993',currentAmountMinor:'9007199254741000',deltaMinor:'7'}],causalClaim:false};const complete={...input,metrics:input.metrics.map(m=>m.kind==='allOrders'?{...m,amount_minor:'9007199254741000',known_subtotal:'9007199254741000',status:'complete',coverage:{known_n:3,eligible_n:3},missing_reasons:[]}:m)};assert.deepEqual(buildBrief({...complete,comparison}).comparison,comparison,'BRIEF_COMPARISON_EXACT');const unknown={...comparison,status:'not_comparable',reasons:['SOURCE_INCOMPLETE'],metrics:[{...comparison.metrics[0],previousAmountMinor:null,currentAmountMinor:null,deltaMinor:null}]};assert.deepEqual(buildBrief({...input,comparison:unknown}).comparison,unknown,'BRIEF_COMPARISON_UNKNOWN');});
test('F06-06 server HTML escapes source text and never sends',{skip:!available},async()=>{const {buildBrief,briefHtml}=await load(),input=fixture();input.problems[0].title='<img src=x onerror=alert(1)>';input.problems[0].evidence[0].quote='<script>globalThis.SYN_CANARY=1</script>';input.actions[0].title='<svg onload=alert(2)>';const brief={id:uuid(9),version:1,inputHash:hash(5),contentHash:hash(6),createdAt:input.asOf,createdBy:uuid(7),previousId:null,stale:false,document:buildBrief(input)},html=briefHtml(brief);assert.equal(typeof html,'string');assert.ok(!/<script\b|<img\b|<svg\b/i.test(html),'BRIEF_HTML_EXECUTABLE_SOURCE');assert.ok(html.includes('&lt;img'),'BRIEF_TITLE_NOT_ESCAPED');assert.equal(brief.document.sent,false);assert.equal(brief.document.scopeHash,input.scopeHash);});
test('F06-06 contradictory snapshot scope or currency cannot publish',{skip:!available},async()=>{const {buildBrief}=await load(),input=fixture();for(const patch of [{snapshotId:uuid(99)},{scopeHash:hash(9)},{scope:{...input.scope,currency:'MXN'}},{scope:{...input.scope,exponent:0}},{metrics:input.metrics.map((m,i)=>i===0?{...m,currency:'MXN'}:m)}])assert.throws(()=>buildBrief({...input,...patch}),'BRIEF_SCOPE_MISMATCH_ACCEPTED:'+JSON.stringify(patch));});

test('F06-06 critical-lane truncation mutant is killed and restored',{skip:!available},async()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-brief-domain-mutant-'));try{
  for(const file of ['briefs/build.mjs','workspace-service/contracts.mjs','metrics/money.mjs','metrics/scope.mjs']){const target=path.join(tmp,'packages',file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(path.join(candidate,'packages',file),target);}
  const target=path.join(tmp,'packages/briefs/build.mjs'),original=fs.readFileSync(target,'utf8'),needle='critical:x.problems.filter(p=>p.critical)';assert.equal(original.split(needle).length,2,'BRIEF_MUTANT_ANCHOR_CHANGED');
  const oracle=fn=>assert.deepEqual(fn(fixture()).critical.map(p=>p.id),[uuid(14)],'BRIEF_CRITICAL_NOT_TRUNCATED');
  oracle((await import(pathToFileURL(target).href+'?before')).buildBrief);
  fs.writeFileSync(target,original.replace(needle,'critical:x.problems.slice(0,3).filter(p=>p.critical)'));
  const broken=(await import(pathToFileURL(target).href+'?mutant')).buildBrief;assert.throws(()=>oracle(broken),e=>e.code==='ERR_ASSERTION'&&e.message.includes('BRIEF_CRITICAL_NOT_TRUNCATED'),'BRIEF_SEMANTIC_MUTANT_SURVIVED');
  fs.writeFileSync(target,original);oracle((await import(pathToFileURL(target).href+'?restored')).buildBrief);
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
test('F06-06 mixed published and fallback ranking is permutation invariant',{skip:!available},async()=>{const {buildBrief}=await load(),input=fixture(),problems=input.problems.slice(0,3).map((p,i)=>({...p,rank:i<2?i+1:null,rankingBasis:i<2?'published_priority':'evidence_count',evidenceCount:[1,100,50][i],evidence:Array.from({length:[1,100,50][i]},(_,n)=>({...p.evidence[0],runId:uuid(5000+i*100+n)}))}));const order=ps=>buildBrief({...input,problems:ps}).top3.map(p=>p.id),expected=order(problems);for(const permutation of [[problems[2],problems[1],problems[0]],[problems[1],problems[2],problems[0]]])assert.deepEqual(order(permutation),expected,'BRIEF_MIXED_RANK_NONDETERMINISTIC');});
