import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {randomUUID} from 'node:crypto';import {configured,request,started,digest} from './fixtures.mjs';import {q} from './harness.mjs';import {backend} from '../../tests/acceptance/support/F01-03/import-uploads/oracles.mjs';import {read,write} from '../../tests/acceptance/support/F01-03/harness.mjs';import {foreignKeys} from '../../tests/acceptance/support/F01-03/oracles.mjs';
const tables=['ai_budget_limits','ai_budget_reservations','ai_budget_attempts','ai_budget_reconciliations'];
const token=(ownerToken,sql)=>`PERFORM set_config('vexa.budget_owner_token',${q(ownerToken)},true);${sql}`;
const denied=result=>assert.notEqual(result.code,'00000','BUDGET_DIRECT_SQL_MUST_REJECT');
export async function security(t,h){
 const fixtures=[];for(let n=0;n<2;n++){const s=await configured(h),id=(await s.repository.reserve(request(s.actor))).reservationId;await s.repository.recordAttempt(id,started());await s.repository.finalize(id,{state:'uncertain',actualMinor:null,reportedMinor:'0'});const r=(await s.repository.list({window:s.window})).find(x=>x.id===id);await s.repository.reconcile({reservationId:id,expectedVersion:r.version,actualMinor:'10',evidenceHash:digest('SYN-SQL-receipt-'+id),confirmedProviderEvidence:true});fixtures.push({...s,id});}
 const[A,B]=fixtures;h.sql(`INSERT INTO memberships(tenant_id,user_id,role,status) VALUES(${q(B.actor.tenant)},${q(A.actor.id)},'owner','active')`);
 await t.test('four budget tables have FORCE RLS deny public grants and validated tenant composite FKs',()=>{const fks=foreignKeys(h);for(const table of tables){const schema=h.json(`SELECT json_build_object('rls',relrowsecurity,'force',relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`);assert.deepEqual(schema,{rls:true,force:true});for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const privilege of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE']){const allowed=role==='vexa_backend'&&(['SELECT','INSERT'].includes(privilege)||privilege==='UPDATE'&&['ai_budget_limits','ai_budget_reservations'].includes(table));assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(privilege)})`),allowed?'t':'f','BUDGET_GRANT:'+table+':'+role+':'+privilege);}const own=fks.filter(f=>f.table===table);assert.ok(own.length>0);for(const fk of own){assert.ok(fk.validated,'BUDGET_FK_VALIDATED');assert.ok(fk.parent==='organizations'?fk.mapping.tenant_id==='id':fk.mapping.tenant_id==='tenant_id','BUDGET_FK_TENANT_BOUND');}}assert.ok(fks.some(f=>f.table==='ai_budget_reservations'&&f.parent==='jobs'&&f.mapping.job_id==='id'),'BUDGET_JOB_FK');assert.ok(fks.some(f=>f.table==='ai_budget_attempts'&&f.parent==='ai_budget_reservations'&&f.mapping.reservation_id==='id'),'BUDGET_ATTEMPT_FK');});
 await t.test('actual SQL rows are selected-tenant scoped even for a dual-tenant owner and evidence is immutable',async()=>{for(const table of tables){const result=backend(h,read(table),A.actor,A.actor.tenant,'read');assert.equal(result.code,'00000');assert.ok(result.rows.length>0,'BUDGET_READ_POSITIVE:'+table);assert.ok(result.rows.every(x=>x.tenant_id===A.actor.tenant),'BUDGET_SELECTED_TENANT:'+table);denied(backend(h,write(`DELETE FROM ${table} WHERE tenant_id=${q(A.actor.tenant)}`),A.actor,A.actor.tenant,'configure'));}for(const table of ['ai_budget_attempts','ai_budget_reconciliations'])denied(backend(h,write(`UPDATE ${table} SET created_at=created_at+interval '1 second' WHERE tenant_id=${q(A.actor.tenant)}`),A.actor,A.actor.tenant,'configure'));const reserved=await configured(h),id=(await reserved.repository.reserve(request(reserved.actor))).reservationId;h.fenceFixture={...reserved,id};const update=write(`UPDATE ai_budget_reservations SET state='settled',actual_minor=0,reported_minor=0,version=version+1 WHERE id=${q(id)}`);denied(backend(h,update,reserved.actor,reserved.actor.tenant,'import'));denied(backend(h,token(randomUUID(),update),reserved.actor,reserved.actor.tenant,'import'));const valid=backend(h,token(reserved.ownerToken,update),reserved.actor,reserved.actor.tenant,'import');assert.equal(valid.code,'00000','BUDGET_OWNER_TOKEN_POSITIVE_CONTROL');const invalidStarted=write(`INSERT INTO ai_budget_attempts(tenant_id,reservation_id,owner_token,attempt_index,state,model,provider,pricing_version,ceiling_minor) VALUES(${q(reserved.actor.tenant)},${q(id)},${q(reserved.ownerToken)},0,'started',NULL,NULL,NULL,80)`);denied(backend(h,token(reserved.ownerToken,invalidStarted),reserved.actor,reserved.actor.tenant,'import'));});
 await t.test('quota tenant and reconciliation mutants fail their exact oracles then restore',()=>{const cycles=[];const cycle=(name,oracle,mutation,restore)=>{oracle();h.sql(mutation);try{assert.throws(oracle,undefined,'BUDGET_MUTANT_SURVIVED:'+name);}finally{h.sql(restore);}oracle();cycles.push({name,baseline:0,mutant:1,restored:0});};
  cycle('selected_tenant',()=>{const result=backend(h,read('ai_budget_reservations'),A.actor,A.actor.tenant,'read');assert.equal(result.code,'00000');assert.ok(result.rows.length>0);assert.ok(result.rows.every(x=>x.tenant_id===A.actor.tenant),'BUDGET_MUTANT_TENANT_LEAK');},'CREATE POLICY synthetic_budget_leak ON ai_budget_reservations FOR SELECT TO vexa_backend USING(true)','DROP POLICY synthetic_budget_leak ON ai_budget_reservations');
  const s=h.fenceFixture;cycle('direct_quota',()=>denied(backend(h,token(s.ownerToken,write(`INSERT INTO ai_budget_reservations(tenant_id,job_id,purpose,window_key,task_key,fingerprint,actor_id,owner_token,held_minor) VALUES(${q(s.actor.tenant)},${q(s.jobId)},'extraction',${q(s.window)},${q(randomUUID())},${q(digest(randomUUID()))},${q(s.actor.id)},${q(s.ownerToken)},80)`)),s.actor,s.actor.tenant,'import')),'ALTER TABLE ai_budget_reservations DISABLE TRIGGER ai_budget_reservation_guard','ALTER TABLE ai_budget_reservations ENABLE TRIGGER ai_budget_reservation_guard');
  cycle('evidence_delete',()=>denied(backend(h,write(`DELETE FROM ai_budget_attempts WHERE tenant_id=${q(A.actor.tenant)}`),A.actor,A.actor.tenant,'import')),'GRANT DELETE ON ai_budget_attempts TO vexa_backend; CREATE POLICY synthetic_budget_delete ON ai_budget_attempts FOR DELETE TO vexa_backend USING(true);ALTER TABLE ai_budget_attempts DISABLE TRIGGER ai_budget_attempt_guard','ALTER TABLE ai_budget_attempts ENABLE TRIGGER ai_budget_attempt_guard;DROP POLICY synthetic_budget_delete ON ai_budget_attempts;REVOKE DELETE ON ai_budget_attempts FROM vexa_backend');
  fs.writeFileSync(path.join(h.evidence,'mutants.json'),JSON.stringify(cycles),{mode:0o600});
 });
}
