import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {setup,q} from './harness.mjs';
const candidate=process.env.VEXA_CANDIDATE,evidence=process.env.VEXA_TEAM_EVIDENCE;fs.mkdirSync(evidence,{recursive:true});const h=await setup(candidate,evidence);const checks=[];const pass=name=>{checks.push(name);console.log('PASS '+name);};
try{
const owner=await h.request(h.A,'/api/team');assert.equal(owner.status,200);assert.equal(owner.data.data.items.length,2);
assert.equal((await h.request({...h.A,tenant:h.B.tenant},'/api/team')).status,403);
assert.equal((await h.request({...h.bot,tenant:h.A.tenant},'/api/team')).status,403);
assert.equal((await h.request(null,'/api/team')).status,401);
assert.equal((await h.request(h.A,'/api/team',{operation:'invite'},{origin:'https://foreign.example.test'})).status,403);pass('owner-tenant-analyst-anonymous-csrf');
let r=await h.request(h.A,'/api/team',{operation:'revoke',id:h.A.id,version:1});assert.equal(r.data.error.code,'team_last_owner');
r=await h.request(h.A,'/api/team',{operation:'role',id:h.bot.id,role:'viewer'});assert.equal(r.status,409);assert.equal(r.data.error.code,'team_version_conflict');
r=await h.request(h.A,'/api/team',{operation:'role',id:h.bot.id,version:1,role:'owner'});assert.equal(r.status,200);
const race=await Promise.all([h.request(h.A,'/api/team',{operation:'revoke',id:h.bot.id,version:2}),h.request({...h.bot,tenant:h.A.tenant},'/api/team',{operation:'revoke',id:h.A.id,version:1})]);assert.equal(race.filter(r=>r.status===200).length,1);assert.equal(h.sql(`select count(*) from memberships where tenant_id=${q(h.A.tenant)} and status='active' and role='owner'`),'1');
// Restore this fixture's original owner through owned superuser setup only, after preserving exact race outcome.
fs.writeFileSync(path.join(evidence,'race.json'),JSON.stringify(race));h.sql(`update memberships set role=case when user_id=${q(h.A.id)} then 'owner' else 'analyst' end,status='active',permissions_version=permissions_version+1 where tenant_id=${q(h.A.tenant)}`);pass('cas-null-last-owner-concurrent');
const email='invite-'+randomUUID()+'@example.test',requestId=randomUUID(),input={operation:'invite',email,role:'viewer',requestId,confirmed:true};
r=await h.request(h.A,'/api/team',input);assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.data.data.delivery,'sent');const invitation=r.data.data.id;
assert.equal((await h.request(h.A,'/api/team',input)).data.data.replay,true);
assert.equal((await h.request(h.A,'/api/team',{...input,role:'owner'})).status,409);
assert.equal((await h.request(h.A,'/api/team',{...input,requestId:randomUUID()})).data.error.code,'team_invitation_pending');
const mail=h.mail('/api/v1/messages');assert.equal(mail.messages.length,1);const message=h.mail('/api/v1/message/'+mail.messages[0].ID),link=message.HTML.match(/href="([^\"]+)"/)[1].replaceAll('&amp;','&');assert.equal(new URL(link).hostname,'127.0.0.1');
assert.equal(h.sql(`select count(*) from memberships where user_id=(select id from auth.users where email=${q(email)})`),'0');pass('smtp-one-message-idempotence-no-autoaccept');
assert.equal((await h.request(h.B,'/auth/invitations/'+invitation+'/session',{operation:'accept'})).status,403);
const verified=await fetch(link,{redirect:'manual'}),location=verified.headers.get('location');assert.ok(location);const auth=new URLSearchParams(new URL(location).hash.slice(1)),token=auth.get('access_token'),refresh=auth.get('refresh_token');assert.ok(token);const user=await h.auth('auth','/user',token);assert.equal(user.data.email,email);assert.ok(user.data.email_confirmed_at);const invitee={id:user.data.id,token,refresh,tenant:h.A.tenant};
assert.equal((await h.request(invitee,'/api/team')).status,403);
const browser=await h.browser(),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.goto(location);await page.getByRole('button',{name:'Aceptar invitación',exact:true}).waitFor();assert.equal(new URL(page.url()).hash,'');await page.getByRole('button',{name:'Aceptar invitación',exact:true}).click();await page.getByText('Invitación aceptada.',{exact:true}).waitFor();await page.screenshot({path:path.join(evidence,'invitation-mobile.png'),fullPage:true});fs.writeFileSync(path.join(evidence,'before-selection.json'),JSON.stringify({members:h.json(`select jsonb_agg(to_jsonb(m)) from memberships m where user_id=${q(invitee.id)}`),cookies:(await context.cookies()).map(c=>({name:c.name,length:c.value.length,path:c.path})),root:await page.evaluate(async()=>{const r=await fetch('/');return{status:r.status,url:r.url};})}));page.on('request',request=>{if(request.url().endsWith('/auth/organization'))void request.allHeaders().then(headers=>fs.writeFileSync(path.join(evidence,'selection-origin.json'),JSON.stringify({origin:headers.origin??null,referer:headers.referer??null})));});page.on('response',response=>{if(response.url().endsWith('/auth/organization'))void response.text().then(text=>fs.writeFileSync(path.join(evidence,'selection-response.json'),JSON.stringify({status:response.status(),body:text.slice(0,400)}))).catch(()=>{});});await page.getByRole('button',{name:'Entrar al equipo',exact:true}).click();await page.waitForURL(h.base+'/');assert.equal(new URL(page.url()).pathname,'/');
assert.equal((await h.request(invitee,'/auth/invitations/'+invitation+'/session',{operation:'accept'})).status,200);assert.equal(h.sql(`select count(*) from team_audit where operation='accept' and target_id=${q(invitation)}`),'1');pass('browser-final-session-verified-accept-select-replay');
r=await h.request(h.A,'/api/team');const member=r.data.data.items.find(x=>x.id===invitee.id);assert.ok(member);r=await h.request(h.A,'/api/team',{operation:'revoke',id:member.id,version:member.version});assert.equal(r.status,200);
assert.equal((await h.request(invitee,'/auth/invitations/'+invitation+'/session',{operation:'accept'})).status,403);
for(const route of ['/api/workspace','/api/workspace/export?format=json&snapshot_id='+randomUUID()+'&scope_hash='+'a'.repeat(64),'/api/jobs/'+randomUUID()]){const response=await fetch(h.base+route,{headers:{cookie:h.cookie(invitee)}});assert.ok([401,403].includes(response.status),route+':'+response.status);}
await page.goto(h.base+'/settings/team');await page.waitForURL(/login/);assert.ok(!(await page.textContent('body')).includes(email));await context.close();pass('revocation-existing-api-export-job-ui');
// Existing verified Auth user: invitation endpoint reports user_exists, then exactly one magic link.
const existing=await h.newUser();r=await h.request(h.A,'/api/team',{operation:'invite',email:existing.email,role:'operator',requestId:randomUUID(),confirmed:true});assert.equal(r.status,200);assert.equal(r.data.data.delivery,'sent',JSON.stringify(r));const existingId=r.data.data.id;
assert.equal(h.mail('/api/v1/messages').messages.length,2);
const oldEmail=existing.email;h.sql(`update auth.users set email=${q('changed-'+randomUUID()+'@example.test')} where id=${q(existing.id)}`);assert.equal((await h.request(existing,'/auth/invitations/'+existingId+'/session',{operation:'accept'})).status,403);h.sql(`update auth.users set email=${q(oldEmail)},email_confirmed_at=null where id=${q(existing.id)}`);assert.equal((await h.request(existing,'/auth/invitations/'+existingId+'/session',{operation:'accept'})).status,403);h.sql(`update auth.users set email_confirmed_at=now() where id=${q(existing.id)};update team_invitations set expires_at=created_at+interval '1 second',created_at=now()-interval '1 day' where id=${q(existingId)}`);
// Explicit timestamp assignment avoids invalid relative fixture expiry.
h.sql(`update team_invitations set expires_at=now()-interval '1 hour' where id=${q(existingId)}`);assert.equal((await h.request(existing,'/auth/invitations/'+existingId+'/session',{operation:'accept'})).status,403);pass('existing-magic-email-current-confirmed-expiry');
// Cancellation, parallel acceptance, pending and member pagination use real Auth/PG.
const pendingUser=await h.newUser(),make={operation:'invite',email:pendingUser.email,role:'viewer',requestId:randomUUID(),confirmed:true};r=await h.request(h.A,'/api/team',make);assert.equal(r.status,200);const pendingId=r.data.data.id;
let pending=await h.request(h.A,'/api/team?kind=invitations'),row=pending.data.data.items.find(x=>x.id===pendingId);assert.ok(row);assert.equal((await h.request(h.A,'/api/team',{operation:'cancel',id:pendingId,version:row.version})).status,200);assert.equal((await h.request(pendingUser,'/auth/invitations/'+pendingId+'/session',{operation:'accept'})).status,403);
r=await h.request(h.A,'/api/team',{...make,requestId:randomUUID()});assert.equal(r.status,200);const parallelId=r.data.data.id;const accepts=await Promise.all([h.request(pendingUser,'/auth/invitations/'+parallelId+'/session',{operation:'accept'}),h.request(pendingUser,'/auth/invitations/'+parallelId+'/session',{operation:'accept'})]);assert.deepEqual(accepts.map(r=>r.status),[200,200]);assert.equal(h.sql(`select count(*) from team_audit where target_id=${q(parallelId)} and operation='accept'`),'1');assert.equal((await h.request({...pendingUser,tenant:h.A.tenant},'/api/team',{operation:'role',id:h.A.id,version:1,role:'viewer'})).status,403);pass('cancel-parallel-accept-viewer');
const faultInput={operation:'invite',email:'uncertain-'+randomUUID()+'@example.test',role:'viewer',requestId:randomUUID(),confirmed:true};h.teamFault=true;const callsBefore=h.inviteCalls;r=await h.request(h.A,'/api/team',faultInput);assert.equal(r.status,200);assert.equal(r.data.data.delivery,'uncertain');const callsAfter=h.inviteCalls;assert.equal(callsAfter,callsBefore+1);h.teamFault=false;r=await h.request(h.A,'/api/team',faultInput);assert.equal(r.data.data.replay,true);assert.equal(h.inviteCalls,callsAfter);pass('http-ambiguous-claimed-no-resend');
for(let n=0;n<26;n++){const created=await h.auth('rest','/rpc/team_manage',h.A.token,{method:'POST',body:{p_tenant:h.A.tenant,p_input:{operation:'invite',email:'page-'+randomUUID()+'@example.test',role:'viewer',confirmed:true,requestId:randomUUID()}}});assert.equal(created.status,200);const memberUser=await h.newUser();h.sql(`insert into memberships(tenant_id,user_id,role,status) values(${q(h.A.tenant)},${q(memberUser.id)},'viewer','active')`);}
for(const kind of ['members','invitations']){const first=await h.request(h.A,'/api/team?kind='+kind);assert.equal(first.data.data.items.length,25);assert.ok(first.data.data.nextCursor);const second=await h.request(h.A,'/api/team?kind='+kind+'&cursor='+first.data.data.nextCursor);assert.ok(second.data.data.items.length>0);assert.ok(!second.data.data.items.some(x=>first.data.data.items.some(y=>y.id===x.id)));}pass('both-pagination-no-overlap');
// Owner browser loading, sanitized network error, retry and clear after authority revocation.
const ownerContext=await browser.newContext({viewport:{width:1280,height:900}});await ownerContext.addCookies(h.cookie(h.A).split('; ').map(v=>{const at=v.indexOf('=');return{name:v.slice(0,at),value:v.slice(at+1),url:h.base};}));const ownerPage=await ownerContext.newPage();await ownerPage.goto(h.base+'/settings/team');await ownerPage.getByText(h.A.email,{exact:false}).waitFor();await ownerPage.screenshot({path:path.join(evidence,'team-desktop.png'),fullPage:true});await ownerPage.route('**/api/team?*',route=>route.abort('failed'));await ownerPage.getByRole('button',{name:'Actualizar',exact:true}).click();await ownerPage.getByRole('alert').filter({hasText:'No se pudo cargar'}).waitFor();assert.ok(!(await ownerPage.textContent('body')).includes('Failed to fetch'));assert.ok(!(await ownerPage.textContent('body')).includes(h.A.email));await ownerPage.unrouteAll({behavior:'wait'});await ownerPage.getByRole('button',{name:'Actualizar',exact:true}).click();await ownerPage.getByText(h.A.email,{exact:false}).waitFor();await ownerContext.close();pass('ui-network-sanitized-clear-retry');
h.verifySources();fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({node:process.version,checks,synthetic:true,remoteSends:0},null,2));
}finally{await h.close();}
