 'use client';
import { useRef, useState } from 'react';
export function ActionForm({endpoint,version,scope,kind,disabledReason,owner,baseline,planScope}:{endpoint:string;version:number;scope:string;kind:'recommendation'|'intervention'|'brief'|'explorer'|'plan';disabledReason?:string;owner?:string;baseline?:string;planScope?:string}){
 const [target,setTarget]=useState('approved'),[measurement,setMeasurement]=useState('');
 const blocked=disabledReason??(kind==='intervention'&&target==='closed'&&!measurement.trim()?'Falta una referencia de medición para cerrar.':undefined);
 const [pending,setPending]=useState(false),[message,setMessage]=useState('');const key=useRef<string|null>(null),busy=useRef(false);
 return <form className={kind==='plan'?'plan-form':'action-form'} onSubmit={async event=>{event.preventDefault();if(busy.current||blocked)return;busy.current=true;setPending(true);setMessage('');const fields=new FormData(event.currentTarget);const payload:Record<string,unknown>={scope};for(const [k,v] of fields)if(k!=='measurement_ref'||v!=='')payload[k]=v;if(kind!=='explorer')payload.expected_version=version;
 if(kind==='plan'){const plan:Record<string,unknown>={owner_id:owner,baseline_ref:baseline};for(const name of ['hypothesis','scope_hash','unit','population','outcome','control_plan','metric_definition_version','coverage','start','end']){plan[name]=payload[name];delete payload[name];}payload.plan=plan;}
 key.current??=crypto.randomUUID();try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify(payload),cache:'no-store'});const body=await response.json();setMessage(response.ok?'Operación registrada. Recarga para consultar la versión actual.':body.error?.message??'No se pudo completar la operación.');if(response.ok)key.current=null;}catch{setMessage('No se pudo confirmar el resultado. Conserva esta página y reintenta con la misma clave.');}finally{busy.current=false;setPending(false);}}}>
 {kind==='explorer'?<label>Pregunta dentro del alcance<textarea name="question" minLength={3} maxLength={2000} required placeholder="¿Qué evidencia respalda los problemas de este periodo?"/></label>:<><label>Razón / hipótesis<textarea name="reason" maxLength={2000} required/></label>{kind==='plan'&&<>{['hypothesis','scope_hash','unit','population','outcome','control_plan','metric_definition_version','coverage','start','end'].map(name=><label key={name}>{({hypothesis:'Hipótesis',scope_hash:'Hash de alcance del baseline',unit:'Unidad',population:'Población',outcome:'Resultado a medir',control_plan:'Plan de control',metric_definition_version:'Versión de definición de métrica',coverage:'Cobertura y limitaciones',start:'Inicio (ISO 8601)',end:'Fin (ISO 8601)'} as Record<string,string>)[name]}<input name={name} defaultValue={name==='scope_hash'?planScope:undefined} readOnly={name==='scope_hash'} required maxLength={2000}/></label>)}</>}{kind==='recommendation'&&<label>Responsable (ID de miembro)<input name="owner_id" required/></label>}{kind==='intervention'&&<><label>Nuevo estado<select name="target" value={target} onChange={e=>setTarget(e.target.value)}><option value="approved">Aprobada (owner)</option><option value="active">Activa</option><option value="measuring">En medición</option><option value="closed">Cerrada</option><option value="cancelled">Cancelada</option></select></label><label>Referencia de medición (obligatoria al cerrar)<input value={measurement} onChange={e=>setMeasurement(e.target.value)} name="measurement_ref" placeholder="UUID de la medición"/></label></>}</>}
 <button disabled={pending||!!blocked} type="submit">{pending?'Consultando…':kind==='explorer'?'Consultar evidencia':kind==='recommendation'?'Proponer intervención':kind==='brief'?'Generar brief':kind==='plan'?'Guardar plan':'Solicitar transición'}</button><p role="status">{blocked??message}</p>
 </form>;
}
