'use client';
import {useId,useState} from 'react';
import type {Bundle} from '../../lib/workspace/contracts';
import {buildCfoModel} from './cfo-model.mjs';
import styles from './cfo-overview.module.css';
const states={ready:'Publicado',partial:'Cobertura parcial',stale:'Corte desactualizado',empty:'Sin publicación'};
const percent=(bps:number)=>`${(bps/100).toLocaleString('es-MX',{maximumFractionDigits:2})}%`;
export function CfoOverview({bundle}:{bundle:Bundle}){
 const model=buildCfoModel(bundle.items),[selection,setSelection]=useState<string|null>(null),id=useId();
 const selected=model.rows.find(r=>r.key===selection)??model.rows[0],detailId=id+'-detail';
 if(bundle.meta.state==='empty'||!model.rows.length)return <div className={styles.empty} role="status"><span className={styles.kicker}>Resumen financiero</span><h2>Sin cifras publicadas para este alcance</h2><p>Revisa el periodo y los filtros o publica un snapshot desde las fuentes autorizadas.</p><details><summary>Cobertura de la consulta</summary><p>{bundle.meta.coverage}</p></details></div>;
 return <div className={styles.dashboard}>
  <div className={styles.statusRow} role="status"><span className={styles.badge} data-state={bundle.meta.state}>{states[bundle.meta.state]}</span><span>Corte <time dateTime={bundle.meta.watermark??undefined}>{bundle.meta.watermark?bundle.meta.watermark.replace('T',' ').replace(/\.\d{3}Z$/,' UTC'):'no informado'}</time></span><span>{model.rows.length} indicadores · mismo alcance</span></div>
  <div className={styles.kpis}>{model.rows.map(row=><article key={row.key} className={styles.kpi} data-state={row.state}>
   <span className={styles.kpiLabel}>{row.metric.label}</span><strong className={styles.kpiValue}>{row.display}</strong>
   <span className={styles.kpiFoot}>{row.state==='known'?'Importe publicado':row.state==='invalid'?'Revisa la unidad y el importe':'Total desconocido'}</span>
   {row.subtotal&&<span className={styles.subtotal}>Conocido: {row.subtotal}<small>Subtotal; no es el total</small></span>}
   <span className={styles.kpiCoverage}>{row.coverage.label}</span>
  </article>)}</div>
  <div className={styles.visualGrid}>
   <section className={styles.visual} aria-labelledby={id+'-amounts'}><div className={styles.panelHeading}><h2 id={id+'-amounts'}>Importes del corte</h2><span>{model.currency??'Sin escala común'}</span></div>
    <p className={styles.hint}>{model.comparisonNote}</p>
    <div className={styles.amountRows}>{model.bars.map(row=><button type="button" key={row.key} className={styles.amountRow} aria-pressed={selected?.key===row.key} aria-controls={detailId} onClick={()=>setSelection(row.key)}>
     <span className={styles.chartLabel}>{row.metric.label}</span><span className={styles.chartValue}>{row.display}</span>
     {model.compatible&&model.maximum!=='0'&&row.state==='known'?<span className={styles.moneyTrack} aria-hidden="true"><span className={styles.zeroLine}/><span className={styles.moneyBar} data-negative={row.negative} style={{width:`${(row.bps??0)/200}%`,left:row.negative?`${50-(row.bps??0)/200}%`:'50%'}}/></span>:<span className={styles.noBar}>{row.state==='unknown'?'Importe total no disponible':row.state==='invalid'?'Importe no verificable':model.maximum==='0'?'Cero publicado':'Sin escala comparable'}</span>}
    </button>)}</div>
   </section>
   <section className={styles.visual} aria-labelledby={id+'-coverage'}><div className={styles.panelHeading}><h2 id={id+'-coverage'}>Cobertura de los importes</h2><span>Registros conocidos</span></div><p className={styles.hint}>Cada indicador conserva su propio denominador.</p>
    <div className={styles.coverageRows}>{model.rows.map(row=><div key={row.key} className={styles.coverageRow}><div><span>{row.metric.label}</span><strong>{row.coverage.bps===null?'—':percent(row.coverage.bps)}</strong></div><span className={styles.hint}>{row.coverage.label}</span>{row.coverage.bps!==null&&<div className={styles.coverageTrack} role="meter" aria-label={`Cobertura de ${row.metric.label}`} aria-valuemin={0} aria-valuemax={row.coverage.eligible!} aria-valuenow={row.coverage.known!} aria-valuetext={row.coverage.label}><span style={{width:`${row.coverage.bps/100}%`}}/></div>}</div>)}</div>
   </section>
  </div>
  {selected&&<section id={detailId} className={styles.selection} aria-label="Detalle del indicador seleccionado" aria-live="polite"><div><span className={styles.kicker}>Indicador seleccionado</span><h3>{selected.metric.label}</h3></div><strong>{selected.display}</strong><span>{selected.coverage.label}</span><details><summary>Ver procedencia y límites</summary><dl><div><dt>Referencia</dt><dd>{selected.metric.source_ref}</dd></div><div><dt>Tipo</dt><dd>{selected.metric.kind}</dd></div><div><dt>Estado de origen</dt><dd>{selected.metric.status??'No informado'}</dd></div><div><dt>Moneda / decimales</dt><dd>{selected.metric.currency} / {String(selected.metric.exponent)}</dd></div></dl>{selected.subtotal&&<p>Subtotal conocido: {selected.subtotal}. El total sigue sin estar disponible.</p>}{selected.reasons.length>0&&<p>Limitaciones de origen: {selected.reasons.join(' · ')}</p>}</details></section>}
  <section className={styles.tablePanel} aria-label="Tabla completa de indicadores"><div className={styles.panelHeading}><h2>Detalle financiero</h2><span>Valores exactos</span></div><div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Tabla financiera, desplazamiento horizontal"><table><caption>Indicadores del snapshot y alcance seleccionados. Los importes no se suman.</caption><thead><tr><th scope="col">Indicador</th><th scope="col">Importe total</th><th scope="col">Subtotal conocido</th><th scope="col">Cobertura</th><th scope="col">Procedencia</th></tr></thead><tbody>{model.rows.map(row=><tr key={row.key}><th scope="row">{row.metric.label}<small>{row.recordTitle} · v{row.version}</small></th><td>{row.display}<small>{row.metric.currency} · {String(row.metric.exponent)} decimales</small></td><td>{row.knownSubtotal??'No disponible'}<small>{row.subtotal?'No equivale al total':''}</small></td><td>{row.coverage.label}<small>{row.metric.status??(row.state==='known'?'Importe publicado':'No informado')}</small></td><td><details><summary>Ver referencia</summary><p>{row.metric.source_ref}</p><p>{row.metric.kind}</p>{row.reasons.length>0&&<p>{row.reasons.join(' · ')}</p>}</details></td></tr>)}</tbody></table></div></section>
  <details className={styles.disclosure}><summary>Cómo leer estas cifras y su cobertura</summary><p>Los ingresos expuestos no equivalen a pérdida, ahorro ni retorno causal. Órdenes, exposición y reembolsos describen conceptos distintos y no se suman. La comparación de barras usa magnitudes del mismo corte, no variaciones entre periodos.</p><p>{bundle.meta.coverage}</p><p>Un subtotal conocido conserva únicamente los importes disponibles; no sustituye un total desconocido. Un porcentaje de cobertura describe registros con importe conocido, no la proporción del dinero observado.</p>{bundle.items.map(item=><div key={item.id}><p>{item.summary}</p><dl>{item.details.map((d,i)=><div key={i}><dt>{d.label}</dt><dd>{d.value}</dd></div>)}</dl>{item.evidence.length>0&&<details><summary>Evidencia autorizada ({item.evidence.length})</summary>{item.evidence.map(e=><figure key={e.id}><blockquote>{e.quote}</blockquote><figcaption>{e.role} · {e.source_ref}</figcaption></figure>)}</details>}</div>)}</details>
 </div>;
}
