'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {formatMinorUnits} from '../../../../../packages/metrics/money.mjs';
import type {ComponentSummary,ConversationRef,DetailKind,DetailView,EventSummary} from '../../../../../packages/workspace-service/detail.mjs';
import {DataState} from './data-state';
type Step={kind:DetailKind;id:string;componentId?:string;eventId?:string};
const money=(value:string|null,currency:string,exponent:number)=>formatMinorUnits(value,currency,exponent);
function EventFacts({event}:{event:EventSummary}){return <dl className="record-details"><div><dt>Registro financiero</dt><dd>{event.externalId}</dd></div><div><dt>Tipo</dt><dd>{event.kind}</dd></div><div><dt>Importe registrado</dt><dd>{money(event.amount_minor,event.currency,event.exponent)}</dd></div><div><dt>Estado</dt><dd>{event.status}</dd></div><div><dt>Fecha efectiva</dt><dd><time>{event.effectiveAt}</time></dd></div><div><dt>Revisión física</dt><dd>{event.id}</dd></div>{event.reversalOf&&<div><dt>Revierte el evento</dt><dd>{event.reversalOf}</dd></div>}</dl>;}
function Conversations({items}:{items:ConversationRef[]}){return <section aria-label="Conversaciones del detalle"><h3>Conversaciones y evidencia contextual</h3><p>Las conversaciones describen el contexto. Una frase del cliente no prueba un importe ni un reembolso.</p>{!items.length&&<p>Sin conversaciones atribuibles y autorizadas en este corte.</p>}{items.map(c=><article key={c.id} className="record-card"><h4>{c.label}</h4><p>{c.source} · {c.state==='historical'?'Revisión histórica':'Revisión capturada'} · Conversación {c.id}</p>{c.customer_id===null&&<p>Identidad del cliente desconocida; no se atribuye a un perfil.</p>}{'citations' in c&&Array.isArray(c.citations)&&c.citations.map((q:{message_revision_id:string;quote:string;quote_hash:string;role:string},index:number)=><figure key={q.message_revision_id+':'+index}><blockquote>{q.quote}</blockquote><figcaption>{q.role} · Revisión {q.message_revision_id}</figcaption></figure>)}</article>)}</section>;}
export function FinancialDetailPanel({kind,id,initialQuery,children}:{kind:'problem'|'customer';id:string;initialQuery:string;children?:ReactNode}){
 const [query,setQuery]=useState(initialQuery),[step,setStep]=useState<Step>({kind,id}),[reload,setReload]=useState(0),[data,setData]=useState<DetailView|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const [relatedAuthorized,setRelatedAuthorized]=useState(true);
 const generation=useRef(0),controller=useRef<AbortController|null>(null),resolved=useRef(initialQuery);
 const invalidate=useCallback(()=>{controller.current?.abort();generation.current++;},[]);
 useEffect(()=>{const back=()=>{invalidate();const next=window.location.search.slice(1);resolved.current=next;setQuery(next);setStep({kind,id});setData(null);setBusy(true);setError('');setReload(n=>n+1);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[invalidate,kind,id]);
 useEffect(()=>{
  const epoch=++generation.current,abort=new AbortController();controller.current=abort;
  const load=async()=>{if(abort.signal.aborted||epoch!==generation.current)return;setBusy(true);setData(null);setError('');const params=new URLSearchParams(query);for(const key of ['resource','format','cursor','limit','root_kind','root_id','component_id','event_id'])params.delete(key);
   if(!params.get('snapshot_id')||!params.get('scope_hash')){setError('Abre este detalle desde una publicación en Resumen o Problemas para conservar su periodo y sus filtros.');setBusy(false);return;}
   params.set('root_kind',kind);params.set('root_id',id);if(step.componentId)params.set('component_id',step.componentId);if(step.eventId)params.set('event_id',step.eventId);
   try{const response=await fetch('/api/workspace/detail/'+step.kind+'/'+encodeURIComponent(step.id)+'?'+params.toString(),{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if([401,403,404].includes(response.status))setRelatedAuthorized(false);const body=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;
    if(!response.ok)throw Error(response.status===401||response.status===403?'Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.':response.status===404?'No existe un detalle autorizado para este identificador y alcance.':response.status===409?'La identidad de esta vista no coincide con el alcance. Abre de nuevo el detalle desde la publicación.':response.status===400?'El alcance del detalle no es válido. Abre la publicación y revisa sus filtros.':'No se pudo consultar la evidencia. Reintenta cuando el servicio esté disponible.');
    const next=body.data as DetailView;if(!next||next.kind!==step.kind||next.id!==step.id||next.snapshot_id!==params.get('snapshot_id')||next.scope_hash!==params.get('scope_hash')||!next.detail_hash||params.has('detail_hash')&&next.detail_hash!==params.get('detail_hash'))throw Error('No se pudo verificar la identidad del detalle recibido.');
    const pinned=new URLSearchParams(query);for(const key of ['resource','format','cursor','limit','root_kind','root_id','component_id','event_id'])pinned.delete(key);pinned.set('detail_hash',next.detail_hash);resolved.current=pinned.toString();window.history.replaceState(null,'',window.location.pathname+'?'+pinned.toString());setData(next);setRelatedAuthorized(true);
   }catch(e){if(!abort.signal.aborted&&epoch===generation.current){setData(null);setError(e instanceof Error?e.message:'No se pudo consultar el detalle.');}}
   finally{if(!abort.signal.aborted&&epoch===generation.current)setBusy(false);}
  };void Promise.resolve().then(load);return()=>{abort.abort();};
 },[query,step,reload,kind,id]);
 const open=(next:Step)=>{invalidate();setData(null);setBusy(true);setError('');setQuery(resolved.current);setStep(next);setReload(n=>n+1);};
 const newIdentity=()=>{invalidate();const next=new URLSearchParams(resolved.current);next.delete('detail_hash');resolved.current=next.toString();window.history.pushState(null,'',window.location.pathname+'?'+next.toString());setQuery(next.toString());setStep({kind,id});setData(null);setError('');setBusy(true);setReload(n=>n+1);};
 const params=new URLSearchParams(query);for(const key of ['resource','format','cursor','limit','root_kind','root_id','component_id','event_id'])params.delete(key);if(data)params.set('detail_hash',data.detail_hash);const shared=new URLSearchParams(params);shared.delete('detail_hash');const suffix='?'+params.toString();
 const components=(items:ComponentSummary[])=><section aria-label="Componentes financieros"><h3>Componentes de la cifra</h3>{!items.length&&<p>No hay componentes verificables en este alcance.</p>}<div className="record-grid">{items.map(c=><article className="record-card" key={c.id}><h4>{c.label}</h4><p>{money(c.money.amount_minor,c.money.currency,c.money.exponent)}</p>{c.money.amount_minor===null&&c.money.known_subtotal!==null&&<p>Subtotal conocido: {money(c.money.known_subtotal,c.money.currency,c.money.exponent)}; no es el total.</p>}<p>{c.event_count} registros financieros · {c.money.status}</p>{c.missing_reasons.length>0&&<p>Limitaciones: {c.missing_reasons.join(', ')}</p>}<button onClick={()=>open({kind:'component',id:c.id,componentId:c.id})}>Abrir componente: {c.label}</button></article>)}</div></section>;
 return <><section aria-label="Detalle financiero autorizado"><p className="eyebrow">Cifras con procedencia</p>{kind==='customer'?<h1>Historial del cliente</h1>:<h2>Desglose financiero del problema</h2>}<p>Recorre la cifra, sus componentes, los eventos y su evidencia financiera. Las referencias conservan la publicación y cada paso vuelve a comprobar tu acceso.</p>
  <p><Link href={'/problems?'+shared.toString()}>Volver a problemas de esta publicación</Link></p><button disabled={busy} onClick={()=>open(step)}>Actualizar detalle</button><button disabled={busy} onClick={newIdentity}>Abrir nueva vista de identidad</button>{step.kind!==kind&&<button disabled={busy} onClick={()=>open({kind,id})}>Volver al detalle principal</button>}
  {busy&&<DataState state={{kind:'loading'}}/>}{error&&<DataState state={{kind:'error',code:'detail_request_failed',message:error}}/>}
  {data&&!busy&&<><h3>{data.title}</h3><p className="snapshot">Snapshot: {data.snapshot_id} · Alcance: {data.scope_hash} · Vista de detalle: {data.detail_hash}</p><p>Corte financiero: <time>{data.as_of}</time></p>{'detail_as_of' in data&&typeof data.detail_as_of==='string'&&<p>Identidad fijada para esta vista: <time>{data.detail_as_of}</time>. Las asociaciones pueden ser posteriores al corte financiero; no modifican sus registros.</p>}
   <DataState state={data.state==='empty'?{kind:'empty'}:{kind:data.state,coverage:data.coverage,watermark:data.as_of}}>
    {data.kind==='problem'&&<><p><Link href={'/recommendations?'+shared.toString()+'&problem_id='+encodeURIComponent(id)}>Revisar recomendaciones de este problema</Link></p>{components(data.components)}<section aria-label="Clientes asociados"><h3>Clientes asociados</h3>{!data.customers.length&&<p>Identidad del cliente desconocida; no se crea un perfil.</p>}<ul>{data.customers.map((c,index)=><li key={c.declaredKey+':'+index}>{c.customer_id?<Link href={'/customers/'+encodeURIComponent(c.customer_id)+suffix}>Ver cliente conocido: {c.label}</Link>:<span>{c.declaredKey}: identidad no resuelta; sin perfil de cliente.</span>}</li>)}</ul></section><Conversations items={data.conversations}/><aside className="state-panel partial" aria-label="Causalidad actual"><h3>Estado causal actual</h3><p>Esta evaluación vigente está separada de las cifras históricas del snapshot.</p>{data.causality.view?<><strong>{{unassessed:'Sin evaluar',hypothesis:'Causa probable, no confirmada',confirmed:'Causa confirmada con evidencia operativa',retracted:'Causa retractada'}[data.causality.view.claim.state]}</strong><p>{data.causality.view.claim.probableCause??'Sin causa identificada'}</p><p>{data.causality.view.claim.reason}</p></>:<p>{data.causality.unavailableReason??'No hay evaluación causal autorizada.'}</p>}</aside></>}
    {data.kind==='customer'&&<><p>Identificadores financieros aprobados: {data.customer.declaredKeys.join(', ')||'Sin asociación en este corte'}</p>{components(data.components)}<section aria-label="Órdenes del cliente"><h3>Órdenes atribuidas a este cliente</h3>{!data.orders.length&&<p>No hay órdenes atribuibles con evidencia en este corte.</p>}<ul>{data.orders.map(o=><li key={o.id}>{o.externalId} · {money(o.amount_minor,o.currency,o.exponent)} · {o.status} · <time>{o.effectiveAt}</time></li>)}</ul></section><Conversations items={data.conversations}/></>}
    {data.kind==='component'&&<><p>Importe del componente: {money(data.component.money.amount_minor,data.component.money.currency,data.component.money.exponent)}</p><p>Los eventos muestran su registro original. No sumes filas entre problemas ni confundas exposición con pérdida.</p>{data.events.length?<div className="record-grid">{data.events.map(event=><article className="record-card" key={event.id}><h4>Evento {event.externalId}</h4><EventFacts event={event}/><button onClick={()=>open({kind:'event',id:event.id,componentId:data.component.id,eventId:event.id})}>Abrir evento: {event.externalId}</button></article>)}</div>:<p>Sin eventos verificables; no se sustituye la evidencia por una explicación generada.</p>}</>}
    {data.kind==='event'&&<><EventFacts event={data.event}/><h3>Evidencia financiera del evento</h3>{!data.evidence.length&&<p>Sin evidencia financiera verificable.</p>}{data.evidence.map(e=><button key={e.id} onClick={()=>open({kind:'evidence',id:e.id,componentId:step.componentId,eventId:data.event.id})}>Abrir evidencia: {e.label}</button>)}</>}
    {data.kind==='evidence'&&<article className="record-card"><h3>Registro financiero aprobado</h3><p>{data.evidence.notice}</p><EventFacts event={data.evidence.event}/><dl className="record-details"><div><dt>Revisión contable</dt><dd>{data.evidence.record.revision}</dd></div><div><dt>Registrado por</dt><dd>{data.evidence.record.actorId}</dd></div><div><dt>Fecha de registro</dt><dd><time>{data.evidence.record.recordedAt}</time></dd></div><div><dt>Fuente financiera</dt><dd>{data.evidence.source.name} · versión {data.evidence.source.version}</dd></div><div><dt>Tipo de evidencia</dt><dd>{data.evidence.source.evidenceType}</dd></div></dl><h4>Justificación del registro</h4><p>{data.evidence.record.report}</p><h4>Procedencia de la fuente</h4><p>{data.evidence.source.report}</p><p>Este registro procede de evidencia financiera aprobada. Las conversaciones contextuales no acreditan este importe.</p></article>}
   </DataState>
  </>}
 </section>{relatedAuthorized&&children}</>;
}
