import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';import {q} from './harness.mjs';import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';import {insert} from '../../tests/acceptance/support/F01-03/matrix.mjs';
export {scope,source,currency,order} from '../F05-snapshots/fixtures.mjs';
// Every result is explicitly synthetic transport evidence; actual ingestion, redaction,
// extraction validation/commit and SQL authorization are exercised. No paid model.
export async function detailProblemFixture(h){
 const actors=new Map();const {persistCanonical}=await import(pathToFileURL(path.join(h.built,'packages/ingestion/persistence/index.mjs')));
 const canonicalActor=async actor=>{if(actors.has(actor.id))return actors.get(actor.id);const a={...actor,connection:randomUUID(),source:'zendesk',account:'SYN-detail-'+randomUUID()};h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(a.connection)},${q(a.tenant)},'zendesk',${q(a.account)})`);const database=h.repository(a).database,importId=randomUUID();h.sql(`INSERT INTO imports(id,tenant_id,connection_id,file_hash,mapping_version,state,idempotency_key,total,pending) VALUES(${q(importId)},${q(a.tenant)},${q(a.connection)},'SYN-detail-canonical','1','queued',${q(importId)},0,0)`);const save=async(type,id,payload)=>{const envelope=h.ingestion.createEnvelope({tenant_id:a.tenant,connection_id:a.connection,source:a.source,source_account_id:a.account},{entity_type:type,external_id:id,source_revision:'SYN-detail-v1',occurred_at:'2026-09-05T12:00:00.000Z',observed_at:'2026-09-06T12:00:00.000Z',payload_ref:'source:SYN-detail'},payload);const result=await database.transaction('import',s=>persistCanonical(s,{importId,record:{row_ref:randomUUID(),mapping_version:'1',envelope,payload}}));assert.ok(['inserted','duplicate'].includes(result.status),JSON.stringify(result));return result.canonical_id;};const customers={};for(const key of ['C1','C2'])customers[key]=await save('customer',key,{display_name:a.tenant===h.B.tenant?'SOLO_B_9F '+key:'SYN '+key});const result={a,database,save,customers};actors.set(actor.id,result);return result;};
 const {createExtractionRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/extraction-repository.mjs'))),{sha256}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/index.mjs')));
 async function extraction(actor,{category,severity,label,quote,conversation,externalMessage,customerKey}){const {a,database,save,customers}=await canonicalActor(actor);await save('conversation',conversation,{customer_external_id:customerKey??null,order_external_id:null});const sync=h.sync.createSyncRepository({database}),row=await sync.ensure({connectionId:a.connection,mode:'live',window:{...windowSpec,version:'SYN-detail-'+randomUUID()},mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,a,externalMessage,{text:quote,role:'customer',conversation})],'end',{done:true})});const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(a.tenant)} AND connection_id=${q(a.connection)} AND external_id=${q(conversation)}`),jobId=randomUUID();h.sql(`INSERT INTO jobs(id,tenant_id,type,state,input_ref,input_hash,version) VALUES(${q(jobId)},${q(a.tenant)},'extraction','running','SYN-DETAIL274',${q(randomUUID())},'SYN-v1')`);const repository=createExtractionRepository({database}),prepared=await repository.prepare({conversationId,jobId,taskKey:randomUUID(),taxonomy:[category],policy:{version:'SYN',emails:true,phones:true,namesMode:'dictionary',names:[]}}),revision=prepared.input.revisions[0],start=[...revision.text.slice(0,revision.text.indexOf(quote))].length,span={message_revision_id:revision.message_revision_id,start,end:start+[...quote].length,quote,quote_hash:sha256(quote),role:'customer'},run=h.json(`SELECT to_jsonb(r) FROM extraction_runs r WHERE id=${q(prepared.runId)}`);await repository.complete({runId:prepared.runId,result:{ok:true,data:{issues:[{category,severity,evidence:[span]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null},meta:{promptHash:run.prompt_hash,schemaHash:run.schema_hash,model:'synthetic/detail-model'},billingState:'settled'}});return{a,prepared,conversationId,span,logicalConversation:conversation,logicalMessage:externalMessage,customerId:customerKey?customers[customerKey]:null};}
 async function problem(actor,{label,category='delivery',severity='low',messages}){const count=messages.length,extractions=[];for(const m of messages)extractions.push(await extraction(actor,{label,category,severity,quote:m.text,conversation:m.conversation,externalMessage:m.message,customerKey:m.customerKey}));const id=randomUUID(),embeddingIds=extractions.map(()=>randomUUID()),snapshot={id,label,version:1,state:'active',outlier:count===1,modelId:'synthetic-3d',dimensions:3,embeddingVersion:'1',embeddingIds,conversationIds:extractions.map(x=>x.conversationId),orderIds:[]};let sql=`BEGIN;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('vexa.tenant_id',${q(actor.tenant)},true),set_config('vexa.action','configure',true);`;sql+=insert('problems',{id,tenant_id:actor.tenant,title:label,severity,cause_status:'unknown',provenance:{kind:'vector-problem-v1'}})+';';for(let i=0;i<extractions.length;i++){const x=extractions[i];sql+=insert('embeddings',{id:embeddingIds[i],tenant_id:actor.tenant,model_id:'synthetic-3d',dim:3,version:'1',content:'SYN detail grouping',embedding:'[1,0,0]',message_revision_id:x.span.message_revision_id})+';'+insert('problem_embedding_members',{tenant_id:actor.tenant,embedding_id:embeddingIds[i],problem_id:id,extraction_run_id:x.prepared.runId,conversation_id:x.conversationId})+';';}sql+=insert('problem_versions',{id:randomUUID(),tenant_id:actor.tenant,problem_id:id,previous_version_id:null,version:1,title:label,rationale:'SYN verified grouping of real authorized extraction fixtures',change_kind:'create',provenance:{kind:'vector-problem-v1',snapshot,actorId:actor.id,operation:'create'}})+';COMMIT;';h.sql(sql);return{id,label,extractions,embeddingIds};}
 return{problem,canonicalActor};
}

import {scope,source,currency,order} from '../F05-snapshots/fixtures.mjs';
export const detailReport='SYN explicit owner attestation of operational identity and physical financial evidence; no narrative inference.';
export async function seedDetail(h,{beforeSnapshot}={}){
 const ok=async p=>{const r=await p;assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};
 const ledger=body=>ok(h.request(h.A,'/api/economics',body));
 const factory=await detailProblemFixture(h),a=await factory.canonicalActor(h.A),b=await factory.canonicalActor(h.B);
 const p1=await factory.problem(h.A,{label:'SYN P1 devolución observada',messages:[
  {conversation:'T1',message:'M1',customerKey:'C1',text:'SYN Me devolvieron 20 dólares y todavía falta el paquete.'},
  {conversation:'T2',message:'M2',customerKey:'C1',text:'SYN Mi pedido sigue con una entrega pendiente.'},
  {conversation:'T-C2',message:'M-C2',customerKey:'C2',text:'SYN Otro cliente tiene también una entrega pendiente.'}
 ]});
 const p2=await factory.problem(h.A,{label:'SYN P2 atención compartida',messages:[{conversation:'T3',message:'M3',customerKey:'C1',text:'SYN Necesito resolver el seguimiento de mis dos pedidos.'}]});
 await ledger(currency('USD'));
 const src=await ledger(source()),payment=await ledger({...source(),name:'SYN physical payment ledger',evidenceType:'payment_ledger'});
 const o1=await ledger(order(src,'O1','10000')),o2=await ledger(order(src,'O2','20000'));
 const r1=await ledger(order(payment,'R1','2000',{kind:'refund',status:'settled',orderId:o1.id}));
 const v1=await ledger(order(payment,'V1','-500',{kind:'reversal',status:'settled',orderId:o1.id,reversalOf:r1.id}));
 for(const [problem,row] of [[p1,o1],[p1,o2],[p1,r1],[p1,v1],[p2,o1],[p2,o2]])await ledger({operation:'link',problemId:problem.id,ledgerRowId:row.rowId,expectedVersion:0,active:true,report:detailReport,attested:true});
 for(const row of [o1,o2])await ledger({operation:'orderCustomer',orderRowId:row.rowId,customerKey:'C1',expectedVersion:0,report:detailReport,attested:true});
 const {dateBasis:_serverDateBasis,...economicQuery}=scope;const exposure=await ok(h.request(h.A,'/api/economics?'+new URLSearchParams(economicQuery)));
 await ledger({operation:'relationCoverage',scope,expectedInputHash:exposure.exposure.inputHash,expectedVersion:exposure.exposure.coverage?.version??0,complete:true,report:detailReport,attested:true});
 const fixture={factory,a,b,p1,p2,src,payment,o1,o2,r1,v1,ok,ledger};
 if(beforeSnapshot)await beforeSnapshot(fixture);
 const draft=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'stage',scope}));
 const snapshot=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'publish',snapshotId:draft.id,expectedContentHash:draft.contentHash}));
 return {...fixture,snapshot};
}
export function detailQuery(snapshot,scopeHash,patch={}){return new URLSearchParams({date_start:scope.start.slice(0,10),date_end:scope.end.slice(0,10),timezone:'UTC',date_basis:'occurred_at',currency:'USD',basis:scope.basis,snapshot_id:snapshot.id,...(scopeHash?{scope_hash:scopeHash}:{}),...patch});}
