import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {setup,q} from './harness.mjs';import {seedDetail,scope,detailQuery,detailReport} from './fixtures.mjs';import './pure.mjs';
const base='/api/workspace',bindings=base+'/customer-bindings';
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const envelope=r=>{assert.equal(r.data.contract_version,'f06-detail-v1');assert.match(r.data.meta?.trace_id??'',uuid);if(r.status!==200)assert.equal(r.data.error?.retryable,r.status===503);};
async function bounded(p,label){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('DETAIL_BOUNDED_HANDSHAKE:'+label)),20000);})]);}finally{clearTimeout(timer);}}
test('F06-02 physical financial drilldown and canonical customer identity',{timeout:480000},async t=>{
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate&&fs.existsSync(path.join(candidate,'packages/workspace-service/detail.mjs')),'DETAIL_IMPLEMENTATION_MISSING');
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-detail274-'));fs.chmodSync(evidence,0o700);console.log('F0602_RUNNING:'+evidence);let h;
 const step=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();}catch(e){failure=e;throw e;}});if(failure)throw Error('DETAIL_PREREQUISITE:'+name,{cause:failure});};
 try{
 h=await setup(candidate,evidence);let f,workspace,problem,customer,refundComponent,refundEvents;
 const ok=async p=>{const r=await p;assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};
 const read=async(kind,id,patch={},actor=h.A)=>{const r=await h.request(actor,base+'/detail/'+kind+'/'+id+'?'+detailQuery(f.snapshot,workspace.meta.scope_hash,{...(problem?.detail_hash?{detail_hash:problem.detail_hash}:{}),...patch}));envelope(r);return r;};
 const binding=(customerKey,customerId,expectedVersion=0,actor=h.A)=>h.request(actor,bindings,{customerKey,customerId,expectedVersion,active:true,report:detailReport,attested:true});
 await step('real canonical ingestion evidence and exact settled refund establish snapshot',async()=>{
  f=await seedDetail(h,{beforeSnapshot:async x=>{
   const draft=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'stage',scope}));x.beforeBindingSnapshot=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'publish',snapshotId:draft.id,expectedContentHash:draft.contentHash}));x.beforeBindingWorkspace=await ok(h.request(h.A,base+'?'+detailQuery(x.beforeBindingSnapshot,null,{resource:'problems'})));x.beforeBindingDetail=await ok(h.request(h.A,base+'/detail/problem/'+x.p1.id+'?'+detailQuery(x.beforeBindingSnapshot,x.beforeBindingWorkspace.meta.scope_hash)));
   const browser=await h.browser(),ctx=await browser.newContext({timezoneId:'America/Merida'});ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const i=v.indexOf('=');return{name:v.slice(0,i),value:v.slice(i+1),url:h.base};}));h.ctx=ctx;h.p=await ctx.newPage();await h.p.goto(h.base+'/problems?'+detailQuery(x.beforeBindingSnapshot,x.beforeBindingWorkspace.meta.scope_hash));await h.p.getByRole('region',{name:'Problemas con alcance compartido'}).getByRole('link',{name:x.p1.label,exact:true}).click();const oldPanel=h.p.getByRole('region',{name:'Detalle financiero autorizado',exact:true});await oldPanel.getByText('C1: identidad no resuelta; sin perfil de cliente.',{exact:true}).waitFor();assert.equal(await oldPanel.locator('a[href*="/customers/"]').count(),0,'UNKNOWN_IDENTITY_HAS_NO_CUSTOMER_URL');assert.equal(new URL(h.p.url()).searchParams.get('detail_hash'),x.beforeBindingDetail.detail_hash);const page=await ctx.newPage();await page.goto(h.base+'/economics');
   const panel=page.getByRole('region',{name:'Asociaciones de clientes',exact:true});await panel.getByLabel('Identificador financiero del cliente',{exact:true}).selectOption('C1');await panel.getByLabel('Cliente conocido de la fuente',{exact:true}).selectOption(x.a.customers.C1);await panel.getByLabel('Razón y evidencia de identidad',{exact:true}).fill(detailReport);
   const consent=panel.getByLabel('Confirmo la identidad y esta versión de la asociación',{exact:true}),save=panel.getByRole('button',{name:'Guardar asociación de cliente',exact:true});assert.equal(await save.isEnabled(),false);await consent.check();await panel.getByLabel('Razón y evidencia de identidad',{exact:true}).fill(detailReport+' Reviewed.');assert.equal(await consent.isChecked(),false,'CONSENT_BOUND_TO_EXACT_IDENTITY_DECISION');assert.equal(await save.isEnabled(),false);await consent.check();const response=page.waitForResponse(r=>new URL(r.url()).pathname===bindings&&r.request().method()==='POST');await save.click();assert.equal((await response).status(),200);await panel.getByText(/^Asociación guardada\./).waitFor();assert.equal(await consent.isChecked(),false,'SAVE_REQUIRES_NEW_CONSENT');await page.close();
  }});
  assert.equal(f.snapshot.id,f.beforeBindingSnapshot.id,'IDENTITY_ASSOCIATION_DOES_NOT_INVENT_FINANCIAL_SNAPSHOT_CHANGES');
  workspace=await ok(h.request(h.A,base+'?'+detailQuery(f.snapshot,null,{resource:'problems'})));
  problem=await ok(read('problem',f.p1.id));customer=await ok(read('customer',f.a.customers.C1));
  assert.equal(problem.snapshot_id,f.snapshot.id);assert.equal(problem.scope_hash,workspace.meta.scope_hash);assert.equal(problem.base_scope_hash,f.snapshot.scopeHash);
  refundComponent=problem.components.find(c=>c.metric==='refunds');assert.ok(refundComponent,'REFUND_COMPONENT_PRESENT');assert.equal(refundComponent.money.known_subtotal,'1500','R1_MINUS_V1_NOT_M1_NARRATIVE');
  fs.writeFileSync(path.join(evidence,'initial-detail.json'),JSON.stringify({workspace,problem,customer},null,2));
 });
 await step('component to event to physical evidence preserves snapshot and exact revisions',async()=>{
  const context={root_kind:'problem',root_id:f.p1.id,component_id:refundComponent.id};
  const missing=await h.request(h.A,base+'/detail/component/'+refundComponent.id+'?'+detailQuery(f.snapshot,workspace.meta.scope_hash,context));assert.equal(missing.status,400,'LOWER_DRILL_MUST_PIN_DETAIL_IDENTITY');envelope(missing);const malformed=await read('problem',f.p1.id,{detail_hash:'invalid'});assert.equal(malformed.status,400);assert.equal((await read('component',refundComponent.id,{...context,root_id:f.p2.id})).status,404,'COMPONENT_CANNOT_CROSS_ROOT_CONTEXT');assert.equal((await read('problem',f.p1.id,{detail_hash:'0'.repeat(64)})).status,404,'UNKNOWN_RECEIPT_NEVER_FALLS_BACK_TO_LATEST');const component=await ok(read('component',refundComponent.id,context));refundEvents=component.events;
  assert.deepEqual(new Set(refundEvents.map(e=>e.id)),new Set([f.r1.rowId,f.v1.rowId]));
  assert.equal(refundEvents.find(e=>e.id===f.r1.rowId).amount_minor,'2000');assert.equal(refundEvents.find(e=>e.id===f.v1.rowId).amount_minor,'-500');
  for(const physical of [f.r1,f.v1]){const event=await ok(read('event',physical.rowId,context));assert.equal(event.event.id,physical.rowId);assert.equal(event.snapshot_id,f.snapshot.id);assert.equal(event.scope_hash,problem.scope_hash);assert.ok(event.evidence.length);for(const ref of event.evidence){const e=await ok(read('evidence',ref.id,{...context,event_id:physical.rowId}));assert.equal(e.evidence.record.rowId,physical.rowId);assert.equal(e.evidence.source.id,f.payment.id);assert.equal(e.evidence.source.evidenceType,'payment_ledger');assert.equal(e.evidence.accountingAuthority,'approved_ledger_record');assert.equal(e.evidence.event.amount_minor,physical===f.r1?'2000':'-500');assert.doesNotMatch(JSON.stringify(e.evidence),/Me devolvieron 20 dólares/,'NARRATIVE_IS_NOT_ACCOUNTING_AUTHORITY');}}
 });
 await step('customer union deduplicates shared orders and excludes another customer in same cluster',async()=>{
  assert.equal(customer.customer.id,f.a.customers.C1);assert.deepEqual(new Set(customer.orders.map(o=>o.entityId)),new Set([f.o1.id,f.o2.id]));assert.equal(customer.orders.length,2);
  const expected=[...f.p1.extractions.filter(e=>e.customerId===f.a.customers.C1),...f.p2.extractions].map(e=>e.conversationId);
  assert.deepEqual(new Set(customer.conversations.map(c=>c.id)),new Set(expected));assert.equal(customer.conversations.length,3);
  const other=f.p1.extractions.find(e=>e.customerId===f.a.customers.C2);assert.ok(other);assert.ok(!customer.conversations.some(c=>c.id===other.conversationId));
  assert.equal(customer.components.find(c=>c.metric==='allOrders').money.known_subtotal,'30000','CUSTOMER_UNION_NOT_PROBLEM_JOIN_SUM');assert.equal(customer.components.find(c=>c.metric==='refunds').money.known_subtotal,'1500');
 });
 await step('current hypothesis and independent confirmation never alter captured financial amounts',async()=>{
  const route='/api/problems/'+f.p1.id+'/causality',post=body=>h.request(h.A,route,body),revision={operation:'revise',expectedVersion:0,symptom:'SYN entrega pendiente',probableCause:'SYN hipótesis de coordinación operativa',state:'hypothesis',evidenceIds:[],reason:'SYN hipótesis explícita aún sin verificación operacional independiente.',approved:true};
  await ok(post(revision));const probable=await ok(read('problem',f.p1.id));assert.equal(probable.causality.view.claim.state,'hypothesis');assert.equal(probable.causality.scope,'current_authorized');assert.deepEqual(probable.components,problem.components,'CAUSAL_NARRATIVE_CANNOT_CREATE_MONEY');assert.equal((await post({...revision,expectedVersion:1,state:'confirmed'})).status,409);
  const operational=await ok(post({operation:'evidence',expectedVersion:1,expectedEvidenceVersion:0,recordId:'SYN operational inspection R1',sourceKind:'inspection',observedAt:'2026-09-12T12:00:00.000Z',report:'SYN revisión operacional independiente de entrega; no implica un importe financiero.',stance:'supports',status:'active',facts:{batch:null,carrier:null,sku:null},attested:true}));
  await ok(post({...revision,expectedVersion:1,state:'confirmed',evidenceIds:[operational.evidence[0].id],reason:'SYN confirmación humana limitada a la inspección operacional independiente.'}));const confirmed=await ok(read('problem',f.p1.id));assert.equal(confirmed.causality.view.claim.state,'confirmed');assert.deepEqual(confirmed.components,problem.components);assert.equal(confirmed.detail_hash,problem.detail_hash);
 });
 await step('authorized readers, strict tenant denial, owner CAS and CSRF identity writes',async()=>{
  const secondary={...h.bot,tenant:h.A.tenant};for(const role of ['viewer','analyst','operator']){h.sql(`UPDATE memberships SET role=${q(role)} WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);const r=await read('customer',f.a.customers.C1,{},secondary);envelope(r);assert.equal(r.status,200,JSON.stringify(r.data));assert.deepEqual(r.data.data.orders,customer.orders);assert.equal((await binding('C1',f.a.customers.C1,1,secondary)).status,403);}
  for(const [actor,id,status] of [[null,f.a.customers.C1,401],[h.A,f.b.customers.C1,404],[h.B,f.a.customers.C1,404],[{...h.A,tenant:h.B.tenant},f.a.customers.C1,403]]){const r=await read('customer',id,{},actor);assert.equal(r.status,status,JSON.stringify(r));envelope(r);assert.equal(r.data.data,undefined);assert.doesNotMatch(JSON.stringify(r.data),/SOLO_B_9F/);}
  assert.equal((await h.request(h.A,bindings,{customerKey:'C1',customerId:f.a.customers.C1,expectedVersion:1,active:true,report:detailReport,attested:true,tenantId:h.B.tenant})).status,400,'TENANT_BODY_NOT_TRUSTED');assert.equal((await binding('C1',f.a.customers.C1,0)).status,409);assert.equal((await binding('C1',f.b.customers.C1,1)).status,404);
  const r=await fetch(h.base+bindings,{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify({customerKey:'C1',customerId:f.a.customers.C1,expectedVersion:1,active:true,report:detailReport,attested:true})});assert.equal(r.status,403);
 });
 await step('identity association after old cutoff never rewrites historical unknown customer',async()=>{
  const oldWorkspace=f.beforeBindingWorkspace;const old=await ok(h.request(h.A,base+'/detail/problem/'+f.p1.id+'?'+detailQuery(f.beforeBindingSnapshot,oldWorkspace.meta.scope_hash,{detail_hash:f.beforeBindingDetail.detail_hash})));
  assert.ok(old.customers.some(c=>c.declaredKey==='C1'&&c.customer_id===null&&c.identity==='unresolved'));assert.equal((await h.request(h.A,base+'/detail/customer/'+f.a.customers.C1+'?'+detailQuery(f.beforeBindingSnapshot,oldWorkspace.meta.scope_hash,{detail_hash:f.beforeBindingDetail.detail_hash}))).status,404);
  assert.equal(old.components.find(c=>c.metric==='refunds').money.known_subtotal,'1500');assert.equal(old.detail_hash,f.beforeBindingDetail.detail_hash);assert.equal(old.detail_as_of,f.beforeBindingDetail.detail_as_of);assert.equal(old.as_of,problem.as_of);assert.notEqual(old.detail_hash,problem.detail_hash);assert.ok(Date.parse(problem.detail_as_of)>=Date.parse(old.detail_as_of));
 });
 await step('real navigation preserves scope from problem through financial evidence and customer union',async()=>{
  const page=h.p,panel=page.getByRole('region',{name:'Detalle financiero autorizado',exact:true});await panel.getByText('C1: identidad no resuelta; sin perfil de cliente.',{exact:true}).waitFor();await panel.getByRole('button',{name:'Abrir nueva vista de identidad',exact:true}).click();await panel.getByRole('link',{name:/^Ver cliente conocido:/}).first().waitFor();assert.notEqual(new URL(page.url()).searchParams.get('detail_hash'),f.beforeBindingDetail.detail_hash,'EXPLICIT_NEW_IDENTITY_VIEW');await panel.getByRole('button',{name:'Abrir componente: '+refundComponent.label,exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.get('snapshot_id'),f.snapshot.id);assert.equal(new URL(page.url()).searchParams.get('scope_hash'),workspace.meta.scope_hash);assert.ok(new URL(page.url()).searchParams.get('detail_hash'));
  await panel.getByRole('button',{name:'Abrir componente: '+refundComponent.label,exact:true}).click();await panel.getByRole('button',{name:'Abrir evento: R1',exact:true}).click();await panel.getByRole('button',{name:/^Abrir evidencia:/}).first().click();await panel.getByRole('heading',{name:'Registro financiero aprobado',exact:true}).waitFor();assert.match(await panel.innerText(),/payment_ledger/);assert.match(await panel.innerText(),/20\.00 USD/);assert.doesNotMatch(await panel.innerText(),/Me devolvieron 20 dólares/);await page.screenshot({path:path.join(evidence,'physical-refund-evidence.png'),fullPage:true});
  await panel.getByRole('button',{name:'Volver al detalle principal',exact:true}).click();await panel.getByRole('link',{name:/^Ver cliente conocido:/}).first().click();await panel.getByRole('region',{name:'Órdenes del cliente',exact:true}).waitFor();assert.equal(new URL(page.url()).pathname,'/customers/'+f.a.customers.C1);assert.equal(new URL(page.url()).searchParams.get('snapshot_id'),f.snapshot.id);assert.equal(new URL(page.url()).searchParams.get('scope_hash'),workspace.meta.scope_hash);
  assert.equal(await panel.getByRole('region',{name:'Conversaciones del detalle',exact:true}).locator('article').count(),3);assert.doesNotMatch(await panel.innerText(),/Otro cliente tiene/);assert.match(await panel.innerText(),/300\.00 USD/);await page.screenshot({path:path.join(evidence,'canonical-customer-union.png'),fullPage:true});
  await panel.getByRole('link',{name:'Volver a problemas de esta publicación',exact:true}).click();await page.getByRole('region',{name:'Problemas con alcance compartido'}).getByRole('link',{name:f.p1.label,exact:true}).click();await panel.getByRole('button',{name:'Abrir componente: '+refundComponent.label,exact:true}).waitFor();
 });
 await step('current source withdrawal denies physical detail and clears visible financial data',async()=>{
  const page=h.p,panel=page.getByRole('region',{name:'Detalle financiero autorizado',exact:true});await page.getByRole('region',{name:'Miembros del problema',exact:true}).waitFor();await page.getByRole('region',{name:'Evaluación causal',exact:true}).getByText('Estado operacional: confirmed · Versión 2',{exact:true}).waitFor();h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(f.a.a.connection)}`);
  try{const r=await read('problem',f.p1.id);assert.ok([403,404].includes(r.status),JSON.stringify(r));envelope(r);assert.equal(r.data.data,undefined);await panel.getByRole('button',{name:'Actualizar detalle',exact:true}).click();await panel.getByRole('heading',{name:'No pudimos cargar esta vista',exact:true}).waitFor();assert.equal(await panel.getByRole('region',{name:'Componentes financieros',exact:true}).count(),0);assert.equal(await panel.locator('a[href*="/customers/"]').count(),0);assert.equal(await page.getByRole('region',{name:'Miembros del problema',exact:true}).count(),0,'PAGE_WIDE_AUTH_REJECTION_MUST_CLEAR_PROBLEM_MEMBERS');assert.doesNotMatch(await page.locator('body').innerText(),/SYN hipótesis de coordinación operativa/,'PAGE_WIDE_AUTH_REJECTION_MUST_CLEAR_CAUSAL_DATA');}finally{h.sql(`UPDATE connections SET status='active' WHERE id=${q(f.a.a.connection)}`);}
  await panel.getByRole('button',{name:'Actualizar detalle',exact:true}).click();await panel.getByRole('button',{name:'Abrir componente: '+refundComponent.label,exact:true}).waitFor();
 });
 await step('late authorized detail cannot repopulate after real navigation and membership withdrawal',async()=>{
  const page=h.p,panel=page.getByRole('region',{name:'Detalle financiero autorizado',exact:true});let release,seen,finish;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r),done=new Promise(r=>finish=r);h.releaseHold=release;let captured=false;
  await page.route('**/api/workspace/detail/**',async intercepted=>{if(!captured){captured=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);const body=await response.body();seen();await held;await intercepted.fulfill({status:200,headers:response.headers(),body}).catch(()=>{});}finally{finish();}}else await intercepted.continue();});
  await panel.getByRole('button',{name:'Actualizar detalle',exact:true}).click();await bounded(started,'authorized-detail-captured');h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);
  await panel.getByRole('link',{name:'Volver a problemas de esta publicación',exact:true}).click();const globalDenied=page.getByText('Acceso denegado. Inicia sesión con una cuenta que tenga una organización activa.',{exact:true});await globalDenied.waitFor();await page.goBack();const denial=await Promise.race([globalDenied.waitFor().then(()=> 'layout_auth_denied'),panel.getByText('Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.',{exact:true}).waitFor().then(()=> 'detail_auth_denied')]);fs.writeFileSync(path.join(evidence,'late-response-denial.json'),JSON.stringify({denial,url:page.url(),capturedAuthorizedResponse:captured}));assert.equal((await read('problem',f.p1.id)).status,403);release();await bounded(done,'authorized-detail-released');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await panel.getByRole('region',{name:'Componentes financieros',exact:true}).count(),0);assert.equal(await panel.getByRole('region',{name:'Conversaciones del detalle',exact:true}).count(),0);assert.equal(await panel.locator('a[href*="/customers/"]').count(),0);assert.equal(await page.getByRole('region',{name:'Miembros del problema',exact:true}).count(),0);const visible=await page.locator('body').innerText();assert.ok(!visible.includes(f.p1.label));assert.doesNotMatch(visible,/SYN hipótesis de coordinación operativa|Me devolvieron 20 dólares/,'LATE200_NO_PRIVATE_DATA_AFTER_HISTORY_RETURN');await page.unroute('**/api/workspace/detail/**');h.releaseHold=null;await page.screenshot({path:path.join(evidence,'late-detail-revoked.png'),fullPage:true});
 });

 h.verifySources();
 }finally{h?.releaseHold?.();if(h?.p&&!h.p.isClosed()){fs.writeFileSync(path.join(evidence,'last-dom.html'),await h.p.content().catch(()=>''));await h.p.screenshot({path:path.join(evidence,'last-ui.png'),fullPage:true}).catch(()=>{});}if(h)await h.close();console.log('F0602_EVIDENCE:'+evidence);}
});
