import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'CANDIDATE_REQUIRED');
test('F06-02 independent detail implementation present',async()=>{const file=path.join(candidate,'packages/workspace-service/detail.mjs');assert.ok(fs.existsSync(file),'DETAIL_IMPLEMENTATION_MISSING');const m=await import(pathToFileURL(file));assert.equal(typeof m.createDetailService,'function','DETAIL_FACTORY_REQUIRED');const service=m.createDetailService({database:{transaction(){throw Error('NO_DATABASE_ON_FACTORY');}}});for(const name of ['get','customerBindings','recordCustomerBinding'])assert.equal(typeof service[name],'function','DETAIL_METHOD_REQUIRED:'+name);});
test('F06-02 detail rejects unsupported selectors before any database access',async()=>{const {createDetailService}=await import(pathToFileURL(path.join(candidate,'packages/workspace-service/detail.mjs')));let calls=0;const service=createDetailService({database:{transaction(){calls++;throw Error('UNEXPECTED_DATABASE_ACCESS');}}});const id='10000000-0000-4000-8000-000000000001',snapshot='20000000-0000-4000-8000-000000000001';const valid='date_start=2026-09-01&date_end=2026-10-01&currency=USD&basis=net&exponent=2&snapshot_id='+snapshot+'&scope_hash='+'a'.repeat(64);for(const input of [{kind:'sql',id,query:new URLSearchParams(valid)},{kind:'problem',id:'null',query:new URLSearchParams(valid)},{kind:'problem',id,query:new URLSearchParams(valid+'&tenant_id=foreign')},{kind:'problem',id,query:new URLSearchParams(valid+'&snapshot_id='+snapshot)},{kind:'problem',id,query:new URLSearchParams(valid.replace('2026-09-01','2026-02-30'))}]){await assert.rejects(()=>service.get(input),e=>[400,404].includes(e.status),'DETAIL_INVALID_SELECTOR_FAILS_CLOSED');assert.equal(calls,0,'DETAIL_NO_DATABASE_FOR_INVALID_SELECTOR');}});
import {graphFixture} from './independent-fixtures.mjs';
const graph=async()=>import(pathToFileURL(path.join(candidate,'packages/workspace-service/detail-graph.mjs')));
test('F06-02 financial detail traces exact refunds reversals and distinct components',async()=>{const {projectDetailGraph,financialEvent}=await graph();const input=graphFixture(),p=projectDetailGraph(input);assert.equal(p.metrics.exposure.amountMinor,'30000','DETAIL_P1_EXPOSURE');assert.equal(p.metrics.refunds.amountMinor,'1500','DETAIL_REFUND_NET_1500');assert.equal(p.metrics.replacement.amountMinor,'1200');assert.equal(p.metrics.supportModel.amountMinor,'500');assert.deepEqual(p.eventRows.refunds.map(r=>r.id).sort(),['physical-R1','physical-V1'],'DETAIL_REFUND_PHYSICAL_EVENTS');const r=financialEvent(input.rows.economic_ledger_entries.find(r=>r.entity_id==='R1'));assert.equal(r.id,'physical-R1');assert.equal(r.entityId,'R1');assert.equal(r.amount_minor,'2000');assert.equal(r.kind,'refund');assert.equal(projectDetailGraph({...input,rootId:'P2'}).metrics.exposure.amountMinor,'10000');});
test('F06-02 customer identity is explicit and union does not double count problems',async()=>{const{projectDetailGraph}=await graph();const input={...graphFixture(),rootKind:'customer',rootId:'CANONICAL-C1'},p=projectDetailGraph(input);assert.equal(p.metrics.exposure.amountMinor,'30000','DETAIL_CUSTOMER_UNION_30000');assert.equal(p.metrics.allOrders.amountMinor,'30000');assert.deepEqual(p.orders.map(r=>r.entity_id).sort(),['O1','O2']);assert.deepEqual(projectDetailGraph({...input,identityLinks:[]}).orders,[],'DETAIL_NO_CUSTOMER_BY_TEXTUAL_KEY');assert.deepEqual(projectDetailGraph({...input,rootId:'declared-C1'}).orders,[],'DETAIL_DECLARED_KEY_NOT_CANONICAL_ID');input.rows.economic_order_customers[1].customer_key=null;const partial=projectDetailGraph(input);assert.deepEqual(partial.orders.map(r=>r.entity_id),['O1'],'DETAIL_UNKNOWN_CUSTOMER_NOT_ATTRIBUTED');});
test('F06-02 SKU membership and alias identity preserve exact captured event lineage',async()=>{const{projectDetailGraph}=await graph();const input=graphFixture();input.binding.filters.sku=['SKU-X'];assert.equal(projectDetailGraph(input).metrics.exposure.amountMinor,'10000');input.rows.dimensionMappings=[];assert.equal(projectDetailGraph(input).metrics.exposure.amountMinor,null,'DETAIL_UNKNOWN_SKU_NOT_ZERO');const alias=graphFixture(),copy={...alias.rows.economic_ledger_entries[0],id:'physical-O1-copy',entity_id:'O1-copy',external_id:'O1-copy'};alias.rows.economic_ledger_entries.push(copy);alias.rows.economic_order_aliases.push({active:true,alias_entity_id:copy.entity_id,canonical_entity_id:'O1',alias_row_id:copy.id,canonical_row_id:'physical-O1'});assert.equal(projectDetailGraph(alias).metrics.allOrders.amountMinor,'30000','DETAIL_ALIAS_DEDUP');copy.amount_minor='99999';assert.equal(projectDetailGraph(alias).metrics.allOrders.amountMinor,null,'DETAIL_CONFLICTING_ALIAS_NOT_SUMMED');});
test('F06-02 approved direct refund link counts without order unless a dimension requires order identity',async()=>{const{projectDetailGraph}=await graph();const input=graphFixture();for(const r of input.rows.economic_ledger_entries.filter(r=>['refund','reversal'].includes(r.kind)))r.order_id=null;input.rows.economic_problem_links=[{active:true,problem_id:'P1',entity_id:'R1'}];assert.equal(projectDetailGraph(input).metrics.refunds.amountMinor,'1500','DETAIL_DIRECT_FINANCIAL_LINK_NOT_UNKNOWN_WITHOUT_DIMENSION');input.binding.filters.sku=['SKU-X'];assert.equal(projectDetailGraph(input).metrics.refunds.amountMinor,null,'DETAIL_DIRECT_EVENT_UNKNOWN_SKU_MEMBERSHIP');});
test('F06-02 absent financial source is unknown while complete empty source is zero',async()=>{const{projectDetailGraph}=await graph();const input=graphFixture();input.rows.economic_ledger_entries=input.rows.economic_ledger_entries.filter(r=>!['refund','reversal'].includes(r.kind));assert.equal(projectDetailGraph(input).metrics.refunds.amountMinor,'0','DETAIL_COMPLETE_LEDGER_EMPTY_ZERO');input.rows.economic_source_versions=input.rows.economic_source_versions.filter(r=>r.evidence_type!=='payment_ledger');const result=projectDetailGraph(input);assert.equal(result.metrics.refunds.amountMinor,null);assert.equal(result.metrics.refunds.knownSubtotalMinor,null,'DETAIL_ABSENT_SOURCE_NOT_OBSERVED_ZERO');});

import os from 'node:os';
test('F06-02 causal refund reversal mutant fails exact financial oracle and restores',async()=>{
 const source=fs.readFileSync(path.join(candidate,'packages/workspace-service/detail-graph.mjs'),'utf8');
 const anchor="const refundRows=events.filter(r=>['refund','reversal'].includes(r.kind))";
 assert.equal(source.split(anchor).length,2,'DETAIL_REFUND_MUTANT_SINGLE_ANCHOR');
 const portable=source.replace(/from ['"](\.[^'"]+)['"]/g,(_match,relative)=>'from '+JSON.stringify(pathToFileURL(path.resolve(candidate,'packages/workspace-service',relative)).href));
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-detail-financial-mutant-')),file=path.join(tmp,'graph.mjs');
 const oracle=m=>assert.equal(m.projectDetailGraph(graphFixture()).metrics.refunds.amountMinor,'1500','DETAIL_REFUND_REVERSAL_SEMANTIC');
 try{
  fs.writeFileSync(file,portable);oracle(await import(pathToFileURL(file).href+'?baseline'));
  fs.writeFileSync(file,portable.replace(anchor,"const refundRows=events.filter(r=>['refund'].includes(r.kind))"));
  const mutant=await import(pathToFileURL(file).href+'?mutant');
  assert.throws(()=>oracle(mutant),e=>e.code==='ERR_ASSERTION'&&e.message.includes('DETAIL_REFUND_REVERSAL_SEMANTIC'),'DETAIL_FINANCIAL_MUTANT_NOT_SETUP_FAILURE');
  fs.writeFileSync(file,portable);oracle(await import(pathToFileURL(file).href+'?restored'));
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
