import {test} from 'node:test';import assert from 'node:assert/strict';import {previewImport,normalizeDate,exportRowErrors,mappingVersion} from './mapping.mjs';
const mapping={columns:{id:'id',text:'text',date:'date',amount:'amount'},timezone:'America/New_York',dateFormat:'dmy',currency:'USD'};
const context={tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',source:'csv',source_account_id:'SYNTHETIC'};
const run=(csv,m=mapping)=>previewImport(Buffer.from(csv),{contentType:'text/csv',mapping:m,context,observedAt:'2026-09-20T00:00:00Z'});
test('calendar, DST unique, fold and gap; explicit offset',()=>{assert.equal(normalizeDate('01/02/2026','America/New_York','dmy'),'2026-02-01T05:00:00.000Z');for(const [value,code] of [['2026-02-30','INVALID_CALENDAR'],['2026-03-08T02:30:00','DST_GAP'],['2026-11-01T01:30:00','DST_FOLD']])assert.throws(()=>normalizeDate(value,'America/New_York','iso'),e=>e.code===code);assert.equal(normalizeDate('2026-11-01T01:30:00-04:00','America/New_York','iso'),'2026-11-01T05:30:00.000Z');assert.throws(()=>run('id,text,date,amount\na,b,01/02/2026,10.01',{...mapping,dateFormat:undefined}));});
test('money exact, unknown and JPY; errors no raw content',()=>{const p=run('id,text,date,amount\na,SYNTHETIC,01/02/2026,10.01\nb,SYNTHETIC,,\nc,SECRET,30/02/2026,2');assert.equal(p.sample.rows[0].money.amount_minor,'1001');assert.equal(p.sample.rows[1].money,null);assert.equal(p.coverage.rejected,1);assert.ok(!JSON.stringify(p.errors).includes('SECRET'));assert.equal(run('id,text,date,amount\na,b,,10.01',{...mapping,currency:'JPY'}).coverage.rejected,1);});
test('10K population, bounded sample, stable version and invalid headers',()=>{const p=run('id,text,date,amount\n'+Array.from({length:10000},(_,i)=>`${i},SYNTHETIC,,0`).join('\n'));assert.equal(p.input_rows,10000);assert.equal(p.coverage.accepted,10000);assert.equal(p.sample.rows.length,20);assert.equal(p.sample.representative,false);assert.equal(mappingVersion(mapping),mappingVersion({...mapping,columns:{...mapping.columns}}));assert.throws(()=>run('id,id\na,b'));assert.throws(()=>run('id,text\na,b'));});
test('CSV injection after controls, quotes and multiline stays quoted',()=>{const csv=exportRowErrors([{line:2,field:' \t=HYPERLINK("x")',code:'\r\n@SUM(1)'},{line:3,field:'+cmd',code:'-cmd'}]);assert.match(csv,/"' \t=HYPERLINK\(""x""\)"/);assert.ok(csv.includes('"\'\r\n@SUM(1)"'));assert.ok(csv.endsWith('\r\n'));});
import {archive,parts} from './mapping-fixtures.mjs';
test('XLSX explicit sheet, unsupported serial date and formula row accounting',()=>{
 const cell=(r,v)=>`<c r="${r}" t="inlineStr"><is><t>${v}</t></is></c>`;
 const sheet=`<row r="1">${['id','text','date','amount'].map((v,i)=>cell(String.fromCharCode(65+i)+'1',v)).join('')}</row><row r="2">${cell('A2','a')}${cell('B2','SYNTHETIC')}${cell('C2','01/02/2026')}<c r="D2"><v>10.01</v></c></row><row r="3">${cell('A3','b')}${cell('B3','SYNTHETIC')}<c r="C3"><v>45678</v></c><c r="D3"><v>1</v></c></row><row r="4">${cell('A4','c')}<c r="B4"><f>1+1</f><v>2</v></c></row>`;
 const entries=parts(sheet),options={contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',mapping,context,observedAt:'2026-09-20T00:00:00Z'};
 const p=previewImport(archive(entries),options);assert.equal(p.input_rows,3);assert.equal(p.coverage.accepted,1);assert.equal(p.coverage.rejected,2);assert.equal(p.sample.rows[0].money.amount_minor,'1001');assert.ok(p.errors.some(e=>e.code==='UNSUPPORTED_EXCEL_DATE'));assert.ok(p.errors.some(e=>e.code==='XLSX_FORMULA'));
 entries[2][1]=entries[2][1].replace('</sheets>','<sheet name="Other" sheetId="2" r:id="s2"/></sheets>');entries[3][1]=entries[3][1].replace('</Relationships>','<Relationship Id="s2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/other.xml"/></Relationships>');entries.push(['xl/worksheets/other.xml',entries[5][1]]);
 assert.throws(()=>previewImport(archive(entries),options),e=>e.code==='SHEET_REQUIRED');assert.equal(previewImport(archive(entries),{...options,mapping:{...mapping,sheet:'Other'}}).input_rows,3);
});
