import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {input,clone} from './fixtures.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
const unavailable=m=>{assert.equal(m.amountMinor,null,'UNAVAILABLE_MUST_NOT_ASSERT_AMOUNT');assert.ok(['partial','unavailable'].includes(m.status),'UNAVAILABLE_STATUS');assert.ok(m.missingReasons.length>0,'MISSING_REASON_REQUIRED');};
export async function adapterOracles(adaptLedger,t){const base=input();
 await t.test('FIN synthetic union, signed reversal and missing amount preserve original units/provenance',()=>{const r=adaptLedger(base);assert.equal(r.schemaVersion,'vexa-ledger-adapter-v1');assert.equal(r.tenantId,base.authorization.tenantId);assert.equal(r.snapshotId,base.snapshot.id);assert.deepEqual(r.scope,base.scope);assert.equal(r.metrics.allOrders.amountMinor,null);assert.equal(r.metrics.allOrders.knownSubtotalMinor,'30000');assert.equal(r.metrics.allOrders.knownCount,2);assert.equal(r.metrics.allOrders.totalCount,3);assert.equal(r.metrics.allOrders.status,'partial');assert.equal(r.metrics.exposure.global.amountMinor,'30000');assert.equal(r.metrics.exposure.byProblem['SYN-P1'].amountMinor,'30000');assert.equal(r.metrics.exposure.byProblem['SYN-P2'].amountMinor,'10000');assert.equal(r.metrics.exposure.problemRowsAreAdditive,false);assert.equal(r.metrics.refunds.amountMinor,'1500','SIGNED_REVERSAL_SUBTRACTED');for(const m of [r.metrics.allOrders,r.metrics.exposure.global,r.metrics.refunds]){assert.equal(m.currency,'USD');assert.equal(m.exponent,2);assert.equal(m.basis,base.scope.basis);assert.deepEqual(m.window,{start:base.scope.start,end:base.scope.end,timezone:'UTC',dateBasis:'occurred_at'});assert.ok(m.evidenceRefs.includes('SYN-source-record'));}assert.equal(r.totalImpact,undefined,'FAMILIES_NOT_SUMMED');});
 await t.test('exact arbitrary precision and verified zero remain distinct from missing',()=>{const a=clone(base);a.orders=[{...a.orders[0],amountMinor:'9007199254740993'},{...a.orders[1],amountMinor:'6'}];a.links=[];assert.equal(adaptLedger(a).metrics.allOrders.amountMinor,'9007199254740999');a.orders=[{...a.orders[0],amountMinor:'0'}];assert.equal(adaptLedger(a).metrics.allOrders.amountMinor,'0');a.orders[0].amountMinor=null;unavailable(adaptLedger(a).metrics.allOrders);for(const amount of [12,1.5,'01','1e3','-1','1.50'])assert.throws(()=>adaptLedger({...a,orders:[{...a.orders[0],amountMinor:amount}]}));});
 await t.test('complete empty scope can assert zero while incomplete source cannot',()=>{const a=clone(base);a.orders=[];a.events=[];a.links=[];assert.equal(adaptLedger(a).metrics.allOrders.amountMinor,'0');a.snapshot.sources[0].complete=false;for(const m of [adaptLedger(a).metrics.allOrders,adaptLedger(a).metrics.refunds])unavailable(m);});
 await t.test('foreign tenant is rejected before time or currency exclusions',()=>{for(const family of ['orders','events','links']){const a=clone(base);a[family][0].tenantId='SYN-TENANT-B';if(family!=='links'){a[family][0].currency='MXN';a[family][0].occurredAt='2025-01-01T00:00:00Z';}assert.throws(()=>adaptLedger(a),undefined,'TENANT_MUST_PRECEDE_SCOPE_FILTER');}const a=clone(base);a.snapshot.tenantId='SYN-TENANT-B';assert.throws(()=>adaptLedger(a));});
 await t.test('half-open boundaries, source time and snapshot time do not silently widen scope',()=>{const a=clone(base);a.links=[];a.orders=[{...a.orders[0],occurredAt:a.scope.start,amountMinor:'17'},{...a.orders[1],occurredAt:a.scope.end,recordedAt:'2026-10-01T13:00:00Z',amountMinor:'23'},{...a.orders[2],recordedAt:'2026-10-03T00:00:00Z',amountMinor:'31'}];const r=adaptLedger(a);assert.equal(r.metrics.allOrders.amountMinor,'17');assert.equal(r.excluded.outsideWindow,1);assert.equal(r.excluded.afterSnapshot,1);const old=JSON.stringify(r);const newer=clone(a);newer.snapshot.id='SYN-new';newer.snapshot.asOf='2026-10-04T00:00:00Z';assert.equal(adaptLedger(newer).metrics.allOrders.amountMinor,'48');assert.equal(JSON.stringify(r),old,'OLD_BUNDLE_IMMUTABLE');});
 await t.test('currencies and bases remain separate; exponent mismatch is never silently reinterpreted',()=>{const a=clone(base);a.links=[];a.orders=[{...a.orders[0],amountMinor:'100'},{...a.orders[1],amountMinor:'200',currency:'MXN'},{...a.orders[2],amountMinor:'300',basis:'gross-with-tax'}];const r=adaptLedger(a);assert.equal(r.metrics.allOrders.amountMinor,'100');assert.equal(r.excluded.otherCurrency,1);assert.equal(r.excluded.otherBasis,1);const b=clone(a);b.orders=[{...a.orders[0],exponent:0}];assert.throws(()=>adaptLedger(b),undefined,'EXPONENT_MUST_BE_EXPLICIT_AND_COMPATIBLE');});
 await t.test('settlement is explicit, unknown status cannot become observed zero',()=>{const a=clone(base);a.events=[{...a.events[0],status:'pending'}];assert.equal(adaptLedger(a).metrics.refunds.amountMinor,'0');a.events[0].status='cancelled';assert.equal(adaptLedger(a).metrics.refunds.amountMinor,'0');a.events[0].status='unknown';unavailable(adaptLedger(a).metrics.refunds);});
 await t.test('ticket or model claims and unregistered sources cannot become financial provenance',()=>{for(const family of ['orders','events'])for(const field of ['provenance','sourceAccount','evidenceRef']){const a=clone(base);a[family][0][field]=field==='provenance'?'llm_ticket':field==='sourceAccount'?'SYN-not-registered':'';assert.throws(()=>adaptLedger(a),undefined,'FINANCIAL_PROVENANCE_REQUIRED');}});
 await t.test('stable identity deduplicates replay; changed value or state remains explicit conflict',()=>{const r=adaptLedger(base),a=clone(base);a.orders=[...a.orders,...clone(a.orders)];a.events=[...a.events,...clone(a.events)];a.links=[...a.links,...clone(a.links)];const replay=adaptLedger(a);assert.deepEqual(replay,r,'EXACT_REPLAY_HASH_AND_NUMBERS');a.orders.push({...a.orders[0],amountMinor:'99999'});let bad=adaptLedger(a);unavailable(bad.metrics.allOrders);assert.ok(bad.issues.length>0);const b=clone(base);b.events.push({...b.events[0],status:'pending'});bad=adaptLedger(b);unavailable(bad.metrics.refunds);assert.ok(bad.issues.length>0);});
 await t.test('source identity conflict cannot evade canonical-id dedup',()=>{const a=clone(base);a.orders.push({...a.orders[0],id:'SYN-duplicate-identity',amountMinor:'42'});const r=adaptLedger(a);unavailable(r.metrics.allOrders);assert.ok(r.issues.length>0);});
 await t.test('orphan, excess and cross-currency reversal produce reconciliation instead of clipping',()=>{for(const type of ['orphan','excess','currency']){const a=clone(base);if(type==='orphan')a.events=[a.events[1]];if(type==='excess')a.events[1].amountMinor='-3000';if(type==='currency'){a.events[0].currency='MXN';a.events[1].currency='USD';}const r=adaptLedger(a);unavailable(r.metrics.refunds);assert.ok(r.issues.length>0);}});
 await t.test('permutation replay hashes are deterministic and scope/auth/provenance changes are visible',()=>{const r=adaptLedger(base),a=clone(base);a.orders.reverse();a.events.reverse();a.links.reverse();assert.deepEqual(adaptLedger(a),r);assert.match(r.scopeHash,/^[a-f0-9]{64}$/);assert.match(r.inputHash,/^[a-f0-9]{64}$/);for(const mutate of [a=>a.authorization.permissionsVersion='SYN-v2',a=>a.scope.start='2026-09-02T00:00:00Z']){const b=clone(base);mutate(b);assert.notEqual(adaptLedger(b).scopeHash,r.scopeHash);}const refresh=clone(base);refresh.snapshot.id='SYN-v2';refresh.snapshot.asOf='2026-10-03T00:00:00Z';refresh.snapshot.sources[0].watermark='SYN-next-watermark';assert.equal(adaptLedger(refresh).scopeHash,r.scopeHash,'SCOPE_STABLE_ACROSS_SNAPSHOTS');assert.notEqual(adaptLedger(refresh).inputHash,r.inputHash,'SNAPSHOT_INPUT_HASH_CHANGED');const b=clone(base);b.orders[0].evidenceRef='SYN-different-proof';assert.notEqual(adaptLedger(b).inputHash,r.inputHash);});
 await t.test('stable economic source identity excludes revision and conflicts are found before filtering',()=>{const a=clone(base);a.events.push({...a.events[0],id:'SYN-another-canonical-refund',sourceRevision:'2'});unavailable(adaptLedger(a).metrics.refunds);const b=clone(base);b.orders.push({...b.orders[0],amountMinor:'12345',occurredAt:'2025-01-01T00:00:00Z',recordedAt:'2025-01-01T01:00:00Z'});unavailable(adaptLedger(b).metrics.allOrders);});
 await t.test('impossible calendar dates are rejected instead of normalized',()=>{for(const field of ['occurredAt','recordedAt']){const a=clone(base);a.orders[0][field]='2026-02-30T12:00:00Z';assert.throws(()=>adaptLedger(a),undefined,'INVALID_FINANCIAL_CALENDAR_DATE');}const a=clone(base);a.scope.start='2026-02-30T00:00:00Z';assert.throws(()=>adaptLedger(a));});
 await t.test('reversal within period with original outside period cannot disappear as observed zero',()=>{const a=clone(base);a.events[0].occurredAt='2026-08-31T23:59:59Z';const r=adaptLedger(a);unavailable(r.metrics.refunds);assert.ok(r.issues.length>0,'EXCLUDED_ORIGINAL_REQUIRES_RECONCILIATION');});
 await t.test('open period never asserts a closed total from complete data only up to asOf',()=>{const a=clone(base);a.orders=a.orders.slice(0,2);a.links=[];a.snapshot.asOf='2026-09-20T00:00:00Z';a.snapshot.sources[0].watermark=a.snapshot.asOf;const r=adaptLedger(a);unavailable(r.metrics.allOrders);assert.equal(r.metrics.allOrders.knownSubtotalMinor,'30000');assert.ok(r.metrics.allOrders.missingReasons.includes('WINDOW_INCOMPLETE'));unavailable(r.metrics.refunds);});
 await t.test('canonical problem strings remain own JSON keys without prototype collisions',()=>{const a=clone(base);const names=['__proto__','constructor','toString'];a.links=a.links.map((l,i)=>({...l,problemId:names[i]}));const r=JSON.parse(JSON.stringify(adaptLedger(a)));for(const id of names)assert.equal(Object.hasOwn(r.metrics.exposure.byProblem,id),true,'PROBLEM_KEY_MUST_SURVIVE_JSON:'+id);assert.equal(r.metrics.exposure.byProblem.__proto__.amountMinor,'10000');assert.equal(r.metrics.exposure.byProblem.constructor.amountMinor,'20000');assert.equal(r.metrics.exposure.global.amountMinor,'30000');});
 await t.test('adapter is pure and metadata omissions never receive guessed defaults',()=>{const before=JSON.stringify(base);adaptLedger(base);assert.equal(JSON.stringify(base),before);for(const field of ['currency','exponent','basis','timezone','dateBasis','start','end']){const a=clone(base);delete a.scope[field];assert.throws(()=>adaptLedger(a),undefined,'SCOPE_REQUIRED:'+field);}const a=clone(base);a.snapshot.sources=[];assert.throws(()=>adaptLedger(a));});
}
test('F05-01 independent ledger adapter contract',{timeout:30000},async t=>{const candidate=process.env.VEXA_CANDIDATE??path.resolve(new URL('../..',import.meta.url).pathname),file=path.join(candidate,'packages/economics/adapter.mjs');assert.ok(fs.existsSync(file),'F0501_ADAPTER_IMPLEMENTATION_MISSING');const source=fs.readFileSync(file),kernel=fs.readFileSync(path.join(candidate,'packages/economics/index.mjs'));const mod=await import(pathToFileURL(file));assert.equal(typeof mod.adaptLedger,'function','F0501_ADAPTER_EXPORT_REQUIRED');await adapterOracles(mod.adaptLedger,t);const calibration=[];for(const [name,needle,replacement,oracle] of [
 ['unknown-zero','amountMinor:blocked||incomplete||openWindow?null:raw.amountMinor',"amountMinor:blocked||incomplete||openWindow?'0':raw.amountMinor",fn=>{const a=input();a.orders=[];a.events=[];a.links=[];a.snapshot.sources[0].complete=false;assert.equal(fn(a).metrics.allOrders.amountMinor,null,'INCOMPLETE_SOURCE_MUST_NOT_ASSERT_ZERO');}],
 ['number-rounding','amountMinor:blocked||incomplete||openWindow?null:raw.amountMinor','amountMinor:blocked||incomplete||openWindow?null:raw.amountMinor===null?null:String(Number(raw.amountMinor))',fn=>{const a=input();a.orders=[{...a.orders[0],amountMinor:'9007199254740993'}];a.links=[];assert.equal(fn(a).metrics.allOrders.amountMinor,'9007199254740993','EXACT_MINOR_UNITS_MUST_SURVIVE_BOUNDARY');}],
 ['foreign-tenant',"requireValue(r&&r.tenantId===a.tenantId,'TENANT_MISMATCH')","requireValue(r,'TENANT_MISMATCH')",fn=>{const a=input();a.orders[0].tenantId='SYN-FOREIGN';assert.throws(()=>fn(a),undefined,'FOREIGN_TENANT_MUST_REJECT');}]
 ])await t.test('causal mutant '+name+' is killed 0→1→0',async()=>{oracle(mod.adaptLedger);const text=source.toString();assert.equal(text.split(needle).length,2,'MUTANT_TARGET_UNIQUE');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-fin250-mutant-'));try{fs.writeFileSync(path.join(dir,'index.mjs'),kernel);fs.writeFileSync(path.join(dir,'adapter.mjs'),text.replace(needle,replacement));const mutant=await import(pathToFileURL(path.join(dir,'adapter.mjs')));let error;try{oracle(mutant.adaptLedger);}catch(e){error=e;}assert.equal(error?.code,'ERR_ASSERTION','MUTANT_MUST_FAIL_FINANCIAL_ASSERTION_NOT_SETUP');oracle(mod.adaptLedger);calibration.push({name,before:0,mutant:1,after:0,assertion:error.message,mutantHash:hash(fs.readFileSync(path.join(dir,'adapter.mjs')))});}finally{fs.rmSync(dir,{recursive:true,force:true});assert.equal(fs.existsSync(dir),false,'MUTANT_TMP_CLEANED');}});console.log('F0501_CALIBRATION:'+JSON.stringify(calibration));assert.equal(hash(fs.readFileSync(file)),hash(source),'ADAPTER_SOURCE_UNCHANGED');assert.equal(hash(fs.readFileSync(path.join(candidate,'packages/economics/index.mjs'))),hash(kernel),'KERNEL_SOURCE_UNCHANGED');});
