import {randomUUID} from 'node:crypto';import {hashValue} from '../evaluation/evaluate.mjs';import {createExtractionConfigResolver} from '../runtime.mjs';import {candidateCatalog,digest,reject} from './catalog.mjs';import {verifySummary,eligibility} from './verify.mjs';
const uuid=v=>typeof v==='string'&&/^[a-f0-9-]{36}$/i.test(v),strict=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k));
export function createCandidateRepository({database,env=process.env,runtimeCode}){const catalog=candidateCatalog(env),base=createExtractionConfigResolver(env.VEXA_EXTRACTION_CONFIG_JSON??'[]'),tx=async(fn)=>{let error;try{return await database.transaction('configure',async s=>{try{if(s.role!=='owner')reject('owner_required',403);const value=await fn(s);if(!(await s.query("SELECT public.vexa_member($1,array['owner']) AS ok",[s.tenantId])).rows[0]?.ok)reject('owner_required',403);return value;}catch(e){if(e.code?.startsWith('candidates_'))error=e;throw e;}});}catch(e){throw error??e;}};const rows=async(s,table,before)=>{
 const result=table==='candidate_results';let condition='';const params=[s.tenantId];
 if(before!==undefined){params.push(before);if(result){const boundary=(await s.query('SELECT id FROM public.candidate_results WHERE tenant_id=$1 AND id=$2',params)).rows[0];if(!boundary)reject('cursor_invalid');condition=' AND (created_at,id) < (SELECT created_at,id FROM public.candidate_results WHERE tenant_id=$1 AND id=$2)';}else condition=' AND version < $2';}
 return (await s.query(`SELECT * FROM public.${table} WHERE tenant_id=$1${condition} ORDER BY ${result?'created_at DESC,id DESC':'version DESC'} LIMIT 101`,params)).rows;
 };const assessment=(envelope,tenant)=>{try{const p=verifySummary(envelope,tenant,env);return {...eligibility(p,catalog.get(tenant,p.candidateId),runtimeCode),summary:p};}catch{return{eligible:false,reason:'signature_or_key_unavailable',summary:null};}};
 return {async list(input={}){if(!strict(input,['resultsBefore','historyBefore'])||(input.resultsBefore!==undefined&&(typeof input.resultsBefore!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(input.resultsBefore)))||(input.historyBefore!==undefined&&(!Number.isSafeInteger(input.historyBefore)||input.historyBefore<1)))reject('cursor_invalid');return tx(async s=>{
 const foundResults=await rows(s,'candidate_results',input.resultsBefore),foundHistory=await rows(s,'candidate_selections',input.historyBefore),results=foundResults.slice(0,100),history=foundHistory.slice(0,100);
 const latest=input.historyBefore===undefined?history[0]:(await s.query('SELECT version,candidate_id FROM public.candidate_selections WHERE tenant_id=$1 ORDER BY version DESC LIMIT 1',[s.tenantId])).rows[0];
 return{next:{results:foundResults.length>100?results.at(-1).id:null,history:foundHistory.length>100?history.at(-1).version:null},activeCandidateId:latest?.candidate_id??null,catalog:catalog.list(s.tenantId).map(c=>({candidateId:c.candidateId,configHash:c.config.hash})),results:results.map(r=>({id:r.id,candidateId:r.candidate_id,configHash:r.config_hash,createdAt:r.created_at,...assessment(r.envelope,s.tenantId)})),history:history.map(r=>({version:r.version,candidateId:r.candidate_id,configHash:r.config_hash,operation:r.operation,targetVersion:r.target_version,reason:r.reason,evidenceHash:r.evidence_hash,createdAt:r.created_at})),version:latest?.version??0,comparison:'different_holdouts_not_comparable',criteria:{minimumCases:30,utilityGreaterThan:0.85,coverage:1,citationIntegrity:1,completeHumanReview:true,knownCost:true}};});},
 async register(input){if(!strict(input,['operation','envelope','requestId'])||!uuid(input.requestId))reject('input_invalid');return tx(async s=>{const p=verifySummary(input.envelope,s.tenantId,env),entry=catalog.get(s.tenantId,p.candidateId);if(!entry||entry.config.hash!==p.configHash)reject('configuration_changed',409);const old=(await s.query('SELECT envelope FROM public.candidate_results WHERE tenant_id=$1 AND id=$2',[s.tenantId,input.requestId])).rows[0];if(old){if(hashValue(old.envelope)!==hashValue(input.envelope))reject('request_conflict',409);return{id:input.requestId,replay:true};}await s.query('INSERT INTO public.candidate_results(tenant_id,id,actor_id,candidate_id,config_hash,envelope) VALUES($1,$2,$3,$4,$5,$6)',[s.tenantId,input.requestId,s.userId,p.candidateId,p.configHash,JSON.stringify(input.envelope)]);return{id:input.requestId,replay:false};});},
 async change(input){if(!strict(input,['operation','resultId','targetVersion','expectedVersion','confirmed','reason','evidenceHash'])||!['select','rollback'].includes(input.operation)||input.confirmed!==true||!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<0||!digest(input.evidenceHash)||!['validated_evaluation','incident_recovery','quality_regression'].includes(input.reason))reject('input_invalid');return tx(async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':candidate-selection']);const history=await rows(s,'candidate_selections'),current=history[0];if((current?.version??0)!==input.expectedVersion)reject('version_conflict',409);let target=null,resultId=input.resultId,selectedHash;const baseHash=current?.base_hash??base(s.tenantId).hash;
 if(input.operation==='rollback'){if(!Number.isInteger(input.targetVersion)||input.targetVersion<0||input.targetVersion>=input.expectedVersion||input.resultId!==undefined)reject('rollback_invalid');if(input.targetVersion===0){selectedHash=base(s.tenantId).hash;if(selectedHash!==baseHash)reject('configuration_changed',409);resultId=null;}else{target=(await s.query('SELECT * FROM public.candidate_selections WHERE tenant_id=$1 AND version=$2',[s.tenantId,input.targetVersion])).rows[0];if(!target)reject('rollback_invalid');resultId=target.result_id;selectedHash=target.config_hash;if(resultId===null&&base(s.tenantId).hash!==selectedHash)reject('configuration_changed',409);}}
 else if(input.targetVersion!==undefined||!uuid(resultId))reject('input_invalid');let candidateId=null;if(resultId){const result=(await s.query('SELECT * FROM public.candidate_results WHERE tenant_id=$1 AND id=$2',[s.tenantId,resultId])).rows[0];if(!result)reject('result_unavailable',404);const p=verifySummary(result.envelope,s.tenantId,env),entry=catalog.get(s.tenantId,p.candidateId);if(!eligibility(p,entry,runtimeCode).eligible)reject('promotion_blocked',409);candidateId=p.candidateId;selectedHash=entry.config.hash;}
 await s.query('INSERT INTO public.candidate_selections(tenant_id,version,actor_id,candidate_id,config_hash,base_hash,result_id,operation,target_version,reason,evidence_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[s.tenantId,input.expectedVersion+1,s.userId,candidateId,selectedHash,baseHash,resultId,input.operation,input.targetVersion??null,input.reason,input.evidenceHash]);return{version:input.expectedVersion+1,candidateId,configHash:selectedHash};});}
 };
}
