'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Brief,BriefList,BriefProblem} from '../../../../../packages/briefs/index.mjs';
import type {Scope,Metric} from '../../lib/workspace/contracts';
import {formatMinorUnits} from '../../../../../packages/metrics/money.mjs';
import {SharedFilters} from '../workspace/shared-filters';
type Filters=Scope & {basis:string;exponent?:number};
type Page=BriefList;
const money=(value:string|null,currency:string,exponent:number)=>value===null?'Desconocido':formatMinorUnits(value,currency,exponent);
function clean(value:string){const q=new URLSearchParams(value);for(const k of ['resource','format','problem_id','detail_hash','root_kind','root_id','component_id','event_id','q','status','order'])q.delete(k);return q;}
function defaults(value:string):Filters{const q=clean(value),now=new Date();return {date_start:q.get('date_start')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),date_end:q.get('date_end')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString(),timezone:'UTC',date_basis:q.get('date_basis')??'occurred_at',currency:q.get('currency')??'USD',basis:q.get('basis')??'net',sku:q.getAll('sku'),source:q.getAll('source'),snapshot_id:q.get('snapshot_id'),...(q.has('exponent')?{exponent:Number(q.get('exponent'))}:{})};}
function pinned(scope:Scope,snapshotId:string,scopeHash:string){const q=new URLSearchParams({date_start:scope.date_start.slice(0,10),date_end:scope.date_end.slice(0,10),timezone:scope.timezone,date_basis:scope.date_basis,currency:scope.currency,basis:scope.basis??'net',snapshot_id:snapshotId,scope_hash:scopeHash});if(scope.exponent!==null&&scope.exponent!==undefined)q.set('exponent',String(scope.exponent));for(const v of scope.sku)q.append('sku',v);for(const v of scope.source)q.append('source',v);return q;}
function message(status:number){return [401,403].includes(status)?'Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.':status===404?'El brief o sus fuentes ya no están disponibles con tus permisos.':status===409?'La publicación, las fuentes o la versión cambió. Actualiza antes de volver a generar.':status===400?'Revisa el alcance y la comparación seleccionada.':'No se pudo verificar la operación. Actualiza para comprobar el estado guardado.';}
const comparisonReason=(reason:string)=>({NO_COMPARISON_SELECTED:'No se seleccionó un periodo anterior.',PERIODS_NOT_PREVIOUS_DISJOINT:'El periodo de comparación debe terminar antes de comenzar el actual.',WINDOW_DURATION_MISMATCH:'Los periodos tienen distinta duración.',METRIC_VERSION_MISMATCH:'Los periodos usan versiones de cálculo diferentes.',SOME_METRICS_UNKNOWN:'Algunas medidas no tienen datos suficientes para estimar su diferencia.'}[reason]??'Los datos requieren una revisión antes de compararse.');
function validBrief(value:Brief){return Boolean(value?.id&&Number.isInteger(value.version)&&value.contentHash&&value.document?.snapshotId&&value.document?.scopeHash&&Array.isArray(value.document.metrics));}
function Figures({metrics}:{metrics:Metric[]}){return <dl className="metric-grid">{metrics.map((metric,index)=><div key={metric.kind+':'+index}><dt>{metric.label}</dt><dd>{money(metric.amount_minor,metric.currency,metric.exponent)}{metric.amount_minor===null&&metric.known_subtotal!==null&&<small>Subtotal conocido: {money(metric.known_subtotal,metric.currency,metric.exponent)}; no es el total.</small>}<small style={{overflowWrap:'anywhere'}}>Fuente: {metric.source_ref}</small></dd></div>)}</dl>;}
function Problem({item}:{item:BriefProblem}){return <article className="record-card" aria-label={'Problema del brief: '+item.title}><h3>{item.href.startsWith('/')&&!item.href.startsWith('//')?<Link href={item.href}>{item.title}</Link>:item.title}</h3><p>Versión {item.version} · {item.rankingBasis==='published_priority'?'Prioridad publicada':'Orden por cantidad de evidencia, sin estimación de riesgo'} · {item.evidenceCount} citas</p><Figures metrics={item.metrics}/><details><summary>Evidencia de {item.title}</summary>{item.evidence.map((e,i)=><figure key={e.runId+':'+e.messageRevisionId+':'+i}><blockquote>{e.quote}</blockquote><figcaption>{e.role} · {e.category} · Revisión {e.messageRevisionId}</figcaption></figure>)}</details></article>;}
function Document({brief}:{brief:Brief}){const d=brief.document;return <article aria-label={'Brief versión '+brief.version}>
 <h2>Brief ejecutivo · Versión {brief.version}</h2><p>Creado: {brief.createdAt} · Corte: {d.asOf}</p><p className="snapshot">Publicación: {d.snapshotId} · Alcance: {d.scopeHash}</p><p>Periodo: {d.scope.date_start} a {d.scope.date_end} (fin exclusivo) · {d.scope.timezone} · Base: {d.scope.basis} · {d.scope.currency}</p><p>Cobertura: {d.coverage}{d.watermark?' · Actualización: '+d.watermark:''}</p>{brief.stale&&<p role="status">Versión histórica: hay cambios posteriores. Conserva las cifras y fuentes de su generación.</p>}
 <section aria-label="Cifras del brief"><h3>Cifras observadas</h3><Figures metrics={d.metrics}/><p>La exposición no representa pérdida ni ahorro. No se suman los importes de problemas compartidos.</p></section>
 <section aria-label="Tres prioridades del brief"><h3>Tres prioridades</h3>{d.top3.length?d.top3.map(item=><Problem key={item.id} item={item}/>):<p>No hay problemas autorizados en este alcance.</p>}</section>
 <section aria-label="Revisión crítica del brief"><h3>Revisión crítica</h3><p>Se presenta separada de la clasificación económica.</p>{d.critical.length?d.critical.map(item=><Problem key={item.id} item={item}/>):<p>No se identificaron problemas críticos en la evidencia disponible de este corte.</p>}</section>
 <section aria-label="Cambios observados del brief"><h3>Cambios entre periodos</h3>{d.comparison.status==='available'?<><p>Comparación con la publicación {d.comparison.snapshotId}. Diferencia observada entre el periodo actual y el anterior; no acredita un efecto causado por VEXA.</p><dl className="metric-grid">{d.comparison.metrics.map((metric,i)=><div key={metric.kind+':'+i}><dt>{d.metrics.find(value=>value.kind===metric.kind)?.label??metric.kind}</dt><dd>{money(metric.deltaMinor,metric.currency,metric.exponent)}<small>Anterior: {money(metric.previousAmountMinor,metric.currency,metric.exponent)} · Actual: {money(metric.currentAmountMinor,metric.currency,metric.exponent)}</small></dd></div>)}</dl></>:<p>{d.comparison.status==='not_requested'?'No se seleccionó una publicación previa para comparar.':'Los periodos no permiten una comparación válida.'}</p>}{d.comparison.reasons.length>0&&<ul>{d.comparison.reasons.map(reason=><li key={reason}>{comparisonReason(reason)}</li>)}</ul>}</section>
 <section aria-label="Acciones del brief"><h3>Decisiones y acciones registradas</h3>{d.actions.length?<ul>{d.actions.map(action=><li key={action.kind+':'+action.id}>{action.href.startsWith('/')&&!action.href.startsWith('//')?<Link href={action.href}>{action.title}</Link>:action.title} · {action.kind==='intervention'?'Intervención':'Recomendación'} · Versión {action.version} · {action.status}<p>{action.summary}</p><p>Responsable: {action.ownerId??'Sin asignar'}</p></li>)}</ul>:<p>No hay acciones registradas para este alcance.</p>}</section>
 <section aria-label="Límites del brief"><h3>Límites e interpretación</h3><ul>{d.limits.map(limit=><li key={limit}>{limit}</li>)}</ul><p>Pronóstico: no estimable. {d.forecast.reason}</p><p>Contenido generado con plantilla determinística. Generar y descargar no envía correos.</p></section>
 <details><summary>Identidad de la versión</summary><p>Documento: {brief.id}</p><p>Plantilla: {d.templateVersion}</p><p>Hash del contenido: {brief.contentHash}</p><p>Hash de entradas: {brief.inputHash}</p>{brief.previousId&&<Link href={'/briefs/'+brief.previousId}>Ver versión anterior</Link>}</details>
 </article>;}
export function BriefsPanel({initialQuery,initialId}:{initialQuery:string;initialId?:string}){
 const [query,setQuery]=useState(clean(initialQuery).toString()),[scope,setScope]=useState<Filters>(()=>defaults(initialQuery)),[page,setPage]=useState<Page|null>(null),[selected,setSelected]=useState<Brief|null>(null),[comparison,setComparison]=useState(''),[busy,setBusy]=useState(true),[empty,setEmpty]=useState(false),[locked,setLocked]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const generation=useRef(0),controller=useRef<AbortController|null>(null),current=useRef(query),pending=useRef(false),keys=useRef(new Map<string,string>());
 const invalidate=useCallback(()=>{controller.current?.abort();generation.current++;pending.current=false;},[]);
 const load=useCallback(async(input:string)=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;pending.current=true;setBusy(true);setError('');setNotice('');setPage(null);setSelected(null);setEmpty(false);
  try{let requested=clean(input),detail:Brief|null=null;
   if(initialId){const response=await fetch('/api/briefs/'+encodeURIComponent(initialId),{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(message(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;detail=json.data as Brief;if(!validBrief(detail)||detail.id!==initialId)throw Error('No se pudo verificar la versión solicitada.');requested=pinned(detail.document.scope,detail.document.snapshotId,detail.document.scopeHash);current.current=requested.toString();setScope({...detail.document.scope,exponent:detail.document.scope.exponent??undefined});setPage({items:[detail],snapshotId:detail.document.snapshotId,scopeHash:detail.document.scopeHash,scope:detail.document.scope,canGenerate:false,expectedPreviousId:null,comparisonOptions:[],unavailableCount:0,totalCount:1,nextCursor:null});setSelected(detail);setLocked(false);return;}
   if(!requested.get('snapshot_id')||!requested.get('scope_hash')){const resolve=clean(input);resolve.delete('cursor');resolve.set('resource','problems');const response=await fetch('/api/workspace?'+resolve,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(message(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const meta=json.data?.meta;if(!meta?.scope)throw Error('No se pudo verificar el alcance publicado.');setScope({...meta.scope,exponent:meta.scope.exponent??undefined});if(!meta.snapshot_id||!meta.scope_hash){setEmpty(true);return;}requested=pinned(meta.scope,meta.snapshot_id,meta.scope_hash);}
   const response=await fetch('/api/briefs?'+requested,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(message(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const data=json.data as Page;if(data?.snapshotId!==requested.get('snapshot_id')||data?.scopeHash!==requested.get('scope_hash')||!Array.isArray(data.items)||data.items.some(item=>!validBrief(item)||item.document.snapshotId!==data.snapshotId||item.document.scopeHash!==data.scopeHash))throw Error('El historial recibido no corresponde a este alcance.');current.current=requested.toString();window.history.replaceState(null,'',window.location.pathname+'?'+requested);setScope({...data.scope,exponent:data.scope.exponent??undefined});setPage(data);setSelected(detail);setComparison(previous=>data.comparisonOptions.some(option=>option.query===previous&&option.eligible)?previous:'');setLocked(false);
  }catch(e){if(!abort.signal.aborted&&epoch===generation.current){setPage(null);setSelected(null);setError(e instanceof Error?e.message:message(503));}}
  finally{if(!abort.signal.aborted&&epoch===generation.current){pending.current=false;setBusy(false);}}
 },[initialId]);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)void load(query);});return()=>{active=false;invalidate();};},[query,load,invalidate]);
 useEffect(()=>{const back=()=>{invalidate();const next=clean(window.location.search.slice(1)).toString();current.current=next;if(next===query)void load(next);else setQuery(next);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[query,load,invalidate]);
 const navigate=(q:URLSearchParams)=>{invalidate();setPage(null);setSelected(null);setBusy(true);setComparison('');const next=q.toString();current.current=next;window.history.pushState(null,'','/briefs?'+next);if(next===query)void load(next);else setQuery(next);};
 const apply=(q:URLSearchParams)=>{const old=clean(current.current);if(['date_start','date_end','currency','basis','exponent'].some(k=>(old.get(k)??'')!==(q.get(k)??''))&&q.get('snapshot_id')===scope.snapshot_id)q.delete('snapshot_id');q.delete('scope_hash');q.delete('cursor');navigate(q);};
 const act=async(kind:'generate'|'read'|'json'|'html',brief?:Brief)=>{if(pending.current||!page||(kind==='generate'&&locked))return;pending.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;setBusy(true);setError('');setNotice('');
  try{let url='/api/briefs',body:string|undefined;const download=kind==='json'||kind==='html';if(kind==='generate'){const q=clean(current.current);q.delete('cursor');q.delete('limit');const payload={operation:'generate',query:q.toString(),comparisonQuery:comparison||null,expectedPreviousId:page.expectedPreviousId};const signature=JSON.stringify(payload);let key=keys.current.get(signature);if(!key){key=crypto.randomUUID();keys.current.set(signature,key);}body=JSON.stringify({...payload,requestKey:key});}else{if(!brief)return;url+='/'+brief.id+(download?'/export?format='+kind:'');}
   const response=await fetch(url,{method:body?'POST':'GET',cache:'no-store',signal:abort.signal,headers:body?{'Content-Type':'application/json'}:undefined,body});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok){if([401,403,404,409].includes(response.status)){setPage(null);setSelected(null);}if(kind==='generate')setLocked(true);throw Error(message(response.status));}
   if(download){const blob=await response.blob();if(abort.signal.aborted||epoch!==generation.current)return;if(!response.headers.get('content-disposition')?.startsWith('attachment')||!response.headers.get('content-type')?.includes(kind==='json'?'application/json':'text/html'))throw Error('No se pudo verificar el archivo de descarga.');const object=URL.createObjectURL(blob),a=document.createElement('a');a.href=object;a.download='vexa-brief-'+brief!.id+'.'+kind;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(object),0);setNotice('Descarga autorizada preparada.');}
   else{const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const data=json.data as Brief;if(!validBrief(data)||data.document.snapshotId!==page.snapshotId||data.document.scopeHash!==page.scopeHash||(kind==='read'&&data.id!==brief?.id))throw Error('La versión recibida no corresponde al alcance solicitado.');setSelected(data);if(kind==='generate'){setPage({...page,expectedPreviousId:data.id,items:[data,...page.items.filter(item=>item.id!==data.id)]});setNotice('Brief guardado y verificado. No se envió correo.');}}
  }catch(e){if(!abort.signal.aborted&&epoch===generation.current){if(kind==='generate')setLocked(true);setError(e instanceof Error?e.message:message(503));}}
  finally{if(!abort.signal.aborted&&epoch===generation.current){pending.current=false;setBusy(false);}}
 };
 return <section aria-label="Brief ejecutivo"><p className="eyebrow">Prioridades y decisiones</p><h1>Brief ejecutivo</h1><p>Versiones guardadas con cifras, evidencia y acciones de un alcance definido. Cada descarga comprueba el acceso vigente.</p>
  {!initialId&&<SharedFilters key={JSON.stringify(scope)} scope={scope} onApply={apply}/>}<button disabled={busy} onClick={()=>void load(current.current)}>Actualizar briefs</button>{initialId&&<p><Link href={selected?'/briefs?'+pinned(selected.document.scope,selected.document.snapshotId,selected.document.scopeHash):'/briefs'}>Volver al historial del alcance</Link></p>}
  {busy&&<p role="status">Verificando brief…</p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{locked&&<p>Actualiza para comprobar la versión guardada antes de intentar otra generación.</p>}{empty&&<p>No hay una publicación para este alcance. <Link href="/economics">Revisar publicaciones</Link></p>}
  {page&&<><p className="snapshot">Publicación: {page.snapshotId} · Alcance: {page.scopeHash}</p>{page.canGenerate&&!initialId&&<form className="action-form" aria-label="Generar brief" onSubmit={event=>{event.preventDefault();void act('generate');}}><label htmlFor="brief-comparison">Publicación previa para comparar</label><select id="brief-comparison" disabled={busy||locked} value={comparison} onChange={event=>setComparison(event.target.value)}><option value="">Sin comparación previa</option>{page.comparisonOptions.map(option=><option key={option.snapshotId+':'+option.scopeHash} value={option.query} disabled={!option.eligible}>{option.start} a {option.end} · {option.snapshotId}{!option.eligible?' · No comparable: '+option.reasons.map(comparisonReason).join(' '):''}</option>)}</select><button disabled={busy||locked}>Generar versión</button><small>Los cambios comparan periodos compatibles. No demuestran ahorro causado por la intervención.</small></form>}
   <section aria-label="Historial de briefs"><h2>Versiones guardadas</h2>{!page.items.length&&<p>No hay briefs guardados y accesibles para este alcance.</p>}{page.unavailableCount>0&&<p>Algunas versiones ya no están disponibles con el acceso actual.</p>}<ul>{page.items.map(brief=><li key={brief.id}><button disabled={busy} onClick={()=>void act('read',brief)}>Abrir versión {brief.version}</button> · {brief.createdAt} <Link href={'/briefs/'+brief.id}>Enlace a versión {brief.version}</Link></li>)}</ul>{page.nextCursor&&!initialId&&<button disabled={busy} onClick={()=>{const q=clean(current.current);q.set('cursor',page.nextCursor!);navigate(q);}}>Más versiones</button>}</section>
   {selected&&<>{locked&&<p role="status">Última versión verificada. La nueva generación no está confirmada; actualiza antes de usarla como versión vigente.</p>}<Document brief={selected}/><div className="action-form" role="group" aria-label="Exportar brief"><button disabled={busy} onClick={()=>void act('json',selected)}>Descargar JSON</button><button disabled={busy} onClick={()=>void act('html',selected)}>Descargar HTML</button><p>El HTML descargado se puede imprimir. El archivo conserva la versión seleccionada.</p></div></>}
  </>}
 </section>;
}
