import fs from'node:fs';import os from'node:os';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{execFileSync}from'node:child_process';import{randomUUID}from'node:crypto';import{hash,need}from'./contract.mjs';
const originalFetch=globalThis.fetch;
const base=path.dirname(fileURLToPath(import.meta.url));
function verifyFile(root,item){need(typeof item.path==='string'&&!path.isAbsolute(item.path)&&item.path.split('/').every(x=>x&&x!=='.'&&x!=='..')&&/^[a-f0-9]{64}$/.test(item.sha256),'S01_CONTROL_MANIFEST');const file=path.join(root,item.path),s=fs.lstatSync(file);need(s.isFile()&&!s.isSymbolicLink()&&hash(fs.readFileSync(file))===item.sha256,'S01_CONTROL_DRIFT');}
export async function prepareLiveControl(){
 need(arguments.length===0,'S01_BOOTSTRAP_OVERRIDES');need(process.versions.node.split('.')[0]==='22','S01_NODE22_REQUIRED');const raw=fs.readFileSync(path.join(base,'dependencies.json')),manifest=JSON.parse(raw);need(manifest.schema==='s01-external-control-pins-v1'&&Array.isArray(manifest.files),'S01_CONTROL_MANIFEST');for(const f of manifest.files.filter(x=>!x.path.startsWith('node_modules/')))verifyFile(base,f);
 const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'rovaq-s01-control-'));fs.chmodSync(runtime,0o700);const owner=randomUUID(),marker=path.join(runtime,'.owner');fs.writeFileSync(marker,owner,{flag:'wx',mode:0o600});const audit=runtime+'.cleanup.json',fd=fs.openSync(audit,'wx',0o600);let closed=false,ready=false;const record=value=>{const b=Buffer.from(JSON.stringify({schema:'s01-control-bootstrap-v1',controlManifestSha256:hash(raw),runtime,ready,...value})+'\n');fs.writeSync(fd,b,0,b.length,0);fs.ftruncateSync(fd,b.length);fs.fsyncSync(fd);};record({removed:false,status:'preparing'});
 const close=()=>{if(closed)return;try{need(fs.readFileSync(marker,'utf8')===owner&&!fs.lstatSync(runtime).isSymbolicLink(),'S01_CONTROL_OWNERSHIP');fs.rmSync(runtime,{recursive:true,force:false});need(!fs.existsSync(runtime),'S01_CONTROL_CLEANUP');record({removed:true,status:'closed'});}catch{record({removed:false,status:'cleanup_failed'});throw Object.assign(new Error('S01_CONTROL_CLEANUP'),{code:'S01_CONTROL_CLEANUP'});}finally{closed=true;fs.closeSync(fd);}};
 try{
  for(const f of manifest.files.filter(x=>!x.path.startsWith('node_modules/'))){const dest=path.join(runtime,f.path);fs.mkdirSync(path.dirname(dest),{recursive:true,mode:0o700});fs.copyFileSync(path.join(base,f.path),dest,fs.constants.COPYFILE_EXCL);fs.chmodSync(dest,0o600);}
  fs.writeFileSync(path.join(runtime,'dependencies.json'),raw,{flag:'wx',mode:0o600});
  // No inherited tokens, HMAC key, approval/config variables or package lifecycle scripts.
  const env={PATH:path.dirname(process.execPath)+path.delimiter+(process.env.PATH??''),HOME:process.env.HOME??'',TMPDIR:os.tmpdir(),npm_config_userconfig:path.join(runtime,'empty.npmrc'),npm_config_audit:'false',npm_config_fund:'false',npm_config_update_notifier:'false',npm_config_logs_max:'0',npm_config_logs_dir:path.join(runtime,'npm-logs')};fs.writeFileSync(env.npm_config_userconfig,'',{flag:'wx',mode:0o600});
  execFileSync('npm',['ci','--offline','--ignore-scripts','--no-audit','--no-fund'],{cwd:runtime,env,stdio:'pipe',timeout:20000,killSignal:'SIGKILL',maxBuffer:1024*1024});
  for(const f of manifest.files)verifyFile(runtime,f);need(globalThis.fetch===originalFetch,'S01_CAPTURE_ORDER');const module=await import(pathToFileURL(path.join(runtime,'live.mjs')).href);ready=true;record({removed:false,status:'ready'});return Object.freeze({runLive:module.runLive,close,cleanupReceipt:audit});
 }catch(e){try{close();}catch{throw Object.assign(new Error('S01_CONTROL_CLEANUP'),{code:'S01_CONTROL_CLEANUP'});}throw Object.assign(new Error(e?.code?.startsWith('S01_')?e.code:'S01_OFFLINE_BOOTSTRAP_FAILED'),{code:e?.code?.startsWith('S01_')?e.code:'S01_OFFLINE_BOOTSTRAP_FAILED',cleanupReceipt:audit});}
}
