import fs from 'node:fs';import{execFileSync}from'node:child_process';import path from'node:path';import{createHash}from'node:crypto';
export const hash=x=>createHash('sha256').update(x).digest('hex');
export const need=(v,c)=>{if(!v)throw Object.assign(new Error(c),{code:c});};
const hex=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),id=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,1024}$/.test(v),decimal=v=>typeof v==='string'&&/^[1-9][0-9]*$/.test(v),uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(v);
const exact=(x,required,optional=[])=>{need(x&&typeof x==='object'&&!Array.isArray(x),'S01_SCHEMA');need(required.every(k=>Object.hasOwn(x,k))&&Object.keys(x).every(k=>[...required,...optional].includes(k)),'S01_SCHEMA');};
export function privateJSON(file,candidate){need(typeof file==='string'&&path.isAbsolute(file),'S01_PRIVATE_PATH');const root=fs.realpathSync(candidate),real=fs.realpathSync(file);need(real!==root&&!real.startsWith(root+path.sep),'S01_OUTSIDE_CANDIDATE');const fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const st=fs.fstatSync(fd);need(st.isFile()&&(st.mode&0o777)===0o600&&st.size<=8*1024*1024,'S01_PRIVATE_FILE');const raw=Buffer.alloc(st.size+1);let n=0;while(n<raw.length){const count=fs.readSync(fd,raw,n,raw.length-n,n);if(!count)break;n+=count;}need(n===st.size,'S01_PRIVATE_SIZE');let value;try{value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw.subarray(0,n)));}catch{need(false,'S01_PRIVATE_JSON');}return{value,bytes:raw.subarray(0,n)};}finally{fs.closeSync(fd);}}
export function validateConfig(c,approval,profile,now=Date.now()){
 exact(c,['version','authentication','authorization_ref','account_id','app_id','tenant_id','connection_id','reviewer','implementer','expires_at','reconciliation_file','reconciliation_sha256','export_context_file','export_context_sha256','profile','receipt_file','candidate_manifest_file','candidate_manifest_sha256'],['inbox_id','archived']);
 need(c.version==='v5'&&c.profile===profile,'S01_VERSION_PROFILE');need(['private_app','oauth'].includes(c.authentication),'S01_AUTHENTICATION_MODE');need(typeof c.authorization_ref==='string'&&c.authorization_ref.length>10&&c.authorization_ref===approval,'S01_APPROVAL_REFERENCE');need(decimal(c.account_id)&&decimal(c.app_id)&&uuid(c.tenant_id)&&uuid(c.connection_id),'S01_SCOPE');need(typeof c.reviewer==='string'&&c.reviewer.trim().length>2&&typeof c.implementer==='string'&&c.implementer.trim().length>0&&c.reviewer.trim()!==c.implementer.trim(),'S01_INDEPENDENT_REVIEWER');need(typeof c.expires_at==='string'&&Date.parse(c.expires_at)>now&&Date.parse(c.expires_at)<now+24*3600000,'S01_APPROVAL_WINDOW');need(['reconciliation_sha256','export_context_sha256','candidate_manifest_sha256'].every(k=>hex(c[k])),'S01_PINS');need(c.inbox_id===undefined||decimal(c.inbox_id),'S01_INBOX');need(c.archived===undefined||typeof c.archived==='boolean','S01_ARCHIVED');return c;
}
export function validateReference(r,c,context){
 exact(r,['version','origin','account_id','reviewer','profile','export_context_sha256','threads','messages']);need(r.version==='v5'&&r.origin==='authorized-ui-or-export'&&r.account_id===c.account_id&&r.reviewer===c.reviewer&&r.profile===c.profile&&r.export_context_sha256===c.export_context_sha256,'S01_REFERENCE_PROVENANCE');need(Array.isArray(r.threads)&&r.threads.length>=20&&r.threads.length<=1000&&r.threads.every(id)&&new Set(r.threads).size===r.threads.length,'S01_TWENTY_THREADS');need(Array.isArray(r.messages)&&r.messages.length>=20&&r.messages.length<=10000,'S01_REFERENCE_MESSAGES');const seen=new Set();for(const m of r.messages){exact(m,['id','thread','digest']);need(id(m.id)&&r.threads.includes(m.thread)&&hex(m.digest),'S01_REFERENCE_MESSAGE');const k=JSON.stringify([m.thread,m.id]);need(!seen.has(k),'S01_REFERENCE_DUPLICATE');seen.add(k);context.get({accountId:c.account_id,threadId:m.thread,messageId:m.id});}need(context.size===r.messages.length,'S01_CONTEXT_INVENTORY');return r;
}
export function reserveReceipt(file,candidate){need(typeof file==='string'&&path.isAbsolute(file),'S01_RECEIPT_PATH');const parent=path.dirname(file),st=fs.lstatSync(parent);need(st.isDirectory()&&!st.isSymbolicLink()&&(st.mode&0o077)===0,'S01_RECEIPT_DIRECTORY');const real=path.join(fs.realpathSync(parent),path.basename(file)),root=fs.realpathSync(candidate);need(real!==root&&!real.startsWith(root+path.sep),'S01_RECEIPT_OUTSIDE_CANDIDATE');const fd=fs.openSync(file,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);let closed=false;const write=value=>{need(!closed,'S01_RECEIPT_CLOSED');const b=Buffer.from(JSON.stringify(value,null,2)+'\n');fs.writeSync(fd,b,0,b.length,0);fs.ftruncateSync(fd,b.length);fs.fsyncSync(fd);};write({schema:'s01-live-v5-receipt',status:'started',formalAcceptance:false});return{write,close(){if(!closed){closed=true;fs.closeSync(fd);}}};}
export function verifyCandidateManifest(doc,candidate){exact(doc,['schema','files']);need(doc.schema==='s01-candidate-source-pins-v1'&&Array.isArray(doc.files)&&doc.files.length>0&&doc.files.length<=10000,'S01_SOURCE_MANIFEST');const root=fs.realpathSync(candidate),seen=new Set();for(const item of doc.files){exact(item,['path','sha256']);need(typeof item.path==='string'&&!path.isAbsolute(item.path)&&item.path.split('/').every(x=>x&&x!=='.'&&x!=='..')&&hex(item.sha256)&&!seen.has(item.path),'S01_SOURCE_PIN');seen.add(item.path);const file=path.join(root,item.path),st=fs.lstatSync(file);need(st.isFile()&&!st.isSymbolicLink()&&fs.realpathSync(file).startsWith(root+path.sep),'S01_SOURCE_FILE');need(hash(fs.readFileSync(file))===item.sha256,'S01_SOURCE_DRIFT');}need(seen.has('packages/connectors/index.mjs'),'S01_SOURCE_ENTRY');const tracked=execFileSync('git',['-C',root,'ls-files','--cached','-z'],{encoding:'utf8',maxBuffer:8*1024*1024}).split('\0').filter(Boolean);need(tracked.length===seen.size&&tracked.every(f=>seen.has(f)),'S01_SOURCE_INVENTORY');return seen;}
