// SYN-testable orchestration. Native facade never accepts these dependencies from caller.
import{performance}from'node:perf_hooks';import{need}from'./contract.mjs';
export async function introspect(fetcher,c,token,outerSignal){
 const controller=new AbortController(),signal=AbortSignal.any([outerSignal,controller.signal]),end=performance.now()+10000;let reader,timer;
 const check=()=>need(!signal.aborted&&performance.now()<end,'S01_INTROSPECTION_TIMEOUT');
 const abortPromise=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(Object.assign(new Error('S01_INTROSPECTION_TIMEOUT'),{code:'S01_INTROSPECTION_TIMEOUT'}));},10000);signal.addEventListener('abort',()=>reject(Object.assign(new Error('S01_INTROSPECTION_ABORT'),{code:'S01_INTROSPECTION_ABORT'})),{once:true});});
 try{return await Promise.race([(async()=>{check();const priv=c.authentication==='private_app';const url=priv?'https://api.hubapi.com/oauth/v2/private-apps/get/access-token-info':`https://api.hubapi.com/oauth/v1/access-tokens/${encodeURIComponent(token)}`;const r=await fetcher(url,{method:priv?'POST':'GET',redirect:'manual',signal,...(priv?{headers:{'content-type':'application/json'},body:JSON.stringify({tokenKey:token})}:{})});check();need(r.status===200&&!r.redirected&&r.body,'S01_INTROSPECTION_HTTP');reader=r.body.getReader();const chunks=[];let size=0;while(true){check();const part=await reader.read();check();if(part.done)break;size+=part.value.byteLength;need(size<=1024*1024,'S01_INTROSPECTION_LIMIT');chunks.push(part.value);}const m=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks)));check();const hub=priv?m.hubId:m.hub_id,app=priv?m.appId:m.app_id;need(Number.isSafeInteger(hub)&&hub>0&&Number.isSafeInteger(app)&&app>0&&String(hub)===c.account_id&&String(app)===c.app_id&&(priv||m.token_type==='access'),'S01_LIVE_ACCOUNT_APP_MISMATCH');need(Array.isArray(m.scopes)&&m.scopes.includes('conversations.read'),'S01_LIVE_SCOPE_MISSING');return Object.freeze({scopes:Object.freeze([...m.scopes])});})(),abortPromise]);}finally{clearTimeout(timer);controller.abort();void reader?.cancel().catch(()=>{});}
}
export function guardRequest(input,init,{threadIds,archived,token}){
 let u;try{u=new URL(input);}catch{need(false,'S01_ROUTE');}need(u.origin==='https://api.hubapi.com'&&!u.username&&!u.password&&!u.hash,'S01_HOST_ALLOWLIST');need(init?.method==='GET'&&init.redirect==='manual'&&init.signal instanceof AbortSignal&&!init.body,'S01_READONLY_POLICY');need(new Headers(init.headers).get('authorization')===`Bearer ${token}`,'S01_AUTH_HEADER');const m=/^\/conversations\/v3\/conversations\/threads\/([A-Za-z0-9_-]+)(\/messages(?:\/([A-Za-z0-9_-]+)\/original-content)?)?$/.exec(u.pathname);need(m&&threadIds.has(m[1]),'S01_THREAD_SCOPE');const allowed=m[3]?[]:m[2]?['limit','archived','after']:['archived','association'];for(const[k]of u.searchParams)need(allowed.includes(k)&&u.searchParams.getAll(k).length===1,'S01_QUERY');if(!m[3])need(u.searchParams.get('archived')===String(archived),'S01_ARCHIVED_QUERY');if(!m[2])need(u.searchParams.get('association')==='TICKET','S01_TICKET_QUERY');if(m[2]&&!m[3])need(u.searchParams.get('limit')==='100','S01_LIMIT_QUERY');if(u.searchParams.has('after'))need(u.searchParams.get('after').length>0&&u.searchParams.get('after').length<=4096&&!/[\u0000-\u001f]/.test(u.searchParams.get('after')),'S01_CURSOR_QUERY');return m[3]?'original':m[2]?'messages':'thread';
}
export async function executePrepared({config:c,reference:r,token,key,createObserver,metadataFetch,loadImplementation,projectRich,verifyMessage,signal:callerSignal}){
 const started=performance.now(),wallStart=Date.now(),deadline=started+240000,controller=new AbortController(),signal=callerSignal?AbortSignal.any([controller.signal,callerSignal]):controller.signal;let timer,observer,outcome,threadRequests=0,messageRequests=0,originalRequests=0;const counts={threads:0,messages:0,events:0,records:0,pages:0};const expected=new Map(r.messages.map(x=>[JSON.stringify([x.thread,x.id]),x.digest]));const check=()=>need(!signal.aborted&&performance.now()<deadline&&Date.now()<Date.parse(c.expires_at),'S01_TOTAL_DEADLINE');timer=setTimeout(()=>controller.abort(),Math.max(1,Math.min(240000,Date.parse(c.expires_at)-wallStart)));
 let onAbort;const abortRun=new Promise((_,reject)=>{onAbort=()=>reject(Object.assign(new Error('S01_TOTAL_DEADLINE'),{code:'S01_TOTAL_DEADLINE'}));signal.addEventListener('abort',onAbort,{once:true});});
 try{return await Promise.race([(async()=>{
  check();const metadata=await introspect(metadataFetch,c,token,signal);check();
  observer=createObserver({threadIds:[...r.threads],signal,projectRich:value=>{check();const proof=projectRich(value,observer);check();return proof;}});
  const wanted=new Set(r.threads),fetch=async(input,init)=>{check();const kind=guardRequest(input,init,{threadIds:wanted,archived:c.archived??false,token});if(kind==='thread')threadRequests++;else if(kind==='messages')messageRequests++;else originalRequests++;return observer.fetch(input,init);};
  // The native facade has already captured transport before this first product import.
  const{createHubSpotAdapter}=await loadImplementation();check();need(typeof createHubSpotAdapter==='function','S01_IMPLEMENTATION');const adapter=createHubSpotAdapter({context:{tenant_id:c.tenant_id,connection_id:c.connection_id,source:'hubspot',source_account_id:c.account_id},token,version:'v3',scopes:metadata.scopes,fetch,threadIds:[...r.threads],inboxId:c.inbox_id,archived:c.archived??false,includeNotes:false,includeTickets:false,maxPages:Math.max(20,r.threads.length),maxRecords:10000,maxRetries:1,maxDelayMs:1000,timeoutMs:10000,deadlineMs:Math.min(wallStart+240000,Date.parse(c.expires_at))});
  for await(const page of adapter.pages()){
   check();need(Array.isArray(page.errors)&&page.errors.length===0&&Array.isArray(page.records),'S01_PAGE_QUARANTINE');counts.pages++;
   for(const record of page.records){check();need(record?.envelope?.tenant_id===c.tenant_id&&record.envelope.connection_id===c.connection_id&&record.envelope.source==='hubspot'&&record.envelope.source_account_id===c.account_id,'S01_PRODUCT_SCOPE');const proof=observer.verifyRecord(record);counts.records++;const type=record.envelope.entity_type;if(type==='thread')counts.threads++;else if(type==='thread_event')counts.events++;else if(type==='message'){need(record.body_complete===true,'S01_BODY_COMPLETE');const digest=expected.get(JSON.stringify([record.conversation_id,record.envelope.external_id]));need(digest,'S01_MESSAGE_OUTSIDE_REFERENCE');verifyMessage(record,proof,digest,key);counts.messages++;}else need(false,'S01_ENTITY');}
   // Deliberately NO early break when every thread ID has appeared.
  }
  check();const complete=observer.assertComplete(r.messages.map(({id,thread})=>({id,thread})));need(threadRequests>=20&&messageRequests>=20&&counts.threads===r.threads.length&&counts.messages===r.messages.length,'S01_SAMPLE_COUNTS');const stats=observer.stats();return(outcome={status:'passed',counts,requests:stats.requests,requestKinds:{thread:threadRequests,messages:messageRequests,original:originalRequests},metadataRequests:1,accountScopesVerified:true,providerPlainAndPayloadExact:true,uiSourceContentActionsReconciled:true,inventoryComplete:true,peakObserverAccountedBytes:stats.peakAccountedBytes,elapsedMs:performance.now()-started,limits:{totalMs:240000,requests:250,requestMs:10000,retries:1,responseBytes:8388608,accountedBytes:67108864,records:10000},formalAcceptance:false});
 })(),abortRun]);}finally{clearTimeout(timer);signal.removeEventListener('abort',onAbort);controller.abort();observer?.close();if(observer){const closed=observer.stats();need(closed.closed&&closed.activeBodies===0&&closed.retainedBytes===0,'S01_OBSERVER_CLEANUP');if(outcome)outcome.observerCleanup={closed:true,activeBodies:0,retainedBytes:0};}}
}
