import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{executePrepared,introspect,guardRequest}from'./driver-core.mjs';import{createObserverCore}from'./vendor/observer/observer-core.mjs';import{fragmentTree}from'./vendor/parser/fragment.mjs';import{parseExportContext,projectWithExportContext,EXPORT_PROFILE}from'./vendor/profile/export-context.mjs';import{projectionWitness,projectionWitnessDigest,messageDigest,verifyMessage}from'./vendor/dual/identity.mjs';
import{pathToFileURL}from'node:url';import path from'node:path';
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate&&path.isAbsolute(candidate),'explicit SYN candidate required');const implementation=await import(pathToFileURL(path.join(candidate,'packages/connectors/index.mjs')).href);
const sha=x=>createHash('sha256').update(x).digest('hex'),token='SYNTHETIC-TOKEN-NOT-CREDENTIAL',key='SYNTHETIC-HMAC-KEY-NOT-AUTHORIZATION-0001',stamp='2026-10-08T00:00:00Z';
function fixture(){
 const threads=Array.from({length:20},(_,i)=>String(1001+i)),messages=threads.map((thread,i)=>({id:'M'+i,conversationsThreadId:thread,type:'MESSAGE',text:'SYNTHETIC body '+i,richText:'<p>SYNTHETIC body '+i+'</p>',truncationStatus:'NOT_TRUNCATED',senders:[{actorId:'V-SYN'}],createdAt:stamp,updatedAt:stamp}));messages.push({id:'COMMENT',conversationsThreadId:threads.at(-1),type:'COMMENT',text:'SYNTHETIC private note',richText:'<p>SYNTHETIC private note</p>',truncationStatus:'NOT_TRUNCATED',senders:[{actorId:'A-SYN'}],createdAt:stamp,updatedAt:stamp});
 const doc={schema:'source-dom-export-context-v1',profile:'source_dom_export_context_reconciled',createdAt:stamp,selectionSha256:'a'.repeat(64),collectionManifestSha256:'b'.repeat(64),records:messages.map(m=>({accountId:'123',threadId:m.conversationsThreadId,messageId:m.id,captureUrl:`https://app.hubspot.com/help-desk/123/view/search/ticket/555/thread/${m.conversationsThreadId}`,baseUri:'https://app.hubspot.com/x/',baseSource:'captured-document-base-uri',htmlSha256:'c'.repeat(64),mhtmlSha256:'d'.repeat(64),collectionSha256:'e'.repeat(64)}))};const raw=Buffer.from(JSON.stringify(doc)),context=parseExportContext(raw,{sha256:sha(raw),accountId:'123'});
 const rich=({thread,id,richText})=>{const tree=fragmentTree(richText),result=projectWithExportContext({tree,treeSha256:sha(JSON.stringify(tree)),sourceSha256:sha(richText)},{accountId:'123',threadId:thread,messageId:id},context);return projectionWitness(result,{profile:EXPORT_PROFILE,contextSha256:context.sha256,accountId:'123',threadId:thread,messageId:id});};
 const reference={threads,messages:messages.map(m=>({id:m.id,thread:m.conversationsThreadId,digest:messageDigest({envelope:{entity_type:'message',external_id:m.id},conversation_id:m.conversationsThreadId,body_complete:true,role:m.type==='COMMENT'?'internal':'customer',visibility:m.type==='COMMENT'?'internal':'public',associations:[{entity_type:'ticket',external_id:'555'}]},projectionWitnessDigest(rich({thread:m.conversationsThreadId,id:m.id,richText:m.richText})),key)}))};
 const config={authentication:'private_app',account_id:'123',app_id:'456',tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',expires_at:new Date(Date.now()+60000).toISOString()};let requests=0,meta=0;
 const provider=async(input,init)=>{requests++;const u=new URL(input),thread=u.pathname.split('/')[5];if(!u.pathname.endsWith('/messages'))return Response.json({id:thread,createdAt:stamp,archived:false,threadAssociations:{associatedTicketId:'555'}});const found=messages.filter(m=>m.conversationsThreadId===thread);if(thread===threads[0])found.push({id:'EVENT',conversationsThreadId:thread,type:'ASSIGNMENT',createdAt:stamp,updatedAt:stamp});const body=thread===threads.at(-1)?u.searchParams.has('after')?{results:found.slice(1)}:{results:found.slice(0,1),paging:{next:{after:'SYN-CURSOR'}}}:{results:found};return Response.json(body);};
 const metadata=async()=>{meta++;return Response.json({hubId:123,appId:456,scopes:['conversations.read']});};
 return{config,reference,token,key,projectRich:rich,verifyMessage,createObserver:o=>createObserverCore({...o,capturedFetch:provider}),metadataFetch:metadata,loadImplementation:async()=>implementation,counts:()=>({requests,meta}),provider,metadata,messages};
}
test('SYN real adapter, synchronous parser and dual oracle consume every page/entity including final COMMENT',async()=>{const f=fixture(),r=await executePrepared(f);assert.equal(r.status,'passed');assert.deepEqual(r.counts,{threads:20,messages:21,events:1,records:42,pages:r.counts.pages});assert.equal(r.requestKinds.messages,21);assert.equal(f.counts().meta,1);assert.equal(r.formalAcceptance,false);});
test('SYN all thread IDs emitted first cannot short-circuit remaining messages',async()=>{const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:opts=>({async*pages(){const rows=[];for await(const p of implementation.createHubSpotAdapter(opts).pages())rows.push(...p.records);yield{errors:[],records:rows.filter(x=>x.envelope.entity_type==='thread')};yield{errors:[],records:rows.filter(x=>x.envelope.entity_type!=='thread')};}})});const r=await executePrepared(f);assert.equal(r.counts.messages,21);assert.equal(r.counts.pages,2);});
for(const[name,mutate]of [['text',r=>({...r,text:r.text+' altered'})],['payload',r=>({...r,payload:{...r.payload,SYN:'altered'}})],['role',r=>({...r,role:'agent'})]])test('SYN product '+name+' tamper fails independent provider fidelity',async()=>{const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:opts=>({async*pages(){for await(const p of implementation.createHubSpotAdapter(opts).pages())yield{...p,records:p.records.map(r=>r.envelope.entity_type==='message'?mutate(r):r)};}})});await assert.rejects(executePrepared(f),e=>e.code?.startsWith('OBS_'));});
test('SYN omitted event/message record fails complete emission even if all thread IDs exist',async()=>{const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:opts=>({async*pages(){for await(const p of implementation.createHubSpotAdapter(opts).pages())yield{...p,records:p.records.filter(r=>r.envelope.external_id!=='COMMENT')};}})});await assert.rejects(executePrepared(f),e=>e.code==='OBS_EMISSION_MISSING');});
test('SYN wrong UI digest fails despite exact provider text/payload',async()=>{const f=fixture();f.reference.messages[0].digest='0'.repeat(64);await assert.rejects(executePrepared(f),e=>e.code==='DUAL_UI_MISMATCH');});
test('SYN UI inventory omission cannot pass with provider fidelity',async()=>{const f=fixture();f.reference.messages.pop();await assert.rejects(executePrepared(f),e=>e.code==='S01_MESSAGE_OUTSIDE_REFERENCE');});
test('SYN errors are not accepted as partial coverage',async()=>{const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:()=>({async*pages(){yield{records:[],errors:[{code:'SYN'}]};}})});await assert.rejects(executePrepared(f),e=>e.code==='S01_PAGE_QUARANTINE');});
test('SYN metadata failure never imports product or requests conversations',async()=>{const f=fixture();let imports=0;f.metadataFetch=async()=>Response.json({hubId:999,appId:456,scopes:['conversations.read']});f.loadImplementation=async()=>{imports++;return implementation;};await assert.rejects(executePrepared(f),e=>e.code==='S01_LIVE_ACCOUNT_APP_MISMATCH');assert.equal(imports,0);assert.equal(f.counts().requests,0);});
test('SYN OAuth mode is explicit and cannot fall back to private app',async()=>{let calls=0;const c={authentication:'oauth',account_id:'123',app_id:'456'};const signal=new AbortController().signal;const m=await introspect(async(url,init)=>{calls++;assert.equal(init.method,'GET');assert.match(String(url),/oauth\/v1\/access-tokens\//);return Response.json({hub_id:123,app_id:456,token_type:'access',scopes:['conversations.read']});},c,token,signal);assert.deepEqual(m.scopes,['conversations.read']);assert.equal(calls,1);await assert.rejects(introspect(async()=>{calls++;return new Response('{}',{status:401});},c,token,signal));assert.equal(calls,2);});
test('SYN oversized metadata body fails before product',async()=>{const f=fixture();f.metadataFetch=async()=>new Response('x'.repeat(1024*1024+1));await assert.rejects(executePrepared(f),e=>e.code==='S01_INTROSPECTION_LIMIT');assert.equal(f.counts().requests,0);});
test('SYN shared abort covers metadata headers and body',async()=>{for(const body of [false,true]){const controller=new AbortController();setTimeout(()=>controller.abort(),15);await assert.rejects(introspect(async()=>body?new Response(new ReadableStream({start(){},cancel(){}})):new Promise(()=>{}),{authentication:'private_app'},token,controller.signal));}});
test('SYN route guard rejects extra scope/method/query without transport',()=>{const good='https://api.hubapi.com/conversations/v3/conversations/threads/1001?archived=false&association=TICKET',init={method:'GET',redirect:'manual',signal:new AbortController().signal,headers:{authorization:`Bearer ${token}`}},scope={threadIds:new Set(['1001']),archived:false,token};assert.equal(guardRequest(good,init,scope),'thread');for(const url of [good.replace('1001','1002'),good.replace('api.hubapi.com','evil.invalid'),good+'&extra=x',good+'&association=TICKET',good.replace('TICKET','CONTACT')])assert.throws(()=>guardRequest(url,init,scope));assert.throws(()=>guardRequest(good,{...init,method:'POST'},scope));});

test('SYN omitted thread_event also fails complete emission',async()=>{const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:opts=>({async*pages(){for await(const p of implementation.createHubSpotAdapter(opts).pages())yield{...p,records:p.records.filter(r=>r.envelope.entity_type!=='thread_event')};}})});await assert.rejects(executePrepared(f),e=>e.code==='OBS_EMISSION_MISSING');});
test('SYN shared abort terminates a stalled adapter iterator, not only fetch',async()=>{const f=fixture(),controller=new AbortController();f.signal=controller.signal;f.loadImplementation=async()=>({createHubSpotAdapter:()=>({async*pages(){await new Promise(()=>{});}})});setTimeout(()=>controller.abort(),15);await assert.rejects(executePrepared(f),e=>e.code==='S01_TOTAL_DEADLINE');});
test('SYN tenant/connection/provider/account envelope must retain configured scope',async()=>{for(const key of ['tenant_id','connection_id','source','source_account_id']){const f=fixture();f.loadImplementation=async()=>({createHubSpotAdapter:opts=>({async*pages(){for await(const p of implementation.createHubSpotAdapter(opts).pages())yield{...p,records:p.records.map(r=>({...r,envelope:{...r.envelope,[key]:'SYN-foreign'}}))};}})});await assert.rejects(executePrepared(f),e=>e.code==='S01_PRODUCT_SCOPE');}});
