// Run outside orchestration's bounded process group. Never kills a consumer or child.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {pathToFileURL} from 'node:url';
import {privateInput,directory,digest,candidateRevision,prepareControl,verifyReport,regular} from './control.mjs';
import {keyBytes,challengeInput,authenticate,controlHashes} from './receipt.mjs';
export async function waitForExecution(executable,args,{log,onStart=()=>{}}){
 const fd=fs.openSync(log,'wx',0o600);let child;const state={code:null,signal:null,error:null,interrupted:false};
 // A cancellation is sticky failure. Wait for CLI's own compensation and bounded operations.
 const interrupted=()=>{state.interrupted=true;};process.on('SIGTERM',interrupted);process.on('SIGINT',interrupted);
 try{child=spawn(executable,args,{stdio:['ignore',fd,fd],detached:true,env:{PATH:process.env.PATH,HOME:process.env.HOME,LANG:process.env.LANG}});await new Promise(resolve=>{child.once('error',()=>{state.error='EXECUTION_START_FAILED';});child.once('close',(code,signal)=>{state.code=code;state.signal=signal;resolve();});try{onStart(child.pid);}catch{state.error='EXECUTION_PROCESS_RECEIPT_FAILED';}});return state;}finally{process.removeListener('SIGTERM',interrupted);process.removeListener('SIGINT',interrupted);fs.closeSync(fd);}
}
export async function launch({controller=path.resolve(import.meta.dirname,'../..'),candidate,gateInput,executionInput,approvalReference}){
 const startedAt=new Date().toISOString(),sha=candidateRevision(candidate),gate=privateInput(gateInput),challenge=challengeInput(gate.challenge,sha,approvalReference),key=keyBytes(gate.key,candidate,controller),challengeHash=digest(fs.readFileSync(gate.challenge)),input=privateInput(executionInput),release=privateInput(input.release),authorization=privateInput(input.authorization),config=privateInput(input.config);
 assert.equal(authorization.approvalReference,approvalReference,'APPROVAL_REFERENCE_MISMATCH');assert.equal(authorization.releaseSha,sha,'CANDIDATE_RELEASE_MISMATCH');assert.equal(release.source?.commit_sha,sha,'CANDIDATE_RELEASE_MISMATCH');assert.ok(!fs.existsSync(gate.receipt),'NEW_RECEIPT_REQUIRED');assert.ok(path.isAbsolute(input.workDirectory),'ABSOLUTE_WORK_DIRECTORY_REQUIRED');
 fs.mkdirSync(input.workDirectory,{mode:0o700});directory(input.workDirectory);const driver=path.join(input.workDirectory,'examiner');fs.mkdirSync(driver,{mode:0o700});const hashes=prepareControl(controller,driver),control=controlHashes(controller);const {validate}=await import(pathToFileURL(path.join(driver,'contract.mjs')));validate(release,authorization,config);
 // Operator-prepared Playwright installation, never fetched or copied from the candidate.
 assert.ok(path.isAbsolute(input.playwrightDirectory),'PREPARED_PLAYWRIGHT_REQUIRED');const pw=fs.realpathSync(input.playwrightDirectory);regular(path.join(pw,'package.json'));const packageInfo=JSON.parse(fs.readFileSync(path.join(pw,'package.json')));assert.equal(packageInfo.name,'playwright-core');assert.match(packageInfo.version,/^1\./);const relative=path.relative(fs.realpathSync(candidate),pw);assert.ok(relative.startsWith('..'+path.sep)||path.isAbsolute(relative),'PLAYWRIGHT_OUTSIDE_CANDIDATE_REQUIRED');fs.mkdirSync(path.join(driver,'node_modules'),{mode:0o700});fs.symlinkSync(pw,path.join(driver,'node_modules/playwright-core'));
 const snapshot={};for(const [name,value]of Object.entries({release,authorization,config})){snapshot[name]=path.join(input.workDirectory,name+'.json');fs.writeFileSync(snapshot[name],JSON.stringify(value)+'\n',{flag:'wx',mode:0o600});}
 const output=path.join(input.workDirectory,'smoke'),args=[path.join(driver,'cli.mjs'),'--release',snapshot.release,'--authorization',snapshot.authorization,'--config',snapshot.config,'--out',output];if(input.cdp)args.push('--cdp',input.cdp);
 const state=await waitForExecution(process.execPath,args,{log:path.join(input.workDirectory,'execution.log'),onStart:pid=>fs.writeFileSync(path.join(input.workDirectory,'process.json'),JSON.stringify({pid,status:'running',consumerCleanupOwnedByCli:true})+'\n',{flag:'wx',mode:0o600})});fs.writeFileSync(path.join(input.workDirectory,'process-result.json'),JSON.stringify(state)+'\n',{flag:'wx',mode:0o600});assert.deepEqual(state,{code:0,signal:null,error:null,interrupted:false},'EXECUTION_OR_COMPENSATION_NOT_CONFIRMED');
 const report=privateInput(path.join(output,'report.json')),fixtureHash=digest(JSON.stringify(config.fixture));verifyReport(report,{sha,hashes,authorizationId:authorization.id,fixtureHash,out:output});assert.equal(candidateRevision(candidate),sha);assert.deepEqual(controlHashes(controller),control);challengeInput(gate.challenge,sha,approvalReference);assert.equal(digest(fs.readFileSync(gate.challenge)),challengeHash,'CHALLENGE_CHANGED');assert.equal(report.mode,authorization.environment==='local-owned'?'local-synthetic-proof':'remote-authorized','ENVIRONMENT_BINDING');for(const [name,hash]of Object.entries(hashes))assert.equal(digest(fs.readFileSync(path.join(driver,name))),hash,'EXAMINER_CHANGED');
 const payload={schema:'vexa-smoke-control-receipt-v1',status:'verified_execution',candidateSha:sha,nonce:challenge.nonce,challengeHash,approvalReference,startedAt,completedAt:new Date().toISOString(),examinerHashes:hashes,controlHashes:control,authorizationId:authorization.id,fixtureHash,output,reportHash:digest(fs.readFileSync(path.join(output,'report.json'))),process:state,inputHashes:Object.fromEntries(['release','authorization','config'].map(k=>[k,digest(fs.readFileSync(snapshot[k]))])),playwrightVersion:packageInfo.version};fs.writeFileSync(gate.receipt,JSON.stringify({payload,mac:authenticate(payload,key)})+'\n',{flag:'wx',mode:0o600});return {status:'verified_execution',candidateSha:sha,production:false};
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(import.meta.filename)){try{const result=await launch({candidate:process.env.VEXA_CANDIDATE,gateInput:process.env.VEXA_SMOKE_GATE_INPUT,executionInput:process.env.VEXA_SMOKE_EXECUTION_INPUT,approvalReference:process.env.VEXA_SMOKE_APPROVAL_REFERENCE});console.log(JSON.stringify(result));}catch{console.error('SMOKE_CONTROL_BLOCKED_OR_FAILED; inspect private execution evidence; no favorable receipt issued');process.exitCode=1;}}
