import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHmac,timingSafeEqual} from 'node:crypto';
import {privateInput,regular,digest,candidateRevision,modules,verifyReport} from './control.mjs';
const within=(root,file)=>{const relative=path.relative(fs.realpathSync(root),fs.realpathSync(file));return relative===''||(!relative.startsWith('..'+path.sep)&&relative!=='..'&&!path.isAbsolute(relative));};
export function keyBytes(file,candidate,controller){regular(file,0o600);assert.ok(!within(candidate,file)&&!within(controller,file),'CONTROL_KEY_OUTSIDE_CHECKOUT_REQUIRED');const key=fs.readFileSync(file);assert.equal(key.length,32,'CONTROL_KEY_32_BYTES_REQUIRED');return key;}
export function currentHashes(controller){return Object.fromEntries(modules.map(name=>{const f=path.join(controller,'packages/release/smoke',name);regular(f);return [name,digest(fs.readFileSync(f))];}));}
export function controlHashes(controller){return Object.fromEntries(['control.mjs','receipt.mjs','launcher.mjs','gate.mjs','control.test.mjs'].map(name=>{const f=path.join(controller,'support/F08-smoke',name);regular(f);return [name,digest(fs.readFileSync(f))];}));}
export function challengeInput(file,sha,approvalReference){const challenge=privateInput(file);assert.equal(challenge.schema,'vexa-smoke-challenge-v1');assert.match(challenge.nonce,/^[a-f0-9]{64}$/);assert.equal(challenge.candidateSha,sha,'CHALLENGE_CANDIDATE');assert.ok(approvalReference?.trim(),'REAL_APPROVAL_REFERENCE_REQUIRED');assert.equal(challenge.approvalReference,approvalReference,'APPROVAL_REFERENCE_MISMATCH');const now=Date.now(),issued=Date.parse(challenge.issuedAt),expires=Date.parse(challenge.expiresAt);assert.ok(Number.isFinite(issued)&&issued<=now&&expires>now&&expires-issued<=86400000,'CHALLENGE_EXPIRED');return challenge;}
export function authenticate(payload,key){return createHmac('sha256',key).update(JSON.stringify(payload)).digest('hex');}
export function verifyReceipt({controller,candidate,gateInput,approvalReference}){
 const input=privateInput(gateInput),sha=candidateRevision(candidate),challenge=challengeInput(input.challenge,sha,approvalReference),key=keyBytes(input.key,candidate,controller),envelope=privateInput(input.receipt);assert.match(envelope.mac??'',/^[a-f0-9]{64}$/,'RECEIPT_SIGNATURE_REQUIRED');const expected=authenticate(envelope.payload,key);assert.ok(timingSafeEqual(Buffer.from(envelope.mac,'hex'),Buffer.from(expected,'hex')),'RECEIPT_AUTHENTICATION_FAILED');
 const p=envelope.payload;assert.equal(p.schema,'vexa-smoke-control-receipt-v1');assert.equal(p.status,'verified_execution');assert.equal(p.candidateSha,sha);assert.equal(p.nonce,challenge.nonce,'NONCE_BINDING');assert.equal(p.challengeHash,digest(fs.readFileSync(input.challenge)),'CHALLENGE_BINDING');assert.deepEqual(p.examinerHashes,currentHashes(controller));assert.deepEqual(p.controlHashes,controlHashes(controller));assert.equal(p.approvalReference,approvalReference);assert.ok(Date.parse(p.startedAt)>=Date.parse(challenge.issuedAt)&&Date.parse(p.completedAt)>=Date.parse(p.startedAt)&&Date.parse(p.completedAt)<=Date.now()&&Date.parse(p.completedAt)<Date.parse(challenge.expiresAt),'RECEIPT_TIME_BINDING');assert.deepEqual(p.process,{code:0,signal:null,error:null,interrupted:false});
 const reportFile=path.join(p.output,'report.json');regular(reportFile,0o600);assert.equal(digest(fs.readFileSync(reportFile)),p.reportHash,'REPORT_HASH');const report=privateInput(reportFile);verifyReport(report,{sha,hashes:p.examinerHashes,authorizationId:p.authorizationId,fixtureHash:p.fixtureHash,out:p.output});return {status:'verified_execution',candidateSha:sha,runId:report.runId,mode:report.mode,production:false};
}
