import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {createHash,createHmac,randomUUID} from 'node:crypto';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {setup,q} from './admission-harness.mjs';
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-retention-race-repair-')),key='SYN332-ledger-signing-local-only-0123456789';console.log('RETENTION_REPAIR_EVIDENCE:'+evidence);const report={status:'running',node:process.version,checks:[],label:'SYNTHETIC local real Auth/PostgreSQL/Storage/API/browser; no remote calls'};let h,context;const sha=x=>createHash('sha256').update(x).digest('hex');const ok=(r,n,label)=>{assert.equal(r.status,n,label+': '+JSON.stringify(r.data));return r.data.data;};const check=async(name,fn)=>{const started=Date.now();await fn();report.checks.push({name,status:'pass',ms:Date.now()-started});fs.writeFileSync(path.join(evidence,'report.json'),JSON.stringify(report,null,2));console.log('PASS '+name);};
try{
 h=await setup(process.env.VEXA_CANDIDATE??process.cwd(),evidence);await h.stopWeb();await h.startWeb(false,{VEXA_RETENTION_LEDGER_KEY:key});
 const post=(operation,input={},a=h.A)=>h.request(a,'/api/recovery',{operation,...input});const worker=await h.worker();const call=async(op)=>{const r=await worker.call(op);assert.equal(r.ok,true,op+JSON.stringify(r.error));return r.value;};
 let uploadVersion=0;const upload=async(rows,expectedState='succeeded')=>{await call('heartbeat');uploadVersion++;const bytes=Buffer.from('id,text,date,role,conversation\n'+rows.map(([id,conversation])=>`${id},SYNTHETIC335-${id}-${uploadVersion},2026-09-01T00:00:00Z,customer,${conversation}`).join('\n')+'\n'),hash=sha(bytes);const v=ok(await h.request(h.A,'/api/imports',{connection_id:h.A.connection,mapping_version:'csv-message-v1',content_type:'text/csv',size:bytes.length,sha256:hash}),201,'RESERVE');assert.equal(new URL(v.upload_url).origin,h.common.VEXA_SUPABASE_URL);const put=await fetch(v.upload_url,{method:'PUT',headers:{'content-type':'text/csv'},body:bytes});assert.equal(put.status,200);await put.arrayBuffer();const mapping={columns:{id:'id',text:'text',date:'date',role:'role',conversation:'conversation'},timezone:'UTC',dateFormat:'iso'},m=ok(await h.request(h.A,`/api/imports/${v.import_id}/mapping`,{mapping,expected_version:'csv-message-v1'}),200,'MAPPING');ok(await h.request(h.A,`/api/imports/${v.import_id}/confirm`,{upload_token:m.upload_token,sha256:hash,mapping_version:m.mapping_version}),202,'CONFIRM');await call('consume');const observed=h.json(`SELECT json_build_object('state',j.state,'path',i.object_path,'hash',i.file_hash) FROM jobs j JOIN imports i ON i.id=j.import_id WHERE i.id=${q(v.import_id)}`);assert.equal(observed.state,expectedState,'REAL_WORKER_IMPORT');return {...observed,id:v.import_id};};
 const {createClient}=createRequire(path.join(h.tmp,'package.json'))('@supabase/supabase-js');const client=a=>createClient(h.common.VEXA_SUPABASE_URL,h.common.VEXA_SUPABASE_ANON_KEY,{global:{headers:{Authorization:'Bearer '+a.token}},auth:{persistSession:false,autoRefreshToken:false}}),bucket=client(h.A).storage.from('vexa-private');const exists=async(p,a=h.A)=>{const r=await fetch(h.common.VEXA_SUPABASE_URL+'/storage/v1/object/authenticated/vexa-private/'+p,{headers:{apikey:h.common.VEXA_SUPABASE_ANON_KEY,Authorization:'Bearer '+a.token}});await r.arrayBuffer();return r.status;};


 ok(await post('policy',{expectedVersion:0,backupTtlSeconds:3600}),200,'POLICY');await upload([['RACE-MESSAGE','RACE-CONVERSATION']]);
 const {createRecoveryWeb}=await import(pathToFileURL(path.join(h.built,'packages/recovery/web.mjs'))),{createRecoveryRepository}=await import(pathToFileURL(path.join(h.built,'packages/recovery/index.mjs')));
 const web=createRecoveryWeb({database:h.database(h.A),ledgerKey:key}),writer=createRecoveryRepository({database:h.database(h.A)});
 await check('artifact committed before confirmation invalidates signed scope',async()=>{
  const preview=await web.preview({connectionId:h.A.connection,entityType:'conversation',externalId:'RACE-CONVERSATION'});
  await writer.registerArtifact({connectionId:h.A.connection,entityType:'conversation',sourceKey:'RACE-CONVERSATION',class:'cache',objectPath:h.A.tenant+'/cache/before-confirm',expiresAt:Date.now()+300000});
  await assert.rejects(web.erase({token:preview.token,requestId:preview.requestId,confirmed:true}),e=>e.code==='retention_scope_changed');assert.equal(h.json('SELECT count(*)::int FROM retention_ledger'),0);
 });
 for(const direct of [false,true])await check((direct?'direct SQL':'canonical registration')+' admission serializes with erase',async()=>{
  const suffix=direct?'DIRECT':'CANONICAL',target='RACE-'+suffix;await upload([['MESSAGE-'+suffix,target]]);
  const database=h.database(h.A),writerDatabase=h.database(h.A);let armed=false,writerPromise,settled=false,artifact,writerError,blockedObserved=false;
  const input={connectionId:h.A.connection,entityType:'conversation',sourceKey:target,class:'cache',objectPath:h.A.tenant+'/cache/after-scope-'+suffix,expiresAt:Date.now()+300000};
  const interleaved={transaction:(action,fn)=>database.transaction(action,s=>fn({...s,query:async(...args)=>{const result=await s.query(...args);if(armed&&args[0].includes('SELECT public.retention_web_scope')){
   armed=false;const operation=direct?writerDatabase.transaction('retain',async writerScope=>(await writerScope.query("INSERT INTO retention_artifacts(tenant_id,connection_id,entity_type,source_key,class,object_path,expires_at,status) VALUES($1,$2,$3,$4,$5,$6,to_timestamp($7::double precision/1000),'active') RETURNING id,status",[writerScope.tenantId,input.connectionId,input.entityType,input.sourceKey,input.class,input.objectPath,input.expiresAt])).rows[0]):createRecoveryRepository({database:writerDatabase}).registerArtifact(input);
   writerPromise=operation.then(value=>{artifact=value;settled=true;},error=>{writerError=error;settled=true;});
   for(let i=0;i<80;i++){if(h.json("SELECT count(*)::int FROM pg_stat_activity WHERE wait_event_type='Lock' AND wait_event='advisory'")>0){blockedObserved=true;break;}await delay(25);}
   assert.equal(blockedObserved,true,'WRITER_MUST_WAIT_FOR_SCOPE_LOCK');assert.equal(settled,false,'WRITER_MUST_NOT_COMMIT_INSIDE_ERASE');
  }return result;}}))};
  const bound=createRecoveryWeb({database:interleaved,ledgerKey:key});const preview=await bound.preview({connectionId:h.A.connection,entityType:'conversation',externalId:target});assert.equal(preview.scope.artifacts.length,0);armed=true;
  const result=await bound.erase({token:preview.token,requestId:preview.requestId,confirmed:true});await writerPromise;if(writerError)throw writerError;assert.equal(result.state,'active_content_erased');assert.equal(artifact.status,'pending');
  assert.equal(h.json(`SELECT count(*)::int FROM retention_web_requests WHERE request_id=${q(preview.requestId)}`),1);
  fs.writeFileSync(path.join(evidence,'serialization-'+suffix+'.json'),JSON.stringify({blockedObserved,previewArtifacts:preview.scope.artifacts,requestId:preview.requestId,result,artifact,registeredAfterErasure:true},null,2));
  await assert.rejects(writerDatabase.transaction('retain',s=>s.query('UPDATE retention_artifacts SET object_path=$1 WHERE id=$2',[h.A.tenant+'/cache/changed-scope',artifact.id])),e=>e.code==='database_permission_denied'&&e.status===403);
  assert.equal(h.json(`SELECT to_jsonb(object_path) FROM retention_artifacts WHERE id=${q(artifact.id)}`),input.objectPath);
 });
 h.verifySources();report.status='pass';
}catch(e){report.status='fail';report.error=e.stack;process.exitCode=1;console.error(e);}finally{if(context){for(const p of context.pages()){try{await p.screenshot({path:path.join(evidence,'final-ui.png'),fullPage:true});fs.writeFileSync(path.join(evidence,'final-ui.txt'),await p.locator('body').innerText());}catch{}}await context.close();}if(h){try{report.finalState=h.json('SELECT json_build_object(\'pending\',(SELECT count(*) FROM retention_artifacts WHERE status=\'pending\'),\'requests\',(SELECT count(*) FROM retention_web_requests))');}catch{}await h.close();}fs.writeFileSync(path.join(evidence,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
