import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {createRecoveryRepository} from '../index.mjs';import {createLocalStorage} from '../local.mjs';import {createEnvelope,identityKey} from '../../ingestion/index.mjs';import {persistCanonical,readCanonicalHistory} from '../../ingestion/persistence/index.mjs';import {createExtractionRepository} from '../../intelligence/extraction-repository.mjs';import {createEvidenceRepository} from '../../intelligence/evidence-repository.mjs';import {createDetailService} from '../../workspace-service/detail.mjs';
const {Pool}=createRequire(import.meta.url)('pg');const pool=new Pool({host:'127.0.0.1',port:61820,user:'supabase_admin',password:'synthetic-recovery-local-only',database:'postgres'});const root=await fs.mkdtemp(path.join(os.tmpdir(),'vexa-recovery319-'));await fs.writeFile(path.join(root,'.vexa-recovery-owned'),'synthetic-vexa-recovery-v1');const storage=await createLocalStorage(root);const A=randomUUID(),U=randomUUID(),C=randomUUID(),C2=randomUUID(),I=randomUUID(),I2=randomUUID(),E='SYN319-shared-42';const sha=x=>createHash('sha256').update(x).digest('hex');const result={label:'SYNTHETIC real PostgreSQL namespace/consumer guards; injected synthetic source reader, no provider',checks:[]};
const database={async transaction(action,fn){const c=await pool.connect();try{await c.query('BEGIN');await c.query('SET LOCAL ROLE vexa_backend');await c.query("SELECT set_config('request.jwt.claim.sub',$1,true),set_config('vexa.tenant_id',$2,true),set_config('vexa.action',$3,true)",[U,A,action]);const v=await fn({userId:U,tenantId:A,role:'owner',query:(...args)=>c.query(...args)});await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};
const q=(...a)=>pool.query(...a);const repo=createRecoveryRepository({database,storage});
async function save(type,e,payload,connection=C,revision='1'){const envelope=createEnvelope({tenant_id:A,connection_id:connection,source:'zendesk',source_account_id:connection===C?'SYN319':'SYN319-OTHER'},{entity_type:type,external_id:e,source_revision:revision,observed_at:'2026-09-23T00:00:00Z',payload_ref:'SYN319:'+e},payload);return database.transaction('import',s=>persistCanonical(s,{importId:connection===C?I:I2,record:{row_ref:randomUUID(),mapping_version:'1',envelope,payload}}));}
const history=id=>database.transaction('read',s=>readCanonicalHistory(s,{canonicalId:id}));
try{
await q('INSERT INTO auth.users(id) VALUES($1)',[U]);await q("INSERT INTO organizations(id,name) VALUES($1,'SYN319')",[A]);await q("INSERT INTO memberships(tenant_id,user_id,role,status) VALUES($1,$2,'owner','active')",[A,U]);await q("INSERT INTO connections(id,tenant_id,source,account_id) VALUES($1,$3,'zendesk','SYN319'),($2,$3,'zendesk','SYN319-OTHER')",[C,C2,A]);await q("INSERT INTO imports(id,tenant_id,connection_id,file_hash,mapping_version,state,idempotency_key,total,pending) VALUES($1,$3,$4,'SYN319','1','queued',$1::uuid::text,0,0),($2,$3,$5,'SYN319','1','queued',$2::uuid::text,0,0)",[I,I2,A,C,C2]);await repo.policy({expectedVersion:0,backupTtlSeconds:3600});
const customer=await save('customer',E,{display_name:'SYN319 unrelated customer'}),conversation=await save('conversation',E,{customer_external_id:null,order_external_id:null});await save('conversation','TARGET-PARENT',{customer_external_id:null,order_external_id:null});const message=await save('message',E,{text:'SYN319 target',role:'customer',conversation_external_id:'TARGET-PARENT'});await save('conversation','OTHER-CV',{customer_external_id:null,order_external_id:null},C2);const other=await save('message',E,{text:'SYN319 unrelated connection',role:'customer',conversation_external_id:'OTHER-CV'},C2);await save('message','KEEP',{text:'SYN319 keep evidence',role:'customer',conversation_external_id:E});for(const x of [customer,conversation,message,other])assert.equal(x.status,'inserted');const beforeCustomer=await history(customer.canonical_id),beforeConversation=await history(conversation.canonical_id);
const detail=createDetailService({database});assert.ok((await detail.customerBindings()).customers.some(x=>x.id===customer.canonical_id));
const artifacts=[];for(const [entityType,connectionId]of [['message',C],['customer',C],['conversation',C],['message',C2]]){const objectPath=`${A}/exports/${entityType}-${connectionId}`;await storage.write(objectPath,'SYN319 BYTES');await repo.registerArtifact({connectionId,entityType,sourceKey:E,class:'export',objectPath,expiresAt:Date.now()+300000});artifacts.push({entityType,connectionId,objectPath});}
await assert.rejects(repo.registerArtifact({connectionId:C,sourceKey:E,class:'cache',objectPath:`${A}/missing-type`,expiresAt:Date.now()+300000}),/RETENTION_OPERATION_REJECTED/);
const job=randomUUID();await q("INSERT INTO jobs(id,tenant_id,type,state,input_ref,input_hash,version) VALUES($1,$2,'extraction','running','SYN319','SYN319','1')",[job,A]);const extraction=createExtractionRepository({database,sourceReader:async()=> 'SYN319 keep evidence'}),args={conversationId:conversation.canonical_id,jobId:job,taskKey:randomUUID(),taxonomy:['delivery'],policy:{version:'SYN319',emails:true,phones:true,namesMode:'dictionary',names:[]}},prepared=await extraction.prepare(args),revision=prepared.input.revisions[0],run=(await q('SELECT prompt_hash,schema_hash FROM extraction_runs WHERE id=$1',[prepared.runId])).rows[0];const data={issues:[{category:'delivery',severity:'low',evidence:[{message_revision_id:revision.message_revision_id,start:0,end:[...revision.text].length,quote:revision.text,quote_hash:sha(revision.text),role:'customer'}]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null};assert.equal((await extraction.complete({runId:prepared.runId,result:{ok:true,data,meta:{promptHash:run.prompt_hash,schemaHash:run.schema_hash,model:'synthetic319'},billingState:'settled'}})).status,'succeeded');const evidence=createEvidenceRepository({database});assert.equal((await evidence.get(prepared.runId)).state,'current');
await repo.erase({connectionId:C,entityType:'message',externalId:E,requestId:randomUUID(),confirmed:true});assert.equal(await history(message.canonical_id),null);assert.deepEqual(await history(customer.canonical_id),beforeCustomer,'MESSAGE_TOMBSTONE_MUST_NOT_HIDE_UNRELATED_CUSTOMER_WITH_SAME_EXTERNAL_ID');assert.deepEqual(await history(conversation.canonical_id),beforeConversation);assert.ok(await history(other.canonical_id));assert.equal((await q('SELECT count(*) FROM tombstones WHERE tenant_id=$1',[A])).rows[0].count,'0','NO_NEW_UNTYPED_TOMBSTONES');assert.equal((await save('message',E,{text:'SYN319 resurrect',role:'customer',conversation_external_id:'TARGET-PARENT'},C,'2')).code,'SOURCE_TOMBSTONED');assert.equal((await save('customer',E,{display_name:'SYN319 unrelated customer'})).status,'duplicate');assert.equal((await save('conversation',E,{customer_external_id:null,order_external_id:null})).status,'duplicate');assert.ok((await detail.customerBindings()).customers.some(x=>x.id===customer.canonical_id));assert.equal((await evidence.get(prepared.runId)).state,'current');assert.equal((await extraction.prepare({...args,taskKey:randomUUID()})).acquired,true);assert.equal((await repo.purgeArtifacts()).complete,true);for(const a of artifacts)assert.equal(await storage.exists(a.objectPath),!(a.entityType==='message'&&a.connectionId===C),'ARTIFACT_TYPED_SCOPE');
for(const entityType of ['message','customer']){const objectPath=`${A}/cache/after-${entityType}`;await storage.write(objectPath,'SYN319');const registered=await repo.registerArtifact({connectionId:C,entityType,sourceKey:E,class:'cache',objectPath,expiresAt:Date.now()+300000});assert.equal(registered.status,entityType==='message'?'pending':'active');}result.checks.push('message erased; same-id customer/conversation/other-connection history, extraction, evidence and artifacts preserved; replay denied');
// Isolate new consumer guards with a typed ledger mark while fixture bytes remain intact.
await q("INSERT INTO retention_ledger(tenant_id,id,connection_id,entity_type,external_id,actor_id,policy_version) VALUES($1,$2,$3,'conversation',$4,$5,1)",[A,randomUUID(),C,E,U]);await assert.rejects(extraction.prepare({...args,taskKey:randomUUID()}),/EXTRACTION_TOMBSTONED/);await assert.rejects(evidence.get(prepared.runId),/EVIDENCE_UNAVAILABLE/);assert.ok((await detail.customerBindings()).customers.some(x=>x.id===customer.canonical_id));await q("INSERT INTO retention_ledger(tenant_id,id,connection_id,entity_type,external_id,actor_id,policy_version) VALUES($1,$2,$3,'customer',$4,$5,1)",[A,randomUUID(),C,E,U]);assert.ok(!(await detail.customerBindings()).customers.some(x=>x.id===customer.canonical_id));result.checks.push('typed-only markers independently enforced by extraction/evidence/customer detail guards');
// Legacy ambiguous external tombstones still block both types conservatively.
await q("INSERT INTO tombstones(tenant_id,connection_id,deleted_source_key,reason) VALUES($1,$2,'LEGACY319','synthetic legacy')",[A,C]);for(const kind of ['message','customer'])assert.equal((await save(kind,'LEGACY319',kind==='message'?{text:'SYN',role:'customer',conversation_external_id:'TARGET-PARENT'}:{display_name:'SYN'})).code,'SOURCE_TOMBSTONED');const legacyArtifact=await repo.registerArtifact({connectionId:C,entityType:'customer',sourceKey:'LEGACY319',class:'cache',objectPath:`${A}/legacy-cache`,expiresAt:Date.now()+300000});assert.equal(legacyArtifact.status,'pending');result.checks.push('legacy external tombstone remains blocking including new artifacts, immutable history untouched');console.log(JSON.stringify({root,...result}));
}finally{await pool.end();await fs.writeFile(path.join(root,'observations.json'),JSON.stringify(result,null,2));}
