import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {createRecoveryRepository} from '../index.mjs';import {createLocalStorage,backupLocal,restoreLocal} from '../local.mjs';
const {Pool,Client}=createRequire(import.meta.url)('pg');const root=await fs.mkdtemp(path.join(os.tmpdir(),'vexa-recovery314-'));const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const A=id(1),U=id(2),C=id(3),CV=id(4),M=id(5),R=id(6);const key='SYN314-ONLY-NOT-A-REAL-KEY-0123456789';const pools=[];const pool=port=>{const p=new Pool({host:'127.0.0.1',port,user:'supabase_admin',password:'synthetic-recovery-local-only',database:'postgres',connectionTimeoutMillis:3000});pools.push(p);return p;};const source=pool(61820);
async function storage(name){const dir=path.join(root,name);await fs.mkdir(dir);await fs.writeFile(path.join(dir,'.vexa-recovery-owned'),'synthetic-vexa-recovery-v1');return createLocalStorage(dir);}
const evidence={label:'SYNTHETIC LOCAL ONLY',root,checks:[]};
try{
await source.query('INSERT INTO auth.users(id) VALUES($1)',[U]);await source.query("INSERT INTO organizations(id,name) VALUES($1,'SYN314')",[A]);await source.query("INSERT INTO memberships(tenant_id,user_id,role,status) VALUES($1,$2,'owner','active')",[A,U]);await source.query("INSERT INTO connections(id,tenant_id,source,account_id) VALUES($1,$2,'zendesk','SYN314')",[C,A]);await source.query("INSERT INTO conversations(id,tenant_id,connection_id,source,external_id) VALUES($1,$2,$3,'zendesk','CV')",[CV,A,C]);await source.query("INSERT INTO messages(id,tenant_id,connection_id,conversation_id,external_id,role) VALUES($1,$2,$3,$4,'ERASE','customer')",[M,A,C,CV]);await source.query("INSERT INTO message_revisions(id,tenant_id,message_id,revision,text_ref,redacted_text,hash) VALUES($1,$2,$3,'1','SYN314','SYN314-SECRET-TEXT',$4)",[R,A,M,'a'.repeat(64)]);
const database={async transaction(action,fn){const c=await source.connect();try{await c.query('BEGIN');await c.query('SET LOCAL ROLE vexa_backend');await c.query("SELECT set_config('request.jwt.claim.sub',$1,true),set_config('vexa.tenant_id',$2,true),set_config('vexa.action',$3,true)",[U,A,action]);const v=await fn({userId:U,tenantId:A,role:'owner',query:(...args)=>c.query(...args)});await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};const live=await storage('source'),repo=createRecoveryRepository({database,storage:live,ledgerKey:key});await repo.policy({expectedVersion:0,backupTtlSeconds:3600});const backup=await backupLocal({mode:'synthetic-local',sourceContainer:'vexa-recovery-309-source',storageRoot:live.root,archive:path.join(root,'backup-original')});const cutoff=Date.now();await repo.erase({connectionId:C,entityType:'message',externalId:'ERASE',requestId:id(7),confirmed:true});const ledger=await repo.exportLedger();const keyFile=path.join(root,'key');await fs.writeFile(keyFile,key,{mode:0o600});
for(const [name,port,container,signature,actorId,expectedRows]of [['invalid-signature',61821,'vexa-recovery-309-target','0'.repeat(64),U,0],['post-load-failure',61822,'vexa-recovery-309-incompatible',ledger.signature,id(99),1]]){
 const admin=pool(port);await admin.query("CREATE ROLE syn314_app LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD 'synthetic314'; GRANT vexa_backend TO syn314_app; GRANT CONNECT ON DATABASE postgres TO syn314_app");const cfg={host:'127.0.0.1',port,user:'syn314_app',password:'synthetic314',database:'postgres',connectionTimeoutMillis:3000};const existing=new Client(cfg);existing.on('error',()=>{});await existing.connect();await existing.query('SELECT 1');const target=await storage(name),ledgerFile=path.join(root,name+'.json');await fs.writeFile(ledgerFile,JSON.stringify({...ledger,signature}),{mode:0o600});let rejection;try{await restoreLocal({mode:'synthetic-local',sourceContainer:'vexa-recovery-309-source',targetContainer:container,storageRoot:target.root,archive:backup.archive,expectedManifestHash:backup.manifestHash,confirmEmptyTarget:true,recoveryCutoff:cutoff,ledgers:[{tenantId:A,actorId,ledgerFile,ledgerKeyFile:keyFile,expectedLedgerHash:ledger.sha256,recoveryCutoff:cutoff}]});}catch(e){rejection=e.message;}
 assert.ok(rejection);assert.ok(await fs.stat(path.join(target.root,'RESTORE_BLOCKED')));let oldDenied=false;try{await existing.query('SELECT 1');}catch{oldDenied=true;}assert.equal(oldDenied,true,'EXISTING_APP_SESSION_TERMINATED');await existing.end().catch(()=>{});const fresh=new Client(cfg);await assert.rejects(fresh.connect(),/too many connections/,'EXPLICIT_CONNECT_ROLE_REMAINS_BLOCKED');await fresh.end().catch(()=>{});const rows=Number((await admin.query('SELECT count(*) FROM organizations')).rows[0].count);assert.equal(rows,expectedRows,'SIGNATURE_AUTHENTICATED_BEFORE_RESTORE');const connectionLimit=Number((await admin.query("SELECT datconnlimit FROM pg_database WHERE datname='postgres'")).rows[0].datconnlimit);assert.equal(connectionLimit,0);evidence.checks.push({case:name,rejection,oldDenied,newDenied:true,organizations:rows,connectionLimit,markerPreserved:true});
}
console.log(JSON.stringify(evidence));
}finally{for(const p of pools)await p.end();await fs.writeFile(path.join(root,'observations.json'),JSON.stringify(evidence,null,2));}
