import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';import {q} from './harness.mjs';import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';import {insert} from '../../tests/acceptance/support/F01-03/matrix.mjs';
export {scope,source,currency,order} from '../F05-snapshots/fixtures.mjs';
export const policy=(expectedVersion=0,patch={})=>({operation:'policy',expectedVersion,name:'SYN approved operational priority',weights:{impact:2500,frequency:2500,severity:2500,actionability:2500},frequencyBaseline:20,impactBaselineMinor:'90071992547409930',currency:'USD',exponent:2,report:'SYN human operational policy approval, fixed references not estimated probabilities.',attested:true,...patch});
export const action=(p,expectedVersion=0,level='high')=>({operation:'actionability',problemId:p.id,expectedProblemVersion:1,expectedVersion,level,report:'SYN operational investigation approved by fixture owner with current evidence version.',attested:true});
// Every result is explicitly synthetic transport evidence; actual ingestion, redaction,
// extraction validation/commit and SQL authorization are exercised. No paid model.
export async function priorityFixture(h){
 const {createExtractionRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/extraction-repository.mjs'))),{sha256}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/index.mjs')));
 async function extraction(actor,{category,severity,label}){const a={...actor,connection:randomUUID(),source:'zendesk',account:'SYN-priority-'+randomUUID()};h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(a.connection)},${q(a.tenant)},'zendesk',${q(a.account)})`);const database=h.repository(a).database,sync=h.sync.createSyncRepository({database}),row=await sync.ensure({connectionId:a.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});const quote=category==='smoke'?'El cargador emite humo':'El menú es difícil de encontrar';await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,a,'T1',{type:'ticket'}),record(h.ingestion,a,'M1',{text:quote,role:'customer'})],'end',{done:true})});const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(a.tenant)} AND connection_id=${q(a.connection)}`),jobId=randomUUID();h.sql(`INSERT INTO jobs(id,tenant_id,type,state,input_ref,input_hash,version) VALUES(${q(jobId)},${q(a.tenant)},'extraction','running','SYN-PRIORITY269',${q(randomUUID())},'SYN-v1')`);const repository=createExtractionRepository({database}),prepared=await repository.prepare({conversationId,jobId,taskKey:randomUUID(),taxonomy:[category],policy:{version:'SYN',emails:true,phones:true,namesMode:'dictionary',names:[]}}),revision=prepared.input.revisions[0],start=[...revision.text.slice(0,revision.text.indexOf(quote))].length,span={message_revision_id:revision.message_revision_id,start,end:start+[...quote].length,quote,quote_hash:sha256(quote),role:'customer'},run=h.json(`SELECT to_jsonb(r) FROM extraction_runs r WHERE id=${q(prepared.runId)}`);await repository.complete({runId:prepared.runId,result:{ok:true,data:{issues:[{category,severity,evidence:[span]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null},meta:{promptHash:run.prompt_hash,schemaHash:run.schema_hash,model:'synthetic/priority-model'},billingState:'settled'}});return{a,prepared,conversationId,span};}
 async function problem(actor,{label,category='usability',severity='low',count=1}){const extractions=[];for(let i=0;i<count;i++)extractions.push(await extraction(actor,{label,category,severity}));const id=randomUUID(),embeddingIds=extractions.map(()=>randomUUID()),snapshot={id,label,version:1,state:'active',outlier:count===1,modelId:'synthetic-3d',dimensions:3,embeddingVersion:'1',embeddingIds,conversationIds:extractions.map(x=>x.conversationId),orderIds:[]};let sql=`BEGIN;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('vexa.tenant_id',${q(actor.tenant)},true),set_config('vexa.action','configure',true);`;sql+=insert('problems',{id,tenant_id:actor.tenant,title:label,severity,cause_status:'unknown',provenance:{kind:'vector-problem-v1'}})+';';for(let i=0;i<extractions.length;i++){const x=extractions[i];sql+=insert('embeddings',{id:embeddingIds[i],tenant_id:actor.tenant,model_id:'synthetic-3d',dim:3,version:'1',content:'SYN priority grouping',embedding:'[1,0,0]',message_revision_id:x.span.message_revision_id})+';'+insert('problem_embedding_members',{tenant_id:actor.tenant,embedding_id:embeddingIds[i],problem_id:id,extraction_run_id:x.prepared.runId,conversation_id:x.conversationId})+';';}sql+=insert('problem_versions',{id:randomUUID(),tenant_id:actor.tenant,problem_id:id,previous_version_id:null,version:1,title:label,rationale:'SYN verified grouping of real authorized extraction fixtures',change_kind:'create',provenance:{kind:'vector-problem-v1',snapshot,actorId:actor.id,operation:'create'}})+';COMMIT;';h.sql(sql);return{id,label,extractions,embeddingIds};}
 return{problem};
}
