import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'CANDIDATE_REQUIRED');const source=path.join(candidate,'packages/metrics/priority.mjs');
const policy={weights:{impact:4000,frequency:2000,severity:3000,actionability:1000},frequencyBaseline:20,impactBaselineMinor:'10000',currency:'USD',exponent:2};
const problem={severity:'low',criticalLane:false,issueIds:['a','b'],actionability:'medium',impact:{amount_minor:'2500',known_subtotal:'2500',coverage:{known_n:1,eligible_n:1},currency:'USD',exponent:2}};
test('F05-06 independent formula exists',()=>assert.ok(fs.existsSync(source),'PRIORITY_IMPLEMENTATION_MISSING'));
test('F05-06 exact financial contribution and explicit unknown interval',async()=>{assert.ok(fs.existsSync(source),'PRIORITY_IMPLEMENTATION_MISSING');const {priority}=await import(pathToFileURL(source));const known=priority(problem,policy);assert.deepEqual(known.contributions,{impact:1000,frequency:200,severity:500,actionability:500});assert.equal(known.scoreKnownBps,2200);assert.equal(known.scoreUpperBps,2200);assert.equal(known.status,'complete');const unknown=priority({...problem,impact:null,actionability:'unknown'},policy);assert.equal(unknown.contributions.impact,null);assert.equal(unknown.contributions.actionability,null);assert.equal(unknown.scoreKnownBps,700);assert.equal(unknown.scoreUpperBps,5700,'PRIORITY_UNKNOWN_INTERVAL_NOT_ZERO');assert.equal(unknown.status,'partial');const partial=priority({...problem,impact:{...problem.impact,amount_minor:null,coverage:{known_n:1,eligible_n:2}}},policy);assert.equal(partial.scoreKnownBps,2200);assert.equal(partial.scoreUpperBps,5200,'PRIORITY_PARTIAL_SUBTOTAL_LOWER_BOUND');});
test('F05-06 BigInt ratio boundary has no Number rounding',async()=>{const {priority}=await import(pathToFileURL(source));const base='9007199254740993';const p={...policy,impactBaselineMinor:base};const r=priority({...problem,impact:{...problem.impact,amount_minor:'9007199254740992'}},p);assert.equal(r.contributions.impact,3999,'PRIORITY_BIGINT_PRECISION');assert.equal(priority({...problem,impact:{...problem.impact,amount_minor:base}},p).contributions.impact,4000);});
test('F05-06 fixed baseline unique issues currency isolation and safety lane',async()=>{const {priority}=await import(pathToFileURL(source));assert.deepEqual(priority({...problem,issueIds:['a','b','a']},policy),priority(problem,policy));const before=[problem,{...problem,severity:'medium'}].map(x=>priority(x,policy));const after=[problem,{...problem,severity:'medium'},{...problem,impact:null,issueIds:[]}].map(x=>priority(x,policy));assert.deepEqual(after.slice(0,2),before,'PRIORITY_NO_SET_MIN_MAX');const critical=priority({...problem,severity:'critical',criticalLane:true,impact:null,issueIds:['smoke'],actionability:'unknown'},policy);assert.equal(critical.criticalLane,true,'PRIORITY_CRITICAL_WITH_UNKNOWN_MONEY');assert.equal(critical.status,'partial');assert.ok(critical.reasons.includes('human_safety_review_independent_of_money'));assert.equal(priority({...problem,impact:{...problem.impact,currency:'MXN'}},policy).contributions.impact,null,'PRIORITY_CROSS_CURRENCY_NOT_COMPARED');const changed=priority(problem,{...policy,weights:{impact:1000,frequency:2000,severity:6000,actionability:1000}});assert.equal(changed.scoreKnownBps,1950);assert.notEqual(changed.scoreKnownBps,before[0].scoreKnownBps);});
test('F05-06 causal unknown-to-zero mutant baseline failure restoration',async()=>{const original=fs.readFileSync(source,'utf8'),target='scoreUpperBps=scoreKnownBps+Object.entries(missing).reduce';assert.ok(original.includes(target),'PRIORITY_MUTANT_TARGET');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-priority-mutant268-'));try{fs.cpSync(path.join(candidate,'packages'),path.join(temp,'packages'),{recursive:true});const file=path.join(temp,'packages/metrics/priority.mjs');const probe=async tag=>{const {priority}=await import(pathToFileURL(file)+'?'+tag);const result=priority({...problem,impact:null,actionability:'unknown'},policy);assert.equal(result.scoreUpperBps,5700,'PRIORITY_UNKNOWN_INTERVAL_NOT_ZERO');};await probe('baseline');fs.writeFileSync(file,original.replace(target,'scoreUpperBps=scoreKnownBps+0*Object.entries(missing).reduce'));await assert.rejects(probe('mutant'),e=>e.code==='ERR_ASSERTION'&&e.message.includes('PRIORITY_UNKNOWN_INTERVAL_NOT_ZERO'));fs.writeFileSync(file,original);await probe('restored');}finally{fs.rmSync(temp,{recursive:true,force:true});}});
