/** Local SYN walkthrough; does not accept F08-03 or contact a CRM. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {setup} from './portability-harness.mjs';
import {record,page,adapter,windowSpec} from '../../../tests/acceptance/support/F03-sync/fixtures.mjs';
import {insert} from '../../../tests/acceptance/support/F01-03/matrix.mjs';
const q=v=>"'"+String(v).replaceAll("'","''")+"'";
const root=path.resolve(fileURLToPath(new URL('../../../',import.meta.url))),evidence=process.argv[2];assert.ok(evidence,'PRIVATE_EVIDENCE_DIRECTORY_REQUIRED');if(fs.existsSync(evidence)){assert.ok(!fs.lstatSync(evidence).isSymbolicLink()&&fs.statSync(evidence).isDirectory(),'EVIDENCE_DIRECTORY_ONLY');assert.deepEqual(fs.readdirSync(evidence),[],'EVIDENCE_MUST_BE_EMPTY');}fs.mkdirSync(evidence,{recursive:true,mode:0o700});fs.chmodSync(evidence,0o700);
const scope={dateStart:'2026-01-01T00:00:00Z',dateEnd:'2026-10-01T00:00:00Z',timezone:'UTC',currency:'USD',dateBasis:'conversation',sources:[],channels:[]};
const report={synthetic:true,providerRequests:0,humanRehearsal:false,checks:[],snapshots:{},comparisons:{}};let h,context;
const check=(name,details)=>{report.checks.push({name,...details});console.log('PASS '+name);};
const save=(name,v)=>fs.writeFileSync(path.join(evidence,name),JSON.stringify(v,null,2)+'\n');
try{
 h=await setup(root,evidence);console.log('READY pid='+process.pid+' web=61624');const repo=h.repository(h.A);
 const hs={...h.A,source:'hubspot',account:'SYN-PORTABILITY-HUBSPOT'},zd={...h.A,source:'zendesk',connection:randomUUID(),account:'SYN-PORTABILITY-ZENDESK'};
 h.sql(`UPDATE connections SET source='hubspot',account_id=${q(hs.account)} WHERE id=${q(hs.connection)}`);h.sql(insert('connections',{id:zd.connection,tenant_id:zd.tenant,source:zd.source,account_id:zd.account}));
 function crm(actor,id){if(actor.source==='zendesk'){const r=record(h.ingestion,actor,id,{type:'ticket'});r.payload.via={channel:'email'};r.envelope=h.ingestion.createEnvelope(r.envelope,r.envelope,r.payload);return r;}
 const payload={id,createdAt:'2026-02-01T00:00:00Z',originalChannelId:'1000'};return {payload,envelope:h.ingestion.createEnvelope({tenant_id:actor.tenant,connection_id:actor.connection,source:actor.source,source_account_id:actor.account},{entity_type:'thread',external_id:id,source_revision:'SYN-r1',occurred_at:'2026-02-01T00:00:00Z',observed_at:'2026-09-01T00:00:00Z',payload_ref:'SYN-PORTABILITY-THREAD'},payload)};}
 const hsRows=['42','99'].map(id=>crm(hs,id)),zdRows=['142','199'].map(id=>crm(zd,id));
 save('fixture.json',{label:'SYN adapters fed local fixture pages, not provider HTTP',hubspot:hsRows,zendesk:zdRows,crosswalk:[['42','142'],['99','199']],orders:[{id:'SYN-O1',minor:'10000'},{id:'SYN-O2',minor:'20000'}],refunds:'not part of this scope; do not add demo15USD'});
 async function sync(actor,rows,version){const p=page(rows,'SYN-END-'+version,{done:true});p.adapter_version='SYN-PORTABILITY-'+actor.source;return h.sync.runSync({repository:h.sync.createSyncRepository({database:repo.database}),connectionId:actor.connection,mode:'live',window:{...windowSpec,version},adapterFactory:async()=>adapter([p])});}
 const cid=(actor,id)=>h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(actor.tenant)} AND connection_id=${q(actor.connection)} AND external_id=${q(id)}`);
 function order(n,amount){const id=randomUUID(),rev=randomUUID(),ext='SYN-O'+n,provenance={source:hs.source,account_id:hs.account,synthetic:true};h.sql(insert('orders',{id,tenant_id:hs.tenant,connection_id:hs.connection,external_id:ext,amount_minor:amount,currency:'USD',exponent:2,occurred_at:'2026-02-01T00:00:00Z'}));h.sql(insert('source_revisions',{id:rev,tenant_id:hs.tenant,connection_id:hs.connection,entity_type:'order',external_id:ext,source_revision:'SYN-financial-v1',content_hash:'a'.repeat(64),fingerprint:'b'.repeat(64),mapping_version:'crm-canonical-v1',snapshot:[{synthetic:true,amount_minor:amount}],canonical_id:id,order_id:id,provenance}));h.sql(insert('source_heads',{id,tenant_id:hs.tenant,connection_id:hs.connection,entity_type:'order',external_id:ext,version:1,state:'unique',selected_revision_id:rev}));return id;}
 const capture=async name=>{const r=await h.request(h.A,'/api/migrations',scope);if(r.status!==201){const diagnostic=h.comparison.createComparisonRepository({database:{transaction:(action,work)=>repo.database.transaction(action,tx=>work({...tx,query:async(text,values)=>{try{return await tx.query(text,values);}catch(e){save('sql-failure.json',{code:e.code,message:e.message,where:e.where,routine:e.routine,statement:text});throw e;}}}))}});try{await diagnostic.capture(scope);}catch{}}assert.equal(r.status,201,JSON.stringify(r.data));report.snapshots[name]=r.data.snapshot;return r.data.snapshot;};
 const compare=async(name,a,b)=>{const r=await h.request(h.A,'/api/migrations/compare?'+new URLSearchParams({before:a.id,after:b.id}));assert.equal(r.status,200);report.comparisons[name]=r.data;return r.data;};
 await sync(hs,hsRows,'SYN-HS-1');const orders=[order(1,'10000'),order(2,'20000')],hsIds=['42','99'].map(id=>cid(hs,id));hsIds.forEach((id,i)=>h.sql(`UPDATE conversations SET order_id=${q(orders[i])} WHERE id=${q(id)}`));
 const parallelScope={...scope,dateStart:'2026-01-02T00:00:00Z'};const pair=await Promise.all([h.request(h.A,'/api/migrations',parallelScope),h.request(h.A,'/api/migrations',parallelScope)]);assert.ok(pair.every(r=>r.status===201));assert.equal(pair[0].data.snapshot.id,pair[1].data.snapshot.id);assert.equal(h.sql(`SELECT count(*) FROM metric_snapshots WHERE tenant_id=${q(h.A.tenant)} AND scope_hash=(SELECT scope_hash FROM metric_snapshots WHERE id=${q(pair[0].data.snapshot.id)}) AND input_hash=${q(pair[0].data.snapshot.inputHash)}`),'1');check('concurrent captures converge on one immutable identity',{});const baseline=await capture('hubspot');assert.equal((await capture('hubspotIdempotent')).id,baseline.id);const viewer={...h.bot,tenant:h.A.tenant};h.sql(`UPDATE memberships SET role='viewer' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(viewer.id)}`);assert.equal((await h.request(viewer,'/api/migrations',scope)).status,403);assert.equal((await h.request(viewer,'/api/migrations')).status,200);check('capture idempotent and viewer read-only',{viewerCaptureStatus:403});assert.equal(baseline.summary.money.USD.amountMinor,'30000');const baselineBytes=h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(baseline.id)}`);
 await sync(zd,zdRows,'SYN-ZD-1');const zdIds=['142','199'].map(id=>cid(zd,id));zdIds.forEach((id,i)=>h.sql(`UPDATE conversations SET order_id=${q(orders[i])} WHERE id=${q(id)}`));const overlap=await capture('overlap');assert.equal(overlap.summary.conversations,4);assert.equal(overlap.summary.orders,2);assert.equal(overlap.summary.money.USD.amountMinor,'30000');
 const historyBefore=h.sql(`SELECT jsonb_agg(to_jsonb(v) ORDER BY id) FROM source_revisions v WHERE tenant_id=${q(h.A.tenant)}`);await sync(hs,hsRows,'SYN-HS-REPLAY');await sync(zd,zdRows,'SYN-ZD-REPLAY');assert.equal(h.sql(`SELECT count(*) FROM conversations WHERE tenant_id=${q(h.A.tenant)}`),'4');assert.equal(h.sql(`SELECT jsonb_agg(to_jsonb(v) ORDER BY id) FROM source_revisions v WHERE tenant_id=${q(h.A.tenant)}`),historyBefore);check('same source replay preserves canonical IDs and revisions',{sourceConversations:4,orders:2});
 const browser=await h.browser();context=await browser.newContext({viewport:{width:1440,height:1000}});context.setDefaultTimeout(15000);await context.addCookies(h.cookie(h.A).split('; ').map(v=>{const n=v.indexOf('=');return{name:v.slice(0,n),value:v.slice(n+1),url:h.base};}));const p=await context.newPage();await p.goto(h.base+'/migrations');await p.waitForLoadState('networkidle');save('dom-recognition.json',{headings:await p.getByRole('heading').allTextContents(),buttons:await p.getByRole('button').allTextContents(),labels:await p.locator('label').allTextContents()});
 for(let i=0;i<2;i++){await p.getByRole('combobox',{name:/^Conversación origen/}).selectOption(zdIds[i]);await p.getByRole('combobox',{name:/^Conversación destino/}).selectOption(hsIds[i]);await p.getByRole('button',{name:'Preparar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Propuesta pendiente de aprobación'}).waitFor();await p.getByLabel('Referencia de evidencia',{exact:true}).fill('SYN-portability-crosswalk:'+['42=142','99=199'][i]);await p.getByLabel('Motivo de la decisión',{exact:true}).fill('Ensayo SYN: equivalencia explícita en fixture, no aprobación humana real.');await p.getByLabel('Confirmo esta decisión de identidad',{exact:true}).check();const response=p.waitForResponse(r=>r.url().endsWith('/api/migrations/aliases')&&r.request().method()==='POST');await p.getByRole('button',{name:'Confirmar alias',exact:true}).click();assert.equal((await response).status(),201);await p.getByText('Alias confirmado. Las fuentes originales y los cortes históricos se conservan.',{exact:true}).waitFor();}
 const aliased=await capture('aliased');assert.equal(aliased.summary.conversations,2);assert.equal(aliased.summary.sourceConversations,4);assert.equal(aliased.summary.money.USD.amountMinor,'30000');for(let i=0;i<2;i++)assert.equal((await repo.aliases.resolve({conversationId:zdIds[i]})).canonical_id,hsIds[i]);
 const identical=await compare('aliasEquivalent',overlap,aliased);assert.equal(identical.state,'comparable');assert.equal(identical.money.USD.deltaMinor,'0');assert.equal(identical.savings,null);check('browser explicit alias joins both CRMs without doubling money',{resolved:2,source:4,amountMinor:'30000',deltaMinor:'0',savings:null});
 async function screenshot(name,a,b,heading){await p.getByRole('button',{name:'Actualizar cortes',exact:true}).click();await p.getByLabel('Antes',{exact:true}).selectOption(a.id);await p.getByLabel('Después',{exact:true}).selectOption(b.id);const rr=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/migrations/compare');await p.getByRole('button',{name:'Comparar cortes',exact:true}).click();assert.equal((await rr).status(),200);await p.getByRole('heading',{name:heading,exact:true}).waitFor();const section=p.getByRole('region',{name:'Resultado de comparación'});save(name+'.json',{text:await section.innerText()});await section.screenshot({path:path.join(evidence,name+'.png')});}
 await screenshot('01-equivalent',overlap,aliased,'Comparable');
 const changed=await compare('providerCoverage',baseline,aliased);assert.equal(changed.state,'no_comparable');assert.ok(changed.reasons.includes('channel_coverage_changed'));assert.deepEqual(changed.channels.map(c=>c.channel),['hubspot_1000','zendesk_email']);await screenshot('02-provider-coverage',baseline,aliased,'No comparable');check('provider channel IDs remain distinct and deny false comparability',{reasons:changed.reasons});
 h.sql(`UPDATE conversations SET deleted_at=now() WHERE id IN (${hsIds.map(q).join(',')})`);const lost=await capture('missingHubspotChannel');const loss=await compare('loss',aliased,lost);assert.equal(loss.state,'no_comparable');assert.equal(loss.channels.find(c=>c.channel==='hubspot_1000').after,0);assert.equal(loss.money.USD.deltaMinor,null);await screenshot('03-channel-loss',aliased,lost,'No comparable');check('missing source coverage never becomes improvement',{deltaMinor:null});
 await sync(zd,[crm(zd,'UNKNOWN')],'SYN-ZD-UNKNOWN');const unknownOrder=order(3,null);h.sql(`UPDATE conversations SET order_id=${q(unknownOrder)} WHERE id=${q(cid(zd,'UNKNOWN'))}`);const unknown=await capture('unknownMoney');assert.equal(unknown.summary.money.USD.amountMinor,null);assert.equal(unknown.summary.money.USD.knownSubtotalMinor,'30000');await screenshot('04-unknown',lost,unknown,'Comparable');assert.match(await p.getByRole('region',{name:'Resultado de comparación'}).innerText(),/desconocido/);check('unknown money remains null with separate known subtotal',{amountMinor:null,knownSubtotalMinor:'30000'});
 const foreign=await h.request(h.B,'/api/migrations/compare?'+new URLSearchParams({before:baseline.id,after:aliased.id}));assert.equal(foreign.status,409);const listB=await h.request(h.B,'/api/migrations/aliases');assert.equal(listB.status,200);assert.deepEqual(listB.data.conversations,[]);const forged=await h.request(h.B,'/api/migrations/aliases',{operation:'propose',sourceConversationId:zdIds[0],targetConversationId:hsIds[0]});assert.equal(forged.status,409);check('tenant B cannot read snapshots or bind A identities',{comparisonStatus:409,proposalStatus:409,listingCount:0});
 assert.equal(h.sql(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(baseline.id)}`),baselineBytes);check('baseline immutable despite alias and later source fixture changes',{});h.verifySources();report.status='passed';
}catch(e){report.status='failed';report.error={name:e.name,message:e.message,stack:e.stack};process.exitCode=1;console.error(e);}finally{if(context)await context.close();if(h)await h.close();save('report.json',report);}
