import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';import {q} from './harness.mjs';import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';
export async function fixtureFactory(h){const {createExtractionRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/extraction-repository.mjs'))),{createEvidenceRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/evidence-repository.mjs'))),{sha256}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/index.mjs')));
  async function fixture(role='customer',existingActor=null){
   const a={...(existingActor??await h.actor())};Object.assign(a,{connection:randomUUID(),account:'SYN-evidence-'+randomUUID(),source:'zendesk'});h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(a.connection)},${q(a.tenant)},'zendesk',${q(a.account)})`);
   const database=h.database(a),sync=h.sync.createSyncRepository({database}),row=await sync.ensure({connectionId:a.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,a,'T1',{type:'ticket'}),record(h.ingestion,a,'M1',{text:'Ana Pérez: 😀 batería emite humo',role})],'end',{done:true})});
   const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(a.tenant)} AND connection_id=${q(a.connection)}`),jobId=h.job(a),repository=createExtractionRepository({database}),prepared=await repository.prepare({conversationId,jobId,taskKey:randomUUID(),taxonomy:['battery'],policy:{version:'SYN',emails:true,phones:true,namesMode:'dictionary',names:['Ana Pérez']}}),revision=prepared.input.revisions[0],quote='😀 batería emite humo',start=[...revision.text.slice(0,revision.text.indexOf(quote))].length;
   const span={message_revision_id:revision.message_revision_id,start,end:start+[...quote].length,quote,quote_hash:sha256(quote),role},data={issues:[{category:'battery',severity:'high',evidence:[span]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null},run=h.json(`SELECT to_jsonb(r) FROM extraction_runs r WHERE id=${q(prepared.runId)}`),result={ok:true,data,meta:{promptHash:run.prompt_hash,schemaHash:run.schema_hash,model:'synthetic/model'},billingState:'settled'};
   return {a,database,sync,repository,prepared,result,quote,jobId,conversationId,span,reader:createEvidenceRepository({database}),complete:()=>repository.complete({runId:prepared.runId,result})};
  }
return fixture;}
