import test from 'node:test';import assert from 'node:assert/strict';import {createHmac,createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';import path from 'node:path';const {handleEmailWebhook}=await import(pathToFileURL(path.join(process.env.VEXA_CANDIDATE,'packages/notifications/receipts.mjs')));
const secret=Buffer.from('SYN_LOCAL_TEST_ONLY_32_BYTE_SECRET');const webhookSecret='whsec_'+secret.toString('base64');
function fixture({timestamp=String(Math.floor(Date.now()/1000)),payload={type:'email.delivered',created_at:new Date().toISOString(),data:{email_id:'SYN_provider_1',tenant_id:'foreign-tenant'}},id='SYN_event_1'}={}){const body=JSON.stringify(payload);const headers={'content-type':'application/json','svix-id':id,'svix-timestamp':timestamp,'svix-signature':'v1,'+createHmac('sha256',secret).update(`${id}.${timestamp}.${body}`).digest('base64')};return{body,headers};}
async function run(f){const calls=[];const r=await handleEmailWebhook(new Request('https://vexa.test/api/webhooks/email',{method:'POST',...f}),{webhookSecret,repository:{record:async v=>{calls.push(v);return{replay:false}}}});return{r,calls};}
test('valid original signature yields only trusted receipt fields, no payload tenant',async()=>{const f=fixture(),{r,calls}=await run(f);assert.equal(r.status,200);assert.equal(calls.length,1);assert.deepEqual(Object.keys(calls[0]).sort(),['bounceKind','eventId','occurredAt','payloadHash','providerId','type']);assert.equal(calls[0].bounceKind,null);assert.equal(calls[0].payloadHash,createHash('sha256').update(f.body).digest('hex'));assert.equal(r.headers.get('cache-control'),'no-store');});
for(const [name,change] of Object.entries({modified_body:f=>({...f,body:f.body+' '}),invalid_signature:f=>({...f,headers:{...f.headers,'svix-signature':'v1,INVALID'}}),old_timestamp:()=>fixture({timestamp:String(Math.floor(Date.now()/1000)-301)}),future_timestamp:()=>fixture({timestamp:String(Math.floor(Date.now()/1000)+301)}),unknown_type:()=>fixture({payload:{type:'email.invented',created_at:new Date().toISOString(),data:{email_id:'SYN_provider_1'}}}),bad_provider_id:()=>fixture({payload:{type:'email.delivered',created_at:new Date().toISOString(),data:{email_id:'bad/id'}}}),bad_event_id:()=>fixture({id:'bad/id'}),future_occurrence:()=>fixture({payload:{type:'email.delivered',created_at:new Date(Date.now()+360000).toISOString(),data:{email_id:'SYN_provider_1'}}})}))test(name+' never persists a receipt',async()=>{const {r,calls}=await run(change(fixture()));assert.equal(r.status,400);assert.equal(calls.length,0);});
test('body size is bounded before verification and persistence',async()=>{const {r,calls}=await run({...fixture(),body:'x'.repeat(65537)});assert.equal(r.status,413);assert.equal(calls.length,0);});
test('invalid UTF8 is rejected instead of normalized before signature',async()=>{const {r,calls}=await run({...fixture(),body:new Uint8Array([0xc3,0x28])});assert.equal(r.status,400);assert.equal(calls.length,0);});
