import {seedCurrent,checkCurrent} from './current352.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
import {createRecoveryRepository,digest} from '../index.mjs';import {createLocalStorage,backupLocal,restoreLocal} from '../local.mjs';
import {persistCanonical,readCanonicalHistory} from '../../ingestion/persistence/index.mjs';import {createEnvelope} from '../../ingestion/index.mjs';
const {Pool}=createRequire(import.meta.url)('pg');const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const A=id(1),B=id(2),U=id(3),V=id(4),CA=id(5),CB=id(6),I=id(7),M=id(8),R=id(9),C=id(10),RR=id(11),J=id(12),SN=id(13),E='SYN-ERASE';
const key='SYNTHETIC-RECOVERY-KEY-309-DO-NOT-USE-IN-PRODUCTION';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'vexa-recovery309-evidence-'));const sourceStore=path.join(root,'source-storage'),targetStore=path.join(root,'target-storage');
for(const dir of [sourceStore,targetStore]){await fs.mkdir(dir);await fs.writeFile(path.join(dir,'.vexa-recovery-owned'),'synthetic-vexa-recovery-v1');}
const sourcePool=new Pool({host:'127.0.0.1',port:61820,user:'supabase_admin',password:'synthetic-recovery-local-only',connectionTimeoutMillis:5000,database:'postgres'}),targetPool=new Pool({host:'127.0.0.1',port:61821,user:'supabase_admin',password:'synthetic-recovery-local-only',connectionTimeoutMillis:5000,database:'postgres'});
function db(pool,tenant=A,user=U){return{transaction:async(action,work)=>{const c=await pool.connect();try{await c.query('BEGIN');await c.query('SET LOCAL ROLE vexa_backend');await c.query("SELECT set_config('request.jwt.claim.sub',$1,true),set_config('vexa.tenant_id',$2,true),set_config('vexa.action',$3,true)",[user,tenant,action]);const member=(await c.query("SELECT role FROM memberships WHERE tenant_id=$1 AND user_id=$2 AND status='active'",[tenant,user])).rows[0];assert.ok(member);const out=await work({tenantId:tenant,userId:user,role:member.role,query:(...a)=>c.query(...a)});await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};}
const q=(sql,values)=>sourcePool.query(sql,values);
const live=await createLocalStorage(sourceStore),database=db(sourcePool),repo=createRecoveryRepository({database,storage:live,ledgerKey:key});let currentState;let snapshotBefore,backup,ledgerA,ledgerB,cutoff;const observations={label:'SYNTHETIC local PostgreSQL17+filesystem Storage; no production/AuthHTTP/cloud',root};
test('SYNTHETIC real backup restore tombstones and rollback',async t=>{
 t.after(async()=>{await sourcePool.end();await targetPool.end();await fs.writeFile(path.join(root,'observations.json'),JSON.stringify(observations,null,2));console.log('RECOVERY309_EVIDENCE:'+root);});
 await t.test('seed canonical SQL + scoped policies, actual raw/vector/cache/export objects',async()=>{
 await q('INSERT INTO auth.users(id) VALUES($1),($2)',[U,V]);await q('INSERT INTO organizations(id,name) VALUES($1,$2),($3,$4)',[A,'SYN A',B,'SYN B']);await q("INSERT INTO memberships(tenant_id,user_id,role,status) VALUES($1,$2,'owner','active'),($3,$2,'owner','active'),($1,$4,'viewer','active')",[A,U,B,V]);
 await q("INSERT INTO connections(id,tenant_id,source,account_id) VALUES($1,$2,'zendesk','SYNACCOUNT'),($3,$4,'zendesk','SYNACCOUNT')",[CA,A,CB,B]);
 await q("INSERT INTO imports(id,tenant_id,connection_id,file_hash,mapping_version,state,idempotency_key,object_path,total,accepted) VALUES($1,$2,$3,'SYN','v1','running','SYN',$4,1,1)",[I,A,CA,`${A}/imports/${I}/raw.csv`]);
 await q("INSERT INTO conversations(id,tenant_id,connection_id,source,external_id) VALUES($1,$2,$3,'zendesk','SYN-C')",[C,A,CA]);
 await q("INSERT INTO messages(id,tenant_id,connection_id,conversation_id,external_id,role) VALUES($1,$2,$3,$4,$5,'customer')",[M,A,CA,C,E]);
 await q("INSERT INTO message_revisions(id,tenant_id,message_id,revision,text_ref,redacted_text,hash) VALUES($1,$2,$3,'original','SYN-REF','SYN ORIGINAL SECRET',$4),($5,$2,$3,'redacted','SYN-REDACTED','SYN REDACTED SECRET',$4)",[R,A,M,'a'.repeat(64),RR]);
 await q("INSERT INTO import_rows(tenant_id,import_id,row_ref,state,payload_ref) VALUES($1,$2,'1','accepted','SYN-REF')",[A,I]);
 await q("INSERT INTO source_revisions(id,tenant_id,connection_id,entity_type,external_id,source_revision,content_hash,fingerprint,mapping_version,canonical_id,message_id,message_revision_id,snapshot,provenance) VALUES($1,$2,$3,'message',$4,'original',$5,$5,'v1',$6,$6,$7,'[]','{}')",[id(14),A,CA,E,'a'.repeat(64),M,R]);await q("INSERT INTO source_heads(id,tenant_id,connection_id,entity_type,external_id,selected_revision_id,version,state) VALUES($1,$2,$3,'message',$4,$5,1,'unique')",[M,A,CA,E,id(14)]);
 await q("INSERT INTO redaction_maps(tenant_id,original_revision_id,redacted_revision_id,policy_hash,private_map) VALUES($1,$2,$3,$4,'[\"SYN NAME\"]')",[A,R,RR,'a'.repeat(64)]);
 await q("INSERT INTO embeddings(id,tenant_id,message_revision_id,model_id,dim,version,content,embedding) VALUES($1,$2,$3,'SYN',3,'1','SYN REDACTED SECRET','[1,0,0]')",[id(15),A,RR]);
 await q("INSERT INTO sync_cursors(id,tenant_id,connection_id,import_id,scope_hash,mode,window_spec,mapping_version) VALUES($1,$2,$3,$4,$5,'live','{}','v1')",[id(16),A,CA,I,'b'.repeat(64)]);const raw={envelope:{entity_type:'message',external_id:E},payload:{text:'SYN RAW SECRET'}};
 await q("INSERT INTO sync_raw_objects(id,tenant_id,sync_id,connection_id,import_id,row_ref,raw_hash,original,normalized,result) VALUES($1,$2,$3,$4,$5,'1',$6,$7,$7,'{}')",[id(17),A,id(16),CA,I,'c'.repeat(64),JSON.stringify(raw)]);
 await q("INSERT INTO jobs(id,tenant_id,import_id,type,state,input_ref,input_hash,version) VALUES($1,$2,$3,'import','running','SYN','SYN','1')",[J,A,I]);
 await q("INSERT INTO metric_snapshots(id,tenant_id,scope_hash,input_hash,policy_version,watermark,status) VALUES($1,$2,'SYN-SCOPE','SYN','1',now(),'draft')",[SN,A]);await q("INSERT INTO components(id,tenant_id,snapshot_id,amount_minor,currency,exponent) VALUES($1,$2,$3,12345,'USD',2)",[id(18),A,SN]);await q("UPDATE metric_snapshots SET status='published',bundle_ref='SYN-BUNDLE',published_at=now() WHERE id=$1",[SN]);snapshotBefore=digest((await q('SELECT to_jsonb(s) AS s FROM metric_snapshots s WHERE id=$1',[SN])).rows[0].s);
 await q("INSERT INTO extraction_runs(id,tenant_id,model_id,prompt_hash,schema_hash,status,conversation_id,provenance) VALUES($1,$2,'SYN','SYN','SYN','succeeded',$3,$4)",[id(22),A,C,JSON.stringify({result:{issues:[{evidence:[{message_revision_id:RR,quote:'SYN REDACTED SECRET',quote_hash:'SYN'}]}]}})]);
 const briefDoc={metrics:[{amount_minor:'12345',currency:'USD'}],top3:[{evidence:[{messageRevisionId:RR,quote:'SYN REDACTED SECRET'}]}]};await q("INSERT INTO weekly_briefs(id,tenant_id,status,version,snapshot_id,document,canonical_document) VALUES($1,$2,'published',1,$3,$4,$5)",[id(23),A,SN,JSON.stringify(briefDoc),JSON.stringify(briefDoc)]);

 await q("INSERT INTO audit_events(tenant_id,actor,action,resource,reason,trace_id) VALUES($1,'SYN','checkpoint','SYN','before-backup','SYN')",[A]);
 await repo.policy({expectedVersion:0,backupTtlSeconds:3600});await createRecoveryRepository({database:db(sourcePool,B),storage:live,ledgerKey:key}).policy({expectedVersion:0,backupTtlSeconds:3600});
 for(const [className,p]of [['raw',`${A}/imports/${I}/raw.csv`],['cache',`${A}/cache/SYN.json`],['export',`${A}/exports/SYN.json`]]){await live.write(p,'SYN PRIVATE BYTES');await repo.registerArtifact({connectionId:CA,entityType:'message',sourceKey:E,class:className,objectPath:p,expiresAt:Date.now()+3500000});}await live.write(`${B}/cache/SYN.json`,'SYN B preserved');
 const denied=createRecoveryRepository({database:db(sourcePool,A,V),storage:live});await assert.rejects(()=>denied.erase({connectionId:CA,entityType:'message',externalId:E,requestId:id(20),confirmed:true}));await assert.rejects(()=>repo.erase({connectionId:CB,entityType:'message',externalId:E,requestId:id(20),confirmed:true}));

// Independent326: identical external ID in tenant B, plus registered TTL backup.
await q("INSERT INTO conversations(id,tenant_id,connection_id,source,external_id) VALUES($1,$2,$3,'zendesk','SYN-B-C')",[id(80),B,CB]);await q("INSERT INTO messages(id,tenant_id,connection_id,conversation_id,external_id,role) VALUES($1,$2,$3,$4,$5,'customer')",[id(81),B,CB,id(80),E]);await q("INSERT INTO message_revisions(id,tenant_id,message_id,revision,text_ref,redacted_text,hash) VALUES($1,$2,$3,'1','SYN-B-REF','SYN B DELETE LATER',$4)",[id(82),B,id(81),'d'.repeat(64)]);
await live.write(`${A}/backup/ttl`, 'SYN TTL BYTES');await repo.registerArtifact({connectionId:CA,entityType:'message',sourceKey:E,class:'backup',objectPath:`${A}/backup/ttl`,expiresAt:Date.now()+3500000});
 });
 await t.test('backup captures real PG dump and immutable storage bytes before deletion',async()=>{currentState=await seedCurrent({pool:sourcePool,db,id,A,B,U,V,CA,C,RR});backup=await backupLocal({mode:'synthetic-local',sourceContainer:'vexa-recovery-309-source',storageRoot:sourceStore,archive:path.join(root,'backup-original')});observations.backup=backup;assert.ok((await fs.stat(path.join(backup.archive,'database.dump'))).size>0);});
 await t.test('erasure purges raw/text/maps/vectors, fences jobs, prevents canonical replay',async()=>{
 cutoff=Date.now();await q("INSERT INTO audit_events(tenant_id,actor,action,resource,reason,trace_id) VALUES($1,'SYN','checkpoint','SYN','after-backup-control','SYN')",[A]);const erased=await repo.erase({connectionId:CA,entityType:'message',externalId:E,requestId:id(20),confirmed:true});assert.equal(erased.messages,1);assert.equal(erased.vectors,1);assert.equal((await q('SELECT state FROM jobs WHERE id=$1',[J])).rows[0].state,'cancelled');assert.equal((await q('SELECT count(*)::integer AS n FROM embeddings WHERE tenant_id=$1',[A])).rows[0].n,0);assert.equal((await q('SELECT redacted_text FROM message_revisions WHERE id=$1',[R])).rows[0].redacted_text,null);assert.deepEqual((await q('SELECT original FROM sync_raw_objects WHERE id=$1',[id(17)])).rows[0].original,{});assert.deepEqual((await q('SELECT private_map FROM redaction_maps WHERE tenant_id=$1',[A])).rows[0].private_map,[]);assert.equal(await database.transaction('read',s=>readCanonicalHistory(s,{canonicalId:M})),null);
 const p={text:'SYN ATTEMPTED RESURRECTION',role:'customer',conversation_external_id:'SYN-C'};const envelope=createEnvelope({tenant_id:A,connection_id:CA,source:'zendesk',source_account_id:'SYNACCOUNT'},{entity_type:'message',external_id:E,source_revision:'resurrect',observed_at:new Date().toISOString(),payload_ref:'SYN'},p);
 const replay=await database.transaction('import',s=>persistCanonical(s,{importId:I,record:{envelope,payload:p,mapping_version:'v1',row_ref:'new-replay'}}));assert.equal(replay.code,'SOURCE_TOMBSTONED');assert.equal((await q('SELECT count(*)::integer AS n FROM message_revisions WHERE message_id=$1',[M])).rows[0].n,2);
 const purged=await repo.purgeArtifacts();assert.equal(purged.complete,true);assert.equal(await live.exists(`${A}/cache/SYN.json`),false);assert.equal(await live.exists(`${A}/exports/SYN.json`),false);assert.equal(await live.exists(`${A}/imports/${I}/raw.csv`),false);assert.equal(await live.exists(`${B}/cache/SYN.json`),true);
 assert.equal((await q('SELECT redacted_text FROM message_revisions WHERE id=$1',[id(82)])).rows[0].redacted_text,'SYN B DELETE LATER','TENANT_B_PRESERVED_BY_A_ERASE');
assert.equal(await live.exists(`${A}/backup/ttl`),true,'UNEXPIRED_BACKUP_RETAINED');await q("UPDATE retention_artifacts SET expires_at=clock_timestamp()-interval '1 second' WHERE tenant_id=$1 AND class='backup'",[A]);assert.equal((await repo.purgeArtifacts()).complete,true);assert.equal(await live.exists(`${A}/backup/ttl`),false,'EXPIRED_BACKUP_PHYSICALLY_PURGED');
await createRecoveryRepository({database:db(sourcePool,B),storage:live,ledgerKey:key}).erase({connectionId:CB,entityType:'message',externalId:E,requestId:id(83),confirmed:true});
ledgerA=await repo.exportLedger();ledgerB=await createRecoveryRepository({database:db(sourcePool,B),ledgerKey:key}).exportLedger();const bad=structuredClone(ledgerA);bad.payload.events=[];await assert.rejects(()=>repo.reapplyLedger(bad,{expectedHash:ledgerA.sha256,notBefore:cutoff}));observations.erased=erased;observations.ledgerHash=ledgerA.sha256;
 });
 await t.test('old backup + latest independent signed ledger restores every tenant without resurrection',async()=>{
 const keyFile=path.join(root,'ledger-key');await fs.writeFile(keyFile,key,{mode:0o600});const ledgers=[];for(const [tenantId,ledger]of [[A,ledgerA],[B,ledgerB]]){const file=path.join(root,tenantId+'.ledger.json');await fs.writeFile(file,JSON.stringify(ledger),{mode:0o600});ledgers.push({tenantId,actorId:U,ledgerFile:file,ledgerKeyFile:keyFile,expectedLedgerHash:ledger.sha256,recoveryCutoff:cutoff});}
 const base={mode:'synthetic-local',sourceContainer:'vexa-recovery-309-source',targetContainer:'vexa-recovery-309-target',storageRoot:targetStore,archive:backup.archive,expectedManifestHash:backup.manifestHash,recoveryCutoff:cutoff,confirmEmptyTarget:true};await assert.rejects(()=>restoreLocal({...base,ledgers:ledgers.slice(0,1)}));// A constraint-only schema mismatch must fail before data load.
await targetPool.query('ALTER TABLE organizations ADD CONSTRAINT syn326_mismatch CHECK (true)');await assert.rejects(restoreLocal({...base,ledgers}),/SYNTHETIC_RECOVERY_GUARD/);assert.equal((await targetPool.query('SELECT count(*) FROM organizations')).rows[0].count,'0');await targetPool.query('ALTER TABLE organizations DROP CONSTRAINT syn326_mismatch');
await assert.rejects(live.write('../escape','SYN'),/SYNTHETIC_RECOVERY_GUARD/);await fs.symlink(os.tmpdir(),path.join(sourceStore,'escape-link'));await assert.rejects(live.read('escape-link/test'),/SYNTHETIC_RECOVERY_GUARD/);await fs.unlink(path.join(sourceStore,'escape-link'));
const result=await restoreLocal({...base,ledgers});assert.equal(result.reconciliations.length,2);assert.equal((await targetPool.query('SELECT redacted_text FROM message_revisions WHERE id=$1',[id(82)])).rows[0].redacted_text,null,'TENANT_B_POST_BACKUP_ERASURE_REPLAYED');assert.equal((await targetPool.query("SELECT datconnlimit FROM pg_database WHERE datname='postgres'")).rows[0].datconnlimit,0);observations.restore=result;assert.equal(result.backupOriginalHashUnchanged,true);assert.equal((await targetPool.query('SELECT count(*)::integer AS n FROM embeddings WHERE tenant_id=$1',[A])).rows[0].n,0);assert.equal((await targetPool.query('SELECT redacted_text FROM message_revisions WHERE id=$1',[R])).rows[0].redacted_text,null);const restoredStorage=await createLocalStorage(targetStore);assert.equal(await restoredStorage.exists(`${A}/cache/SYN.json`),false);assert.equal(await restoredStorage.exists(`${B}/cache/SYN.json`),true);assert.equal(await restoredStorage.exists(`${A}/imports/${I}/raw.csv`),false);assert.equal((await targetPool.query('SELECT count(*)::integer AS n FROM retention_ledger WHERE tenant_id=$1',[A])).rows[0].n,ledgerA.payload.events.length);assert.equal(await db(targetPool).transaction('read',s=>readCanonicalHistory(s,{canonicalId:M})),null);
 const restoredRun=(await targetPool.query('SELECT provenance FROM extraction_runs WHERE id=$1',[id(22)])).rows[0].provenance;assert.equal(restoredRun.result.issues[0].evidence[0].quote,null);const restoredBrief=(await targetPool.query('SELECT document,canonical_document FROM weekly_briefs WHERE id=$1',[id(23)])).rows[0];assert.equal(restoredBrief.document.top3[0].evidence[0].quote,null);assert.deepEqual(JSON.parse(restoredBrief.canonical_document),restoredBrief.document);assert.equal(restoredBrief.document.metrics[0].amount_minor,'12345');assert.equal((await targetPool.query('SELECT count(*)::integer n FROM retention_redactions WHERE tenant_id=$1',[A])).rows[0].n,2);observations.derivedRestore={quotesAbsent:true,financialAmountUnchanged:true,redactionReceipts:2};
 // Prior application query shape remains valid on expanded schema; last authorized financial bundle is identical.
 const saved=(await targetPool.query('SELECT to_jsonb(s) AS s FROM metric_snapshots s WHERE id=$1',[SN])).rows[0].s;assert.equal(digest(saved),snapshotBefore);const oldRead=await db(targetPool).transaction('read',s=>s.query("SELECT s.bundle_ref,c.amount_minor FROM metric_snapshots s JOIN components c ON c.tenant_id=s.tenant_id AND c.snapshot_id=s.id WHERE s.tenant_id=$1 AND s.status='published'",[A]));assert.equal(oldRead.rows[0].amount_minor,'12345');const latestSource=(await q("SELECT max(occurred_at) AS at FROM audit_events WHERE tenant_id=$1 AND action='checkpoint'",[A])).rows[0].at;const latestRestored=(await targetPool.query("SELECT max(occurred_at) AS at FROM audit_events WHERE tenant_id=$1 AND action='checkpoint'",[A])).rows[0].at;observations.rpo={observedMs:latestSource.getTime()-latestRestored.getTime(),lostControlMarkers:1,definition:'Difference between latest source and restored synthetic checkpoint; tombstones replayed separately; no SLA'};assert.ok(observations.rpo.observedMs>=0);
 observations.currentSchema=await checkCurrent({pool:targetPool,db,id,A,B,U,V,CA,C,RR,state:currentState});observations.rollback={schemaStrategy:'expand-only-no-down-migration',financialSnapshotHashUnchanged:true,lastPublishedAmountMinor:'12345',scope:'legacy-authorized-SQL-shape-not-full-web-rollback'};
 });
});
