import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {runGroup} from '../F07-load/process.mjs';
export async function launch(){
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'VEXA_CANDIDATE_REQUIRED');
 for(const name of ['packages/recovery/index.mjs','packages/recovery/local.mjs','supabase/migrations/0038_team_invitations.sql'])assert.ok(fs.existsSync(path.join(candidate,name)),'RECOVERY_IMPLEMENTATION_MISSING:'+name);
 assert.ok(!process.env.VEXA_CI_JOURNAL&&!process.env.VEXA_CI_BROKER,'EXCLUSIVE_RESOURCE_JOURNAL_REQUIRED');
 const root=path.resolve(import.meta.dirname,'../..'),out=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'f0706-external-'));fs.chmodSync(out,0o700);const evidence=path.join(out,'restore');fs.mkdirSync(evidence,{mode:0o700});console.log('F07-06 evidence: '+out);
 const env={...process.env,VEXA_EVIDENCE:evidence};delete env.NODE_TEST_CONTEXT;
 const restore=await runGroup(process.execPath,[path.join(root,'support/F07-recovery/drill-run.mjs')],{env,log:path.join(out,'restore.log'),timeoutMs:480000});fs.writeFileSync(path.join(out,'restore-process.json'),JSON.stringify(restore)+'\n',{mode:0o600});assert.ok(!restore.timedOut&&!restore.error&&restore.signal===null&&restore.code===0,'RESTORE_PROCESS_OR_CLEANUP_FAILED');
 const observed=JSON.parse(fs.readFileSync(path.join(evidence,'drill-artifacts/observations.json'))),cleanup=JSON.parse(fs.readFileSync(path.join(evidence,'cleanup.json')));
 assert.equal(observed.restore.backupOriginalHashUnchanged,true);assert.equal(Object.keys(observed.currentSchema.tablesIdentical).length,7);assert.equal(observed.currentSchema.unknownCostPreserved,true);assert.equal(observed.currentSchema.erasedFeedbackRejected,true);assert.equal(observed.currentSchema.candidates.restoredRollbackVersion,3);assert.equal(observed.currentSchema.candidates.staleCasDenied,true);assert.equal(observed.currentSchema.candidates.revokedCustodianDenied,true);assert.equal(observed.rollback.financialSnapshotHashUnchanged,true);assert.ok(cleanup.temporaryRemoved&&cleanup.resources.length===3&&cleanup.resources.every(x=>x.absent));
 let rollbackEvidence;const rollback=await runGroup(process.execPath,[path.join(root,'support/F07-recovery/rollback.mjs')],{env,log:path.join(out,'rollback.log'),timeoutMs:480000,onLine:line=>{if(line.startsWith('{')){const record=JSON.parse(line);if(record.evidence)rollbackEvidence=record.evidence;}}});fs.writeFileSync(path.join(out,'rollback-process.json'),JSON.stringify(rollback)+'\n',{mode:0o600});assert.ok(!rollback.timedOut&&!rollback.error&&rollback.signal===null&&rollback.code===0,'ROLLBACK_PROCESS_OR_CLEANUP_FAILED');assert.ok(rollbackEvidence);
 const receipt=JSON.parse(fs.readFileSync(path.join(rollbackEvidence,'receipt.json')));assert.equal(receipt.status,'pass_local_previous_binary_financial_continuity');assert.equal(receipt.observed.before_hash,receipt.observed.after_hash);assert.equal(receipt.observed.previous_served_sha,'d1956d991bbf3d0332b4abb0fd50be464ea312db');assert.equal(receipt.observed.refund_minor,'1500');assert.equal(receipt.observed.foreign_status,404);assert.equal(receipt.observed.roll_forward_identical,true);assert.ok(receipt.build_removed&&receipt.previous_source_removed&&receipt.cleanup.ownResourcesRemoved&&receipt.cleanup.resources.every(x=>x.absent));
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'local_restore_and_financial_rollback_verified',candidate,restoreEvidence:evidence,rollbackEvidence,production:false,previous_app_not_general_recommendation:true})+'\n',{mode:0o600});return out;
}
