import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {once} from 'node:events';import {createHash} from 'node:crypto';
import {copyBuildInputs,buildEnvironment} from '../../tests/acceptance/scaffold-copy.mjs';import {prepareControl} from '../F07-chaos/control.mjs';import {pathToFileURL} from 'node:url';import {seedDetail,detailQuery} from '../F06-detail/fixtures.mjs';
const root=path.resolve(import.meta.dirname,'../..'),current=process.env.VEXA_CANDIDATE,previous='d1956d991bbf3d0332b4abb0fd50be464ea312db';assert.ok(current,'VEXA_CANDIDATE_REQUIRED');
const evidence=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'vexa-app-rollback-current-'));fs.chmodSync(evidence,0o700);const old=path.join(evidence,'previous-source'),build=path.join(evidence,'previous-build'),control=path.join(evidence,'control');fs.mkdirSync(old);fs.mkdirSync(control);prepareControl(root,control);const {setup,q}=await import(pathToFileURL(path.join(control,'harness.mjs')));const report={status:'running',previous,current_source:current,schema:'candidate migrations, with current tested baseline through0038',node:process.version,pid:process.pid,commands:[],scope:'local real previous Next binary financial snapshot continuity; not all old routes or production',known_previous_limit:'d195 candidate lists fail above100; never a blanket rollback recommendation'};let h,web;
const hash=x=>createHash('sha256').update(x).digest('hex'),save=()=>fs.writeFileSync(path.join(evidence,'receipt.json'),JSON.stringify(report,null,2)+'\n',{mode:0o600});save();console.log(evidence);
try{
 const archive=spawnSync('git',['archive',previous,'--','package.json','package-lock.json','apps','packages'],{cwd:root,timeout:30000,maxBuffer:64*1024*1024});assert.ok(!archive.error&&archive.signal===null&&archive.status===0,'KNOWN_PRIOR_SOURCE_REQUIRED');const unpack=spawnSync('tar',['-xf','-','-C',old],{input:archive.stdout,timeout:30000});assert.ok(!unpack.error&&unpack.signal===null&&unpack.status===0,'PRIOR_SOURCE_UNPACK');report.previous_archive_sha256=hash(archive.stdout);
 copyBuildInputs(old,build);const env={...buildEnvironment(process.env,build),PATH:path.dirname(process.execPath)+':'+process.env.PATH,VEXA_BUILD_REVISION:previous};
 for(const args of [['ci','--offline','--ignore-scripts','--no-audit','--no-fund'],['run','lint','--workspace','@vexa/web'],['run','build','--workspace','@vexa/web']]){const result=spawnSync('npm',args,{cwd:build,env,encoding:'utf8',timeout:150000,maxBuffer:8*1024*1024});fs.writeFileSync(path.join(evidence,'build-'+report.commands.length+'.log'),(result.stdout??'')+(result.stderr??''));report.commands.push({args,status:result.status,signal:result.signal,error:result.error?.message??null});save();assert.ok(!result.error&&result.signal===null&&result.status===0,'PREVIOUS_BUILD');}
 h=await setup(current,evidence);const fixture=await seedDetail(h);const snap=()=>h.json(`SELECT jsonb_build_object('snapshot',(SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(fixture.snapshot.id)}),'components',(SELECT jsonb_agg(to_jsonb(c) ORDER BY c.id) FROM components c WHERE snapshot_id=${q(fixture.snapshot.id)}))`),original=hash(JSON.stringify(snap()));
 const query=detailQuery(fixture.snapshot,null,{resource:'problems'}),endpoint='/api/workspace?'+query;
 const read=async()=>{const response=await h.request(h.A,endpoint);assert.equal(response.status,200);const workspace=response.data.data;const detail=await h.request(h.A,'/api/workspace/detail/problem/'+fixture.p1.id+'?'+detailQuery(fixture.snapshot,workspace.meta.scope_hash));assert.equal(detail.status,200);const data=detail.data.data;assert.equal(data.snapshot_id,fixture.snapshot.id);assert.equal(data.components.find(x=>x.metric==='refunds').money.known_subtotal,'1500');return{snapshot_id:data.snapshot_id,scope_hash:data.scope_hash,detail_hash:data.detail_hash,components:data.components,workspace};};
 const before=await read();await h.stopWeb();
 web=spawn(process.execPath,[path.join(build,'node_modules/next/dist/bin/next'),'start',path.join(build,'apps/web'),'--hostname','127.0.0.1','--port','61624'],{cwd:build,env:{...h.common,NEXT_PUBLIC_SUPABASE_URL:h.common.VEXA_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY:h.common.VEXA_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL:h.base},stdio:['ignore','ignore','ignore']});report.previous_pid=web.pid;save();
 let version;for(let i=0;i<150;i++){try{const r=await fetch(h.base+'/api/health/version',{signal:AbortSignal.timeout(1000)});if(r.ok){version=await r.json();break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}assert.equal(version?.data?.revision,previous,'PREVIOUS_BINARY_SERVED');
 const after=await read();assert.deepEqual(after,before,'PREVIOUS_BINARY_SNAPSHOT_CONTINUITY');assert.equal(hash(JSON.stringify(snap())),original,'ROLLBACK_DID_NOT_MUTATE_SNAPSHOT');assert.equal((await h.request(h.B,endpoint)).status,404,'FOREIGN_SNAPSHOT_NOT_VISIBLE');
 const end=once(web,'exit');web.kill('SIGTERM');await end;web=null;await h.startWeb();assert.deepEqual(await read(),before,'ROLL_FORWARD_SNAPSHOT_CONTINUITY');
 report.observed={previous_served_sha:version.data.revision,before_hash:hash(JSON.stringify(before)),after_hash:hash(JSON.stringify(after)),snapshot_hash:original,refund_minor:'1500',foreign_status:404,roll_forward_identical:true};h.verifySources();report.status='pass_local_previous_binary_financial_continuity';
}catch(error){report.status='failed';report.error={message:error.message,stack:error.stack};process.exitCode=1;}finally{
 if(web&&web.exitCode===null&&web.signalCode===null){const end=once(web,'exit');web.kill('SIGKILL');await end;}
 if(h)try{await h.close();report.cleanup=JSON.parse(fs.readFileSync(path.join(evidence,'cleanup.json')));}catch(e){report.status='failed';report.cleanup_error=e.message;process.exitCode=1;}
 if(report.status==='pass_local_previous_binary_financial_continuity'){fs.rmSync(build,{recursive:true,force:true});report.build_removed=true;fs.rmSync(old,{recursive:true,force:true});report.previous_source_removed=true;}
 save();console.log(JSON.stringify({status:report.status,error:report.error,evidence}));
}
