import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {setup,q} from './harness.mjs';
import {seedNotifications} from './fixtures.mjs';
import {assertNotificationDatabaseBoundary} from './database-boundary.mjs';
import './pure.mjs';
const route='/api/notifications',prefRoute=route+'/preferences';
async function bounded(p,label){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('NOTIFICATION_HANDSHAKE:'+label)),20000);})]);}finally{clearTimeout(timer);}}
test('F06-08 current membership owns inbox preferences and resource access across real API and browser',{timeout:480000},async t=>{
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate&&fs.existsSync(path.join(candidate,'packages/notifications/index.mjs')),'NOTIFICATION_IMPLEMENTATION_MISSING');
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-notification294-'));fs.chmodSync(evidence,0o700);console.log('F0608_RUNNING:'+evidence);let h;
 const step=async(name,fn)=>{let error;await t.test(name,async()=>{try{await fn();}catch(e){error=e;throw e;}});if(error)throw Error('NOTIFICATION_PREREQUISITE:'+name,{cause:error});};
 try{
  h=await setup(candidate,evidence);let f,preferences,cursor,readResult,baselineWrites;
  const request=async(actor,url,body)=>{const r=await h.request(actor,url,body);assert.equal(r.data.contract_version,'f06-notifications-v1');assert.match(r.data.meta?.trace_id??'',/^[0-9a-f-]{36}$/i);if(r.status!==200)assert.equal(r.data.error.retryable,r.status===503);return r;};
  const ok=async promise=>{const r=await promise;assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};
  const list=(actor=h.A,query='limit=10&status=all')=>request(actor,route+'?'+query);
  const prefs=(actor=h.A)=>request(actor,prefRoute);
  const save=(body,actor=h.A)=>request(actor,prefRoute,body);
  const read=(id,actor=h.A,body={})=>request(actor,route+'/'+id+'/read',body);
  const writes=()=>h.json("SELECT jsonb_build_object('jobs',(SELECT count(*) FROM jobs),'outbox',(SELECT count(*) FROM outbox),'ledger',(SELECT count(*) FROM economic_ledger_entries),'snapshots',(SELECT count(*) FROM metric_snapshots),'crm',(SELECT count(*) FROM crm_sync_settings),'events',(SELECT count(*) FROM notification_events),'inbox',(SELECT count(*) FROM notification_inbox))");
  await step('real fixture has published authorized resource and recipients from memberships only',async()=>{
   f=await seedNotifications(h);baselineWrites=writes();assert.equal((await ok(list())).items.length,10);preferences=await ok(prefs());assert.equal(preferences.catalog.length,6);assert.ok(preferences.catalog.every(x=>x.connected===false));assert.deepEqual(preferences.channels.map(x=>x.id).sort(),['email','inapp','push']);assert.ok(preferences.channels.every(x=>x.deliveryAvailable===false&&x.reason));assert.ok(preferences.preferences.every(x=>x.enabled===false&&x.version===0));
  });
  await step('notify database capability is bounded and pooled identity does not leak',async()=>{await assertNotificationDatabaseBoundary(h);});
  await step('inbox pagination enumerates unique own IDs and cursor cannot cross user tenant or filters',async()=>{
   let page=await ok(list()),ids=[];cursor=page.nextCursor;assert.ok(cursor);for(let i=0;i<10;i++){ids.push(...page.items.map(x=>x.id));for(const item of page.items){assert.equal(item.resourceId,f.brief.id);assert.ok(item.href.startsWith('/'));assert.equal(item.readAt,null);}if(!page.nextCursor)break;page=await ok(list(h.A,'limit=10&status=all&cursor='+encodeURIComponent(page.nextCursor)));assert.ok(i<9,'INBOX_CURSOR_LOOP');}assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids.slice().sort(),f.ownIds.slice().sort());assert.equal((await ok(list(f.viewer))).items.length,1);assert.equal((await ok(list(h.B))).items.length,0);for(const [actor,query] of [[f.viewer,'limit=10&status=all'],[h.B,'limit=10&status=all'],[h.A,'limit=10&status=unread'],[h.A,'limit=1&status=all']])assert.equal((await list(actor,query+'&cursor='+encodeURIComponent(cursor))).status,409);h.sql(`UPDATE memberships SET permissions_version=permissions_version+1 WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);assert.equal((await list(h.A,'limit=10&status=all&cursor='+encodeURIComponent(cursor))).status,409);fs.writeFileSync(path.join(evidence,'inbox-pages.json'),JSON.stringify({ids,cursorBoundTo:'tenant/user/permissions/filter/limit'}));
  });
  await step('REST direct calls cannot change another member or create a CRM recipient',async()=>{
   assert.equal((await list(null)).status,401);for(const actor of [h.A,h.B,f.viewer])for(const table of ['notification_events','notification_inbox','notification_preferences']){const direct=await h.auth('rest','/'+table+'?select=*',actor.token);assert.equal(direct.status,403,'DIRECT_TABLE_ACCESS_DENIED:'+table);assert.equal(direct.data.code,'42501');}const directPatch=await h.auth('rest','/notification_inbox?id=eq.'+f.ownIds[0],f.viewer.token,{method:'PATCH',body:{read_at:new Date().toISOString()}});assert.equal(directPatch.status,403);assert.equal(directPatch.data.code,'42501');assert.equal((await read(f.ownIds[0],f.viewer)).status,404);assert.equal((await read(f.viewerId,h.A)).status,404);assert.equal((await read(f.ownIds[0],h.B)).status,404);for(const extra of [{userId:f.viewer.id},{tenantId:h.B.tenant},{recipientId:f.customerId},{email:'SYN-no-send@example.test'}])assert.equal((await save({channel:'inapp',eventType:'*',enabled:true,expectedVersion:0,...extra})).status,400);assert.equal((await read(f.ownIds[0],h.A,{userId:f.viewer.id})).status,400);assert.equal((await fetch(h.base+route,{method:'POST',headers:{cookie:h.cookie(h.A),Origin:h.base,'content-type':'application/json'},body:JSON.stringify({userId:f.customerId,eventType:'brief.available',resourceId:f.brief.id})})).status,405);for(const query of ['limit=0','limit=101','status=unknown','limit=1&limit=2','userId='+f.viewer.id])assert.equal((await list(h.A,query)).status,400);const noOrigin=await fetch(h.base+prefRoute,{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify({channel:'inapp',eventType:'*',enabled:true,expectedVersion:0})});assert.equal(noOrigin.status,403);assert.deepEqual(writes(),baselineWrites);
  });
  await step('viewer preferences are personal persisted CAS and do not enable a delivery transport',async()=>{
   const input={channel:'email',eventType:'brief.available',enabled:true,expectedVersion:0};const results=await Promise.all([save(input,f.viewer),save({...input,enabled:false},f.viewer)]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);let view=await ok(prefs(f.viewer));let row=view.preferences.find(x=>x.channel==='email'&&x.eventType==='brief.available');assert.equal(row.version,1);const next=await ok(save({...input,enabled:!row.enabled,expectedVersion:row.version},f.viewer));assert.ok(next);view=await ok(prefs(f.viewer));row=view.preferences.find(x=>x.channel==='email'&&x.eventType==='brief.available');assert.equal(row.version,2);assert.equal((await save(input,f.viewer)).status,409);assert.equal((await ok(prefs())).preferences.find(x=>x.channel==='email'&&x.eventType==='brief.available').version,0);assert.equal((await ok(prefs(h.B))).preferences.find(x=>x.channel==='email'&&x.eventType==='brief.available').version,0);assert.ok(view.channels.every(x=>x.deliveryAvailable===false));assert.deepEqual(writes(),baselineWrites);
  });
  await step('mark read is owned idempotent under concurrency and unread pagination changes honestly',async()=>{
   const results=await Promise.all([read(f.ownIds[0]),read(f.ownIds[0])]);assert.deepEqual(results.map(x=>x.status),[200,200]);readResult=results[0].data.data;assert.equal(readResult.id,f.ownIds[0]);assert.equal(results[1].data.data.readAt,readResult.readAt);assert.equal((await ok(read(f.ownIds[0]))).readAt,readResult.readAt);const unread=await ok(list(h.A,'limit=100&status=unread'));assert.equal(unread.items.length,f.ownIds.length-1);assert.ok(!unread.items.some(x=>x.id===readResult.id));const all=await ok(list(h.A,'limit=100&status=all'));assert.equal(all.items.find(x=>x.id===readResult.id).readAt,readResult.readAt);assert.equal((await ok(list(f.viewer))).items[0].readAt,null);assert.deepEqual(writes(),baselineWrites);
  });
  await step('real navigation shows authorized notices and failed loading is an error instead of empty',async()=>{
   const browser=await h.browser(),ctx=await browser.newContext({timezoneId:'America/Merida'});ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(value=>{const i=value.indexOf('=');return{name:value.slice(0,i),value:value.slice(i+1),url:h.base};}));h.ctx=ctx;h.p=await ctx.newPage();await h.p.goto(h.base+'/overview?'+f.query);await h.p.getByRole('link',{name:'Notificaciones',exact:true}).click();const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});await panel.getByRole('list',{name:'Avisos disponibles',exact:true}).waitFor();assert.equal(new URL(h.p.url()).pathname,'/notifications');assert.ok(await panel.locator('article[data-notification-id]').count()>0);let once=false;await h.p.route('**/api/notifications?*',async intercepted=>{if(!once&&intercepted.request().method()==='GET'&&new URL(intercepted.request().url()).searchParams.get('limit')!=='1'){once=true;await intercepted.abort('failed');}else await intercepted.continue();});await panel.getByRole('button',{name:'Actualizar notificaciones',exact:true}).click();await panel.getByRole('alert').waitFor();assert.equal(await panel.locator('article[data-notification-id]').count(),0);assert.equal(await panel.getByText(/No tienes notificaciones|No hay avisos/).count(),0);await h.p.unroute('**/api/notifications?*');await panel.getByRole('button',{name:'Actualizar notificaciones',exact:true}).click();await panel.getByRole('list',{name:'Avisos disponibles',exact:true}).waitFor();await h.p.screenshot({path:path.join(evidence,'notifications-inbox.png'),fullPage:true});await h.p.setViewportSize({width:390,height:844});await h.p.screenshot({path:path.join(evidence,'notifications-mobile.png'),fullPage:true});await h.p.setViewportSize({width:1280,height:900});
  });
  await step('browser pagination preserves unique notices and the unread filter resets its page',async()=>{
   const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).uncheck();await panel.getByRole('button',{name:'Cargar más avisos',exact:true}).click();const expected=f.ownIds.length;await h.p.waitForFunction(n=>document.querySelectorAll('article[data-notification-id]').length===n,expected);const ids=await panel.locator('article[data-notification-id]').evaluateAll(nodes=>nodes.map(x=>x.getAttribute('data-notification-id')));assert.equal(new Set(ids).size,expected);assert.deepEqual(ids.slice().sort(),f.ownIds.slice().sort());const loaded=h.p.waitForResponse(r=>new URL(r.url()).pathname===route&&r.request().method()==='GET'&&new URL(r.url()).searchParams.get('status')==='unread');await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).check();assert.equal((await loaded).status(),200);assert.equal(await panel.locator('article[data-notification-id="'+readResult.id+'"]').count(),0);assert.ok(await panel.locator('article[data-notification-id]').count()<=30);
  });
  await step('preferences survive a lost committed response and refresh without pretending delivery',async()=>{
   await h.p.getByRole('link',{name:'Configurar avisos',exact:true}).click();const panel=h.p.getByRole('region',{name:'Preferencias de notificaciones',exact:true});const channel=preferences.channels.find(x=>x.id==='inapp'),fieldset=panel.getByRole('group',{name:channel.label,exact:true}),checkbox=fieldset.getByLabel('Activar '+channel.label,{exact:true});await checkbox.waitFor();assert.equal(await checkbox.isChecked(),false);let mark,finish;const started=new Promise(r=>mark=r),finished=new Promise(r=>finish=r);let once=false;await h.p.route('**/api/notifications/preferences',async intercepted=>{if(!once&&intercepted.request().method()==='POST'){once=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);mark();await intercepted.abort('failed');}finally{finish();}}else await intercepted.continue();});await checkbox.click();await bounded(started,'preference-committed');await bounded(finished,'preference-response-lost');await panel.getByRole('alert').waitFor();await h.p.unroute('**/api/notifications/preferences');const after=await ok(prefs());const row=after.preferences.find(x=>x.channel==='inapp'&&x.eventType==='*');assert.equal(row.enabled,true);assert.equal(row.version,1);assert.deepEqual(writes(),baselineWrites);await panel.getByRole('button',{name:'Actualizar preferencias',exact:true}).click();await checkbox.waitFor();assert.equal(await checkbox.isChecked(),true);await checkbox.click();await panel.getByText('Preferencias guardadas y verificadas.',{exact:true}).waitFor();const updated=await ok(prefs());assert.equal(updated.preferences.find(x=>x.channel==='inapp'&&x.eventType==='*').enabled,false);assert.ok(updated.channels.every(x=>x.deliveryAvailable===false));await h.p.reload();await checkbox.waitFor();assert.equal(await checkbox.isChecked(),false);await h.p.screenshot({path:path.join(evidence,'notification-preferences.png'),fullPage:true});await h.p.getByRole('link',{name:'Ver notificaciones',exact:true}).click();await h.p.getByRole('list',{name:'Avisos disponibles',exact:true}).waitFor();
  });
  await step('real double click marks a notice once and CTA opens its currently authorized real resource',async()=>{
   const item=(await ok(list(h.A,'limit=1&status=unread'))).items[0];f.uiId=item.id;const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true}),article=panel.locator('article[data-notification-id="'+item.id+'"]');await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).uncheck();await article.waitFor();await article.getByRole('button',{name:'Marcar como leído',exact:true}).dblclick();await article.getByText(/^Leído ·/).waitFor();const persisted=await ok(read(item.id));assert.equal((await ok(read(item.id))).readAt,persisted.readAt);const resource= h.p.waitForResponse(r=>new URL(r.url()).pathname==='/api/briefs/'+f.brief.id&&r.request().method()==='GET');await article.getByRole('link',{name:'Abrir detalle',exact:true}).click();assert.equal((await resource).status(),200);assert.equal(new URL(h.p.url()).pathname,'/briefs/'+f.brief.id);await h.p.getByRole('article',{name:'Brief versión '+f.brief.version,exact:true}).waitFor();await h.p.getByRole('link',{name:'Notificaciones',exact:true}).click();await h.p.getByRole('list',{name:'Avisos disponibles',exact:true}).waitFor();
  });
  await step('resource withdrawal removes list payload and rejects fresh read and CTA authorization',async()=>{
   const connection=f.a.a.connection;h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(connection)}`);try{const page=await ok(list(h.A,'limit=100&status=all'));assert.equal(page.items.length,0);assert.equal((await read(f.ownIds[0])).status,404);const briefResponse=await h.request(h.A,'/api/briefs/'+f.brief.id);assert.ok([403,404].includes(briefResponse.status));const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).uncheck();const refreshed=h.p.waitForResponse(r=>new URL(r.url()).pathname===route&&r.request().method()==='GET');await panel.getByRole('button',{name:'Actualizar notificaciones',exact:true}).click();assert.equal((await refreshed).status(),200);await panel.getByText('No hay avisos disponibles.',{exact:true}).waitFor();assert.equal(await panel.getByRole('link',{name:'Abrir detalle',exact:true}).count(),0);}finally{h.sql(`UPDATE connections SET status='active' WHERE id=${q(connection)}`);}const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});await panel.getByRole('button',{name:'Actualizar notificaciones',exact:true}).click();await panel.getByRole('list',{name:'Avisos disponibles',exact:true}).waitFor();
  });
  await step('late inbox response cannot restore another page or history after membership revocation',async()=>{
   const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});let mark,finish,release;const started=new Promise(r=>mark=r),finished=new Promise(r=>finish=r),held=new Promise(r=>release=r);h.releaseHeld=release;let once=false;await h.p.route('**/api/notifications?*',async intercepted=>{if(once||new URL(intercepted.request().url()).searchParams.get('limit')==='1'){await intercepted.continue();return;}once=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);const bytes=await response.body();assert.ok(JSON.parse(bytes.toString()).data.items.length>0);mark();await held;await intercepted.fulfill({status:200,headers:response.headers(),body:bytes}).catch(()=>{});}finally{finish();}});await panel.getByRole('button',{name:'Actualizar notificaciones',exact:true}).click();await bounded(started,'inbox-authorized-captured');h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);for(const response of [await list(),await prefs(),await read(f.ownIds[0])])assert.equal(response.status,403);await h.p.getByRole('navigation',{name:'Espacio de trabajo',exact:true}).getByRole('link',{name:'Resumen',exact:true}).click();await h.p.getByText(/Acceso denegado|Tu acceso cambió|Acceder a VEXA/).first().waitFor();await h.p.goBack();await h.p.getByText(/Acceso denegado|Tu acceso cambió|Acceder a VEXA/).first().waitFor();release();await bounded(finished,'inbox-late-released');await h.p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await h.p.locator('article[data-notification-id]').count(),0);assert.equal(await h.p.getByRole('link',{name:'Abrir detalle',exact:true}).count(),0);await h.p.screenshot({path:path.join(evidence,'notifications-revoked.png'),fullPage:true});
  });
  await step('inbox operations have no external delivery or business side effects',async()=>{
   assert.deepEqual(writes(),baselineWrites);const attempts=fs.readFileSync(path.join(evidence,'outbound-attempts.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);assert.ok(attempts.length>0);assert.equal(attempts.filter(x=>x.blocked).length,0);fs.writeFileSync(path.join(evidence,'no-external-effects.json'),JSON.stringify({writes:baselineWrites,externalAttempts:0,observedLocalRequests:attempts.length}));
  });
 }finally{if(h){try{h.releaseHeld?.();if(h.p){fs.writeFileSync(path.join(evidence,'last-dom.html'),await h.p.content());fs.writeFileSync(path.join(evidence,'last-url.txt'),h.p.url());await h.p.screenshot({path:path.join(evidence,'last-ui.png'),fullPage:true});}}catch{}await h.close();}console.log('F0608_EVIDENCE:'+evidence);}
});
