import {spawn} from 'node:child_process';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createServer} from 'node:http';import {once} from 'node:events';import {randomUUID} from 'node:crypto';
import {setup,q} from './support/F03-runtime/harness.mjs';
test('CRM browser configuration to hosted worker provider transport SQL health and reconnect',{timeout:540000},async t=>{
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-f03-runtime-external-'));fs.chmodSync(evidence,0o700);let h,provider;const requests=[];let mode='ok';
 try{
  h=await setup(process.env.VEXA_CANDIDATE,evidence);
  provider=createServer((req,res)=>{requests.push({path:req.url,method:req.method});res.setHeader('Content-Type','application/json');if(req.headers.authorization!=='Bearer SYN-CRM-SECRET'){res.writeHead(401);return res.end('{}');}if(mode==='revoked'){res.writeHead(401);return res.end('{}');}const p=new URL(req.url,'http://fixture').pathname,stamp='2026-09-20T12:00:00Z';let body;
   if(p.includes('/incremental/'))body={tickets:[{id:101,status:'open',created_at:stamp,updated_at:stamp}],after_cursor:'SYN-final',after_url:'https://synthetic-vexa.zendesk.com/api/v2/incremental/tickets/cursor.json?cursor=SYN-final',end_of_stream:true};
   else if(p.includes('/comments'))body={comments:[{id:1001,author_id:3,public:true,plain_body:'SYNTHETIC battery issue',created_at:stamp},{id:1002,author_id:4,public:false,plain_body:'SYNTHETIC internal investigation',created_at:stamp}],meta:{has_more:false,after_cursor:null},links:{next:null}};
   else if(p.includes('/users/3'))body={user:{id:3,role:'end-user'}};else if(p.includes('/users/4'))body={user:{id:4,role:'agent'}};else{res.writeHead(404);return res.end('{}');}res.end(JSON.stringify(body));
  });provider.listen(0,'127.0.0.1');await once(provider,'listening');const port=provider.address().port,preload=path.join(h.tmp,'synthetic-provider-preload.mjs');
  // Test-only provider boundary: actual adapter HTTP is routed to our labeled local fixture.
  fs.writeFileSync(preload,`const original=globalThis.fetch;globalThis.fetch=(input,init)=>{const u=new URL(typeof input==='string'?input:input.url??String(input));if(u.origin==='https://synthetic-vexa.zendesk.com'){if(new Headers(init?.headers).get('authorization')!=='Bearer SYN-CRM-SECRET')throw Error('SYNTHETIC_SECRET_REQUIRED');return original('http://127.0.0.1:${port}'+u.pathname+u.search,init).then(r=>new Response(r.body,{status:r.status,statusText:r.statusText,headers:r.headers}));}if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('EXTERNAL_NETWORK_NOT_AUTHORIZED');return original(input,init);};`);
  const env={NODE_OPTIONS:'--import '+preload,VEXA_CRM_CREDENTIALS_JSON:JSON.stringify([{tenantId:h.A.tenant,source:'zendesk',accountId:'SYN-CRM-RUNTIME',ref:'syn-crm',token:'SYN-CRM-SECRET',subdomain:'synthetic-vexa'}])};await h.stopWeb();await h.startWeb(false,env);
  let connectionId;
  const tick=async()=>{for(let i=0;i<4;i++){const r=await fetch(h.base+'/api/internal/crm',{method:'POST',headers:{authorization:'Bearer '+h.triggerSecret},signal:AbortSignal.timeout(30000)}),value=await r.json();assert.equal(r.status,200,'REAL_HOSTED_TICK:'+JSON.stringify(value));if(value.data?.state!=='idle'&&value.code!=='IDLE')return value.data;}return {state:'idle'};};
  const due=()=>h.sql(`UPDATE crm_sync_settings SET next_attempt_at=now()-interval '1 second' WHERE connection_id=${q(connectionId)}`);
  await t.test('owner configures from browser and one hosted tick imports full message bodies',async()=>{const browser=await h.browser(),ctx=await browser.newContext();ctx.setDefaultTimeout(15000);try{await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const n=v.indexOf('=');return{name:v.slice(0,n),value:v.slice(n+1),url:h.base};}));const p=await ctx.newPage();await p.goto(h.base+'/connections');await p.getByLabel('Identificador de la cuenta').fill('SYN-CRM-RUNTIME');await p.getByLabel('Nombre de la credencial configurada').fill('syn-crm');await p.getByLabel('Inicio del histórico (UTC)').fill('2026-01-01T00:00');const result=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/connections/settings'&&r.request().method()==='POST');await p.getByRole('button',{name:'Guardar conexión',exact:true}).click();const response=await result;assert.equal(response.status(),201,'BROWSER_CONFIG_SAVED');connectionId=(await response.json()).data.connectionId;assert.match(connectionId,/^[a-f0-9-]{36}$/);assert.equal(h.sql(`SELECT count(*) FROM crm_sync_settings WHERE connection_id=${q(connectionId)}`),'1');const completed=await tick();assert.equal(completed.state,'done','HOSTED_IMPORT_TERMINAL');assert.equal(h.sql(`SELECT count(*) FROM messages WHERE connection_id=${q(connectionId)}`),'2','REAL_PROVIDER_BODIES_PERSISTED');assert.equal(h.sql(`SELECT count(*) FROM sync_raw_objects WHERE connection_id=${q(connectionId)}`),'3');assert.ok(requests.length>=3&&requests.every(r=>r.method==='GET'),'READ_ONLY_PROVIDER');const refresh=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/connections');await p.getByRole('button',{name:'Actualizar conexiones'}).click();assert.equal((await refresh).status(),200);await p.getByText(/Última sincronización completada/).waitFor();await p.screenshot({path:path.join(evidence,'crm-runtime-healthy.png'),fullPage:true});}finally{await ctx.close();}});
  await t.test('401 blocks future fetch and owner reconnection schedules an actual retry',async()=>{mode='revoked';due();assert.equal((await tick()).state,'blocked');const previous=requests.length;assert.equal((await tick()).state,'idle');assert.equal(requests.length,previous,'REVOKED_NO_REPEATED_PROVIDER_CALL');const health=(await h.request(h.A,'/api/connections')).data.connections.find(r=>r.id===connectionId);assert.equal(health.state,'reconnect_required');mode='ok';const browser=await h.browser(),ctx=await browser.newContext();ctx.setDefaultTimeout(15000);try{await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const n=v.indexOf('=');return{name:v.slice(0,n),value:v.slice(n+1),url:h.base};}));const p=await ctx.newPage();await p.goto(h.base+'/connections');await p.getByLabel('Confirmo la rotación de credenciales de esta cuenta').check();const updated=p.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/recheck'));await p.getByRole('button',{name:'Permitir nuevo intento'}).click();assert.equal((await updated).status(),202);assert.equal((await tick()).state,'done','RECHECK_REACHES_PROVIDER');assert.equal(h.sql(`SELECT count(*) FROM messages WHERE connection_id=${q(connectionId)}`),'2','RETRY_DEDUP');}finally{await ctx.close();}});
  await t.test('product scheduler calls hosted CRM without an open browser and persists another window',async()=>{
   due();const before=requests.length;
   // The durable dispatcher rotates across both authorized fixture tenants.
   for(let slot=0;slot<4&&requests.length===before;slot++){
   const child=spawn(process.execPath,[path.join(h.tmp,'packages/jobs/durable/scheduler.mjs'),'--once'],{cwd:h.tmp,env:{PATH:process.env.PATH,VEXA_WORKER_ENDPOINT:h.base+'/api/internal/crm',VEXA_WORKER_TRIGGER_SECRET:h.triggerSecret},stdio:['ignore','pipe','pipe']});
   const timer=setTimeout(()=>child.kill('SIGKILL'),60000);let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
   let exit;try{exit=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});}finally{clearTimeout(timer);if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');}
   assert.equal(exit,0,'SCHEDULER_EXIT:'+output);assert.match(output,/worker_http_status=200/);
   }
   assert.ok(requests.length>before,'SCHEDULER_REACHED_PROVIDER');
   assert.equal(h.sql(`SELECT count(*) FROM messages WHERE connection_id=${q(connectionId)}`),'2','SCHEDULER_CANONICAL_DEDUP');
   assert.equal(h.sql(`SELECT state FROM connection_health WHERE connection_id=${q(connectionId)}`),'healthy');
  });
  await t.test('original owner revocation, disabled delegation and trigger authentication stop network',async()=>{due();const before=requests.length;h.sql(`UPDATE worker_delegations SET enabled=false WHERE user_id=${q(h.bot.id)}`);assert.equal((await tick()).state,'idle');h.sql(`UPDATE worker_delegations SET enabled=true WHERE user_id=${q(h.bot.id)};UPDATE memberships SET status='revoked' WHERE user_id=${q(h.A.id)}`);assert.equal((await tick()).state,'idle');assert.equal(requests.length,before,'REVOKED_ACTOR_NO_PROVIDER');h.sql(`UPDATE memberships SET status='active' WHERE user_id=${q(h.A.id)}`);assert.equal((await fetch(h.base+'/api/internal/crm',{method:'POST'})).status,401);assert.equal((await fetch(h.base+'/api/internal/crm',{method:'POST',headers:{authorization:'Bearer '+h.triggerSecret},body:JSON.stringify({tenantId:h.B.tenant})})).status,400);assert.equal(requests.length,before);});
  await t.test('settings cannot be configured by viewer, foreign tenant or missing CSRF',async()=>{const row=(await h.request(h.A,'/api/connections/settings')).data.settings.find(r=>r.connectionId===connectionId),body={connectionId,source:row.source,accountId:row.accountId,credentialRef:row.credentialRef,historyFrom:row.historyFrom,enabled:true,overlapSeconds:60,pollSeconds:300,expectedVersion:row.version};assert.equal((await h.request(h.B,'/api/connections/settings',body)).status,409);assert.equal((await h.request({...h.bot,tenant:h.A.tenant},'/api/connections/settings',body)).status,403);assert.equal((await fetch(h.base+'/api/connections/settings',{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify(body)})).status,403);});
  h.verifySources();fs.writeFileSync(path.join(evidence,'provider-requests.json'),JSON.stringify(requests),{mode:0o600});
 }finally{if(h)await h.close();if(provider){provider.closeAllConnections();await new Promise(r=>provider.close(r));}console.log('F03_RUNTIME_EVIDENCE:'+evidence);}
});
