'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ExplorerPage,ExplorerEvidence,ExplorerQuestion} from '../../../../../packages/recommendations/explorer.mjs';
import type {Scope,Metric} from '../../lib/workspace/contracts';
import {formatMinorUnits} from '../../../../../packages/metrics/money.mjs';
const money=(metric:Metric)=>metric.amount_minor===null?'Desconocido':formatMinorUnits(metric.amount_minor,metric.currency,metric.exponent);
import {SharedFilters} from '../workspace/shared-filters';
import {DataState} from '../workspace/data-state';
type Filters=Scope & {basis:string;exponent?:number};
const searchKeys=['q','status','order','limit','cursor'];
function clean(value:string){const q=new URLSearchParams(value);for(const k of ['resource','format','problem_id','detail_hash','root_kind','root_id','component_id','event_id'])q.delete(k);return q;}
function scopeOnly(value:string){const q=clean(value);for(const k of searchKeys)q.delete(k);return q;}
function defaults(value:string):Filters{const q=clean(value),now=new Date();return {date_start:q.get('date_start')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),date_end:q.get('date_end')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString(),timezone:'UTC',date_basis:q.get('date_basis')??'occurred_at',currency:q.get('currency')??'USD',basis:q.get('basis')??'net',sku:q.getAll('sku'),source:q.getAll('source'),snapshot_id:q.get('snapshot_id'),...(q.has('exponent')?{exponent:Number(q.get('exponent'))}:{})};}
function pin(scope:Scope,snapshot:string,hash:string){const q=new URLSearchParams({date_start:scope.date_start.slice(0,10),date_end:scope.date_end.slice(0,10),timezone:scope.timezone,date_basis:scope.date_basis,currency:scope.currency,basis:scope.basis??'net',snapshot_id:snapshot,scope_hash:hash});if(scope.exponent!==null&&scope.exponent!==undefined)q.set('exponent',String(scope.exponent));for(const s of scope.sku)q.append('sku',s);for(const s of scope.source)q.append('source',s);return q;}
function errorMessage(status:number){return status===401||status===403?'Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.':status===404?'La publicación o su evidencia ya no están disponibles con tus permisos.':status===409?'El alcance o la autorización cambió. Reinicia la búsqueda para obtener una página vigente.':status===400?'Revisa la búsqueda, los filtros y el alcance solicitado.':'No se pudo verificar la consulta. Reintenta sin cambiar tu búsqueda.';}
export function ExplorerPanel({initialQuery}:{initialQuery:string}){
 const [query,setQuery]=useState(clean(initialQuery).toString()),[scope,setScope]=useState<Filters>(()=>defaults(initialQuery)),[page,setPage]=useState<ExplorerPage|null>(null),[evidence,setEvidence]=useState<ExplorerEvidence|null>(null),[answer,setAnswer]=useState<ExplorerQuestion|null>(null),[question,setQuestion]=useState(''),[busy,setBusy]=useState(true),[empty,setEmpty]=useState(false),[error,setError]=useState('');
 const generation=useRef(0),controller=useRef<AbortController|null>(null),current=useRef(query),pending=useRef(false);
 const invalidate=useCallback(()=>{controller.current?.abort();generation.current++;pending.current=false;},[]);
 const clearProtected=()=>{setPage(null);setEvidence(null);setAnswer(null);};
 const load=useCallback(async(input:string)=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;pending.current=true;setBusy(true);setError('');setPage(null);setEvidence(null);setAnswer(null);setEmpty(false);
  try{let requested=clean(input);if(!requested.get('snapshot_id')||!requested.get('scope_hash')){const only=scopeOnly(input);only.set('resource','problems');const response=await fetch('/api/workspace?'+only,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(errorMessage(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const meta=json.data?.meta;if(!meta?.scope)throw Error('No se pudo verificar el alcance publicado.');setScope({...meta.scope,exponent:meta.scope.exponent??undefined});if(!meta.snapshot_id||!meta.scope_hash){setEmpty(true);return;}const fixed=pin(meta.scope,meta.snapshot_id,meta.scope_hash);for(const k of searchKeys)if(requested.has(k))fixed.set(k,requested.get(k)!);requested=fixed;}
   const response=await fetch('/api/explorer?'+requested,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok)throw Error(errorMessage(response.status));const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;const data=json.data as ExplorerPage;if(!data?.meta||!Array.isArray(data.items)||data.meta.snapshotId!==requested.get('snapshot_id')||data.meta.scopeHash!==requested.get('scope_hash'))throw Error('La página recibida no corresponde al alcance solicitado.');setScope({...data.meta.scope,exponent:data.meta.scope.exponent??undefined});current.current=requested.toString();window.history.replaceState(null,'',window.location.pathname+'?'+requested);setPage(data);
  }catch(e){if(!abort.signal.aborted&&epoch===generation.current){setPage(null);setEvidence(null);setAnswer(null);setError(e instanceof Error?e.message:errorMessage(503));}}
  finally{if(!abort.signal.aborted&&epoch===generation.current){pending.current=false;setBusy(false);}}
 },[]);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)void load(query);});return()=>{active=false;invalidate();};},[query,load,invalidate]);
 useEffect(()=>{const back=()=>{invalidate();const next=clean(window.location.search.slice(1)).toString();current.current=next;if(next===query)void load(next);else setQuery(next);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[query,load,invalidate]);
 const navigate=(q:URLSearchParams)=>{invalidate();clearProtected();setBusy(true);const next=q.toString();current.current=next;window.history.pushState(null,'',window.location.pathname+'?'+next);if(next===query)void load(next);else setQuery(next);};
 const apply=(next:URLSearchParams)=>{const old=clean(current.current);const changed=['date_start','date_end','currency','basis','exponent'].some(k=>(old.get(k)??'')!==(next.get(k)??''));if(changed&&next.get('snapshot_id')===scope.snapshot_id)next.delete('snapshot_id');next.delete('scope_hash');for(const k of searchKeys.filter(k=>k!=='cursor'))if(old.has(k))next.set(k,old.get(k)!);navigate(next);};
 const consult=async(kind:'evidence'|'question',id?:string)=>{if(pending.current||!page)return;pending.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;setBusy(true);setError('');setAnswer(null);setEvidence(null);const fixed=scopeOnly(current.current).toString();
  try{const response=await fetch(kind==='evidence'?'/api/explorer/tools':'/api/explorer/query',{method:'POST',cache:'no-store',signal:abort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(kind==='evidence'?{name:'get_evidence',args:{query:fixed,problemId:id}}:{question,query:fixed})});if(abort.signal.aborted||epoch!==generation.current)return;if(!response.ok){if([401,403,404,409].includes(response.status))clearProtected();throw Error(errorMessage(response.status));}const json=await response.json();if(abort.signal.aborted||epoch!==generation.current)return;if(kind==='evidence'){const result=json.data?.result as ExplorerEvidence;if(!result||result.problemId!==id||result.snapshotId!==page.meta.snapshotId||result.scopeHash!==page.meta.scopeHash||!Array.isArray(result.citations))throw Error('No se pudo verificar la evidencia de este problema.');setEvidence(result);}else{const result=json.data as ExplorerQuestion;if(!result||!result.status||(result.snapshotId!==null&&result.snapshotId!==page.meta.snapshotId)||(result.scopeHash!==null&&result.scopeHash!==page.meta.scopeHash))throw Error('No se pudo verificar el alcance de la respuesta.');setAnswer(result);}}
  catch(e){if(!abort.signal.aborted&&epoch===generation.current)setError(e instanceof Error?e.message:errorMessage(503));}
  finally{if(!abort.signal.aborted&&epoch===generation.current){pending.current=false;setBusy(false);}}
 };
 const restart=()=>{const q=clean(current.current);q.delete('cursor');navigate(q);};
 return <section aria-label="Explorador de evidencia"><p className="eyebrow">Consulta y trazabilidad</p><h1>Explorador de evidencia</h1><p>Busca problemas y revisa sus citas dentro de una publicación. Las consultas son de solo lectura y no ejecutan acciones externas.</p>
  <SharedFilters key={JSON.stringify(scope)} scope={scope} onApply={apply}/>
  <form key={query} className="action-form" aria-label="Buscar problemas" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),q=scopeOnly(current.current);for(const key of ['q','status','order','limit']){const value=String(form.get(key)??'');if(value)q.set(key,value);}navigate(q);}}>
   <label>Buscar en problemas y evidencia<input name="q" type="search" maxLength={200} defaultValue={clean(query).get('q')??''}/></label>
   <label>Estado de cobertura<select name="status" defaultValue={clean(query).get('status')??'all'}><option value="all">Todos</option><option value="ready">Completa</option><option value="partial">Parcial</option><option value="stale">Corte anterior</option></select></label>
   <label>Orden de resultados<select name="order" defaultValue={clean(query).get('order')??'title_asc'}><option value="title_asc">Título e identificador</option><option value="id_asc">Identificador</option></select></label>
   <label>Resultados por página<select name="limit" defaultValue={clean(query).get('limit')??'25'}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></label><button disabled={busy}>Buscar</button>
  </form><button disabled={busy} onClick={()=>void load(current.current)}>Actualizar consulta</button><button disabled={busy} onClick={restart}>Reiniciar paginación</button>
  {busy&&<p role="status">Verificando consulta…</p>}{error&&<p role="alert">{error}</p>}{empty&&<><DataState state={{kind:'empty'}}/><p>No hay una publicación para este alcance. <Link href="/economics">Revisar publicaciones</Link></p></>}
  {page&&<><p className="snapshot">Publicación: {page.meta.snapshotId} · Alcance: {page.meta.scopeHash}</p><p role="status">{page.meta.totalMatched} resultados · {page.items.length} en esta página</p><p>Cobertura: {page.meta.coverage}</p>{page.meta.watermark&&<p>Actualización de los datos: {page.meta.watermark}</p>}
   <form className="action-form" aria-label="Consulta ejecutiva" onSubmit={e=>{e.preventDefault();void consult('question');}}><label htmlFor="explorer-question">Pregunta sobre este alcance</label><textarea id="explorer-question" value={question} onChange={e=>setQuestion(e.target.value)} required maxLength={2000} placeholder="¿Qué reembolsos constan en este corte?"/><button disabled={busy||!question.trim()}>Consultar datos</button><small>Consulta determinística: muestra datos verificables del alcance seleccionado. Una comparación o una explicación causal necesita evidencia adicional.</small></form>
   {answer&&<section aria-label="Respuesta de la consulta"><h2>{answer.status==='answered'?'Datos del corte consultado':answer.status==='clarification_required'?'Precisa tu pregunta':answer.status==='abstained'?'La evidencia no permite esa conclusión':'Consulta fuera del alcance disponible'}</h2><p>{answer.message}</p>{answer.answer&&<p>{answer.answer}</p>}{answer.missing.length>0&&<p>Falta precisar: {answer.missing.map(x=>({basis:'base de los importes',currency:'moneda',period:'periodo',published_scope:'publicación y alcance',measure:'medida financiera'}[x])).join(', ')}.</p>}{answer.coverage&&<p>Cobertura: {answer.coverage}</p>}<dl className="metric-grid">{answer.metrics.map((metric,i)=><div key={i}><dt>{metric.label}</dt><dd>{money(metric)}</dd>{metric.amount_minor===null&&metric.known_subtotal!==null&&<small>Subtotal conocido: {money({...metric,amount_minor:metric.known_subtotal})}; no es el total.</small>}</div>)}</dl>{answer.references.length>0&&<><h3>Referencias de los datos</h3><ul>{answer.references.map((reference,i)=><li key={reference.sourceRef+':'+i}>{reference.href.startsWith('/')&&!reference.href.startsWith('//')?<a href={reference.href}>{reference.label}</a>:reference.label} · {reference.sourceRef}</li>)}</ul></>}</section>}
   {!page.items.length&&<p>No hay problemas que coincidan con esta búsqueda dentro del alcance autorizado.</p>}
   <div className="record-grid">{page.items.map(item=><article key={item.id} className="record-card" aria-label={'Problema: '+item.title}><h2><Link href={'/problems/'+item.id+'?'+pin(page.meta.scope,page.meta.snapshotId,page.meta.scopeHash)}>{item.title}</Link></h2><p>{item.summary}</p><p>Versión {item.version} · {item.status==='ready'?'Cobertura completa':item.status==='partial'?'Cobertura parcial':'Corte anterior'}</p><dl className="metric-grid">{item.metrics.map((metric,i)=><div key={i}><dt>{metric.label}</dt><dd>{money(metric)}</dd>{metric.amount_minor===null&&metric.known_subtotal!==null&&<small>Subtotal conocido: {money({...metric,amount_minor:metric.known_subtotal})}; no es el total.</small>}</div>)}</dl><p>{item.evidenceCount} citas verificables</p><button disabled={busy} onClick={()=>void consult('evidence',item.id)}>Ver evidencia de {item.title}</button></article>)}</div>
   {page.meta.nextCursor&&<button disabled={busy} onClick={()=>{const q=clean(current.current);q.set('cursor',page.meta.nextCursor!);navigate(q);}}>Página siguiente</button>}
   {evidence&&<section aria-label="Evidencia consultada"><h2>Evidencia de {evidence.title}</h2><p>{evidence.coverage} · Versión {evidence.problemVersion}</p>{evidence.citations.map((citation,i)=><figure key={citation.runId+':'+citation.messageRevisionId+':'+i}><blockquote>{citation.quote}</blockquote><figcaption>{citation.role} · {citation.source} · {citation.category} · Revisión {citation.messageRevisionId}</figcaption></figure>)}{!evidence.citations.length&&<p>No hay citas disponibles con el acceso vigente.</p>}</section>}
  </>}
 </section>;
}
