// SQL-only SYN Storage/Auth fixture for PostgreSQL tests; no HTTP service claim.
// Auth session/user columns match the SQL fixture used by the reviewed local recovery harness.
// Operation helpers copied byte-for-byte from official Storage v1.69.11 image
// sha256:97ed68d33417d253a45fe0a70f84324d92250a3e239bf18aa6cf87269dbf6727,
// migrations0024/0058, also calibrated in support/F07-recovery/storage-bootstrap.test.mjs.
const fixtureSQL = "create schema if not exists storage;\ncreate table if not exists storage.buckets(id text primary key,name text,public boolean);\ncreate table if not exists storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text,metadata jsonb);\nalter table storage.objects enable row level security;\ngrant usage on schema storage to authenticated;\ngrant select,insert,delete on storage.objects to authenticated;";
const operationSQL = [
  "CREATE OR REPLACE FUNCTION storage.operation()\n    RETURNS text AS $$\nBEGIN\n    RETURN current_setting('storage.operation', true);\nEND;\n$$ LANGUAGE plpgsql STABLE;",
  "-- Ergonomic helpers for operation-aware RLS policies.\n-- These helpers read the existing transaction-local storage.operation GUC (Grand Unified Configuration).\n\nCREATE OR REPLACE FUNCTION storage.allow_only_operation(expected_operation text)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nAS $$\n  WITH current_operation AS (\n    SELECT storage.operation() AS raw_operation\n  ),\n  normalized AS (\n    SELECT\n      CASE\n        WHEN raw_operation LIKE 'storage.%' THEN substr(raw_operation, 9)\n        ELSE raw_operation\n      END AS current_operation,\n      CASE\n        WHEN expected_operation LIKE 'storage.%' THEN substr(expected_operation, 9)\n        ELSE expected_operation\n      END AS requested_operation\n    FROM current_operation\n  )\n  SELECT CASE\n    WHEN requested_operation IS NULL OR requested_operation = '' THEN FALSE\n    ELSE COALESCE(current_operation = requested_operation, FALSE)\n  END\n  FROM normalized;\n$$;\n\nCREATE OR REPLACE FUNCTION storage.allow_any_operation(expected_operations text[])\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nAS $$\n  WITH current_operation AS (\n    SELECT storage.operation() AS raw_operation\n  ),\n  normalized AS (\n    SELECT CASE\n      WHEN raw_operation LIKE 'storage.%' THEN substr(raw_operation, 9)\n      ELSE raw_operation\n    END AS current_operation\n    FROM current_operation\n  )\n  SELECT EXISTS (\n    SELECT 1\n    FROM normalized n\n    CROSS JOIN LATERAL unnest(expected_operations) AS expected_operation\n    WHERE expected_operation IS NOT NULL\n      AND expected_operation <> ''\n      AND n.current_operation = CASE\n        WHEN expected_operation LIKE 'storage.%' THEN substr(expected_operation, 9)\n        ELSE expected_operation\n      END\n  );\n$$;\n"
];
export function bootstrapStorageFixture(sql){sql(fixtureSQL);sql("CREATE TABLE IF NOT EXISTS auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email_confirmed_at timestamptz;ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS deleted_at timestamptz;ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS banned_until timestamptz;");for(const statement of operationSQL)sql(statement);}
