import {createWorkspaceService} from '../workspace-service/index.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
import {WorkspaceError,check,uuid} from '../workspace-service/contracts.mjs';
import {EconomicError} from '../metrics/repository.mjs';
import {formatMinorUnits} from '../metrics/money.mjs';
import {parseExplorerQuery,normalizeSearch,explorerCursorBinding,encodeExplorerCursor,decodeExplorerCursor,validateToolCall,clarifyQuestion} from './explorer-contracts.mjs';
const one=async(s,q,a=[])=>(await s.query(q,a)).rows[0],compare=(a,b)=>a<b?-1:a>b?1:0,AI=Object.freeze({available:false,reason:'deterministic_mode'});
// Reuses the laboratory's structured read-only port boundary. The accepted canonical
// workspace/evidence repositories replace its obsolete snapshot SQL and broad commands.
export function createExplorerRepository({database}){
 const readonly=Object.freeze({async transaction(action,fn){check(action==='read','explorer_read_only',403);let own;try{return await database.transaction('read',async s=>{try{return await fn(s);}catch(e){if(e instanceof WorkspaceError||e instanceof EconomicError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}}});
 const workspace=createWorkspaceService({database:readonly});
 async function bundle(parsed,resource='problems'){const q=new URLSearchParams(parsed.sharedQuery);q.set('resource',resource);const result=await workspace.query(q,{all:true});check(result.meta.snapshot_id&&result.meta.scope_hash,'snapshot_not_found',404);return result;}
 async function citations(view){return readonly.transaction('read',async s=>{const bound=await one(s,'SELECT problem_versions FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,view.meta.scope_hash]);check(bound,'scope_not_found',404);const base=await one(s,'SELECT input_manifest FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,view.meta.snapshot_id]);check(base,'snapshot_not_found',404);const capturedRuns=new Set(base.input_manifest.models.map(r=>r.id)),cache=new Map(),byProblem=new Map(),evidence=createEvidenceRepository({database:{transaction:async(action,fn)=>{check(action==='read','explorer_read_only',403);return fn(s);}}});
 for(const item of view.items){const pinned=bound.problem_versions.find(p=>p.problemId===item.id);check(pinned,'historical_problem_unavailable',403);const p=await one(s,'SELECT provenance FROM public.problem_versions WHERE tenant_id=$1 AND id=$2 AND problem_id=$3',[s.tenantId,pinned.versionId,item.id]);check(p,'historical_problem_unavailable',403);const ids=p.provenance.snapshot.embeddingIds;check(Array.isArray(ids)&&ids.length,'historical_evidence_unavailable',403);const links=(await s.query('SELECT embedding_id,extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1 AND embedding_id=ANY($2::uuid[])',[s.tenantId,ids])).rows;check(links.length===new Set(ids).size&&links.every(r=>capturedRuns.has(r.extraction_run_id)),'historical_evidence_unavailable',403);const refs=[];for(const runId of [...new Set(links.map(r=>r.extraction_run_id))]){if(!cache.has(runId)){let run;try{run=await evidence.get(runId);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')throw new WorkspaceError('evidence_unavailable',403);throw e;}const conversation=await one(s,'SELECT source FROM public.conversations WHERE tenant_id=$1 AND id=$2',[s.tenantId,run.conversationId]);check(conversation,'evidence_unavailable',403);cache.set(runId,run.issues.flatMap(issue=>issue.evidence.map(span=>({runId,conversationId:run.conversationId,messageRevisionId:span.message_revision_id,quote:span.quote,quoteHash:span.quote_hash,role:span.role,category:issue.category,severity:issue.severity??'unknown',source:conversation.source}))));}refs.push(...cache.get(runId));}
 byProblem.set(item.id,[...new Map(refs.map(r=>[r.runId+':'+r.messageRevisionId+':'+r.quoteHash+':'+r.category,r])).values()].sort((a,b)=>compare(a.runId,b.runId)||compare(a.messageRevisionId,b.messageRevisionId)||compare(a.quoteHash,b.quoteHash)));}
 return byProblem;});}
 const api={
 async search({query}){const parsed=parseExplorerQuery(query),view=await bundle(parsed),refs=await citations(view);let items=view.items.map(row=>({id:row.id,title:row.title,version:row.version,status:row.status,summary:row.summary,metrics:row.metrics,evidenceCount:refs.get(row.id).length,citations:refs.get(row.id)}));const needle=normalizeSearch(parsed.search);items=items.filter(row=>(parsed.status==='all'||row.status===parsed.status)&&(!needle||normalizeSearch([row.title,row.summary,...row.citations.flatMap(r=>[r.quote,r.category])].join(' ')).includes(needle)));
 const sortKey=row=>parsed.order==='id_asc'?'':normalizeSearch(row.title);items.sort((a,b)=>compare(sortKey(a),sortKey(b))||compare(a.id,b.id));const totalMatched=items.length,binding=explorerCursorBinding({authHash:view.meta.cursor_auth_hash,snapshotId:view.meta.snapshot_id,scopeHash:view.meta.scope_hash,search:parsed.search,status:parsed.status,order:parsed.order,limit:parsed.limit}),after=decodeExplorerCursor(parsed.cursor,{binding});if(after){check(items.some(r=>r.id===after.id&&sortKey(r)===after.sort),'cursor_position_invalid',409);items=items.filter(r=>compare(sortKey(r),after.sort)>0||sortKey(r)===after.sort&&compare(r.id,after.id)>0);}const more=items.length>parsed.limit;items=items.slice(0,parsed.limit);const last=items.at(-1);return {items,meta:{snapshotId:view.meta.snapshot_id,scopeHash:view.meta.scope_hash,baseScopeHash:view.meta.base_scope_hash,scope:view.meta.scope,state:!totalMatched?'empty':view.meta.state,coverage:view.meta.coverage,watermark:view.meta.watermark,nextCursor:more?encodeExplorerCursor({binding,after:{sort:sortKey(last),id:last.id}}):null,totalMatched,query:parsed.search,statusFilter:parsed.status,order:parsed.order,limit:parsed.limit,ai:AI}};},
 async evidence({query,problemId}){check(uuid(problemId),'problem_not_found',404);const parsed=parseExplorerQuery(query);check(parsed.search===''&&parsed.status==='all'&&parsed.order==='title_asc'&&parsed.cursor===null,'tool_filters_invalid');const view=await bundle(parsed),item=view.items.find(r=>r.id===problemId);check(item,'problem_not_found',404);const refs=await citations({...view,items:[item]});return {problemId,problemVersion:item.version,title:item.title,snapshotId:view.meta.snapshot_id,scopeHash:view.meta.scope_hash,coverage:view.meta.coverage,citations:refs.get(problemId)};},
 async tools(input){const call=validateToolCall(input),query=new URLSearchParams(call.args.query);let result;if(call.name==='search_problems')result=await api.search({query});else if(call.name==='get_evidence')result=await api.evidence({query,problemId:call.args.problemId});else result=await bundle(parseExplorerQuery(query),'metrics');return {name:call.name,result};},
 async ask(input){await readonly.transaction('read',async()=>null);const question=clarifyQuestion(input);const common={mode:'deterministic',question:question.question,answer:null,missing:question.missing,snapshotId:null,scopeHash:null,scope:null,coverage:null,metrics:[],references:[],ai:AI};if(question.missing.length)return {...common,status:'clarification_required',message:'Indica base, moneda y período; selecciona un snapshot y alcance publicados. Para «pérdida», distingue reembolsos liquidados, órdenes registradas o ingresos expuestos: no son equivalentes.'};const parsed=parseExplorerQuery(new URLSearchParams(question.query)),view=await bundle(parsed,'metrics');const pinned={...common,snapshotId:view.meta.snapshot_id,scopeHash:view.meta.scope_hash,scope:view.meta.scope,coverage:view.meta.coverage};if(!question.metrics.length)return {...pinned,status:'unsupported',message:'Consulta determinística disponible para reembolsos, órdenes registradas e ingresos expuestos. Esta vista no ejecuta un modelo de IA ni interpreta otras instrucciones.'};const metrics=view.items[0].metrics.filter(m=>question.metrics.includes(m.kind));const referenceQuery=new URLSearchParams(parsed.sharedQuery);const references=metrics.map(m=>({kind:'snapshot_metric',metric:m.kind,sourceRef:m.source_ref,snapshotId:view.meta.snapshot_id,scopeHash:view.meta.scope_hash,href:'/overview?'+referenceQuery.toString(),label:'Evidencia financiera del mismo snapshot y alcance: '+m.label}));const facts=metrics.map(m=>m.amount_minor===null?`${m.label}: total desconocido.${m.known_subtotal===null?'':` Subtotal conocido ${formatMinorUnits(m.known_subtotal,m.currency,m.exponent)}; no equivale al total.`}`:`${m.label}: ${formatMinorUnits(m.amount_minor,m.currency,m.exponent)}.`).join(' ');const caveat=' Las filas por problema no se suman y la exposición no es pérdida ni ahorro.';if(question.causal)return {...pinned,status:'abstained',metrics,references,answer:'No se puede demostrar una variación o una causa con este único corte. '+facts+caveat,message:'Para establecer aumento o disminución falta un período comparable con la misma base, moneda y cobertura. Para explicar una causa falta evidencia operacional independiente; las citas conversacionales por sí solas no la confirman.'};return {...pinned,status:'answered',metrics,references,answer:facts+caveat,message:'Resultado determinístico del snapshot y alcance indicados, con autorización vigente; sin inferencia ni ejecución externa.'};}
 };
 return Object.freeze(api);
}
