import {randomUUID} from 'node:crypto';
import {createWorkspaceService} from '../workspace-service/index.mjs';
import {createDetailService} from '../workspace-service/detail.mjs';
import {WorkspaceError,check,uuid,hash} from '../workspace-service/contracts.mjs';
import {DomainError} from '../problems/contracts.mjs';
import {EconomicError} from '../metrics/repository.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
import {proposeRecommendation,GENERATOR_VERSION} from './generate.mjs';
const one=async(s,q,a=[])=>(await s.query(q,a)).rows[0],iso=x=>new Date(x).toISOString();
const strict=(q,keys)=>check(q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>keys.includes(k)),'input_invalid');
const text=(x,min,max)=>typeof x==='string'&&x.trim()===x&&x.length>=min&&x.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(x);
const key=k=>check(text(k,1,128),'request_key_invalid');const version=v=>check(Number.isInteger(v)&&v>0,'version_invalid');
const scoped=s=>({transaction:async(_a,fn)=>fn(s)});
const draftView=r=>({id:r.id,status:r.status,version:r.version,recommendationId:r.recommendation_id,recommendationVersion:r.recommendation_version,snapshotId:r.baseline_ref,scopeHash:r.provenance.scopeHash,ownerId:r.owner_id,hypothesis:r.hypothesis,createdAt:iso(r.created_at),executionEnabled:false});
function cleanQuery(value){check(typeof value==='string'&&value.length<=8192,'scope_query_invalid');const q=new URLSearchParams(value);for(const k of ['resource','limit','cursor','format','detail_hash'])check(!q.has(k),'unsupported_filter');check(q.get('snapshot_id')&&q.get('scope_hash'),'scope_required');q.sort();return q;}
export function createRecommendationRepository({database}){
 const tx=async(action,fn)=>{let own;try{return await database.transaction(action,async s=>{try{return await fn(s);}catch(e){if(e instanceof WorkspaceError||e instanceof DomainError||e instanceof EconomicError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}};
 async function captured(query,problemId,detailHash=null){const q=cleanQuery(query);if(detailHash)q.set('detail_hash',detailHash);const detail=await createDetailService({database}).get({kind:'problem',id:problemId,query:q});return tx('read',async s=>{const binding=await one(s,'SELECT * FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,detail.scope_hash]);const pinned=binding.problem_versions.find(v=>v.problemId===problemId);check(pinned,'problem_not_found',404);const p=await one(s,'SELECT * FROM public.problem_versions WHERE tenant_id=$1 AND id=$2',[s.tenantId,pinned.versionId]);const latest=await one(s,'SELECT id,version,provenance FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,problemId]);check(p&&latest,'problem_not_found',404);const refs=[];const repo=createEvidenceRepository({database:scoped(s)});for(const runId of [...new Set(detail.conversations.flatMap(c=>c.evidenceRunIds))]){let run;try{run=await repo.get(runId);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')throw new WorkspaceError('evidence_unavailable',403);throw e;}for(const issue of run.issues)for(const span of issue.evidence)refs.push({runId,messageRevisionId:span.message_revision_id,quote:span.quote,quoteHash:span.quote_hash,role:span.role,category:issue.category,severity:issue.severity??'unknown'});}
 const evidenceRefs=[...new Map(refs.map(r=>[hash(r),r])).values()].sort((a,b)=>hash(a).localeCompare(hash(b)));check(evidenceRefs.length>0,'evidence_required',409);return {detail,binding,p,latest,evidenceRefs,role:s.role,userId:s.userId};});}
 async function raw(id){check(uuid(id),'recommendation_not_found',404);return tx('read',async s=>{const r=await one(s,"SELECT * FROM public.recommendations WHERE tenant_id=$1 AND id=$2 AND recommendation_schema='recommendation-v1'",[s.tenantId,id]);check(r,'recommendation_not_found',404);const history=(await s.query('SELECT * FROM public.recommendation_versions WHERE tenant_id=$1 AND recommendation_id=$2 ORDER BY version',[s.tenantId,id])).rows;for(const h of history)check((await one(s,'SELECT public.recommendation_member_active($1,$2) AS ok',[s.tenantId,h.actor_id])).ok,'recommendation_contributor_unavailable',403);if(r.owner_id)check((await one(s,'SELECT public.recommendation_member_active($1,$2) AS ok',[s.tenantId,r.owner_id])).ok,'recommendation_owner_unavailable',403);const drafts=(await s.query("SELECT * FROM public.interventions WHERE tenant_id=$1 AND recommendation_id=$2 AND provenance->>'kind'='recommendation-draft-v1' ORDER BY created_at,id",[s.tenantId,id])).rows;return {r,history,drafts,role:s.role};});}
 async function authorized(id){const data=await raw(id),r=data.r,ctx=await captured(r.provenance.query,r.problem_id,r.detail_hash);const available=new Set(ctx.evidenceRefs.map(hash));check(r.evidence_refs.every(e=>available.has(hash(e))),'recommendation_evidence_unavailable',403);const causalIds=r.provenance.causalEvidenceIds??[];check(causalIds.every(id=>ctx.detail.causality.view?.evidence.some(e=>e.id===id&&e.status==='active')),'operational_evidence_unavailable',403);const stale=ctx.latest.id!==r.problem_version_id||ctx.latest.provenance.snapshot.state!=='active'||(r.provenance.causalVersion??null)!==(ctx.detail.causality.view?.claim.version??null);return {...data,ctx,stale};}
 function view({r,history,drafts,role,stale,ctx}){return {id:r.id,version:r.version,status:r.status,title:r.title,problemId:r.problem_id,problemVersion:ctx.p.version,problemVersionId:r.problem_version_id,snapshotId:r.snapshot_id,scopeHash:r.scope_hash,detailHash:r.detail_hash,scope:ctx.detail.scope,action:r.action,preconditions:r.preconditions,rationale:r.rationale,evidenceRefs:r.evidence_refs,ownerId:r.owner_id,actorId:r.actor_id,reason:r.change_reason,generatorVersion:r.generator_version,priority:r.provenance.priority,effort:r.provenance.effort,causalState:r.provenance.causalState,causalVersion:r.provenance.causalVersion,automaticExternalAction:false,causalClaim:false,stale,canMutate:role!=='viewer'&&!stale&&!r.approval_bound,history:history.map(h=>({version:h.version,status:h.definition.status,action:h.definition.action,preconditions:h.definition.preconditions,rationale:h.definition.rationale,ownerId:h.definition.owner_id,reason:h.definition.change_reason,actorId:h.actor_id,createdAt:iso(h.created_at)})),drafts:drafts.map(draftView)};}
 async function ensureMutable(id,expectedVersion){const current=await authorized(id);check(!current.stale&&!current.r.approval_bound,'recommendation_stale',409);check(current.r.version===expectedVersion,'version_conflict',409);return current;}
 return {
 async list({query}){check(query instanceof URLSearchParams,'scope_query_invalid');const q=cleanQuery(query.toString()),workspace=await createWorkspaceService({database}).query(new URLSearchParams([...q,['resource','problems']]),{all:true});const info=await tx('read',async s=>({ids:(await s.query("SELECT id FROM public.recommendations WHERE tenant_id=$1 AND snapshot_id=$2 AND scope_hash=$3 AND recommendation_schema='recommendation-v1' ORDER BY created_at DESC,id",[s.tenantId,workspace.meta.snapshot_id,workspace.meta.scope_hash])).rows,members:(await s.query('SELECT * FROM public.recommendation_members($1)',[s.tenantId])).rows,role:s.role}));const items=[];let unavailableCount=0;for(const row of info.ids){try{items.push(view(await authorized(row.id)));}catch(e){if(e instanceof WorkspaceError&&[403,404].includes(e.status))unavailableCount++;else throw e;}}return {items,problemOptions:workspace.items.map(p=>({id:p.id,label:p.title,version:p.version})),members:info.members,canPropose:info.role!=='viewer',snapshotId:workspace.meta.snapshot_id,scopeHash:workspace.meta.scope_hash,scope:workspace.meta.scope,unavailableCount};},
 async get({id}){return view(await authorized(id));},
 async generate(q){strict(q,['query','problemId','requestKey']);key(q.requestKey);check(uuid(q.problemId),'problem_not_found',404);const query=cleanQuery(q.query);const ctx=await captured(query.toString(),q.problemId);check(ctx.p.id===ctx.latest.id&&ctx.latest.provenance.snapshot.state==='active','problem_version_stale',409);const generated=proposeRecommendation({problem:{id:q.problemId,title:ctx.detail.title,version:ctx.p.version},evidenceRefs:ctx.evidenceRefs,causality:ctx.detail.causality.view});const fingerprint=hash({problemId:q.problemId,snapshotId:ctx.detail.snapshot_id,scopeHash:ctx.detail.scope_hash,generatorVersion:GENERATOR_VERSION});let id;await tx('propose',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':recommendation:'+q.requestKey]);const replay=await one(s,'SELECT id,provenance FROM public.recommendations WHERE tenant_id=$1 AND idempotency_key=$2',[s.tenantId,'recommendation:'+q.requestKey]);if(replay){check(replay.provenance.requestFingerprint===fingerprint,'idempotency_conflict',409);id=replay.id;return;}await captured(query.toString(),q.problemId,ctx.detail.detail_hash);id=randomUUID();const provenance={kind:'recommendation-v1',query:query.toString(),requestFingerprint:fingerprint,priority:generated.priority,effort:generated.effort,causalState:generated.causalState,causalVersion:generated.causalVersion,causalEvidenceIds:ctx.detail.causality.view?.claim.evidenceIds??[],automaticExternalAction:false,causalClaim:false};await s.query("INSERT INTO public.recommendations(id,tenant_id,status,version,title,rationale,problem_id,snapshot_id,idempotency_key,provenance,recommendation_schema,problem_version_id,workspace_binding_id,scope_hash,detail_hash,action,preconditions,evidence_refs,generator_version,actor_id,change_reason) VALUES($1,$2,'proposed',1,$3,$4,$5,$6,$7,$8,'recommendation-v1',$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)",[id,s.tenantId,ctx.detail.title,generated.rationale,q.problemId,ctx.detail.snapshot_id,'recommendation:'+q.requestKey,JSON.stringify(provenance),ctx.p.id,ctx.binding.id,ctx.detail.scope_hash,ctx.detail.detail_hash,generated.action,JSON.stringify(generated.preconditions),JSON.stringify(ctx.evidenceRefs),GENERATOR_VERSION,s.userId,'Propuesta condicionada generada desde evidencia autorizada y versión capturada.']);await captured(query.toString(),q.problemId,ctx.detail.detail_hash);});return view(await authorized(id));},
 async revise(q){strict(q,['id','expectedVersion','action','preconditions','rationale','ownerId','reason']);version(q.expectedVersion);check(text(q.action,20,2000)&&text(q.rationale,20,4000)&&text(q.reason,20,2000)&&Array.isArray(q.preconditions)&&q.preconditions.length>=1&&q.preconditions.length<=10&&q.preconditions.every(p=>text(p,10,500))&&(q.ownerId===null||uuid(q.ownerId)),'revision_invalid');await ensureMutable(q.id,q.expectedVersion);await tx('propose',async s=>{await s.query('SELECT id FROM public.recommendations WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[s.tenantId,q.id]);await ensureMutable(q.id,q.expectedVersion);if(q.ownerId)check((await one(s,'SELECT public.recommendation_member_active($1,$2) AS ok',[s.tenantId,q.ownerId])).ok,'owner_not_found',404);const r=await s.query('UPDATE public.recommendations SET version=version+1,action=$4,preconditions=$5,rationale=$6,owner_id=$7,change_reason=$8,actor_id=$9 WHERE tenant_id=$1 AND id=$2 AND version=$3',[s.tenantId,q.id,q.expectedVersion,q.action,JSON.stringify(q.preconditions),q.rationale,q.ownerId,q.reason,s.userId]);check(r.rowCount===1,'version_conflict',409);});return view(await authorized(q.id));},
 async setState(q){strict(q,['id','expectedVersion','status','reason']);version(q.expectedVersion);check(['proposed','dismissed'].includes(q.status)&&text(q.reason,20,2000),'state_invalid');await ensureMutable(q.id,q.expectedVersion);await tx('propose',async s=>{await s.query('SELECT id FROM public.recommendations WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[s.tenantId,q.id]);const before=await ensureMutable(q.id,q.expectedVersion);check(before.r.status!==q.status,'state_unchanged',409);const r=await s.query('UPDATE public.recommendations SET version=version+1,status=$4,change_reason=$5,actor_id=$6 WHERE tenant_id=$1 AND id=$2 AND version=$3',[s.tenantId,q.id,q.expectedVersion,q.status,q.reason,s.userId]);check(r.rowCount===1,'version_conflict',409);});return view(await authorized(q.id));},
 async createDraft(q){strict(q,['id','expectedVersion','requestKey']);check(uuid(q.id),'recommendation_not_found',404);version(q.expectedVersion);key(q.requestKey);await authorized(q.id);const fingerprint=hash({recommendationId:q.id,expectedVersion:q.expectedVersion});return tx('propose',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':intervention:'+q.requestKey]);const replay=await one(s,'SELECT * FROM public.interventions WHERE tenant_id=$1 AND idempotency_key=$2',[s.tenantId,'recommendation-draft:'+q.requestKey]);if(replay){check(replay.provenance.requestFingerprint===fingerprint,'idempotency_conflict',409);return draftView(replay);}await s.query('SELECT id FROM public.recommendations WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[s.tenantId,q.id]);const checked=await ensureMutable(q.id,q.expectedVersion);check(checked.r.status==='proposed','recommendation_dismissed',409);const r=await one(s,'SELECT * FROM public.recommendations WHERE tenant_id=$1 AND id=$2',[s.tenantId,q.id]);const provenance={kind:'recommendation-draft-v1',actorId:s.userId,requestFingerprint:fingerprint,recommendationVersion:r.version,scopeHash:r.scope_hash,definition:r,automaticExternalAction:false,causalClaim:false};const row=await one(s,"INSERT INTO public.interventions(tenant_id,status,version,owner_id,hypothesis,reason,idempotency_key,recommendation_id,recommendation_version,baseline_ref,provenance) VALUES($1,'draft',1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[s.tenantId,r.owner_id,r.action,'Borrador sin ejecución; requiere plan de medición y aprobación posteriores.','recommendation-draft:'+q.requestKey,r.id,r.version,r.snapshot_id,JSON.stringify(provenance)]);return draftView(row);});}
 };
}
