import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {q,insert} from '../matrix.mjs';import {read,write,rows,denied} from '../harness.mjs';import {backend} from '../import-uploads/oracles.mjs';
export const tables=['sync_cursors','sync_raw_objects','sync_pages'];export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
const expected={sync_cursors:[['organizations',{tenant_id:'id'}],['connections',{tenant_id:'tenant_id',connection_id:'id'}],['imports',{tenant_id:'tenant_id',import_id:'id',connection_id:'connection_id'}]],sync_raw_objects:[['organizations',{tenant_id:'id'}],['sync_cursors',{tenant_id:'tenant_id',sync_id:'id',connection_id:'connection_id',import_id:'import_id'}]],sync_pages:[['organizations',{tenant_id:'id'}],['sync_cursors',{tenant_id:'tenant_id',sync_id:'id'}]]};
export function schema(h,fks){assert.deepEqual(present(h),tables,'SYNC_ALL_TABLES');for(const table of tables){
 assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'SYNC_FORCE_RLS:'+table);
 assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','SYNC_TENANT_NONNULL');
 for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),role==='vexa_backend'&&(['SELECT','INSERT'].includes(action)||(table==='sync_cursors'&&action==='UPDATE'))?'t':'f',`SYNC_GRANT:${table}:${role}:${action}`);
 const keys=fks.filter(f=>f.table===table);assert.equal(keys.length,expected[table].length,'SYNC_FK_COUNT:'+table);for(const[parent,mapping]of expected[table])assert.ok(keys.some(f=>f.parent===parent&&f.validated&&JSON.stringify(Object.entries(f.mapping).sort())===JSON.stringify(Object.entries(mapping).sort())),'SYNC_FK_REQUIRED:'+table+':'+parent);
 }}
export function seed(h,base,actors){const f={actors};for(const side of ['a','b']){const tenant=base[side].imports.tenant_id,connection=base[side].connections.id,importId=base[side].imports.id;h.sql(`UPDATE imports SET connection_id=${q(connection)} WHERE id=${q(importId)}`);const cursor={id:randomUUID(),tenant_id:tenant,connection_id:connection,import_id:importId,scope_hash:(side==='a'?'a':'b').repeat(64),mode:'live',window_spec:{from:'2026-01-01',to:'2026-09-01',overlapSeconds:60,version:'SYN'},mapping_version:'crm-canonical-v1'};const raw={id:randomUUID(),tenant_id:tenant,sync_id:cursor.id,connection_id:connection,import_id:importId,row_ref:'SYN-'+side,raw_hash:'c'.repeat(64),original:{text:'SYNTHETIC PRIVATE RAW'},normalized:{code:'ROLE_AMBIGUOUS'},result:{status:'rejected',code:'ROLE_AMBIGUOUS'}};const page={id:randomUUID(),tenant_id:tenant,sync_id:cursor.id,version:1,previous_checkpoint:null,checkpoint:{cursor:'SYN-opaque'},done:false,coverage:{},counts:{rejected:1}};f[side]={sync_cursors:cursor,sync_raw_objects:raw,sync_pages:page,connections:base[side].connections,imports:base[side].imports,organizations:{id:tenant}};for(const table of tables)h.sql(insert(table,f[side][table]));}return f;}
export function seedStandalone(h){const a=h.actor(),b=h.actor(),actors={a,b};for(const role of ['analyst','operator','viewer'])actors[role]=h.actor(role,a.tenant);actors.outsider=h.actor();actors.dual=h.actor('owner',a.tenant);h.sql(`INSERT INTO memberships(tenant_id,user_id,role,status) VALUES(${q(b.tenant)},${q(actors.dual.id)},'owner','active')`);const base={};for(const[side,actor]of Object.entries({a,b})){const imported={id:randomUUID(),tenant_id:actor.tenant,connection_id:actor.connection,file_hash:'SYN',mapping_version:'crm-canonical-v1',state:'running',idempotency_key:randomUUID()};h.sql(insert('imports',imported));base[side]={imports:imported,connections:{id:actor.connection,tenant_id:actor.tenant}};}return seed(h,base,actors);}
const scans=(r,ids,label)=>{assert.equal(r.code,'00000',label);assert.deepEqual(r.rows.map(x=>x.id).sort(),ids.sort(),label);};
export function access(h,f,actors){const A=f.a.sync_cursors.tenant_id,B=f.b.sync_cursors.tenant_id;
 for(const table of tables){
  for(const a of [null,...Object.values(actors)])denied(h.probe(read(table),a),'SYNC_DIRECT_RAW_DENIED');denied(h.probe('SET LOCAL ROLE service_role; '+read(table)),'SYNC_SERVICE_DENIED');
  for(const key of ['a','analyst','dual'])scans(backend(h,read(table),actors[key],A,'read'),[f.a[table].id],'SYNC_READ_POSITIVE:'+table+key);
  for(const key of ['viewer','operator','outsider'])scans(backend(h,read(table),actors[key],A,'read'),[],'SYNC_ROLE_DENIED:'+key);
  for(const scope of [null,B])scans(backend(h,read(table),actors.a,scope,'read'),[],'SYNC_WRONG_SCOPE');scans(backend(h,read(table),actors.dual,A,'read'),[f.a[table].id],'SYNC_DUAL_ONLY_SELECTED');
  const fresh={...f.a[table],id:randomUUID(),...(table==='sync_cursors'?{scope_hash:'d'.repeat(64)}:table==='sync_raw_objects'?{row_ref:'fresh'}:{version:2})};
  rows(backend(h,write(insert(table,fresh)),actors.a,A),[0],'SYNC_INSERT_POSITIVE');for(const key of ['viewer','operator','outsider'])denied(backend(h,write(insert(table,fresh)),actors[key],A),'SYNC_WRITE_ROLE');
  denied(backend(h,write(insert(table,{...fresh,tenant_id:B})),actors.dual,A),'SYNC_INSERT_SCOPE');denied(backend(h,write(`DELETE FROM public.${table}`),actors.a,A),'SYNC_NO_DELETE');
  const prep=`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)} AND tenant_id=${q(A)};`;scans(backend(h,read(table),actors.a,A,'read',prep),[],'SYNC_REVOKED_READ');
  if(table!=='sync_cursors')denied(backend(h,write(`UPDATE public.${table} SET id=id`),actors.a,A),'SYNC_APPEND_ONLY');
 }
 const advance=backend(h,write(`UPDATE sync_cursors SET checkpoint='{"cursor":"changed"}' WHERE id=${q(f.a.sync_cursors.id)}`),actors.a,A);assert.equal(advance.code,'23514','SYNC_CURSOR_REQUIRES_COMMITTED_PAGE');
 rows(backend(h,write(`UPDATE sync_cursors SET lease_until=lease_until WHERE id=${q(f.a.sync_cursors.id)}`),actors.a,A),[0],'SYNC_CURSOR_WRITE_POSITIVE');
 for(const[col,value]of [['id',randomUUID()],['tenant_id',B],['connection_id',f.b.connections.id],['import_id',f.b.imports.id],['scope_hash','e'.repeat(64)],['mode','backfill'],['mapping_version','changed']]){const r=backend(h,write(`UPDATE sync_cursors SET ${col}=${q(value)} WHERE id=${q(f.a.sync_cursors.id)}`),actors.a,A);assert.equal(r.code,'23514','SYNC_IDENTITY_IMMUTABLE:'+col);}
 denied(backend(h,write(`UPDATE sync_cursors SET done=true WHERE tenant_id=${q(B)}`),actors.dual,A),'SYNC_UPDATE_FOREIGN_SCOPE');
}
export function fk(h,f,key){const row={...f.a[key.table],id:randomUUID(),...(key.table==='sync_cursors'?{scope_hash:'f'.repeat(64)}:key.table==='sync_raw_objects'?{row_ref:'fk'}:{version:99})};const probe=r=>h.probe(write(insert(key.table,r))+' SET CONSTRAINTS ALL IMMEDIATE;');rows(probe(row),[0],'SYNC_FK_POSITIVE:'+key.name);const bad={...row};if(key.parent==='organizations')bad.tenant_id=randomUUID();else for(const[col,ref]of Object.entries(key.mapping))if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];const r=probe(bad);assert.equal(r.code,'23503','SYNC_FK_CROSS:'+key.name);assert.ok(r.constraint,'SYNC_FK_CONSTRAINT');}
