import test from 'node:test';
import assert from 'node:assert/strict';
import {createImportHandler} from './imports.mjs';
const tenant='11111111-1111-4111-8111-111111111111';
function fixture(role='owner'){
 const rows=new Map(),actions=[],queries=[];let sequence=0,sideEffects=0;
 const database={async transaction(action,work){actions.push(action);return work({tenantId:tenant,userId:'22222222-2222-4222-8222-222222222222',role,async query(sql,values){queries.push({sql,values});if(sql.startsWith('INSERT INTO public.connections')){assert.equal(values[0],tenant);const key=JSON.stringify(values);if(rows.has(key))return {rows:[]};const row={id:`33333333-3333-4333-8333-${String(++sequence).padStart(12,'0')}`,source:'csv',account_id:values[1],status:'active'};rows.set(key,row);return {rows:[{id:row.id}]};}if(sql.startsWith('SELECT id,source,account_id,status'))return {rows:[rows.get(JSON.stringify(values))].filter(Boolean)};if(sql.startsWith('SELECT id,source,account_id'))return {rows:[...rows.values()]};if(sql.startsWith('SELECT i.id,i.state'))return {rows:[]};throw Error('Unexpected query');}});}};
 const unexpected=async()=>{sideEffects++;throw Error('Unexpected side effect');};
 const handler=createImportHandler({database,storage:{createUpload:unexpected,read:unexpected},confirmationSecret:'SYN'.repeat(16),admission:unexpected});
 const request=async(input,{path='/api/imports/connections',method='POST'}={})=>{const r=await handler(new Request('https://fixture.invalid'+path,{method,...(method==='POST'?{headers:{'content-type':'application/json'},body:JSON.stringify(input)}:{})}));return {status:r.status,...await r.json()};};
 return {request,rows,actions,queries,sideEffects:()=>sideEffects};
}
test('owner creates CSV, trims account and replay reuses ID without Storage or admission',async()=>{const f=fixture();const first=await f.request({account_id:' SYN historical source '});assert.equal(first.status,201);assert.deepEqual(first.data,{connection:{id:first.data.connection.id,source:'csv',account_id:'SYN historical source'},created:true});const replay=await f.request({account_id:'SYN historical source'});assert.equal(replay.status,200);assert.equal(replay.data.connection.id,first.data.connection.id);assert.equal(replay.data.created,false);assert.equal(f.rows.size,1);assert.deepEqual(f.actions,['configure','configure']);assert.equal(f.sideEffects(),0);});
test('existing inactive CSV is not reactivated',async()=>{const f=fixture();await f.request({account_id:'SYN'});[...f.rows.values()][0].status='disconnected';const r=await f.request({account_id:'SYN'});assert.equal(r.status,409);assert.equal(r.error.code,'connection_not_active');assert.equal([...f.rows.values()][0].status,'disconnected');});
for(const role of ['analyst','operator','viewer'])test(role+' cannot create even if a supplied database port calls the callback',async()=>{const f=fixture(role);assert.equal((await f.request({account_id:'SYN'})).status,403);assert.equal(f.queries.length,0);});
for(const input of [null,[],{}, {account_id:''},{account_id:' '},{account_id:17},{account_id:'x'.repeat(201)},{account_id:'SYN\nsource'},{account_id:'SYN\u007f'},...['source','tenant_id','id','status','credential_ref'].map(k=>({account_id:'SYN',[k]:'untrusted'}))])test('reject invalid/extra metadata '+JSON.stringify(input),async()=>{const f=fixture();assert.equal((await f.request(input)).status,400);assert.equal(f.actions.length,0);assert.equal(f.sideEffects(),0);});
test('account boundary200 and SQL-like text stay parameterized data',async()=>{const f=fixture();assert.equal((await f.request({account_id:'x'.repeat(200)})).status,201);const value="SYN '; DELETE FROM connections; --";assert.equal((await f.request({account_id:value})).status,201);assert(f.queries.some(q=>q.values.includes(value)));assert(f.queries.every(q=>!q.sql.includes(value)));assert.equal(f.rows.size,2);});
test('new route rejects GET/query strings and does not capture import subpaths',async()=>{const f=fixture();assert.equal((await f.request(null,{method:'GET'})).status,405);assert.equal((await f.request({account_id:'SYN'},{path:'/api/imports/connections?tenant=x'})).status,404);assert.equal((await f.request({account_id:'SYN'},{path:'/api/imports/connections/confirm'})).status,404);assert.equal(f.actions.length,0);});
for(const role of ['owner','analyst'])test('list exposes capability for '+role+' without altering import collections',async()=>{const f=fixture(role);const r=await f.request(null,{method:'GET',path:'/api/imports'});assert.equal(r.status,200);assert.equal(r.data.canConfigure,role==='owner');assert.deepEqual(r.data.connections,[]);assert.deepEqual(r.data.reservations,[]);});
