import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {createServer} from 'node:http';import {once} from 'node:events';import {spawn} from 'node:child_process';
import {setup,q} from '../F04-extraction/browser-harness.mjs';import {syntheticConfig} from '../F04-extraction/config-fixture.mjs';
import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';
test('F04 UI revocation invalidates stale authorized responses',{timeout:540000},async t=>{
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-revocation-browser-'));fs.chmodSync(evidence,0o700);let h,provider;const requests=[];let uncertain=false;
 try{
  h=await setup(process.env.VEXA_CANDIDATE,evidence);
  const sync=h.repository(h.A).repository,row=await sync.ensure({connectionId:h.A.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,h.A,'T1',{type:'ticket'}),record(h.ingestion,h.A,'M1',{text:'SYNTHETIC Ana Pérez ana@example.test: 😀 batería rota y cafe\u0301'})],'end',{done:true})});
  const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(h.A.tenant)}`);
  provider=createServer(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks).toString();requests.push({method:req.method,pii:body.includes('Ana Pérez')||body.includes('ana@example.test')});res.setHeader('Content-Type','application/json');if(req.headers.authorization!=='Bearer SYN-EXTRACTION-KEY'){res.writeHead(401);return res.end('{}');}const payload=JSON.parse(body),r=JSON.parse(payload.messages[1].content).revisions[0],quote='😀 batería rota y cafe\u0301',start=[...r.text.slice(0,r.text.indexOf(quote))].length;return res.end(JSON.stringify({id:'SYN-EXTRACTION',usage:uncertain?{}:{cost:'0.000020'},choices:[{finish_reason:'stop',message:{content:JSON.stringify({issues:[{category:'battery',severity:'high',evidence:[{message_revision_id:r.message_revision_id,quote,start,end:start+[...quote].length,role:'customer'}]}],entities:[],sentiment:'negative',intent:'complaint',urgency:'normal',abstention:null})}}]}));});provider.listen(0,'127.0.0.1');await once(provider,'listening');
  const preload=path.join(h.tmp,'synthetic-extraction-preload.mjs');fs.writeFileSync(preload,`const original=globalThis.fetch;globalThis.fetch=(input,init)=>{const u=new URL(typeof input==='string'?input:input.url??String(input));if(u.href==='https://openrouter.ai/api/v1/chat/completions')return original('http://127.0.0.1:${provider.address().port}/synthetic-extraction',init).then(r=>new Response(r.body,{status:r.status,headers:r.headers}));if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('EXTERNAL_NETWORK_NOT_AUTHORIZED');return original(input,init);};`);
  await h.stopWeb();await h.startWeb(false,{NODE_OPTIONS:'--import '+preload,VEXA_EXTRACTION_CONFIG_JSON:JSON.stringify([syntheticConfig(h.A.tenant)]),VEXA_AI_RUNTIME:'enabled',OPENROUTER_API_KEY:'SYN-EXTRACTION-KEY'});
  const browser=await h.browser();let ctx=await browser.newContext();ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(value=>{const i=value.indexOf('=');return{name:value.slice(0,i),value:value.slice(i+1),url:h.base};}));let p=await ctx.newPage();
  async function sendButton(name){const response=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/extraction'&&r.request().method()==='POST');await p.getByRole('button',{name,exact:true}).click();return response;}
  async function tick(){for(let i=0;i<4;i++){const response=await fetch(h.base+'/api/internal/extraction',{method:'POST',headers:{authorization:'Bearer '+h.triggerSecret}}),body=await response.json();assert.equal(response.status,200,'HOSTED:'+JSON.stringify(body));if(body.data?.state&&body.data.state!=='idle')return body.data;}throw Error('NO_WORKER_PROGRESS');}
  await t.test('owner configures both limits and requests analysis from served browser',async()=>{await p.goto(h.base+'/analysis');await p.getByLabel('Tipo de límite').selectOption('all');await p.getByLabel('Límite en USD',{exact:true}).fill('10');assert.equal((await sendButton('Guardar límite')).status(),200);await p.getByText('Global: $10.000000',{exact:true}).waitFor();await p.getByLabel('Tipo de límite').selectOption('extraction');await p.getByLabel('Límite en USD',{exact:true}).fill('5');assert.equal((await sendButton('Guardar límite')).status(),200);await p.getByText('Extracción: $5.000000',{exact:true}).waitFor();await p.getByLabel('Conversación',{exact:true}).selectOption(conversationId);assert.equal((await sendButton('Solicitar análisis')).status(),202);await p.getByText('En cola',{exact:true}).waitFor();const out=await tick();assert.equal(out.state,'succeeded');assert.equal(out.runStatus,'succeeded');await p.reload();await p.getByText('Terminado',{exact:true}).waitFor();assert.equal(requests.length,1);assert.equal(requests[0].pii,false,'NO_PII_OVER_PROVIDER_HTTP');await p.screenshot({path:path.join(evidence,'extraction-finished.png'),fullPage:true});});
  await t.test('browser opens exact authorized quotation from its analysis job',async()=>{await p.getByRole('link',{name:'Ver evidencia',exact:true}).click();await p.getByRole('heading',{name:'Evidencia del análisis',exact:true}).waitFor();assert.equal(await p.locator('blockquote').textContent(),'😀 batería rota y cafe\u0301');await p.getByText(/^Cliente · Revisión/).waitFor();assert.ok(!(await p.locator('body').textContent()).includes('Ana Pérez'));await p.screenshot({path:path.join(evidence,'authorized-quote.png'),fullPage:true});await p.goto(h.base+'/analysis');});
  const settle=async()=>{await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};
  await t.test('late authorized evidence response cannot repopulate after current source denial',async()=>{
   const runId=h.sql(`SELECT id FROM extraction_runs WHERE tenant_id=${q(h.A.tenant)} AND status='succeeded' LIMIT 1`),pattern='**/api/extraction/'+runId+'/evidence';
   let release,firstResolve,deliveredResolve;const held=new Promise(r=>release=r),first=new Promise(r=>firstResolve=r),delivered=new Promise(r=>deliveredResolve=r);let n=0;const observed=[];
   await p.route(pattern,async route=>{const response=await route.fetch();observed.push(response.status());if(++n===1){assert.equal(response.status(),200);firstResolve();await held;try{await route.fulfill({response});}catch(error){if(!/Target closed|disposed|closed|aborted|canceled/i.test(error.message))throw error;}finally{deliveredResolve();}}else await route.fulfill({response});});
   try{await p.goto(h.base+'/analysis/'+runId);await first;h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(h.A.connection)}`);
    await p.getByRole('alert').filter({hasText:'No se puede mostrar evidencia autorizada'}).waitFor({timeout:20000});assert.equal(await p.locator('blockquote').count(),0,'CURRENT_DENIAL_CLEARS');
    release();await delivered;await settle();assert.equal(await p.locator('blockquote').count(),0,'LATE_SUCCESS_MUST_NOT_REPOPULATE_EVIDENCE');assert.equal(await p.getByRole('alert').filter({hasText:'No se puede mostrar evidencia autorizada'}).count(),1,'CURRENT_DENIAL_REMAINS');assert.deepEqual(observed,[200,409]);
   }finally{release();await delivered;await p.unroute(pattern);h.sql(`UPDATE connections SET status='active' WHERE id=${q(h.A.connection)}`);}
  });
  await t.test('membership denial clears analysis snapshot and rejects a late previous snapshot',async()=>{
   await p.goto(h.base+'/analysis');await p.getByText('Global: $10.000000',{exact:true}).waitFor();
   let release,firstResolve,deliveredResolve;const held=new Promise(r=>release=r),first=new Promise(r=>firstResolve=r),delivered=new Promise(r=>deliveredResolve=r);let n=0;const observed=[];
   await p.route('**/api/extraction',async route=>{const response=await route.fetch();observed.push(response.status());if(++n===1){assert.equal(response.status(),200);firstResolve();await held;try{await route.fulfill({response});}catch(error){if(!/Target closed|disposed|closed|aborted|canceled/i.test(error.message))throw error;}finally{deliveredResolve();}}else await route.fulfill({response});});
   try{await first;h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(h.A.id)} AND tenant_id=${q(h.A.tenant)}`);
    await p.getByRole('alert').filter({hasText:'No se pudo consultar el análisis.'}).waitFor({timeout:20000});assert.equal((await h.request(h.A,'/api/extraction')).status,403,'CURRENT_MEMBERSHIP_DENIED');
    const cleared=async()=>{assert.equal(await p.getByText('Global: $10.000000',{exact:true}).count(),0,'DENIAL_CLEARS_PRIVATE_BUDGET');assert.equal(await p.getByRole('button',{name:'Guardar límite',exact:true}).count(),0,'DENIAL_CLEARS_OWNER_FORM');assert.equal(await p.getByRole('link',{name:'Ver evidencia',exact:true}).count(),0,'DENIAL_CLEARS_PRIVATE_JOBS');};
    await cleared();release();await delivered;await settle();await cleared();assert.deepEqual(observed,[200,403]);
   }finally{release();await delivered;await p.unroute('**/api/extraction');h.sql(`UPDATE memberships SET status='active' WHERE user_id=${q(h.A.id)} AND tenant_id=${q(h.A.tenant)}`);}
  });
  await ctx.close();h.verifySources();fs.writeFileSync(path.join(evidence,'provider-requests.json'),JSON.stringify(requests),{mode:0o600});
 }finally{if(h)await h.close();if(provider){provider.closeAllConnections();await new Promise(resolve=>provider.close(resolve));}console.log('F04_REVOCATION_BROWSER:'+evidence);}
});
