import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';
import {setup,q} from '../F04-extraction/harness.mjs';import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';
test('F04-04 authorized evidence and immutable revision history',{timeout:360000},async t=>{
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(fs.existsSync(path.join(candidate,'packages/intelligence/evidence-repository.mjs')),'EVIDENCE_REPOSITORY_IMPLEMENTATION_MISSING');
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-evidence-sql-'));fs.chmodSync(evidence,0o700);let h;
 try{
  h=await setup(candidate,evidence);const {createExtractionRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/extraction-repository.mjs'))),{createEvidenceRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/evidence-repository.mjs'))),{sha256}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/index.mjs')));
  async function fixture(role='customer'){
   const a=await h.actor();Object.assign(a,{connection:randomUUID(),account:'SYN-evidence',source:'zendesk'});h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(a.connection)},${q(a.tenant)},'zendesk','SYN-evidence')`);
   const database=h.database(a),sync=h.sync.createSyncRepository({database}),row=await sync.ensure({connectionId:a.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,a,'T1',{type:'ticket'}),record(h.ingestion,a,'M1',{text:'Ana Pérez: 😀 batería rota y cafe\u0301',role})],'end',{done:true})});
   const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(a.tenant)}`),jobId=h.job(a),repository=createExtractionRepository({database}),prepared=await repository.prepare({conversationId,jobId,taskKey:randomUUID(),taxonomy:['battery'],policy:{version:'SYN',emails:true,phones:true,namesMode:'dictionary',names:['Ana Pérez']}}),revision=prepared.input.revisions[0],quote='😀 batería rota y cafe\u0301',start=[...revision.text.slice(0,revision.text.indexOf(quote))].length;
   const span={message_revision_id:revision.message_revision_id,start,end:start+[...quote].length,quote,quote_hash:sha256(quote),role},data={issues:[{category:'battery',severity:'high',evidence:[span]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null},run=h.json(`SELECT to_jsonb(r) FROM extraction_runs r WHERE id=${q(prepared.runId)}`),result={ok:true,data,meta:{promptHash:run.prompt_hash,schemaHash:run.schema_hash,model:'synthetic/model'},billingState:'settled'};
   return {a,database,sync,repository,prepared,result,quote,jobId,conversationId,span,reader:createEvidenceRepository({database}),complete:()=>repository.complete({runId:prepared.runId,result})};
  }
  await t.test('exact emoji/accent citation is served from authorized immutable redacted revision',async()=>{const f=await fixture();await f.complete();const out=await f.reader.get(f.prepared.runId);assert.equal(out.state,'current');assert.equal(out.issues[0].evidence[0].quote,f.quote);assert.equal(out.issues[0].evidence[0].role,'customer');assert.equal(out.issues[0].evidence[0].quote_hash,f.span.quote_hash);assert.ok(!JSON.stringify(out).includes('Ana Pérez'));});
  await t.test('internal note retains its role and cannot become a customer quotation',async()=>{const f=await fixture('internal');await f.complete();assert.equal((await f.reader.get(f.prepared.runId)).issues[0].evidence[0].role,'internal');const forged=await fixture('internal');forged.result.data.issues[0].evidence[0].role='customer';assert.equal((await forged.complete()).status,'failed');await assert.rejects(forged.reader.get(forged.prepared.runId));});
  for(const defect of ['invented_quote','outside_range','foreign_revision'])await t.test('claim rejects '+defect+' without publishing an issue',async()=>{const f=await fixture(),span=f.result.data.issues[0].evidence[0];if(defect==='invented_quote'){span.quote='SYN inventada';span.quote_hash=sha256(span.quote);}if(defect==='outside_range')span.end+=10;if(defect==='foreign_revision'){const other=await fixture();span.message_revision_id=other.span.message_revision_id;assert.equal(other.quote,f.quote);}assert.equal((await f.complete()).status,'failed');assert.equal(h.sql(`SELECT count(*) FROM issues WHERE tenant_id=${q(f.a.tenant)}`),'0');await assert.rejects(f.reader.get(f.prepared.runId));});
  await t.test('same text, foreign tenant and revoked identity do not authorize a quote',async()=>{const f=await fixture();await f.complete();const other=await h.actor();await assert.rejects(createEvidenceRepository({database:h.database(other)}).get(f.prepared.runId));h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(f.a.id)}`);await assert.rejects(f.reader.get(f.prepared.runId));});
  await t.test('viewer can read redacted evidence without any redaction-map access',async()=>{const f=await fixture();await f.complete();const viewer=await h.actor('viewer',f.a.tenant);const database=h.database(viewer);assert.equal((await database.transaction('read',s=>s.query('SELECT id FROM redaction_maps'))).rows.length,0);assert.equal((await createEvidenceRepository({database}).get(f.prepared.runId)).issues[0].evidence[0].quote,f.quote);});
  for(const field of ['revision','message','conversation','connection','tombstone','head'])await t.test('revoked source '+field+' prevents historical quote display',async()=>{const f=await fixture();await f.complete();if(field==='revision')h.sql(`UPDATE message_revisions SET deleted_at=now() WHERE id=${q(f.span.message_revision_id)}`);if(field==='message')h.sql(`UPDATE messages SET deleted_at=now() WHERE tenant_id=${q(f.a.tenant)}`);if(field==='conversation')h.sql(`UPDATE conversations SET deleted_at=now() WHERE id=${q(f.conversationId)}`);if(field==='connection')h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(f.a.connection)}`);if(field==='head')h.sql(`DELETE FROM source_heads WHERE tenant_id=${q(f.a.tenant)} AND entity_type='message'`);if(field==='tombstone')h.sql(`INSERT INTO tombstones(tenant_id,deleted_source_key,reason) VALUES(${q(f.a.tenant)},${q(f.conversationId)},'SYN retention')`);await assert.rejects(f.reader.get(f.prepared.runId));});
  await t.test('tampered revision is rejected even if its mutable hash is changed too',async()=>{const f=await fixture();await f.complete();h.sql(`UPDATE message_revisions SET redacted_text='SYN altered',hash=${q(sha256('SYN altered'))} WHERE id=${q(f.span.message_revision_id)}`);await assert.rejects(f.reader.get(f.prepared.runId));});
  await t.test('new selected source revision keeps prior evidence historical and rejects stale extraction',async()=>{const old=await fixture();await old.complete();const pending=await fixture(),{selectCanonicalRevision}=await import(pathToFileURL(path.join(h.built,'packages/ingestion/persistence/index.mjs')));for(const f of [old,pending]){
   const syncRow=await f.sync.ensure({connectionId:f.a.connection,mode:'live',window:{...windowSpec,to:'2026-09-02T00:00:00.000Z',version:'SYN-next'},mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await f.sync.claim({syncId:syncRow.id,workerId,leaseMs:30000});await f.sync.commitPage({syncId:syncRow.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,f.a,'M1',{text:'SYN nuevo contenido',revision:'r2'})],'next-end',{done:true})});
   const head=h.json(`SELECT to_jsonb(h) FROM source_heads h WHERE tenant_id=${q(f.a.tenant)} AND entity_type='message'`),revisionId=h.sql(`SELECT id FROM source_revisions WHERE tenant_id=${q(f.a.tenant)} AND entity_type='message' AND source_revision='r2'`);assert.equal(head.state,'ambiguous');assert.equal((await f.database.transaction('import',scope=>selectCanonicalRevision(scope,{canonicalId:head.id,revisionId,expectedVersion:head.version,reason:'SYN authorized revision selection'}))).status,'selected');
  }assert.equal((await old.reader.get(old.prepared.runId)).state,'historical');const result=await pending.complete();assert.equal(result.status,'failed');assert.equal(result.reason,'source_changed');assert.equal(h.sql(`SELECT count(*) FROM issues WHERE tenant_id=${q(pending.a.tenant)}`),'0');});
  h.verifySources();
 }finally{if(h)await h.close();console.log('F04_EVIDENCE_SQL:'+evidence);}
});
