import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash,createHmac} from 'node:crypto';import {runLive} from './live.mjs';import {server,origin} from './http.mjs';
const date='2026-09-20T12:00:00Z',text='SYNTHETIC independently expected';const sha=x=>createHash('sha256').update(x).digest('hex');
test('full live driver uses real loopback HTTP but stays labelled synthetic',async()=>{
 const root=process.env.VEXA_CANDIDATE;if(!root)throw new Error('VEXA_CANDIDATE_REQUIRED');const privateRoot=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-zendesk-live-synthetic-'));const key='SYNTHETIC-RECONCILIATION-KEY-AT-LEAST-32-BYTES';
 const tickets=Array.from({length:21},(_,i)=>({id:String(i+1),updated_at:date,deleted:i===0,updated_since_previous_export:i===1,comments:i===0?[]:[{id:String(100+i),role:i===1?'internal':'customer',visibility:i===1?'internal':'public',text_sha256:sha(text)}]}));
 const reference={version:1,subdomain:'synthetic-vexa',startTime:1700000000,origin:'ui-export',independentExportRef:'SYNTHETIC-EXTERNAL-EXPORT',tickets};reference.signature=createHmac('sha256',key).update(JSON.stringify(reference)).digest('hex');const referenceText=JSON.stringify(reference);fs.writeFileSync(path.join(privateRoot,'reference.json'),referenceText,{mode:0o600});
 const config={version:1,authorizationRef:'SYNTHETIC-APPROVAL',subdomain:'synthetic-vexa',context:{tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',source:'zendesk',source_account_id:'synthetic-vexa'},accountConfirmed:true,providerContractConfirmed:true,authorizedReadScope:'account-wide-incremental-tickets-comments-authors',startTime:1700000000,expiresAt:Date.now()+60000,expectedAdminUserId:'3',maxPages:5,maxRecords:1000,referenceFile:'reference.json',referenceSha256:sha(referenceText)};const configPath=path.join(privateRoot,'config.json');fs.writeFileSync(configPath,JSON.stringify(config),{mode:0o600});
 const keys=['VEXA_ZENDESK_S02_CONFIG','VEXA_ZENDESK_TOKEN','VEXA_ZENDESK_RECONCILIATION_KEY','VEXA_ZENDESK_APPROVAL_REFERENCE'],old=Object.fromEntries(keys.map(k=>[k,process.env[k]])),native=globalThis.fetch;
 const s=await server(u=>{if(u.pathname==='/api/v2/users/me.json')return {user:{id:3,role:'admin'}};if(u.pathname==='/api/v2/oauth/tokens/current.json')return {token:{user_id:3,scopes:['read'],token:'SYNTHETIC-SECRET-PREFIX'}};if(u.pathname.includes('/incremental/'))return {tickets:tickets.map(t=>({id:Number(t.id),created_at:date,updated_at:date,status:t.deleted?'deleted':'open'})),after_cursor:'end',after_url:`${origin}/api/v2/incremental/tickets/cursor.json?cursor=end`,end_of_stream:true};if(u.pathname.includes('/comments')){const id=u.pathname.split('/')[4],t=tickets.find(t=>t.id===id);return {comments:t.comments.map(c=>({id:Number(c.id),author_id:4,created_at:date,public:c.visibility==='public',plain_body:text})),meta:{has_more:false},links:{next:null}};}return {user:{id:4,role:'end-user'}};});
 try{Object.assign(process.env,{VEXA_ZENDESK_S02_CONFIG:configPath,VEXA_ZENDESK_TOKEN:'SYNTHETIC-TOKEN',VEXA_ZENDESK_RECONCILIATION_KEY:key,VEXA_ZENDESK_APPROVAL_REFERENCE:'WRONG-APPROVAL'});globalThis.fetch=s.fetch;await assert.rejects(()=>runLive(root),/S02_APPROVAL_MISMATCH/);assert.equal(s.requests.length,0,'APPROVAL_BEFORE_NETWORK');process.env.VEXA_ZENDESK_APPROVAL_REFERENCE=config.authorizationRef;process.env.VEXA_ZENDESK_RECONCILIATION_KEY='SYNTHETIC-WRONG-KEY-OF-ENOUGH-LENGTH';await assert.rejects(()=>runLive(root),/S02_REFERENCE_SIGNATURE/);assert.equal(s.requests.length,0,'SIGNATURE_BEFORE_NETWORK');process.env.VEXA_ZENDESK_RECONCILIATION_KEY=key;fs.writeFileSync(configPath,JSON.stringify({...config,authorizedReadScope:'selected-20-tickets'}));await assert.rejects(()=>runLive(root),/S02_SCOPE_REQUIRED/);assert.equal(s.requests.length,0,'SCOPE_BEFORE_NETWORK');fs.writeFileSync(configPath,JSON.stringify(config));const result=await runLive(root);assert.equal(result.status,'pass');assert.equal(result.matched_tickets,21);assert.equal(result.matched_messages,20);assert.ok(!JSON.stringify(result).includes('SECRET'));assert.equal(result.reference_sha256,sha(referenceText));}
 finally{globalThis.fetch=native;for(const key of keys)if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];await s.close();fs.rmSync(privateRoot,{recursive:true});}
});
test('missing live configuration is blocked without any network',async()=>{const old={...process.env};delete process.env.VEXA_ZENDESK_S02_CONFIG;const native=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('FORBIDDEN');};try{await assert.rejects(()=>runLive(process.env.VEXA_CANDIDATE),/S02_LIVE_BLOCKED/);assert.equal(calls,0);}finally{globalThis.fetch=native;if(old.VEXA_ZENDESK_S02_CONFIG!==undefined)process.env.VEXA_ZENDESK_S02_CONFIG=old.VEXA_ZENDESK_S02_CONFIG;}});
