'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {CauseView} from '../../../../packages/problems/causality.mjs';
export function CauseEvidence({problemId}:{problemId:string}){
 const generation=useRef(0);const [data,setData]=useState<CauseView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [symptom,setSymptom]=useState(''),[cause,setCause]=useState(''),[state,setState]=useState('hypothesis'),[reason,setReason]=useState(''),[refs,setRefs]=useState<string[]>([]),[approved,setApproved]=useState(false);
 const [recordId,setRecordId]=useState(''),[sourceKind,setSourceKind]=useState('inspection'),[observedAt,setObservedAt]=useState(''),[report,setReport]=useState(''),[stance,setStance]=useState('supports'),[status,setStatus]=useState('active'),[batch,setBatch]=useState(''),[carrier,setCarrier]=useState(''),[sku,setSku]=useState(''),[attested,setAttested]=useState(false);
 const clear=useCallback(()=>{setData(null);setBusy(false);setSymptom('');setCause('');setReason('');setRefs([]);setApproved(false);setRecordId('');setReport('');setObservedAt('');setBatch('');setCarrier('');setSku('');setAttested(false);},[]);
 const request=useCallback(async(body?:unknown)=>{const epoch=++generation.current;setBusy(true);try{const r=await fetch('/api/problems/'+encodeURIComponent(problemId)+'/causality',{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(epoch!==generation.current)return;if(r.status===401||r.status===403){generation.current++;clear();setError('Autorización revocada.');return;}const value=await r.json();if(epoch!==generation.current)return;if(!r.ok)throw Error(r.status===409?'La versión o la evidencia cambió. Actualiza antes de continuar.':'No se pudo completar la evaluación.');setData(value.data);setSymptom(value.data.claim.symptom);setCause(value.data.claim.probableCause??'');setRefs([]);setApproved(false);setAttested(false);setError('');}catch(e){if(epoch===generation.current){clear();setError(e instanceof Error?e.message:'Error de consulta');}}finally{if(epoch===generation.current)setBusy(false);}},[problemId,clear]);
 const invalidate=useCallback(()=>{generation.current++;},[]);
 useEffect(()=>{void Promise.resolve().then(()=>request());return invalidate;},[request,invalidate]);
 const current=data?.evidence.filter(e=>!data.evidence.some(other=>other.recordId===e.recordId&&other.version>e.version))??[];
 return <section aria-label="Evaluación causal"><h2>Síntoma, hipótesis y confirmación operacional</h2><button disabled={busy} onClick={()=>void request()}>Actualizar evaluación causal</button>{error&&<p role="alert">{error}</p>}{data&&<>
 {data.claim.criticalReview&&<p role="alert">Posible riesgo severo: revisión humana prioritaria, incluso con baja corroboración. No demuestra un defecto de lote. No activa recall ni reembolso.</p>}
 <p>Síntoma: {data.claim.symptom}</p><p>Causa probable: {data.claim.probableCause??'Desconocida'}</p><p>Estado operacional: {data.claim.state} · Versión {data.claim.version}</p><p>Lote: {data.claim.facts.batch??'Desconocido'} · Transportista: {data.claim.facts.carrier??'Desconocido'} · SKU: {data.claim.facts.sku??'Desconocido'}</p><p>Una agrupación o una confianza estadística no confirma causalidad. La confirmación registra una revisión humana y sus pruebas operacionales.</p>
 <h3>Evidencia operacional y contraria</h3>{current.map(e=><article key={e.id}><h4>{e.recordId} · versión {e.version} · {e.status}</h4><p>{e.sourceKind} · {e.stance==='contradicts'?'Contradice la hipótesis':'Apoya la hipótesis'} · Actor {e.actorId}</p><pre>{e.report}</pre><p>Huella: {e.digest}</p></article>)}
 {data.canRecord&&<form onSubmit={e=>{e.preventDefault();const old=current.find(x=>x.recordId===recordId);void request({operation:'evidence',expectedVersion:data.claim.version,expectedEvidenceVersion:old?.version??0,recordId,sourceKind,observedAt:new Date(observedAt).toISOString(),report,stance,status,facts:{batch:batch.trim()||null,carrier:carrier.trim()||null,sku:sku.trim()||null},attested});}}><fieldset disabled={busy}><legend>Aportar o rectificar prueba operacional independiente</legend><label>Identificador del registro operacional<input required maxLength={200} value={recordId} onChange={e=>{setRecordId(e.target.value);setAttested(false);}}/></label><label>Procedencia<select value={sourceKind} onChange={e=>setSourceKind(e.target.value)}><option value="inspection">Inspección física</option><option value="lab">Ensayo de laboratorio</option><option value="carrier_record">Registro del transportista</option></select></label><label>Fecha de observación<input required type="datetime-local" value={observedAt} onChange={e=>setObservedAt(e.target.value)}/></label><label>Informe operacional: método y observaciones<textarea required minLength={20} maxLength={16000} value={report} onChange={e=>{setReport(e.target.value);setAttested(false);}}/></label><label>Relación con la hipótesis<select value={stance} onChange={e=>setStance(e.target.value)}><option value="supports">Apoya</option><option value="contradicts">Contradice</option></select></label><label>Estado de la prueba<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Vigente</option><option value="withdrawn">Retirada mediante nueva versión</option></select></label><label>Lote documentado, opcional<input value={batch} onChange={e=>setBatch(e.target.value)}/></label><label>Transportista documentado, opcional<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>SKU documentado, opcional<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>Atestiguo que revisé este registro operacional independiente del ticket y que los datos indicados constan en él.</label><button disabled={!attested}>Guardar evidencia operacional</button></fieldset></form>}
 {data.canRecord&&<form onSubmit={e=>{e.preventDefault();void request({operation:'revise',expectedVersion:data.claim.version,symptom,probableCause:cause.trim()||null,state,evidenceIds:refs,reason,approved});}}><fieldset disabled={busy}><legend>Revisar la evaluación causal</legend><label>Síntoma observado<textarea required value={symptom} onChange={e=>{setSymptom(e.target.value);setApproved(false);}}/></label><label>Causa probable, opcional<textarea value={cause} onChange={e=>{setCause(e.target.value);setApproved(false);}}/></label><label>Decisión<select value={state} onChange={e=>{setState(e.target.value);setApproved(false);}}><option value="hypothesis">Hipótesis, sin confirmación</option>{data.canConfirm&&<option value="confirmed">Confirmación operacional humana</option>}<option value="retracted">Rectificar o retirar confirmación</option></select></label>{current.filter(x=>x.status==='active').map(x=><label key={x.id}><input type="checkbox" checked={refs.includes(x.id)} onChange={e=>{setRefs(v=>e.target.checked?[...v,x.id]:v.filter(id=>id!==x.id));setApproved(false);}}/>{x.recordId} · {x.stance}</label>)}<label>Motivo y valoración de evidencia contraria<textarea required value={reason} onChange={e=>{setReason(e.target.value);setApproved(false);}}/></label><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Confirmo esta revisión humana y su alcance; no ordena acciones externas.</label><button disabled={!approved||state==='confirmed'&&(!cause.trim()||!refs.length)}>Guardar revisión causal</button></fieldset></form>}
 <details><summary>Historial inmutable de evaluaciones y pruebas</summary>{data.history.map(h=><article key={h.version}><p>Versión {h.version}: {h.state}, actor {h.actorId}</p><p>{h.symptom} · {h.probableCause??'Sin causa afirmada'} · {h.reason}</p></article>)}{data.evidence.map(e=><p key={e.id}>{e.recordId} v{e.version}: {e.stance}, {e.status}, actor {e.actorId}, huella {e.digest}</p>)}</details>
 </>}</section>;
}
