"use client";
import {useEffect,useRef,useState} from 'react';
import type {CRMSettings} from '../../../../packages/connectors/runtime.mjs';
export function ConnectionSettings(){
 const requestGeneration=useRef(0);
 const [rows,setRows]=useState<CRMSettings[]>([]),[owner,setOwner]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState<CRMSettings|null>(null),[source,setSource]=useState<'hubspot'|'zendesk'>('zendesk'),[account,setAccount]=useState(''),[credential,setCredential]=useState(''),[history,setHistory]=useState(''),[enabled,setEnabled]=useState(true);
 function deny(){requestGeneration.current++;setRows([]);setOwner(false);setSelected(null);setSource('zendesk');setAccount('');setCredential('');setHistory('');setEnabled(true);setNotice('');setBusy(false);setError('Ya no tienes autorización para consultar o configurar estas conexiones.');}
 useEffect(()=>{const controller=new AbortController(),generation=++requestGeneration.current;async function load(){try{const response=await fetch('/api/connections/settings',{cache:'no-store',signal:controller.signal});if(controller.signal.aborted||generation!==requestGeneration.current)return;if([401,403].includes(response.status)){deny();return;}if(!response.ok)throw Error('No se pudo consultar la configuración de conexiones.');const value=await response.json();if(!Array.isArray(value.settings))throw Error('Respuesta de configuración inválida.');if(!controller.signal.aborted&&generation===requestGeneration.current){setRows(value.settings);setOwner(value.canConfigure===true);}}catch(e){if(!controller.signal.aborted&&generation===requestGeneration.current)setError(e instanceof Error?e.message:'No se pudo cargar.');}finally{if(!controller.signal.aborted&&generation===requestGeneration.current)setBusy(false);}}void load();return()=>controller.abort();},[]);
 function edit(row:CRMSettings|null){setSelected(row);setSource(row?.source??'zendesk');setAccount(row?.accountId??'');setCredential(row?.credentialRef??'');setHistory(row?.historyFrom.slice(0,16)??'');setEnabled(row?.enabled??true);setError('');setNotice('');}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const generation=++requestGeneration.current;setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/connections/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(selected?{connectionId:selected.connectionId,expectedVersion:selected.version}:{}),source,accountId:account,credentialRef:credential,historyFrom:new Date(history+'Z').toISOString(),enabled,overlapSeconds:selected?.overlapSeconds??60,pollSeconds:selected?.pollSeconds??300})});if(generation!==requestGeneration.current)return;if([401,403].includes(response.status)){deny();return;}if(!response.ok)throw Error(response.status===409?'La configuración cambió. Recarga antes de guardar.':response.status===403?'Sólo el propietario puede configurar conexiones.':'No se pudo guardar la conexión.');const {data}=await response.json();if(generation!==requestGeneration.current)return;setRows(previous=>[...previous.filter(row=>row.connectionId!==data.connectionId),data]);setSelected(data);setNotice(data.enabled?'Conexión guardada. La carga histórica y la comprobación de permisos se ejecutarán en el próximo ciclo del consumidor.':'Sincronización pausada. El historial ya guardado se conserva.');}catch(e){if(generation===requestGeneration.current)setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{if(generation===requestGeneration.current)setBusy(false);}}
 return <section aria-labelledby="connection-settings-title"><h2 id="connection-settings-title">Configurar sincronización</h2>
 {busy&&<p role="status">Consultando configuración…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!busy&&rows.length===0&&!error&&<p>Aún no hay una sincronización programada.</p>}
 {rows.map(row=><article key={row.connectionId}><h3>{row.source}: {row.accountId}</h3><p>{row.enabled?'Habilitada':'Pausada'} · Histórico desde {new Date(row.historyFrom).toLocaleDateString('es-MX',{timeZone:'UTC'})}</p>{row.errorCode&&<p role="status">{row.errorCode==='CRM_CREDENTIAL_CONFIGURATION_REQUIRED'?'Falta configurar la credencial de esta cuenta.':row.errorCode==='RECONNECT_REQUIRED'?'La cuenta requiere reconexión.':'La sincronización requiere revisión.'} {row.failureCount>=4?'Se detuvo tras cuatro fallos; corrige la causa y guarda para reanudar.':''}</p>}{owner&&<button disabled={busy} onClick={()=>edit(row)}>Editar {row.accountId}</button>}</article>)}
 {owner&&<><button disabled={busy} onClick={()=>edit(null)}>Nueva conexión</button><form onSubmit={event=>void save(event)}>
 <label>Proveedor<select value={source} disabled={busy||selected!==null} onChange={event=>setSource(event.target.value as 'hubspot'|'zendesk')}><option value="zendesk">Zendesk</option><option value="hubspot">HubSpot</option></select></label>
 <label>Identificador de la cuenta<input required maxLength={200} value={account} disabled={busy||selected!==null} onChange={event=>setAccount(event.target.value)}/></label>
 <label>Nombre de la credencial configurada<input required maxLength={120} pattern="[a-zA-Z0-9_.:-]+" value={credential} disabled={busy} onChange={event=>setCredential(event.target.value)}/></label><p>Usa el nombre asignado a la credencial de esta organización. No pegues un token en este campo.</p>
 <label>Inicio del histórico (UTC)<input required type="datetime-local" value={history} disabled={busy} onChange={event=>setHistory(event.target.value)}/></label><p>Cambiar esta fecha inicia otra carga histórica; los registros repetidos se deduplican. HubSpot puede recorrer todo el histórico disponible.</p>
 <label><input type="checkbox" checked={enabled} disabled={busy} onChange={event=>setEnabled(event.target.checked)}/>Habilitar sincronización</label><button type="submit" disabled={busy}>Guardar conexión</button>
 </form></>}
 </section>;
}
