'use client';
import {formatMinorUnits as money} from '../../../../packages/metrics/money.mjs';
import {useState} from 'react';
import type {EconomicEntry,EconomicSource} from '../../../../packages/metrics/repository.mjs';
import type {ExposureView} from '../../../../packages/metrics/exposure.mjs';

type Props={view:ExposureView;entries:EconomicEntry[];sources:EconomicSource[];canWrite:boolean;busy:boolean;onSubmit:(input:unknown)=>Promise<void>};
type Metric={amountMinor:string|null;knownSubtotalMinor:string|null;knownCount:number;totalCount:number;status:string;currency:string;exponent:number};
const kindLabel:Record<string,string>={order:'Orden',refund:'Reembolso',reversal:'Reversión',replacement:'Reemplazo',support_model:'Soporte modelado'};

function Amount({name,value}:{name:string;value:Metric}){return <article aria-label={name}><h4>{name}</h4><p>{money(value.amountMinor,value.currency,value.exponent)}</p><p>Subtotal conocido: {money(value.knownSubtotalMinor,value.currency,value.exponent)} · Cobertura {value.knownCount}/{value.totalCount}</p>{value.amountMinor===null&&<p>El subtotal no acredita el total. Hay importes, vínculos o cobertura pendientes de revisión.</p>}</article>;}
function Records({ids,entries,sources}:{ids:string[];entries:EconomicEntry[];sources:EconomicSource[]}){return <details><summary>Ver registros y evidencia</summary>{[...new Set(ids)].map(id=>{const e=entries.find(row=>row.id===id);return e?<article key={id}><h5>{e.externalId} · {kindLabel[e.kind]}</h5><p>{money(e.amountMinor,e.currency,e.exponent)} · {e.effectiveAt}</p><p>{e.report}</p><p>Revisión {e.revision}; fuente {sources.find(s=>s.id===e.sourceId)?.name??'pendiente de revisión'}.</p></article>:<p key={id}>El registro ya no está disponible en la consulta autorizada actual.</p>;})}</details>;}
function Approval({name,report,approved,onReport,onApproved}:{name:string;report:string;approved:boolean;onReport:(v:string)=>void;onApproved:(v:boolean)=>void}){return <><label>Evidencia de {name}<textarea required minLength={20} maxLength={4000} value={report} onChange={e=>{onReport(e.target.value);onApproved(false);}}/></label><label style={{display:'flex',alignItems:'center',gap:'.5rem'}}><input style={{width:'auto'}} type="checkbox" checked={approved} onChange={e=>onApproved(e.target.checked)}/>Revisé y apruebo {name}</label></>;}

export function EconomicExposurePanel({view,entries,sources,canWrite,busy,onSubmit}:Props){
 const [problem,setProblem]=useState(''),[entry,setEntry]=useState(''),[linkReport,setLinkReport]=useState(''),[linkApproved,setLinkApproved]=useState(false);
 const [alias,setAlias]=useState(''),[canonical,setCanonical]=useState(''),[aliasReport,setAliasReport]=useState(''),[aliasApproved,setAliasApproved]=useState(false);
 const [customerOrder,setCustomerOrder]=useState(''),[customerKey,setCustomerKey]=useState(''),[customerReport,setCustomerReport]=useState(''),[customerApproved,setCustomerApproved]=useState(false);
 const [complete,setComplete]=useState(false),[coverageReport,setCoverageReport]=useState(''),[coverageApproved,setCoverageApproved]=useState(false);
 const [approvalHash,setApprovalHash]=useState<Record<string,string>>({});
 const consent=(kind:string,approved:boolean)=>approved&&approvalHash[kind]===view.inputHash;
 const approve=(kind:string,setter:(v:boolean)=>void)=>(value:boolean)=>{setter(value);setApprovalHash(previous=>({...previous,[kind]:view.inputHash}));};
 const linkConsent=consent('link',linkApproved),aliasConsent=consent('alias',aliasApproved),customerConsent=consent('customer',customerApproved),coverageConsent=consent('coverage',coverageApproved);
 const ledger=entries.filter(e=>Object.hasOwn(kindLabel,e.kind)),orders=ledger.filter(e=>e.kind==='order');
 const currentEntry=ledger.find(e=>e.rowId===entry),currentRelation=view.relations.find(r=>r.problemId===problem&&r.entityId===currentEntry?.id);
 const aliasEntry=orders.find(e=>e.rowId===alias),currentAlias=view.aliases.find(a=>a.aliasEntityId===aliasEntry?.id);
 const selectedOrder=orders.find(e=>e.rowId===customerOrder),currentCustomer=view.customerBindings.find(c=>c.entityId===selectedOrder?.id);
 const label=(id:string)=>view.problemOptions.find(p=>p.id===id)?.label??'Problema autorizado';
 const rowName=(id:string)=>ledger.find(e=>e.id===id)?.externalId??'Registro pendiente de revisión';
 const chooseEntry=(e:EconomicEntry)=><option key={e.rowId} value={e.rowId}>{kindLabel[e.kind]} · {e.externalId} · {money(e.amountMinor,e.currency,e.exponent)}</option>;
 const submitLink=(active:boolean)=>{if(!currentEntry||!problem||!linkConsent)return;setLinkApproved(false);void onSubmit({operation:'link',problemId:problem,ledgerRowId:entry,expectedVersion:currentRelation?.version??0,active,report:linkReport,attested:true});};
 const submitAlias=(active:boolean)=>{if(!alias||!canonical||!aliasConsent)return;setAliasApproved(false);void onSubmit({operation:'orderAlias',aliasRowId:alias,canonicalRowId:canonical,expectedVersion:currentAlias?.version??0,active,report:aliasReport,attested:true});};
 const customerMetric=view.metrics.customerExposure.global;
 return <section aria-label="Exposición por problemas"><h3>Exposición por problemas</h3><p>Ingresos de órdenes vinculadas, no pérdidas. Los totales globales usan registros únicos; las filas por problema no se suman.</p><p>Ventana UTC: {view.scope.start} a {view.scope.end}, fin exclusivo. Moneda {view.scope.currency}; base {view.scope.basis}.</p>
 <Amount name="Exposición global de órdenes" value={view.metrics.global}/><Records ids={view.metrics.membership.map(r=>r.orderId)} entries={ledger} sources={sources}/>
 <article aria-label="Clientes únicos vinculados"><h4>Clientes únicos vinculados</h4><p>{customerMetric.count===null?'Total desconocido':`${customerMetric.count} clientes únicos`}</p><p>{customerMetric.knownCount} identidades conocidas · {customerMetric.knownOrderCount}/{customerMetric.totalOrderCount} órdenes con identidad.</p><p>Identidades canónicas declaradas y aprobadas por el propietario; no se infieren de nombres o correos.</p></article>
 {Object.entries(view.metrics.byProblem).length===0?<p>Sin exposición por problema calculable para esta ventana. Revisa los vínculos y la cobertura.</p>:<div role="group" aria-label="Exposición por problema, filas no aditivas">{Object.entries(view.metrics.byProblem).map(([id,metric])=><section key={id} aria-label={label(id)}><h4>{label(id)}</h4><Amount name="Ingresos de órdenes vinculadas" value={metric}/><p>Fila no aditiva: una orden puede aparecer en varios problemas.</p><Records ids={view.metrics.membership.filter(r=>r.problemId===id).map(r=>r.orderId)} entries={ledger} sources={sources}/>{view.metrics.eventUnion.byProblem[id]&&<details><summary>Eventos asociados a este problema, no aditivos</summary><Amount name="Reembolsos del problema" value={view.metrics.eventUnion.byProblem[id].refunds}/><Amount name="Reemplazos del problema" value={view.metrics.eventUnion.byProblem[id].replacement}/><Amount name="Soporte modelado del problema" value={view.metrics.eventUnion.byProblem[id].supportModel}/><Records ids={view.metrics.eventUnion.byProblem[id].eventIds} entries={ledger} sources={sources}/></details>}{view.metrics.customerExposure.byProblem[id]&&<p>Clientes únicos: {view.metrics.customerExposure.byProblem[id].count??'total desconocido'} · {view.metrics.customerExposure.byProblem[id].knownCount} identidades conocidas.</p>}</section>)}</div>}
 <section aria-label="Eventos asociados sin duplicación"><h4>Eventos asociados sin duplicación</h4><p>Cada evento cuenta una vez en el global, aunque esté relacionado con varios problemas. No acredita causalidad.</p><Amount name="Reembolsos asociados netos" value={view.metrics.eventUnion.global.refunds}/><Amount name="Costos de reemplazo asociados" value={view.metrics.eventUnion.global.replacement}/><Amount name="Soporte modelado asociado" value={view.metrics.eventUnion.global.supportModel}/><Records ids={view.metrics.eventUnion.global.eventIds} entries={ledger} sources={sources}/></section>
 <p role="status">{view.coverage?.complete&&view.coverage.current?'Cobertura de vínculos revisada para estos datos.':'Cobertura de vínculos pendiente o desactualizada. Los totales completos permanecen desconocidos.'}</p>
 <details><summary>Vínculos y equivalencias vigentes</summary>{view.relations.length===0&&<p>Todavía no hay vínculos registrados.</p>}{view.relations.map(r=><article key={r.id}><h4>{label(r.problemId)} · {rowName(r.entityId)}</h4><p>Versión {r.version} · {r.active?'Vínculo activo':'Vínculo retirado'}{!r.valid?' · Requiere revisar evidencia, fuente o permisos':''}</p><p>{r.report}</p></article>)}{view.aliases.map(a=><article key={a.id}><h4>{rowName(a.aliasEntityId)} → {rowName(a.canonicalEntityId)}</h4><p>Equivalencia v{a.version} · {a.active&&a.valid?'Confirmada':'Retirada o pendiente de revisión'}</p><p>{a.report}</p></article>)}{view.customerBindings.map(c=><article key={c.id}><h4>{rowName(c.entityId)} · Identidad declarada</h4><p>{c.valid&&c.customerKey?c.customerKey:'Sin identidad vigente'} · versión {c.version}</p><p>{c.report}</p></article>)}</details>
 {canWrite&&<>
 <details open><summary>Vincular un registro a un problema</summary><form onSubmit={e=>{e.preventDefault();submitLink(true);}}><fieldset disabled={busy}><legend>Relación económica documentada</legend><label>Problema<select required value={problem} onChange={e=>{setProblem(e.target.value);setLinkApproved(false);}}><option value="">Selecciona un problema</option>{view.problemOptions.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Registro económico documentado<select required value={entry} onChange={e=>{setEntry(e.target.value);setLinkApproved(false);}}><option value="">Selecciona un registro</option>{ledger.map(chooseEntry)}</select></label>{currentRelation&&<p>Versión actual {currentRelation.version}; {currentRelation.active?'vínculo activo':'vínculo retirado'}.</p>}<Approval name="el vínculo" report={linkReport} approved={linkConsent} onReport={setLinkReport} onApproved={approve('link',setLinkApproved)}/><button disabled={!linkConsent||!entry||!problem}>Vincular registro económico</button>{currentRelation?.active&&<button type="button" disabled={!linkConsent} onClick={()=>submitLink(false)}>Retirar vínculo</button>}</fieldset></form></details>
 <details><summary>Confirmar equivalencia de órdenes</summary><p>Usa esta opción sólo cuando la evidencia demuestra que ambos registros representan la misma orden. El importe o el nombre por sí solos no prueban identidad.</p><form onSubmit={e=>{e.preventDefault();submitAlias(true);}}><fieldset disabled={busy}><legend>Equivalencia de órdenes</legend><label>Orden duplicada<select required value={alias} onChange={e=>{setAlias(e.target.value);setAliasApproved(false);}}><option value="">Selecciona una orden duplicada</option>{orders.map(chooseEntry)}</select></label><label>Orden canónica<select required value={canonical} onChange={e=>{setCanonical(e.target.value);setAliasApproved(false);}}><option value="">Selecciona la orden canónica</option>{orders.filter(e=>e.rowId!==alias).map(chooseEntry)}</select></label><Approval name="la equivalencia" report={aliasReport} approved={aliasConsent} onReport={setAliasReport} onApproved={approve('alias',setAliasApproved)}/><button disabled={!aliasConsent||!alias||!canonical}>Guardar equivalencia de órdenes</button>{currentAlias?.active&&<button type="button" disabled={!aliasConsent||!canonical} onClick={()=>submitAlias(false)}>Retirar equivalencia</button>}</fieldset></form></details>
 <details><summary>Identidad de cliente declarada</summary><p>Introduce una clave canónica estable respaldada por evidencia. La misma clave identifica al mismo cliente dentro de esta organización. Déjala vacía para retirar una identidad.</p><form onSubmit={e=>{e.preventDefault();if(!customerOrder||!customerConsent)return;setCustomerApproved(false);void onSubmit({operation:'orderCustomer',orderRowId:customerOrder,customerKey:customerKey.trim()||null,expectedVersion:currentCustomer?.version??0,report:customerReport,attested:true});}}><fieldset disabled={busy}><legend>Identidad de cliente de la orden</legend><label>Orden con identidad de cliente<select required value={customerOrder} onChange={e=>{setCustomerOrder(e.target.value);const order=orders.find(o=>o.rowId===e.target.value);setCustomerKey(view.customerBindings.find(c=>c.entityId===order?.id)?.customerKey??'');setCustomerApproved(false);}}><option value="">Selecciona una orden</option>{orders.map(chooseEntry)}</select></label><label>Clave canónica del cliente<input maxLength={200} value={customerKey} onChange={e=>{setCustomerKey(e.target.value);setCustomerApproved(false);}}/></label><Approval name="la identidad del cliente" report={customerReport} approved={customerConsent} onReport={setCustomerReport} onApproved={approve('customer',setCustomerApproved)}/><button disabled={!customerConsent||!customerOrder}>Guardar identidad del cliente</button></fieldset></form></details>
 <details><summary>Revisar cobertura de vínculos</summary><p>Confirma únicamente después de conciliar todas las relaciones de la ventana mostrada. Cambiar los datos, identidades o permisos obliga a revisarla nuevamente.</p><form onSubmit={e=>{e.preventDefault();if(!coverageConsent)return;setCoverageApproved(false);void onSubmit({operation:'relationCoverage',scope:view.scope,expectedInputHash:view.inputHash,expectedVersion:view.coverage?.version??0,complete,report:coverageReport,attested:true});}}><fieldset disabled={busy}><legend>Cobertura documentada</legend><label style={{display:'flex',gap:'.5rem'}}><input style={{width:'auto'}} type="checkbox" checked={complete} onChange={e=>{setComplete(e.target.checked);setCoverageApproved(false);}}/>Confirmo que revisé todas las relaciones de esta ventana</label><Approval name="la cobertura de vínculos" report={coverageReport} approved={coverageConsent} onReport={setCoverageReport} onApproved={approve('coverage',setCoverageApproved)}/><button disabled={!coverageConsent}>Guardar revisión de cobertura</button></fieldset></form></details>
 </>}
 </section>;
}
