'use client';
import {EconomicSnapshotPanel} from './economic-snapshot-panel';
import {EconomicMoneyPanel} from './economic-money-panel';
import {formatMinorUnits as format} from '../../../../packages/metrics/money.mjs';
import {EconomicExposurePanel} from './economic-exposure-panel';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {EconomicView} from '../../../../packages/metrics/repository.mjs';
const kinds={order:'Orden registrada',refund:'Reembolso',reversal:'Reversión de reembolso',replacement:'Costo de reemplazo',support_model:'Soporte modelado',future_scenario:'Escenario futuro'};
const sources={order_export:'Exportación de órdenes',payment_ledger:'Registro de pagos',replacement_invoice:'Factura de reemplazo',support_timesheet:'Registro de tiempo de soporte',scenario_assumption:'Supuesto aprobado de escenario'};
const typeFor:Record<string,string>={order:'order_export',refund:'payment_ledger',reversal:'payment_ledger',replacement:'replacement_invoice',support_model:'support_timesheet',future_scenario:'scenario_assumption'};

export function EconomicPanel(){
 const generation=useRef(0),[data,setData]=useState<EconomicView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [fxRateId,setFxRateId]=useState('');
 const [start,setStart]=useState('2026-09-01'),[end,setEnd]=useState('2026-10-01'),[currency,setCurrency]=useState('USD'),[exponent,setExponent]=useState('2'),[basis,setBasis]=useState('net_order_excluding_tax_shipping');
 const [sourceId,setSourceId]=useState(''),[sourceName,setSourceName]=useState(''),[evidenceType,setEvidenceType]=useState('payment_ledger'),[complete,setComplete]=useState(false),[active,setActive]=useState(true),[sourceReport,setSourceReport]=useState(''),[sourceApproved,setSourceApproved]=useState(false);
 const [kind,setKind]=useState('refund'),[externalId,setExternalId]=useState(''),[effectiveAt,setEffectiveAt]=useState(''),[amount,setAmount]=useState(''),[status,setStatus]=useState('settled'),[orderId,setOrderId]=useState(''),[reversalOf,setReversalOf]=useState(''),[report,setReport]=useState(''),[attested,setAttested]=useState(false),[entrySource,setEntrySource]=useState('');
 const [duration,setDuration]=useState(''),[rate,setRate]=useState(''),[rateVersion,setRateVersion]=useState(''),[rateEvidence,setRateEvidence]=useState(''),[validFrom,setValidFrom]=useState(''),[validUntil,setValidUntil]=useState(''),[customers,setCustomers]=useState(''),[probability,setProbability]=useState(''),[revenue,setRevenue]=useState(''),[horizon,setHorizon]=useState('30'),[assumption,setAssumption]=useState(''),[assumptionReport,setAssumptionReport]=useState('');
 const clear=useCallback(()=>{setData(null);setBusy(false);setSourceId('');setSourceName('');setSourceReport('');setSourceApproved(false);setEntrySource('');setExternalId('');setAmount('');setOrderId('');setReversalOf('');setReport('');setAttested(false);setDuration('');setRate('');setRateVersion('');setRateEvidence('');setCustomers('');setProbability('');setRevenue('');setAssumption('');setAssumptionReport('');},[]);
 const request=useCallback(async(body?:unknown)=>{const epoch=++generation.current;setBusy(true);try{const query=new URLSearchParams({start:start+'T00:00:00.000Z',end:end+'T00:00:00.000Z',currency,exponent,basis,timezone:'UTC',...(fxRateId?{fxRateId}:{})});const r=await fetch('/api/economics'+(body?'':'?'+query),{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(epoch!==generation.current)return;if(r.status===401||r.status===403){generation.current++;clear();setError('Autorización revocada para el ledger.');return;}const json=await r.json();if(epoch!==generation.current)return;if(!r.ok)throw Error(r.status===409?'Conflicto de versión, identidad o fuente. Actualiza y revisa los registros.':r.status===400?'Revisa los campos, las fechas y las unidades monetarias.':'No se pudo consultar el ledger.');if(body){setAttested(false);setSourceApproved(false);const fresh=await fetch('/api/economics?'+query,{cache:'no-store'});if(epoch!==generation.current)return;if(fresh.status===401||fresh.status===403){generation.current++;clear();setError('Autorización revocada para el ledger.');return;}if(!fresh.ok)throw Error('El registro se guardó; no se pudo actualizar la consulta.');const latest=await fresh.json();if(epoch!==generation.current)return;setData(latest.data);}else setData(json.data);setError('');}catch(e){if(epoch===generation.current){clear();setError(e instanceof Error?e.message:'Error de ledger');}}finally{if(epoch===generation.current)setBusy(false);}},[start,end,currency,exponent,basis,fxRateId,clear]);
 const invalidate=useCallback(()=>{generation.current++;},[]);useEffect(()=>{void Promise.resolve().then(()=>request());return invalidate;},[request,invalidate]);
 const latestSource=data?.sources.find(x=>x.id===sourceId),selectedSource=data?.sources.find(x=>x.id===entrySource),old=data?.entries.find(x=>x.sourceId===entrySource&&x.externalId===externalId&&x.kind===kind);
 const modeled=kind==='support_model'||kind==='future_scenario';
 function submitEntry(){if(!selectedSource)return;const iso=(date:string)=>new Date(date+'Z').toISOString();const details=kind==='support_model'?{durationSeconds:duration||null,rateMinorPerMinute:rate||null,rateVersion,unit:'minute',validFrom:iso(validFrom),validUntil:iso(validUntil),rateEvidence,approved:true}:kind==='future_scenario'?{affectedCustomers:customers===''?null:Number(customers),relevantRevenueMinor:revenue||null,probabilityBps:probability===''?null:Number(probability),horizonDays:Number(horizon),assumptionId:assumption,assumptionReport,unit:'customer',validFrom:iso(validFrom),validUntil:iso(validUntil),approved:true}:{};void request({operation:'record',sourceId:entrySource,sourceVersion:selectedSource.version,expectedRevision:old?.revision??0,externalId,kind,effectiveAt:iso(effectiveAt),currency,exponent:Number(exponent),basis,amountMinor:modeled?null:amount.trim()||null,status:modeled?'modeled':status,orderId:orderId||null,reversalOf:kind==='reversal'?reversalOf:null,details,report,attested});}
 return <section aria-label="Ledger económico"><h2>Registro económico y componentes separados</h2><p>Consulta actual del ledger, sin publicar un snapshot. No suma exposición, devoluciones, costos y escenarios como pérdida o ahorro.</p><form onSubmit={e=>{e.preventDefault();void request();}}><label>Inicio de ventana UTC<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fin exclusivo UTC<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Moneda<input required maxLength={3} value={currency} onChange={e=>{setCurrency(e.target.value.toUpperCase());setFxRateId('');}}/></label><label>Decimales de la moneda<select value={exponent} onChange={e=>setExponent(e.target.value)}>{[0,1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>Base de cálculo<input required value={basis} onChange={e=>setBasis(e.target.value)}/></label><button disabled={busy}>Actualizar ledger</button></form>{error&&<p role="alert">{error}</p>}{fxRateId&&<button disabled={busy} onClick={()=>setFxRateId('')}>Mostrar monedas originales</button>}
 {data&&<EconomicSnapshotPanel scope={{start:start+'T00:00:00.000Z',end:end+'T00:00:00.000Z',currency,exponent:Number(exponent),basis,timezone:'UTC',dateBasis:'occurred_at'}} fxRateId={fxRateId||undefined}/>}{data&&<><p>{data.notice}</p><label>Conversión explícita<select value={fxRateId} disabled={busy} onChange={e=>setFxRateId(e.target.value)}><option value="">Sin conversión</option>{data.monetary.fxRates.filter(r=>r.valid&&r.base===currency).map(r=><option key={r.id} value={r.id}>{r.base} → {r.quote} · {r.rate} · {r.date} · v{r.version}</option>)}</select></label><EconomicMoneyPanel key={data.monetary.catalog.version+data.monetary.fxRates.map(r=>r.id).join(',')} view={data.monetary} canWrite={data.canWrite} busy={busy} onSubmit={request}/>{data.state==='empty'&&<p>No hay registros económicos autorizados. La ausencia no acredita cero.</p>}<div>{[['Órdenes registradas, no pérdida',data.bundle.metrics.allOrders],['Reembolsos netos liquidados',data.bundle.metrics.refunds],['Costos documentados de reemplazo',data.bundle.components.replacement],['Costo modelado de soporte',data.bundle.components.supportModel]].map(([name,m])=>{const metric=m as {amountMinor:string|null;knownSubtotalMinor:string|null;knownCount:number;totalCount:number;status:string;missingReasons:string[];currency:string;exponent:number};return <article key={String(name)}><h3>{String(name)}</h3><p>{format(metric.amountMinor,metric.currency,metric.exponent)} · {metric.status}</p><p>Subtotal conocido: {format(metric.knownSubtotalMinor,metric.currency,metric.exponent)} · Cobertura {metric.knownCount}/{metric.totalCount}</p><p>{metric.missingReasons.join(', ')}</p></article>;})}</div>
 {data.exposure&&<EconomicExposurePanel view={data.exposure} entries={data.entries} sources={data.sources} canWrite={data.canWrite} busy={busy} onSubmit={request}/>}
 <h3>Escenarios futuros, no pronósticos calibrados</h3>{data.bundle.components.futureScenarios.length===0?<p>Sin escenarios documentados; importe desconocido.</p>:data.bundle.components.futureScenarios.map((s:{id:string;amountMinor:string|null;currency:string;exponent:number;horizonDays:number;assumptions:string;start:string;end:string;missingReasons:string[]})=><article key={s.id}><p>{format(s.amountMinor,s.currency,s.exponent)} · Horizonte {s.horizonDays} días</p><p>Proyección UTC: {s.start} a {s.end}</p><p>{s.assumptions}</p>{s.missingReasons.includes('assumption_not_valid_as_of')&&<p>El supuesto no está vigente en la fecha de consulta; importe desconocido.</p>}</article>)}
 {data.bundle.issues.length>0&&<section aria-label="Conflictos económicos"><h3>Conflictos para conciliación</h3>{data.bundle.issues.map((i:{code:string;id?:string},n:number)=><p key={n}>{i.code} {i.id??''}</p>)}<p>No se recortan reversals ni se ocultan conflictos para cuadrar un total.</p></section>}
 {data.canWrite&&<><form onSubmit={e=>{e.preventDefault();void request({operation:'source',...(sourceId?{sourceId}:{}),expectedVersion:latestSource?.version??0,name:sourceName,evidenceType,active,complete,windowStart:start+'T00:00:00.000Z',windowEnd:end+'T00:00:00.000Z',watermark:new Date().toISOString(),report:sourceReport,attested:sourceApproved});}}><fieldset disabled={busy}><legend>Registrar o versionar una fuente operacional</legend><label>Fuente para actualizar<select value={sourceId} onChange={e=>{const s=data.sources.find(x=>x.id===e.target.value);setSourceId(e.target.value);setSourceName(s?.name??'');setEvidenceType(s?.evidenceType??'payment_ledger');setActive(s?.active??true);setComplete(s?.complete??false);setSourceApproved(false);}}><option value="">Nueva fuente</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.name} · v{s.version}</option>)}</select></label><label>Nombre de fuente<input required value={sourceName} onChange={e=>setSourceName(e.target.value)}/></label><label>Tipo de evidencia<select value={evidenceType} disabled={!!sourceId} onChange={e=>setEvidenceType(e.target.value)}>{Object.entries(sources).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Documento, responsable y alcance revisados<textarea required minLength={20} value={sourceReport} onChange={e=>{setSourceReport(e.target.value);setSourceApproved(false);}}/></label><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Fuente activa y autorizada</label><label><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/>Verifiqué completitud de esta familia en la ventana indicada</label><label><input type="checkbox" checked={sourceApproved} onChange={e=>setSourceApproved(e.target.checked)}/>Apruebo la evidencia operacional. El relato de un ticket no acredita un pago.</label><button disabled={!sourceApproved}>Guardar fuente</button></fieldset></form>
 <form onSubmit={e=>{e.preventDefault();submitEntry();}}><fieldset disabled={busy}><legend>Aportar o corregir un registro económico</legend><label>Componente<select value={kind} onChange={e=>{setKind(e.target.value);setEntrySource('');setStatus(e.target.value==='order'?'recorded':'settled');setAttested(false);}}>{Object.entries(kinds).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Fuente documentada<select required value={entrySource} onChange={e=>setEntrySource(e.target.value)}><option value="">Selecciona una fuente activa</option>{data.sources.filter(s=>s.active&&s.evidenceType===typeFor[kind]).map(s=><option key={s.id} value={s.id}>{s.name} · v{s.version}</option>)}</select></label><label>Identificador del registro en la fuente<input required value={externalId} onChange={e=>setExternalId(e.target.value)}/></label>{old&&<p>Nueva revisión de {old.id}, versión actual {old.revision}. Se conserva el historial.</p>}<label>Fecha efectiva UTC<input type="datetime-local" required value={effectiveAt} onChange={e=>setEffectiveAt(e.target.value)}/></label>{!modeled&&<><label>Importe en unidades menores, vacío si desconocido<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><p>Con {exponent} decimales, 1500 significa {format('1500',currency,Number(exponent))}. Una reversión usa signo negativo.</p><label>Estado financiero<select value={status} onChange={e=>setStatus(e.target.value)}><option value={kind==='order'?'recorded':'settled'}>{kind==='order'?'Registrado':'Liquidado'}</option><option value="pending">Pendiente</option><option value="cancelled">Cancelado</option><option value="unknown">Desconocido</option></select></label></>}
 <label>Orden relacionada, opcional<select value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Sin relación acreditada</option>{data.entries.filter(x=>x.kind==='order').map(x=><option key={x.id} value={x.id}>{x.externalId}</option>)}</select></label>{kind==='reversal'&&<label>ID del reembolso original<input required value={reversalOf} onChange={e=>setReversalOf(e.target.value)} list="refund-identities"/><datalist id="refund-identities">{data.entries.filter(x=>x.kind==='refund').map(x=><option key={x.id} value={x.id}>{x.externalId}</option>)}</datalist></label>}
 {modeled&&<><label>Vigencia desde UTC<input required type="datetime-local" value={validFrom} onChange={e=>setValidFrom(e.target.value)}/></label><label>Vigencia hasta UTC<input required type="datetime-local" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label></>}
 {kind==='support_model'&&<><label>Duración observada en segundos, vacío si falta<input value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Tarifa aprobada en unidades menores por minuto, vacío si falta<input value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Versión de tarifa<input required value={rateVersion} onChange={e=>setRateVersion(e.target.value)}/></label><label>Evidencia y aprobación de tarifa<textarea required value={rateEvidence} onChange={e=>setRateEvidence(e.target.value)}/></label></>}
 {kind==='future_scenario'&&<><label>Clientes afectados conocidos, vacío si desconocido<input value={customers} onChange={e=>setCustomers(e.target.value)}/></label><label>Ingreso relevante por cliente, unidades menores<input value={revenue} onChange={e=>setRevenue(e.target.value)}/></label><label>Probabilidad del supuesto, puntos básicos (0 a 10000)<input value={probability} onChange={e=>setProbability(e.target.value)}/></label><label>Horizonte en días<input required value={horizon} onChange={e=>setHorizon(e.target.value)}/></label><label>Identificador del supuesto<input required value={assumption} onChange={e=>setAssumption(e.target.value)}/></label><label>Hipótesis y límites del escenario<textarea required value={assumptionReport} onChange={e=>setAssumptionReport(e.target.value)}/></label></>}
 <label>Evidencia operacional del registro<textarea required minLength={20} value={report} onChange={e=>{setReport(e.target.value);setAttested(false);}}/></label><label><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>Revisé la fuente y apruebo el registro y sus supuestos. No procede de una inferencia del modelo.</label><button disabled={!attested||!entrySource}>Guardar registro económico</button></fieldset></form></>}
 <details><summary>Ledger e historial inmutable</summary>{data.history.map(e=><article key={e.rowId}><h4>{e.externalId} · {e.kind} · revisión {e.revision}</h4><p>{format(e.amountMinor,e.currency,e.exponent)} · {e.status} · {e.effectiveAt}</p><p>ID {e.id} · Actor {e.actorId}</p><p>{e.report}</p></article>)}</details></>}
 </section>;
}
