'use client';
import {EconomicPriorityPanel} from './economic-priority-panel';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {EconomicScope} from '../../../../packages/metrics/repository.mjs';
import type {SnapshotView} from '../../../../packages/metrics/snapshots.mjs';
export function EconomicSnapshotPanel({scope,fxRateId}:{scope:EconomicScope;fxRateId?:string}){const [published,setPublished]=useState<SnapshotView|null>(null),[draft,setDraft]=useState<SnapshotView|null>(null),[canPublish,setCanPublish]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);const selectionKey=JSON.stringify({scope,...(fxRateId?{fxRateId}:{})});const clear=useCallback(()=>{setPublished(null);setDraft(null);setCanPublish(false);},[]);
 const request=useCallback(async(body?:unknown)=>{const epoch=++generation.current;setBusy(true);const selection=JSON.parse(selectionKey) as {scope:EconomicScope;fxRateId?:string};try{const query=new URLSearchParams({...selection.scope,exponent:String(selection.scope.exponent),...(selection.fxRateId?{fxRateId:selection.fxRateId}:{})});query.delete('dateBasis');const response=await fetch('/api/economic-snapshots'+(body?'':'?'+query),{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(epoch!==generation.current)return;if(response.status===401||response.status===403){generation.current++;clear();setBusy(false);setError('Autorización revocada para snapshots.');return;}const json=await response.json();if(epoch!==generation.current)return;if(!response.ok)throw Error(response.status===409?'Las fuentes o el snapshot cambiaron. Actualiza y vuelve a preparar.':'No se pudo completar la operación del snapshot.');if(body){if(json.data.status==='published'){setPublished(json.data);setDraft(null);}else setDraft(json.data);}else{setPublished(json.data.snapshot);setCanPublish(json.data.canPublish);setDraft(null);}setError('');}catch(e){if(epoch===generation.current){clear();setError(e instanceof Error?e.message:'Error de snapshot');}}finally{if(epoch===generation.current)setBusy(false);}},[selectionKey,clear]);
 const invalidate=useCallback(()=>{generation.current++;},[]);useEffect(()=>{void Promise.resolve().then(()=>{clear();return request();});return invalidate;},[request,clear,invalidate]);
 return <section aria-label="Snapshots publicados"><h2>Snapshots publicados</h2><p>Una publicación conserva sus cifras, alcance y versiones. Los valores desconocidos y la cobertura parcial permanecen explícitos.</p><button disabled={busy} onClick={()=>void request()}>Actualizar snapshots</button>{canPublish&&<button disabled={busy} onClick={()=>void request({operation:'stage',...JSON.parse(selectionKey)})}>Preparar snapshot</button>}{error&&<p role="alert">{error}</p>}{draft&&<article><h3>Preparación pendiente de publicación</h3><p>Snapshot preparado: {draft.id}</p><p>{draft.scope.start} → {draft.scope.end} · {draft.scope.currency} · {draft.scope.timezone} · Corte {draft.asOf}</p><p>{draft.components.length} componentes; las cantidades desconocidas no se convierten en cero.</p><button disabled={busy||!canPublish} onClick={()=>void request({operation:'publish',snapshotId:draft.id,expectedContentHash:draft.contentHash})}>Publicar snapshot</button></article>}{!published&&<p>No hay un snapshot publicado para este alcance.</p>}{published&&<article data-snapshot-id={published.id} data-scope-hash={published.scopeHash}><h3>Snapshot publicado</h3><p>Snapshot: {published.id}</p><p>{published.scope.start} → {published.scope.end} · {published.scope.currency} · {published.scope.timezone} · Base {published.scope.basis}</p><p>Corte: {published.asOf} · Marca de fuente: {published.watermark??'Sin fuentes'} · Publicado: {published.publishedAt}</p><p>Clientes expuestos: {published.exposure.customerExposure.global.count??'Desconocido'} · Clientes conocidos: {published.exposure.customerExposure.global.knownCount} · {published.exposure.customerExposure.global.status}. Las filas por problema no son aditivas.</p><p>Versión: {published.versions.schema} · Integridad: {published.contentHash}</p><a download={'snapshot-'+published.id+'.json'} href={'/api/economic-snapshots/'+published.id+'/export?format=json&scopeHash='+published.scopeHash}>Descargar JSON</a>{' '}<a download={'snapshot-'+published.id+'.csv'} href={'/api/economic-snapshots/'+published.id+'/export?format=csv&scopeHash='+published.scopeHash}>Descargar CSV</a><EconomicPriorityPanel key={published.id} snapshotId={published.id}/>{published.components.map(c=><div key={c.id}><h4>{c.label}</h4><p>{c.display}</p><p>{c.money?.missing_reasons.join(', ')}</p></div>)}</article>}</section>;
}
