 'use client';
import {useEffect,useState} from 'react';
export function EmailLoginComplete(){const [organizations,setOrganizations]=useState<{id:string;name:string}[]|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');
useEffect(()=>{let active=true;const fragment=new URLSearchParams(location.hash.slice(1));history.replaceState(null,'',location.pathname);const accessToken=fragment.get('access_token'),refreshToken=fragment.get('refresh_token');async function establish(){try{if(!accessToken||!refreshToken||fragment.has('error'))throw new Error();const response=await fetch('/auth/email/session',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({accessToken,refreshToken})});const result=await response.json();if(!response.ok)throw new Error();if(active){setOrganizations(result.organizations);setSelected(result.organizations[0]?.id??'');}}catch{if(active)setError('El enlace no es válido o ya no puede usarse. Solicita un nuevo acceso desde el formulario de correo.');}finally{if(active)setBusy(false);}}void establish();return()=>{active=false;};},[]);
async function enter(){if(busy||!selected)return;setBusy(true);setError('');try{const form=new FormData();form.set('tenant_id',selected);const response=await fetch('/auth/organization',{method:'POST',signal:AbortSignal.timeout(15000),body:form});if(!response.ok||new URL(response.url).pathname!=='/')throw new Error();
// eslint-disable-next-line @next/next/no-location-assign-relative-destination -- New Auth and tenant cookies require discarding the pre-login Router cache.
window.location.assign('/');
}catch{setOrganizations(null);setSelected('');setError('El acceso al equipo cambió o la sesión no está disponible. Vuelve a iniciar sesión.');setBusy(false);}}
return <section className="home" aria-busy={busy}><h1>Acceso por correo</h1>{busy&&<p role="status">Validando sesión…</p>}{error&&<p role="alert">{error}</p>}{organizations&&organizations.length>0&&<><label htmlFor="email-login-organization">Organización</label><select id="email-login-organization" value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}>{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select><button disabled={busy} onClick={enter}>Entrar al equipo</button></>}{organizations?.length===0&&<p>Sesión iniciada. No tienes acceso a un equipo activo. Si recibiste una invitación pendiente, abre su enlace para aceptarla.</p>}<a href="/login">Volver a iniciar sesión</a></section>;}
