'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
type Job={id:string;runId:string|null;conversationId:string;state:string;runStatus:string|null;reason:string|null};
type Reservation={id:string;state:string;version:number;actualMinor:string|null;heldMinor:string;reportedMinor:string};
type Snapshot={jobs:Job[];conversations:{id:string;source:string}[];canSubmit:boolean;canConfigure:boolean;configuration:{ready:boolean;enabled:boolean;window:string|null};limits:{purpose:string;limit_minor:string;version:number}[];reservations:Reservation[]};
const stateLabels:Record<string,string>={queued:'En cola',running:'Analizando',succeeded:'Terminado',failed:'Requiere atención',cancelled:'Cancelado'};
const reasons:Record<string,string>={reconciliation_required:'La ejecución fue interrumpida. Revisa el consumo con el proveedor antes de solicitar otro análisis.',runtime_disabled:'La conexión con el proveedor de IA está desactivada.',configuration_changed:'La configuración cambió. Revisa los límites antes de crear otra solicitud.',budget_exceeded:'No hay saldo disponible en los límites de esta ventana.',ambiguous:'El contenido no permite una clasificación fiable.',invalid_output:'La respuesta del proveedor quedó en cuarentena.',policy_blocked:'La política del proveedor o su catálogo necesitan revisión.'};
function usd(minor:string){const value=BigInt(minor);return `${value/1000000n}.${String(value%1000000n).padStart(6,'0')}`;}
export function ExtractionPanel(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[limit,setLimit]=useState(''),[purpose,setPurpose]=useState('extraction'),[reservation,setReservation]=useState(''),[actual,setActual]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false);
 const requestKey=useRef<string|null>(null),refreshGeneration=useRef(0);
 const reload=useCallback(async(signal?:AbortSignal)=>{
  const generation=++refreshGeneration.current;
  try{
   const response=await fetch('/api/extraction',{cache:'no-store',signal}),body=await response.json();
   if(!response.ok)throw Error(body.error?.code==='configuration_required'?'Falta configurar el servicio de análisis.':'No se pudo consultar el análisis.');
   if(!signal?.aborted&&generation===refreshGeneration.current){setSnapshot(body);setError('');}
  }catch(e){
   if(signal?.aborted||generation!==refreshGeneration.current)return;
   setSnapshot(null);throw e;
  }
 },[]);
 useEffect(()=>{const controller=new AbortController();const update=()=>reload(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);});void update();const timer=setInterval(update,10000);return()=>{controller.abort();clearInterval(timer);};},[reload]);
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/extraction',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){if(response.status===401||response.status===403){++refreshGeneration.current;setSnapshot(null);}const value=await response.json();throw Error(response.status===409?'La configuración cambió o la solicitud entró en conflicto. Actualiza y vuelve a revisar.':value.error?.code==='role_insufficient'?'Esta acción requiere un propietario.':'No se pudo completar la acción.');}if(body.action==='submit')requestKey.current=null;if(body.action==='reconcile'){setConfirmed(false);setEvidence('');setActual('');}await reload();}catch(e){setError(e instanceof Error?e.message:'No se pudo completar la acción.');}finally{setBusy(false);}}
 return <section aria-labelledby="analysis-title"><h1 id="analysis-title">Análisis de conversaciones</h1><p>Los análisis se ejecutan en segundo plano. Los importes inciertos permanecen reservados hasta contrastarlos con el proveedor.</p>{error&&<p role="alert">{error}</p>}{!snapshot?<p>Cargando estado…</p>:<>
 {!snapshot.configuration.ready&&<p role="status">Falta configurar la política de privacidad, el catálogo y los modelos del proveedor.</p>}{snapshot.configuration.ready&&!snapshot.configuration.enabled&&<p role="status">El proveedor de IA está desactivado. Actívalo sólo después de autorizar la política y el consumo.</p>}
 {snapshot.canSubmit&&<form onSubmit={event=>{event.preventDefault();requestKey.current??=crypto.randomUUID();void action({action:'submit',conversationId:selected,requestKey:requestKey.current});}}><label>Conversación<select aria-label="Conversación" value={selected} onChange={event=>{setSelected(event.target.value);requestKey.current=null;}}><option value="">Selecciona una conversación</option>{snapshot.conversations.map(c=><option key={c.id} value={c.id}>{c.source} · {c.id}</option>)}</select></label><button disabled={busy||!selected||!snapshot.configuration.ready||!snapshot.configuration.enabled}>Solicitar análisis</button></form>}
 <h2>Trabajos</h2>{snapshot.jobs.length===0?<p>Aún no hay análisis solicitados.</p>:<ul>{snapshot.jobs.map(job=><li key={job.id}><strong>{stateLabels[job.state]??job.state}</strong> · {job.conversationId}{job.runStatus==='abstained'&&<span> · Sin clasificación concluyente</span>}{job.runId&&['succeeded','abstained'].includes(job.runStatus??'')&&<p><Link href={'/analysis/'+job.runId}>Ver evidencia</Link></p>}{job.reason&&<p>{reasons[job.reason]??'Revisa la configuración y el registro de la ejecución.'}</p>}{['queued','running'].includes(job.state)&&<button disabled={busy} onClick={()=>void action({action:'cancel',jobId:job.id})}>Cancelar análisis</button>}</li>)}</ul>}
 {snapshot.canConfigure&&snapshot.configuration.ready&&<><h2>Límites de consumo</h2><p>Ventana: {snapshot.configuration.window}. Deben existir un límite global y otro de extracción. Importes en USD.</p><ul>{snapshot.limits.map(item=><li key={item.purpose}>{item.purpose==='all'?'Global':'Extracción'}: ${usd(item.limit_minor)}</li>)}</ul><form onSubmit={event=>{event.preventDefault();const current=snapshot.limits.find(item=>item.purpose===purpose);void action({action:'budget',purpose,limitUsd:limit,...(current?{expectedVersion:current.version}:{})});}}><label>Tipo de límite<select aria-label="Tipo de límite" value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="extraction">Extracción</option><option value="all">Global</option></select></label><label>Límite en USD<input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,6})?" value={limit} onChange={e=>setLimit(e.target.value)}/></label><button disabled={busy}>Guardar límite</button></form>
 <h2>Reservas pendientes de conciliación</h2><ul>{snapshot.reservations.filter(r=>['reserved','uncertain'].includes(r.state)).map(r=><li key={r.id}>{r.id} · Reservado: ${usd(r.heldMinor)} · Reportado: ${usd(r.reportedMinor)} · Costo final: {r.actualMinor===null?'desconocido':`$${usd(r.actualMinor)}`}</li>)}</ul>
 <form onSubmit={event=>{event.preventDefault();const row=snapshot.reservations.find(r=>r.id===reservation);if(row)void action({action:'reconcile',reservationId:row.id,expectedVersion:row.version,actualUsd:actual,evidenceHash:evidence,confirmedProviderEvidence:confirmed});}}><label>Reserva<select aria-label="Reserva" required value={reservation} onChange={e=>{setReservation(e.target.value);setConfirmed(false);}}><option value="">Selecciona una reserva</option>{snapshot.reservations.filter(r=>['reserved','uncertain'].includes(r.state)).map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label><label>Costo confirmado en USD<input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,6})?" value={actual} onChange={e=>setActual(e.target.value)}/></label><label>Huella SHA-256 del recibo del proveedor<input required pattern="[a-f0-9]{64}" value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Contrasté este costo con evidencia del proveedor.</label><button disabled={busy||!confirmed||!reservation}>Conciliar costo</button></form></>}
 </>}</section>;
}
