'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
export const historyStates:Record<string,string>={active:'En curso',paused:'Pausado',cancelled:'Cancelado',completed:'Completado',pending:'Pendiente',extracting:'Analizando',grouping:'Agrupando',skipped:'Omitido',failed:'Requiere atención'};
export const historyReasons:Record<string,string>={authorization_revoked:'La autorización del owner o de la conexión ya no está vigente.',runtime_disabled:'El servicio requiere habilitación explícita.',configuration_changed:'La configuración cambió. Revisa el lote antes de reautorizar.',extraction_abstained:'El análisis se abstuvo por falta de evidencia suficiente.',extraction_failed:'El análisis no terminó. Consulta su trabajo antes de solicitar otro lote.',grouping_failed:'La agrupación no terminó. Revisa su trabajo y el presupuesto.',source_unavailable:'La fuente ya no está disponible para este análisis.'};
type Item={conversationId:string;state:string;reason:string|null;extractionJob:string|null;embeddingJob:string|null;runId:string|null};
export function HistoryItems({batchId}:{batchId:string}){const [cursors,setCursors]=useState<Array<string|null>>([null]),[data,setData]=useState<{items:Item[];nextCursor:string|null}|null>(null),[error,setError]=useState('');const cursor=cursors.at(-1)??null,epoch=useRef(0);
 useEffect(()=>{const controller=new AbortController(),generation=++epoch.current;void(async()=>{try{const response=await fetch('/api/history?'+new URLSearchParams({batch:batchId,...(cursor?{cursor}:{})}),{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error('No se pudo consultar esta página del lote.');const result=await response.json();if(!controller.signal.aborted&&generation===epoch.current){setData(result);setError('');}}catch{if(!controller.signal.aborted&&generation===epoch.current){setData(null);setError('No se pudo consultar esta página del lote. Intenta abrirla de nuevo.');}}})();return()=>controller.abort();},[batchId,cursor]);
 function move(next:boolean){setData(null);setError('');setCursors(previous=>next&&data?.nextCursor?[...previous,data.nextCursor]:previous.slice(0,-1));}
 return <section aria-label="Conversaciones del lote" aria-busy={!data&&!error}><h3>Conversaciones del lote</h3><p>Página {cursors.length}</p>{error&&<p role="alert">{error}</p>}{data?<ul>{data.items.map(item=><li key={item.conversationId}>Conversación {item.conversationId}: {historyStates[item.state]??item.state}{item.reason&&<p>{historyReasons[item.reason]??'Requiere revisión.'}</p>}{item.runId&&<p><Link href={'/analysis/'+item.runId}>Ver análisis de {item.conversationId}</Link></p>}{item.extractionJob&&<p>Trabajo de análisis: {item.extractionJob}</p>}{item.embeddingJob&&<p>Trabajo de agrupación: {item.embeddingJob} · <Link href="/problems/manage">Revisar agrupación y consumo</Link></p>}</li>)}</ul>:!error&&<p role="status">Cargando conversaciones…</p>}<button disabled={!data||cursors.length===1} onClick={()=>move(false)}>Conversaciones anteriores del lote</button><button disabled={!data?.nextCursor} onClick={()=>move(true)}>Conversaciones siguientes del lote</button></section>;
}
