'use client';
import {ConfirmationDialog} from './confirmation-dialog';
import {HistoryItems,historyStates,historyReasons} from './history-items';
import {useCallback,useEffect,useRef,useState} from 'react';
type Batch={id:string;connectionId:string;state:string;reason:string|null;version:number;enumerated:boolean;counts:Record<string,number>};
type Snapshot={batches:Batch[];connections:Array<{id:string;source:string;account_id:string}>;configuration:{ready:boolean;enabled:boolean}};
export function HistoryPanel(){const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[connection,setConnection]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[selectedBatch,setSelectedBatch]=useState<string|null>(null);const epoch=useRef(0),requestKey=useRef<string|null>(null),pending=useRef(false);
 const load=useCallback(async(signal?:AbortSignal)=>{const generation=++epoch.current;let failure='No se pudo consultar el histórico. Intenta actualizar de nuevo.';setLoading(true);try{const r=await fetch('/api/history',{cache:'no-store',signal});if(!r.ok){failure=r.status===403?'Esta operación requiere el rol owner.':'No se pudo consultar el histórico.';throw Error('HISTORY_LOAD_FAILED');}const value=await r.json();if(generation===epoch.current&&!signal?.aborted){setSnapshot(value);setError('');}}catch{if(!signal?.aborted&&generation===epoch.current){setSnapshot(null);setSelectedBatch(null);setConfirmed(false);setError(failure);}}finally{if(!signal?.aborted&&generation===epoch.current)setLoading(false);}},[]);
 const invalidate=useCallback(()=>{epoch.current++;},[]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal));const timer=setInterval(()=>{if(!pending.current)void load(controller.signal);},5000);return()=>{controller.abort();clearInterval(timer);invalidate();};},[load,invalidate]);
 async function action(body:Record<string,unknown>){if(pending.current)return;pending.current=true;setBusy(true);setError('');let failure='No se pudo modificar el lote. Actualiza su estado antes de volver a intentar.';try{const r=await fetch('/api/history',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){failure=r.status===409?'El lote cambió. Revisa su estado antes de continuar.':r.status===403?'La autorización ya no está vigente.':'No se pudo modificar el lote.';throw Error('HISTORY_ACTION_FAILED');}requestKey.current=null;setConfirmed(false);await load();}catch{await load();setConfirmed(false);setError(failure);}finally{pending.current=false;setBusy(false);}}
 return <section aria-label="Histórico de conversaciones" aria-busy={loading||busy}><h1>Procesar histórico</h1><p>Un owner puede autorizar el análisis y la agrupación de conversaciones canónicas de una conexión. El trabajo continúa en segundo plano al cerrar esta página y respeta las políticas y presupuestos configurados. No publica snapshots.</p>{loading&&<p role="status">{snapshot?'Actualizando histórico…':'Cargando histórico…'}</p>}{error&&<p role="alert">{error}</p>}<button disabled={busy||loading} onClick={()=>void load()}>Actualizar histórico</button>{snapshot&&<><p>{snapshot.configuration.ready&&snapshot.configuration.enabled?'Servicio autorizado y configurado.':'Falta configuración o habilitación explícita del servicio.'}</p><form onSubmit={e=>{e.preventDefault();if(!confirmed)return;requestKey.current??=crypto.randomUUID();void action({operation:'start',connectionId:connection,requestKey:requestKey.current,confirmed:true});}}><label>Conexión del histórico<select aria-label="Conexión del histórico" required disabled={busy} value={connection} onChange={e=>{setConnection(e.target.value);setConfirmed(false);requestKey.current=null;}}><option value="">Selecciona una conexión</option>{snapshot.connections.map(c=><option key={c.id} value={c.id}>{c.source} · {c.account_id}</option>)}</select></label><label><input type="checkbox" disabled={busy||!connection} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Autorizo el análisis y la agrupación de este histórico con los límites configurados.</label><button disabled={busy||!confirmed||!connection||!snapshot.configuration.ready||!snapshot.configuration.enabled}>Autorizar lote histórico</button></form><section aria-label="Lotes históricos">{snapshot.batches.map(b=><article key={b.id}><h2>Lote {b.id}</h2><p>Estado: {historyStates[b.state]??b.state} · {b.enumerated?'Selección completa':'Selección en curso'}</p>{b.reason&&<p>{historyReasons[b.reason]??'Requiere revisión.'}</p>}<ul>{Object.entries(b.counts).map(([state,n])=><li key={state}>{historyStates[state]??state}: {n}</li>)}</ul>{b.state==='cancelled'&&<p>Los trabajos pendientes quedan sin autorización para continuar.</p>}<button onClick={()=>setSelectedBatch(selectedBatch===b.id?null:b.id)}>Ver conversaciones del lote {b.id}</button>{selectedBatch===b.id&&<HistoryItems key={b.id} batchId={b.id}/>} {['active','paused'].includes(b.state)&&<button disabled={busy} onClick={()=>void action({operation:'cancel',batchId:b.id,expectedVersion:b.version})}>Cancelar lote {b.id}</button>}{b.state==='paused'&&<ConfirmationDialog triggerLabel={'Reautorizar lote '+b.id} title="¿Reautorizar este lote?" description={'El lote '+b.id+' continuará con su configuración original y los límites autorizados. Esta acción renueva su autorización.'} confirmLabel="Reautorizar lote" disabled={busy} onConfirm={()=>action({operation:'resume',batchId:b.id,expectedVersion:b.version,confirmed:true})}/>}</article>)}</section></>}</section>;
}
