'use client';
import {ScrollTable} from './workspace/scroll-table';
import {useEffect,useState,useRef} from 'react';
import type {Mapping,Preview} from '../../../../packages/ingestion/mapping.mjs';
type Reservation={id:string;state:string;mapping_version:string};
type Detail={import:Reservation&{file_hash:string;expires_at:string;content_type?:string;job_id?:string};mapping:Mapping|null;headers?:string[];sheets?:string[];preview?:Preview;preview_state:string;upload_token?:string};
const initial:Mapping={columns:{id:'',text:''},timezone:'',dateFormat:'iso',currency:null};
async function api(route:string,body?:unknown,key?:string,signal?:AbortSignal){const r=await fetch('/api/imports'+route,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body),signal}).catch(()=>{throw new Error('No se pudo recibir la respuesta. Revisa el estado antes de repetir la operación.');});const j=await r.json();if(!r.ok)throw new Error(`${r.status}: ${j.error?.code??'imports_unavailable'}. ${j.error?.message??''}`);return j.data;}
export function ImportPreview(){
 const [connections,setConnections]=useState<{id:string;source:string;account_id:string}[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[connection,setConnection]=useState(''),[file,setFile]=useState<File|null>(null),[detail,setDetail]=useState<Detail|null>(null),[mapping,setMapping]=useState<Mapping>(initial),[preview,setPreview]=useState<Preview|null>(null),[headers,setHeaders]=useState<string[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[approved,setApproved]=useState(false);
 const [sheets,setSheets]=useState<string[]>([]),[nextOffset,setNextOffset]=useState<number|null>(null),[nextConnectionOffset,setNextConnectionOffset]=useState<number|null>(null);
 const [canConfigure,setCanConfigure]=useState(false),[connectionName,setConnectionName]=useState('');
 const retry=useRef<{fingerprint:string;key:string;id?:string}|null>(null);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){const message=e instanceof Error?e.message:'Error de importación';setError(message);if(/mapping_version_conflict|confirmation_conflict|upload_capability_invalid|reservation_expired/.test(message))setApproved(false);}finally{setBusy(false);}}
 async function list(offset=0,connectionOffset=0,append=false){const data=await api(`?offset=${offset}&connection_offset=${connectionOffset}`);setCanConfigure(data.canConfigure===true);setConnections(previous=>append?Array.from(new Map([...previous,...data.connections].map(c=>[c.id,c])).values()):data.connections);if(!append&&!data.connections.some((item:{id:string})=>item.id===connection))setConnection('');setReservations(previous=>append?Array.from(new Map([...previous,...data.reservations].map(r=>[r.id,r])).values()):data.reservations);if(!append||offset>0)setNextOffset(data.next_offset);if(!append||connectionOffset>0)setNextConnectionOffset(data.next_connection_offset);}
 useEffect(()=>{
  const controller=new AbortController();
  async function initialize(){
   try{
    const data=await api('?offset=0&connection_offset=0',undefined,undefined,controller.signal);
    if(controller.signal.aborted)return;
    setCanConfigure(data.canConfigure===true);setConnections(data.connections);setReservations(data.reservations);
    setNextOffset(data.next_offset);setNextConnectionOffset(data.next_connection_offset);
   }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Error de importación');}
   finally{if(!controller.signal.aborted)setBusy(false);}
  }
  void initialize();
  return()=>controller.abort();
 },[]);
 async function createConnection(){const data=await api('/connections',{account_id:connectionName});await list();setConnections(previous=>previous.some(c=>c.id===data.connection.id)?previous:[...previous,data.connection]);setConnection(data.connection.id);setConnectionName('');setNotice(data.created?'Conexión CSV creada. Selecciona el archivo para importarlo.':'Conexión CSV existente seleccionada.');}
 async function load(id:string,sheet?:string){const d:Detail=await api('/'+id+(sheet?'?sheet='+encodeURIComponent(sheet):''));setDetail(d);setMapping(sheet?{...initial,sheet}:d.mapping??{...initial,sheet:d.sheets?.length===1?d.sheets[0]:null});setPreview(d.preview??null);setHeaders(d.preview?.headers??d.headers??[]);setSheets(d.preview?.sheets??d.sheets??[]);setApproved(Boolean(!sheet&&d.mapping&&d.upload_token&&new Date(d.import.expires_at)>new Date()));setNotice(d.preview_state==='awaiting_upload'?'Carga pendiente. Reintenta con el mismo archivo.':d.preview_state==='sheet_required'?'Selecciona una hoja del archivo.':d.import.state==='queued'?'En cola. La importación todavía no está procesada.':'Configura y valida las columnas.');}
 function change(next:Mapping){setMapping(next);setApproved(false);setPreview(null);}
 function changeProfile(value:string){
  if(value==='history-message-v1'){
   if(detail?.import.content_type!=='text/csv')return;
   change({...mapping,profile:'history-message-v1',dateFormat:'iso'});
  }else if(value===''){
   const next={...mapping};delete next.profile;change(next);
  }
 }
 function checkProfile(){
  if(!mapping.profile)return;
  if(detail?.import.content_type!=='text/csv')throw Error('El modo histórico requiere un archivo confirmado como CSV. Recarga la reserva.');
  if(mapping.dateFormat!=='iso'||(['id','text','date','role','conversation'] as const).some(k=>!mapping.columns[k]))throw Error('Para el modo histórico, selecciona las columnas de ID, texto, fecha, rol y conversación, con formato de fecha ISO.');
 }
 async function upload(){if(!file||!connection)throw Error('Selecciona conexión y archivo.');if(file.size<1||file.size>20*1024*1024)throw Error('El archivo debe tener entre 1 byte y 20 MiB.');const bytes=await file.arrayBuffer(),sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');const type=file.name.toLowerCase().endsWith('.xlsx')?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv';const fingerprint=JSON.stringify([connection,sha,type]);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};const attempt=retry.current!;
 try{if(attempt.id){const existing:Detail=await api('/'+attempt.id);if(existing.import.state==='reserved'&&new Date(existing.import.expires_at)<=new Date())throw Error('reservation_expired');if(existing.preview_state!=='awaiting_upload'){await load(attempt.id);await list();return;}}
 const d=await api('',{connection_id:connection,mapping_version:'interactive-unmapped-v1',content_type:type,size:file.size,sha256:sha},attempt.key);attempt.id=d.import_id;setNotice('Reserva creada. Subiendo directamente a Storage…');const r=await fetch(d.upload_url,{method:'PUT',headers:{'Content-Type':type},body:bytes}).catch(()=>{throw new Error('No se pudo confirmar la subida. Reintenta con el mismo archivo; todavía no se ha confirmado ningún job.');});if(!r.ok)throw Error('No se pudo subir el objeto. Reintenta con el mismo archivo; no se ha confirmado ningún job.');await load(d.import_id);await list();}catch(e){if(e instanceof Error&&e.message.includes('reservation_expired'))retry.current=null;throw e;}}
 async function validate(){if(!detail)return;checkProfile();const p:Preview=await api('/'+detail.import.id+'/preview',{mapping});setPreview(p);setHeaders(p.headers);setNotice('Validación de todas las filas; la muestra no es representativa.');}
 async function save(){if(!detail)return;checkProfile();const p=await api('/'+detail.import.id+'/mapping',{mapping,expected_version:detail.import.mapping_version});setPreview(p);setDetail({...detail,mapping,upload_token:p.upload_token,import:{...detail.import,mapping_version:p.mapping_version}});setApproved(true);setNotice('Configuración confirmada y guardada. Puedes enviar la importación a la cola.');}
 async function confirm(){if(!detail||!approved)return;const d=await api('/'+detail.import.id+'/confirm',{upload_token:detail.upload_token,sha256:detail.import.file_hash,mapping_version:detail.import.mapping_version});setApproved(false);setNotice(d.state==='queued'?'En cola; no significa procesamiento completado.':d.state);await load(detail.import.id);await list();}
 return <section aria-labelledby="imports-heading"><h1 id="imports-heading">Importaciones CSV / Excel</h1><p>Archivos hasta 20 MiB. Declara zona horaria, formato y moneda. La validación no equivale a ingestión completada.</p>
 {error&&<p role="alert">{error} Si hay conflicto, recarga la reserva antes de guardar. Las reservas caducadas requieren una nueva importación.</p>}<p role="status" aria-live="polite">{busy?'Procesando…':notice}</p>
 <button disabled={busy} onClick={()=>void run(()=>list())}>Recargar reservas / reintentar</button>
 {canConfigure&&<form onSubmit={event=>{event.preventDefault();void run(createConnection);}}><fieldset disabled={busy}><legend>Nueva conexión CSV</legend><p>Usa un nombre para identificar el origen de estos archivos. Conserva una conexión diferente para cada origen.</p><label>Nombre del origen CSV<input name="csv-account" value={connectionName} onChange={event=>setConnectionName(event.target.value)} required maxLength={200}/></label><button disabled={busy||!connectionName.trim()}>Crear conexión CSV</button></fieldset></form>}
 <fieldset disabled={busy}><legend>Nueva importación</legend><label>Conexión<select value={connection} onChange={e=>setConnection(e.target.value)}><option value="">Selecciona conexión</option>{connections.map(c=><option key={c.id} value={c.id}>{c.source} · {c.account_id}</option>)}</select></label>{!connections.length&&<p>No hay conexiones activas disponibles.</p>}<label>Archivo<input type="file" accept=".csv,.xlsx" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={!connection||!file} onClick={()=>void run(upload)}>Reservar y subir archivo</button></fieldset>
 {nextConnectionOffset!==null&&<button disabled={busy} onClick={()=>void run(()=>list(0,nextConnectionOffset,true))}>Más conexiones</button>}
 <h2>Reservas recientes</h2>{!reservations.length?<p>No hay reservas.</p>:<ul>{reservations.map(r=><li key={r.id}><button disabled={busy} onClick={()=>void run(()=>load(r.id))}>{r.id} · {r.state}</button></li>)}</ul>}
 {nextOffset!==null&&<button disabled={busy} onClick={()=>void run(()=>list(nextOffset,0,true))}>Más reservas</button>}
 {detail&&<>{detail.import.job_id&&<a href={'/jobs/'+detail.import.job_id}>Ver progreso real de ingestión</a>}<h2>Configuración de columnas</h2><p>Para ingerir mensajes, asigna fecha, rol (customer/agent/internal) y conversación. No se infieren relaciones financieras.</p><p>Estado: {detail.import.state} · Versión: {detail.import.mapping_version}</p><fieldset disabled={busy||detail.import.state!=='reserved'}><legend>Mapping explícito</legend>
 <label>Modo de importación<select aria-describedby="import-profile-help" disabled={detail.import.content_type!=='text/csv'} value={mapping.profile??''} onChange={e=>changeProfile(e.target.value)}><option value="">Estándar (predeterminado)</option><option value="history-message-v1" disabled={detail.import.content_type!=='text/csv'}>Histórico de mensajes (CSV)</option></select></label>
 <p id="import-profile-help">{detail.import.content_type==='text/csv'?'El modo histórico es opcional. Al cambiar de modo debes volver a validar y confirmar la configuración.':'El modo histórico sólo está disponible para archivos que el servidor confirma como CSV.'}</p>
 {mapping.profile==='history-message-v1'&&<p>Requiere columnas de ID, texto, fecha, rol y conversación, y fechas ISO con zona horaria (Z o un desplazamiento como -06:00). Conserva textos largos y la precisión original de las fechas, dentro de los límites de importación. La vista muestra UTC en milisegundos; no garantiza el orden exacto dentro del mismo milisegundo. Cambiar de modo no inicia una importación ni actualiza mensajes ya importados.</p>}
 {(['id','text','date','order','sku','amount','currency','customer','role','conversation'] as const).map(k=><label key={k}>Columna {k}{headers.length?<select value={mapping.columns[k]??''} onChange={e=>change({...mapping,columns:{...mapping.columns,[k]:e.target.value||null}} as Mapping)}><option value="">{k==='id'||k==='text'||(mapping.profile==='history-message-v1'&&['date','role','conversation'].includes(k))?'Selecciona (obligatoria)':'Sin columna'}</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select>:<input value={mapping.columns[k]??''} onChange={e=>change({...mapping,columns:{...mapping.columns,[k]:e.target.value}})}/>}</label>)}
 <label>Zona horaria IANA<input placeholder="America/Merida" value={mapping.timezone} onChange={e=>change({...mapping,timezone:e.target.value})}/></label><label>Formato de fecha<select disabled={mapping.profile==='history-message-v1'} value={mapping.dateFormat} onChange={e=>change({...mapping,dateFormat:e.target.value as Mapping['dateFormat']})}><option value="iso">ISO</option><option value="ymd">AAAA-MM-DD</option><option value="dmy">DD/MM/AAAA</option><option value="mdy">MM/DD/AAAA</option></select></label><label>Moneda explícita<select value={mapping.currency??''} onChange={e=>change({...mapping,currency:e.target.value||null})}><option value="">Sin importes / moneda por fila</option>{['USD','MXN','EUR','GBP','CAD','AUD','JPY','KWD'].map(c=><option key={c}>{c}</option>)}</select></label><label>Hoja Excel (obligatoria si hay varias)<select disabled={!sheets.length} value={mapping.sheet??''} onChange={e=>{setApproved(false);setPreview(null);void run(()=>load(detail.import.id,e.target.value));}}><option value="">Selecciona hoja</option>{sheets.map(sheet=><option key={sheet} value={sheet}>{sheet}</option>)}</select></label>
 <button onClick={()=>void run(validate)}>Validar y previsualizar</button><button disabled={!preview} onClick={()=>void run(save)}>Guardar y confirmar mapping</button><button disabled={!approved} onClick={()=>void run(confirm)}>Confirmar envío a cola</button></fieldset>
 {preview&&<><h2>Validación: {preview.input_rows} filas</h2><p>Aceptadas {preview.coverage.accepted}; rechazadas {preview.coverage.rejected}; duplicadas {preview.coverage.duplicates}; pendientes {preview.coverage.pending}. El procesamiento en cola confirma la deduplicación y los conteos finales.</p><p>Muestra limitada a {preview.sample.limit}, no representativa.</p><ScrollTable label="Muestra normalizada, tabla desplazable"><table><caption>Muestra normalizada</caption><thead><tr><th>Fila</th><th>ID</th><th>Texto</th><th>Fecha UTC</th><th>Importe minor units</th></tr></thead><tbody>{preview.sample.rows.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.id}</td><td>{r.text}</td><td>{r.occurred_at??'Desconocida'}</td><td>{r.money?`${r.money.amount_minor} ${r.money.currency}`:'Desconocido'}</td></tr>)}</tbody></table></ScrollTable><ul>{preview.errors.slice(0,100).map((e,i)=><li key={i}>Fila {e.line}, {e.field}: {e.code}</li>)}</ul>{detail.mapping&&<a href={'/api/imports/'+detail.import.id+'/errors.csv'}>Descargar errores CSV del mapping guardado</a>}</>}
 <button disabled={busy} onClick={()=>void run(()=>load(detail.import.id))}>Recargar esta reserva</button></>}
 </section>;
}
