'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ComparisonResult,ComparisonSnapshot} from '../../../../packages/connectors/comparability.mjs';
const reasonLabels:Record<string,string>={currency_unit_changed:'Cambió la unidad monetaria; los importes no son comparables.',scope_changed:'Cambiaron filtros, ventana, moneda o base temporal.',pipeline_changed:'Cambió la versión del procesamiento.',mapping_changed:'Cambió el mapeo de las fuentes.',taxonomy_changed:'Cambió la taxonomía: documenta el cambio y genera cortes con el mismo método.',channel_coverage_changed:'Cambió la cobertura de canales; menos casos no significa una mejora.',incomplete_evidence:'Hay datos sin versión, fecha o canal verificable.',empty_dataset:'Uno de los cortes no contiene conversaciones.'};

function moneyText(value:string|null|undefined,exponent:number|undefined){if(value==null)return 'desconocido';if(exponent===undefined)return value+' (unidad sin verificar)';const negative=value.startsWith('-'),digits=(negative?value.slice(1):value).padStart(exponent+1,'0');return (negative?'-':'')+(exponent?digits.slice(0,-exponent)+'.'+digits.slice(-exponent):digits);}
export function MigrationComparison(){
 const requestGeneration=useRef(0);
 const [denied,setDenied]=useState(false);
 const [snapshots,setSnapshots]=useState<ComparisonSnapshot[]>([]),[before,setBefore]=useState(''),[after,setAfter]=useState(''),[result,setResult]=useState<ComparisonResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[nextCursor,setNextCursor]=useState<string|null>(null);
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[timezone,setTimezone]=useState('UTC'),[currency,setCurrency]=useState('USD'),[sources,setSources]=useState(''),[channels,setChannels]=useState('');
 const api=useCallback(async(url:string,body?:unknown,signal?:AbortSignal)=>{
  const generation=++requestGeneration.current;
  const response=await fetch('/api/migrations'+url,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',signal});
  if(signal?.aborted||generation!==requestGeneration.current)throw new DOMException('Respuesta obsoleta','AbortError');
  if([401,403].includes(response.status)){requestGeneration.current++;setDenied(true);setSnapshots([]);setBefore('');setAfter('');setResult(null);setNextCursor(null);setLoaded(false);setStart('');setEnd('');setTimezone('UTC');setCurrency('USD');setSources('');setChannels('');throw Error('Ya no tienes autorización para consultar o modificar estos cortes.');}
  if(!response.ok)throw Error(response.status===409?'No se pudo congelar o comparar este alcance. Comprueba versiones, identidades y límites del dataset.':'No se pudo consultar el servicio de comparación. Reintenta.');
  const data=await response.json();if(signal?.aborted||generation!==requestGeneration.current)throw new DOMException('Respuesta obsoleta','AbortError');return data;
 },[]);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const body=await api('',undefined,signal);setSnapshots(body.snapshots);setNextCursor(body.nextCursor);setLoaded(true);setDenied(false);},[api]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>refresh(controller.signal)).catch(e=>{if(!controller.signal.aborted&&e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[refresh]);
 async function action(work:()=>Promise<void>){setError('');setBusy(true);try{await work();}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Error de comparación.');}finally{setBusy(false);}}
 const label=(s:ComparisonSnapshot)=>`${s.id} · ${s.watermark} · ${s.summary.conversations} conversaciones`;
 return <section><h1>Comparación de migración</h1><p>Conserva cortes inmutables del dataset antes y después. Las diferencias no demuestran ahorro ni efecto causal.</p><p>Ventana UTC por inicio de conversación. Los mensajes y las órdenes vinculadas siguen ese alcance. El corte conserva el método y las versiones de origen disponibles.</p>
 {error&&<p role="alert">{error}</p>}
 <button disabled={busy} onClick={()=>void action(()=>refresh())}>Actualizar cortes</button>
 {!loaded&&!error&&<p role="status">Cargando cortes…</p>}{loaded&&!snapshots.length&&<p>Aún no hay cortes publicados. Congela el dataset para crear el primero.</p>}
 <form onSubmit={e=>{e.preventDefault();void action(async()=>{const data=await api('',{dateStart:new Date(start+'T00:00:00Z').toISOString(),dateEnd:new Date(end+'T00:00:00Z').toISOString(),timezone,currency,dateBasis:'conversation',sources:sources.split(',').map(x=>x.trim()).filter(Boolean),channels:channels.split(',').map(x=>x.trim()).filter(Boolean)});setAfter(data.snapshot.id);setResult(null);await refresh();});}}><fieldset disabled={busy||denied}><legend>Congelar un corte nuevo — owner o analyst</legend>
 <label>Inicio UTC<input required type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fin UTC exclusivo<input required type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label>
 <label>Zona horaria del contrato<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><label>Moneda<input required maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label>
 <label>Fuentes, separadas por coma<input value={sources} onChange={e=>setSources(e.target.value)} placeholder="Todas las fuentes si se deja vacío"/></label><label>Canales, separados por coma<input value={channels} onChange={e=>setChannels(e.target.value)} placeholder="Todos los canales si se deja vacío"/></label>
 <button type="submit">Congelar corte</button></fieldset></form>
 <fieldset disabled={busy||denied}><legend>Seleccionar cortes guardados</legend>{nextCursor&&<button onClick={()=>void action(async()=>{const data=await api('?'+new URLSearchParams({cursor:nextCursor}));setSnapshots(previous=>[...previous,...data.snapshots.filter((s:ComparisonSnapshot)=>!previous.some(p=>p.id===s.id))]);setNextCursor(data.nextCursor);})}>Cargar cortes anteriores</button>}<label htmlFor="comparison-before">Antes</label><select id="comparison-before" value={before} onChange={e=>{setBefore(e.target.value);setResult(null);}}><option value="">Selecciona baseline</option>{snapshots.map(s=><option key={s.id} value={s.id}>{label(s)}</option>)}</select><label htmlFor="comparison-after">Después</label><select id="comparison-after" value={after} onChange={e=>{setAfter(e.target.value);setResult(null);}}><option value="">Selecciona corte posterior</option>{snapshots.map(s=><option key={s.id} value={s.id}>{label(s)}</option>)}</select>
 <button disabled={!before||!after||before===after} onClick={()=>void action(async()=>setResult(await api('/compare?'+new URLSearchParams({before,after}))))}>Comparar cortes</button></fieldset>
 {result&&<section aria-label="Resultado de comparación"><h2>{result.state==='comparable'?'Comparable':'No comparable'}</h2><p>{result.notice}</p><p>Antes: {result.before.id} · Después: {result.after.id}</p>{result.reasons.length>0&&<ul>{result.reasons.map(reason=><li key={reason}>{reasonLabels[reason]??reason}</li>)}</ul>}
 <h3>Registros únicos</h3><table><thead><tr><th>Registro</th><th>Antes</th><th>Después</th><th>Diferencia descriptiva</th></tr></thead><tbody>{Object.entries(result.counts).map(([key,v])=><tr key={key}><th>{({conversations:'Conversaciones resueltas',sourceConversations:'Conversaciones fuente',messages:'Mensajes fuente',orders:'Órdenes vinculadas'} as Record<string,string>)[key]}</th><td>{v.before}</td><td>{v.after}</td><td>{v.delta}</td></tr>)}</tbody></table>
 <h3>Cobertura observada por canal</h3><p>Conteos observados; no acreditan el total disponible en el proveedor. Los canales con prefijo de proveedor conservan su identificador original; no se asumen equivalencias entre HubSpot y Zendesk.</p><table><thead><tr><th>Canal</th><th>Antes</th><th>Después</th></tr></thead><tbody>{result.channels.map(c=><tr key={c.channel}><th>{c.channel}</th><td>{c.before}</td><td>{c.after}</td></tr>)}</tbody></table>
 <h3>Importes de órdenes vinculadas</h3><p>No representan pérdidas, ahorro ni ingresos recuperados. Importes desconocidos permanecen desconocidos.</p>{Object.entries(result.money).map(([code,m])=><p key={code}>{code}: antes {moneyText(m.before?.amountMinor,result.before.method.currencyExponents[code])} (subtotal conocido {moneyText(m.before?.knownSubtotalMinor,result.before.method.currencyExponents[code])}); después {moneyText(m.after?.amountMinor,result.after.method.currencyExponents[code])} (subtotal conocido {moneyText(m.after?.knownSubtotalMinor,result.after.method.currencyExponents[code])}). Delta comparable: {m.deltaMinor===null?'no disponible':moneyText(m.deltaMinor,result.after.method.currencyExponents[code])}.</p>)}
 <details><summary>Método y procedencia congelados</summary><pre>{JSON.stringify({before:{scope:result.before.scope,method:result.before.method,watermark:result.before.watermark,inputHash:result.before.inputHash,warnings:result.before.summary.warnings},after:{scope:result.after.scope,method:result.after.method,watermark:result.after.watermark,inputHash:result.after.inputHash,warnings:result.after.summary.warnings}},null,2)}</pre></details></section>}
 </section>;
}
