 'use client';
import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';
import {TeamPanel} from './team-panel';
type Organization={id:string;name:string};
type Audit={id:string;actorId:string;operation:string;tenantId:string;createdAt:string};
export function PlatformPanel(){
 const [items,setItems]=useState<Organization[]>([]),[next,setNext]=useState<string|null>(null),[selected,setSelected]=useState<Organization|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[audit,setAudit]=useState<Audit[]>([]),[auditNext,setAuditNext]=useState<string|null>(null);
 const generation=useRef(0),requestId=useRef(crypto.randomUUID());
 const load=useCallback(async(cursor?:string)=>{const g=++generation.current;setBusy(true);setError('');setItems([]);setSelected(null);try{const r=await fetch(`/api/platform${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw new Error();if(g===generation.current){setItems(v.data.items);setNext(v.data.nextCursor);return true;}}catch{if(g===generation.current){setNext(null);setAudit([]);setAuditNext(null);setError('No se pudo cargar la plataforma. Verifica tu acceso y actualiza.');}}finally{if(g===generation.current)setBusy(false);}return false;},[]);
 useEffect(()=>{const lifecycle=generation;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);lifecycle.current++;};},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/platform',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({operation:'create',name:fields.get('name'),ownerEmail:fields.get('ownerEmail'),confirmed:fields.get('confirmed')==='on',requestId:requestId.current})});const v=await r.json();if(!r.ok){setItems([]);setSelected(null);setAudit([]);throw new Error(v.error?.code==='platform_owner_unavailable'?'El responsable necesita una cuenta existente con correo confirmado.':v.error?.code==='platform_self_change_forbidden'?'Usa una cuenta responsable diferente de tu cuenta de plataforma.':v.error?.code==='platform_request_conflict'?'Este intento ya tiene otros datos. Actualiza la página antes de continuar.':'No se pudo crear la organización. Verifica tu acceso.');}requestId.current=crypto.randomUUID();form.reset();if(await load())setNotice('Organización creada con un owner activo. No se envió ningún correo.');}catch(e){setError(e instanceof Error&&!['TimeoutError','AbortError','TypeError'].includes(e.name)?e.message:'No se confirmó el resultado. Conserva los mismos datos y vuelve a intentar; el intento no creará duplicados.');}finally{setBusy(false);}}
 async function loadAudit(cursor?:string){setBusy(true);setError('');setAudit([]);try{const r=await fetch(`/api/platform?operation=audit${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw new Error();setAudit(v.data.items);setAuditNext(v.data.nextCursor);}catch{setItems([]);setSelected(null);setAuditNext(null);setError('No se pudo cargar la actividad. Verifica tu acceso.');}finally{setBusy(false);}}
 return <div aria-busy={busy}><h1>Administración de plataforma</h1><p>Administra organizaciones y sus equipos. Este permiso no concede acceso al contenido de sus clientes.</p>
 <form onSubmit={create}><h2>Crear organización</h2><label>Nombre <input name="name" required maxLength={200} disabled={busy}/></label><label>Correo del responsable <input name="ownerEmail" type="email" required maxLength={254} disabled={busy}/></label><p>El responsable debe tener una cuenta existente con correo confirmado. Recibirá el rol owner.</p><label><input name="confirmed" type="checkbox" required disabled={busy}/>Confirmo la organización y el responsable.</label><button disabled={busy}>Crear organización</button></form>
 {busy&&<p role="status">Cargando…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <h2>Organizaciones</h2><button disabled={busy} onClick={()=>void load()}>Actualizar organizaciones</button><ul>{items.map(item=><li key={item.id}><button disabled={busy} onClick={()=>setSelected(item)} aria-pressed={selected?.id===item.id}>{item.name}</button></li>)}</ul>{next&&<button disabled={busy} onClick={()=>void load(next)}>Siguiente página de organizaciones</button>}
 {selected&&<section aria-label={`Equipo de ${selected.name}`}><h2>{selected.name}</h2><TeamPanel key={selected.id} endpoint={`/api/platform/team?tenantId=${selected.id}`} platform/></section>}
 <h2>Actividad administrativa</h2><button disabled={busy} onClick={()=>void loadAudit()}>Actualizar actividad</button><ul>{audit.map(item=><li key={item.id}>{item.operation} · {new Date(item.createdAt).toLocaleString()} · Organización: {item.tenantId??'—'} · Actor: {item.actorId}</li>)}</ul>{auditNext&&<button disabled={busy} onClick={()=>void loadAudit(auditNext)}>Actividad anterior</button>}
 </div>;
}
