 'use client';
import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';
import {TeamPanel} from './team-panel';
type Organization={id:string;name:string};
type Audit={id:string;actorId:string;operation:string;tenantId:string;createdAt:string};
export function PlatformPanel(){
 const [items,setItems]=useState<Organization[]>([]),[next,setNext]=useState<string|null>(null),[selected,setSelected]=useState<Organization|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmed,setConfirmed]=useState(false),[audit,setAudit]=useState<Audit[]>([]),[auditNext,setAuditNext]=useState<string|null>(null);
 const generation=useRef(0),requestId=useRef(crypto.randomUUID());
 const load=useCallback(async(cursor?:string)=>{const g=++generation.current;setBusy(true);setError('');setItems([]);setSelected(null);try{const r=await fetch(`/api/platform${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw new Error();if(g===generation.current){setItems(v.data.items);setNext(v.data.nextCursor);return true;}}catch{if(g===generation.current){setNext(null);setAudit([]);setAuditNext(null);setError('No se pudo cargar la plataforma. Verifica tu acceso y actualiza.');}}finally{if(g===generation.current)setBusy(false);}return false;},[]);
 useEffect(()=>{const lifecycle=generation;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);lifecycle.current++;};},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/platform',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({operation:'create',name:fields.get('name'),ownerEmail:fields.get('ownerEmail'),confirmed:fields.get('confirmed')==='on',requestId:requestId.current})});const v=await r.json();if(!r.ok){setItems([]);setSelected(null);setAudit([]);throw new Error(v.error?.code==='platform_owner_unavailable'?'El responsable necesita una cuenta existente con correo confirmado.':v.error?.code==='platform_self_change_forbidden'?'Usa una cuenta responsable diferente de tu cuenta de plataforma.':v.error?.code==='platform_request_conflict'?'Este intento ya tiene otros datos. Actualiza la página antes de continuar.':'No se pudo crear la organización. Verifica tu acceso.');}requestId.current=crypto.randomUUID();form.reset();setConfirmed(false);if(await load())setNotice('Organización creada con un owner activo. No se envió ningún correo.');}catch(e){setError(e instanceof Error&&!['TimeoutError','AbortError','TypeError'].includes(e.name)?e.message:'No se confirmó el resultado. Conserva los mismos datos y vuelve a intentar; el intento no creará duplicados.');}finally{setBusy(false);}}
 async function loadAudit(cursor?:string){setBusy(true);setError('');setAudit([]);try{const r=await fetch(`/api/platform?operation=audit${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw new Error();setAudit(v.data.items);setAuditNext(v.data.nextCursor);}catch{setItems([]);setSelected(null);setAuditNext(null);setError('No se pudo cargar la actividad. Verifica tu acceso.');}finally{setBusy(false);}}
 return <div className="platform-panel" aria-busy={busy}>
 <header className="platform-page-heading"><div><p className="eyebrow">Control de plataforma</p><h1>Organizaciones y equipos</h1><p>Administra los espacios de trabajo y las personas responsables de cada organización.</p></div><a className="platform-create-link" href="#crear-organizacion">Crear organización</a></header>
 <div className="platform-permission-note"><strong>Acceso administrativo</strong><span>Este permiso no concede acceso al contenido de los clientes.</span></div>
 {busy&&<p role="status">Cargando…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="platform-grid">
  <section className="platform-card platform-organizations" id="organizaciones" aria-labelledby="organizations-title"><header><div><p className="eyebrow">Espacios de trabajo</p><h2 id="organizations-title">Organizaciones</h2></div><button className="platform-secondary" disabled={busy} onClick={()=>void load()}>Actualizar organizaciones</button></header><p className="platform-description">Selecciona una organización para gestionar su equipo.</p>
   {!busy&&!error&&items.length===0&&<div className="platform-empty"><h3>No hay organizaciones en esta página</h3><p>Crea un espacio y asigna una cuenta responsable para comenzar.</p></div>}
   <ul className="platform-organization-list">{items.map(item=><li key={item.id}><button disabled={busy} onClick={()=>setSelected(item)} aria-pressed={selected?.id===item.id}><span className="organization-initial" aria-hidden="true">{item.name.slice(0,1).toUpperCase()}</span><span><strong>{item.name}</strong><small>{selected?.id===item.id?'Equipo seleccionado':'Administrar equipo'}</small></span><span className="organization-open" aria-hidden="true">→</span></button></li>)}</ul>{next&&<button className="platform-secondary" disabled={busy} onClick={()=>void load(next)}>Siguiente página de organizaciones</button>}
  </section>
  <section className="platform-card platform-create" id="crear-organizacion" aria-labelledby="create-title"><header><div><p className="eyebrow">Nuevo espacio</p><h2 id="create-title">Crear organización</h2></div></header><p className="platform-description">El responsable debe tener una cuenta existente con correo confirmado. Recibirá el rol owner.</p>
   <form onSubmit={create}><label>Nombre de la organización<input name="name" autoComplete="organization" placeholder="Nombre del espacio de trabajo" required maxLength={200} disabled={busy} onChange={()=>setConfirmed(false)}/></label><label>Correo del responsable<input name="ownerEmail" type="email" autoComplete="email" placeholder="nombre@empresa.com" required maxLength={254} disabled={busy} onChange={()=>setConfirmed(false)}/></label><label className="platform-confirmation"><input name="confirmed" type="checkbox" required disabled={busy} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Confirmo la organización y el responsable.</label><button disabled={busy}>Crear organización</button><p className="platform-form-note">La creación no envía ningún correo.</p></form>
  </section>
 </div>
 {selected&&<section className="platform-card platform-team" aria-label={`Equipo de ${selected.name}`}><header><div><p className="eyebrow">Organización seleccionada</p><h2>{selected.name}</h2></div></header><TeamPanel key={selected.id} endpoint={`/api/platform/team?tenantId=${selected.id}`} platform/></section>}
 <section className="platform-card platform-activity" id="actividad" aria-labelledby="activity-title"><header><div><p className="eyebrow">Trazabilidad</p><h2 id="activity-title">Actividad administrativa</h2></div><button className="platform-secondary" disabled={busy} onClick={()=>void loadAudit()}>Actualizar actividad</button></header><p className="platform-description">Consulta las operaciones registradas y quién las realizó.</p>
 {audit.length===0&&<p className="platform-activity-hint">Usa «Actualizar actividad» para consultar los registros disponibles.</p>}
 <ul className="platform-audit-list">{audit.map(item=><li key={item.id}><div><strong>{item.operation}</strong><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time></div><dl><div><dt>Organización</dt><dd>{item.tenantId??'—'}</dd></div><div><dt>Actor</dt><dd>{item.actorId}</dd></div></dl></li>)}</ul>{auditNext&&<button className="platform-secondary" disabled={busy} onClick={()=>void loadAudit(auditNext)}>Actividad anterior</button>}
 </section>
 </div>;
}
