'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ProblemSnapshot,ProblemDetail,Match} from '../lib/problems/contracts';
const jobStates:Record<string,string>={queued:'En cola',running:'Agrupando',succeeded:'Terminado',failed:'Requiere atención',cancelled:'Cancelado'};
const stale=()=>new DOMException('Respuesta obsoleta','AbortError');
export function ProblemsPanel({problemId}:{problemId?:string}){
 const generation=useRef(0),actionPending=useRef(false),requestKey=useRef<string|null>(null);
 const [snapshot,setSnapshot]=useState<ProblemSnapshot|null>(null),[detail,setDetail]=useState<ProblemDetail|null>(null),[matches,setMatches]=useState<Match[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [source,setSource]=useState(''),[embedding,setEmbedding]=useState(''),[operation,setOperation]=useState<'split'|'merge'>('split'),[other,setOther]=useState(''),[selected,setSelected]=useState<string[]>([]),[labelA,setLabelA]=useState(''),[labelB,setLabelB]=useState(''),[reason,setReason]=useState(''),[approved,setApproved]=useState(false);
 const clear=useCallback(()=>{setSnapshot(null);setDetail(null);setMatches(null);setSource('');setEmbedding('');setOther('');setSelected([]);setLabelA('');setLabelB('');setReason('');setApproved(false);setNotice('');requestKey.current=null;},[]);
 const invalidate=useCallback(()=>{generation.current++;},[]);
 const request=useCallback(async(url:string,epoch:number,body?:unknown,signal?:AbortSignal)=>{
  const response=await fetch(url,{method:body===undefined?'GET':'POST',cache:'no-store',signal,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
  if(signal?.aborted||epoch!==generation.current)throw stale();
  if(response.status===401||response.status===403){generation.current++;clear();setError('Ya no tienes autorización para consultar o modificar estos problemas.');throw stale();}
  const data=await response.json();if(signal?.aborted||epoch!==generation.current)throw stale();
  if(!response.ok)throw Error(response.status===404?'No existe un problema accesible con este identificador.':response.status===409?'La versión o los miembros cambiaron. Actualiza y revisa la decisión.':data.error?.code==='configuration_required'||data.error?.code==='runtime_disabled'?'El servicio de agrupación necesita configuración y autorización del administrador.':'No se pudo completar la solicitud de problemas. Reintenta.');return data;
 },[clear]);
 const reload=useCallback(async(signal?:AbortSignal)=>{const epoch=++generation.current;try{const [listing,current]=await Promise.all([request('/api/problems',epoch,undefined,signal),problemId?request('/api/problems/'+encodeURIComponent(problemId),epoch,undefined,signal):Promise.resolve(null)]);if(!signal?.aborted&&epoch===generation.current){setSnapshot(listing);setDetail(current?.problem??null);setError('');setMatches(null);setSelected([]);setApproved(false);}}catch(e){if(e instanceof Error&&e.name==='AbortError')return;if(!signal?.aborted&&epoch===generation.current){clear();setError(e instanceof Error?e.message:'No se pudieron cargar los problemas.');}}},[problemId,request,clear]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>reload(controller.signal));return()=>{controller.abort();invalidate();};},[reload,invalidate]);
 async function action(body:Record<string,unknown>){if(actionPending.current)return;actionPending.current=true;setBusy(true);setError('');setNotice('');const epoch=++generation.current;try{const response=await request('/api/problems',epoch,body);if(epoch!==generation.current)return;if(body.operation==='retrieve'){setMatches(response.data);return;}if(body.operation==='submit'){requestKey.current=null;setNotice('Agrupación en cola. Actualiza para consultar el resultado del consumidor.');}else{setNotice('Revisión guardada. Las versiones anteriores se conservan.');setReason('');setApproved(false);setSelected([]);}await reload();}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'No se pudo completar la acción.');}finally{actionPending.current=false;setBusy(false);}}
 const otherProblem=snapshot?.problems.find(p=>p.id===other),remaining=detail?.embeddingIds.filter(id=>!selected.includes(id))??[];
 function restructure(){if(!detail)return;const parents=[{problemId:detail.id,expectedVersion:detail.version}];let children;if(operation==='merge'){if(!otherProblem)return;parents.push({problemId:otherProblem.id,expectedVersion:otherProblem.version});children=[{label:labelA,embeddingIds:[...new Set([...detail.embeddingIds,...otherProblem.embeddingIds])]}];}else children=[{label:labelA,embeddingIds:selected},{label:labelB,embeddingIds:remaining}];void action({operation,parents,children,reason,approved});}
 return <main aria-label="Catálogo de problemas"><h1>{problemId?'Detalle del problema':'Problemas de negocio'}</h1><p>Identidades estables y agrupaciones con procedencia. La similitud no confirma una causa ni representa pérdida o ahorro.</p>
 <button disabled={busy} onClick={()=>void reload()}>Actualizar problemas</button>{problemId&&<Link href="/problems">Volver a problemas</Link>}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Procesando solicitud…</p>}{!snapshot&&!error&&<p role="status">Cargando problemas…</p>}
 {snapshot&&<>
 {!snapshot.configuration.ready||!snapshot.configuration.enabled?<p role="status">La agrupación requiere que el administrador configure el proveedor y autorice su ejecución.</p>:null}
 {!problemId&&<><h2>Catálogo estable</h2>{!snapshot.problems.length&&<p>Aún no hay problemas agrupados. Selecciona una extracción publicada para comenzar.</p>}<ul>{snapshot.problems.map(p=><li key={p.id}><Link href={'/problems/'+p.id}>{p.label}</Link> · versión {p.version} · {p.state==='retired'?'Retirado; historial conservado':'Activo'}{p.outlier?' · Atípico: requiere revisión humana':''} · {p.conversationIds.length} conversaciones únicas</li>)}</ul></>}
 {snapshot.canSubmit&&!problemId&&<form onSubmit={e=>{e.preventDefault();requestKey.current??=crypto.randomUUID();void action({operation:'submit',extractionRunId:source,requestKey:requestKey.current});}}><h2>Agrupar extracción</h2><label>Extracción publicada<select required disabled={busy} value={source} onChange={e=>{setSource(e.target.value);requestKey.current=null;}}><option value="">Selecciona una extracción</option>{snapshot.sources.map(s=><option key={s.id} value={s.id}>{s.id} · conversación {s.conversationId}</option>)}</select></label><button disabled={busy||!source||!snapshot.configuration.ready||!snapshot.configuration.enabled}>Agrupar extracción</button></form>}
 {!problemId&&<section aria-label="Trabajos de agrupación"><h2>Trabajos de agrupación</h2>{!snapshot.jobs.length?<p>No hay solicitudes de agrupación.</p>:snapshot.jobs.map(j=><article key={j.id}><p>Solicitud {j.id}: {jobStates[j.state]??j.state}</p>{j.reason&&<p>Requiere revisión: {j.reason}</p>}</article>)}</section>}
 </>}
 {detail&&snapshot&&<><h2>{detail.label}</h2><p>ID estable: {detail.id} · Versión {detail.version} · {detail.state==='retired'?'Retirado; historial conservado':'Activo'}</p>{detail.outlier&&<p role="status">Atípico: requiere revisión humana. No se asignó automáticamente a otro problema.</p>}<p>Modelo {detail.modelId} · {detail.dimensions} dimensiones · Espacio {detail.embeddingVersion}</p><p>{detail.conversationIds.length} conversaciones y {detail.orderIds.length} órdenes únicas. No se suman importes entre problemas.</p>
 <section aria-label="Miembros del problema"><h3>Miembros y procedencia</h3><ul>{detail.embeddingIds.map(id=><li key={id}>{id}</li>)}</ul><details><summary>Identidades de las fuentes</summary><p>Conversaciones: {detail.conversationIds.join(', ')||'Ninguna'}</p><p>Órdenes: {detail.orderIds.join(', ')||'Ninguna'}</p></details></section>
 <form onSubmit={e=>{e.preventDefault();void action({operation:'retrieve',embeddingId:embedding,limit:10});}}><label>Miembro para buscar similares<select required disabled={busy} value={embedding} onChange={e=>{setEmbedding(e.target.value);setMatches(null);}}><option value="">Selecciona un miembro</option>{detail.embeddingIds.map(id=><option key={id} value={id}>{id}</option>)}</select></label><button disabled={busy||!embedding}>Buscar similares</button></form>
 {matches&&<section aria-label="Resultados de similitud"><h3>Resultados de similitud autorizados</h3>{!matches.length?<p>No hay resultados autorizados en el mismo espacio.</p>:<ul>{matches.map(m=><li key={m.embeddingId}>{m.problemId?<Link href={'/problems/'+m.problemId}>{m.problemId}</Link>:'Sin agrupación'} · Miembro {m.embeddingId} · Distancia {m.distance}</li>)}</ul>}</section>}
 {snapshot.canRestructure&&detail.state==='active'&&<form onSubmit={e=>{e.preventDefault();restructure();}}><fieldset disabled={busy}><legend>Revisión humana de la agrupación</legend><label>Operación<select value={operation} onChange={e=>{setOperation(e.target.value as 'split'|'merge');setApproved(false);}}><option value="split">Dividir</option><option value="merge">Unir</option></select></label>
 {operation==='split'?<><p>Selecciona los miembros del primer grupo. Los restantes formarán el segundo; ningún miembro se pierde.</p>{detail.embeddingIds.map(id=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>{setSelected(previous=>e.target.checked?[...previous,id]:previous.filter(x=>x!==id));setApproved(false);}}/>{id}</label>)}<label>Nombre del segundo grupo<input required maxLength={200} value={labelB} onChange={e=>{setLabelB(e.target.value);setApproved(false);}}/></label></>:<label>Problema para unir<select required value={other} onChange={e=>{setOther(e.target.value);setApproved(false);}}><option value="">Selecciona otro problema</option>{snapshot.problems.filter(p=>p.id!==detail.id&&p.state==='active'&&p.modelId===detail.modelId&&p.dimensions===detail.dimensions&&p.embeddingVersion===detail.embeddingVersion).map(p=><option key={p.id} value={p.id}>{p.label} · versión {p.version}</option>)}</select></label>}
 <label>{operation==='split'?'Nombre del primer grupo':'Nombre del grupo unido'}<input required maxLength={200} value={labelA} onChange={e=>{setLabelA(e.target.value);setApproved(false);}}/></label><label>Motivo de la revisión<textarea required maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);setApproved(false);}}/></label><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Confirmo la revisión humana</label><p>La decisión registra las versiones actuales y conserva las versiones anteriores. Revisa nuevamente si hay un conflicto.</p><button disabled={!approved||!reason.trim()||!labelA.trim()||(operation==='split'?selected.length===0||remaining.length===0||!labelB.trim():!other)}>Aplicar revisión</button></fieldset></form>}
 <section aria-label="Historial del problema"><h3>Historial de versiones</h3>{detail.history.map(h=><article key={h.id}><h4>Versión {h.version}</h4><p>{h.provenance.operation==='split'?'División revisada':h.provenance.operation==='merge'?'Unión revisada':h.provenance.jobId?'Agrupación de evidencia':'Actualización del problema'}</p>{typeof h.provenance.reason==='string'&&<p>Motivo: {h.provenance.reason}</p>}<details><summary>Ver procedencia para auditoría</summary><pre>{JSON.stringify(h.provenance,null,2)}</pre></details></article>)}</section>
 </>}
 </main>;
}
