'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Snapshot={ready:boolean;policy:{version:number;backupTtlSeconds:number}|null;connections:Array<{id:string;source:string;accountId:string}>;artifacts:Array<{id:string;class:string;path:string;status:string}>;counts:{pending:number;deleted:number}};
type Preview={target:{connectionId:string;entityType:string;externalId:string};scope:{messages:string[];conversations:string[];revisions:unknown[];vectors:string[];jobs:string[];problems:string[];rawObjects:string[];rawFiles:Array<{importId:string;path:string;rows:number}>;artifacts:unknown[];derived:unknown[];policy:{version:number}};requestId:string;token:string;expiresAt:number};
class RetentionRequestError extends Error {}
export function RetentionPanel(){const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[sourceLoading,setSourceLoading]=useState(false),[ttl,setTtl]=useState('2592000'),[connection,setConnection]=useState(''),[kind,setKind]=useState('conversation'),[external,setExternal]=useState(''),[sources,setSources]=useState<Array<{id:string;externalId:string}>>([]),[cursor,setCursor]=useState<string|null>(null),[next,setNext]=useState<string|null>(null),[preview,setPreview]=useState<Preview|null>(null),[confirmed,setConfirmed]=useState(false);const pending=useRef(false),epoch=useRef(0);
 const clear=useCallback(()=>{setPreview(null);setConfirmed(false);},[]);
 const load=useCallback(async(signal?:AbortSignal)=>{
  const generation=++epoch.current;setLoading(true);setNotice('');
  try{const r=await fetch('/api/recovery',{cache:'no-store',signal});if(!r.ok)throw new RetentionRequestError(r.status===403?'Se requiere un owner activo.':'No se pudo consultar la retención.');const data=await r.json();if(!signal?.aborted&&generation===epoch.current){setSnapshot(data);setTtl(String(data.policy?.backupTtlSeconds??2592000));setError('');return true;}return false;
  }catch(e){if(!signal?.aborted&&generation===epoch.current){setSnapshot(null);clear();setError(e instanceof RetentionRequestError?e.message:'No se pudo consultar la retención. Comprueba la conexión y vuelve a actualizar.');}return false;
  }finally{if(!signal?.aborted&&generation===epoch.current)setLoading(false);}
 },[clear]);
 useEffect(()=>{const c=new AbortController();void Promise.resolve().then(()=>load(c.signal));return()=>c.abort();},[load]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(async()=>{
  if(controller.signal.aborted)return;if(!connection){setSourceLoading(false);return;}setSourceLoading(true);
  try{const r=await fetch('/api/recovery?'+new URLSearchParams({connectionId:connection,entityType:kind,...(cursor?{cursor}:{})}),{signal:controller.signal,cache:'no-store'});if(!r.ok)throw new RetentionRequestError('No se pudieron consultar las fuentes.');const result=await r.json();if(!controller.signal.aborted){setSources(result.items);setNext(result.nextCursor);setError('');}}
  catch{if(!controller.signal.aborted){setSources([]);setNext(null);clear();setError('No se pudieron consultar las fuentes. Comprueba la conexión y vuelve a seleccionar.');}}
  finally{if(!controller.signal.aborted)setSourceLoading(false);}
 });return()=>controller.abort();},[connection,kind,cursor,clear]);
 async function action(operation:string,input:Record<string,unknown>={}){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/recovery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation,...input})});if(!r.ok)throw new RetentionRequestError(r.status===409?'La política o el alcance cambió. Previsualiza de nuevo y confirma el alcance actual.':r.status===403?'La autorización ya no está vigente.':r.status===413?'El alcance supera el límite de esta operación. Selecciona una entidad menor.':'No se pudo completar la operación.');if(operation==='export'){const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='retention-ledger.json';a.click();URL.revokeObjectURL(url);setNotice('Ledger firmado exportado. La clave permanece en el servidor.');}else{const {data}=await r.json();if(operation==='preview'){setPreview(data);setConfirmed(false);}else{clear();if(!await load())return;setNotice(operation==='erase'?'Contenido activo borrado. Revisa y elimina los archivos físicos pendientes.':operation==='purge'?data.complete?'Purga física completada. Las copias externas no registradas no están verificadas.':'Quedan archivos pendientes. Puedes reintentar sin repetir el borrado lógico.':'Política guardada.');}}}catch(e){clear();await load();setError(e instanceof RetentionRequestError?e.message:'No se pudo confirmar la operación. Actualiza el estado antes de reintentar.');}finally{pending.current=false;setBusy(false);}}
 const unavailable=busy||loading||sourceLoading;
 function selection(){clear();setExternal('');setSources([]);setCursor(null);setNext(null);}
 return <section aria-label="Retención y borrado" aria-busy={unavailable}><h1>Retención y borrado</h1><p>Esta operación elimina contenido fuente y derivados. Conserva identidades y el historial financiero autorizado. Las copias externas no registradas no se pueden verificar desde aquí.</p>{loading&&<p role="status">{snapshot?'Actualizando retención…':'Cargando retención…'}</p>}{sourceLoading&&<p role="status">Cargando fuentes…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={unavailable} onClick={()=>{clear();void load();}}>Actualizar retención</button>{snapshot&&<>{!snapshot.ready&&<p role="status">Falta configurar la clave de firma del ledger en el servidor.</p>}<form onSubmit={e=>{e.preventDefault();void action('policy',{expectedVersion:snapshot.policy?.version??0,backupTtlSeconds:Number(ttl)});}}><h2>Política de copias registradas</h2><p>Versión: {snapshot.policy?.version??0}. El borrado del contenido activo es inmediato; el historial financiero autorizado se conserva.</p><label>Retención máxima de backups en segundos<input aria-describedby="retention-ttl-help" required type="number" min="1" max="31536000" value={ttl} disabled={unavailable} onChange={e=>{setTtl(e.target.value);clear();}}/></label><p id="retention-ttl-help">Este límite se aplica a las nuevas copias registradas. Las copias existentes conservan su fecha de vencimiento; cambiar esta política no las elimina ni modifica su fecha.</p><button disabled={unavailable}>Guardar política de retención</button></form>
 <form onSubmit={e=>{e.preventDefault();void action('preview',{connectionId:connection,entityType:kind,externalId:external});}}><h2>Seleccionar entidad canónica</h2><label>Conexión de retención<select aria-label="Conexión de retención" required disabled={unavailable} value={connection} onChange={e=>{setConnection(e.target.value);selection();}}><option value="">Selecciona conexión</option>{snapshot.connections.map(c=><option key={c.id} value={c.id}>{c.source} · {c.accountId}</option>)}</select></label><label>Tipo de entidad<select aria-label="Tipo de entidad" disabled={unavailable} value={kind} onChange={e=>{setKind(e.target.value);selection();}}><option value="conversation">Conversación</option><option value="message">Mensaje</option><option value="customer">Cliente</option></select></label><label>Identidad externa canónica<select aria-label="Identidad externa canónica" required disabled={unavailable||!sources.length} value={external} onChange={e=>{setExternal(e.target.value);clear();}}><option value="">Selecciona entidad</option>{sources.map(s=><option key={s.id} value={s.externalId}>{s.externalId}</option>)}</select></label><button type="button" disabled={unavailable||!cursor} onClick={()=>{selection();}}>Primera página de entidades</button><button type="button" disabled={unavailable||!next} onClick={()=>{setCursor(next);setExternal('');setSources([]);clear();}}>Siguiente página de entidades</button><button disabled={unavailable||!external||!snapshot.policy||!snapshot.ready}>Previsualizar borrado</button></form>
 {preview&&<section aria-label="Alcance del borrado"><h2>Revisar alcance exacto</h2><p>Conexión {preview.target.connectionId} · {preview.target.entityType}: {preview.target.externalId}</p><p>{preview.scope.conversations.length} conversaciones, {preview.scope.messages.length} mensajes, {preview.scope.revisions.length} revisiones y {preview.scope.vectors.length} vectores.</p><p>{preview.scope.derived.length} materializaciones derivadas y {preview.scope.artifacts.length} artefactos registrados asociados.</p><p>{preview.scope.jobs.length} trabajos activos se cancelarán, {preview.scope.problems.length} problemas perderán esta evidencia y se archivarán, y {preview.scope.rawObjects.length} objetos RAW canónicos se vaciarán.</p><h3>Archivos RAW completos</h3>{preview.scope.rawFiles.length?<ul>{preview.scope.rawFiles.map(f=><li key={f.importId}>{f.path} · {f.rows} filas registradas. Se elimina el archivo completo, incluidas otras filas que contenga.</li>)}</ul>:<p>No hay archivos RAW asociados a este alcance.</p>}<p>Solicitud: {preview.requestId}. Política versión {preview.scope.policy.version}. La confirmación caduca a las {new Date(preview.expiresAt).toLocaleTimeString()}.</p><label><input type="checkbox" disabled={unavailable} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo este alcance y la eliminación completa de los archivos RAW indicados, incluidas sus otras filas.</label><button disabled={unavailable||!confirmed} onClick={()=>void action('erase',{token:preview.token,requestId:preview.requestId,confirmed:true})}>Confirmar borrado irreversible</button></section>}
 <section aria-label="Purga física"><h2>Archivos físicos</h2><p>Pendientes: {snapshot.counts.pending} · Eliminados: {snapshot.counts.deleted}</p><ul>{snapshot.artifacts.map(a=><li key={a.id}>{a.class}: {a.path} · {a.status==='deleted'?'Eliminado':a.status==='pending'?'Pendiente':'Conservado según política'}</li>)}</ul><button disabled={unavailable||!snapshot.counts.pending} onClick={()=>void action('purge')}>Eliminar o reintentar hasta 25 archivos pendientes</button></section><button disabled={unavailable||!snapshot.ready} onClick={()=>void action('export')}>Exportar ledger firmado</button></>}</section>;
}
