 'use client';
import {useEffect,useState} from 'react';
export function TeamInvitation({id}:{id:string}){const [data,setData]=useState<{status:string;organization?:string;role:string;tenantId?:string}|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
useEffect(()=>{let active=true;const fragment=new URLSearchParams(location.hash.slice(1));history.replaceState(null,'',location.pathname);const accessToken=fragment.get('access_token'),refreshToken=fragment.get('refresh_token');async function load(){try{const response=await fetch(`/auth/invitations/${id}/session`,accessToken&&refreshToken?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'session',accessToken,refreshToken})}:{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error();if(active)setData(result.data);}catch{if(active)setError('La invitación no está disponible para esta sesión. Inicia sesión con el correo que recibió la invitación.');}finally{if(active)setBusy(false);}}void load();return()=>{active=false;};},[id]);
async function accept(){setBusy(true);setError('');try{const response=await fetch(`/auth/invitations/${id}/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'accept'})});const result=await response.json();if(!response.ok)throw new Error();setData(result.data);}catch{setData(null);setError('No se pudo aceptar. La invitación puede haber expirado o cambiado.');}finally{setBusy(false);}}
async function enter(){setBusy(true);setError('');try{const form=new FormData();form.set('tenant_id',data?.tenantId??'');const response=await fetch('/auth/organization',{method:'POST',body:form});if(!response.ok||new URL(response.url).pathname!=='/')throw new Error();
// eslint-disable-next-line @next/next/no-location-assign-relative-destination -- Auth and tenant cookies changed; discard pre-auth Router cache.
window.location.assign('/');}catch{setError('No se pudo abrir el equipo. Verifica tu sesión e intenta otra vez.');setBusy(false);}}
return <section className="access-flow" aria-busy={busy}><h1>Invitación al equipo</h1>{busy&&<p role="status">Validando invitación…</p>}{error&&<p role="alert">{error}</p>}{data&&data.status!=='accepted'&&<><p>{data.organization} te invita con rol {data.role}. Todavía no tienes acceso por esta invitación.</p><button disabled={busy} onClick={accept}>Aceptar invitación</button></>}{data?.status==='accepted'&&<><p>Invitación aceptada.</p><button disabled={busy} onClick={enter}>Entrar al equipo</button></>}<a href="/login">Iniciar sesión</a></section>;}
