 'use client';
import {ConfirmationDialog} from './confirmation-dialog';
import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';
type Item={id:string;email:string;role:string;status:string;version:number;delivery?:string;expiresAt?:string};
const roles=['owner','analyst','operator','viewer'];
export function TeamPanel(){const [kind,setKind]=useState('members'),[items,setItems]=useState<Item[]>([]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const generation=useRef(0);const requestId=useRef(crypto.randomUUID());
const load=useCallback(async(cursor?:string)=>{const version=++generation.current;setBusy(true);setItems([]);setError('');try{const response=await fetch(`/api/team?kind=${kind}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error();if(generation.current===version){setItems(result.data.items);setNext(result.data.nextCursor);return true;}}catch{if(generation.current===version){setNext(null);setError('No se pudo cargar el equipo. Verifica tu acceso e intenta otra vez.');}}finally{if(generation.current===version)setBusy(false);}return false;},[kind]);
useEffect(()=>{const lifecycle=generation;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);lifecycle.current++;};},[load]);
async function mutate(input:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/team',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const result=await response.json();if(!response.ok){setItems([]);throw new Error(result.error?.code==='team_last_owner'?'Debes conservar al menos un owner activo.':result.error?.code==='team_version_conflict'?'El equipo cambió. Actualiza antes de continuar.':result.error?.code==='team_configuration_required'?'Falta configurar el envío de invitaciones.':'No se pudo completar la operación. Actualiza y verifica tu acceso.');}if(await load())setNotice(input.operation==='invite'?`Invitación registrada. Envío: ${result.data.delivery==='sent'?'aceptado por Auth; pendiente de aceptación':result.data.delivery==='failed'?'fallido':result.data.delivery==='not_started'?'pendiente':'incierto; no se reenviará automáticamente'}.`:'Cambio guardado.');if(input.operation==='invite')requestId.current=crypto.randomUUID();}catch(e){setError(e instanceof Error&&!e.message.includes('fetch')?e.message:'No se pudo conectar. Intenta actualizar.');}finally{setBusy(false);}}
function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void mutate({operation:'invite',email:form.get('email'),role:form.get('role'),requestId:requestId.current,confirmed:form.get('confirmed')==='on'});}
return <section aria-busy={busy}><h1>Equipo</h1><p>Solo un owner vigente puede administrar el equipo. Las invitaciones expiran en 7 días y no conceden acceso hasta su aceptación.</p><form onSubmit={invite}><h2>Invitar integrante</h2><label>Correo <input name="email" type="email" required maxLength={254} disabled={busy}/></label><label>Rol <select name="role" defaultValue="viewer" disabled={busy}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label><input type="checkbox" name="confirmed" required disabled={busy}/>Confirmo el correo y el rol; enviar invitación.</label><button disabled={busy}>Invitar</button></form><label>Mostrar <select value={kind} disabled={busy} onChange={e=>{setNotice('');setKind(e.target.value);}}><option value="members">Miembros</option><option value="invitations">Invitaciones pendientes</option></select></label><button disabled={busy} onClick={()=>void load()}>Actualizar</button>{busy&&<p role="status">Cargando…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<ul>{items.map(item=><li key={item.id}><p>{item.email} — {item.role} — {item.status}{item.delivery?` — envío ${item.delivery}`:''}</p>{item.expiresAt&&<p>Vence: {new Date(item.expiresAt).toLocaleString()}</p>}{kind==='members'&&item.status==='active'?<><label>Nuevo rol <select aria-label={`Rol de ${item.email}`} value={item.role} disabled={busy} onChange={e=>void mutate({operation:'role',id:item.id,version:item.version,role:e.target.value})}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><ConfirmationDialog triggerLabel="Revocar" title="¿Revocar el acceso al equipo?" description={'Se revocará el acceso de '+item.email+' a esta organización. Confirma sólo si deseas retirar su membresía.'} confirmLabel="Revocar acceso" disabled={busy} onConfirm={()=>mutate({operation:'revoke',id:item.id,version:item.version})}/></>:kind==='invitations'?<button disabled={busy} onClick={()=>void mutate({operation:'cancel',id:item.id,version:item.version})}>Cancelar invitación</button>:null}</li>)}</ul>{next&&<button disabled={busy} onClick={()=>void load(next)}>Siguiente página</button>}</section>;}
