'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {Intervention,InterventionPlan,Measurement,SnapshotOption} from '../../../../../packages/interventions/index.mjs';
import {formatMinorUnits} from '../../../../../packages/metrics/money.mjs';
import type {Scope} from '../../lib/workspace/contracts';
import {SharedFilters} from '../workspace/shared-filters';

type List={items:Intervention[];unavailableCount:number};
type Operation=(id:string,body:Record<string,unknown>)=>Promise<void>;
const statusLabel:Record<Intervention['status'],string>={draft:'Borrador',approved:'Plan aprobado',active:'En ejecución',measuring:'En medición',closed:'Medición cerrada',cancelled:'Cancelada'};
const outcomeLabel={refunds:'Reembolsos observados',exposure:'Ingresos expuestos',allOrders:'Importe de órdenes'};
function text(data:FormData,key:string){return String(data.get(key)??'').trim();}
function utc(value:string){return value?new Date(value+'Z').toISOString():'';}
function inputTime(value:string|undefined|null){return value?.slice(0,19)??'';}
function money(value:string|null,m:Measurement){return value===null?'Desconocido':formatMinorUnits(value,m.currency,m.exponent);}
function optionLabel(s:SnapshotOption){return s.start+' → '+s.end+' · '+s.currency+' · '+s.basis+' · '+s.id;}
function cleanQuery(value:string){const q=new URLSearchParams(value);for(const key of ['problem_id','detail_hash','resource','format','cursor','limit','root_kind','root_id','component_id','event_id','q','status','order'])q.delete(key);return q;}
function initialScope(value:string):Scope & {basis:string;exponent?:number}{const q=cleanQuery(value),now=new Date();return {date_start:q.get('date_start')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),date_end:q.get('date_end')??new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString(),timezone:'UTC',date_basis:q.get('date_basis')??'occurred_at',currency:q.get('currency')??'USD',basis:q.get('basis')??'net',sku:q.getAll('sku'),source:q.getAll('source'),snapshot_id:q.get('snapshot_id'),...(q.has('exponent')?{exponent:Number(q.get('exponent'))}:{})};}
function pinnedQuery(scope:Scope,snapshot:string,hash:string){const q=new URLSearchParams({date_start:scope.date_start.slice(0,10),date_end:scope.date_end.slice(0,10),timezone:scope.timezone,date_basis:scope.date_basis,currency:scope.currency,basis:scope.basis??'net',snapshot_id:snapshot,scope_hash:hash});if(scope.exponent!==null&&scope.exponent!==undefined)q.set('exponent',String(scope.exponent));for(const sku of scope.sku)q.append('sku',sku);for(const source of scope.source)q.append('source',source);return q;}
function validList(value:List,query:string){const q=new URLSearchParams(query);return !!value&&Array.isArray(value.items)&&value.items.every(item=>item.recommendationSnapshotId===q.get('snapshot_id')&&item.scopeHash===q.get('scope_hash'));}
function failure(status:number){return status===401||status===403?'Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.':status===404?'No se puede consultar esta intervención o su evidencia con los permisos actuales.':status===409?'La versión, el plan o los cortes no permiten esta operación. Actualiza y revisa la cobertura, las fechas y el resultado antes de continuar.':status===400?'Revisa los campos y las fechas de la solicitud.':'No se pudo verificar la operación. Actualiza para comprobar su estado antes de continuar.';}
function Result({value}:{value:Measurement}){return <section aria-label="Resultado medido"><h3>Comparación antes y después</h3><p>{value.status==='complete'?'Medición completa':value.status==='partial'?'Medición parcial':'Medición no disponible'} · <time>{value.measuredAt}</time></p><dl><dt>Antes</dt><dd>{money(value.baselineAmountMinor,value)}</dd><dt>Después</dt><dd>{money(value.postAmountMinor,value)}</dd><dt>Diferencia observada</dt><dd>{money(value.deltaMinor,value)}</dd><dt>Población antes / después</dt><dd>{value.baselineDenominator??'Desconocida'} / {value.postDenominator??'Desconocida'}</dd></dl>{value.baselineAmountMinor===null&&<p>Subtotal conocido antes: {money(value.baselineKnownSubtotalMinor,value)}</p>}{value.postAmountMinor===null&&<p>Subtotal conocido después: {money(value.postKnownSubtotalMinor,value)}</p>}<p>La comparación describe una asociación. No demuestra ahorro causado por la intervención; una caída del importe puede reflejar cambios de volumen o composición.</p>{value.reasons.length>0&&<ul aria-label="Limitaciones de la medición">{value.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}<details><summary>Publicaciones de la medición</summary><p>Referencia: {value.baselineSnapshotId}</p><p>Posterior: {value.postSnapshotId}</p></details></section>;}
function InterventionCard({item,busy,conflict,operate}:{item:Intervention;busy:boolean;conflict:boolean;operate:Operation}){
 const [baseline,setBaseline]=useState(item.plan?.baselineSnapshotId??item.baselineOptions.find(x=>x.eligible)?.id??'');
 const locked=busy||conflict;const p=item.plan;const selected=item.baselineOptions.find(x=>x.id===baseline);
 const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(locked||!selected?.eligible)return;const data=new FormData(event.currentTarget);const plan:InterventionPlan={hypothesis:text(data,'hypothesis'),ownerId:text(data,'owner'),baselineSnapshotId:baseline,scopeHash:item.scopeHash,metricDefinitionVersion:selected.policyVersion,start:utc(text(data,'start')),end:utc(text(data,'end')),unit:text(data,'unit') as InterventionPlan['unit'],population:text(data,'population'),outcome:text(data,'outcome') as InterventionPlan['outcome'],controlPlan:text(data,'control'),maturityDays:Number(text(data,'maturity')),concurrentChanges:text(data,'changes')};void operate(item.id,{operation:'plan',expectedVersion:item.version,reason:text(data,'reason'),plan});};
 const target=({draft:'approved',approved:'active',active:'measuring',measuring:'closed',closed:'measuring'} as const)[item.status as 'draft'|'approved'|'active'|'measuring'|'closed'];
 const canAdvance=item.status==='closed'?item.canReopen:target==='approved'?item.canApprove:!!target&&item.canExecute;
 const advance=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(locked||!canAdvance)return;const data=new FormData(event.currentTarget);void operate(item.id,{operation:'transition',expectedVersion:item.version,target,reason:text(data,'reason'),...(target==='active'?{actualStart:utc(text(data,'actualStart'))}:{}),...(target==='measuring'&&item.status==='active'?{actualEnd:utc(text(data,'actualEnd'))}:{})});};
 return <article id={'intervention-'+item.id} className="record-card" aria-label={'Intervención: '+item.title}><header><span className="status">{statusLabel[item.status]} · v{item.version}</span><h2>{item.title}</h2></header><p>{item.hypothesis}</p><p>Responsable: {item.ownerId??'Sin asignar'}</p><p>Registrar el avance documenta una acción humana. Esta pantalla no cambia el CRM ni emite reembolsos.</p><details><summary>Contexto de la recomendación</summary><p>Publicación: {item.recommendationSnapshotId}</p><p>Periodo: {item.scope.date_start} → {item.scope.date_end} · {item.scope.currency} · {item.scope.basis}</p><p>SKU: {item.scope.sku.join(', ')||'Todos'} · Fuentes: {item.scope.source.join(', ')||'Todas'}</p><p>Alcance: {item.scopeHash}</p></details>
 {item.canEditPlan&&<form className="action-form" aria-label="Plan de medición" onSubmit={save}><fieldset disabled={locked} style={{minWidth:0,display:'grid',gap:'1rem'}}><legend>Fijar el plan antes de ejecutar</legend><label>Hipótesis<textarea name="hypothesis" required minLength={20} maxLength={2000} defaultValue={p?.hypothesis??item.hypothesis}/></label><label>Responsable de la intervención<select name="owner" required defaultValue={p?.ownerId??item.ownerId??''}><option value="">Seleccionar responsable</option>{item.members.filter(x=>['owner','operator'].includes(x.role)).map(m=><option key={m.id} value={m.id}>{m.id} · {m.role}</option>)}</select></label><label>Publicación de referencia para medir<select required value={baseline} onChange={e=>setBaseline(e.target.value)}><option value="">Seleccionar publicación</option>{item.baselineOptions.map(s=><option key={s.id} value={s.id} disabled={!s.eligible}>{optionLabel(s)}{s.eligible?'':' · No elegible'}</option>)}</select></label><p>La referencia de medición puede ser más reciente que el contexto de la recomendación. Se fija al aprobar este plan.</p>{!item.baselineOptions.some(s=>s.eligible)&&<p role="status">Falta una publicación compatible y completa. <Link href="/economics">Revisar publicaciones</Link></p>}<label>Inicio previsto (UTC)<input name="start" type="datetime-local" step="1" required defaultValue={inputTime(p?.start)}/></label><label>Fin previsto (UTC)<input name="end" type="datetime-local" step="1" required defaultValue={inputTime(p?.end)}/></label><label>Unidad de análisis<select name="unit" defaultValue={p?.unit??'order'}><option value="order">Orden</option><option value="customer">Cliente</option></select></label><label>Población evaluada<textarea name="population" required minLength={10} maxLength={2000} defaultValue={p?.population??''}/></label><label>Resultado a medir<select name="outcome" defaultValue={p?.outcome??'refunds'}>{Object.entries(outcomeLabel).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Plan de control<textarea name="control" required minLength={10} maxLength={2000} defaultValue={p?.controlPlan??''}/></label><small>Declara si no hay grupo de control. Una comparación descriptiva no permite atribuir causalidad.</small><label>Días de madurez<input name="maturity" type="number" required min="0" max="365" step="1" defaultValue={p?.maturityDays??0}/></label><label>Cambios concurrentes<textarea name="changes" required minLength={10} maxLength={2000} defaultValue={p?.concurrentChanges??''}/></label><label>Razón del plan<textarea name="reason" required minLength={20} maxLength={2000}/></label><button disabled={!selected?.eligible}>Guardar plan</button></fieldset></form>}
 {p&&<section aria-label="Plan guardado"><h3>{item.status==='draft'?'Plan guardado para revisión':'Plan fijado al aprobar'}</h3><p>{p.hypothesis}</p><p>Responsable registrado en el plan: {p.ownerId}</p><p>Referencia para medir: {p.baselineSnapshotId}</p><p>Inicio / fin previstos: {p.start} → {p.end}</p><p>Población: {p.population} · Unidad: {p.unit==='order'?'Orden':'Cliente'}</p><p>Resultado: {outcomeLabel[p.outcome]} · Madurez: {p.maturityDays} días</p><p>Control: {p.controlPlan}</p><p>Cambios concurrentes: {p.concurrentChanges}</p><p>Inicio real: {item.actualStart??'Pendiente'} · Fin real: {item.actualEnd??'Pendiente'}</p></section>}
 {canAdvance&&<form className="action-form" aria-label="Avanzar intervención" onSubmit={advance}><fieldset disabled={locked} style={{minWidth:0,display:'grid',gap:'1rem'}}><legend>Registrar avance</legend><label>Razón de la transición<textarea name="reason" required minLength={20} maxLength={2000}/></label>{target==='active'&&<label>Inicio real (UTC)<input name="actualStart" type="datetime-local" step="1" required/></label>}{target==='measuring'&&item.status==='active'&&<label>Fin real (UTC)<input name="actualEnd" type="datetime-local" step="1" required/></label>}<button disabled={!p||(target==='closed'&&!item.canClose)}>{item.status==='closed'?'Reabrir medición':target==='approved'?'Aprobar plan':target==='active'?'Registrar inicio':target==='measuring'?'Registrar fin e iniciar medición':'Cerrar medición'}</button>{target==='closed'&&!item.canClose&&<p>El cierre requiere una medición completa y compatible. Un resultado parcial permanece pendiente.</p>}</fieldset></form>}
 {item.status==='measuring'&&item.canExecute&&<form className="action-form" aria-label="Medir resultado" onSubmit={event=>{event.preventDefault();if(locked)return;const data=new FormData(event.currentTarget);void operate(item.id,{operation:'measure',expectedVersion:item.version,postSnapshotId:text(data,'post'),reason:text(data,'reason')});}}><fieldset disabled={locked} style={{minWidth:0,display:'grid',gap:'1rem'}}><legend>Calcular a partir de publicaciones verificadas</legend><label>Publicación posterior<select name="post" required defaultValue=""><option value="">Seleccionar publicación</option>{item.snapshotOptions.map(s=><option key={s.id} value={s.id} disabled={!s.eligible}>{optionLabel(s)}{s.eligible?'':' · No elegible'}</option>)}</select></label><label>Razón de la medición<textarea name="reason" required minLength={20} maxLength={2000}/></label><button disabled={!item.snapshotOptions.some(s=>s.eligible)}>Medir resultado</button>{!item.snapshotOptions.some(s=>s.eligible)&&<p role="status">Aún no hay un corte posterior elegible. Revisa fechas, cobertura y madurez en <Link href="/economics">publicaciones</Link>.</p>}</fieldset></form>}
 {item.canAssign&&<form className="action-form" aria-label="Reasignar intervención" onSubmit={event=>{event.preventDefault();if(locked)return;const data=new FormData(event.currentTarget);void operate(item.id,{operation:'assign',expectedVersion:item.version,ownerId:text(data,'owner'),reason:text(data,'reason')});}}><fieldset disabled={locked} style={{minWidth:0,display:'grid',gap:'1rem'}}><legend>Reasignar sin modificar el plan aprobado</legend><label>Nuevo responsable<select name="owner" required defaultValue=""><option value="">Seleccionar responsable</option>{item.members.filter(m=>['owner','operator'].includes(m.role)).map(m=><option key={m.id} value={m.id}>{m.id} · {m.role}</option>)}</select></label><label>Razón de reasignación<textarea name="reason" required minLength={20} maxLength={2000}/></label><button>Reasignar responsable</button><p>La asignación actual cambia con auditoría; el responsable que figuraba en el plan aprobado permanece en el historial.</p></fieldset></form>}
 {item.measurements.map(value=><Result key={value.id} value={value}/>)}
 {item.canCancel&&!['closed','cancelled'].includes(item.status)&&<form className="action-form" aria-label="Cancelar intervención" onSubmit={event=>{event.preventDefault();if(locked)return;const data=new FormData(event.currentTarget);void operate(item.id,{operation:'transition',expectedVersion:item.version,target:'cancelled',reason:text(data,'reason')});}}><fieldset disabled={locked} style={{minWidth:0,display:'grid',gap:'1rem'}}><legend>Cancelar conservando el historial</legend><label>Razón de cancelación<textarea name="reason" required minLength={20} maxLength={2000}/></label><button>Cancelar intervención</button><p>Cancelar no revierte una acción que ya se haya realizado fuera de VEXA.</p></fieldset></form>}
 <details><summary>Versiones del plan ({item.planHistory.length})</summary>{item.planHistory.map(version=><section key={version.version} aria-label={'Plan versión '+version.version}><h3>Plan v{version.version}</h3><p>Registrado por {version.actorId} · <time>{version.createdAt}</time></p><p>{version.plan.hypothesis}</p><dl><dt>Responsable original</dt><dd>{version.plan.ownerId}</dd><dt>Referencia de medición</dt><dd>{version.plan.baselineSnapshotId}</dd><dt>Periodo previsto</dt><dd>{version.plan.start} → {version.plan.end}</dd><dt>Población y unidad</dt><dd>{version.plan.population} · {version.plan.unit==='order'?'Orden':'Cliente'}</dd><dt>Resultado</dt><dd>{outcomeLabel[version.plan.outcome]}</dd><dt>Plan de control</dt><dd>{version.plan.controlPlan}</dd><dt>Madurez</dt><dd>{version.plan.maturityDays} días</dd><dt>Cambios concurrentes</dt><dd>{version.plan.concurrentChanges}</dd></dl></section>)}</details>
 <details><summary>Historial de la intervención ({item.history.length})</summary><ol>{item.history.map(event=><li key={event.version}><p>v{event.version} · {statusLabel[event.status as Intervention['status']]??event.status} · <time>{event.createdAt}</time></p><p>{event.reason}</p><p>Responsable del registro: {event.actorId}</p></li>)}</ol></details></article>;
}

export function InterventionsPanel({initialQuery}:{initialQuery:string}){
 const [query,setQuery]=useState(cleanQuery(initialQuery).toString()),[scope,setScope]=useState(()=>initialScope(initialQuery)),[view,setView]=useState<List|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false),[empty,setEmpty]=useState(false);
 const controller=useRef<AbortController|null>(null),epoch=useRef(0),inFlight=useRef(false),resolved=useRef(query),keys=useRef(new Map<string,string>());
 const invalidate=useCallback(()=>{controller.current?.abort();epoch.current++;inFlight.current=false;},[]);
 const load=useCallback(async(value:string)=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const generation=++epoch.current;inFlight.current=false;setView(null);setError('');setNotice('');setEmpty(false);setConflict(false);setBusy(true);
  try{const requested=cleanQuery(value);requested.set('resource','problems');const pin=await fetch('/api/workspace?'+requested,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||generation!==epoch.current)return;if(!pin.ok)throw Error(failure(pin.status));const envelope=await pin.json();if(abort.signal.aborted||generation!==epoch.current)return;const meta=envelope.data?.meta;if(!meta?.scope)throw Error('No se pudo verificar la publicación solicitada.');setScope({...meta.scope,exponent:meta.scope.exponent??undefined});if(!meta.snapshot_id||!meta.scope_hash){setEmpty(true);return;}const fixed=pinnedQuery(meta.scope,meta.snapshot_id,meta.scope_hash);
   const response=await fetch('/api/interventions?'+fixed,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||generation!==epoch.current)return;if(!response.ok)throw Error(failure(response.status));const listed=await response.json();if(abort.signal.aborted||generation!==epoch.current)return;const next=listed.data as List;if(!validList(next,fixed.toString()))throw Error('No se pudo verificar la respuesta de intervenciones.');resolved.current=fixed.toString();setScope(initialScope(fixed.toString()));setView(next);window.history.replaceState(null,'',window.location.pathname+'?'+fixed+window.location.hash);
  }catch(e){if(!abort.signal.aborted&&generation===epoch.current)setError(e instanceof Error?e.message:failure(503));}finally{if(!abort.signal.aborted&&generation===epoch.current)setBusy(false);}
 },[]);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)void load(query);});return()=>{active=false;invalidate();};},[query,load,invalidate]);
 useEffect(()=>{const back=()=>{invalidate();setView(null);setBusy(true);const value=cleanQuery(window.location.search).toString();resolved.current=value;if(value===query)void load(value);else setQuery(value);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[query,load,invalidate]);
 useEffect(()=>{if(view&&window.location.hash.startsWith('#intervention-'))document.getElementById(window.location.hash.slice(1))?.scrollIntoView({block:'start'});},[view]);
 const apply=(next:URLSearchParams)=>{next.delete('scope_hash');if(['date_start','date_end','currency','basis','sku','source','exponent'].some(k=>next.getAll(k).join('|')!==new URLSearchParams(resolved.current).getAll(k).join('|'))&&next.get('snapshot_id')===scope.snapshot_id)next.delete('snapshot_id');const value=cleanQuery(next.toString()).toString();controller.current?.abort();epoch.current++;inFlight.current=false;setView(null);setBusy(true);resolved.current=value;window.history.pushState(null,'',window.location.pathname+'?'+value);if(value===query)void load(value);else setQuery(value);};
 const operate:Operation=async(id,body)=>{if(inFlight.current)return;inFlight.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const generation=++epoch.current;setBusy(true);setError('');setNotice('');const fingerprint=JSON.stringify({id,...body});let requestKey=keys.current.get(fingerprint);if(!requestKey){requestKey=crypto.randomUUID();keys.current.set(fingerprint,requestKey);}let saved=false;
  try{const response=await fetch('/api/interventions/'+id,{method:'POST',cache:'no-store',signal:abort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestKey})});if(abort.signal.aborted||generation!==epoch.current)return;if(!response.ok){if([401,403,404].includes(response.status))setView(null);if(response.status===409)setConflict(true);throw Error(failure(response.status));}const changed=await response.json();if(abort.signal.aborted||generation!==epoch.current)return;if(!changed.data)throw Error('No se pudo verificar el cambio.');saved=true;const refresh=await fetch('/api/interventions?'+resolved.current,{cache:'no-store',signal:abort.signal});if(abort.signal.aborted||generation!==epoch.current)return;if(!refresh.ok){setView(null);throw Error('El cambio se guardó, pero falta verificar el estado actual. Actualiza antes de continuar.');}const next=await refresh.json();if(abort.signal.aborted||generation!==epoch.current)return;if(!validList(next.data,resolved.current))throw Error('La respuesta no contiene un estado verificable.');setView(next.data);setConflict(false);setNotice('Cambio guardado y verificado.');
  }catch(e){if(!abort.signal.aborted&&generation===epoch.current){if(saved)setView(null);setConflict(true);setError(e instanceof Error?e.message:failure(503));}}finally{if(!abort.signal.aborted&&generation===epoch.current){inFlight.current=false;setBusy(false);}}
 };
 return <section aria-label="Intervenciones y medición"><p className="eyebrow">Acciones y resultados</p><h1>Intervenciones</h1><p>Define y aprueba el plan antes de actuar. Mide después con publicaciones compatibles, conservando hipótesis, fechas, responsables y evidencia.</p><SharedFilters key={JSON.stringify(scope)} scope={scope} onApply={apply}/><button disabled={busy} onClick={()=>void load(resolved.current)}>Actualizar intervenciones</button>{busy&&<p role="status">Verificando intervenciones…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{empty&&<p>No hay una publicación disponible para este alcance. <Link href="/economics">Revisar publicaciones</Link></p>}{view&&<>{view.unavailableCount>0&&<p role="status">Hay intervenciones que no pueden mostrarse con la evidencia y los permisos actuales.</p>}{!view.items.length&&<p>No hay intervenciones para este alcance. Crea un borrador desde <Link href={'/recommendations?'+query}>Recomendaciones</Link>.</p>}{view.items.map(item=><InterventionCard key={item.id+':'+item.version} item={item} busy={busy} conflict={conflict} operate={operate}/>)}</>}</section>;
}
