import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';
const load=async name=>import(pathToFileURL(path.join(process.env.VEXA_CANDIDATE,'packages/metrics',name)));
const catalog={version:'SYN-catalog-independent263',currencies:{USD:2,JPY:0,KWD:3}};
const window={start:'2024-01-31T12:00:00Z',end:'2024-02-29T12:00:00Z',timezone:'UTC',date_basis:'occurred_at',horizon:null};
const metric=(value,patch={})=>({metric_id:'SYN263',tenant_id:'SYNtenant',currency:'USD',exponent:2,catalog_version:catalog.version,window,basis:'net-no-tax',grain:'order',amount_minor:value,known_subtotal:value,coverage:{known_n:1,eligible_n:1},status:'complete',missing_reasons:[],provenance:[{source:'SYN263',reference:'manual-source',version:'1'}],additive:true,...patch});
const fx=(patch={})=>({approved:true,approval_ref:'SYN263-human-approval',source:'SYN-not-live-rate',version:'1',base:'USD',quote:'JPY',rate:'1',date:'2024-02-29',rounding:'half_even',...patch});
test('F05-04 independent signed rounding and exponent rational boundaries',async()=>{const {convertMoney}=await load('money.mjs');for(const [value,mode,expected]of [['-50','half_even','0'],['-50','half_up','-1'],['-150','half_even','-2'],['-250','half_even','-2'],['-199','toward_zero','-1'],['150','half_even','2'],['250','half_even','2']])assert.equal(convertMoney(metric(value),{catalog,targetCurrency:'JPY',fx:fx({rounding:mode})}).converted.amount_minor,expected,'SIGNED_EXPONENT_ROUNDING:'+value+mode);assert.equal(convertMoney(metric('123'),{catalog,targetCurrency:'KWD',fx:fx({quote:'KWD',rate:'1.25'})}).converted.amount_minor,'1538','EXPONENT_RATIONAL_ONE_ROUND');const tiny=convertMoney(metric('100000000000000000000000000000000000000'),{catalog,targetCurrency:'USD',fx:null});assert.equal(tiny.converted.amount_minor,tiny.original.amount_minor);assert.equal(tiny.conversion,null);assert.throws(()=>convertMoney(metric('1'),{catalog,targetCurrency:'USD',fx:fx()}),{code:'FX_NOT_REQUIRED'});assert.throws(()=>convertMoney(metric('1'),{catalog,targetCurrency:'JPY',fx:fx({base:'JPY',quote:'USD'})}),{code:'APPROVED_FX_REQUIRED'});});
test('F05-04 independent precision preserves permutations cancellation and safe coverage',async()=>{const {sumMoney,validateMoney}=await load('money.mjs');const huge='9'.repeat(200);const rows=[metric(huge,{metric_id:'a'}),metric('-'+huge,{metric_id:'b'}),metric('1',{metric_id:'c'})];assert.equal(sumMoney(rows,{catalog}).amount_minor,'1');assert.deepEqual(sumMoney(rows,{catalog}),sumMoney([...rows].reverse(),{catalog}));assert.throws(()=>sumMoney([metric('0',{metric_id:'a',coverage:{known_n:Number.MAX_SAFE_INTEGER,eligible_n:Number.MAX_SAFE_INTEGER}}),metric('0',{metric_id:'b'})],{catalog}),{code:'COVERAGE_OVERFLOW'});for(const amount of ['-0','01','1.0','1e3','+1',1])assert.throws(()=>validateMoney(metric(amount),catalog),{code:'MINOR_UNITS_INVALID'});assert.throws(()=>sumMoney([metric('0',{status:'not_applicable',amount_minor:null,known_subtotal:null,coverage:{known_n:0,eligible_n:1},missing_reasons:['not eligible']})],{catalog}),{code:'NOT_APPLICABLE_IS_NOT_ZERO'});});
test('F05-04 independent month clamp leap year time zone and horizon compatibility',async()=>{const {validateWindow,containsInstant,assertCompatibleWindows}=await load('scope.mjs');const leap={...window,horizon:{as_of:window.start,quantity:1,unit:'month',version:'SYN-month-v1'}};assert.equal(validateWindow(leap).end,'2024-02-29T12:00:00.000Z');const nonleap={...leap,start:'2023-01-31T12:00:00Z',end:'2023-02-28T12:00:00Z',horizon:{...leap.horizon,as_of:'2023-01-31T12:00:00Z'}};assert.equal(validateWindow(nonleap).end,'2023-02-28T12:00:00.000Z');assert.equal(containsInstant(leap,'2024-02-29T11:59:59.999Z'),true);assert.equal(containsInstant(leap,leap.end),false);assert.throws(()=>validateWindow({...leap,timezone:'Invalid/Clock'}),{code:'TIMEZONE_INVALID'});assert.throws(()=>validateWindow({...leap,end:'2024-03-02T12:00:00Z'}),{code:'HORIZON_WINDOW_MISMATCH'});assert.throws(()=>assertCompatibleWindows([leap,{...leap,horizon:{...leap.horizon,version:'different-definition'}}]),{code:'WINDOW_OR_HORIZON_MISMATCH'});assert.throws(()=>assertCompatibleWindows([leap,{...leap,timezone:'America/Merida'}]),{code:'WINDOW_OR_HORIZON_MISMATCH'});});
