import fs from 'node:fs';import {spawnSync,spawn} from 'node:child_process';import {randomUUID,randomBytes,createHmac} from 'node:crypto';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {buildEnvironment} from './build-env.mjs';
const root=process.cwd(),require=createRequire(root+'/candidate/package.json'),{createServerClient}=require('@supabase/ssr');
const name='vexa-ui-review-'+randomUUID(),pass=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex'),owned=[];let browser,app,proxy;const results=[];const report=(label,data)=>{results.push({label,...data});console.log(JSON.stringify(results.at(-1)));fs.writeFileSync(root+'/results.json',JSON.stringify(results,null,2));};
function docker(args,input){const r=spawnSync('docker',args,{input,encoding:'utf8',timeout:30000});assert.equal(r.status,0,'Docker '+args[0]+' failed');return r.stdout.trim();}
const sql=s=>docker(['exec','-i',name+'-db','psql','-XqAt','-U','supabase_admin','-d','postgres','-v','ON_ERROR_STOP=1'],s);
const sign=claims=>{const b=[{alg:'HS256',typ:'JWT'},claims].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');return b+'.'+createHmac('sha256',secret).update(b).digest('base64url');};const anon=sign({role:'anon',iss:'supabase',exp:Math.floor(Date.now()/1000)+3600});
function run(kind,image,env,port,inner){owned.push(name+'-'+kind);docker(['run','--pull','never','-d','--name',name+'-'+kind,'--network',name,...(port?['-p',`127.0.0.1:${port}:${inner}`]:[]),...Object.entries(env).flatMap(([k,v])=>['-e',k+'='+v]),image]);}
async function wait(f){for(let i=0;i<120;i++){try{if(await f())return;}catch{}await new Promise(r=>setTimeout(r,150));}throw Error('readiness failed');}
try{
 docker(['network','create',name]);
 run('db','public.ecr.aws/supabase/postgres:17.6.1.159',{POSTGRES_PASSWORD:pass});
 await wait(()=>{try{docker(['exec',name+'-db','pg_isready','-h','127.0.0.1']);return sql("SELECT count(*) FROM pg_roles WHERE rolname='supabase_auth_admin'")==='1';}catch{return false;}});
 sql(`ALTER ROLE supabase_auth_admin PASSWORD '${pass}';ALTER ROLE authenticator PASSWORD '${pass}';`);
 run('auth','public.ecr.aws/supabase/gotrue:v2.195.0',{GOTRUE_API_HOST:'0.0.0.0',GOTRUE_API_PORT:9999,API_EXTERNAL_URL:'http://127.0.0.1:57520',GOTRUE_SITE_URL:'http://127.0.0.1:57523',GOTRUE_DB_DRIVER:'postgres',GOTRUE_DB_DATABASE_URL:`postgres://supabase_auth_admin:${pass}@${name}-db:5432/postgres`,GOTRUE_JWT_SECRET:secret,GOTRUE_JWT_AUD:'authenticated',GOTRUE_JWT_DEFAULT_GROUP_NAME:'authenticated',GOTRUE_DISABLE_SIGNUP:false,GOTRUE_MAILER_AUTOCONFIRM:true},57521,9999);
 await wait(async()=> (await fetch('http://127.0.0.1:57521/health')).ok);
 const mig=fs.readdirSync(root+'/candidate/supabase/migrations').find(x=>x.includes('identity'));sql(fs.readFileSync(root+'/candidate/supabase/migrations/'+mig,'utf8'));
 run('rest','public.ecr.aws/supabase/postgrest:v16.1',{PGRST_DB_URI:`postgres://authenticator:${pass}@${name}-db:5432/postgres`,PGRST_DB_SCHEMAS:'public',PGRST_DB_ANON_ROLE:'anon',PGRST_JWT_SECRET:secret},57522,3000);
 await wait(async()=> (await fetch('http://127.0.0.1:57522/')).ok);
 proxy=http.createServer((req,res)=>{const isAuth=req.url.startsWith('/auth/v1/');const upstream=http.request({host:'127.0.0.1',port:isAuth?57521:57522,path:req.url.replace(isAuth?'/auth/v1':'/rest/v1',''),method:req.method,headers:req.headers},r=>{res.writeHead(r.statusCode,r.headers);r.pipe(res);});upstream.on('error',()=>{res.statusCode=502;res.end();});req.pipe(upstream);});await new Promise(r=>proxy.listen(57520,'127.0.0.1',r));
 const env={...buildEnvironment(process.env,root),NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:57520',NEXT_PUBLIC_SUPABASE_ANON_KEY:anon,NEXT_PUBLIC_SITE_URL:'http://127.0.0.1:57523'};
 app=spawn(process.execPath,[root+'/candidate/node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','57523'],{cwd:root+'/candidate/apps/web',env,stdio:['ignore',fs.openSync(root+'/server.log','w'),fs.openSync(root+'/server-error.log','w')]});
 await wait(async()=> (await fetch('http://127.0.0.1:57523/api/health/version')).ok);
 const org=randomUUID(),orgB=randomUUID();sql(`INSERT INTO organizations(id,name) VALUES('${org}','SYN Review A'),('${orgB}','SYN Review B');`);
 const sessions={};for(const role of ['owner','analyst','operator','viewer']){
  const jar=new Map();const client=createServerClient('http://127.0.0.1:57520',anon,{cookies:{getAll:()=>[...jar.values()],setAll:items=>items.forEach(c=>jar.set(c.name,c))}});
  const {data,error}=await client.auth.signUp({email:`syn-${randomUUID()}@example.test`,password:randomUUID()+'Aa!'});assert.equal(error,null);assert.ok(data.session);
  sql(`INSERT INTO memberships(tenant_id,user_id,role,status) VALUES('${org}','${data.user.id}','${role}','active'),('${orgB}','${data.user.id}','viewer','active');`);
  sessions[role]={session:data.session,jar,uid:data.user.id};
  const cookie=[...jar.values()].map(c=>c.name+'='+c.value).join('; ')+'; vexa_active_org='+org;
  for(const route of ['/','/overview']){const response=await fetch('http://127.0.0.1:57523'+route,{headers:{cookie},redirect:'manual'});const html=await response.text();assert.equal(response.status,200);assert.match(html.replace(/<!--.*?-->/g,''),new RegExp('Rol: +'+role),'active role must match fixture');report(role,{route,status:response.status,rootlink:html.includes('Abrir workspace'),rolePresent:html.includes(role),unavailable:html.includes('workspace_unavailable'),privateNav:html.includes('workspace-sidebar')});}
  if(role==='owner'){
   for(const route of ['/problems','/recommendations','/explorer','/interventions','/briefs','/problems/'+randomUUID(),'/customers/'+randomUUID()]){const response=await fetch('http://127.0.0.1:57523'+route,{headers:{cookie}});const html=await response.text();report('route',{route,status:response.status,unavailable:html.includes('workspace_unavailable')});}
   const response=await fetch('http://127.0.0.1:57523/customers/'+randomUUID()+'?currency=ZZZ',{headers:{cookie}});const html=await response.text();report('customer_reset',{expected:new URL(response.url).pathname,invalid:html.includes('invalid_currency'),href:html.match(/href="([^"]+)"[^>]*>Restablecer filtros/)?.[1]});
   const reset=await fetch('http://127.0.0.1:57523'+results.find(r=>r.label==='customer_reset').href,{headers:{cookie}});report('customer_reset_result',{status:reset.status});
   const selection=await fetch('http://127.0.0.1:57523/auth/organization',{method:'POST',headers:{cookie,Origin:'http://127.0.0.1:57523','Content-Type':'application/x-www-form-urlencoded'},body:'tenant_id='+orgB,redirect:'manual'});report('selector',{status:selection.status,location:selection.headers.get('location'),setCookie:selection.headers.has('set-cookie')});
  }
 }
 for(const route of ['/overview','/overview?currency=ZZZ','/problems/'+randomUUID()]){const r=await fetch('http://127.0.0.1:57523'+route,{redirect:'manual'});const html=await r.text();report('anonymous',{route,status:r.status,location:r.headers.get('location'),privateNav:html.includes('class="workspace-sidebar"')});}
 const vjar=[...sessions.viewer.jar.values()].map(c=>c.name+'='+c.value).join('; ');
 const foreign=await fetch('http://127.0.0.1:57523/overview',{headers:{cookie:vjar+'; vexa_active_org='+randomUUID()},redirect:'manual'});report('foreign_org',{status:foreign.status,location:foreign.headers.get('location')});
 const fake={...sessions.viewer.session,access_token:sessions.viewer.session.access_token.slice(0,-5)+'ABCDE'};const vname=[...sessions.viewer.jar.keys()].find(n=>n.endsWith('-auth-token'));const forged=await fetch('http://127.0.0.1:57523/overview',{headers:{cookie:vname+'=base64-'+Buffer.from(JSON.stringify(fake)).toString('base64url')},redirect:'manual'});report('forged',{status:forged.status,location:forged.headers.get('location')});
 // Expired JWT probe: signed by own local issuer, retains real refresh token/session.
 const original=sessions.owner;const claims=JSON.parse(Buffer.from(original.session.access_token.split('.')[1],'base64url'));const expired={...original.session,access_token:sign({...claims,exp:Math.floor(Date.now()/1000)-60}),expires_at:Math.floor(Date.now()/1000)-60};
 const cookieName=[...original.jar.keys()].find(n=>n.endsWith('-auth-token'));const cookie=cookieName+'=base64-'+Buffer.from(JSON.stringify(expired)).toString('base64url');
 const response=await fetch('http://127.0.0.1:57523/overview',{headers:{cookie},redirect:'manual'});const body=await response.text();report('expired_refresh_workspace',{status:response.status,setCookie:response.headers.has('set-cookie'),rendersWorkspace:body.includes('workspace-sidebar')});
 const rootRes=await fetch('http://127.0.0.1:57523/',{headers:{cookie},redirect:'manual'});await rootRes.text();report('expired_refresh_root',{status:rootRes.status,setCookie:rootRes.headers.has('set-cookie')});
 sql(`UPDATE memberships SET status='revoked' WHERE user_id='${sessions.viewer.uid}';`);const revokedCookie=[...sessions.viewer.jar.values()].map(c=>c.name+'='+c.value).join('; ');const revoked=await fetch('http://127.0.0.1:57523/overview',{headers:{cookie:revokedCookie},redirect:'manual'});report('revoked',{status:revoked.status,location:revoked.headers.get('location')});
const resetResult=results.find(r=>r.label==='customer_reset');const problems=[];if(resetResult.href!==resetResult.expected)problems.push('DETAIL_RESET_PRESERVES_ID');if(!results.find(r=>r.label==='expired_refresh_workspace').setCookie)problems.push('WORKSPACE_REFRESH_COOKIE_REQUIRED');assert.deepEqual(problems,[]);console.log('PASS two P2 UI regressions');
}catch(e){for(const n of owned){const r=spawnSync('docker',['logs','--tail','15',n],{encoding:'utf8'});fs.writeFileSync(root+'/'+n.slice(name.length+1)+'.log',(r.stdout+r.stderr).replaceAll(pass,'[redacted]').replaceAll(secret,'[redacted]'));}throw e;}finally{await browser?.close();if(app)app.kill('SIGTERM');if(proxy)await new Promise(r=>proxy.close(r));for(const n of owned.reverse())docker(['rm','-f','-v',n]);docker(['network','rm',name]);}
