import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {setup,iso} from './fixture.mjs';
const candidate=path.resolve(process.env.VEXA_CANDIDATE??process.cwd()),file=path.join(candidate,'packages/gateway/index.mjs');
let createGateway;
test('F04-01 gateway implementation exists at the candidate boundary',async()=>{assert.ok(fs.existsSync(file),'F04_GATEWAY_IMPLEMENTATION_MISSING');({createGateway}=await import(pathToFileURL(file)));assert.equal(typeof createGateway,'function','F04_GATEWAY_FACTORY_MISSING');});
const blocked=async fixture=>{const result=await fixture.run();assert.equal(result?.ok,false,'F04_BLOCKED_RESULT_REQUIRED');assert.equal(fixture.state.fetches.length,0,'F04_NO_TRANSPORT_WITHOUT_ELIGIBILITY');return result;};
const subject=options=>{assert.equal(typeof createGateway,'function','F04_GATEWAY_IMPLEMENTATION_MISSING');return setup(createGateway,options);};
test('F04 runtime is disabled by default even when synthetic credentials and policy are supplied',async()=>{for(const options of [{omitRuntime:true},{runtime:'stub'},{runtime:'disabled'}]){const f=subject(options);await blocked(f);assert.equal(f.state.reserved.length,0,'F04_STUB_MUST_NOT_RESERVE');}});
test('F04 explicit runtime routes one eligible model with the required provider restrictions',async()=>{const f=subject();const result=await f.run();assert.equal(result.ok,true,'F04_ELIGIBLE_POSITIVE_CONTROL');assert.equal(f.state.fetches.length,1);const sent=f.state.fetches[0];assert.equal(sent.url,'https://openrouter.ai/api/v1/chat/completions');assert.equal(sent.redirect,'error');assert.equal(sent.body.model,'synthetic/model-a');assert.deepEqual(sent.body.provider.only,['synthetic-provider-eu']);assert.equal(sent.body.provider.allow_fallbacks,false);assert.equal(sent.body.provider.data_collection,'deny');assert.equal(sent.body.provider.zdr,true);assert.equal(sent.body.provider.require_parameters,true);assert.equal(sent.body.response_format.type,'json_schema');});
test('F04 allowed model list is required and intersects with public catalog membership',async()=>{for(const allowedModels of [undefined,[],['synthetic/not-selected']])await blocked(subject({policy:{allowedModels}}));await blocked(subject({catalog:{models:[{id:'synthetic/other',contextTokens:200000,supportedParameters:['response_format']}]}}));});
test('F04 invalid or empty catalog never becomes allow all',async()=>{for(const catalog of [{models:[]},{models:null},{models:{}},{version:''},{version:null},{fetchedAt:'not-a-date'},{expiresAt:'not-a-date'},{fetchedAt:iso(1)},{expiresAt:iso(0)},{expiresAt:iso(-1)},{fetchedAt:iso(-1000),expiresAt:iso(-2000)}])await blocked(subject({catalog}));const f=subject();f.options.catalog=undefined;const absent=createGateway(f.options);const result=await absent.extract(f.input);assert.equal(result.ok,false);assert.equal(f.state.fetches.length,0,'F04_MISSING_CATALOG_MUST_BLOCK');});
test('F04 catalog capability and context bounds constrain the configured endpoint',async()=>{for(const entry of [{id:'synthetic/model-a',contextTokens:200000,supportedParameters:[]},{id:'synthetic/model-a',contextTokens:200000,supportedParameters:['temperature']},{id:'synthetic/model-a',contextTokens:50,supportedParameters:['response_format']},{id:'synthetic/model-a',contextTokens:0,supportedParameters:['response_format']}])await blocked(subject({catalog:{models:[entry]}}));});
test('F04 collection deny and ZDR are distinct from endpoint residency attestations',async()=>{for(const candidate of [{zdr:false},{zdr:undefined},{dataCollection:'allow'},{residency:'us'},{privacyAttestation:null},{privacyAttestation:{version:'SYN',residencyEnforced:false,expiresAt:iso(60000)}}])await blocked(subject({candidate}));const f=subject({policy:{requireZdr:false},candidate:{zdr:false}});assert.equal((await f.run()).ok,true,'F04_DENY_WITHOUT_ZDR_POSITIVE_CONTROL');assert.equal(f.state.fetches[0].body.provider.data_collection,'deny');assert.equal(f.state.fetches[0].body.provider.zdr,undefined,'F04_DENY_NOT_PRESENTED_AS_ZDR');});
test('F04 catalog metadata cannot grant private endpoint attestation',async()=>{await blocked(subject({candidate:{privacyAttestation:null},catalog:{models:[{id:'synthetic/model-a',contextTokens:200000,supportedParameters:['response_format'],zdr:true,residency:'eu',privacyAttestation:{version:'untrusted-public',residencyEnforced:true,expiresAt:iso(60000)}}]}}));});
test('F04 fallback preserves model/provider/residency intersection',async()=>{const seed=subject(),first=seed.modelsByRole.extraction[0];const f=subject({models:[first,{...first,model:'synthetic/model-b',provider:'synthetic-provider-us',residency:'us'}],hooks:{transport:({response})=>response(503)}});const result=await f.run();assert.equal(result.ok,false);assert.equal(f.state.fetches.length,1,'F04_INCOMPATIBLE_FALLBACK_SENT');assert.deepEqual(f.state.fetches.map(x=>x.body.model),['synthetic/model-a']);const valid=subject({models:[first,{...first,model:'synthetic/model-b',provider:'synthetic-secondary-eu'}],hooks:{transport:({state,response})=>response(state.fetches.length===1?503:200)}});assert.equal((await valid.run()).ok,true,'F04_VALID_FALLBACK_CONTROL');assert.deepEqual(valid.state.fetches.map(x=>x.body.model),['synthetic/model-a','synthetic/model-b']);});
for(const step of ['reserve','attempt'])test('F04 catalog expiring during '+step+' is revalidated immediately before transport',async()=>{const hooks={[step]:async({advance,value})=>{if(step==='reserve'||value.state==='started')advance(60000);}};const f=subject({hooks});await blocked(f);assert.equal(f.state.settled.length,1);assert.equal(f.state.settled[0].actualMinor,'0','F04_UNSENT_HAS_KNOWN_ZERO_COST');});
test('F04 fallback cannot send after catalog expires while receiving first response',async()=>{const seed=subject(),first=seed.modelsByRole.extraction[0];const f=subject({models:[first,{...first,model:'synthetic/model-b',provider:'synthetic-secondary-eu'}],hooks:{transport:({response})=>response(503),attempt:async({advance,value})=>{if(value.state==='received')advance(60000);}}});assert.equal((await f.run()).ok,false);assert.equal(f.state.fetches.length,1,'F04_STALE_FALLBACK_SENT');});
test('F04 policy catalog and endpoint config are snapshotted across caller mutations',async()=>{const f=subject();f.policy.allowedModels.length=0;f.policy.providers.length=0;f.policy.residency='us';f.catalog.models[0].id='tampered';f.catalog.expiresAt=iso(-1);f.modelsByRole.extraction[0].provider='tampered';assert.equal((await f.run()).ok,true,'F04_CONFIG_REFERENCE_MUTATION_CHANGED_APPROVAL');assert.equal(f.state.fetches[0].body.model,'synthetic/model-a');assert.deepEqual(f.state.fetches[0].body.provider.only,['synthetic-provider-eu']);});
test('F04 caller cannot extend expired snapshot during budget await',async()=>{const f=subject({hooks:{reserve:async({advance,catalog})=>{catalog.expiresAt=iso(120000);advance(60000);}}});await blocked(f);});

for(const field of ['privacyAttestation','pricing'])test('F04 endpoint '+field+' freshness is independent from catalog freshness',async()=>{const seed=subject(),original=seed.modelsByRole.extraction[0];const candidate=field==='privacyAttestation'?{privacyAttestation:{...original.privacyAttestation,expiresAt:iso(500)}}:{pricing:{...original.pricing,validUntil:iso(500)}};await blocked(subject({candidate,hooks:{attempt:async({advance,value})=>{if(value.state==='started')advance(500);}}}));});

test('F04 expiry between eligibility and context lookup returns policy_blocked without throwing',async()=>{const f=subject();let tick=0;const initial=Date.parse(f.catalog.fetchedAt)+1000,end=Date.parse(f.catalog.expiresAt);f.options.clock.now=()=>++tick>=3?end:initial;let result;await assert.doesNotReject(async()=>{result=await blocked(f);},'F04_EXPIRY_BOUNDARY_MUST_RETURN_POLICY_BLOCKED');assert.equal(result.error.code,'policy_blocked','F04_EXPIRY_BOUNDARY_MUST_RETURN_POLICY_BLOCKED');assert.equal(f.state.reserved.length,0);});
