import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {setup,q} from './harness.mjs';import {seedRecommendations,scope,createReader} from './fixtures.mjs';import './pure.mjs';
const base='/api/recommendations',trace=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const envelope=r=>{assert.equal(r.data.contract_version,'f06-recommendations-v1');assert.match(r.data.meta?.trace_id??'',trace);if(r.status!==200)assert.equal(r.data.error?.retryable,r.status===503);};
async function bounded(p,label){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('RECOMMENDATION_HANDSHAKE:'+label)),20000);})]);}finally{clearTimeout(timer);}}
const reason='SYN human reviewed the specific captured evidence, conditions and responsible operational team.';
test('F06-03 conditional recommendations persist safely and create idempotent drafts only',{timeout:480000},async t=>{
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate&&fs.existsSync(path.join(candidate,'packages/recommendations/index.mjs')),'RECOMMENDATIONS_IMPLEMENTATION_MISSING');const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-recommendations277-'));fs.chmodSync(evidence,0o700);console.log('F0603_RUNNING:'+evidence);let h;
 const step=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();}catch(e){failure=e;throw e;}});if(failure)throw Error('RECOMMENDATION_PREREQUISITE:'+name,{cause:failure});};
 try{
 h=await setup(candidate,evidence);let f,query,rec,second,version1,draft,keyPayload,operationalBaseline,viewer;
 const ok=async p=>{const r=await p;assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};
 const request=async(actor,route,body)=>{const r=await h.request(actor,route,body);envelope(r);return r;};
 const get=(id=rec.id,actor=h.A)=>request(actor,base+'/'+id);
 const mutate=(body,id=rec.id,actor=h.A)=>request(actor,base+'/'+id,body);
 const draftRequest=(payload,id=rec.id,actor=h.A)=>request(actor,base+'/'+id+'/interventions',payload);
 const generate=(problemId,key=randomUUID(),actor=h.A)=>request(actor,base,{operation:'generate',query:query.toString(),problemId,requestKey:key});
 const operational=()=>h.json("SELECT jsonb_build_object('jobs',(SELECT count(*) FROM jobs),'outbox',(SELECT count(*) FROM outbox),'crmSettings',(SELECT count(*) FROM crm_sync_settings))");
 const panel=()=>h.p.getByRole('region',{name:'Recomendaciones con evidencia',exact:true});
 const card=()=>panel().getByRole('article',{name:'Recomendación: '+rec.title,exact:true});
 const waitPost=(page,route)=>page.waitForResponse(r=>new URL(r.url()).pathname===route&&r.request().method()==='POST');
 await step('real captured evidence and financial scope seed recommendations without external operations',async()=>{
  f=await seedRecommendations(h,async()=>{});viewer=await createReader(h);query=new URLSearchParams({date_start:scope.start.slice(0,10),date_end:scope.end.slice(0,10),timezone:'UTC',date_basis:'occurred_at',currency:'USD',basis:scope.basis,snapshot_id:f.snapshot.id});const workspace=await ok(h.request(h.A,'/api/workspace?'+query.toString()+'&resource=problems'));query.set('scope_hash',workspace.meta.scope_hash);
  const list=await ok(request(h.A,base+'?'+query));assert.equal(list.items.length,0);assert.ok(list.problemOptions.some(p=>p.id===f.p1.id));operationalBaseline=operational();
  const browser=await h.browser(),ctx=await browser.newContext({timezoneId:'America/Merida'});ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const i=v.indexOf('=');return{name:v.slice(0,i),value:v.slice(i+1),url:h.base};}));h.ctx=ctx;h.p=await ctx.newPage();
  await h.p.goto(h.base+'/problems?'+query);await h.p.getByRole('region',{name:'Problemas con alcance compartido'}).getByRole('link',{name:f.p1.label,exact:true}).click();await h.p.getByRole('region',{name:'Detalle financiero autorizado'}).getByRole('link',{name:'Revisar recomendaciones de este problema',exact:true}).click();await panel().getByRole('button',{name:'Proponer recomendación',exact:true}).waitFor();assert.equal(await panel().getByLabel('Problema para recomendar',{exact:true}).inputValue(),f.p1.id);assert.equal(new URL(h.p.url()).searchParams.get('snapshot_id'),f.snapshot.id);assert.equal(new URL(h.p.url()).searchParams.get('scope_hash'),query.get('scope_hash'));
  const saved=waitPost(h.p,base);await panel().getByRole('button',{name:'Proponer recomendación',exact:true}).click();const response=await saved;assert.equal(response.status(),200);rec=(await response.json()).data;assert.equal(rec.problemId,f.p1.id);assert.equal(rec.problemVersion,1);assert.equal(rec.snapshotId,f.snapshot.id);assert.equal(rec.scopeHash,query.get('scope_hash'));assert.ok(rec.preconditions.length);assert.ok(rec.evidenceRefs.length);assert.equal(rec.automaticExternalAction,false);assert.equal(rec.causalClaim,false);assert.ok(rec.evidenceRefs.some(e=>e.runId===f.p1.extraction.prepared.runId&&e.messageRevisionId===f.p1.extraction.span.message_revision_id));version1=structuredClone(rec.history.find(v=>v.version===1));await card().waitFor();second=await ok(generate(f.p2.id));fs.writeFileSync(path.join(evidence,'initial-recommendations.json'),JSON.stringify({rec,second},null,2));
 });
 await step('publication rejects missing conditions and injected evidence instead of weakening the definition',async()=>{
  const revision={operation:'revise',expectedVersion:rec.version,action:rec.action,preconditions:[],rationale:rec.rationale,ownerId:h.A.id,reason};assert.equal((await mutate(revision)).status,400);assert.equal((await mutate({...revision,preconditions:rec.preconditions,action:''})).status,400);assert.equal((await request(h.A,base,{operation:'generate',query:query.toString(),problemId:f.p1.id,requestKey:randomUUID(),evidenceRefs:[]})).status,400);assert.equal((await generate(randomUUID())).status,404);assert.equal((await get()).data.data.version,1);assert.equal((await get()).data.data.history.length,1);
 });
 await step('real revision form assigns an authorized owner and survives reload with immutable history',async()=>{
  const c=card();await c.getByLabel('Acción propuesta',{exact:true}).fill('SYN Revisar las entregas citadas de P1 con el responsable operacional.');await c.getByLabel('Condiciones previas, una por línea',{exact:true}).fill('SYN Revisar las citas capturadas\nSYN Confirmar alcance antes de actuar');await c.getByLabel('Justificación de la recomendación',{exact:true}).fill('SYN Las conversaciones citadas justifican investigación, no confirman causa ni ahorro.');await c.getByLabel('Responsable de la recomendación',{exact:true}).selectOption(h.bot.id);await c.getByLabel('Razón del cambio',{exact:true}).fill(reason);const saved=waitPost(h.p,base+'/'+rec.id);await c.getByRole('button',{name:'Guardar revisión',exact:true}).click();assert.equal((await saved).status(),200);rec=await ok(get());assert.equal(rec.version,2);assert.equal(rec.ownerId,h.bot.id);assert.deepEqual(rec.history.find(v=>v.version===1),version1);await h.p.reload();await card().getByLabel('Acción propuesta',{exact:true}).waitFor();assert.equal(await card().getByLabel('Acción propuesta',{exact:true}).inputValue(),rec.action);assert.equal(await card().getByLabel('Responsable de la recomendación',{exact:true}).inputValue(),h.bot.id);
 });
 await step('real CAS rejection preserves the unsaved form and never pretends an optimistic save',async()=>{
  const c=card(),pending='SYN BORRADOR LOCAL NO GUARDADO';await c.getByLabel('Acción propuesta',{exact:true}).fill(pending);await c.getByLabel('Razón del cambio',{exact:true}).fill(reason);const actor={...h.bot,tenant:h.A.tenant};h.sql(`UPDATE memberships SET role='operator' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);const other=await ok(mutate({operation:'revise',expectedVersion:rec.version,action:'SYN revisión concurrente autorizada del operador',preconditions:rec.preconditions,rationale:rec.rationale,ownerId:h.bot.id,reason},rec.id,actor));const saved=waitPost(h.p,base+'/'+rec.id);await c.getByRole('button',{name:'Guardar revisión',exact:true}).click();assert.equal((await saved).status(),409);assert.equal(await c.getByLabel('Acción propuesta',{exact:true}).inputValue(),pending,'CAS_REJECTION_PRESERVES_UNSAVED_DRAFT');assert.equal((await get()).data.data.action,other.action);await panel().getByRole('button',{name:'Actualizar recomendaciones',exact:true}).click();await h.p.waitForFunction(({id,action})=>[...document.querySelectorAll('article')].some(s=>s.getAttribute('aria-label')?.startsWith('Recomendación:')&&[...s.querySelectorAll('textarea')].some(x=>x.value===action)),{id:rec.id,action:other.action});rec=await ok(get());assert.equal(rec.version,3);
 });
 await step('dismiss and reopen require reasons and preserve status history',async()=>{
  assert.equal((await mutate({operation:'state',expectedVersion:rec.version,status:'dismissed',reason:''})).status,400);await card().getByLabel('Razón para cambiar el estado',{exact:true}).fill('SYN descartada después de revisar condiciones operacionales insuficientes.');let saved=waitPost(h.p,base+'/'+rec.id);await card().getByRole('button',{name:'Descartar recomendación',exact:true}).click();assert.equal((await saved).status(),200);rec=await ok(get());assert.equal(rec.status,'dismissed');assert.equal((await draftRequest({expectedVersion:rec.version,requestKey:randomUUID()})).status,409);await card().getByRole('button',{name:'Reabrir recomendación',exact:true}).waitFor();await card().getByLabel('Razón para cambiar el estado',{exact:true}).fill('SYN condiciones revisadas de nuevo; retomar investigación sin ejecutar acciones externas.');saved=waitPost(h.p,base+'/'+rec.id);await card().getByRole('button',{name:'Reabrir recomendación',exact:true}).click();assert.equal((await saved).status(),200);rec=await ok(get());assert.equal(rec.status,'proposed');assert.ok(rec.history.some(v=>v.status==='dismissed'&&v.reason.includes('descartada')));assert.deepEqual(rec.history.find(v=>v.version===1),version1);
 });
 await step('committed draft with lost response retries the same key and double submission creates only one draft',async()=>{
  let seen,finish;const started=new Promise(r=>seen=r),done=new Promise(r=>finish=r);let dropped=false,uiAttempts=0;const route=base+'/'+rec.id+'/interventions';
  await h.p.route('**'+route,async intercepted=>{uiAttempts++;if(!dropped){dropped=true;try{keyPayload=intercepted.request().postDataJSON();const response=await intercepted.fetch();assert.equal(response.status(),200);draft=(await response.json()).data;seen();await intercepted.abort('failed');}finally{finish();}}else await intercepted.continue();});
  await card().getByRole('button',{name:'Crear intervención borrador',exact:true}).dblclick();await bounded(started,'real-draft-committed');await bounded(done,'lost-response-delivered');await panel().getByRole('alert').waitFor();assert.equal(uiAttempts,1,'UI_DOUBLE_CLICK_SENDS_ONE_DRAFT');assert.equal(await card().getByRole('region',{name:'Borradores de intervención',exact:true}).count(),0,'LOST_RESPONSE_NEVER_PRETENDS_SUCCESS');await h.p.unroute('**'+route);assert.equal(draft.status,'draft');assert.equal(draft.executionEnabled,false);assert.equal(h.sql(`SELECT count(*) FROM interventions WHERE tenant_id=${q(h.A.tenant)} AND recommendation_id=${q(rec.id)}`),'1');
  const retry=waitPost(h.p,route);await card().getByRole('button',{name:'Crear intervención borrador',exact:true}).click();const response=await retry;assert.equal(response.status(),200);assert.deepEqual(response.request().postDataJSON(),keyPayload,'LOST_RESPONSE_RETRY_MUST_KEEP_EXACT_KEY_AND_VERSION');assert.equal((await response.json()).data.id,draft.id);
  const concurrent=await Promise.all([draftRequest(keyPayload),draftRequest(keyPayload)]);for(const r of concurrent){assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.data.data.id,draft.id);}assert.equal(h.sql(`SELECT count(*) FROM interventions WHERE tenant_id=${q(h.A.tenant)} AND recommendation_id=${q(rec.id)}`),'1');assert.equal((await draftRequest(keyPayload,second.id)).status,409,'SAME_KEY_CANNOT_MOVE_TO_OTHER_RECOMMENDATION');
  const before=rec;rec=await ok(mutate({operation:'revise',expectedVersion:rec.version,action:rec.action,preconditions:rec.preconditions,rationale:rec.rationale,ownerId:rec.ownerId,reason:reason+' Nuevo contexto revisado.'}));assert.equal((await draftRequest({...keyPayload,expectedVersion:rec.version})).status,409,'SAME_KEY_DIFFERENT_VERSION_CONFLICT');assert.equal((await draftRequest(keyPayload)).data.data.id,draft.id,'ORIGINAL_SUCCESSFUL_REPLAY_STABLE_AFTER_REVISION');assert.equal(draft.recommendationVersion,before.version);assert.equal(draft.snapshotId,f.snapshot.id);assert.equal(draft.scopeHash,query.get('scope_hash'));assert.deepEqual(operational(),operationalBaseline,'DRAFT_HAS_NO_JOBS_OR_CRM_OUTBOX_SIDE_EFFECTS');fs.writeFileSync(path.join(evidence,'draft-recovery.json'),JSON.stringify({draft,keyPayload,concurrentIds:concurrent.map(x=>x.data.data.id)}));
 });
 await step('viewer writes forbidden, cross tenant hidden, CSRF rejected and assigned owner authorized',async()=>{
  assert.equal((await get(rec.id,viewer)).status,200);assert.equal((await generate(f.p2.id,randomUUID(),viewer)).status,403);assert.equal((await mutate({operation:'state',expectedVersion:rec.version,status:'dismissed',reason},rec.id,viewer)).status,403);assert.equal((await draftRequest(keyPayload,rec.id,viewer)).status,403);assert.equal((await get(rec.id,h.B)).status,404);assert.equal((await get(rec.id,null)).status,401);assert.equal((await get(rec.id,{...h.A,tenant:h.B.tenant})).status,403);
  assert.equal((await mutate({operation:'revise',expectedVersion:rec.version,action:rec.action,preconditions:rec.preconditions,rationale:rec.rationale,ownerId:h.B.id,reason})).status,404);const bad=await fetch(h.base+base+'/'+rec.id,{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify({operation:'state',expectedVersion:rec.version,status:'dismissed',reason})});assert.equal(bad.status,403);
 });
 await step('captured recommendation remains historical after real problem merge but cannot mutate stale evidence context',async()=>{
  const prior=await ok(get()),ids=h.json(`SELECT jsonb_agg(embedding_id) FROM problem_embedding_members WHERE tenant_id=${q(h.A.tenant)} AND problem_id IN(${q(f.p1.id)},${q(f.p2.id)})`);await ok(h.request(h.A,'/api/problems',{operation:'merge',parents:[{problemId:f.p1.id,expectedVersion:1},{problemId:f.p2.id,expectedVersion:1}],children:[{label:'SYN merged problem after recommendation',embeddingIds:ids}],reason,approved:true}));const current=await ok(get());assert.equal(current.stale,true);assert.equal(current.canMutate,false);assert.equal(current.action,prior.action);assert.deepEqual(current.evidenceRefs,prior.evidenceRefs);assert.deepEqual(current.history,prior.history);assert.equal((await mutate({operation:'state',expectedVersion:current.version,status:'dismissed',reason})).status,409);assert.equal((await draftRequest({expectedVersion:current.version,requestKey:randomUUID()})).status,409);await panel().getByRole('button',{name:'Actualizar recomendaciones',exact:true}).click();await card().waitFor();
 });
 await step('withdrawn current evidence denies replay and removes page-wide recommendation data',async()=>{
  h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(f.p1.extraction.a.connection)}`);try{for(const r of [await get(),await draftRequest(keyPayload)]){assert.ok([403,404].includes(r.status),JSON.stringify(r));assert.equal(r.data.data,undefined);}await panel().getByRole('button',{name:'Actualizar recomendaciones',exact:true}).click();await panel().getByRole('alert').waitFor();assert.match(await panel().getByRole('alert').innerText(),/Tu acceso cambió|No hay una recomendación o evidencia autorizada/);assert.equal(await h.p.getByRole('article',{name:/^Recomendación:/}).count(),0);assert.ok(!(await h.p.locator('body').innerText()).includes(rec.action));}finally{h.sql(`UPDATE connections SET status='active' WHERE id=${q(f.p1.extraction.a.connection)}`);}await panel().getByRole('button',{name:'Actualizar recomendaciones',exact:true}).click();await card().waitFor();
 });
 await step('late list response never repopulates after authorization denial and protected history return',async()=>{
  let release,seen,finish;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r),done=new Promise(r=>finish=r);h.releaseHold=release;let captured=false;await h.p.route('**/api/recommendations?*',async intercepted=>{if(!captured){captured=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);const body=await response.body();seen();await held;await intercepted.fulfill({status:200,headers:response.headers(),body}).catch(()=>{});}finally{finish();}}else await intercepted.continue();});await panel().getByRole('button',{name:'Actualizar recomendaciones',exact:true}).click();await bounded(started,'authorized-list-captured');h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);await h.p.getByRole('navigation',{name:'Espacio de trabajo',exact:true}).getByRole('link',{name:'Resumen',exact:true}).click();const denied=h.p.getByText('Acceso denegado. Inicia sesión con una cuenta que tenga una organización activa.',{exact:true});await denied.waitFor();await h.p.goBack();await Promise.race([denied.waitFor(),panel().getByText('Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.',{exact:true}).waitFor()]);release();await bounded(done,'authorized-list-released');await h.p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await h.p.getByRole('article',{name:/^Recomendación:/}).count(),0);assert.ok(!(await h.p.locator('body').innerText()).includes(rec.action));await h.p.unroute('**/api/recommendations?*');h.releaseHold=null;await h.p.screenshot({path:path.join(evidence,'revoked-late-list.png'),fullPage:true});
 });
 await step('transport observation and database effects prove zero external CRM execution',async()=>{
  const rows=fs.readFileSync(path.join(evidence,'outbound-attempts.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);assert.ok(rows.length>0,'REAL_AUTH_TRAFFIC_OBSERVED');assert.deepEqual(rows.filter(x=>x.blocked),[],'ZERO_EXTERNAL_TRANSPORT_ATTEMPTS');assert.ok(rows.every(x=>/^\/(auth|storage|rest)\/v1\//.test(x.path)),'NO_NON_AUTH_STORAGE_REST_HTTP_CALL');assert.deepEqual(operational(),operationalBaseline);assert.equal(h.sql("SELECT count(*) FROM interventions WHERE status<>'draft'"),'0');fs.writeFileSync(path.join(evidence,'no-crm-execution.json'),JSON.stringify({observedLocalRequests:rows.length,externalAttempts:0,operationalCounts:operational()}));
 });
 h.verifySources();
 }finally{h?.releaseHold?.();if(h?.p&&!h.p.isClosed()){fs.writeFileSync(path.join(evidence,'last-dom.html'),await h.p.content().catch(()=>''));fs.writeFileSync(path.join(evidence,'last-url.txt'),h.p.url());await h.p.screenshot({path:path.join(evidence,'last-ui.png'),fullPage:true}).catch(()=>{});}if(h)await h.close();console.log('F0603_EVIDENCE:'+evidence);}
});
