import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'CANDIDATE_REQUIRED');
test('F06-03 independent durable recommendation implementation mandatory',async()=>{const file=path.join(candidate,'packages/recommendations/index.mjs');assert.ok(fs.existsSync(file),'RECOMMENDATION_IMPLEMENTATION_MISSING');const {createRecommendationRepository}=await import(pathToFileURL(file));assert.equal(typeof createRecommendationRepository,'function');const repo=createRecommendationRepository({database:{transaction(){throw Error('NO_DATABASE_ON_FACTORY');}}});for(const name of ['list','get','generate','revise','setState','createDraft'])assert.equal(typeof repo[name],'function','RECOMMENDATION_METHOD_REQUIRED:'+name);});

const generatorFile=path.join(candidate,'packages/recommendations/generate.mjs');
async function generator(){assert.ok(fs.existsSync(generatorFile),'RECOMMENDATION_GENERATOR_MISSING');return (await import(pathToFileURL(generatorFile))).proposeRecommendation;}
const problem={id:'SYN-P1',title:'SYN documented issue',version:7};const evidence=(category='delivery',severity='low')=>[{runId:'SYN-RUN',messageRevisionId:'SYN-MESSAGE',quote:'SYN customer reports observed symptom',quoteHash:'a'.repeat(64),role:'customer',category,severity}];
test('F06-03 no recommendation without problem and captured evidence',async()=>{const fn=await generator();for(const evidenceRefs of [[],null,[{...evidence()[0],quote:'   '}]])assert.throws(()=>fn({problem,evidenceRefs}),e=>e.status===400||e.statusCode===400);assert.throws(()=>fn({problem:null,evidenceRefs:evidence()}));});
test('F06-03 category evidence determines an operationally specific action',async()=>{const fn=await generator(),delivery=fn({problem,evidenceRefs:evidence('delivery')}),refund=fn({problem,evidenceRefs:evidence('refund')});assert.notEqual(delivery.action,refund.action);assert.match(delivery.action,/transport|entrega/i);assert.match(refund.action,/pagos|reversos/i);for(const x of [delivery,refund]){assert.ok(x.preconditions.length>=3);assert.equal(x.automaticExternalAction,false);assert.equal(x.causalClaim,false);assert.equal(x.generatorVersion,'conditioned-rules-v1');assert.match(x.rationale,/versión 7/);}});
test('F06-03 single low frequency smoke remains critical with unknown money',async()=>{const fn=await generator();for(const input of [{evidenceRefs:evidence('smoke','unknown')},{evidenceRefs:evidence('delivery','critical')},{evidenceRefs:evidence(),causality:{claim:{criticalReview:true,state:'hypothesis',version:2,evidenceIds:[]}}}]){const x=fn({problem,...input});assert.equal(x.priority,'critical','CRITICAL_REVIEW_MUST_SURVIVE');assert.match(x.action,/humana urgente/);assert.ok(x.preconditions.some(p=>/no autoriza recalls/.test(p)));assert.equal(x.automaticExternalAction,false);}});
test('F06-03 hypothesis does not become confirmed cause and money is never invented',async()=>{const fn=await generator(),input={problem,evidenceRefs:evidence(),causality:{claim:{state:'hypothesis',version:3,probableCause:'SYN unconfirmed',evidenceIds:['SYN-ID']}}},a=fn(input),b=fn({...input,money:{amountMinor:'999999999999999999999999',savings:'500'}});assert.deepEqual(a,b);assert.equal(a.causalState,'hypothesis');assert.match(a.rationale,/no acreditan/);assert.ok(a.preconditions.some(p=>/sin confirmación/.test(p)));assert.doesNotMatch(a.rationale,/999999|500/);const c=fn({...input,causality:{claim:{state:'confirmed',version:4,probableCause:'SYN operational finding',evidenceIds:['SYN-OP-EVIDENCE']}}});assert.match(c.rationale,/operacional versión 4 confirma/);assert.equal(c.causalClaim,false);assert.equal(c.automaticExternalAction,false);});
test('F06-03 causal critical-lane mutant is killed by semantic assertion and restored',async()=>{const {mkdtempSync,cpSync,rmSync,writeFileSync}=await import('node:fs');const {tmpdir}=await import('node:os');const tmp=mkdtempSync(path.join(tmpdir(),'vexa-rec278-mutant-'));try{cpSync(path.join(candidate,'packages'),path.join(tmp,'packages'),{recursive:true});const file=path.join(tmp,'packages/recommendations/generate.mjs'),original=fs.readFileSync(file,'utf8'),anchor="priority:critical?'critical':priorities?'high':'normal'";assert.ok(original.includes(anchor),'CAUSAL_MUTANT_ANCHOR');const check=fn=>assert.equal(fn({problem,evidenceRefs:evidence('smoke','unknown')}).priority,'critical','CRITICAL_REVIEW_MUST_SURVIVE');check((await import(pathToFileURL(file).href+'?baseline')).proposeRecommendation);writeFileSync(file,original.replace(anchor,"priority:priorities?'high':'normal'"));const mutant=(await import(pathToFileURL(file).href+'?mutant')).proposeRecommendation;assert.throws(()=>check(mutant),e=>e.code==='ERR_ASSERTION'&&e.message.includes('CRITICAL_REVIEW_MUST_SURVIVE'),'MUTANT_SEMANTIC_ASSERTION_REQUIRED');writeFileSync(file,original);check((await import(pathToFileURL(file).href+'?restored')).proposeRecommendation);}finally{rmSync(tmp,{recursive:true,force:true});}});
