import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
test('F06-03 durable recommendation implementation exists',()=>assert.ok(process.env.VEXA_CANDIDATE&&fs.existsSync(path.join(process.env.VEXA_CANDIDATE,'packages/recommendations/index.mjs')),'RECOMMENDATIONS_IMPLEMENTATION_MISSING'));
import os from 'node:os';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import {once} from 'node:events';import {fileURLToPath} from 'node:url';
test('control transport observer forwards local bytes and records blocked external attempts',async()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'recommendation-audit277-')),journal=path.join(tmp,'audit.jsonl');let calls=0;
 const server=createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;assert.equal(body,'SYN-CONTROL-CALIBRATION');calls++;res.writeHead(201,{'content-type':'text/plain'});res.end('SYN-REAL-LOCAL-RESPONSE');});server.listen(0,'127.0.0.1');await once(server,'listening');
 try{const port=server.address().port,code=`const a=await fetch('http://127.0.0.1:${port}/synthetic-transport',{method:'POST',body:'SYN-CONTROL-CALIBRATION'});if(a.status!==201||await a.text()!=='SYN-REAL-LOCAL-RESPONSE')process.exit(2);try{await fetch('https://crm.invalid/must-not-send',{method:'POST',body:'not-journaled'});process.exit(3)}catch(e){if(e.message!=='CONTROL_EXTERNAL_TRANSPORT_BLOCKED')throw e;}`;
 const child=spawn(process.execPath,['--import',fileURLToPath(new URL('./outbound-audit.mjs',import.meta.url)),'--input-type=module','-e',code],{env:{...process.env,VEXA_RECOMMENDATION_AUDIT:journal},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',x=>stderr+=x);const [exit]=await once(child,'exit');assert.equal(exit,0,stderr);assert.equal(calls,1);const rows=fs.readFileSync(journal,'utf8').trim().split('\n').map(JSON.parse);assert.deepEqual(rows.map(r=>r.blocked),[false,true]);assert.equal(rows[1].path,'/must-not-send');assert.ok(rows.every(r=>!('body'in r)&&!('headers'in r)));assert.equal(fs.statSync(journal).mode&0o777,0o600);
 }finally{await new Promise(r=>server.close(r));fs.rmSync(tmp,{recursive:true,force:true});}
});
