import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {setup,q} from '../F06-notifications/harness.mjs';import {seedNotifications} from '../F06-notifications/fixtures.mjs';
test('Unread count, opening detail and explicit read persist through UI and real database',{timeout:480000},async t=>{
 const step=async(name,run)=>{let failure;await t.test(name,async()=>{try{await run();}catch(error){failure=error;throw error;}});if(failure)throw failure;};
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-read-root-'));fs.chmodSync(evidence,0o700);console.log('READ_ROOT_EVIDENCE:'+evidence);let h;
 try{
 h=await setup(process.env.VEXA_CANDIDATE,evidence);const f=await seedNotifications(h);
 const inbox=async(actor=h.A,status='unread',limit=1)=>{const r=await h.request(actor,`/api/notifications?status=${status}&limit=${limit}`);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};
 await step('count is full authorized unread set, not page size or another user',async()=>{const v=await inbox();assert.equal(v.items.length,1);assert.equal(v.unreadCount,31);assert.equal((await inbox(f.viewer)).unreadCount,1);assert.equal((await inbox(h.B)).unreadCount,0);});
 const browser=await h.browser(),ctx=await browser.newContext();ctx.setDefaultTimeout(20000);await ctx.addCookies(h.cookie(h.A).split('; ').map(value=>{const i=value.indexOf('=');return{name:value.slice(0,i),value:value.slice(i+1),url:h.base};}));h.ctx=ctx;h.p=await ctx.newPage();await h.p.goto(h.base+'/notifications');const panel=h.p.getByRole('region',{name:'Notificaciones',exact:true});await panel.getByRole('list',{name:'Avisos disponibles'}).waitFor();
 await step('default unread inbox and exact navigation count',async()=>{assert.equal(await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).isChecked(),true);await h.p.getByRole('link',{name:'Notificaciones',exact:true}).getByText('31',{exact:true}).waitFor();});
 let first;
 await step('open detail confirms read and removes pending item',async()=>{const article=panel.locator('article[data-notification-id]').first();first=await article.getAttribute('data-notification-id');await article.getByRole('button',{name:'Abrir detalle',exact:true}).click();await h.p.waitForURL('**/briefs/'+f.brief.id);assert.equal((await inbox()).unreadCount,30);assert.ok(!(await inbox(h.A,'unread',100)).items.some(x=>x.id===first));await h.p.getByRole('link',{name:'Notificaciones',exact:true}).click();await panel.getByRole('list',{name:'Avisos disponibles'}).waitFor();await h.p.getByRole('link',{name:'Notificaciones',exact:true}).getByText('30',{exact:true}).waitFor();});
 await step('explicit read removes pending card while all view keeps history',async()=>{const article=panel.locator('article[data-notification-id]').first(),id=await article.getAttribute('data-notification-id');await article.getByRole('button',{name:'Marcar como leído',exact:true}).click();await h.p.waitForFunction(id=>!document.querySelector(`article[data-notification-id="${id}"]`),id);assert.equal((await inbox()).unreadCount,29);await panel.getByLabel('Mostrar sólo avisos sin leer',{exact:true}).uncheck();await panel.locator(`article[data-notification-id="${id}"]`).getByText(/^Leído ·/).waitFor();const once=(await h.request(h.A,`/api/notifications/${id}/read`,{})).data.data;const twice=(await h.request(h.A,`/api/notifications/${id}/read`,{})).data.data;assert.equal(once.readAt,twice.readAt);assert.equal((await inbox()).unreadCount,29);});
 await step('resource revocation removes count and membership revocation denies access',async()=>{h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(f.a.a.connection)}`);assert.equal((await inbox()).unreadCount,0);h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);assert.equal((await h.request(h.A,'/api/notifications?status=unread&limit=1')).status,403);});
 fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({status:'pass',synthetic:true,externalDelivery:false}));
 }finally{if(h)await h.close();console.log('READ_ROOT_FINISHED:'+evidence);}
});
