import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {canaries,inspectPublished} from './artifact-secrets.mjs';
async function check({route='/api/connections',code='configuration_required',status=503,mode=true,cache='private, no-store',secret=false,version='f03-crm-v1',malformed=false,type='application/json',retryable=true,trace=true}={}){
 const fixture=canaries(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-crm-unconfigured-'));
 const server=createServer((req,res)=>{if(req.url===route){res.writeHead(status,{'Content-Type':type,'Cache-Control':cache});res.end(malformed?'not json':JSON.stringify({contract_version:version,error:{code,message:secret?fixture.server:'Configuración requerida.',retryable},...(trace?{meta:{trace_id:fixture.nonce}}:{})}));}else{res.writeHead(200,{'Content-Type':'text/html'});res.end('<a href="'+route+'">fixture</a>');}});server.listen(0,'127.0.0.1');await once(server,'listening');
 try{return await inspectPublished(tmp,'http://127.0.0.1:'+server.address().port,fixture,{allowUnconfiguredImports:mode});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(tmp,{recursive:true,force:true});}
}
test('offline smoke recognizes only the three explicit CRM configuration contracts',async()=>{for(const route of ['/api/connections','/api/connections/settings','/api/migrations'])await check({route});});
test('configured mode, provider outage, unrelated endpoint, query, wrong code/version/cache and 500 still fail',async()=>{for(const options of [{mode:false},{code:'database_unavailable'},{route:'/api/other'},{route:'/api/connections?tenant=x'},{version:'unknown'},{cache:'public'},{status:500}])await assert.rejects(check(options),/PAGE_HTTP_STATUS/);});
test('an otherwise expected 503 still fails secret detection',()=>assert.rejects(check({secret:true}),/CLIENT_SECRET_LEAK/));

test('offline extraction requires its exact contract and retains all secret/error guards',async()=>{await check({route:'/api/extraction',version:'f04-extraction-v1'});for(const delta of [{version:'f03-crm-v1'},{code:'extraction_unavailable'},{mode:false},{route:'/api/extraction?tenant=x'},{cache:'public'},{status:500}])await assert.rejects(check({route:'/api/extraction',version:'f04-extraction-v1',...delta}),/PAGE_HTTP_STATUS/);await assert.rejects(check({route:'/api/extraction',version:'f04-extraction-v1',secret:true}),/CLIENT_SECRET_LEAK/);});

test('aliases offline exception is exact and retains all error and secret checks',async()=>{const alias={route:'/api/migrations/aliases',version:'f03-alias-v1'};await check(alias);for(const bad of [{mode:false},{status:500},{code:'alias_unavailable'},{version:'f03-crm-v1'},{route:'/api/migrations/aliases/other'},{route:'/api/migrations/aliases?sourceConversationId=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...alias,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...alias,secret:true}),/CLIENT_SECRET_LEAK/);});
test('problems offline exception is exact and retains all error and secret checks',async()=>{const alias={route:'/api/problems',version:'f04-problems-v1'};await check(alias);for(const bad of [{mode:false},{status:500},{code:'problems_unavailable'},{version:'f03-crm-v1'},{route:'/api/problems/other'},{route:'/api/problems?sourceConversationId=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...alias,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...alias,secret:true}),/CLIENT_SECRET_LEAK/);});

test('snapshot offline exception requires exact configuration contract and preserves secret and error checks',async()=>{const snapshot={route:'/api/economic-snapshots',version:'f05-snapshots-v1'};await check(snapshot);for(const bad of [{mode:false},{status:500},{code:'snapshot_request_failed'},{code:'database_unavailable'},{version:'f04-problems-v1'},{route:'/api/economic-snapshots/other'},{route:'/api/economic-snapshots?scopeHash=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...snapshot,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...snapshot,secret:true}),/CLIENT_SECRET_LEAK/);});

test('economics offline exception requires exact configuration contract and preserves secret and error checks',async()=>{const economics={route:'/api/economics',version:'f05-economics-v1'};await check(economics);for(const bad of [{mode:false},{status:500},{code:'economic_request_failed'},{code:'database_unavailable'},{version:'f04-problems-v1'},{route:'/api/economics/other'},{route:'/api/economics?scopeHash=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...economics,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...economics,secret:true}),/CLIENT_SECRET_LEAK/);});

test('priority offline exception requires exact configuration contract and preserves secret and error checks',async()=>{const priority={route:'/api/economic-priorities',version:'f05-priority-v1'};await check(priority);for(const bad of [{mode:false},{status:500},{code:'priority_request_failed'},{code:'database_unavailable'},{version:'f04-problems-v1'},{route:'/api/economic-priorities/other'},{route:'/api/economic-priorities?scopeHash=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...priority,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...priority,secret:true}),/CLIENT_SECRET_LEAK/);});

test('workspace offline exceptions require exact configuration contract and preserve secret and error checks',async()=>{for(const route of ['/api/workspace','/api/workspace/mappings','/api/workspace/export']){const workspace={route,version:'f06-workspace-v1'};await check(workspace);for(const bad of [{mode:false},{status:500},{code:'workspace_request_failed'},{code:'database_unavailable'},{version:'f05-priority-v1'},{route:route+'/other'},{route:route+'?tenant=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...workspace,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...workspace,secret:true}),/CLIENT_SECRET_LEAK/);}});

test('detail customer bindings offline exception preserves exact error and secret guards',async()=>{const detail={route:'/api/workspace/customer-bindings',version:'f06-detail-v1'};await check(detail);for(const bad of [{mode:false},{status:500},{code:'detail_request_failed'},{code:'database_unavailable'},{version:'f06-workspace-v1'},{route:'/api/workspace/customer-bindings/other'},{route:'/api/workspace/detail/problem/unknown'},{route:'/api/workspace/customer-bindings?tenant=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...detail,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...detail,secret:true}),/CLIENT_SECRET_LEAK/);});

test('recommendations offline exception preserves exact configuration and secret guards',async()=>{const recommendation={route:'/api/recommendations',version:'f06-recommendations-v1'};await check(recommendation);for(const bad of [{mode:false},{status:500},{code:'recommendation_request_failed'},{code:'database_unavailable'},{version:'f06-detail-v1'},{route:'/api/recommendations/other'},{route:'/api/recommendations?tenant=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...recommendation,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...recommendation,secret:true}),/CLIENT_SECRET_LEAK/);});

test('explorer offline exception preserves exact configuration and secret guards',async()=>{const explorer={route:'/api/explorer',version:'f06-explorer-v1'};await check(explorer);for(const bad of [{mode:false},{status:500},{code:'explorer_request_failed'},{code:'database_unavailable'},{version:'f06-recommendations-v1'},{route:'/api/explorer/tools'},{route:'/api/explorer/query'},{route:'/api/explorer?tenant=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...explorer,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...explorer,secret:true}),/CLIENT_SECRET_LEAK/);});

test('interventions offline exception preserves exact configuration and secret guards',async()=>{const interventions={route:'/api/interventions',version:'f06-interventions-v1'};await check(interventions);for(const bad of [{mode:false},{status:500},{code:'interventions_request_failed'},{code:'database_unavailable'},{version:'f06-recommendations-v1'},{route:'/api/interventions/other'},{route:'/api/interventions/00000000-0000-4000-8000-000000000001'},{route:'/api/interventions?tenant=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...interventions,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...interventions,secret:true}),/CLIENT_SECRET_LEAK/);});
