import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {canaries,inspectPublished} from './artifact-secrets.mjs';
async function check({route='/api/connections',code='configuration_required',status=503,mode=true,cache='private, no-store',secret=false,version='f03-crm-v1',malformed=false,type='application/json',retryable=true,trace=true}={}){
 const fixture=canaries(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-crm-unconfigured-'));
 const server=createServer((req,res)=>{if(req.url===route){res.writeHead(status,{'Content-Type':type,'Cache-Control':cache});res.end(malformed?'not json':JSON.stringify({contract_version:version,error:{code,message:secret?fixture.server:'Configuración requerida.',retryable},...(trace?{meta:{trace_id:fixture.nonce}}:{})}));}else{res.writeHead(200,{'Content-Type':'text/html'});res.end('<a href="'+route+'">fixture</a>');}});server.listen(0,'127.0.0.1');await once(server,'listening');
 try{return await inspectPublished(tmp,'http://127.0.0.1:'+server.address().port,fixture,{allowUnconfiguredImports:mode});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(tmp,{recursive:true,force:true});}
}
test('offline smoke recognizes only the three explicit CRM configuration contracts',async()=>{for(const route of ['/api/connections','/api/connections/settings','/api/migrations'])await check({route});});
test('configured mode, provider outage, unrelated endpoint, query, wrong code/version/cache and 500 still fail',async()=>{for(const options of [{mode:false},{code:'database_unavailable'},{route:'/api/other'},{route:'/api/connections?tenant=x'},{version:'unknown'},{cache:'public'},{status:500}])await assert.rejects(check(options),/PAGE_HTTP_STATUS/);});
test('an otherwise expected 503 still fails secret detection',()=>assert.rejects(check({secret:true}),/CLIENT_SECRET_LEAK/));

test('aliases offline exception is exact and retains all error and secret checks',async()=>{const alias={route:'/api/migrations/aliases',version:'f03-alias-v1'};await check(alias);for(const bad of [{mode:false},{status:500},{code:'alias_unavailable'},{version:'f03-crm-v1'},{route:'/api/migrations/aliases/other'},{route:'/api/migrations/aliases?sourceConversationId=x'},{cache:'private'},{cache:'public, no-store'},{type:'text/plain'},{malformed:true},{retryable:false},{trace:false}])await assert.rejects(check({...alias,...bad}),/PAGE_HTTP_STATUS/);await assert.rejects(check({...alias,secret:true}),/CLIENT_SECRET_LEAK/);});
