import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {setup,q} from './harness.mjs';import {seedWorkspace,scope,order,parseCsv} from './fixtures.mjs';import './pure.mjs';
const route='/api/workspace';
async function bounded(p,label){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('BOUNDED_HANDSHAKE:'+label)),20000);})]);}finally{clearTimeout(timer);}}
export const query=(snapshot,resource='metrics',patch={})=>{const p=new URLSearchParams({resource,date_start:scope.start.slice(0,10),date_end:scope.end.slice(0,10),timezone:'UTC',date_basis:'occurred_at',currency:'USD',basis:scope.basis,snapshot_id:snapshot.id,...patch});return p;};
test('F06-01 shared authorized snapshot scope across API and real browser',{timeout:480000},async t=>{
 const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate&&fs.existsSync(path.join(candidate,'packages/workspace-service/index.mjs')),'WORKSPACE_IMPLEMENTATION_MISSING');
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-workspace271-'));fs.chmodSync(evidence,0o700);console.log('F0601_RUNNING:'+evidence);let h;const step=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();}catch(e){failure=e;throw e;}});if(failure)throw Error('WORKSPACE_PREREQUISITE_FAILED:'+name,{cause:failure});};
 try{h=await setup(candidate,evidence);const ok=async p=>{const r=await p;assert.equal(r.status,200,JSON.stringify(r.data));return r.data.data;};let f,global,sku,problems;const read=(p,a=h.A)=>h.request(a,route+'?'+p.toString());const mapping=(row,skus,version=0,a=h.A)=>h.request(a,route+'/mappings',{ledgerRowId:row.rowId,expectedVersion:version,skus,source:'csv',active:true,report:'SYN owner attests exact operational order SKU and source provenance.',attested:true});
 await step('real extraction order mappings and published monetary snapshot',async()=>{f=await seedWorkspace(h,async({o1,o2})=>{await ok(mapping(o1,['SKU-X']));await ok(mapping(o2,['SKU-Y']));});global=await ok(read(query(f.snapshot)));sku=await ok(read(query(f.snapshot,'metrics',{sku:'SKU-X'})));problems=await ok(read(query(f.snapshot,'problems')));fs.writeFileSync(path.join(evidence,'initial-bundles.json'),JSON.stringify({global,sku,problems},null,2));assert.equal(global.meta.snapshot_id,f.snapshot.id);assert.equal(sku.meta.snapshot_id,f.snapshot.id);assert.equal(global.meta.base_scope_hash,f.snapshot.scopeHash);assert.notEqual(global.meta.scope_hash,sku.meta.scope_hash,'FILTER_MUST_CHANGE_DERIVED_SCOPE');assert.equal(problems.meta.scope_hash,global.meta.scope_hash,'RESOURCES_SHARE_DATA_SCOPE');assert.equal(problems.items.length,2);const exposure=b=>b.items.flatMap(x=>x.metrics).filter(m=>m.kind==='exposure');assert.equal(exposure(global).length,1);assert.equal(exposure(global)[0].known_subtotal,'30000','GLOBAL_DEDUP_NOT_PROBLEM_SUM');assert.equal(exposure(sku)[0].known_subtotal,'10000','SKU_ORDERS_NOT_LINES');for(const [p,amount] of [[f.p1,'30000'],[f.p2,'10000']])assert.equal(problems.items.find(x=>x.id===p.id).metrics.find(m=>m.kind==='exposure').known_subtotal,amount); });
 await step('real Auth pooled database materialization remains narrower than financial writes',async()=>{const {assertDatabaseBoundary}=await import('./database-boundary.mjs');const result=await assertDatabaseBoundary(h);fs.writeFileSync(path.join(evidence,'database-boundary.json'),JSON.stringify(result));});
 await step('cursor bound to filter snapshot resource and authorized reader',async()=>{const first=await ok(read(query(f.snapshot,'problems',{limit:'1'})));assert.equal(first.items.length,1);assert.ok(first.meta.next_cursor);const second=await ok(read(query(f.snapshot,'problems',{limit:'1',cursor:first.meta.next_cursor})));assert.equal(second.items.length,1);assert.notEqual(first.items[0].id,second.items[0].id);for(const p of [query(f.snapshot,'problems',{sku:'SKU-X',cursor:first.meta.next_cursor}),query(f.snapshot,'metrics',{cursor:first.meta.next_cursor})])assert.equal((await read(p)).status,400);});
 await step('all reader roles same authorized data while mappings owner only and CSRF protected',async()=>{const secondary={...h.bot,tenant:h.A.tenant};for(const role of ['viewer','analyst','operator']){h.sql(`UPDATE memberships SET role=${q(role)} WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.bot.id)}`);const b=await ok(read(query(f.snapshot),secondary));assert.equal(b.meta.scope_hash,global.meta.scope_hash);assert.deepEqual(b.items,global.items);assert.equal((await mapping(f.o1,['SKU-Z'],1,secondary)).status,403);}assert.equal((await read(query(f.snapshot),null)).status,401);assert.equal((await read(query(f.snapshot),h.B)).status,404);assert.equal((await read(query(f.snapshot),{...h.A,tenant:h.B.tenant})).status,403);const r=await fetch(h.base+route+'/mappings',{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify({ledgerRowId:f.o1.rowId,expectedVersion:1,skus:['SKU-Z'],source:'csv',active:true,report:'SYN unauthorized origin cannot attest order mapping.',attested:true})});assert.equal(r.status,403);});
 await step('JSON and CSV export exact bound snapshot scope and monetary minor units',async()=>{
  const p=query(f.snapshot,'metrics',{sku:'SKU-X',scope_hash:sku.meta.scope_hash});p.set('format','json');const response=await fetch(h.base+route+'/export?'+p,{headers:{cookie:h.cookie(h.A)}});assert.equal(response.status,200);const exported=await response.json();assert.equal(exported.meta.scope_hash,sku.meta.scope_hash);assert.equal(exported.meta.snapshot_id,f.snapshot.id);assert.deepEqual(exported.items,sku.items);p.set('format','csv');const csv=await fetch(h.base+route+'/export?'+p,{headers:{cookie:h.cookie(h.A)}});assert.equal(csv.status,200);const rows=parseCsv(await csv.text()),header=rows.shift();assert.deepEqual(header,['snapshot_id','base_scope_hash','scope_hash','record_id','metric','currency','exponent','amount_minor','known_subtotal','status']);assert.ok(rows.length);for(const row of rows){assert.equal(row[0],f.snapshot.id);assert.equal(row[1],f.snapshot.scopeHash);assert.equal(row[2],sku.meta.scope_hash);}assert.ok(rows.some(row=>row[8]==='10000'));p.set('sku','SKU-Y');assert.equal((await fetch(h.base+route+'/export?'+p,{headers:{cookie:h.cookie(h.A)}})).status,409,'EXPORT_FILTER_HASH_MISMATCH');
 });
 await step('new mapping creates honest derived identity and old view remains immutable',async()=>{
  await ok(mapping(f.o1,['SKU-Z'],1));const changed=await ok(read(query(f.snapshot,'metrics',{sku:'SKU-X'})));assert.notEqual(changed.meta.scope_hash,sku.meta.scope_hash);const old=await ok(read(query(f.snapshot,'metrics',{sku:'SKU-X',scope_hash:sku.meta.scope_hash})));assert.deepEqual(old.items,sku.items,'PINNED_MAPPING_HISTORY_UNCHANGED');assert.equal(old.meta.mapping_manifest_id,sku.meta.mapping_manifest_id);await ok(mapping(f.o1,['SKU-X'],2));
 });
 await step('empty and partial are explicit without inventing zero for unknown orders',async()=>{
  const emptyQuery=query(f.snapshot);emptyQuery.delete('snapshot_id');const empty=await ok(read(emptyQuery,h.B));assert.equal(empty.meta.state,'empty');assert.equal(empty.meta.snapshot_id,null);assert.deepEqual(empty.items,[]);
  await f.ledger(order(f.src,'SYN-WORKSPACE-UNKNOWN',null));const draft=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'stage',scope}));const newer=await ok(h.request(h.A,'/api/economic-snapshots',{operation:'publish',snapshotId:draft.id,expectedContentHash:draft.contentHash}));const partial=await ok(read(query(newer)));assert.equal(partial.meta.state,'partial');const all=partial.items.flatMap(x=>x.metrics).find(m=>m.kind==='allOrders');assert.ok(all);assert.equal(all.amount_minor,null,'UNKNOWN_ORDER_IS_NOT_ZERO');assert.equal(all.known_subtotal,'30000');assert.equal(all.coverage.known_n,2);assert.equal(all.coverage.eligible_n,3);assert.deepEqual((await ok(read(query(f.snapshot,'metrics',{scope_hash:global.meta.scope_hash})))).items,global.items,'NEW_LEDGER_DOES_NOT_CHANGE_OLD_SNAPSHOT');
 });
 await step('real browser shares URL scope across overview and problems and exports matching bytes',async()=>{
  const browser=await h.browser(),ctx=await browser.newContext({timezoneId:'America/Merida'});ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(v=>{const i=v.indexOf('=');return{name:v.slice(0,i),value:v.slice(i+1),url:h.base};}));h.ctx=ctx;const p=await ctx.newPage();h.p=p;
  await p.goto(h.base+'/economics');const mappings=p.getByRole('region',{name:'Clasificación de órdenes',exact:true});await mappings.getByLabel(/^Orden para clasificar/).selectOption(f.o2.rowId);const consent=mappings.getByLabel('Confirmo la evidencia y esta versión de la clasificación',{exact:true}),save=mappings.getByRole('button',{name:'Guardar clasificación de orden',exact:true});assert.equal(await save.isEnabled(),false);await mappings.getByLabel('Razón y evidencia de la clasificación',{exact:true}).fill('SYN browser owner reviewed operational source and exact order SKU evidence.');await consent.check();assert.equal(await save.isEnabled(),true);await mappings.getByLabel(/^SKU de la orden, uno por línea/).fill('SKU-Y\nSKU-UI');assert.equal(await consent.isChecked(),false);assert.equal(await save.isEnabled(),false);await mappings.getByLabel(/^SKU de la orden, uno por línea/).fill('SKU-Y');await consent.check();let saved=p.waitForResponse(r=>new URL(r.url()).pathname===route+'/mappings'&&r.request().method()==='POST');await save.click();assert.equal((await saved).status(),200);await mappings.getByText('Clasificación guardada. Las vistas ya fijadas conservan su versión; abre una vista nueva para usar este cambio.',{exact:true}).waitFor();assert.equal(await consent.isChecked(),false);await consent.check();await ok(mapping(f.o2,['SKU-Y'],2));saved=p.waitForResponse(r=>new URL(r.url()).pathname===route+'/mappings'&&r.request().method()==='POST');await save.click();assert.equal((await saved).status(),409);await mappings.getByText('La versión cambió. Actualiza y revisa antes de volver a aprobar.',{exact:true}).waitFor();assert.equal(await mappings.getByRole('button',{name:'Guardar clasificación de orden',exact:true}).count(),0);
  const initial=query(f.snapshot,'metrics',{limit:'1'});initial.delete('resource');await p.goto(h.base+'/overview?'+initial);const panel=p.getByRole('region',{name:'Resumen con alcance compartido'});await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();const rendered=new URL(p.url()).searchParams;assert.equal(rendered.get('snapshot_id'),f.snapshot.id);assert.ok(rendered.get('scope_hash'));h.browserGlobalHash=rendered.get('scope_hash');
  const bytes=await h.browserDownload(p,()=>panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).click());const exported=JSON.parse(bytes.toString());assert.equal(exported.meta.snapshot_id,f.snapshot.id);assert.equal(exported.meta.scope_hash,h.browserGlobalHash);assert.equal(exported.items.flatMap(x=>x.metrics).find(m=>m.kind==='exposure').known_subtotal,'30000');
  await p.getByRole('navigation',{name:'Espacio de trabajo',exact:true}).getByRole('link',{name:'Problemas',exact:true}).click();const pp=p.getByRole('region',{name:'Problemas con alcance compartido'});await pp.locator('.record-card').first().waitFor();assert.equal(await pp.locator('.record-card').count(),1);assert.equal(new URL(p.url()).searchParams.get('scope_hash'),h.browserGlobalHash);assert.equal(new URL(p.url()).searchParams.get('snapshot_id'),f.snapshot.id);assert.match(await pp.innerText(),/no se suma|no se suman/i);
  let pageResponse=p.waitForResponse(r=>{const u=new URL(r.url());return u.pathname===route&&u.searchParams.get('resource')==='problems'&&u.searchParams.has('cursor');});await pp.getByRole('button',{name:'Página siguiente',exact:true}).click();assert.equal((await pageResponse).status(),200);await p.waitForFunction(()=>new URL(location.href).searchParams.has('cursor'));await pp.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();assert.ok(new URL(p.url()).searchParams.get('cursor'),'REAL_ACTIVE_UI_CURSOR');
  await pp.getByLabel(/^SKU, uno por línea/).fill('SKU-X');pageResponse=p.waitForResponse(r=>{const u=new URL(r.url());return u.pathname===route&&u.searchParams.get('resource')==='problems'&&u.searchParams.get('sku')==='SKU-X'&&!u.searchParams.has('cursor');});await pp.getByRole('button',{name:'Aplicar alcance',exact:true}).click();assert.equal((await pageResponse).status(),200);await p.waitForFunction(()=>!new URL(location.href).searchParams.has('cursor')&&document.querySelectorAll('[aria-label="Problemas con alcance compartido"] .record-card').length===2);assert.notEqual(new URL(p.url()).searchParams.get('scope_hash'),h.browserGlobalHash);await pp.getByRole('heading',{name:f.p1.label,exact:true}).waitFor();await pp.getByRole('heading',{name:f.p2.label,exact:true}).waitFor();
  await pp.getByLabel(/^SKU, uno por línea/).fill('');await pp.getByRole('button',{name:'Aplicar alcance',exact:true}).click();await p.waitForFunction(hash=>new URL(location.href).searchParams.get('scope_hash')===hash,h.browserGlobalHash);await pp.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();
  await p.getByRole('navigation',{name:'Espacio de trabajo',exact:true}).getByRole('link',{name:'Resumen',exact:true}).click();await p.getByRole('region',{name:'Resumen con alcance compartido'}).getByRole('link',{name:'Descargar CSV de este alcance',exact:true}).waitFor();
 });
 await step('slow real response A cannot replace filter B and cursor is reset',async()=>{
  const p=h.p,panel=p.getByRole('region',{name:'Resumen con alcance compartido'});let release,seen,finished;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r),done=new Promise(r=>finished=r);h.releaseHold=release;let captured=false;
  await p.route('**/api/workspace?*',async intercepted=>{const u=new URL(intercepted.request().url());if(!captured&&!u.searchParams.has('sku')){captured=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);const body=await response.body();seen();await held;await intercepted.fulfill({status:200,headers:response.headers(),body}).catch(()=>{});}finally{finished();}}else await intercepted.continue();});
  await panel.getByRole('button',{name:'Actualizar vista',exact:true}).click();await bounded(started,'response-captured');await panel.getByLabel(/^SKU, uno por línea/).fill('SKU-X');await panel.getByRole('button',{name:'Aplicar alcance',exact:true}).click();await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();const b=new URL(p.url()).searchParams;assert.equal(b.get('sku'),'SKU-X');assert.equal(b.get('cursor'),null);assert.equal(b.get('basis'),scope.basis,'BASIS_PRESERVED_AFTER_FILTER');const bHash=b.get('scope_hash');assert.notEqual(bHash,h.browserGlobalHash);release();await bounded(done,'response-released');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(new URL(p.url()).searchParams.get('scope_hash'),bHash,'LATE_A_CANNOT_REPLACE_B');assert.match(await panel.innerText(),/100\.00 USD/);assert.doesNotMatch(await panel.innerText(),/300\.00 USD/);await p.unroute('**/api/workspace?*');h.releaseHold=null;
  const bytes=await h.browserDownload(p,()=>panel.getByRole('link',{name:'Descargar CSV de este alcance',exact:true}).click());const rows=parseCsv(bytes.toString());assert.ok(rows.slice(1).every(r=>r[0]===f.snapshot.id&&r[2]===bHash));assert.ok(rows.slice(1).some(r=>r[8]==='10000'));await p.screenshot({path:path.join(evidence,'shared-filter-sku.png'),fullPage:true});
 });
 await step('base window change releases automatic snapshot and renders empty then partial consistently',async()=>{
  const p=h.p,panel=p.getByRole('region',{name:'Resumen con alcance compartido'});await panel.getByLabel('Desde (UTC)',{exact:true}).fill('2026-08-01');await panel.getByLabel('Hasta, exclusivo (UTC)',{exact:true}).fill('2026-08-20');await panel.getByLabel(/^SKU, uno por línea/).fill('');await panel.getByRole('button',{name:'Aplicar alcance',exact:true}).click();await panel.getByRole('heading',{name:'Sin resultados para este alcance',exact:true}).waitFor();assert.equal(new URL(p.url()).searchParams.get('snapshot_id'),null,'BASE_FILTER_RESETS_AUTOMATIC_SNAPSHOT');assert.equal(await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).count(),0);assert.equal(await panel.locator('.record-card').count(),0);
  await panel.getByLabel('Desde (UTC)',{exact:true}).fill('2026-09-01');await panel.getByLabel('Hasta, exclusivo (UTC)',{exact:true}).fill('2026-09-20');await panel.getByRole('button',{name:'Aplicar alcance',exact:true}).click();await panel.getByText('Datos parciales: no equivalen al total',{exact:true}).waitFor();assert.notEqual(new URL(p.url()).searchParams.get('snapshot_id'),f.snapshot.id);assert.match(await panel.innerText(),/Subtotal conocido: 300\.00 USD; no es el total/);await p.screenshot({path:path.join(evidence,'partial-workspace.png'),fullPage:true});
 });
 await step('administrative problem merge preserves exact historical labels IDs and monetary values',async()=>{
  const embeddings=h.json(`SELECT jsonb_agg(embedding_id ORDER BY embedding_id) FROM problem_embedding_members WHERE tenant_id=${q(h.A.tenant)} AND problem_id IN(${q(f.p1.id)},${q(f.p2.id)})`);assert.equal(embeddings.length,2);await ok(h.request(h.A,'/api/problems',{operation:'merge',parents:[{problemId:f.p1.id,expectedVersion:1},{problemId:f.p2.id,expectedVersion:1}],children:[{label:'SYN NEW MERGED PROBLEM AFTER SNAPSHOT',embeddingIds:embeddings}],reason:'SYN actual owner reviews merge after historical financial publication; no financial history rewrite.',approved:true}));const old=await ok(read(query(f.snapshot,'problems',{scope_hash:problems.meta.scope_hash})));assert.equal(old.meta.scope_hash,problems.meta.scope_hash);assert.deepEqual(old.items,problems.items,'ADMINISTRATIVE_MERGE_MUST_NOT_REWRITE_HISTORICAL_MONEY');assert.equal(old.meta.state,'stale','FRESHNESS_SEPARATE_FROM_IMMUTABLE_FINANCIAL_PAYLOAD');const oldGlobal=await ok(read(query(f.snapshot,'metrics',{scope_hash:global.meta.scope_hash})));assert.equal(oldGlobal.items.flatMap(x=>x.metrics).find(m=>m.kind==='exposure').known_subtotal,'30000');const panel=h.p.getByRole('region',{name:'Resumen con alcance compartido'});await panel.getByRole('button',{name:'Actualizar vista',exact:true}).click();await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();await panel.getByText('Datos desactualizados: revisa el corte',{exact:true}).waitFor();await h.p.screenshot({path:path.join(evidence,'historical-after-real-merge.png'),fullPage:true});
 });
 await step('current captured evidence withdrawal denies API and removes UI exports',async()=>{
  const p=h.p,panel=p.getByRole('region',{name:'Resumen con alcance compartido'});h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(f.p1.extraction.a.connection)}`);const denied=await read(query(f.snapshot));assert.ok([403,404].includes(denied.status),JSON.stringify(denied));assert.equal(denied.data.data,undefined);await panel.getByRole('button',{name:'Actualizar vista',exact:true}).click();await panel.getByRole('heading',{name:'No pudimos cargar esta vista',exact:true}).waitFor();assert.equal(await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).count(),0);assert.equal(await panel.locator('.record-card').count(),0);h.sql(`UPDATE connections SET status='active' WHERE id=${q(f.p1.extraction.a.connection)}`);
 });


 await step('late authorized response cannot resurrect workspace after membership revocation',async()=>{
  const p=h.p,panel=p.getByRole('region',{name:'Resumen con alcance compartido'});await panel.getByRole('button',{name:'Actualizar vista',exact:true}).click();await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).waitFor();let release,seen,finish;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r),done=new Promise(r=>finish=r);h.releaseHold=release;let captured=false;
  await p.route('**/api/workspace?*',async intercepted=>{if(!captured){captured=true;try{const response=await intercepted.fetch();assert.equal(response.status(),200);const body=await response.body();seen();await held;await intercepted.fulfill({status:200,headers:response.headers(),body}).catch(()=>{});}finally{finish();}}else await intercepted.continue();});await panel.getByRole('button',{name:'Actualizar vista',exact:true}).click();await bounded(started,'response-captured');h.sql(`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(h.A.tenant)} AND user_id=${q(h.A.id)}`);await panel.getByLabel(/^SKU, uno por línea/).fill('SKU-Y');await panel.getByRole('button',{name:'Aplicar alcance',exact:true}).click();await panel.getByText('Tu acceso cambió. Vuelve a iniciar sesión o selecciona una organización autorizada.',{exact:true}).waitFor();release();await bounded(done,'response-released');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await panel.locator('.record-card').count(),0);assert.equal(await panel.getByRole('link',{name:'Descargar JSON de este alcance',exact:true}).count(),0);await p.unroute('**/api/workspace?*');h.releaseHold=null;await p.screenshot({path:path.join(evidence,'revoked-late200.png'),fullPage:true});await h.ctx.close();
 });
 await step('workspace success and operational errors preserve the versioned trace envelope',async()=>{
  const emptyQuery=query(f.snapshot);emptyQuery.delete('snapshot_id');const cases=[await read(emptyQuery,h.B),await read(emptyQuery,null),await read(emptyQuery,{...h.B,tenant:h.A.tenant}),await h.request(h.B,route+'?date_start=2026-02-30')];assert.deepEqual(cases.map(r=>r.status),[200,401,403,400]);assert.equal(new Set(cases.map(r=>r.data.meta?.trace_id)).size,4,'DISTINCT_REQUEST_TRACES');for(const r of cases){assert.equal(r.data.contract_version,'f06-workspace-v1','WORKSPACE_ENVELOPE_VERSION');assert.match(r.data.meta?.trace_id??'',/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,'WORKSPACE_TRACE_REQUIRED');if(r.status!==200){assert.equal(r.data.error.retryable,false,'NONRETRYABLE_CLIENT_ERROR');assert.equal(typeof r.data.error.message,'string');}}
 });
 h.verifySources();
 }finally{h?.releaseHold?.();if(h?.p&&!h.p.isClosed()){fs.writeFileSync(path.join(evidence,'last-dom.html'),await h.p.content().catch(()=>''));await h.p.screenshot({path:path.join(evidence,'last-ui.png'),fullPage:true}).catch(()=>{});}if(h)await h.close();console.log('F0601_EVIDENCE:'+evidence);}
});
