import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {fixture} from '../../support/F04-evaluation/fixtures.mjs';
const root=process.env.VEXA_CANDIDATE;assert.ok(root);
const ev=await import(pathToFileURL(root+'/packages/intelligence/evaluation/evaluate.mjs'));
const {evaluatePilot}=await import(pathToFileURL(root+'/packages/intelligence/evaluation/pilot.mjs'));
export function sample(kind='human'){
 const f=fixture({kind:'human_gold'}),p=ev.freezeProtocol(f),evaluation=ev.evaluate({protocol:p,dataset:f.dataset,predictions:f.predictions(p)});
 const study={schema_version:'vexa-pilot-study-v1',study_id:'SYN400-NOT-REAL-RESEARCH',kind,window_start:'2026-02-08T00:00:00Z',window_end:'2026-02-10T00:00:00Z',reviewed_at:'2026-02-11T00:00:00Z',reviewer_id:'SYN400-reviewer-private',evidence_ref:'SYN400-private-evidence',evaluation_binding:{dataset_id:evaluation.dataset_id,protocol_hash:evaluation.input_hashes.protocol,holdout_hash:evaluation.input_hashes.holdout,candidate_hash:ev.hashValue(evaluation.candidate)},eligible_ceo_ids:['SYN400-both','SYN400-ceo2'],eligible_buyer_ids:['SYN400-both','SYN400-buyer2'],consents:['SYN400-both','SYN400-ceo2','SYN400-buyer2'].map(participant_id=>({participant_id,consented_at:'2026-02-07T00:00:00Z',evidence_ref:'SYN400-consent-only'})),ceo_sessions:[{participant_id:'SYN400-both',started_at:'2026-02-09T10:00:00-06:00',completed_at:'2026-02-09T16:04:59Z',comprehension_confirmed:true,evidence_ref:'SYN400-clock'},{participant_id:'SYN400-ceo2',started_at:'2026-02-09T12:00:00Z',completed_at:'2026-02-09T12:05:00Z',comprehension_confirmed:true,evidence_ref:'SYN400-clock'}],buyer_responses:[{participant_id:'SYN400-both',responded_at:'2026-02-09T18:00:00Z',new_insight:true,sponsored_action:{committed:true,sponsor_ref:'SYN400-secret-sponsor'},willingness_to_pay:{willing:true,amount_minor:'9007199254740993',currency:'USD',exponent:2},evidence_ref:'SYN400-response'},{participant_id:'SYN400-buyer2',responded_at:'2026-02-09T18:30:00Z',new_insight:false,sponsored_action:{committed:false,sponsor_ref:null},willingness_to_pay:{willing:true,amount_minor:'7',currency:'USD',exponent:2},evidence_ref:'SYN400-response'}]};return{study,evaluation};
}
test('exact valid-declared-human state is review required; shared CEO/buyer identity allowed and real timezone duration measured',()=>{const f=sample(),before=JSON.stringify(f),r=evaluatePilot(f);assert.equal(r.status,'requires_human_review');assert.equal(r.metrics.ceo_comprehension.numerator,1);assert.equal(r.metrics.ceo_comprehension.value,.5);assert.equal(r.metrics.willingness_to_pay.amount_groups[0].known_subtotal_minor,'9007199254741000');assert.equal(r.metrics.willingness_to_pay.amount_groups[0].total_minor,'9007199254741000');assert.equal(r.formal_acceptance,false);assert.equal(r.production_validated,false);assert.equal(JSON.stringify(f),before,'pure does not mutate inputs');assert.equal(ev.hashValue(r),ev.hashValue(evaluatePilot(f)));for(const s of ['SYN400-both','SYN400-secret-sponsor','SYN400-private-evidence','SYN400-response'])assert.equal(JSON.stringify(r).includes(s),false);});
test('nonresponse stays in denominator; no observation cannot be inferred from consent',()=>{const f=sample();f.study.eligible_ceo_ids.push('SYN400-missing-ceo');f.study.eligible_buyer_ids.push('SYN400-missing-buyer');const r=evaluatePilot(f);for(const m of Object.values(r.metrics)){assert.equal(m.denominator,3);assert.equal(m.respondents,2);assert.equal(m.missing,1);}f.study.buyer_responses=[];assert.equal(evaluatePilot(f).status,'blocked');});
test('unassigned unknown, assigned unknown and declared zero remain distinct',()=>{const f=sample();f.study.buyer_responses[0].willingness_to_pay={willing:true,amount_minor:null,currency:null,exponent:null};f.study.buyer_responses[1].willingness_to_pay={willing:true,amount_minor:'0',currency:'USD',exponent:2};let m=evaluatePilot(f).metrics.willingness_to_pay;assert.equal(m.unassigned_unknown_count,1);assert.equal(m.amount_groups[0].total_minor,'0');assert.equal(m.combined_total_minor,null);f.study.buyer_responses[0].willingness_to_pay={willing:true,amount_minor:null,currency:'USD',exponent:2};m=evaluatePilot(f).metrics.willingness_to_pay;assert.equal(m.amount_groups[0].unknown_count,1);assert.equal(m.amount_groups[0].known_subtotal_minor,'0');assert.equal(m.amount_groups[0].total_minor,null);});
test('synthetic outputs expose no measured aggregates or monetary totals in principal metrics',()=>{const r=evaluatePilot(sample('synthetic'));assert.equal(r.status,'not_measured');for(const m of Object.values(r.metrics)){assert.equal(m.value,null);assert.equal(m.numerator,null);assert.equal(m.status,'not_measured');}assert.equal(r.metrics.ceo_comprehension.completed_under_five_minutes,null);for(const g of r.metrics.willingness_to_pay.amount_groups??[]){assert.equal(g.known_subtotal_minor,null);assert.equal(g.total_minor,null);}assert.equal(r.causal_savings.amount_minor,null);});
const negative={
 duplicate_consent:f=>f.study.consents.push({...f.study.consents[0]}),ineligible_consent:f=>f.study.consents.push({participant_id:'SYN400-outsider',consented_at:'2026-02-07T00:00:00Z',evidence_ref:'SYN400-consent'}),duplicate_ceo:f=>f.study.ceo_sessions.push({...f.study.ceo_sessions[0]}),ceo_late_consent:f=>f.study.consents[0].consented_at='2026-02-09T16:01:00Z',non_boolean_understanding:f=>f.study.ceo_sessions[0].comprehension_confirmed='true',non_boolean_insight:f=>f.study.buyer_responses[0].new_insight=1,uncommitted_sponsor:f=>f.study.buyer_responses[1].sponsored_action.sponsor_ref='SYN400-unconfirmed',fraction_exponent:f=>f.study.buyer_responses[0].willingness_to_pay.exponent=2.5,too_large_exponent:f=>f.study.buyer_responses[0].willingness_to_pay.exponent=7,partial_unit:f=>f.study.buyer_responses[0].willingness_to_pay={willing:true,amount_minor:null,currency:'USD',exponent:null},non_integer_string:f=>f.study.buyer_responses[0].willingness_to_pay.amount_minor='1e9',non_iso_currency:f=>f.study.buyer_responses[0].willingness_to_pay.currency='usd',review_before_window_end:f=>f.study.reviewed_at='2026-02-09T00:00:00Z',binding_dataset:f=>f.study.evaluation_binding.dataset_id='SYN400-other',binding_protocol:f=>f.study.evaluation_binding.protocol_hash='e'.repeat(64),observation_pre_candidate:f=>{f.evaluation.candidate.frozen_at='2026-02-09T20:00:00Z';f.study.evaluation_binding.candidate_hash=ev.hashValue(f.evaluation.candidate);}
};for(const [name,mutate]of Object.entries(negative))test('reject independent '+name,()=>{const f=sample();mutate(f);assert.throws(()=>evaluatePilot(f));});
