import test from 'node:test';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import path from 'node:path';
import {fixture} from '../../support/F04-evaluation/fixtures.mjs';
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'EXPLICIT_CANDIDATE_REQUIRED');
const ev=await import(pathToFileURL(path.join(candidate,'packages/intelligence/evaluation/evaluate.mjs')));
const {evaluatePilot}=await import(pathToFileURL(path.join(candidate,'packages/intelligence/evaluation/pilot.mjs')));
export function setup(kind='human'){
 const f=fixture({kind:'human_gold'}),protocol=ev.freezeProtocol(f),evaluation=ev.evaluate({protocol,dataset:f.dataset,predictions:f.predictions(protocol)});
 const study={schema_version:'vexa-pilot-study-v1',study_id:'SYN399-schema-only-not-human-research',kind,window_start:'2026-02-08T00:00:00Z',window_end:'2026-02-10T00:00:00Z',reviewed_at:'2026-02-11T00:00:00Z',reviewer_id:'SYN-reviewer',evidence_ref:'SYN-fixture-never-real-evidence',evaluation_binding:{dataset_id:evaluation.dataset_id,protocol_hash:evaluation.input_hashes.protocol,holdout_hash:evaluation.input_hashes.holdout,candidate_hash:ev.hashValue(evaluation.candidate)},eligible_ceo_ids:['SYN-c1','SYN-c2','SYN-c3'],eligible_buyer_ids:['SYN-b1','SYN-b2','SYN-b3'],consents:['SYN-c1','SYN-c2','SYN-b1','SYN-b2'].map(participant_id=>({participant_id,consented_at:'2026-02-07T00:00:00Z',evidence_ref:'SYN-consent-schema-only'})),ceo_sessions:[{participant_id:'SYN-c1',started_at:'2026-02-09T10:00:00Z',completed_at:'2026-02-09T10:04:59Z',comprehension_confirmed:true,evidence_ref:'SYN-observation'},{participant_id:'SYN-c2',started_at:'2026-02-09T11:00:00Z',completed_at:'2026-02-09T11:05:00Z',comprehension_confirmed:true,evidence_ref:'SYN-observation'}],buyer_responses:[{participant_id:'SYN-b1',responded_at:'2026-02-09T12:00:00Z',new_insight:true,sponsored_action:{committed:true,sponsor_ref:'SYN-sponsor'},willingness_to_pay:{willing:true,amount_minor:'9007199254740993',currency:'USD',exponent:2},evidence_ref:'SYN-response'},{participant_id:'SYN-b2',responded_at:'2026-02-09T12:00:00Z',new_insight:false,sponsored_action:{committed:false,sponsor_ref:null},willingness_to_pay:{willing:true,amount_minor:null,currency:'USD',exponent:2},evidence_ref:'SYN-response'}]};return{study,evaluation};
}
test('denominators include nonresponse and human clock excludes exactly300 seconds; never production',()=>{const r=evaluatePilot(setup());assert.equal(r.schema_version,'vexa-pilot-result-v1');for(const k of ['production_validated','formal_acceptance'])assert.equal(r[k],false);assert.equal(r.release_decision,'not_issued');assert.equal(r.causal_savings.amount_minor,null);const m=r.metrics;assert.equal(m.ceo_comprehension.completed_under_five_minutes,1);assert.equal(m.ceo_comprehension.numerator,1);assert.equal(m.ceo_comprehension.denominator,3);assert.equal(m.ceo_comprehension.missing,1);assert.equal(m.ceo_comprehension.value,1/3);assert.equal(m.new_insight.denominator,3);assert.equal(m.new_insight.numerator,1);assert.equal(m.sponsored_action.numerator,1);assert.equal(m.willingness_to_pay.numerator,2);assert.equal(m.willingness_to_pay.value,2/3);assert.ok(['requires_human_review','blocked'].includes(r.status));});
test('BigInt and unknown amounts retained without converting WTP to contracted income',()=>{const r=evaluatePilot(setup()),m=r.metrics.willingness_to_pay;assert.equal(m.combined_total_minor,null);assert.equal(m.amount_groups.length,1);assert.equal(m.amount_groups[0].known_subtotal_minor,'9007199254740993');assert.equal(m.amount_groups[0].unknown_count,1);assert.equal(m.amount_groups[0].total_minor,null);});
test('currencies and exponents never mix',()=>{const f=setup();f.study.buyer_responses[1].willingness_to_pay={willing:true,amount_minor:'2000',currency:'MXN',exponent:2};let m=evaluatePilot(f).metrics.willingness_to_pay;assert.equal(m.amount_groups.length,2);assert.equal(m.combined_total_minor,null);assert.equal(m.amount_groups.find(x=>x.currency==='MXN').total_minor,'2000');f.study.buyer_responses[1].willingness_to_pay={willing:true,amount_minor:'7',currency:'USD',exponent:0};m=evaluatePilot(f).metrics.willingness_to_pay;assert.equal(m.amount_groups.length,2);});
test('synthetic declared study cannot become measured from a measured schema evaluation',()=>{const f=setup('synthetic'),r=evaluatePilot(f);assert.equal(r.status,'not_measured');for(const m of Object.values(r.metrics)){assert.equal(m.status,'not_measured');assert.equal(m.value,null);assert.equal(m.numerator,null);}assert.equal(r.production_validated,false);});
test('missing human gold blocks overall conclusion',()=>{const f=setup();f.evaluation.status='not_measured';f.evaluation.gold.kind='synthetic';f.evaluation.classification.status='not_measured';assert.equal(evaluatePilot(f).status,'blocked');});
test('empty eligible populations do not produce zero or perfect human percentages',()=>{const f=setup();Object.assign(f.study,{eligible_ceo_ids:[],eligible_buyer_ids:[],consents:[],ceo_sessions:[],buyer_responses:[]});const r=evaluatePilot(f);assert.equal(r.status,'blocked');for(const m of Object.values(r.metrics)){assert.equal(m.denominator,0);assert.equal(m.value,null);}});
const negatives={
 duplicate_eligible:f=>f.study.eligible_buyer_ids.push('SYN-b1'),duplicate_response:f=>f.study.buyer_responses.push(structuredClone(f.study.buyer_responses[0])),ineligible_response:f=>f.study.buyer_responses[0].participant_id='SYN-outsider',missing_consent:f=>f.study.consents=f.study.consents.filter(x=>x.participant_id!=='SYN-b1'),late_consent:f=>f.study.consents.find(x=>x.participant_id==='SYN-b1').consented_at='2026-02-09T13:00:00Z',reversed_clock:f=>f.study.ceo_sessions[0].completed_at='2026-02-09T09:00:00Z',outside_window:f=>f.study.buyer_responses[0].responded_at='2026-02-12T12:00:00Z',missing_timezone:f=>f.study.ceo_sessions[0].started_at='2026-02-09T10:00:00',missing_sponsor:f=>f.study.buyer_responses[0].sponsored_action.sponsor_ref=null,unsafe_numeric_money:f=>f.study.buyer_responses[0].willingness_to_pay.amount_minor=9007199254740993,negative_money:f=>f.study.buyer_responses[0].willingness_to_pay.amount_minor='-1',different_candidate:f=>f.study.evaluation_binding.candidate_hash='c'.repeat(64),different_holdout:f=>f.study.evaluation_binding.holdout_hash='d'.repeat(64),false_willing_money:f=>f.study.buyer_responses[0].willingness_to_pay.willing=false
};for(const [name,mutate]of Object.entries(negatives))test('reject '+name,()=>{const f=setup();mutate(f);assert.throws(()=>evaluatePilot(f));});
test('aggregates omit participant, sponsor and private evidence identities',()=>{const f=setup(),serialized=JSON.stringify(evaluatePilot(f));for(const secret of ['SYN-c1','SYN-b1','SYN-sponsor','SYN-consent-schema-only','SYN-observation','SYN-response'])assert.equal(serialized.includes(secret),false,secret);});
