import {catalog,channels,resourceHref} from './catalog.mjs';
import {NotificationError,check,uuid,parseInboxQuery,validatePreference,cursorBinding,encodeCursor,decodeCursor} from './contracts.mjs';
export {catalog,NotificationError};
const timestamp=column=>`to_char(${column} AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')`;
const preference=r=>({channel:r.channel,eventType:r.event_type,enabled:r.enabled,version:r.version});
/** Identity/capabilities belong to the canonical createDatabase boundary, never request input. */
export function createNotificationRepository({database}){
 check(database&&typeof database.transaction==='function','notification_database_missing',503);
 const tx=async(action,work)=>{let own;try{return await database.transaction(action,async s=>{try{return await work(s);}catch(e){if(e instanceof NotificationError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}};
 return Object.freeze({
 async inbox({query}){const selection=parseInboxQuery(query);return tx('read',async s=>{const binding=cursorBinding(s,selection),after=decodeCursor(selection.cursor,binding);const rows=(await s.query(`SELECT n.id,e.type,e.resource_id,${timestamp('n.created_at')} AS created_at,${timestamp('n.read_at')} AS read_at FROM public.notification_inbox n JOIN public.notification_events e ON e.tenant_id=n.tenant_id AND e.id=n.event_id WHERE n.tenant_id=$1 AND n.user_id=$2 AND ($3='all' OR n.read_at IS NULL) AND ($4::timestamptz IS NULL OR (n.created_at,n.id)<($4::timestamptz,$5::uuid)) ORDER BY n.created_at DESC,n.id DESC LIMIT $6`,[s.tenantId,s.userId,selection.status,after?.createdAt??null,after?.id??null,selection.limit+1])).rows;const page=rows.slice(0,selection.limit),items=await Promise.all(page.map(async r=>{const def=catalog.find(c=>c.type===r.type);let href=resourceHref(r.type,r.resource_id);if(r.type==='intervention.assigned'){const intervention=(await s.query('SELECT provenance FROM public.interventions WHERE tenant_id=$1 AND id=$2',[s.tenantId,r.resource_id])).rows[0];check(intervention,'notification_resource_unavailable',404);const q=new URLSearchParams(intervention.provenance.definition.provenance.query);for(const k of [...q.keys()])if(!['date_start','date_end','date_basis','currency','basis','exponent','sku','source','snapshot_id','scope_hash'].includes(k))q.delete(k);href='/interventions?'+q+'#intervention-'+r.resource_id;}check(def&&href,'notification_resource_unavailable',503);return {id:r.id,type:r.type,resourceId:r.resource_id,title:def.label,body:def.description,href,createdAt:r.created_at,readAt:r.read_at};}));const last=page.at(-1);return {items,nextCursor:rows.length>selection.limit?encodeCursor({createdAt:last.created_at,id:last.id},binding):null,status:selection.status,limit:selection.limit};});},
 async preferences(){return tx('read',async s=>{const rows=(await s.query('SELECT channel,event_type,enabled,version FROM public.notification_preferences WHERE tenant_id=$1 AND user_id=$2',[s.tenantId,s.userId])).rows;return {catalog:[...catalog],channels:[...channels],preferences:channels.flatMap(c=>['*',...catalog.map(e=>e.type)].map(eventType=>{const row=rows.find(r=>r.channel===c.id&&r.event_type===eventType);return row?preference(row):{channel:c.id,eventType,enabled:false,version:0};}))};});},
 async setPreference(input){const p=validatePreference(input);return tx('notify',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[JSON.stringify([s.tenantId,s.userId,p.channel,p.eventType])]);const old=(await s.query('SELECT version FROM public.notification_preferences WHERE tenant_id=$1 AND user_id=$2 AND channel=$3 AND event_type=$4',[s.tenantId,s.userId,p.channel,p.eventType])).rows[0];check((old?.version??0)===p.expectedVersion,'notification_preference_conflict',409);const rows=old?await s.query('UPDATE public.notification_preferences SET enabled=$5,version=version+1 WHERE tenant_id=$1 AND user_id=$2 AND channel=$3 AND event_type=$4 AND version=$6 RETURNING channel,event_type,enabled,version',[s.tenantId,s.userId,p.channel,p.eventType,p.enabled,p.expectedVersion]):await s.query('INSERT INTO public.notification_preferences(tenant_id,user_id,channel,event_type,enabled,version) VALUES($1,$2,$3,$4,$5,1) RETURNING channel,event_type,enabled,version',[s.tenantId,s.userId,p.channel,p.eventType,p.enabled]);check(rows.rowCount===1,'notification_preference_conflict',409);return preference(rows.rows[0]);});},
 async markRead({id}){check(uuid(id),'notification_not_found',404);return tx('notify',async s=>{const r=await s.query(`UPDATE public.notification_inbox SET read_at=coalesce(read_at,clock_timestamp()) WHERE tenant_id=$1 AND user_id=$2 AND id=$3 RETURNING id,${timestamp('read_at')} AS read_at`,[s.tenantId,s.userId,id]);check(r.rows.length===1,'notification_not_found',404);return {id:r.rows[0].id,readAt:r.rows[0].read_at};});}
 });
}
