import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {createServer} from 'node:http';import {once} from 'node:events';import {spawn} from 'node:child_process';
import {setup,q} from './browser-harness.mjs';import {syntheticConfig} from './config-fixture.mjs';
import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';
test('F04 browser request to hosted extraction, budget, reconciliation and scheduler',{timeout:540000},async t=>{
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-extraction-browser-'));fs.chmodSync(evidence,0o700);let h,provider;const requests=[];let uncertain=false;
 try{
  h=await setup(process.env.VEXA_CANDIDATE,evidence);
  const sync=h.repository(h.A).repository,row=await sync.ensure({connectionId:h.A.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,h.A,'T1',{type:'ticket'}),record(h.ingestion,h.A,'M1',{text:'SYNTHETIC Ana Pérez ana@example.test tiene una batería rota'})],'end',{done:true})});
  const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(h.A.tenant)}`);
  provider=createServer(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks).toString();requests.push({method:req.method,pii:body.includes('Ana Pérez')||body.includes('ana@example.test')});res.setHeader('Content-Type','application/json');if(req.headers.authorization!=='Bearer SYN-EXTRACTION-KEY'){res.writeHead(401);return res.end('{}');}return res.end(JSON.stringify({id:'SYN-EXTRACTION',usage:uncertain?{}:{cost:'0.000020'},choices:[{finish_reason:'stop',message:{content:JSON.stringify({issues:[],entities:[],sentiment:'unknown',intent:'unknown',urgency:'unknown',abstention:{reason:'ambiguous'}})}}]}));});provider.listen(0,'127.0.0.1');await once(provider,'listening');
  const preload=path.join(h.tmp,'synthetic-extraction-preload.mjs');fs.writeFileSync(preload,`const original=globalThis.fetch;globalThis.fetch=(input,init)=>{const u=new URL(typeof input==='string'?input:input.url??String(input));if(u.href==='https://openrouter.ai/api/v1/chat/completions')return original('http://127.0.0.1:${provider.address().port}/synthetic-extraction',init).then(r=>new Response(r.body,{status:r.status,headers:r.headers}));if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('EXTERNAL_NETWORK_NOT_AUTHORIZED');return original(input,init);};`);
  await h.stopWeb();await h.startWeb(false,{NODE_OPTIONS:'--import '+preload,VEXA_EXTRACTION_CONFIG_JSON:JSON.stringify([syntheticConfig(h.A.tenant)]),VEXA_AI_RUNTIME:'enabled',OPENROUTER_API_KEY:'SYN-EXTRACTION-KEY'});
  const browser=await h.browser();let ctx=await browser.newContext();ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(value=>{const i=value.indexOf('=');return{name:value.slice(0,i),value:value.slice(i+1),url:h.base};}));let p=await ctx.newPage();
  async function sendButton(name){const response=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/extraction'&&r.request().method()==='POST');await p.getByRole('button',{name,exact:true}).click();return response;}
  async function tick(){for(let i=0;i<4;i++){const response=await fetch(h.base+'/api/internal/extraction',{method:'POST',headers:{authorization:'Bearer '+h.triggerSecret}}),body=await response.json();assert.equal(response.status,200,'HOSTED:'+JSON.stringify(body));if(body.data?.state&&body.data.state!=='idle')return body.data;}throw Error('NO_WORKER_PROGRESS');}
  await t.test('owner configures both limits and requests analysis from served browser',async()=>{await p.goto(h.base+'/analysis');await p.getByLabel('Tipo de límite').selectOption('all');await p.getByLabel('Límite en USD',{exact:true}).fill('10');assert.equal((await sendButton('Guardar límite')).status(),200);await p.getByText('Global: $10.000000',{exact:true}).waitFor();await p.getByLabel('Tipo de límite').selectOption('extraction');await p.getByLabel('Límite en USD',{exact:true}).fill('5');assert.equal((await sendButton('Guardar límite')).status(),200);await p.getByText('Extracción: $5.000000',{exact:true}).waitFor();await p.getByLabel('Conversación',{exact:true}).selectOption(conversationId);assert.equal((await sendButton('Solicitar análisis')).status(),202);await p.getByText('En cola',{exact:true}).waitFor();const out=await tick();assert.equal(out.state,'succeeded');assert.equal(out.runStatus,'abstained');await p.reload();await p.getByText('Terminado',{exact:true}).waitFor();await p.getByText('Sin clasificación concluyente',{exact:false}).waitFor();assert.equal(requests.length,1);assert.equal(requests[0].pii,false,'NO_PII_OVER_PROVIDER_HTTP');await p.screenshot({path:path.join(evidence,'extraction-finished.png'),fullPage:true});});
  await t.test('browser cancellation prevents another provider request',async()=>{await p.getByLabel('Conversación',{exact:true}).selectOption(conversationId);assert.equal((await sendButton('Solicitar análisis')).status(),202);await p.getByRole('button',{name:'Cancelar análisis',exact:true}).waitFor();assert.equal((await sendButton('Cancelar análisis')).status(),200);await p.getByText('Cancelado',{exact:true}).waitFor();assert.equal(requests.length,1);});
  await t.test('actual scheduler subprocess completes without an open browser, leaving unknown cost retained',async()=>{await ctx.close();uncertain=true;const submit=await h.request(h.A,'/api/extraction',{action:'submit',conversationId,requestKey:randomUUID()});assert.equal(submit.status,202);for(let slot=0;slot<4&&requests.length===1;slot++){const child=spawn(process.execPath,[path.join(h.tmp,'packages/jobs/durable/scheduler.mjs'),'--once'],{cwd:h.tmp,env:{PATH:process.env.PATH,VEXA_WORKER_ENDPOINT:h.base+'/api/internal/extraction',VEXA_WORKER_TRIGGER_SECRET:h.triggerSecret},stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>child.kill('SIGKILL'),60000);let output='';child.stdout.on('data',x=>output+=x);child.stderr.on('data',x=>output+=x);let exit;try{exit=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});}finally{clearTimeout(timer);if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');}assert.equal(exit,0,'SCHEDULER:'+output);assert.match(output,/worker_http_status=200/);}assert.equal(requests.length,2);const snapshot=(await h.request(h.A,'/api/extraction')).data;assert.equal(snapshot.jobs.find(j=>j.id===submit.data.data.id).state,'succeeded');const pending=snapshot.reservations.find(r=>r.state==='uncertain');assert.ok(pending);assert.equal(pending.actualMinor,null);});
  await t.test('owner explicitly reconciles a synthetic provider receipt from browser without another send',async()=>{ctx=await browser.newContext();ctx.setDefaultTimeout(15000);await ctx.addCookies(h.cookie(h.A).split('; ').map(value=>{const i=value.indexOf('=');return{name:value.slice(0,i),value:value.slice(i+1),url:h.base};}));p=await ctx.newPage();await p.goto(h.base+'/analysis');await p.getByText(/Costo final: desconocido/).waitFor();const snapshot=(await h.request(h.A,'/api/extraction')).data,reservation=snapshot.reservations.find(r=>r.state==='uncertain');await p.getByLabel('Reserva',{exact:true}).selectOption(reservation.id);await p.getByLabel('Costo confirmado en USD',{exact:true}).fill('0.000030');await p.getByLabel('Huella SHA-256 del recibo del proveedor',{exact:true}).fill('a'.repeat(64));await p.getByLabel('Contrasté este costo con evidencia del proveedor.').check();assert.equal((await sendButton('Conciliar costo')).status(),200);await p.getByText(/Costo final: desconocido/).waitFor({state:'detached'});const updated=(await h.request(h.A,'/api/extraction')).data.reservations.find(r=>r.id===reservation.id);assert.equal(updated.state,'settled');assert.equal(updated.actualMinor,'30');assert.equal(requests.length,2);});
  await t.test('CSRF, viewer, other tenant and trigger boundary deny unauthorized actions',async()=>{const data={action:'submit',conversationId,requestKey:randomUUID()};assert.equal((await fetch(h.base+'/api/extraction',{method:'POST',headers:{cookie:h.cookie(h.A),'content-type':'application/json'},body:JSON.stringify(data)})).status,403);assert.equal((await h.request(h.B,'/api/extraction')).data.jobs.length,0);assert.equal((await h.request(h.B,'/api/extraction',data)).status,503);h.sql(`UPDATE memberships SET role='viewer' WHERE user_id=${q(h.A.id)}`);const view=await h.request(h.A,'/api/extraction');assert.equal(view.data.canSubmit,false);assert.equal(view.data.canConfigure,false);assert.equal((await h.request(h.A,'/api/extraction',data)).status,403);assert.equal((await fetch(h.base+'/api/internal/extraction',{method:'POST'})).status,401);assert.equal(requests.length,2);});
  await ctx.close();h.verifySources();fs.writeFileSync(path.join(evidence,'provider-requests.json'),JSON.stringify(requests),{mode:0o600});
 }finally{if(h)await h.close();if(provider){provider.closeAllConnections();await new Promise(resolve=>provider.close(resolve));}console.log('F04_EXTRACTION_BROWSER_EVIDENCE:'+evidence);}
});
