import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const candidate=path.resolve(process.env.VEXA_CANDIDATE??process.cwd());
const policy={version:'SYN-redact-1',emails:true,phones:true,names:['Ana Pérez'],namesMode:'dictionary'};
async function load(){const file=path.join(candidate,'packages/intelligence/redact.mjs');assert.ok(fs.existsSync(file),'F04_REDACTION_IMPLEMENTATION_MISSING');return import(pathToFileURL(file));}
test('PII removed before model projection; mapping private, Unicode offsets exact',async()=>{const{redactText}=await load();const raw='😀 Ana Pérez: ana@example.test, +52 (999) 123-4567. batería rota';const x=redactText(raw,policy);assert.ok(!x.text.includes('Ana Pérez')&&!x.text.includes('ana@example.test')&&!x.text.includes('123-4567'),'PII_BEFORE_PROVIDER');assert.ok(x.text.endsWith('batería rota'));assert.equal(x.redactionVersion,'SYN-redact-1');for(const s of x.privateMap){assert.equal([...raw].slice(s.originalStart,s.originalEnd).join(''),s.original);assert.equal([...x.text].slice(s.start,s.end).join(''),s.replacement);}assert.equal(x.privateMap.length,3);});
test('overlapping name/email removes entire union without revealing suffix',async()=>{const{redactText}=await load();const x=redactText('Ana@example.test y Ana Pérez',{...policy,names:['Ana']});assert.ok(!x.text.includes('@example.test'),'OVERLAP_REDACTION');assert.ok(!x.text.includes('Ana'));});
test('case folding and composed/decomposed names preserve source offsets',async()=>{const{redactText}=await load();for(const value of ['ANA PÉREZ','Ana Pe\u0301rez']){const x=redactText('😀 '+value+' rota',policy);assert.ok(!x.text.includes(value),'UNICODE_NAME_REDACTION');assert.equal(x.privateMap[0].original,value);assert.equal(x.privateMap[0].originalStart,2);}});
test('policy missing, malformed Unicode, unbounded text fail closed',async()=>{const{redactText}=await load();for(const [text,p] of [['a@x.test',null],['a',{}],['a',{...policy,emails:false}],['\ud800',policy],['x'.repeat(100001),policy]])assert.throws(()=>redactText(text,p),/REDACTION_/);});
test('full suppression is explicit and metadata contains no original',async()=>{const{redactText}=await load();const x=redactText('Nombre desconocido, batería rota',{...policy,namesMode:'suppress_all'});assert.equal(x.text,'[REDACTED]');assert.equal(x.privateMap.length,1);assert.equal(x.privateMap[0].originalStart,0);});
test('deterministic redaction never derives customer order or product IDs',async()=>{const{redactText}=await load();assert.deepEqual(redactText('llegó roto',policy),redactText('llegó roto',policy));const x=redactText('llegó roto',policy);assert.deepEqual(Object.keys(x).sort(),['hash','policyHash','privateMap','redactionVersion','text']);assert.equal(x.privateMap.length,0);});
