import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';
import {setup,q} from './harness.mjs';
import {record,page,windowSpec} from '../../tests/acceptance/support/F03-sync/fixtures.mjs';
test('F04 extraction durable workflow: submission, worker, isolation and crash recovery',{timeout:360000},async t=>{
 const candidate=path.resolve(process.env.VEXA_CANDIDATE??process.cwd()),evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-extraction-workflow-'));fs.chmodSync(evidence,0o700);let h;
 try{
  h=await setup(candidate,evidence);
  const {createExtractionQueue}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/queue.mjs'))),{createExtractionRuntime,createExtractionConfigResolver}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/runtime.mjs'))),{createExtractionHostedHandler}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/hosted.mjs'))),{createExtractionRepository}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/extraction-repository.mjs')));
  async function fixture(){
   const owner=await h.actor(),worker=await h.actor('analyst',owner.tenant);Object.assign(owner,{connection:randomUUID(),account:'SYN-account',source:'zendesk'});
   h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(owner.connection)},${q(owner.tenant)},'zendesk','SYN-account');INSERT INTO worker_delegations(tenant_id,user_id,enabled) VALUES(${q(owner.tenant)},${q(worker.id)},true)`);
   const database=h.database(owner),workerDatabase=h.database(worker),sync=h.sync.createSyncRepository({database}),row=await sync.ensure({connectionId:owner.connection,mode:'live',window:windowSpec,mappingVersion:'crm-canonical-v1'}),workerId=randomUUID(),claim=await sync.claim({syncId:row.id,workerId,leaseMs:30000});
   await sync.commitPage({syncId:row.id,workerId,fence:claim.fence,expectedVersion:0,page:page([record(h.ingestion,owner,'T1',{type:'ticket'}),record(h.ingestion,owner,'M1',{text:'Ana Pérez ana@example.test tiene una batería rota'})],'end',{done:true})});
   const conversationId=h.sql(`SELECT id FROM conversations WHERE tenant_id=${q(owner.tenant)}`),queue=createExtractionQueue({database}),now=Date.now(),expires=new Date(now+180000).toISOString();
   const entry={tenantId:owner.tenant,taxonomy:['battery'],redactionPolicy:{version:'SYN',emails:true,phones:true,namesMode:'dictionary',names:['Ana Pérez']},gateway:{catalog:{version:'SYN',fetchedAt:new Date(now).toISOString(),expiresAt:expires,models:[{id:'synthetic/model',contextTokens:200000,supportedParameters:['response_format']}]},modelsByRole:{extraction:[{model:'synthetic/model',provider:'synthetic/provider',structuredOutput:true,dataCollection:'deny',zdr:true,residency:'eu',contextTokens:200000,privacyAttestation:{version:'SYN',residencyEnforced:true,expiresAt:expires},pricing:{version:'SYN',validUntil:expires,allChargesIncluded:true,inputMicroUsdPerToken:'1',outputMicroUsdPerToken:'1',overheadTokens:1024}}]},policy:{authorized:true,version:'SYN',allowedModels:['synthetic/model'],providers:['synthetic/provider'],dataCollection:'deny',requireZdr:true,residency:'eu',maxAttempts:1,timeoutMs:1000,maxOutputTokens:100,maxInputBytes:100000,maxResponseBytes:100000,maxCostPerCallMinor:'1000000',maxCostPerTaskMinor:'1000000',tenantLimitMinor:'10000000',window:'SYN',currency:'USD',exponent:6}}};
   const resolveConfig=createExtractionConfigResolver(JSON.stringify([entry])),config=resolveConfig(owner.tenant),request={conversationId,requestKey:randomUUID(),configHash:config.hash};let calls=0;
   const fetch=async(_url,options)=>{calls++;assert.ok(!options.body.includes('Ana Pérez')&&!options.body.includes('ana@example.test'),'REDACTED_BEFORE_WORKER_TRANSPORT');return new Response(JSON.stringify({id:'SYN',usage:{cost:'0.000020'},choices:[{finish_reason:'stop',message:{content:JSON.stringify({issues:[],entities:[],sentiment:'unknown',intent:'unknown',urgency:'unknown',abstention:{reason:'ambiguous'}})}}]}),{status:200,headers:{'content-type':'application/json'}});};
   const runtime=()=>createExtractionRuntime({database:workerDatabase,resolveConfig,apiKey:'SYN-NOT-KEY',runtime:'enabled',fetch});
   async function submit(){const job=await queue.submit(request),budget=h.budgetModule.createDurableBudgetRepository({database,purpose:'extraction',jobId:job.id});await budget.configure({window:'SYN',purpose:'all',limitMinor:'10000000'});await budget.configure({window:'SYN',purpose:'extraction',limitMinor:'10000000'});return job;}
   return {owner,worker,database,workerDatabase,queue,config,resolveConfig,entry,request,fetch,runtime,submit,calls:()=>calls};
  }
  await t.test('user enqueues once; independent worker extracts, persists and exposes safe status',async()=>{const f=await fixture(),job=await f.submit();assert.equal(job.state,'queued');assert.equal((await f.queue.submit(f.request)).id,job.id);const out=await f.runtime().tick();assert.equal(out.state,'succeeded');assert.equal(out.runStatus,'abstained');assert.equal(f.calls(),1);const status=(await f.queue.list())[0];assert.equal(status.state,'succeeded');assert.equal(status.runStatus,'abstained');assert.equal(status.reason,'ambiguous');assert.ok(status.runId);assert.ok(!JSON.stringify(status).includes('Ana'));assert.equal((await f.runtime().tick()).state,'idle');assert.equal(f.calls(),1);});
  await t.test('concurrent claims dispatch exactly once',async()=>{const f=await fixture();await f.submit();const results=await Promise.all([f.runtime().tick(),f.runtime().tick()]);assert.equal(results.filter(x=>x.state==='succeeded').length,1);assert.equal(f.calls(),1);});
  await t.test('foreign tenant, viewer and different analyst cannot operate the user request',async()=>{const f=await fixture(),job=await f.submit(),other=await h.actor(),viewer=await h.actor('viewer',f.owner.tenant),analyst=await h.actor('analyst',f.owner.tenant);for(const actor of [other,viewer,analyst]){const queue=createExtractionQueue({database:h.database(actor)});assert.equal((await queue.list()).length,0);await assert.rejects(queue.cancel(job.id));}await assert.rejects(createExtractionQueue({database:h.database(other)}).submit(f.request));await assert.rejects(createExtractionQueue({database:h.database(viewer)}).submit({...f.request,requestKey:randomUUID()}));});
  await t.test('idempotency rejects altered configuration, preserving the original job',async()=>{const f=await fixture();await f.submit();await assert.rejects(f.queue.submit({...f.request,configHash:'a'.repeat(64)}),{status:409,code:"database_conflict"});assert.equal((await f.queue.list()).length,1);});
  await t.test('original actor revocation prevents inference',async()=>{const f=await fixture();await f.submit();h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(f.owner.id)}`);assert.equal((await f.runtime().tick()).state,'failed');assert.equal(f.calls(),0);});
  await t.test('worker delegation revocation prevents claim',async()=>{const f=await fixture();await f.submit();h.sql(`UPDATE worker_delegations SET enabled=false WHERE user_id=${q(f.worker.id)}`);await assert.rejects(f.runtime().tick(),{status:403,code:"database_permission_denied"});assert.equal(f.calls(),0);});
  await t.test('cancelled queued job is not dispatched; cancel during provider prevents publication',async()=>{const a=await fixture(),job=await a.submit();await a.queue.cancel(job.id);assert.equal((await a.runtime().tick()).state,'idle');assert.equal(a.calls(),0);const b=await fixture(),j=await b.submit();const runtime=createExtractionRuntime({database:b.workerDatabase,resolveConfig:b.resolveConfig,apiKey:'SYN',runtime:'enabled',fetch:async(...args)=>{await b.queue.cancel(j.id);return b.fetch(...args);}});await assert.rejects(runtime.tick());assert.equal((await b.queue.list())[0].state,'cancelled');assert.equal(h.sql(`SELECT count(*) FROM issues WHERE tenant_id=${q(b.owner.tenant)}`),'0');assert.equal(h.sql(`SELECT state FROM ai_budget_reservations WHERE tenant_id=${q(b.owner.tenant)}`),'reserved','CANCEL_DOES_NOT_INVENT_FREE_CHARGE');});
  await t.test('crash after prepare is reconciled as uncertain, never resent',async()=>{const f=await fixture(),job=await f.submit(),queue=createExtractionQueue({database:f.workerDatabase}),claim=await queue.claim(),repository=createExtractionRepository({database:queue.scopedDatabase(claim)});await repository.prepare({conversationId:f.request.conversationId,jobId:job.id,taskKey:'extraction:'+job.id,taxonomy:f.config.taxonomy,policy:f.config.redactionPolicy});h.sql(`UPDATE jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=${q(job.id)}`);const out=await f.runtime().tick();assert.equal(out.state,'failed');assert.equal((await f.queue.list())[0].reason,'reconciliation_required');assert.equal(f.calls(),0);await assert.rejects(queue.scopedDatabase(claim).transaction('import',s=>s.query('SELECT 1')));});
  await t.test('crash before prepare safely acquires a new fence and executes only once',async()=>{const f=await fixture(),job=await f.submit(),queue=createExtractionQueue({database:f.workerDatabase}),claim=await queue.claim();h.sql(`UPDATE jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=${q(job.id)}`);assert.equal((await f.runtime().tick()).state,'succeeded');assert.equal(f.calls(),1);await assert.rejects(queue.complete(claim,{}));});
  await t.test('changed server configuration blocks queued work without network',async()=>{const f=await fixture();await f.submit();const altered=structuredClone(f.entry);altered.redactionPolicy.version='SYN-new';const runtime=createExtractionRuntime({database:f.workerDatabase,resolveConfig:createExtractionConfigResolver(JSON.stringify([altered])),runtime:'enabled',apiKey:'SYN',fetch:f.fetch});assert.equal((await runtime.tick()).reason,'configuration_changed');assert.equal(f.calls(),0);});
  await t.test('default runtime remains disabled and makes no provider request',async()=>{const f=await fixture();await f.submit();const runtime=createExtractionRuntime({database:f.workerDatabase,resolveConfig:f.resolveConfig,apiKey:'SYN',fetch:f.fetch});assert.equal((await runtime.tick()).state,'failed');assert.equal((await f.queue.list())[0].reason,'runtime_disabled');assert.equal(f.calls(),0);});
  await t.test('hosted endpoint checks trigger secret/body, invokes durable worker and closes',async()=>{const f=await fixture();await f.submit();let opened=0,closed=0;const secret=randomUUID(),handler=createExtractionHostedHandler({secret,runtime:async()=>{opened++;return{extraction:f.runtime(),close:async()=>{closed++;}};}});const request=(body='',authorization='Bearer '+secret)=>new Request('http://localhost/api/internal/extraction',{method:'POST',body,headers:{authorization}});assert.equal((await handler(request('', 'wrong'))).status,401);assert.equal((await handler(request('{"tenantId":"forged"}'))).status,400);assert.equal(opened,0);const response=await handler(request());assert.equal(response.status,200);assert.equal((await response.json()).data.state,'succeeded');assert.equal(opened,1);assert.equal(closed,1);});
  await t.test('API exposes owner budget CAS and safe jobs; rejects tenant injection and analyst configuration',async()=>{const f=await fixture(),{createExtractionHandler}=await import(pathToFileURL(path.join(h.built,'packages/intelligence/api.mjs'))),api=createExtractionHandler({database:f.database,resolveConfig:f.resolveConfig,runtime:'enabled'}),post=body=>api(new Request('http://local/api/extraction',{method:'POST',body:JSON.stringify(body)}));
   assert.equal((await post({action:'budget',purpose:'all',limitUsd:'10'})).status,200);assert.equal((await post({action:'budget',purpose:'extraction',limitUsd:'5'})).status,200);
   let response=await api(new Request('http://local/api/extraction')),body=await response.json();assert.equal(body.limits.length,2);assert.equal(body.limits.find(x=>x.purpose==='extraction').limit_minor,'5000000');assert.equal(body.conversations.length,1);
   assert.equal((await post({action:'budget',purpose:'extraction',limitUsd:'6',expectedVersion:1})).status,200);assert.equal((await post({action:'budget',purpose:'extraction',limitUsd:'7',expectedVersion:1})).status,409);
   assert.equal((await post({action:'submit',conversationId:f.request.conversationId,requestKey:randomUUID(),tenantId:randomUUID()})).status,400);
   response=await post({action:'submit',conversationId:f.request.conversationId,requestKey:f.request.requestKey});assert.equal(response.status,202);const job=(await response.json()).data;assert.equal((await f.runtime().tick()).state,'succeeded');
   body=await(await api(new Request('http://local/api/extraction'))).json();assert.equal(body.jobs[0].id,job.id);assert.equal(body.reservations.length,1);assert.equal(body.reservations[0].actualMinor,'20');assert.ok(!JSON.stringify(body).includes('Ana Pérez'));
   const analyst=createExtractionHandler({database:f.workerDatabase,resolveConfig:f.resolveConfig});response=await analyst(new Request('http://local/api/extraction',{method:'POST',body:JSON.stringify({action:'budget',purpose:'all',limitUsd:'99'})}));assert.equal(response.status,403);
  });
  for(const fault of ['missing_fence','actor_revoked','lease_expired'])await t.test('SQL queued extraction rejects '+fault+' before run/claim commit',async()=>{const f=await fixture(),job=await f.submit(),queue=createExtractionQueue({database:f.workerDatabase}),claim=await queue.claim();
   if(fault==='actor_revoked')h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(f.owner.id)}`);if(fault==='lease_expired')h.sql(`UPDATE jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=${q(job.id)}`);
   const sqlScoped={transaction:(action,work)=>f.workerDatabase.transaction(action,async scope=>{if(fault!=='missing_fence')await scope.query("SELECT set_config('vexa.extraction_job_fence',$1,true),set_config('vexa.extraction_lease_owner',$2,true)",[String(claim.fencing_token),claim.lease_owner]);return work(scope);})};const raw=createExtractionRepository({database:sqlScoped});await assert.rejects(raw.prepare({conversationId:f.request.conversationId,jobId:job.id,taskKey:'extraction:'+job.id,taxonomy:f.config.taxonomy,policy:f.config.redactionPolicy}),undefined,'QUEUE_SQL_CAPABILITY_REQUIRED:'+fault);assert.equal(h.sql(`SELECT count(*) FROM extraction_runs WHERE job_id=${q(job.id)}`),'0');
  });
  await t.test('SQL terminal extraction rejects revoked original actor despite current worker identity',async()=>{const f=await fixture(),job=await f.submit(),queue=createExtractionQueue({database:f.workerDatabase}),claim=await queue.claim(),ownerToken=randomUUID(),scoped=createExtractionRepository({database:queue.scopedDatabase(claim),ownerToken}),prepared=await scoped.prepare({conversationId:f.request.conversationId,jobId:job.id,taskKey:'extraction:'+job.id,taxonomy:f.config.taxonomy,policy:f.config.redactionPolicy});h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(f.owner.id)}`);await assert.rejects(createExtractionRepository({database:{transaction:(action,work)=>f.workerDatabase.transaction(action,async scope=>{await scope.query("SELECT set_config('vexa.extraction_job_fence',$1,true),set_config('vexa.extraction_lease_owner',$2,true)",[String(claim.fencing_token),claim.lease_owner]);return work(scope);})},ownerToken}).complete({runId:prepared.runId,result:{ok:false,error:{code:'timeout'}}}),undefined,'QUEUE_SQL_TERMINAL_REVOKED');assert.equal(h.sql(`SELECT status FROM extraction_runs WHERE id=${q(prepared.runId)}`),'running');});
  await t.test('cron registration rejects absent approval and uses separate encrypted secret and revocation',()=>{
   const original=fs.readFileSync(path.join(process.env.VEXA_CANDIDATE,'supabase/operations/extraction-cron.sql'),'utf8');
   const body=original.slice(original.indexOf('DO $$'),original.indexOf('commit;'));
   const denied=h.probe(body);assert.equal(denied.code,'P0001','CRON_APPROVAL_REQUIRED');
   h.sql('CREATE EXTENSION IF NOT EXISTS pg_cron; CREATE EXTENSION IF NOT EXISTS pg_net; CREATE EXTENSION IF NOT EXISTS supabase_vault;');
   // The registration and revocation happen in one rolled-back transaction. No job
   // becomes visible to cron and no request is sent to this reserved .invalid host.
   const approved=`PERFORM set_config('vexa.extraction_bootstrap_approved','yes',true); PERFORM set_config('vexa.extraction_endpoint','https://synthetic-vexa.invalid/api/internal/extraction',true); PERFORM set_config('vexa.extraction_secret','SYN-'||repeat('x',40),true);`;
   const register=h.probe(approved+body+`SELECT jsonb_build_array(jsonb_build_object('jobs',(SELECT count(*) FROM cron.job WHERE jobname='vexa-extraction-chunk' AND schedule='30 seconds' AND command LIKE '%vault.decrypted_secrets%' AND command NOT LIKE '%SYN-%'),'secret',(SELECT count(*) FROM vault.secrets WHERE name='vexa_extraction_trigger'))) INTO result;`);
   fs.writeFileSync(path.join(evidence,'cron-register-probe.json'),JSON.stringify(register),{mode:0o600});assert.equal(register.code,'00000','CRON_REGISTRATION');assert.deepEqual(register.rows,[{jobs:1,secret:1}]);
   const revoked=h.probe(approved+body+"PERFORM set_config('vexa.extraction_revoke','yes',true);"+body+"SELECT jsonb_build_array(jsonb_build_object('jobs',(SELECT count(*) FROM cron.job WHERE jobname='vexa-extraction-chunk'))) INTO result;");
   assert.equal(revoked.code,'00000','CRON_REVOCATION');assert.deepEqual(revoked.rows,[{jobs:0}]);
   assert.equal(h.sql("SELECT count(*) FROM cron.job WHERE jobname='vexa-extraction-chunk'"),'0','CRON_NO_PERSISTED_EFFECT');
  });
  h.verifySources();
 }finally{if(h)await h.close();console.log('F04_WORKFLOW_EVIDENCE:'+evidence);}
});
