import {randomUUID,createHash} from 'node:crypto';
import {DomainError} from './contracts.mjs';
import {createProblemRepository,evidence as currentEvidence} from './repository.mjs';
const fail=(message,status=409)=>{throw new DomainError(message,status);};
const check=(ok,message,status)=>{if(!ok)fail(message,status);};
const uuid=x=>typeof x==='string'&&/^[a-f0-9-]{36}$/i.test(x);
const text=(x,max)=>typeof x==='string'&&x.trim().length>0&&x.length<=max;
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];
const evidenceView=r=>({id:r.id,recordId:r.record_id,version:r.version,status:r.status,sourceKind:r.source_kind,observedAt:r.observed_at,report:r.report,digest:r.digest,stance:r.stance,facts:r.facts,actorId:r.actor_id,createdAt:r.created_at});
const claimView=r=>({version:r.version,symptom:r.symptom,probableCause:r.probable_cause,state:r.state,evidenceIds:r.evidence_ids,reason:r.reason,actorId:r.actor_id,facts:r.facts,criticalReview:r.critical_review});
export function createCausalityRepository({database}){
 const underlying=database;database={transaction:async(action,work)=>{let domainError;try{return await underlying.transaction(action,async scope=>{try{return await work(scope);}catch(error){if(error instanceof DomainError)domainError=error;throw error;}});}catch(error){if(domainError)throw domainError;throw error;}}};
 async function view(s,problemId){check(uuid(problemId),'input_invalid',400);const problem=await createProblemRepository({database:{transaction:async(_,work)=>work(s)}}).detail({problemId});
 // Derive current safety risk from authorized extraction citations belonging to these members.
 const members=(await s.query('SELECT m.extraction_run_id,e.message_revision_id FROM public.problem_embedding_members m JOIN public.embeddings e ON e.tenant_id=m.tenant_id AND e.id=m.embedding_id WHERE m.tenant_id=$1 AND m.embedding_id=ANY($2::uuid[])',[s.tenantId,problem.embeddingIds])).rows;
 const runs=new Map();for(const member of members){if(!runs.has(member.extraction_run_id))runs.set(member.extraction_run_id,new Set());runs.get(member.extraction_run_id).add(member.message_revision_id);}
 let currentCritical=false;for(const [runId,revisions] of runs){const run=await currentEvidence(s,runId);if(run.issues.some(issue=>['high','critical'].includes(issue.severity)&&issue.evidence.some(span=>revisions.has(span.message_revision_id))))currentCritical=true;}
 const history=(await s.query('SELECT * FROM public.problem_causal_versions WHERE tenant_id=$1 AND problem_id=$2 ORDER BY version DESC',[s.tenantId,problemId])).rows.map(claimView);
 const evidence=(await s.query('SELECT * FROM public.problem_operational_evidence WHERE tenant_id=$1 AND problem_id=$2 ORDER BY record_id,version,id',[s.tenantId,problemId])).rows.map(evidenceView);
 const claim=history[0]?structuredClone(history[0]):{version:0,symptom:problem.label,probableCause:null,state:'unassessed',evidenceIds:[],reason:'Sin evaluación causal',actorId:null,facts:{batch:null,carrier:null,sku:null},criticalReview:currentCritical};claim.criticalReview=currentCritical;
 // Confirmation is historical if its supporting record, contributor or confirming actor lost current authorization.
 if(claim.state==='confirmed'){const valid=await one(s,"SELECT count(*)::int AS n FROM public.problem_operational_evidence e WHERE public.causality_contributor_active($1,$4) AND e.tenant_id=$1 AND e.problem_id=$2 AND e.id=ANY($3::uuid[]) AND e.status='active' AND public.causality_contributor_active(e.tenant_id,e.actor_id) AND e.version=(SELECT max(x.version) FROM public.problem_operational_evidence x WHERE x.tenant_id=e.tenant_id AND x.problem_id=e.problem_id AND x.record_id=e.record_id)",[s.tenantId,problemId,claim.evidenceIds,claim.actorId]);if(valid.n!==claim.evidenceIds.length)claim.state='retracted';}
 return {problemId,claim,evidence,history,canRecord:['owner','analyst','operator'].includes(s.role),canConfirm:s.role==='owner'};
 }
 const lock=(s,id)=>s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':causality:'+id]);
 return {
 get:({problemId})=>database.transaction('read',s=>view(s,problemId)),
 async recordEvidence(q){check(q&&uuid(q.problemId)&&Number.isInteger(q.expectedVersion)&&Number.isInteger(q.expectedEvidenceVersion)&&q.expectedEvidenceVersion>=0&&text(q.recordId,200)&&['inspection','lab','carrier_record'].includes(q.sourceKind)&&['supports','contradicts'].includes(q.stance)&&['active','withdrawn'].includes(q.status)&&q.attested===true&&text(q.report,16000)&&q.report.length>=20&&Number.isFinite(Date.parse(q.observedAt))&&Date.parse(q.observedAt)<=Date.now(),'evidence_invalid',400);check(q.facts&&Object.keys(q.facts).sort().join(',')==='batch,carrier,sku'&&Object.values(q.facts).every(v=>v===null||text(v,200)),'facts_invalid',400);
 return database.transaction('propose',async s=>{await lock(s,q.problemId);const v=await view(s,q.problemId);check(v.claim.version===q.expectedVersion,'stale_version');const latest=v.evidence.filter(e=>e.recordId===q.recordId).reduce((latest,e)=>!latest||e.version>latest.version?e:latest,null);check((latest?.version??0)===q.expectedEvidenceVersion,'stale_evidence');await s.query('INSERT INTO public.problem_operational_evidence(id,tenant_id,problem_id,record_id,version,actor_id,source_kind,observed_at,report,digest,stance,status,facts,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,true)',[randomUUID(),s.tenantId,q.problemId,q.recordId,q.expectedEvidenceVersion+1,s.userId,q.sourceKind,q.observedAt,q.report,createHash('sha256').update(q.report).digest('hex'),q.stance,q.status,JSON.stringify(q.facts)]);return view(s,q.problemId);});},
 async revise(q){check(q&&uuid(q.problemId)&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&text(q.symptom,2000)&&(q.probableCause===null||text(q.probableCause,2000))&&['hypothesis','confirmed','retracted'].includes(q.state)&&Array.isArray(q.evidenceIds)&&q.evidenceIds.length<=100&&q.evidenceIds.every(uuid)&&new Set(q.evidenceIds).size===q.evidenceIds.length&&text(q.reason,2000)&&q.approved===true,'claim_invalid',400);
 return database.transaction(q.state==='confirmed'?'approve':'propose',async s=>{await lock(s,q.problemId);const v=await view(s,q.problemId);check(v.claim.version===q.expectedVersion,'stale_version');const selected=q.evidenceIds.map(id=>v.evidence.find(e=>e.id===id));check(selected.every(e=>e&&e.status==='active'&&v.evidence.filter(x=>x.recordId===e.recordId).reduce((latest,x)=>!latest||x.version>latest.version?x:latest,null)?.id===e.id),'evidence_unavailable');if(q.state==='confirmed')check(s.role==='owner'&&q.probableCause&&selected.some(e=>e.stance==='supports'),'independent_evidence_required');const facts={batch:null,carrier:null,sku:null};for(const key of Object.keys(facts)){const values=[...new Set(selected.filter(e=>e.stance==='supports').map(e=>e.facts[key]).filter(Boolean))];facts[key]=values.length===1?values[0]:null;}
 await s.query('INSERT INTO public.problem_causal_versions(tenant_id,problem_id,version,actor_id,symptom,probable_cause,state,reason,evidence_ids,facts,critical_review,approved) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true)',[s.tenantId,q.problemId,q.expectedVersion+1,s.userId,q.symptom,q.probableCause,q.state,q.reason,q.evidenceIds,JSON.stringify(facts),v.claim.criticalReview]);return view(s,q.problemId);});}
 };
}
