import {randomUUID} from 'node:crypto';
import {hash,stableId,sortedUnique,requireThat,DomainError} from './contracts.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
const uuid=x=>typeof x==='string'&&/^[a-f0-9-]{36}$/i.test(x);
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];
const scoped=s=>({transaction:async(_,work)=>work(s)});
export const evidence=async(s,id)=>{const e=await createEvidenceRepository({database:scoped(s)}).get(id);requireThat(e.state==='current'&&e.status==='succeeded','source_unavailable',409);return e;};
async function accessible(s,p){for(const id of p.embeddingIds){const m=await one(s,'SELECT extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1 AND embedding_id=$2',[s.tenantId,id]);requireThat(m,'source_unavailable');await evidence(s,m.extraction_run_id);}return p;}
const expected=e=>['EVIDENCE_UNAVAILABLE','source_unavailable'].includes(e.message);
const projection=r=>({...r.provenance.snapshot,id:r.problem_id,version:r.version});
const latest=async(s,id)=>{const r=await one(s,"SELECT * FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 AND provenance->>'kind'='vector-problem-v1' ORDER BY version DESC LIMIT 1",[s.tenantId,id]);requireThat(r,'problem_not_found',404);return projection(r);};
export async function snapshot(s,p,event){
 const prev=await one(s,'SELECT id,version FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,p.id]);
 p={...p,version:(prev?.version??0)+1};
 await s.query('INSERT INTO public.problem_versions(id,tenant_id,problem_id,previous_version_id,version,title,rationale,change_kind,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),s.tenantId,p.id,prev?.id??null,p.version,p.label,event.reason??'Agrupación por vectores',event.operation??(prev?'edit':'create'),JSON.stringify({kind:'vector-problem-v1',snapshot:p,actorId:s.userId,...event})]);return p;
}
export function createProblemRepository({database}){
 // Preserve only our own domain failures after the platform has rolled back.
 // Driver errors and untrusted status/code fields retain the platform sanitizer.
 const underlying=database;
 database={transaction:async(action,work)=>{let domainError;try{return await underlying.transaction(action,async scope=>{try{return await work(scope);}catch(error){if(error instanceof DomainError)domainError=error;throw error;}});}catch(error){if(domainError)throw domainError;throw error;}}};
 const read=work=>database.transaction('read',work);
 return Object.freeze({
 async list(){return read(async s=>{const out=[];for(const r of (await s.query("SELECT DISTINCT ON(problem_id) * FROM public.problem_versions WHERE tenant_id=$1 AND provenance->>'kind'='vector-problem-v1' ORDER BY problem_id,version DESC",[s.tenantId])).rows){try{out.push(await accessible(s,projection(r)));}catch(e){if(!expected(e))throw e;}}return out;});},
 async detail({problemId}){requireThat(uuid(problemId),'input_invalid',400);return read(async s=>({...await accessible(s,await latest(s,problemId)),history:(await s.query('SELECT id,version,provenance FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 ORDER BY version DESC',[s.tenantId,problemId])).rows}));},
 async sources(){return read(async s=>{const out=[];for(const r of (await s.query("SELECT id,conversation_id,created_at FROM public.extraction_runs WHERE tenant_id=$1 AND status='succeeded' ORDER BY created_at DESC LIMIT 100",[s.tenantId])).rows){try{await evidence(s,r.id);out.push({id:r.id,conversationId:r.conversation_id,createdAt:r.created_at});}catch(e){if(!expected(e))throw e;}}return out;});},
 async jobs(){return read(async s=>(await s.query('SELECT j.id,j.state,j.provenance,j.created_at,r.extraction_run_id FROM public.jobs j JOIN public.problem_embedding_requests r ON r.tenant_id=j.tenant_id AND r.job_id=j.id WHERE j.tenant_id=$1 AND (r.actor_id=$2 OR $3) ORDER BY j.created_at DESC LIMIT 100',[s.tenantId,s.userId,s.role==='owner'])).rows.map(r=>({id:r.id,state:r.state,reason:r.provenance?.reason??null,createdAt:r.created_at,extractionRunId:r.extraction_run_id})));},
 async submit({extractionRunId,requestKey,configHash}){requireThat(uuid(extractionRunId)&&uuid(requestKey)&&/^[a-f0-9]{64}$/.test(configHash),'input_invalid',400);return database.transaction('import',async s=>{
 await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':problem-submit:'+s.userId+requestKey]);
 const prior=await one(s,'SELECT * FROM public.problem_embedding_requests WHERE tenant_id=$1 AND actor_id=$2 AND request_key=$3',[s.tenantId,s.userId,requestKey]);
 if(prior){requireThat(prior.extraction_run_id===extractionRunId&&prior.config_hash===configHash,'request_conflict');const j=await one(s,'SELECT * FROM public.jobs WHERE tenant_id=$1 AND id=$2',[s.tenantId,prior.job_id]);return {id:j.id,state:j.state,reason:j.provenance?.reason??null,createdAt:j.created_at,extractionRunId};}
 await evidence(s,extractionRunId);const id=randomUUID();const j=await one(s,"INSERT INTO public.jobs(id,tenant_id,type,input_ref,input_hash,version,max_attempts) VALUES($1,$2,'embedding',$3,$4,'problem-v1',1) RETURNING *",[id,s.tenantId,'extraction:'+extractionRunId,hash({actor:s.userId,requestKey,extractionRunId,configHash})]);
 await s.query('INSERT INTO public.problem_embedding_requests(tenant_id,job_id,extraction_run_id,actor_id,request_key,config_hash) VALUES($1,$2,$3,$4,$5,$6)',[s.tenantId,id,extractionRunId,s.userId,requestKey,configHash]);return {id,state:j.state,reason:null,createdAt:j.created_at,extractionRunId};});},
 async retrieve({embeddingId,limit=10}){requireThat(uuid(embeddingId)&&Number.isInteger(limit)&&limit>0&&limit<=50,'input_invalid',400);return read(async s=>{
 const q=await one(s,'SELECT e.*,m.extraction_run_id FROM public.embeddings e JOIN public.problem_embedding_members m ON m.tenant_id=e.tenant_id AND m.embedding_id=e.id WHERE e.tenant_id=$1 AND e.id=$2',[s.tenantId,embeddingId]);requireThat(q,'embedding_not_found',404);await evidence(s,q.extraction_run_id);
 const allowed=[];for(const r of (await s.query('SELECT DISTINCT extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1',[s.tenantId])).rows){try{await evidence(s,r.extraction_run_id);allowed.push(r.extraction_run_id);}catch(e){if(!expected(e))throw e;}}
 return (await s.query('SELECT e.id AS "embeddingId",m.problem_id AS "problemId",(e.embedding OPERATOR(extensions.<=>) $2::extensions.vector) AS distance FROM public.embeddings e JOIN public.problem_embedding_members m ON m.tenant_id=e.tenant_id AND m.embedding_id=e.id WHERE e.tenant_id=$1 AND e.model_id=$3 AND e.dim=$4 AND e.version=$5 AND m.extraction_run_id=ANY($6::uuid[]) ORDER BY distance,e.id LIMIT $7',[s.tenantId,q.embedding,q.model_id,q.dim,q.version,allowed,limit])).rows;});},
 async restructure({operation,parents,children,reason,approved}){requireThat(['split','merge'].includes(operation)&&approved===true&&typeof reason==='string'&&reason.trim()&&reason.length<=2000&&Array.isArray(parents)&&Array.isArray(children),'input_invalid',400);requireThat(operation==='split'?parents.length===1&&children.length>=2:parents.length>=2&&children.length===1,'shape_invalid',400);return database.transaction('configure',async s=>{
 requireThat(s.role==='owner','role_forbidden',403);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':vector-problems']);const ps=[];for(const parent of parents){const p=await accessible(s,await latest(s,parent.problemId));requireThat(p.version===parent.expectedVersion&&p.state==='active','stale_version');ps.push(p);}requireThat(new Set(ps.map(p=>p.id)).size===ps.length,'duplicate_parent',400);
 requireThat(ps.every(p=>p.modelId===ps[0].modelId&&p.dimensions===ps[0].dimensions&&p.embeddingVersion===ps[0].embeddingVersion),'embedding_space_mismatch');
 const before=sortedUnique(ps.flatMap(p=>p.embeddingIds)),after=children.flatMap(c=>c.embeddingIds??[]);requireThat(after.length===before.length&&sortedUnique(after).length===after.length&&JSON.stringify(sortedUnique(after))===JSON.stringify(before),'partition_invalid',400);
 const severityRows=(await s.query('SELECT severity FROM public.problems WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,ps.map(p=>p.id)])).rows;const severity=['critical','high','medium','low'].find(level=>severityRows.some(p=>p.severity===level));requireThat(severity,'problem_severity_missing');
 const result=[];for(let i=0;i<children.length;i++){const child=children[i];requireThat(typeof child.label==='string'&&child.label.trim()&&child.label.length<=500&&child.embeddingIds.length,'child_invalid',400);const id=stableId({tenant:s.tenantId,operation,parents,child:i});await s.query("INSERT INTO public.problems(id,tenant_id,title,provenance,severity,cause_status) VALUES($1,$2,$3,$4,$5,'unknown')",[id,s.tenantId,child.label,JSON.stringify({kind:'vector-problem-v1'}),severity]);await s.query('UPDATE public.problem_embedding_members SET problem_id=$3 WHERE tenant_id=$1 AND embedding_id=ANY($2::uuid[])',[s.tenantId,child.embeddingIds,id]);const rows=(await s.query('SELECT DISTINCT m.conversation_id,c.order_id FROM public.problem_embedding_members m JOIN public.conversations c ON c.tenant_id=m.tenant_id AND c.id=m.conversation_id WHERE m.tenant_id=$1 AND m.problem_id=$2',[s.tenantId,id])).rows;result.push(await snapshot(s,{...ps[0],id,label:child.label,state:'active',outlier:child.embeddingIds.length===1,embeddingIds:sortedUnique(child.embeddingIds),conversationIds:rows.map(x=>x.conversation_id).sort(),orderIds:sortedUnique(rows.map(x=>x.order_id).filter(Boolean))},{operation,reason,parents}));}
 for(const p of ps){await snapshot(s,{...p,state:'retired'},{operation,reason,children:result.map(x=>x.id)});await s.query('UPDATE public.problems SET archived_at=clock_timestamp() WHERE tenant_id=$1 AND id=$2',[s.tenantId,p.id]);}return result;});}
 });
}
