import {randomUUID} from 'node:crypto';
import {hash,stableId,requireThat,sortedUnique} from './contracts.mjs';
import {evidence,snapshot} from './repository.mjs';
import {createEmbeddingGateway} from '../gateway/embeddings.mjs';
import {createDurableBudgetRepository} from '../gateway/durable-budget.mjs';
const one=async(s,q,a)=>(await s.query(q,a)).rows[0];
export function createProblemConfigResolver(raw='[]'){let entries;try{entries=JSON.parse(raw);}catch{throw Error('configuration_required');}requireThat(Array.isArray(entries),'configuration_required',503);const map=new Map();for(const e of entries){requireThat(e&&typeof e.tenantId==='string'&&!map.has(e.tenantId)&&typeof e.modelId==='string'&&Number.isInteger(e.dimensions)&&e.dimensions>0&&e.dimensions<=4096&&typeof e.version==='string'&&e.version&&Number.isFinite(e.threshold)&&e.threshold>=0&&e.threshold<1&&e.gateway?.candidate?.model===e.modelId,'configuration_required',503);const c=structuredClone(e);map.set(e.tenantId,{...c,hash:hash(c)});}return tenant=>{requireThat(map.has(tenant),'configuration_required',503);return structuredClone(map.get(tenant));};}
export function createProblemRuntime({database,resolveConfig,apiKey,runtime='stub',fetch}={}){
 const tx=work=>database.transaction('import',work);
 return {async tick(){
 const claim=await tx(async s=>{requireThat(s.role==='analyst'&&(await one(s,'SELECT enabled FROM public.worker_delegations WHERE tenant_id=$1 AND user_id=$2',[s.tenantId,s.userId]))?.enabled,'worker_disabled',403);
 const j=await one(s,"SELECT j.*,r.extraction_run_id,r.config_hash,r.network_started FROM public.jobs j JOIN public.problem_embedding_requests r ON r.tenant_id=j.tenant_id AND r.job_id=j.id WHERE j.tenant_id=$1 AND j.type='embedding' AND j.cancel_requested_at IS NULL AND (j.state='queued' OR j.state='running' AND j.lease_until<=clock_timestamp()) ORDER BY j.created_at,j.id LIMIT 1 FOR UPDATE OF j SKIP LOCKED",[s.tenantId]);if(!j)return null;
 if(j.network_started||!(await one(s,'SELECT public.problem_actor_authorized($1) AS ok',[j.id]))?.ok){const reason=j.network_started?'reconciliation_required':'actor_revoked';await s.query("UPDATE public.jobs SET state='failed',lease_until=NULL,provenance=$3 WHERE tenant_id=$1 AND id=$2",[s.tenantId,j.id,JSON.stringify({reason})]);return {recovered:true,id:j.id,state:'failed',reason};}
 const c=await one(s,"UPDATE public.jobs SET state='running',fencing_token=fencing_token+1,lease_owner=$3,lease_until=clock_timestamp()+interval '45 seconds' WHERE tenant_id=$1 AND id=$2 RETURNING *",[s.tenantId,j.id,randomUUID()]);return {...j,...c};});
 if(!claim)return {state:'idle'};if(claim.recovered)return claim;
 const scoped={transaction:async(action,work)=>{requireThat(['read','import'].includes(action),'worker_action_invalid',403);return tx(async s=>{
 await s.query("SELECT set_config('vexa.problem_job_id',$1,true),set_config('vexa.problem_fence',$2,true),set_config('vexa.problem_lease_owner',$3,true)",[claim.id,String(claim.fencing_token),claim.lease_owner]);
 const lock=await one(s,'SELECT id FROM public.jobs WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[s.tenantId,claim.id]);requireThat(lock&&(await one(s,'SELECT public.problem_write_authorized($1) AS ok',[s.tenantId]))?.ok,'stale_fence',403);const result=await work(s);requireThat((await one(s,'SELECT public.problem_actor_authorized(id) AND lease_until>clock_timestamp() AND fencing_token=$3 AND lease_owner=$4 AS ok FROM public.jobs WHERE tenant_id=$1 AND id=$2',[s.tenantId,claim.id,claim.fencing_token,claim.lease_owner]))?.ok,'stale_fence',403);return result;});}};
 try{
 const config=resolveConfig(claim.tenant_id);requireThat(config.hash===claim.config_hash,'configuration_changed');
 const input=await scoped.transaction('read',async s=>{const e=await evidence(s,claim.extraction_run_id),byId=new Map();for(const issue of e.issues)for(const citation of issue.evidence){const id=citation.message_revision_id;const rank=['unknown','low','medium','high','critical'];const prior=byId.get(id);if(!prior||rank.indexOf(issue.severity)>rank.indexOf(prior.severity))byId.set(id,{id,text:citation.quote,label:issue.category,severity:issue.severity});}const rows=[...byId.values()].sort((a,b)=>a.id.localeCompare(b.id));requireThat(rows.length>0&&rows.length<=32&&rows.every(row=>['low','medium','high','critical'].includes(row.severity)),'insufficient_evidence');return {e,rows};});
 await scoped.transaction('import',s=>s.query('UPDATE public.problem_embedding_requests SET network_started=true WHERE tenant_id=$1 AND job_id=$2',[s.tenantId,claim.id]));
 const gateway=createEmbeddingGateway({...config.gateway,apiKey,runtime,fetch,budgetRepository:createDurableBudgetRepository({database:scoped,purpose:'embedding',jobId:claim.id})});
 const vectors=await gateway.embed({tenantId:claim.tenant_id,taskKey:'embedding:'+claim.id,input:input.rows.map(x=>x.text),dimensions:config.dimensions});
 await scoped.transaction('import',async s=>{
 await evidence(s,claim.extraction_run_id);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':vector-problems']);const touched=new Map(),allowedRuns=[];for(const r of (await s.query('SELECT DISTINCT extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1',[s.tenantId])).rows){try{await evidence(s,r.extraction_run_id);allowedRuns.push(r.extraction_run_id);}catch(e){if(!['EVIDENCE_UNAVAILABLE','source_unavailable'].includes(e.message))throw e;}}allowedRuns.push(claim.extraction_run_id);
 for(let i=0;i<input.rows.length;i++){const source=input.rows[i],id=stableId({tenant:s.tenantId,revision:source.id,model:config.modelId,version:config.version}),vector=JSON.stringify(vectors[i]);const existing=await one(s,'SELECT e.dim,m.problem_id FROM public.embeddings e LEFT JOIN public.problem_embedding_members m ON m.tenant_id=e.tenant_id AND m.embedding_id=e.id WHERE e.tenant_id=$1 AND e.id=$2',[s.tenantId,id]);if(existing){requireThat(existing.dim===config.dimensions&&existing.problem_id,'embedding_space_mismatch');continue;}
 const neighbor=await one(s,"SELECT e.id,m.problem_id,(e.embedding OPERATOR(extensions.<=>) $2::extensions.vector) AS distance FROM public.embeddings e JOIN public.problem_embedding_members m ON m.tenant_id=e.tenant_id AND m.embedding_id=e.id JOIN public.problems p ON p.tenant_id=m.tenant_id AND p.id=m.problem_id WHERE e.tenant_id=$1 AND e.model_id=$3 AND e.dim=$4 AND e.version=$5 AND p.archived_at IS NULL AND m.extraction_run_id=ANY($6::uuid[]) ORDER BY distance,e.id LIMIT 1",[s.tenantId,vector,config.modelId,config.dimensions,config.version,allowedRuns]);
 const problemId=neighbor&&neighbor.distance<=config.threshold?neighbor.problem_id:stableId({tenant:s.tenantId,embedding:id});if(!neighbor||neighbor.distance>config.threshold)await s.query("INSERT INTO public.problems(id,tenant_id,title,provenance,severity,cause_status) VALUES($1,$2,$3,$4,$5,'unknown')",[problemId,s.tenantId,source.label,JSON.stringify({kind:'vector-problem-v1'}),source.severity]);
 await s.query('INSERT INTO public.embeddings(id,tenant_id,model_id,dim,version,content,embedding,message_revision_id,provenance) VALUES($1,$2,$3,$4,$5,$6,$7::extensions.vector,$8,$9)',[id,s.tenantId,config.modelId,config.dimensions,config.version,source.text,vector,source.id,JSON.stringify({extractionRunId:claim.extraction_run_id})]);
 await s.query('INSERT INTO public.problem_embedding_members(tenant_id,embedding_id,problem_id,extraction_run_id,conversation_id) VALUES($1,$2,$3,$4,$5)',[s.tenantId,id,problemId,claim.extraction_run_id,input.e.conversationId]);touched.set(problemId,source.label);
 }
 for(const [id,label] of touched){const members=(await s.query('SELECT m.embedding_id,m.conversation_id,c.order_id FROM public.problem_embedding_members m JOIN public.conversations c ON c.tenant_id=m.tenant_id AND c.id=m.conversation_id WHERE m.tenant_id=$1 AND m.problem_id=$2',[s.tenantId,id])).rows;const p=await one(s,'SELECT title FROM public.problems WHERE tenant_id=$1 AND id=$2',[s.tenantId,id]);await snapshot(s,{id,label:p?.title??label,state:'active',outlier:members.length===1,modelId:config.modelId,dimensions:config.dimensions,embeddingVersion:config.version,embeddingIds:sortedUnique(members.map(x=>x.embedding_id)),conversationIds:sortedUnique(members.map(x=>x.conversation_id)),orderIds:sortedUnique(members.map(x=>x.order_id).filter(Boolean))},{jobId:claim.id});}
 await s.query("UPDATE public.jobs SET state='succeeded',provenance='{}' WHERE tenant_id=$1 AND id=$2",[s.tenantId,claim.id]);
 });return {state:'succeeded',id:claim.id};
 }catch(e){const reason=['insufficient_evidence','configuration_changed','configuration_required','runtime_disabled','missing_key','policy_blocked','budget_exceeded','reconciliation_required','invalid_output','cost_overrun'].includes(e.message)?e.message:'execution_failed';await tx(async s=>{await s.query("UPDATE public.jobs SET state='failed',provenance=$5 WHERE tenant_id=$1 AND id=$2 AND fencing_token=$3 AND lease_owner=$4 AND state='running'",[s.tenantId,claim.id,claim.fencing_token,claim.lease_owner,JSON.stringify({reason})]);});return {state:'failed',id:claim.id,reason};}
 }};
}
