import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';import {setTimeout as delay} from 'node:timers/promises';
import {validate,check,fail,hash,privateJson,privateDirectory,assertAuthorizationCurrent} from './contract.mjs';import {transport} from './transport.mjs';
export function money(bundle){check(Array.isArray(bundle?.items),'METRICS_MISSING');const metrics=bundle.items.flatMap(x=>x.metrics??[]),get=kind=>{const rows=metrics.filter(x=>x.kind===kind);check(rows.length===1,'METRIC_NOT_UNIQUE');return rows[0];};const exposure=get('exposure'),refund=get('refunds');check(exposure.amount_minor==='30000'&&refund.amount_minor==='1500'&&[exposure,refund].every(x=>x.currency==='USD'&&x.exponent===2),'MONEY_MISMATCH');return {exposureMinor:exposure.amount_minor,refundMinor:refund.amount_minor,currency:'USD'};}
export function count(value){if(typeof value==='number'){check(Number.isSafeInteger(value)&&value>=0,'COUNTER_INVALID');return BigInt(value);}check(typeof value==='string'&&/^(0|[1-9][0-9]{0,63})$/.test(value),'COUNTER_INVALID');return BigInt(value);}
export function terminal(job){check(job&&typeof job.state==='string','JOB_RESPONSE_INVALID');if(!['succeeded','partial','failed','cancelled','dead_letter'].includes(job.state))return false;check(job.state==='succeeded','JOB_TERMINAL_FAILED');check(job.counters,'JOB_ACCOUNTING_MISSING');const c=Object.fromEntries(['total','accepted','rejected','duplicates','pending'].map(k=>[k,count(job.counters[k])]));check(c.total===3n&&c.accepted===3n&&c.rejected===0n&&c.duplicates===0n&&c.pending===0n&&count(job.checkpoint)===3n&&c.total===c.accepted+c.rejected+c.duplicates+c.pending,'JOB_ACCOUNTING_MISMATCH');return true;}
export async function runSmoke({release,authorization,config,out,browser}){
 const binding=validate(release,authorization,config);await privateDirectory(out);await privateDirectory(config.controlDirectory);check(browser,'BROWSER_REQUIRED');
 const runnerFiles=Object.fromEntries(await Promise.all(['contract.mjs','transport.mjs','runner.mjs','cli.mjs'].map(async name=>[name,hash(await fs.readFile(new URL(name,import.meta.url)))])));const runId=randomUUID(),report={schema:'vexa-release-smoke-v1',runId,mode:binding.local?'local-synthetic-proof':'remote-authorized',sourceSha:binding.expectedSha,nodeVersion:process.version,browserVersion:browser.version(),runnerFiles,authorizationId:authorization.id,checks:[],requests:[],artifacts:[],views:[],admittedJobs:[],jobObservations:[],fixtureHash:hash(JSON.stringify(config.fixture)),status:'running',pending:['Independent review and formal release authorization remain external.']};
 const authority=Object.freeze({expiresAt:authorization.expiresAt}),authorize=()=>assertAuthorizationCurrent(authority),request=transport(config,report.requests,authorize),A=config.accounts.A,B=config.accounts.B,Q=config.fixture.query;let context,pauseOutstanding=false;
 const save=()=>fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{mode:0o600});
 const step=async(name,fn)=>{try{authorize();const observed=await fn();authorize();report.checks.push({name,status:'pass',observed});}catch(e){report.checks.push({name,status:e.blocked?'blocked':'fail',code:e.code??'SMOKE_CHECK_FAILED'});throw e;}finally{await save();}};
 const need=async(actor,url,body,status=200)=>{const r=await request(actor,url,body===undefined?{}:{method:'POST',body});check(r.status===status,'HTTP_STATUS_UNEXPECTED');return r.data?.data;};
 const control=async(action,details={},compensating=false)=>{
  if(compensating)check(action==='resume_consumer'&&pauseOutstanding,'COMPENSATION_SCOPE_INVALID');else authorize();
  const id=randomUUID(),file=path.join(config.controlDirectory,id+'.request.json'),end=compensating?Date.now()+config.operatorTimeoutMs:Math.min(Date.now()+config.operatorTimeoutMs,Date.parse(authority.expiresAt));
  if(action==='arm_pause_after_admission')pauseOutstanding=true;
  await fs.writeFile(file,JSON.stringify({schema:'vexa-smoke-control-v1',runId,id,authorizationId:authorization.id,tenantId:A.tenantId,action,expiresAt:new Date(end).toISOString(),...details,...(compensating?{compensating:true,originalAuthorizationExpiresAt:authority.expiresAt}:{} )}),{flag:'wx',mode:0o600});
  while(Date.now()<end){if(!compensating)authorize();try{const ack=await privateJson(path.join(config.controlDirectory,id+'.ack.json'));if(!compensating)authorize();check(ack.runId===runId&&ack.id===id&&ack.authorizationId===authorization.id&&ack.action===action&&ack.tenantId===A.tenantId&&ack.completed===true,'CONTROL_ACK_INVALID');return;}catch(e){if(e.code!=='ENOENT')throw e;}await delay(200);}
  if(!compensating)authorize();fail('OPERATOR_CONTROL_UNAVAILABLE',true);
 };
 const importSyn=async(tag)=>{const csv=Buffer.from('id,text,date,role,conversation\n'+Array.from({length:3},(_,i)=>`SYN-${runId}-${tag}-${i},SYN smoke message ${i},2026-09-01T00:00:00Z,customer,SYN-${runId}-${tag}`).join('\n')+'\n'),sha=hash(csv),reserved=await need(A,'/api/imports',{connection_id:config.fixture.connectionId,mapping_version:'csv-message-v1',content_type:'text/csv',size:csv.length,sha256:sha},201);check(typeof reserved?.upload_url==='string','UPLOAD_CAPABILITY_MISSING');check(reserved.object_path===A.tenantId+'/imports/'+reserved.import_id+'/original','UPLOAD_TENANT_BINDING_INVALID');check((await request(null,reserved.upload_url,{method:'PUT',body:csv,upload:true})).status===200,'UPLOAD_FAILED');const mapped=await need(A,`/api/imports/${reserved.import_id}/mapping`,{mapping:{columns:{id:'id',text:'text',date:'date',role:'role',conversation:'conversation'},timezone:'UTC',dateFormat:'iso'},expected_version:'csv-message-v1'}),confirmed=await need(A,`/api/imports/${reserved.import_id}/confirm`,{upload_token:mapped.upload_token,sha256:sha,mapping_version:mapped.mapping_version},202),detail=await need(A,`/api/imports/${reserved.import_id}`);const jobId=confirmed.job_id??detail.import?.job_id;check(/^[a-f0-9-]{36}$/.test(jobId??''),'DURABLE_JOB_MISSING');const admitted={jobId,importId:reserved.import_id,csvSha:sha};report.admittedJobs.push(admitted);await save();return admitted;};
 const poll=async(jobId)=>{const end=Date.now()+config.timeoutMs;while(Date.now()<end){const job=await need(A,'/api/jobs/'+jobId);report.jobObservations.push({jobId,state:['queued','running','succeeded','partial','failed','cancelled','dead_letter'].includes(job?.state)?job.state:'invalid',checkpoint:count(job?.checkpoint).toString(),counters:Object.fromEntries(Object.entries(job?.counters??{}).filter(([k])=>['total','accepted','rejected','duplicates','pending'].includes(k)).map(([k,v])=>[k,count(v).toString()]))});if(terminal(job))return {state:job.state,counters:job.counters,checkpoint:job.checkpoint};await delay(250);}fail('JOB_NOT_TERMINAL');};
 try{
  await step('served_revision',async()=>{const r=await request(null,'/api/health/version');check(r.status===200&&r.data?.data?.revision===binding.expectedSha,'SERVED_SHA_MISMATCH');return {expected:binding.expectedSha,observed:r.data.data.revision};});
  await step('two_authenticated_tenants',async()=>{const imports=await need(A,'/api/imports');await need(B,'/api/imports');check(imports.connections?.some(c=>c.id===config.fixture.connectionId&&c.source==='csv'),'CSV_CONNECTION_NOT_AUTHORIZED');return {accounts:2,distinctTenants:true};});
  await step('durable_import_final_accounting',async()=>{const job=await importSyn('normal');await fs.writeFile(path.join(config.controlDirectory,runId+'.normal-job.json'),JSON.stringify({runId,jobId:job.jobId}),{mode:0o600});return {...job,...await poll(job.jobId)};});
  let bundle;
  await step('financial_api_and_protected_export',async()=>{bundle=await need(A,'/api/workspace?'+Q+'&resource=metrics');const values=money(bundle),exported=await request(A,'/api/workspace/export?'+Q+'&resource=metrics&format=json');check(exported.status===200&&exported.headers.get('cache-control')?.includes('private'),'EXPORT_NOT_PROTECTED');money(exported.data);check(JSON.stringify(exported.data)===JSON.stringify(bundle),'EXPORT_SCOPE_MISMATCH');return {...values,snapshotId:bundle.meta.snapshot_id,scopeHash:bundle.meta.scope_hash,exportSha:hash(exported.bytes)};});
  const forbidden=async()=>{const known=await request(B,'/api/problems/'+config.fixture.foreignProblemId);check(known.status===200&&known.data?.problem?.id===config.fixture.foreignProblemId,'FOREIGN_FIXTURE_NOT_VERIFIED');check([403,404].includes((await request(A,'/api/problems/'+config.fixture.foreignProblemId)).status),'FOREIGN_PROBLEM_READ_ALLOWED');for(const url of ['/api/workspace?'+Q+'&resource=metrics','/api/workspace/export?'+Q+'&resource=metrics&format=json'])check([403,404].includes((await request(B,url)).status),'CROSS_TENANT_READ_ALLOWED');for(const url of ['/api/workspace/detail/problem/'+config.fixture.foreignProblemId+'?'+Q,'/api/workspace/detail/customer/'+config.fixture.foreignCustomerId+'?'+Q])check([403,404].includes((await request(A,url)).status),'FOREIGN_ID_READ_ALLOWED');};
  await step('known_foreign_tenant_ids',async()=>{await forbidden();return {denied:true};});
  await step('eight_product_views',async()=>{context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});await context.addCookies(A.cookies.map(c=>({...c,url:config.origin})));await context.route('**/*',r=>{try{authorize();}catch{return r.abort();}return new URL(r.request().url()).origin===config.origin?r.continue():r.abort();});const page=await context.newPage();const routes=[['overview','/overview?'+Q],['problems','/problems?'+Q],['problem','/problems/'+config.fixture.problemId+'?'+Q],['customer','/customers/'+config.fixture.customerId+'?'+Q],['explorer','/explorer?'+Q],['recommendations','/recommendations?'+Q],['interventions','/interventions?'+Q],['brief','/briefs/'+config.fixture.briefId]];for(const [name,url]of routes){const apis={overview:'/api/workspace?'+Q+'&resource=metrics',problems:'/api/workspace?'+Q+'&resource=problems',problem:'/api/workspace/detail/problem/'+config.fixture.problemId+'?'+Q,customer:'/api/workspace/detail/customer/'+config.fixture.customerId+'?'+Q,explorer:'/api/explorer?'+Q,recommendations:'/api/recommendations?'+Q,interventions:'/api/interventions?'+Q,brief:'/api/briefs/'+config.fixture.briefId};const view=await need(A,apis[name]);check(view&&typeof view==='object','VIEW_DATA_MISSING');if(['recommendations','interventions','problems'].includes(name))check(view.items?.length>0,'VIEW_FIXTURE_EMPTY');authorize();const r=await page.goto(config.origin+url);check(r?.status()===200&&new URL(page.url()).origin===config.origin&&!new URL(page.url()).pathname.includes('login'),'VIEW_UNAVAILABLE');await page.waitForLoadState('networkidle');await page.waitForFunction(()=>document.querySelectorAll('[aria-busy=\"true\"]').length===0);check(await page.locator('main#contenido').count()===1,'VIEW_ROOT_MISSING');check(await page.getByRole('heading',{level:1}).count()>0&&await page.getByRole('heading',{level:1}).first().isVisible(),'VIEW_HEADING_MISSING');report.views.push({name,rootCount:await page.locator('main#contenido').count(),nestedMainCount:await page.locator('main#contenido main').count(),headingPresent:true});if(name==='overview'){check((await page.getByText('300.00 USD',{exact:false}).count())>0&&(await page.getByText('15.00 USD',{exact:false}).count())>0,'UI_MONEY_MISMATCH');}authorize();const file=name+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});await fs.chmod(path.join(out,file),0o600);report.artifacts.push({file,sha256:hash(await fs.readFile(path.join(out,file)))});}await context.close();context=null;return {count:8};});
  await step('bounded_consumer_fault_and_recovery',async()=>{await control('arm_pause_after_admission');const job=await importSyn('fault');pauseOutstanding=true;await control('pause_consumer',{jobId:job.jobId,importId:job.importId});const initial=await need(A,'/api/jobs/'+job.jobId);check(!terminal(initial),'FAULT_WINDOW_MISSED');const end=Date.now()+config.timeoutMs;let health;while(Date.now()<end){const r=await request(A,'/api/jobs/health');if(r.status===503&&r.data?.data?.healthy===false&&r.data.data.reasons?.includes('NO_HEARTBEAT')){health=r.data.data;break;}await delay(500);}check(health,'CONSUMER_ALARM_NOT_OBSERVED');const pending=await need(A,'/api/jobs/'+job.jobId);check(!terminal(pending)&&pending.checkpoint===initial.checkpoint&&pending.counters.pending===initial.counters.pending,'PAUSED_JOB_CHANGED');const blocked=await request(A,'/api/imports',{method:'POST',body:{connection_id:config.fixture.connectionId,mapping_version:'csv-message-v1',content_type:'text/csv',size:10,sha256:'a'.repeat(64)}});check(blocked.status===503,'UNHEALTHY_ADMISSION_NOT_BLOCKED');await control('resume_consumer',{jobId:job.jobId});pauseOutstanding=false;const final=await poll(job.jobId),again=await need(A,'/api/imports/'+job.importId);check(again.import?.job_id===job.jobId,'JOB_ID_CHANGED_ON_RECOVERY');return {...job,alarm:health.reasons,checkpointPreserved:pending.checkpoint,pendingBefore:initial.counters.pending,pendingDuring:pending.counters.pending,stateDuring:pending.state,final};});
  await step('revocation_current_reads_and_export',async()=>{await control('revoke_A');for(const url of ['/api/workspace?'+Q+'&resource=metrics','/api/workspace/export?'+Q+'&resource=metrics&format=json','/api/problems/'+config.fixture.foreignProblemId,'/api/workspace/detail/customer/'+config.fixture.foreignCustomerId+'?'+Q])check([401,403].includes((await request(A,url)).status),'REVOKED_ACCESS_ALLOWED');await need(B,'/api/imports');return {Adenied:true,BstillAuthorized:true};});
  report.status='pass';
 }catch(e){report.status=e.blocked?'blocked':'fail';report.error={code:e.code??'SMOKE_EXECUTION_FAILED'};}finally{if(context)await context.close();if(pauseOutstanding){try{await control('resume_consumer',{},true);report.cleanup={resumeRequested:true,operatorAcknowledged:true,compensating:true};}catch{report.cleanup={resumeRequested:true,operatorAcknowledged:false};report.status='blocked';}}await save();}
 return report;
}
