import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {validate,origin,privateJson,operations,assertAuthorizationCurrent} from '../contract.mjs';import {money,terminal,count} from '../runner.mjs';
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',sha='a'.repeat(40);
const input=()=>{const config={origin:'https://smoke.example.invalid',storageOrigin:'https://storage.example.invalid',accounts:Object.fromEntries([['A',a],['B',b]].map(([key,id])=>[key,{tenantId:id,cookies:[{name:'vexa_active_org',value:id},{name:'sb-test-auth-token',value:'SYN-no-real-token'}]}])),fixture:Object.fromEntries(['connectionId','problemId','customerId','briefId','foreignProblemId','foreignCustomerId'].map(k=>[k,a])),timeoutMs:1000,operatorTimeoutMs:1000,controlDirectory:'/private/operator'};Object.assign(config.fixture,{query:'snapshot_id='+a+'&scope_hash='+'b'.repeat(64),expected:{exposureMinor:'30000',refundMinor:'1500',currency:'USD'}});const release={schema_version:'vexa-release-manifest-v1',source:{commit_sha:sha},destination:{url:config.origin}},authorization={schema:'vexa-smoke-authorization-v1',id:'SYN-contract',operator:'SYN contract',approvalReference:'SYN contract NOT remote authorization',confirmed:true,syntheticOnly:true,environment:'remote-authorized',expiresAt:new Date(Date.now()+10000).toISOString(),releaseSha:sha,origin:config.origin,storageOrigin:config.storageOrigin,tenants:[a,b],operations};return{release,authorization,config};};
test('explicit bound target, tenant, expiry and operation authorization',()=>{const i=input();validate(i.release,i.authorization,i.config);for(const patch of [{confirmed:false},{releaseSha:'b'.repeat(40)},{origin:'https://other.invalid'},{tenants:[b,a]},{expiresAt:'2000-01-01'},{operations:['read']}])assert.throws(()=>validate(i.release,{...i.authorization,...patch},i.config));assert.throws(()=>validate(i.release,i.authorization,{...i.config,accounts:{...i.config.accounts,B:i.config.accounts.A}}));});
test('remote HTTP, credentials, query and nonloopback local origins denied',()=>{for(const url of ['http://example.invalid','https://user:secret@example.invalid','https://example.invalid/?token=secret','http://192.168.1.1'])assert.throws(()=>origin(url,false));assert.throws(()=>origin('http://192.168.1.1',true));assert.equal(origin('http://127.0.0.1:62424',true),'http://127.0.0.1:62424');});
test('private inputs reject readable secrets and symlinks',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'vexa-smoke-contract-'));try{const f=path.join(d,'config.json');await fs.writeFile(f,'{}',{mode:0o644});await assert.rejects(privateJson(f),/PRIVATE_INPUT_REQUIRED/);await fs.chmod(f,0o600);assert.deepEqual(await privateJson(f),{});await fs.symlink(f,path.join(d,'link'));await assert.rejects(privateJson(path.join(d,'link')),/PRIVATE_INPUT_REQUIRED/);}finally{await fs.rm(d,{recursive:true,force:true});}});
test('unknown not zero; missing export rows and incomplete terminal fail',()=>{const metrics=[{kind:'exposure',amount_minor:'30000',currency:'USD',exponent:2},{kind:'refunds',amount_minor:'1500',currency:'USD',exponent:2}];money({items:[{metrics}]});assert.throws(()=>money({items:[{metrics:metrics.slice(0,1)}]}));assert.throws(()=>money({items:[{metrics:[metrics[0],{...metrics[1],amount_minor:null}]}]}));assert.equal(terminal({state:'queued'}),false);assert.throws(()=>terminal({state:'succeeded',counters:{total:3,accepted:3,rejected:0,duplicates:0,pending:1},checkpoint:3}));});

test('PostgreSQL BIGINT wire strings retain exact accounting; invalid values are never zero',()=>{assert.equal(terminal({state:'succeeded',checkpoint:3,counters:{total:'3',accepted:'3',rejected:'0',duplicates:'0',pending:'0'}}),true);for(const value of [null,undefined,NaN,Infinity,true,false,1.5,-1,'-1','+3','3e0','03','0.0',Number.MAX_SAFE_INTEGER+1])assert.throws(()=>count(value),/COUNTER_INVALID/);assert.equal(count('9007199254740993'),9007199254740993n);});

import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {transport} from '../transport.mjs';
test('transport never follows redirects or forwards app credentials to Storage',async()=>{const original=globalThis.fetch,events=[],config={origin:'https://app.example.invalid',storageOrigin:'https://storage.example.invalid'},send=transport(config,events,()=>{});let calls=0;try{globalThis.fetch=async(_url,options)=>{calls++;assert.equal(options.redirect,'manual');return new Response('',{status:302,headers:{location:'https://outside.example.invalid'}});};await assert.rejects(send(null,'https://outside.example.invalid'),/OUTSIDE_ORIGIN_DENIED/);assert.equal(calls,0);await assert.rejects(send(null,'/api/health/version'),/REDIRECT_DENIED/);globalThis.fetch=async(_url,options)=>{assert.equal(options.headers.cookie,undefined);assert.equal(options.headers.authorization,undefined);return new Response('');};await send(null,'https://storage.example.invalid/object?token=SYN-capability',{method:'PUT',body:Buffer.from('SYN'),upload:true});assert.ok(!JSON.stringify(events).includes('SYN-capability'));}finally{globalThis.fetch=original;}});
test('CLI executes through symlink aliases and importing it does not run',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'vexa-smoke-entry-'));try{const source=fileURLToPath(new URL('../cli.mjs',import.meta.url)),alias=path.join(d,'alias.mjs');await fs.symlink(source,alias);const r=spawnSync(process.execPath,[alias,'--invalid','SYN'],{encoding:'utf8'});assert.equal(r.status,1,'CLI_ALIAS_MUST_EXECUTE_NOT_SILENT_EXIT_ZERO');assert.match(r.stderr,/SMOKE_INPUT_OR_OUTPUT_INVALID/);const imported=spawnSync(process.execPath,['--input-type=module','-e',`await import(${JSON.stringify(new URL('../cli.mjs',import.meta.url).href)})`],{encoding:'utf8'});assert.equal(imported.status,0);assert.equal(imported.stdout+imported.stderr,'');}finally{await fs.rm(d,{recursive:true,force:true});}});

 test('expiry prevents the next HTTP effect after a prior authorized request',async()=>{const original=globalThis.fetch;let calls=0;const a={expiresAt:new Date(Date.now()+10000).toISOString()},send=transport({origin:'https://app.example.invalid',storageOrigin:'https://storage.example.invalid'},[],()=>assertAuthorizationCurrent(a));try{globalThis.fetch=async()=>{calls++;return new Response('{}');};await send(null,'/api/health/version');a.expiresAt='2000-01-01T00:00:00Z';await assert.rejects(send(null,'/api/imports',{method:'POST',body:{}}),/AUTHORIZATION_EXPIRED/);assert.equal(calls,1);assert.throws(()=>transport({},[]),/AUTHORIZATION_GUARD_REQUIRED/);}finally{globalThis.fetch=original;}});
