'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {PushDevice} from '../../../../../packages/notifications/push.mjs';
type View={observedAt:number;devices:PushDevice[];configured:boolean;publicKey:string|null;currentDeviceId:string|null};
const keyBytes=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function readyWorker(signal:AbortSignal){
 signal.throwIfAborted();
 let timer:ReturnType<typeof setTimeout>|undefined;
 let abort:()=>void=()=>{};
 const interrupted=new Promise<never>((_,reject)=>{abort=()=>reject(signal.reason);signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>reject(Error('worker_ready_timeout')),15000);});
 try{return await Promise.race([(async()=>{const registration=await navigator.serviceWorker.register('/service-worker.js',{scope:'/'});signal.throwIfAborted();await navigator.serviceWorker.ready;return registration;})(),interrupted]);}
 finally{clearTimeout(timer);signal.removeEventListener('abort',abort);}
}
export function PushPreferences(){
 const [view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[permission,setPermission]=useState<NotificationPermission|null>(null),[supported,setSupported]=useState<boolean|null>(null),[observedAt,setObservedAt]=useState(0),[loading,setLoading]=useState(true);const generation=useRef(0),lifetime=useRef<AbortController|null>(null);
 const read=useCallback(async(signal:AbortSignal|undefined=lifetime.current?.signal)=>{
  const epoch=++generation.current;setLoading(true);setMessage('');
  try{const r=await fetch('/api/notifications/push',{cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(15000)});if(!r.ok)throw Error('PUSH_READ_FAILED');const body=await r.json();if(signal?.aborted||epoch!==generation.current)return false;if(!body.data||!Array.isArray(body.data.devices)||typeof body.data.configured!=='boolean'||!Number.isFinite(body.data.observedAt))throw Error('PUSH_READ_INVALID');setView(body.data as View);setObservedAt(body.data.observedAt);return true;}
  catch{if(!signal?.aborted&&epoch===generation.current){setView(null);setMessage('No se pudo verificar el estado de los dispositivos. Actualiza para volver a comprobarlo.');}return false;}
  finally{if(!signal?.aborted&&epoch===generation.current)setLoading(false);}
 },[]);
 useEffect(()=>{const controller=new AbortController();lifetime.current=controller;void Promise.resolve().then(()=>{if(controller.signal.aborted)return;setSupported(window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window);if('Notification' in window)setPermission(Notification.permission);return read(controller.signal);});return()=>{controller.abort();};},[read]);
 async function post(body:unknown,signal:AbortSignal){const r=await fetch('/api/notifications/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.any([signal,AbortSignal.timeout(15000)])});if(!r.ok)throw Error('No se confirmó el cambio. Actualiza el estado antes de volver a intentar.');return r.json();}
 async function enable(){
  const signal=lifetime.current?.signal;if(!signal||signal.aborted||!view?.configured||!view.publicKey||busy||permission==='denied')return;
  setBusy(true);setMessage('');let subscription:PushSubscription|null=null,registrationAttempted=false,permissionRejected=false;
  try{
   const permission=await Notification.requestPermission();signal.throwIfAborted();setPermission(permission);if(permission!=='granted'){permissionRejected=true;throw Error('permission_not_granted');}
   const registration=await readyWorker(signal);signal.throwIfAborted();
   subscription=await registration.pushManager.getSubscription();signal.throwIfAborted();
   if(subscription){const oldKey=subscription.options.applicationServerKey;if(!oldKey||btoa(String.fromCharCode(...new Uint8Array(oldKey))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')!==view.publicKey){await subscription.unsubscribe();subscription=null;}}
   subscription??=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(view.publicKey)});
   signal.throwIfAborted();registrationAttempted=true;await post({op:'register',consent:true,subscription:subscription.toJSON()},signal);if(!await read(signal))return;setMessage('Dispositivo registrado. Esto no confirma una entrega. Activa también tus preferencias de eventos Push.');
  }catch{if(signal.aborted)return;if(subscription&&!registrationAttempted)await subscription.unsubscribe().catch(()=>false);setView(null);setMessage(permissionRejected?'Permiso no concedido. Puedes cambiarlo desde los ajustes del navegador.':'No se confirmó la activación. Actualiza el estado para comprobar si quedó registrada antes de volver a intentarlo.');}finally{if(!signal.aborted)setBusy(false);}
 }
 async function revoke(device:PushDevice){const signal=lifetime.current?.signal;if(!signal||signal.aborted||busy)return;setBusy(true);setMessage('');try{await post({op:'revoke',id:device.id},signal);signal.throwIfAborted();if(device.deviceId===view?.currentDeviceId){const registration=await navigator.serviceWorker.getRegistration('/');const subscription=await registration?.pushManager.getSubscription();signal.throwIfAborted();await subscription?.unsubscribe();}if(!await read(signal))return;setMessage('Suscripción desactivada.');}catch{if(signal.aborted)return;setView(null);setMessage('No se confirmó la desactivación. Actualiza el estado para comprobar si se guardó antes de volver a intentarlo.');}finally{if(!signal.aborted)setBusy(false);}}
 return <section aria-labelledby="push-title" aria-busy={loading||busy}><p className="eyebrow">Tu espacio de trabajo</p><h1 id="push-title">Notificaciones en este dispositivo</h1><p>Recibe un aviso genérico de Rovaq AI, sin datos de clientes ni importes. Al abrirlo se comprueba tu acceso actual.</p><p>La autorización caduca con esta sesión. Al cerrar sesión se desactivan los dispositivos de tu cuenta; al cambiar de organización se desactiva este dispositivo. Puedes volver a activarlo aquí.</p><p><Link href="/settings/notifications">Preferencias por evento</Link> · <Link href="/notifications">Volver a notificaciones</Link></p>{supported===true&&<div className="record-card"><h2>Permiso del navegador</h2><p>{permission==='granted'?'Permitido':permission==='denied'?'Bloqueado. Cambia el permiso en los ajustes del navegador y actualiza el estado.':'Sin solicitar. Sólo se pedirá cuando actives los avisos.'}</p><p>El permiso del navegador, el registro del dispositivo y tus preferencias por evento son independientes. Para recibir avisos deben estar activos los tres.</p></div>}{loading&&<p role="status">Cargando estado de los dispositivos…</p>}{supported===false&&<p>Este navegador no ofrece Web Push en este contexto. En iPhone o iPad, abre Rovaq AI desde su acceso instalado en la pantalla de inicio.</p>}{view&&!view.configured&&<p>Push no está configurado en este entorno. No se solicitará permiso.</p>}<button disabled={supported!==true||permission==='denied'||!view?.configured||busy||loading} onClick={()=>void enable()}>Activar avisos en este dispositivo</button><button disabled={busy||loading} onClick={()=>{if('Notification' in window)setPermission(Notification.permission);void read();}}>Actualizar estado</button><p role="status" aria-live="polite">{message}</p>{view&&<ul aria-label="Dispositivos registrados" style={{listStyle:'none',padding:0,display:'grid',gap:'1rem'}}>{!view.devices.length&&<li>No hay dispositivos registrados en esta organización.</li>}{view.devices.map((d,i)=><li className="record-card" key={d.id}>Dispositivo {i+1}{d.deviceId===view.currentDeviceId?' (este navegador)':''}: {d.status==='revoked'?'desactivado':new Date(d.expiresAt).getTime()<=observedAt?'caducado':'activo'} — válido hasta {new Date(d.expiresAt).toLocaleString()}. <button disabled={busy||loading||d.status==='revoked'} onClick={()=>void revoke(d)}>Desactivar</button></li>)}</ul>}</section>;
}
