import assert from 'node:assert/strict';
import test from 'node:test';
import {createEmbeddingGateway} from './embeddings.mjs';
// Synthetic transport only; these prices and vectors do not represent live data.
function fixture(){const now=Date.now();return {tenantId:'SYN-tenant',input:['Synthetic drill stopped'],gateway:{policy:{authorized:true,version:'SYN',dataCollection:'deny',requireZdr:true,residency:'unrestricted',allowedModels:['openai/text-embedding-3-small'],providers:['azure'],timeoutMs:1000,currency:'USD',exponent:6,window:'SYN-window',maxInputBytes:64000,maxResponseBytes:128000,maxCostPerCallMinor:'10000',maxCostPerTaskMinor:'10000',tenantLimitMinor:'20000'},candidate:{model:'openai/text-embedding-3-small',provider:'azure',zdr:true,dataCollection:'deny',residency:'unrestricted',contextTokens:8192,pricing:{allChargesIncluded:true,version:'SYN',validUntil:new Date(now+60000).toISOString(),overheadTokens:1024,inputMicroUsdPerToken:'1'}},catalog:{version:'SYN',fetchedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+60000).toISOString(),models:[{id:'openai/text-embedding-3-small',dimensions:3,contextTokens:8192}]}},dimensions:3};}
const invalid=Symbol('invalid');const samples=[['observed tiny',1.8e-7,'1'],['decimal number',0.00000018,'1'],['minimal positive',Number.MIN_VALUE,'1'],['six boundary',0.000001,'1'],['above boundary',0.0000010000000000000002,'2'],['below boundary',0.0000009999999999999999,'1'],['explicit zero',0,'0'],['negative zero',-0,'0'],['negative',-0.000001,invalid],['NaN',NaN,invalid],['infinite',Infinity,invalid],['negative infinity',-Infinity,invalid],['missing',undefined,invalid],['null',null,invalid],['boolean',true,invalid],['object',{toString:()=> '0'},invalid],['scientific string','1.8e-7',invalid],['decimal string','0.00000018','1'],['leading zeros','00000.000001','1'],['decimal18','0.000000000000000001','1'],['decimal19','0.0000000000000000001',invalid],['20integer','99999999999999999999','99999999999999999999000000'],['21integer','100000000000000000000',invalid],['numeric max magnitude',Number.MAX_VALUE,invalid],['numeric1e20',1e20,invalid],['numeric1e19',1e19,'10000000000000000000000000'],['overrun',0.5,'500000']];
for(const [name,cost,expected] of samples)test("reported cost: "+name,async()=>{const p=fixture();let settlement,held,attempts=[];const budgetRepository={reserve:async q=>{held=q;return{acquired:true,reservationId:'SYN'}},recordAttempt:async(_,e)=>attempts.push(e),finalize:async(_,v)=>{settlement=v}};
// NaN/Infinity are not legal JSON numbers; inject a parsed object via Number token
// overflow (1e999), or null as JSON serialization specifies, to verify unknown hold.
let body=JSON.stringify({model:p.gateway.candidate.model,data:[{index:0,embedding:[1,...Array(2).fill(0)]}],usage:{...(cost===undefined?{}:{cost})}});if(name==='infinite')body=body.replace('"cost":null','"cost":1e999');if(name==='negative infinity')body=body.replace('"cost":null','"cost":-1e999');
const action=()=>createEmbeddingGateway({...p.gateway,apiKey:'SYN',runtime:'enabled',budgetRepository,fetch:async()=>new Response(body)}).embed({tenantId:p.tenantId,taskKey:'SYN_'+name,input:p.input,dimensions:3});
if(expected===invalid){await assert.rejects(action,e=>e.code==='reconciliation_required',name);assert.equal(settlement.state,'uncertain',name);assert.equal(settlement.actualMinor,null,name);}else{const over=BigInt(expected)>BigInt(p.gateway.policy.maxCostPerCallMinor);if(over)await assert.rejects(action,e=>e.code==='cost_overrun',name);else assert.equal((await action())[0].length,3,name);assert.equal(settlement.state,'settled',name);assert.equal(settlement.actualMinor,expected,name);assert.equal(settlement.reportedMinor,expected,name);}
assert.ok(BigInt(held.amountMinor)>0n);assert.equal(attempts.length,2);});

const canonical='openai/text-embedding-3-small',wire='text-embedding-3-small';
const aliasSamples=[['exact','azure',canonical,canonical,true],['observed alias','azure',canonical,wire,true],['other provider','openai',canonical,wire,false],['provider display case','Azure',canonical,wire,false],['large requested','azure','openai/text-embedding-3-large',wire,false],['large response','azure',canonical,'text-embedding-3-large',false],['foo requested','azure','foo/text-embedding-3-small',wire,false],['foo response','azure',canonical,'foo/text-embedding-3-small',false],['absent','azure',canonical,undefined,false],['null','azure',canonical,null,false],['boolean','azure',canonical,true,false],['number','azure',canonical,123,false],['object','azure',canonical,{model:wire},false],['array','azure',canonical,[wire],false],['spaces','azure',canonical,' '+wire,false],['canonical other provider','openai',canonical,canonical,true]];
for(const [name,provider,requested,responseModel,ok] of aliasSamples)test("response model: "+name,async()=>{const original=fixture();const g=structuredClone(original.gateway);g.candidate.model=requested;g.candidate.provider=provider;g.policy.allowedModels=[requested];g.policy.providers=[provider];g.catalog.models[0].id=requested;let settled,calls=0;const budgetRepository={reserve:async()=>({acquired:true,reservationId:'SYN'}),recordAttempt:async()=>{},finalize:async(_,x)=>{settled=x}};const action=()=>createEmbeddingGateway({...g,apiKey:'SYN',runtime:'enabled',budgetRepository,fetch:async()=>{calls++;return new Response(JSON.stringify({...(responseModel===undefined?{}:{model:responseModel}),usage:{cost:1.8e-7},data:[{index:0,embedding:[1,...Array(2).fill(0)]}]}));}}).embed({tenantId:original.tenantId,taskKey:'SYN_'+name,input:original.input,dimensions:3});if(ok)assert.equal((await action())[0].length,3,name);else await assert.rejects(action,e=>e.code==='invalid_output',name);assert.equal(calls,1);assert.equal(settled.state,'settled',name);assert.equal(settled.actualMinor,'1',name);});
