import {test} from 'node:test';import assert from 'node:assert/strict';
import {createGateway} from './index.mjs';import {validateEvidence,sha256,extractionSchema} from '../intelligence/index.mjs';
const now=Date.now(),future=new Date(now+3600000).toISOString();
function input(text,other=[]){return{tenantId:'SYN',taskKey:'SYN',role:'extraction',taxonomy:['product'],revisions:[{tenant_id:'SYN',message_revision_id:'SYN-r1',role:'customer',text,...{privateMap:'MUST_NOT_LEAVE'}},...other]};}
function classification(span){return{issues:[{category:'product',severity:'medium',evidence:[span]}],sentiment:'negative',intent:'complaint',urgency:'normal',entities:[],abstention:null};}
async function run(data,{respond,limit=1000000,contextTokens=1000000,ceiling='10000000',extraPolicy={}}={}){
 let payload,body,reservations=0,calls=0,held;const policy={version:'SYN',authorized:true,allowedModels:['SYN/model'],providers:['SYN/provider'],dataCollection:'deny',requireZdr:true,residency:'unrestricted',maxAttempts:1,timeoutMs:1000,maxOutputTokens:1000,maxInputBytes:limit,maxResponseBytes:1000000,maxCostPerCallMinor:ceiling,maxCostPerTaskMinor:ceiling,tenantLimitMinor:'20000000',window:'SYN',currency:'USD',exponent:6,...extraPolicy};const model={model:'SYN/model',provider:'SYN/provider',residency:'unrestricted',structuredOutput:true,dataCollection:'deny',zdr:true,contextTokens,pricing:{version:'SYN',validUntil:future,allChargesIncluded:true,inputMicroUsdPerToken:'1',outputMicroUsdPerToken:'1',overheadTokens:1024}};
 const budgetRepository={reserve:async q=>{reservations++;held=q.amountMinor;return{acquired:true,reservationId:'SYN'};},recordAttempt:async()=>{},finalize:async()=>{}};
 const gateway=createGateway({policy,modelsByRole:{extraction:[model]},catalog:{version:'SYN',fetchedAt:new Date(now).toISOString(),expiresAt:future,models:[{id:model.model,contextTokens,supportedParameters:['response_format']}]},apiKey:'SYN-no-key',runtime:'enabled',budgetRepository,fetch:async(_,init)=>{calls++;body=JSON.parse(init.body);payload=JSON.parse(body.messages[1].content);const value=respond?respond(payload):classification(payload.revisions[0].available_evidence[0].ref);return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}],usage:{cost:'0.00001'}}));}});const result=await gateway.extract(data);return{result,payload,body,reservations,calls,held};
}
test('wire refs decode exact NFD and emoji evidence/entity values without regeneration',async()=>{const original='Cafe\u0301 drill 🔧 motor stopped',r=await run(input(original),{respond:p=>{const row=p.revisions[0],s=row.available_evidence[0],v=row.available_values.find(v=>v.value==='Cafe\u0301');assert.ok(v);return{...classification(s.ref),entities:[{type:'product_mention',value:{ref:v.ref},evidence:[s.ref]}]};}});assert.equal(r.result.ok,true);assert.equal(r.result.data.issues[0].evidence[0].quote,original);assert.equal(r.result.data.entities[0].value,'Cafe\u0301');assert.equal(r.result.data.issues[0].evidence[0].end,Array.from(original).length);assert.equal(r.result.data.issues[0].evidence[0].ref,undefined);assert.equal(r.payload.revisions[0].text,original);assert.equal(JSON.stringify(r.body).includes('MUST_NOT_LEAVE'),false);});
test('metadata binds final persisted schema while separately identifying actual wire schema',async()=>{const r=await run(input('product broken'));assert.equal(r.result.ok,true);assert.equal(r.result.meta.schemaHash,sha256(JSON.stringify(extractionSchema(['product'],{modelOutput:true}))));assert.equal(r.result.meta.wireSchemaHash,sha256(JSON.stringify(r.body.response_format.json_schema.schema)));assert.notEqual(r.result.meta.schemaHash,r.result.meta.wireSchemaHash);assert.deepEqual(r.body.response_format.json_schema.schema.properties.issues.items.properties.evidence.items.anyOf[1].enum,['r0s0']);});
test('legacy exact spans and literal entity values remain compatible',async()=>{const r=await run(input('drill broken'),{respond:p=>{const {ref,...span}=p.revisions[0].available_evidence[0];return{...classification(span),entities:[{type:'product_mention',value:'drill',evidence:[span]}]};}});assert.equal(r.result.ok,true);assert.equal(r.result.data.entities[0].value,'drill');});
for(const [name,respond] of [
 ['unknown evidence',()=>classification('r99s0')],
 ['evidence object ref with extra key',()=>classification({ref:'r0s0',extra:true})],
 ['unknown entity value',()=>({...classification('r0s0'),entities:[{type:'product_mention',value:{ref:'r0v999'},evidence:['r0s0']} ]})],
 ['entity ref extra key',()=>({...classification('r0s0'),entities:[{type:'product_mention',value:{ref:'r0v0',extra:true},evidence:['r0s0']} ]})],
 ['entity ref array',()=>({...classification('r0s0'),entities:[{type:'product_mention',value:['r0v0'],evidence:['r0s0']} ]})],
 ['cross revision entity',()=>({...classification('r0s0'),entities:[{type:'product_mention',value:{ref:'r1v0'},evidence:['r0s0']} ]})]
])test(name+' fails closed with no partial success',async()=>{const other={tenant_id:'SYN',message_revision_id:'SYN-r2',role:'agent',text:'drill broken'};const r=await run(input('drill broken',[other]),{respond});assert.equal(r.result.error.code,'invalid_output');assert.equal(r.result.data,undefined);assert.equal(r.calls,1);});
test('foreign tenant revision rejected before reference map/budget/network',async()=>{const r=await run(input('drill broken',[{tenant_id:'FOREIGN',message_revision_id:'foreign',role:'customer',text:'secret'}]));assert.equal(r.result.error.code,'invalid_input');assert.equal(r.reservations,0);assert.equal(r.calls,0);});
test('chunks preserve 4000CP ceiling/200 overlap and decoder uses correct referenced revision',async()=>{const text='😀e\u0301'.repeat(2200);const d=input(text),r=await run(d,{respond:p=>{const spans=p.revisions[0].available_evidence;assert.ok(spans.length>1);for(let i=0;i<spans.length;i++){const {ref,...span}=spans[i];assert.match(ref,/^r0s\d+$/);assert.equal(validateEvidence([{...span,quote_hash:sha256(span.quote)}],d.revisions,{tenantId:'SYN'}).ok,true);assert.ok(Array.from(span.quote).length<=4000);if(i)assert.equal(spans[i-1].end-span.start,200);}return classification(spans.at(-1).ref);}});assert.equal(r.result.ok,true);assert.equal(r.result.data.issues[0].evidence[0].end,Array.from(text).length);});
test('literal phrase candidates are bounded, <=200CP, source-contained and globally <=96',async()=>{const text=Array.from({length:200},(_,i)=>'word'+i).join(' '),others=Array.from({length:4},(_,i)=>({tenant_id:'SYN',message_revision_id:'SYN-r'+(i+2),role:'agent',text}));const r=await run(input(text,others));assert.equal(r.result.ok,true);assert.ok(r.payload.revisions.reduce((n,r)=>n+r.available_values.length,0)<=96);for(const row of r.payload.revisions){assert.ok(row.available_values.length<=32);for(const item of row.available_values){assert.ok(Array.from(item.value).length<=200);assert.ok(row.text.includes(item.value));}assert.equal(row.entity_values_limited,true);} });
test('reference-expanded payload and complete wire body obey limits before reservation',async()=>{for(const options of [{limit:1000},{contextTokens:4000},{ceiling:'4000'}]){const r=await run(input('Cafe\u0301 drill 🔧 motor stopped repeated repeated repeated'),options);assert.ok(['input_too_large','policy_blocked'].includes(r.result.error.code));assert.equal(r.reservations,0);assert.equal(r.calls,0);}});
