import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {fileURLToPath} from 'node:url';import {execFileSync,spawnSync} from 'node:child_process';
import {verifyHumanWorkflow,digest,pitchOracle,handoffOracle,pilotOracle} from './control.mjs';
import {fixture} from '../F04-evaluation/fixtures.mjs';
import {freezeProtocol,evaluate,hashValue} from '../../packages/intelligence/evaluation/evaluate.mjs';
import {evaluatePilot} from '../../packages/intelligence/evaluation/pilot.mjs';
const root=fileURLToPath(new URL('../..',import.meta.url));
const clock=Date.now();
const docNames=['README.md','GUIA-USUARIO.md','GUIA-DESARROLLADOR.md','RUNBOOK.md','ACCESOS-SIN-SECRETOS.md','BACKLOG.md'];
const write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v)+'\n',{mode:0o600});
function act(){return {kind:'human_observation',status:'completed',observer:'SYN-reviewer-not-real-human',evidenceReference:'SYN-schema-test-only',recipient:'SYN-recipient',deliveryChannel:'oauth',followingGuideOnly:true,login:true,import:true,jobTerminal:true,viewsAndEvidence:true,export:true,logoutAndReentry:true,duplicateImportDeduplicated:true,revocationObserved:true,received:true,owner:'SYN-owner',deputy:'SYN-deputy',incidentReference:'SYN-route',completedAt:new Date(clock-86400000).toISOString(),nextReviewAt:new Date(clock+86400000).toISOString(),pending:[]};}
function setup(){
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-human-wrapper-SYN-')),candidate=path.join(tmp,'candidate');fs.mkdirSync(candidate);fs.chmodSync(tmp,0o700);
 const git=(...args)=>execFileSync('git',['-C',candidate,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 const identity=k=>execFileSync('git',['-C',root,'config',k],{encoding:'utf8'}).trim();git('init','-q');git('config','user.name',identity('user.name'));git('config','user.email',identity('user.email'));
 const sources=docNames.map(n=>{const rel='docs/entrega/'+n,p=path.join(candidate,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.copyFileSync(path.join(root,rel),p);return{path:rel,sha256:digest(fs.readFileSync(p))};});git('add','.');git('commit','-qm','SYN isolated wrapper fixture, never published');
 const manifestFile=path.join(tmp,'manifest.json'),reviewFile=path.join(tmp,'review.json'),actFile=path.join(tmp,'act.json');write(actFile,act());
 const backlogFile=path.join(tmp,'backlog.json');write(backlogFile,{sourceSha256:sources.find(x=>x.path.endsWith('/BACKLOG.md')).sha256,rows:Array.from({length:10},(_,i)=>({id:'ENT-'+String(i+1).padStart(2,'0'),status:'closed',evidenceReference:'SYN schema fixture only'}))});
 const manifest={schema:'vexa-human-workflow-v1',task:'F08-05',candidateSha:git('rev-parse','HEAD'),sources,artifacts:[{name:'act',file:actFile,sha256:digest(fs.readFileSync(actFile))},{name:'backlog',file:backlogFile,sha256:digest(fs.readFileSync(backlogFile))}]};
 const review={schema:'vexa-human-workflow-review-v1',task:'F08-05',candidateSha:manifest.candidateSha,operation:'verify_human_workflow',approvalReference:'SYN isolated calibration only',operator:'SYN-operator',reviewer:act().observer,authenticityReviewed:true,authorityCurrent:true,decision:'approved',syntheticEvidenceAcceptedAsHuman:false,backlogScopeReviewed:true,controlSha256:digest(fs.readFileSync(new URL('./control.mjs',import.meta.url))),reviewedAt:new Date(clock-1000).toISOString(),expiresAt:new Date(clock+3600000).toISOString(),humanActSha256:manifest.artifacts[0].sha256};
 const save=()=>{write(manifestFile,manifest);review.manifestSha256=digest(fs.readFileSync(manifestFile));write(reviewFile,review);};save();
 const args=()=>({task:'F08-05',candidate,manifestFile,reviewFile,reviewSha256:digest(fs.readFileSync(reviewFile)),approvalReference:review.approvalReference,now:()=>clock});
 return{tmp,candidate,manifest,review,manifestFile,reviewFile,actFile,save,args,close:()=>fs.rmSync(tmp,{recursive:true,force:true})};
}
test('isolated operator-pinned schema fixture validates integrity, never formal acceptance',()=>{const f=setup();try{const r=verifyHumanWorkflow(f.args());assert.equal(r.status,'operator_reviewed_workflow_verified');assert.equal(r.formalAcceptance,false);assert.equal(r.productionValidated,false);}finally{f.close();}});
const mutations={
 wrong_task:f=>{f.manifest.task='F08-03';f.save();},wrong_revision:f=>{f.manifest.candidateSha='a'.repeat(40);f.save();},expired:f=>{f.review.expiresAt=new Date(clock-1).toISOString();f.save();},unreviewed:f=>{f.review.authenticityReviewed=false;f.save();},revoked:f=>{f.review.authorityCurrent=false;f.save();},pending:f=>{f.review.decision='pending';f.save();},self_review:f=>{f.review.reviewer=f.review.operator;f.save();},stale_control:f=>{f.review.controlSha256='b'.repeat(64);f.save();},missing_source:f=>{f.manifest.sources.pop();f.save();},changed_act:f=>fs.appendFileSync(f.actFile,' '),missing_receipt:f=>{const a=act();a.received=false;write(f.actFile,a);f.manifest.artifacts[0].sha256=digest(fs.readFileSync(f.actFile));f.review.humanActSha256=f.manifest.artifacts[0].sha256;f.save();},synthetic_act:f=>{const a=act();a.kind='synthetic';write(f.actFile,a);f.manifest.artifacts[0].sha256=digest(fs.readFileSync(f.actFile));f.review.humanActSha256=f.manifest.artifacts[0].sha256;f.save();},symlink:f=>{const original=f.actFile+'.original';fs.renameSync(f.actFile,original);fs.symlinkSync(original,f.actFile);},public_input:f=>fs.chmodSync(f.reviewFile,0o644),public_parent:f=>fs.chmodSync(f.tmp,0o755),future_act:f=>{const a=act();a.completedAt=new Date(clock+86400000).toISOString();write(f.actFile,a);f.manifest.artifacts[0].sha256=digest(fs.readFileSync(f.actFile));f.review.humanActSha256=f.manifest.artifacts[0].sha256;f.save();},backlog_unreviewed:f=>{f.review.backlogScopeReviewed=false;f.save();},dirty_candidate:f=>fs.appendFileSync(path.join(f.candidate,'docs/entrega/README.md'),'changed')
};
for(const [name,change]of Object.entries(mutations))test('reject '+name,()=>{const f=setup();try{change(f);assert.throws(()=>verifyHumanWorkflow(f.args()));}finally{f.close();}});
test('missing external inputs and wrong trusted pin are rejected',()=>{assert.throws(()=>verifyHumanWorkflow({task:'F07-05'}),/EXTERNAL_INPUTS_REQUIRED/);const f=setup();try{assert.throws(()=>verifyHumanWorkflow({...f.args(),reviewSha256:'0'.repeat(64)}),/TRUSTED_REVIEW_PIN/);}finally{f.close();}});
test('human rehearsal boundary uses observed clock, not video length',()=>{const a={...act(),startedAt:'2026-09-30T00:00:00Z',finishedAt:'2026-09-30T00:05:00Z',comprehensionConfirmed:true,offlinePlaybackObserved:true,externalRequests:0,fallbackLabelObserved:true,portabilityObserved:true,materialMode:'synthetic_vexa',financial:{currency:'USD',exponent:2,exposureMinor:'30000',refundsMinor:'1500',additive:false,causalSavingClaimed:false}},b={synthetic_fixture:{no_real_customer_data:true},financial:{exposure_minor:'30000',refunds_minor:'1500',additive:false,causal_saving_claimed:false}};pitchOracle(a,b);for(const patch of [{finishedAt:'2026-09-30T00:05:01Z'},{externalRequests:1},{fallbackLabelObserved:false},{portabilityObserved:false},{kind:'synthetic'}])assert.throws(()=>pitchOracle({...a,...patch},b));assert.throws(()=>handoffOracle({...act(),received:false}),/HANDOFF_OBSERVATION/);});
function pilotFixture(){
 const f=fixture({kind:'human_gold'}),protocol=freezeProtocol(f),evaluation=evaluate({protocol,dataset:f.dataset,predictions:f.predictions(protocol)});
 const study={schema_version:'vexa-pilot-study-v1',study_id:'SYN-schema-not-research',kind:'human',window_start:'2026-02-08T00:00:00Z',window_end:'2026-02-10T00:00:00Z',reviewed_at:'2026-02-11T00:00:00Z',reviewer_id:'SYN-reviewer',evidence_ref:'SYN-only',evaluation_binding:{dataset_id:evaluation.dataset_id,protocol_hash:evaluation.input_hashes.protocol,holdout_hash:evaluation.input_hashes.holdout,candidate_hash:hashValue(evaluation.candidate)},eligible_ceo_ids:['SYN-ceo'],eligible_buyer_ids:['SYN-buyer'],consents:['SYN-ceo','SYN-buyer'].map(participant_id=>({participant_id,consented_at:'2026-02-07T00:00:00Z',evidence_ref:'SYN-consent'})),ceo_sessions:[{participant_id:'SYN-ceo',started_at:'2026-02-09T10:00:00Z',completed_at:'2026-02-09T10:04:59Z',comprehension_confirmed:true,evidence_ref:'SYN-clock'}],buyer_responses:[{participant_id:'SYN-buyer',responded_at:'2026-02-09T12:00:00Z',new_insight:true,sponsored_action:{committed:true,sponsor_ref:'SYN-sponsor'},willingness_to_pay:{willing:true,amount_minor:null,currency:null,exponent:null},evidence_ref:'SYN-response'}]};
 const sources=Object.fromEntries(['pilot.mjs','pilot-cli.mjs','evaluate.mjs','cli.mjs'].map(n=>['packages/intelligence/evaluation/'+n,digest(fs.readFileSync(path.join(root,'packages/intelligence/evaluation',n)))])),pilot=evaluatePilot({study,evaluation});
 const evaluationReceipt={schema_version:'vexa-evaluation-receipt-v1',exit_code:0,status:'measured',result_hash:hashValue(evaluation),release_decision:'not_issued',engine_hash:sources['packages/intelligence/evaluation/evaluate.mjs'],cli_hash:sources['packages/intelligence/evaluation/cli.mjs'],exposure:{protocol_hash:evaluation.input_hashes.protocol,holdout_hash:evaluation.input_hashes.holdout,candidate_hash:hashValue(evaluation.candidate),prediction_hash:evaluation.input_hashes.predictions}};
 const pilotReceipt={schema_version:'vexa-pilot-receipt-v1',exit_code:0,result_hash:hashValue(pilot),status:pilot.status,release_decision:'not_issued',engine_hash:sources['packages/intelligence/evaluation/pilot.mjs'],cli_hash:sources['packages/intelligence/evaluation/pilot-cli.mjs'],evaluation_engine_hash:evaluationReceipt.engine_hash,evaluation_cli_hash:evaluationReceipt.cli_hash};const input={study,evaluation,evaluationReceipt,pilot,pilotReceipt};return {input,sources,protocol,dataset:f.dataset,predictions:f.predictions(protocol)};
}
test('pilot recomputes actual evaluator output and preserves human-review requirement',()=>{
 const {input,sources}=pilotFixture(),{study,pilot,evaluationReceipt}=input;pilotOracle(input,sources);
 assert.throws(()=>pilotOracle({...input,study:{...study,kind:'synthetic'}},sources),/HUMAN_DATA_REQUIRED/);assert.throws(()=>pilotOracle({...input,pilot:{...pilot,status:'measured'}},sources),/PILOT_RECOMPUTATION/);assert.throws(()=>pilotOracle({...input,evaluationReceipt:{...evaluationReceipt,result_hash:'a'.repeat(64)}},sources),/EVALUATION_RECEIPT/);
});

function repinAct(f,value){write(f.actFile,value);f.manifest.artifacts.find(x=>x.name==='act').sha256=digest(fs.readFileSync(f.actFile));f.review.humanActSha256=digest(fs.readFileSync(f.actFile));f.save();}
function addArtifact(f,name,file){f.manifest.artifacts.push({name,file,sha256:digest(fs.readFileSync(file))});}
function workflowFixture(task){
 const f=setup();
 const names=task==='F07-05'?['pilot.mjs','pilot-cli.mjs','evaluate.mjs','cli.mjs','PILOT.md'].map(x=>'packages/intelligence/evaluation/'+x):['demo-script.md','demo-backup-manifest.json','demo-backup.webm','portabilidad-crm-resultados.json'].map(x=>'docs/entrega/'+x);
 f.manifest.sources=names.map(rel=>{const p=path.join(f.candidate,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.copyFileSync(path.join(root,rel),p);return {path:rel,sha256:digest(fs.readFileSync(p))};});
 execFileSync('git',['-C',f.candidate,'add','.']);execFileSync('git',['-C',f.candidate,'commit','-qm','SYN isolated workflow schema, not an approval']);
 f.manifest.candidateSha=execFileSync('git',['-C',f.candidate,'rev-parse','HEAD'],{encoding:'utf8'}).trim();f.manifest.task=task;f.review.task=task;f.review.candidateSha=f.manifest.candidateSha;f.manifest.artifacts=f.manifest.artifacts.filter(x=>x.name==='act');
 if(task==='F07-05'){
  const x=pilotFixture(),files={};for(const name of ['protocol','dataset','predictions']){files[name]=path.join(f.tmp,name+'.json');write(files[name],x[name]);addArtifact(f,name,files[name]);}
  const run=(script,args)=>execFileSync(process.execPath,[path.join(root,'packages/intelligence/evaluation',script),...args],{stdio:'pipe'});
  const evaluated=path.join(f.tmp,'evaluated');run('cli.mjs',['evaluate','--protocol',files.protocol,'--dataset',files.dataset,'--predictions',files.predictions,'--out',evaluated,'--ledger',path.join(f.tmp,'ledger.json')]);
  files.study=path.join(f.tmp,'study.json');write(files.study,x.input.study);addArtifact(f,'study',files.study);addArtifact(f,'evaluation',path.join(evaluated,'result.json'));addArtifact(f,'evaluationReceipt',path.join(evaluated,'receipt.json'));
  const piloted=path.join(f.tmp,'piloted');run('pilot-cli.mjs',['--study',files.study,'--evaluation',path.join(evaluated,'result.json'),'--evaluation-receipt',path.join(evaluated,'receipt.json'),'--out',piloted]);
  addArtifact(f,'pilot',path.join(piloted,'result.json'));addArtifact(f,'pilotReceipt',path.join(piloted,'receipt.json'));f.review.acceptanceCriteriaReviewed=true;
  repinAct(f,{...act(),goldCustodyReviewed:true,doubleAnnotationReviewed:true,consentsReviewed:true,representativenessReviewed:true});
 }else repinAct(f,{...act(),startedAt:'2026-09-30T00:00:00Z',finishedAt:'2026-09-30T00:05:00Z',comprehensionConfirmed:true,offlinePlaybackObserved:true,externalRequests:0,fallbackLabelObserved:true,portabilityObserved:true,materialMode:'synthetic_vexa',financial:{currency:'USD',exponent:2,exposureMinor:'30000',refundsMinor:'1500',additive:false,causalSavingClaimed:false}});
 const args=f.args;f.args=()=>({...args(),task});f.save();return f;
}
function cli(f){const a=f.args();return spawnSync(process.execPath,['--test',path.join(root,'tests/acceptance/'+a.task+'.test.mjs')],{encoding:'utf8',env:{PATH:process.env.PATH,VEXA_CANDIDATE:a.candidate,VEXA_HUMAN_WORKFLOW_MANIFEST:a.manifestFile,VEXA_HUMAN_WORKFLOW_REVIEW:a.reviewFile,VEXA_HUMAN_WORKFLOW_REVIEW_SHA256:a.reviewSha256,VEXA_HUMAN_WORKFLOW_APPROVAL_REFERENCE:a.approvalReference},timeout:30000});}
for(const task of ['F07-05','F08-03','F08-05'])test(task+' isolated SYN fixture traverses actual acceptance launcher; not legitimate external approval',()=>{
 const f=task==='F08-05'?setup():workflowFixture(task);try{const result=cli(f);assert.equal(result.status,0,result.stdout+result.stderr);assert.match(result.stdout,/operator_reviewed_workflow_verified/);assert.match(result.stdout,/"formalAcceptance":false/);assert.match(result.stdout,/"productionValidated":false/);
  fs.appendFileSync(f.actFile,' ');const changed=cli(f);assert.equal(changed.status,1);assert.match(changed.stdout,/HUMAN_WORKFLOW_ARTIFACT_CHANGED/);
 }finally{f.close();}
});
for(const task of ['F07-05','F08-03'])test(task+' rejects independently pinned but incomplete human observations',()=>{const f=workflowFixture(task);try{const a=JSON.parse(fs.readFileSync(f.actFile));a[task==='F07-05'?'consentsReviewed':'comprehensionConfirmed']=false;repinAct(f,a);assert.throws(()=>verifyHumanWorkflow(f.args()),task==='F07-05'?/PILOT_HUMAN_AUDIT/:/PITCH_TIMING/);}finally{f.close();}});
test('pilot rejects receipt byte chain mismatch even with operator manifest pin',()=>{const f=workflowFixture('F07-05');try{const p=f.manifest.artifacts.find(x=>x.name==='pilotReceipt'),v=JSON.parse(fs.readFileSync(p.file));v.input_file_hashes.study='a'.repeat(64);write(p.file,v);p.sha256=digest(fs.readFileSync(p.file));f.save();assert.throws(()=>verifyHumanWorkflow(f.args()),/PILOT_INPUT_BYTES/);}finally{f.close();}});
test('pilot study review must precede final human act',()=>{const f=workflowFixture('F07-05');try{const a=JSON.parse(fs.readFileSync(f.actFile));a.completedAt='2026-02-10T23:00:00Z';repinAct(f,a);assert.throws(()=>verifyHumanWorkflow(f.args()),/PILOT_REVIEW_ORDER/);}finally{f.close();}});
test('backlog open rows require complete dated pending register',()=>{const f=setup();try{const pin=f.manifest.artifacts.find(x=>x.name==='backlog'),b=JSON.parse(fs.readFileSync(pin.file));b.rows[0].status='open';write(pin.file,b);pin.sha256=digest(fs.readFileSync(pin.file));f.save();assert.throws(()=>verifyHumanWorkflow(f.args()),/BACKLOG_PENDING/);const a=act();a.pending=[{id:'ENT-01',owner:'SYN-owner',acceptance:'SYN observable acceptance',reproduction:'SYN reproduction',severity:'P1',dueAt:'2026-10-03T00:00:00Z'}];repinAct(f,a);assert.equal(verifyHumanWorkflow(f.args()).status,'operator_reviewed_workflow_verified');for(const patch of [{dueAt:'tomorrow'},{dueAt:'2026-02-30T00:00:00Z'},{severity:'unknown'},{reproduction:''}]){repinAct(f,{...a,pending:[{...a.pending[0],...patch}]});assert.throws(()=>verifyHumanWorkflow(f.args()),/PENDING_REGISTER/);}}finally{f.close();}});
test('private evidence through a custom ancestor symlink is rejected',()=>{const f=setup(),alias=f.tmp+'-alias';try{fs.symlinkSync(f.tmp,alias);assert.throws(()=>verifyHumanWorkflow({...f.args(),manifestFile:path.join(alias,'manifest.json')}),/PRIVATE_INPUT/);}finally{fs.rmSync(alias,{force:true});f.close();}});
