const assert=require('node:assert/strict');
const {chromium}=require('/app/node_modules/playwright-core');
(async()=>{
 let input='';for await(const c of process.stdin)input+=c;
 const {base,cookie,connection,xlsx}=JSON.parse(input);
 const browser=await chromium.launch({headless:true,executablePath:'/ms-playwright/chromium-1226/chrome-linux/chrome',args:['--no-sandbox']});
 try{
  const context=await browser.newContext({acceptDownloads:true});
  await context.addCookies(cookie.split('; ').map(x=>({name:x.slice(0,x.indexOf('=')),value:x.slice(x.indexOf('=')+1),url:base})));
  const page=await context.newPage();
  page.on('console',m=>{if(m.type()==='error')console.log('BROWSER_CONSOLE',m.text().replace(/https?:[^\s'"]+/g,u=>{try{const x=new URL(u);return x.origin+x.pathname}catch{return '[url]'}}));});
  page.on('response',r=>{if(r.status()>=400){const u=new URL(r.url());console.log('BROWSER_HTTP_ERROR',r.status(),u.origin+u.pathname);}});
  page.on('pageerror',()=>console.log('BROWSER_PAGE_ERROR'));
  page.on('requestfailed',r=>{if(r.failure()?.errorText==='net::ERR_ABORTED')return;const u=new URL(r.url());console.log('NETWORK_FAILURE',r.method(),u.origin+u.pathname,r.failure()?.errorText);});
  await page.goto(base+'/imports');await page.getByRole('heading',{name:'Importaciones CSV / Excel'}).waitFor();
  await page.getByRole('button',{name:'Más reservas',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);
  assert.ok(await page.locator('li button').count()>50);
  await page.getByRole('button',{name:'Más conexiones',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);
  assert.equal(await page.getByLabel('Conexión',{exact:false}).locator('option').count(),103);
  await page.getByLabel('Conexión',{exact:false}).selectOption(connection);
  const file={name:'SYNTHETIC.csv',mimeType:'text/csv',buffer:Buffer.from('id,text,date,amount\na,<b>SYNTHETIC</b>,01/02/2026,10.01\nb,SYNTHETIC,31/02/2026,1\n')};
  await page.getByLabel('Archivo',{exact:true}).setInputFiles(file);
  const upload=async()=>{await page.getByRole('button',{name:'Reservar y subir archivo'}).click();await page.waitForFunction(()=>document.querySelector('[role=alert]:not(#__next-route-announcer__)')||(!document.querySelector('fieldset').disabled&&document.body.textContent.includes('Configuración de columnas')));const alert=page.locator('[role=alert]:not(#__next-route-announcer__)');if(await alert.count())throw Error('UPLOAD_UI: '+await alert.innerText());};
  await upload();assert.equal(await page.getByLabel('Conexión',{exact:false}).inputValue(),connection,'selected second-page connection survives refresh');
  const state=()=>page.getByText(/^Estado: /).innerText();const original=await state();
  await upload();assert.equal(await state(),original,'same file retry preserves reservation');
  const confirm=page.getByRole('button',{name:'Confirmar envío a cola'});
  assert.equal(await confirm.isDisabled(),true);
  const configure=async()=>{for(const name of ['id','text','date','amount'])await page.getByLabel('Columna '+name,{exact:false}).selectOption(name);await page.getByLabel('Zona horaria IANA').fill('America/New_York');await page.getByLabel('Formato de fecha').selectOption('dmy');await page.getByLabel('Moneda explícita').selectOption('USD');};
  await configure();await page.getByRole('button',{name:'Validar y previsualizar'}).click();await page.getByRole('heading',{name:'Validación: 2 filas'}).waitFor();
  assert.equal(await confirm.isDisabled(),true);assert.equal(await page.locator('td b').count(),0);assert.ok((await page.locator('table').innerText()).includes('1001 USD'));
  await page.getByRole('button',{name:'Guardar y confirmar mapping'}).click();await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).waitFor();
  const downloadEvent=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).click();const download=await downloadEvent;const stream=await download.createReadStream();let csv='';for await(const chunk of stream)csv+=chunk;assert.match(csv,/INVALID_CALENDAR/);assert.ok(!csv.includes('SYNTHETIC'));
  const detailRoute=(await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).getAttribute('href')).replace('/errors.csv','');
  const current=(await (await context.request.get(base+detailRoute)).json()).data;
  const competing=await context.request.post(base+detailRoute+'/mapping',{headers:{Origin:base},data:{mapping:{...current.mapping,currency:'EUR'},expected_version:current.import.mapping_version}});assert.equal(competing.status(),200);
  await confirm.click();await page.getByRole('alert').filter({hasText:'upload_capability_invalid'}).waitFor();assert.equal(await confirm.isDisabled(),true,'server stale capability clears approval');
  await page.getByLabel('Moneda explícita').selectOption('GBP');assert.equal(await confirm.isDisabled(),true);
  await page.getByRole('button',{name:'Validar y previsualizar'}).click();await page.getByRole('heading',{name:'Validación: 2 filas'}).waitFor();await page.getByRole('button',{name:'Guardar y confirmar mapping'}).click();await page.getByRole('alert').filter({hasText:'mapping_version_conflict'}).waitFor();assert.equal(await confirm.isDisabled(),true);
  await page.getByRole('button',{name:'Recargar esta reserva'}).click();await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);assert.equal(await page.getByLabel('Moneda explícita').inputValue(),'EUR');
  await confirm.click();await page.getByText('Estado: queued',{exact:false}).waitFor();
  await upload();assert.ok((await state()).includes('queued'));
  await page.reload();await page.getByRole('heading',{name:'Importaciones CSV / Excel'}).waitFor();await page.getByRole('button',{name:/ · queued$/}).first().click();await page.getByText('Estado: queued',{exact:false}).waitFor();
  console.log('PASS browser pagination/upload/retry/preview/plain-text/save/export/CAS conflict/change disables confirm/refresh/confirm/reload');
  if(await page.getByRole('button',{name:'Más conexiones',exact:true}).count()){await page.getByRole('button',{name:'Más conexiones',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);}
  await page.getByLabel('Conexión',{exact:false}).selectOption(connection);
  await page.getByLabel('Archivo',{exact:true}).setInputFiles({name:'SYNTHETIC.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(xlsx,'base64')});
  await upload();const sheet=page.getByLabel('Hoja Excel (obligatoria si hay varias)',{exact:false});assert.deepEqual(await sheet.locator('option').allTextContents(),['Selecciona hoja','España 😀','Other']);
  await sheet.selectOption('Other');await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);await configure();await page.getByRole('button',{name:'Validar y previsualizar'}).click();await page.getByRole('heading',{name:'Validación: 1 filas'}).waitFor();assert.ok((await page.locator('table').innerText()).includes('1001 USD'));
  await page.getByRole('button',{name:'Guardar y confirmar mapping'}).click();await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).waitFor();await sheet.selectOption('España 😀');await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);assert.equal(await confirm.isDisabled(),true);assert.equal(await sheet.inputValue(),'España 😀');
  console.log('PASS browser real XLSX multisheet accessible selector/headers/preview/save/change requires approval');
  await page.getByRole('button',{name:'Recargar esta reserva'}).click();await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).waitFor();
  const xlsxRoute=(await page.getByRole('link',{name:'Descargar errores CSV del mapping guardado'}).getAttribute('href')).replace('/errors.csv','');
  console.log('TEST_EXPIRE '+xlsxRoute.split('/').at(-1));
  let expired=false;for(let i=0;i<50;i++){const d=(await (await context.request.get(base+xlsxRoute)).json()).data;if(new Date(d.import.expires_at)<=new Date()){expired=true;break;}await new Promise(r=>setTimeout(r,100));}assert.equal(expired,true,'real database expiry applied');
  await page.getByRole('button',{name:'Recargar esta reserva'}).click();await page.waitForFunction(()=>!document.querySelector('fieldset').disabled);assert.equal(await confirm.isDisabled(),true);
  await page.getByRole('button',{name:'Reservar y subir archivo'}).click();await page.getByRole('alert').filter({hasText:'reservation_expired'}).waitFor();
  await upload();assert.equal(await confirm.isDisabled(),true);assert.deepEqual(await sheet.locator('option').allTextContents(),['Selecciona hoja','España 😀','Other']);
  console.log('PASS browser expired mapping disables confirm/retry signals expiry/explicit same-file renewal uploads real bytes');
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
