import {createEvidenceRepository} from '../evidence-repository.mjs';
import {hashValue,freezeProtocol,exportDevelopment} from '../evaluation/evaluate.mjs';
const uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(x),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
class LearningError extends Error{constructor(code,status=400){super(code);this.code=code;this.status=status;}}
const check=(v,code='evaluation_input_invalid',status=400)=>{if(!v)throw new LearningError(code,status);},strict=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k));
const one=async(s,q,v=[])=>(await s.query(q,v)).rows[0];
const pseudo=(tenant,kind,id)=>hashValue({tenant,kind,id});
// Missing timestamps are unknown, never an implicit Unix epoch.
const timestamp=value=>value instanceof Date?value.getTime():typeof value==='string'&&value.trim()?Date.parse(value):NaN;
export function createLearningRepository({database,clock=Date.now}){
 const tx=async(action,fn)=>{let own;try{return await database.transaction(action,async s=>{try{check(s.role==='owner','evaluation_owner_required',403);const value=await fn(s);check((await one(s,"SELECT public.vexa_member($1,array['owner']) AS ok",[s.tenantId])).ok,'evaluation_owner_required',403);return value;}catch(e){if(e instanceof LearningError)own=e;throw e;}});}catch(e){throw own??e;}};
 const cohort=async(s,id)=>{check(uuid(id));const c=await one(s,'SELECT * FROM public.learning_cohorts WHERE tenant_id=$1 AND id=$2',[s.tenantId,id]);check(c,'evaluation_not_found',404);await s.query('SELECT pg_advisory_xact_lock_shared(hashtextextended($1,0))',[s.tenantId+':'+c.connection_id]);check((await one(s,"SELECT id FROM public.connections WHERE tenant_id=$1 AND id=$2 AND status='active'",[s.tenantId,c.connection_id])),'evaluation_connection_unavailable',409);return c;};
 const summary=c=>({id:c.id,connectionId:c.connection_id,windowStart:c.window_start,cutoff:c.cutoff,taxonomyHash:c.taxonomy_hash,taxonomyVersion:'sha256:'+c.taxonomy_hash,taxonomy:c.taxonomy,count:c.item_count,createdAt:c.created_at});
 async function inspect(s,c,item){
  const base={ordinal:item.ordinal,runId:item.run_id,conversationId:item.conversation_id,inputHash:item.input_hash,resultHash:item.result_hash,manifestHash:item.manifest_hash,taxonomyHash:c.taxonomy_hash};
  const r=await one(s,'SELECT id,input_hash,updated_at,created_at,prompt_hash,schema_hash,provenance,public.learning_hash(provenance->\'result\') AS result_hash,public.learning_hash(provenance->\'input_manifest\') AS manifest_hash,public.learning_hash(provenance->\'taxonomy\') AS taxonomy_hash FROM public.extraction_runs WHERE tenant_id=$1 AND id=$2',[s.tenantId,item.run_id]);
  if(!r||r.input_hash!==item.input_hash||r.result_hash!==item.result_hash||r.manifest_hash!==item.manifest_hash||r.taxonomy_hash!==c.taxonomy_hash)return {...base,eligible:false,reason:'result_changed_or_erased'};
  let evidence;try{evidence=await createEvidenceRepository({database:{transaction:async(_,fn)=>fn(s)}}).get(item.run_id);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')return {...base,eligible:false,reason:'source_unavailable'};throw e;}
  const binding=await one(s,`SELECT v.customer_id,v.created_at AS conversation_available,u.created_at AS customer_available,u.connection_id,u.external_id,h.state FROM public.conversations v LEFT JOIN public.customers u ON u.tenant_id=v.tenant_id AND u.id=v.customer_id LEFT JOIN public.source_heads h ON h.tenant_id=u.tenant_id AND h.id=u.id WHERE v.tenant_id=$1 AND v.id=$2 AND v.connection_id=$3`,[s.tenantId,item.conversation_id,c.connection_id]);
  let reason=null;if(!binding?.customer_id)reason='customer_unknown';else if(binding.customer_id!==item.customer_id||binding.connection_id!==c.connection_id||!['unique','selected'].includes(binding.state)||(await one(s,'SELECT public.retention_source_deleted($1,$2,\'customer\',$3) AS deleted',[s.tenantId,c.connection_id,binding.external_id])).deleted)reason='customer_binding_unavailable';
  const manifest=r.provenance.input_manifest,revisions=(await s.query(`SELECT v.id,v.hash,v.redacted_text,v.created_at,original.id AS original_id,original.created_at AS original_available,original.occurred_at FROM public.message_revisions v JOIN public.message_revisions original ON original.tenant_id=v.tenant_id AND original.id::text=v.provenance->>'original_revision_id' AND original.message_id=v.message_id JOIN public.messages m ON m.tenant_id=v.tenant_id AND m.id=v.message_id WHERE v.tenant_id=$1 AND v.id=ANY($2::uuid[]) ORDER BY v.id`,[s.tenantId,manifest.map(m=>m.message_revision_id)])).rows;
  const times=[timestamp(r.updated_at),timestamp(binding?.conversation_available),...(binding?.customer_available?[timestamp(binding.customer_available)]:[]),...revisions.flatMap(v=>[timestamp(v.created_at),timestamp(v.original_available),timestamp(v.occurred_at)])],eventTime=Math.max(...revisions.map(v=>timestamp(v.occurred_at))),availableAt=Math.max(...times);
  if(revisions.length!==manifest.length||revisions.some(v=>!manifest.some(m=>m.message_revision_id===v.id&&m.original_revision_id===v.original_id&&m.hash===v.hash))||!Number.isFinite(eventTime)||!Number.isFinite(availableAt)||times.some(t=>!Number.isFinite(t)||t>=timestamp(c.cutoff)))reason='temporal_cutoff_excluded';
  const feedback=await one(s,'SELECT version,actor_id,created_at,verdict,labels,topic_correct,evidence_sufficient,decision_possible FROM public.learning_feedback WHERE tenant_id=$1 AND cohort_id=$2 AND ordinal=$3 ORDER BY version DESC LIMIT 1',[s.tenantId,c.id,item.ordinal]);
  return {...base,eligible:!reason,reason,state:evidence.state,status:evidence.status,labels:[...new Set(evidence.issues.map(x=>x.category))].sort(),sentiment:evidence.sentiment,intent:evidence.intent,urgency:evidence.urgency,abstention:evidence.abstention?.reason??null,promptHash:r.prompt_hash,schemaHash:r.schema_hash,policyHash:r.provenance.policy_hash,revisionCount:manifest.length,feedback:feedback?{version:feedback.version,actor:pseudo(s.tenantId,'reviewer',feedback.actor_id),createdAt:feedback.created_at,verdict:feedback.verdict,labels:feedback.labels,topicCorrect:feedback.topic_correct,evidenceSufficient:feedback.evidence_sufficient,decisionPossible:feedback.decision_possible}:null,_revisions:revisions,_customer:binding?.customer_id,_eventTime:eventTime,_availableAt:availableAt};
 }
 const publicItem=x=>Object.fromEntries(Object.entries(x).filter(([k])=>!k.startsWith('_')));
 return {
 async state(cursor=null){check(cursor===null||uuid(cursor));return tx('read',async s=>{if(cursor)check(await one(s,'SELECT id FROM public.learning_cohorts WHERE tenant_id=$1 AND id=$2',[s.tenantId,cursor]));const rows=(await s.query('SELECT * FROM public.learning_cohorts WHERE tenant_id=$1 AND ($2::uuid IS NULL OR id>$2) ORDER BY id LIMIT 26',[s.tenantId,cursor])).rows;return {connections:(await s.query("SELECT id,source FROM public.connections WHERE tenant_id=$1 AND status='active' ORDER BY id",[s.tenantId])).rows,cohorts:rows.slice(0,25).map(summary),cohortNextCursor:rows.length>25?rows[24].id:null,limits:{cases:500,page:25,exportBytes:2000000},promotionEnabled:false};});},
 async taxonomies(connectionId){check(uuid(connectionId));return tx('read',async s=>{check(await one(s,"SELECT id FROM public.connections WHERE tenant_id=$1 AND id=$2 AND status='active'",[s.tenantId,connectionId]),'evaluation_not_found',404);const items=(await s.query(`SELECT public.learning_hash(r.provenance->'taxonomy') AS hash,r.provenance->'taxonomy' AS labels,count(*)::integer AS runs FROM public.extraction_runs r JOIN public.conversations c ON c.tenant_id=r.tenant_id AND c.id=r.conversation_id JOIN public.connections n ON n.tenant_id=c.tenant_id AND n.id=c.connection_id WHERE r.tenant_id=$1 AND c.connection_id=$2 AND n.status='active' AND r.status IN ('succeeded','abstained') GROUP BY r.provenance->'taxonomy' ORDER BY public.learning_hash(r.provenance->'taxonomy') LIMIT 101`,[s.tenantId,connectionId])).rows;check(items.length<=100,'evaluation_taxonomy_limit',413);return{items};});},
 async create(input){check(strict(input,['connectionId','windowStart','cutoff','taxonomyHash','requestId'])&&uuid(input.connectionId)&&uuid(input.requestId)&&hash(input.taxonomyHash)&&typeof input.windowStart==='string'&&typeof input.cutoff==='string'&&Number.isFinite(Date.parse(input.windowStart))&&Date.parse(input.windowStart)<Date.parse(input.cutoff)&&Date.parse(input.cutoff)<=clock());return tx('configure',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':learning:'+input.requestId]);const prior=await one(s,'SELECT * FROM public.learning_cohorts WHERE tenant_id=$1 AND id=$2',[s.tenantId,input.requestId]);if(prior){check(prior.actor_id===s.userId&&prior.connection_id===input.connectionId&&prior.taxonomy_hash===input.taxonomyHash&&new Date(prior.window_start).getTime()===Date.parse(input.windowStart)&&new Date(prior.cutoff).getTime()===Date.parse(input.cutoff),'evaluation_request_conflict',409);return summary(prior);}await s.query('SELECT pg_advisory_xact_lock_shared(hashtextextended($1,0))',[s.tenantId+':'+input.connectionId]);const rows=(await s.query(`SELECT DISTINCT ON(r.conversation_id) r.id,r.conversation_id,c.customer_id,r.input_hash,public.learning_hash(r.provenance->'result') AS result_hash,public.learning_hash(r.provenance->'input_manifest') AS manifest_hash,r.provenance->'taxonomy' AS taxonomy FROM public.extraction_runs r JOIN public.conversations c ON c.tenant_id=r.tenant_id AND c.id=r.conversation_id JOIN public.connections n ON n.tenant_id=c.tenant_id AND n.id=c.connection_id WHERE r.tenant_id=$1 AND c.connection_id=$2 AND n.status='active' AND r.status IN ('succeeded','abstained') AND r.updated_at>=$3::timestamptz AND r.updated_at<$4::timestamptz AND public.learning_hash(r.provenance->'taxonomy')=$5 ORDER BY r.conversation_id,r.updated_at DESC,r.id LIMIT 501`,[s.tenantId,input.connectionId,input.windowStart,input.cutoff,input.taxonomyHash])).rows;check(rows.length,'evaluation_cohort_empty',409);check(rows.length<=500,'evaluation_cohort_limit',413);const taxonomy=rows[0].taxonomy;check(Array.isArray(taxonomy)&&taxonomy.length&&taxonomy.every(v=>typeof v==='string'&&v.length<=80),'evaluation_taxonomy_invalid',409);const c=await one(s,'INSERT INTO public.learning_cohorts(id,tenant_id,actor_id,connection_id,window_start,cutoff,taxonomy_hash,taxonomy,item_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[input.requestId,s.tenantId,s.userId,input.connectionId,input.windowStart,input.cutoff,input.taxonomyHash,JSON.stringify(taxonomy),rows.length]);for(let i=0;i<rows.length;i++){const r=rows[i];await s.query('INSERT INTO public.learning_items(tenant_id,cohort_id,ordinal,run_id,conversation_id,customer_id,input_hash,result_hash,manifest_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[s.tenantId,c.id,i+1,r.id,r.conversation_id,r.customer_id,r.input_hash,r.result_hash,r.manifest_hash]);}return summary(c);});},
 async page({cohortId,cursor=0}){check(uuid(cohortId)&&Number.isInteger(cursor)&&cursor>=0&&cursor<=500);return tx('read',async s=>{const c=await cohort(s,cohortId);check(cursor===0||!!await one(s,'SELECT ordinal FROM public.learning_items WHERE tenant_id=$1 AND cohort_id=$2 AND ordinal=$3',[s.tenantId,c.id,cursor]));const rows=(await s.query('SELECT * FROM public.learning_items WHERE tenant_id=$1 AND cohort_id=$2 AND ordinal>$3 ORDER BY ordinal LIMIT 26',[s.tenantId,c.id,cursor])).rows,items=[];for(const row of rows.slice(0,25))items.push(publicItem(await inspect(s,c,row)));return{cohort:summary(c),items,nextCursor:rows.length>25?items.at(-1).ordinal:null,hasMore:rows.length>25};});},
 async feedback(input){check(strict(input,['cohortId','ordinal','expectedVersion','resultHash','manifestHash','taxonomyHash','verdict','labels','topicCorrect','evidenceSufficient','decisionPossible','reviewConfirmed'])&&input.reviewConfirmed===true&&uuid(input.cohortId)&&Number.isInteger(input.ordinal)&&Number.isInteger(input.expectedVersion)&&input.expectedVersion>=0&&hash(input.resultHash)&&hash(input.manifestHash)&&hash(input.taxonomyHash)&&['correct','correction','abstain'].includes(input.verdict)&&Array.isArray(input.labels)&&input.labels.length<=100&&new Set(input.labels).size===input.labels.length&&['topicCorrect','evidenceSufficient','decisionPossible'].every(k=>typeof input[k]==='boolean'));return tx('configure',async s=>{const c=await cohort(s,input.cohortId);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':learning-feedback:'+c.id+':'+input.ordinal]);const item=await one(s,'SELECT * FROM public.learning_items WHERE tenant_id=$1 AND cohort_id=$2 AND ordinal=$3',[s.tenantId,c.id,input.ordinal]);check(item,'evaluation_not_found',404);check(item.result_hash===input.resultHash&&item.manifest_hash===input.manifestHash&&c.taxonomy_hash===input.taxonomyHash,'evaluation_binding_changed',409);const inspected=await inspect(s,c,item);check(!['source_unavailable','result_changed_or_erased','temporal_cutoff_excluded'].includes(inspected.reason),'evaluation_source_unavailable',409);check(input.labels.every(v=>c.taxonomy.includes(v))&&(input.verdict!=='abstain'||input.labels.length===0));if(input.verdict==='correct')check(hashValue([...input.labels].sort())===hashValue(inspected.labels),'evaluation_correct_labels_mismatch',409);const version=inspected.feedback?.version??0;check(version===input.expectedVersion,'evaluation_feedback_conflict',409);await s.query('INSERT INTO public.learning_feedback(tenant_id,cohort_id,ordinal,version,actor_id,verdict,labels,topic_correct,evidence_sufficient,decision_possible) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[s.tenantId,c.id,item.ordinal,version+1,s.userId,input.verdict,JSON.stringify(input.labels),input.topicCorrect,input.evidenceSufficient,input.decisionPossible]);return{version:version+1};});},
 async exportDevelopment(cohortId){return tx('read',async s=>{const c=await cohort(s,cohortId),provenance=[],rows=(await s.query('SELECT * FROM public.learning_items WHERE tenant_id=$1 AND cohort_id=$2 ORDER BY ordinal',[s.tenantId,c.id])).rows,cases=[],excluded=[];let bytes=0;for(const row of rows){const x=await inspect(s,c,row);if(!x.eligible){excluded.push({ordinal:x.ordinal,runId:x.runId,reason:x.reason});continue;}const clientId=pseudo(s.tenantId,'customer',x._customer),messages=x._revisions.map(r=>({id:pseudo(s.tenantId,'revision',r.id),client_id:clientId,text:r.redacted_text,hash:r.hash,authorized:true}));bytes+=Buffer.byteLength(JSON.stringify(messages));check(bytes<=2000000,'evaluation_export_limit',413);const annotations=x.feedback?[{annotator_id:x.feedback.actor,annotated_at:new Date(x.feedback.createdAt).toISOString(),kind:'human',blind:false,labels:x.feedback.labels}]:[];provenance.push({caseId:pseudo(s.tenantId,'run',x.runId),runId:x.runId,inputHash:x.inputHash,resultHash:x.resultHash,manifestHash:x.manifestHash,taxonomyHash:x.taxonomyHash,policyHash:x.policyHash,promptHash:x.promptHash,schemaHash:x.schemaHash,feedbackVersion:x.feedback?.version??null});cases.push({id:pseudo(s.tenantId,'run',x.runId),client_id:clientId,group_id:pseudo(s.tenantId,'conversation',x.conversationId),split:'dev',event_time:new Date(x._eventTime).toISOString(),available_at:new Date(x._availableAt).toISOString(),messages,content_hash:hashValue(messages),annotations});}const dataset={dataset_id:'historical-development:'+c.id,kind:'silver_assisted',cases},spec={protocol_id:'historical-development:'+c.id,taxonomy:{version:'sha256:'+c.taxonomy_hash,labels:c.taxonomy},cutoff:new Date(c.cutoff).toISOString()},protocol=freezeProtocol({dataset,spec,now:new Date(clock()).toISOString()}),development=exportDevelopment({protocol,dataset});return{dataset,spec,protocol,development,provenance,excluded,counts:{selected:rows.length,exported:cases.length,excluded:excluded.length},notice:'Development only. Owner feedback is not independent human gold. No holdout, inference or promotion.',promotionEnabled:false};});}
 };
}
