import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';import {fork,execFile,spawnSync} from 'node:child_process';import {once} from 'node:events';import {promisify} from 'node:util';
import {generateDataset} from './generator.mjs';import {setup,basePort} from './harness.mjs';
const exec=promisify(execFile),hash=bytes=>createHash('sha256').update(bytes).digest('hex'),q=v=>"'"+String(v).replaceAll("'","''")+"'";
const candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'VEXA_CANDIDATE_REQUIRED');
const sizes=(process.env.VEXA_LOAD_SCALES??'10000').split(',').map(Number);assert.ok(sizes.every(x=>[10000,50000,150000].includes(x))&&sizes.every((x,i)=>!i||x>sizes[i-1]),'LOAD_SCALE_ORDER');
let priorEvidence=null;
if(sizes[0]!==10000){const previous=process.env.VEXA_LOAD_PREVIOUS_REPORT;assert.ok(previous,'SUCCESSFUL_PREVIOUS_SCALE_REQUIRED');const bytes=fs.readFileSync(previous),prior=JSON.parse(bytes),required=sizes[0]===50000?10000:50000;assert.equal(prior.candidate,candidate,'PRIOR_CANDIDATE_MUST_MATCH');assert.equal(prior.status,'measured');const result=prior.scales.find(x=>x.rows===required);assert.equal(result?.status,'pass','PREVIOUS_SCALE_MUST_PASS');assert.equal(result.observed.total,required);assert.equal(result.observed.pending,0);assert.equal(result.observed.accepted+result.observed.rejected+result.observed.duplicates,required);priorEvidence={path:previous,sha256:hash(bytes),validatedScale:required};}

const dependencyBytes=fs.readFileSync(new URL('./dependencies.json',import.meta.url)),dependencyManifest=JSON.parse(dependencyBytes);
const sourceRoots=['apps','packages','supabase/migrations','tests/acceptance/support','tests/acceptance/scaffold-copy.mjs','package.json','package-lock.json'];
const benchmarkFiles=['README.md','dependencies.json','generator.mjs','harness.mjs','run.mjs','summarize.mjs','tests/escalation.test.mjs','tests/generator.test.mjs','worker.mjs'];
const verifyDependencies=()=>{
 const actual=[],benchmark=[];
 const walk=relative=>{const file=path.join(candidate,relative),stat=fs.lstatSync(file);assert.ok(!stat.isSymbolicLink(),'LOAD_SOURCE_SYMLINK:'+relative);if(stat.isDirectory()){for(const name of fs.readdirSync(file).sort())walk(relative+'/'+name);}else{assert.ok(stat.isFile(),'LOAD_SOURCE_TYPE:'+relative);if(relative.startsWith('packages/jobs/load/'))benchmark.push(relative.slice('packages/jobs/load/'.length));else actual.push(relative);}};
 for(const root of sourceRoots)walk(root);
 assert.deepEqual(actual.sort(),dependencyManifest.files.map(f=>f.path).sort(),'LOAD_SOURCE_INVENTORY_CHANGED');assert.deepEqual(benchmark.sort(),benchmarkFiles.slice().sort(),'LOAD_BENCHMARK_INVENTORY_CHANGED');
 for(const file of dependencyManifest.files)assert.equal(hash(fs.readFileSync(path.join(candidate,file.path))),file.sha256,'LOAD_SOURCE_CHANGED:'+file.path);
};verifyDependencies();
if(priorEvidence){const prior=JSON.parse(fs.readFileSync(priorEvidence.path));assert.equal(prior.dependencyManifestSha256,hash(dependencyBytes),'PRIOR_SOURCE_MANIFEST_MUST_MATCH');for(const name of ['generator.mjs','harness.mjs','run.mjs','worker.mjs'])assert.equal(prior.benchmarkImplementation?.[name],hash(fs.readFileSync(new URL('./'+name,import.meta.url))),'PRIOR_BENCHMARK_MUST_MATCH');}
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-load308-'));fs.chmodSync(evidence,0o700);console.log('LOAD308_RUNNING:'+evidence);
const report={schema:'vexa-load-result-v1',synthetic:true,status:'running',candidate,baselineSha:dependencyManifest.baselineSha,proposalDependencies:false,composition:dependencyManifest.composition,dependencyManifestSha256:hash(dependencyBytes),benchmarkImplementation:Object.fromEntries(['generator.mjs','harness.mjs','run.mjs','worker.mjs','dependencies.json'].map(name=>[name,hash(fs.readFileSync(new URL('./'+name,import.meta.url)))])),priorEvidence,startedAt:new Date().toISOString(),hardware:{platform:process.platform,arch:process.arch,cpus:os.cpus().length,cpuModel:os.cpus()[0]?.model,totalMemoryBytes:os.totalmem(),freeMemoryAtStartBytes:os.freemem(),osRelease:os.release(),loadAverageAtStart:os.loadavg(),environment:'Shared developer host; other local workloads are not controlled'},versions:{node:process.version},cost:{measured:false,total:null,currency:null,reason:'Local resources; no monetary measurement and no external paid requests'},slo:{approved:false,budget:null,comparison:null,existingProposedObjective:{source:'docs/blueprint/calidad/02-conjunto-dorado-evaluacion.md#8',rows:1000,tenants:2,jobs:2,p95Ms:600000,scope:'upload through extraction validation aggregation and usable snapshot',testedHere:false},meaning:'No approved SLO for10K/50K/150K ingestion-only; measurements do not validate proposed full pipeline objective or commercial capacity'},scales:[],samples:[],processes:[],pending:['Task-level acceptance pending','No production/cloud/provider capacity measured']};
let h,sampling,busy=false;const workers=new Set();
const save=()=>fs.writeFileSync(path.join(evidence,'report.json'),JSON.stringify(report,null,2));
async function worker(){const child=fork(new URL('./worker.mjs',import.meta.url),[],{execPath:process.execPath,execArgv:[],env:{...h.common,VEXA_WORKER_EMAIL:h.bot.email,VEXA_WORKER_PASSWORD:h.bot.password,VEXA_WORKER_USER_ID:h.bot.id,VEXA_WORKER_TENANT:h.A.tenant},stdio:['ignore','ignore','pipe','ipc']});workers.add(child);let stderr='';child.stderr.on('data',x=>stderr+=x);const pending=new Map();const record={pid:child.pid,startedAt:new Date().toISOString(),chunks:[],maxRssKiB:0};report.processes.push(record);
 child.on('message',m=>{if(m.kind==='chunk'){record.chunks.push(m);record.maxRssKiB=Math.max(record.maxRssKiB,m.maxRssKiB);return;}if(m.ready){record.node=m.node;return;}const callback=pending.get(m.id);if(callback){pending.delete(m.id);callback(m);}});
 await Promise.race([new Promise((resolve,reject)=>{child.once('message',m=>m.ready?resolve():reject(Error('LOAD_WORKER_NOT_READY')));child.once('error',reject);child.once('exit',code=>reject(Error('LOAD_WORKER_START_EXIT:'+code)));}),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(Error('LOAD_WORKER_START_TIMEOUT')),15000);timer.unref();})]);
 return {child,record,async call(op){const id=randomUUID();let timer;try{const value=await Promise.race([new Promise(resolve=>{pending.set(id,resolve);child.send({id,op});}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('LOAD_WORKER_CALL_TIMEOUT:'+op)),960000);})]);assert.equal(value.ok,true,JSON.stringify(value.error));record.maxRssKiB=Math.max(record.maxRssKiB,value.maxRssKiB??0);return value;}finally{clearTimeout(timer);pending.delete(id);}},async close(){if(child.exitCode===null&&child.signalCode===null){const ended=once(child,'exit');child.kill('SIGKILL');await ended;}workers.delete(child);record.endedAt=new Date().toISOString();record.exitCode=child.exitCode;record.signal=child.signalCode;record.stderr=stderr;}};
}
const percentile=(values,p)=>values.length?values.slice().sort((a,b)=>a-b)[Math.ceil(values.length*p)-1]:null;
try{
 h=await setup(candidate,evidence);report.versions.postgres=h.sql('SHOW server_version');report.hardware.docker=JSON.parse(spawnSync('docker',['info','--format','{\"memoryBytes\":{{.MemTotal}},\"cpus\":{{.NCPU}},\"os\":{{json .OperatingSystem}},\"arch\":{{json .Architecture}}}'],{encoding:'utf8'}).stdout);report.versions.docker=spawnSync('docker',['version','--format','{{.Server.Version}}'],{encoding:'utf8'}).stdout.trim();
 const resources=fs.readFileSync(path.join(evidence,'resources.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse),containers=resources.filter(x=>x.kind==='container').map(x=>x.name);
 const sample=async()=>{if(busy)return;busy=true;try{const {stdout}=await exec('docker',['stats','--no-stream','--format','{{json .}}',...containers],{timeout:10000});report.samples.push({at:new Date().toISOString(),controller:process.memoryUsage(),containers:stdout.trim().split('\n').filter(Boolean).map(JSON.parse)});save();}catch(error){report.samples.push({at:new Date().toISOString(),samplingError:error.code??error.message});}finally{busy=false;}};await sample();sampling=setInterval(()=>void sample(),5000);
 report.indexes=h.json("SELECT jsonb_agg(jsonb_build_object('table',tablename,'name',indexname,'definition',indexdef) ORDER BY tablename,indexname) FROM pg_indexes WHERE schemaname='public' AND tablename IN('imports','import_rows','jobs','source_heads','source_revisions','messages','checkpoints')");save();
 for(const rows of sizes){
  const scale={rows,seed:308+rows,status:'running',concurrency:1,workerChunkRows:100,jobDeadlineMs:900000,files:[],apiRequests:[],chunks:[],startedAt:new Date().toISOString()};report.scales.push(scale);const directory=path.join(evidence,'dataset-'+rows);scale.dataset=generateDataset({rows,seed:scale.seed,directory});save();console.log('LOAD308_SCALE_START:'+rows);
  const runners=[];for(let i=0;i<scale.concurrency;i++)runners.push(await worker());await Promise.all(runners.map(w=>w.call('heartbeat')));
  const timed=async(label,fn)=>{const start=performance.now();try{return await fn();}finally{scale.apiRequests.push({label,ms:performance.now()-start});}};const runStart=performance.now();
  try{
   for(const part of scale.dataset.files){await Promise.all(runners.map(w=>w.call('heartbeat')));const bytes=fs.readFileSync(path.join(directory,part.filename));assert.equal(hash(bytes),part.sha256);
    const reserved=await timed('reserve',()=>h.request(h.A,'/api/imports',{connection_id:h.A.connection,mapping_version:'csv-message-v1',content_type:'text/csv',size:bytes.length,sha256:part.sha256}));assert.equal(reserved.status,201,JSON.stringify(reserved.data));const v=reserved.data.data;
    assert.equal(new URL(v.upload_url).origin,'http://127.0.0.1:'+(basePort()+3));const upload=await timed('storage_upload',async()=>{const r=await fetch(v.upload_url,{method:'PUT',headers:{'content-type':'text/csv'},body:bytes,signal:AbortSignal.timeout(30000)});await r.arrayBuffer();return r;});assert.equal(upload.status,200);
    const mapping=await timed('mapping_preview',()=>h.request(h.A,`/api/imports/${v.import_id}/mapping`,{mapping:{columns:{id:'id',text:'text',date:'date',role:'role',conversation:'conversation'},timezone:'UTC',dateFormat:'iso'},expected_version:'csv-message-v1'}));assert.equal(mapping.status,200,JSON.stringify(mapping.data));
    const m=mapping.data.data,confirmed=await timed('confirm',()=>h.request(h.A,`/api/imports/${v.import_id}/confirm`,{upload_token:m.upload_token,sha256:part.sha256,mapping_version:m.mapping_version}));assert.equal(confirmed.status,202,JSON.stringify(confirmed.data));
    const job=h.json(`SELECT jsonb_build_object('id',id,'deadline',deadline,'state',state) FROM jobs WHERE import_id=${q(v.import_id)}`);assert.equal(job.state,'queued');scale.files.push({...part,importId:v.import_id,jobId:job.id});save();
   }
   const processingStart=performance.now();let completed=0;
   await Promise.all(runners.map(async w=>{while(completed<scale.files.length){assert.ok(performance.now()-processingStart<3600000,'LOAD_SCALE_DEADLINE');const before=w.record.chunks.length;await w.call('consume');const chunks=w.record.chunks.slice(before);scale.chunks.push(...chunks);const states=h.json(`SELECT jsonb_agg(jsonb_build_object('id',id,'state',state,'failure_count',failure_count) ORDER BY id) FROM jobs WHERE id IN(${scale.files.map(x=>q(x.jobId)).join(',')})`);assert.ok(states.every(x=>['queued','running','partial','succeeded'].includes(x.state)),'LOAD_TERMINAL_FAILURE:'+JSON.stringify(states));completed=states.filter(x=>['partial','succeeded'].includes(x.state)).length;save();if(!chunks.length&&completed<scale.files.length)await new Promise(r=>setTimeout(r,500));}}));
   scale.processingMs=performance.now()-processingStart;scale.endToEndMs=performance.now()-runStart;
   const totals={total:0,accepted:0,rejected:0,duplicates:0,pending:0};for(const file of scale.files){const actual=h.json(`SELECT jsonb_build_object('total',total,'accepted',accepted,'rejected',rejected,'duplicates',duplicates,'pending',pending,'fileHash',file_hash) FROM imports WHERE id=${q(file.importId)}`);assert.equal(actual.fileHash,file.sha256);for(const key of Object.keys(totals))totals[key]+=Number(actual[key]);assert.equal(Number(actual.accepted)+Number(actual.rejected)+Number(actual.duplicates)+Number(actual.pending),file.rows);assert.equal(Number(h.sql(`SELECT count(*) FROM import_rows WHERE import_id=${q(file.importId)}`)),file.rows);assert.equal(hash(fs.readFileSync(path.join(directory,file.filename))),file.sha256);file.observed=actual;file.jobTiming=h.json(`SELECT jsonb_build_object('state',j.state,'deadline',j.deadline,'failureCount',j.failure_count,'firstStartedAt',min(a.started_at),'lastFinishedAt',max(a.finished_at),'elapsedMs',extract(epoch FROM(max(a.finished_at)-min(a.started_at)))*1000) FROM jobs j JOIN attempts a ON a.job_id=j.id WHERE j.id=${q(file.jobId)} GROUP BY j.id`);
    const endpoint=await timed('job_status',()=>h.request(h.A,'/api/jobs/'+file.jobId));assert.equal(endpoint.status,200,JSON.stringify(endpoint.data));file.apiCounters=endpoint.data.data.counters;assert.deepEqual(Object.fromEntries(Object.entries(file.apiCounters).map(([k,v])=>[k,Number(v)])),Object.fromEntries(Object.keys(totals).map(k=>[k,Number(actual[k])])));
   }assert.deepEqual(totals,scale.dataset.expected);scale.observed=totals;
   const ids=scale.files.map(x=>q(x.importId)).join(',');scale.explain=h.sql(`EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT state,count(*) FROM import_rows WHERE tenant_id=${q(h.A.tenant)} AND import_id IN(${ids}) GROUP BY state`);
   scale.metrics={inputRowsPerSecond:rows/(scale.processingMs/1000),acceptedRowsPerSecond:totals.accepted/(scale.processingMs/1000),commitP50Ms:percentile(scale.chunks.map(x=>x.commitMs),.5),commitP95Ms:percentile(scale.chunks.map(x=>x.commitMs),.95),apiP95Ms:percentile(scale.apiRequests.map(x=>x.ms),.95),commitSamples:scale.chunks.length,apiSamples:scale.apiRequests.length,workerMaxRssKiB:Math.max(...runners.map(x=>x.record.maxRssKiB))};scale.status='pass';console.log('LOAD308_SCALE_PASS:'+rows+':'+JSON.stringify(scale.metrics));
  }catch(error){scale.status='failed';scale.error={message:error.message,code:error.code??null};scale.elapsedMs=performance.now()-runStart;try{scale.failureSnapshot=scale.files.map(file=>({job:h.json(`SELECT row_to_json(j) FROM jobs j WHERE id=${q(file.jobId)}`),import:h.json(`SELECT jsonb_build_object('id',id,'total',total,'accepted',accepted,'rejected',rejected,'duplicates',duplicates,'pending',pending,'file_hash',file_hash) FROM imports WHERE id=${q(file.importId)}`),checkpoint:h.json(`SELECT checkpoint FROM checkpoints WHERE job_id=${q(file.jobId)}`)}));}catch(e){scale.failureSnapshotError=e.message;}save();throw error;}
  finally{await Promise.all(runners.map(w=>w.close()));save();}
 }
 h.verifySources();verifyDependencies();report.status='measured';
}catch(error){report.status='failed';report.error={message:error.message,code:error.code??null};process.exitCode=1;}
finally{if(sampling)clearInterval(sampling);while(busy)await new Promise(r=>setTimeout(r,100));for(const child of workers){if(child.exitCode===null&&child.signalCode===null){const ended=once(child,'exit');child.kill('SIGKILL');await ended;}}if(h)await h.close();report.finishedAt=new Date().toISOString();report.cleanup=fs.existsSync(path.join(evidence,'cleanup.json'))?JSON.parse(fs.readFileSync(path.join(evidence,'cleanup.json'),'utf8')):null;save();console.log('LOAD308_EVIDENCE:'+evidence);}
