import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {q,insert} from './matrix.mjs';
import {write,denied} from './harness.mjs';
import {backend} from './import-uploads/oracles.mjs';
export const tables=['brief_heads','brief_requests'];
export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
export const ownsFk=k=>tables.includes(k.table)||k.table==='weekly_briefs'&&['binding_id','comparison_binding_id','actor_id','previous_id'].some(c=>c in k.mapping);
export function schema(h,fks){
 assert.deepEqual(present(h),tables,'BRIEF_DURABLE_HEAD_AND_REQUEST_REQUIRED');
 for(const table of [...tables,'weekly_briefs'])assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'BRIEF_FORCE_RLS:'+table);
 for(const table of tables){assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','BRIEF_TENANT_REQUIRED');for(const role of ['anon','authenticated','service_role'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),'f','BRIEF_PRIVATE_GRANT:'+table+role+action);for(const action of ['DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege('vexa_backend',${q('public.'+table)},${q(action)})`),'f','BRIEF_MINIMAL_BACKEND_GRANT:'+table+action);}
 const keys=fks.filter(ownsFk);assert.equal(keys.length,10,'BRIEF_TEN_NEW_TENANT_FKS');for(const k of keys)assert.ok(k.validated&&(k.parent==='organizations'?k.mapping.tenant_id==='id':k.mapping.tenant_id==='tenant_id'),'BRIEF_COMPOSITE_FK:'+k.name);
}
const immutableDenied=(result,tag)=>{if(result.code==='23514')return;denied(result,tag);};
const context=(actor,tenant,action='import')=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('request.jwt.claims',${q(JSON.stringify({sub:actor.id,role:'authenticated'}))},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action',${q(action)},true);`;
const where=(table,row)=>table==='brief_heads'?`tenant_id=${q(row.tenant_id)} AND binding_id=${q(row.binding_id)}`:table==='brief_requests'?`tenant_id=${q(row.tenant_id)} AND request_key=${q(row.request_key)}`:`id=${q(row.id)}`;
const read=(table,row)=>`SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') INTO result FROM ${table} x WHERE ${where(table,row)};`;
export function fk(h,f,k){const row=f.a[k.table],probe=values=>h.probe(`ALTER TABLE ${k.table} DISABLE TRIGGER USER;${write(`UPDATE ${k.table} SET ${Object.entries(values).map(([key,value])=>`${key}=${value===null?'NULL':q(value)}`).join(',')} WHERE ${where(k.table,row)}`)}SET CONSTRAINTS ALL IMMEDIATE;`);const same=Object.fromEntries(Object.keys(k.mapping).map(c=>[c,row[c]]));assert.equal(probe(same).code,'00000','BRIEF_FK_POSITIVE:'+k.name);const bad={...same};for(const[col,ref]of Object.entries(k.mapping))if(k.parent==='organizations')bad[col]=randomUUID();else if(col!=='tenant_id')bad[col]=f.b[k.parent][ref];const result=probe(bad);assert.equal(result.code,'23503','BRIEF_FK_FOREIGN:'+k.name);assert.ok(result.constraint);}
const canonical=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';
const hash=x=>createHash('sha256').update(canonical(x)).digest('hex');
const committed=(h,actor,t,sql)=>h.sql('BEGIN;'+context(actor,t)+sql+';COMMIT;');
const seal=row=>{const document=structuredClone(row.document),content_hash=hash(document),input_manifest={...row.input_manifest,documentHash:content_hash};return {...row,document,content_hash,input_manifest,input_hash:hash(input_manifest),canonical_input:canonical(input_manifest),canonical_document:canonical(document)};};
export async function seed(h,base,actors,workspaces){const {buildBrief}=await import(new URL('file://'+process.env.VEXA_CANDIDATE+'/packages/briefs/build.mjs'));const out={};for(const side of ['a','b']){const w=workspaces[side],actor=actors[side],b=w.workspace_scope_bindings,t=w.tenant;const scope={...b.filters,date_start:b.filters.date_start+'T00:00:00.000Z',date_end:b.filters.date_end+'T00:00:00.000Z',scope_hash:b.scope_hash};const metrics=[];for(const kind of ['allOrders','exposure','refunds']){const r=backend(h,`SELECT jsonb_build_array(public.brief_metric(${q(t)}::uuid,${q(b.id)}::uuid,${q(kind)})) INTO result;`,actor,t,'read');assert.equal(r.code,'00000','BRIEF_CANONICAL_SEED:'+JSON.stringify(r));const value=r.rows[0];metrics.push({kind,label:'SYN '+kind,amount_minor:value.amountMinor,known_subtotal:value.knownSubtotalMinor,currency:'USD',exponent:2,source_ref:'workspace:'+b.scope_hash,status:value.status,coverage:{known_n:value.knownCount,eligible_n:value.totalCount},missing_reasons:value.missingReasons});}
 const snap=h.json(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(w.metric_snapshots.id)}`),document=buildBrief({snapshotId:snap.id,scopeHash:b.scope_hash,baseScopeHash:b.base_scope_hash,scope,asOf:new Date(snap.as_of).toISOString(),watermark:new Date(snap.watermark).toISOString(),coverage:'SYN canonical observed coverage',metrics,problems:[],actions:[],comparison:{status:'not_requested',snapshotId:null,scopeHash:null,reasons:['NO_COMPARISON_SELECTED'],metrics:[],causalClaim:false}}),input_manifest={template:'brief-observed-v1',bindingId:b.id,snapshotId:snap.id,snapshotContentHash:snap.content_hash,comparisonBindingId:null,priorityRunId:null,actions:[],documentHash:hash(document)};
 const row=seal({id:randomUUID(),tenant_id:t,status:'published',version:1,scope_hash:b.scope_hash,snapshot_id:snap.id,week_start:b.filters.date_start,brief_schema:'brief-v1',binding_id:b.id,comparison_binding_id:null,actor_id:actor.id,previous_id:null,input_manifest,document});committed(h,actor,t,insert('weekly_briefs',row));const head={tenant_id:t,binding_id:b.id,brief_id:row.id},request={tenant_id:t,request_key:'SYN-brief-'+randomUUID(),fingerprint:hash({row:row.id,query:scope}),brief_id:row.id,actor_id:actor.id};committed(h,actor,t,insert('brief_heads',head)+';'+insert('brief_requests',request));out[side]={...w,metric_snapshots:snap,weekly_briefs:row,brief_heads:head,brief_requests:request,memberships:{user_id:actor.id}};
 }return out;}
export function access(h,f,actors){for(const table of ['weekly_briefs',...tables]){const row=f.a[table],statement=read(table,row);for(const who of ['a','dual','viewer','analyst','operator']){const r=backend(h,statement,actors[who],f.a.tenant,'read');assert.equal(r.code,'00000',JSON.stringify(r));assert.equal(r.rows.length,1,'BRIEF_CURRENT_READ_ROLE:'+table+who);assert.equal(r.rows[0].tenant_id,f.a.tenant);}for(const who of [null,...Object.values(actors)])denied(h.probe(statement,who),'BRIEF_BROWSER_PRIVATE');denied(h.probe('SET LOCAL ROLE service_role;'+statement),'BRIEF_SERVICE_PRIVATE');for(const who of ['b','outsider'])denied(backend(h,statement,actors[who],f.a.tenant,'read'),'BRIEF_FOREIGN_READ');denied(backend(h,statement,actors.dual,f.b.tenant,'read'),'BRIEF_SELECTED_TENANT');denied(backend(h,statement,actors.a,f.a.tenant,'read',`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(f.a.tenant)} AND user_id=${q(actors.a.id)};`),'BRIEF_CURRENT_READER');}
 for(const who of ['viewer','operator','b','outsider']){const request={...f.a.brief_requests,request_key:randomUUID(),actor_id:actors[who].id};denied(backend(h,write(insert('brief_requests',request)),actors[who],f.a.tenant,'import'),'BRIEF_GENERATE_ROLE:'+who);}
 for(const table of ['weekly_briefs','brief_requests'])for(const operation of ['UPDATE','DELETE'])for(const action of ['import','configure','retain','materialize'])immutableDenied(backend(h,write(operation==='DELETE'?`DELETE FROM ${table} WHERE ${where(table,f.a[table])}`:`UPDATE ${table} SET ${table==='weekly_briefs'?"status='failed'":"fingerprint='"+'0'.repeat(64)+"'"} WHERE ${where(table,f.a[table])}`),actors.a,f.a.tenant,action),'BRIEF_IMMUTABLE:'+table+operation+action);
}
const fresh=(f,patch={})=>seal({...f.a.weekly_briefs,id:randomUUID(),version:f.a.weekly_briefs.version+1,previous_id:f.a.weekly_briefs.id,...patch});
export function integrity(h,f,actors){const run=row=>backend(h,write(insert('weekly_briefs',row)),actors.a,f.a.tenant,'import');
 const changed=structuredClone(f.a.weekly_briefs.document);changed.limits.push('SYN an explicit additional disclosure for a new immutable revision.');const valid=fresh(f,{document:changed});assert.equal(run(valid).code,'00000','BRIEF_NEW_VERSION_POSITIVE');
 const forged=structuredClone(changed);forged.metrics.find(m=>m.kind==='allOrders').amount_minor='9007199254740993';assert.notEqual(run(fresh(f,{document:forged})).code,'00000','BRIEF_REHASHED_FORGED_FINANCIAL_AMOUNT');
 const falseCoverage=structuredClone(changed);Object.assign(falseCoverage.metrics.find(m=>m.kind==='allOrders'),{status:'complete',coverage:{known_n:999,eligible_n:999},missing_reasons:[]});assert.notEqual(run(fresh(f,{document:falseCoverage})).code,'00000','BRIEF_REHASHED_FORGED_COVERAGE');
 for(const patch of [{version:1},{version:99},{previous_id:null},{binding_id:f.b.workspace_scope_bindings.id},{snapshot_id:f.b.metric_snapshots.id},{scope_hash:'f'.repeat(64)},{actor_id:actors.dual.id},{brief_schema:'fake'},{canonical_document:'{}'},{input_hash:'0'.repeat(64)}]){const row={...valid,...patch};assert.notEqual(run(row).code,'00000','BRIEF_INVALID_PIN_OR_CAS:'+JSON.stringify(patch));}
 for(const field of ['brief_schema','document','input_manifest','canonical_document','input_hash','binding_id'])immutableDenied(backend(h,write(`UPDATE weekly_briefs SET ${field}=NULL WHERE id=${q(f.a.weekly_briefs.id)}`),actors.a,f.a.tenant,'import'),'BRIEF_NO_MANAGED_DOWNGRADE:'+field);
 const req=f.a.brief_requests;assert.equal(backend(h,write(insert('brief_requests',{...req,fingerprint:'e'.repeat(64)})),actors.a,f.a.tenant,'import').code,'23505','BRIEF_REQUEST_KEY_UNIQUE');assert.equal(backend(h,write(insert('brief_requests',{...req,request_key:randomUUID()})),actors.analyst,f.a.tenant,'import').code,'42501','BRIEF_REQUEST_ACTOR_NOT_SPOOFABLE');
 immutableDenied(backend(h,write(`UPDATE brief_heads SET brief_id=${q(f.b.weekly_briefs.id)} WHERE ${where('brief_heads',f.a.brief_heads)}`),actors.a,f.a.tenant,'import'),'BRIEF_HEAD_FOREIGN');
}
export function authorization(h,f,actors){const a=f.a,statement=read('weekly_briefs',a.weekly_briefs),revoke=`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(a.tenant)} AND user_id=${q(actors.a.id)};`;denied(backend(h,statement,actors.dual,a.tenant,'read',revoke),'BRIEF_CURRENT_FINANCIAL_CONTRIBUTOR');const source={...a.source,id:randomUUID(),version:a.source.version+1,active:false};const before=`PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);PERFORM set_config('vexa.action','configure',true);${insert('economic_source_versions',source)};`;denied(backend(h,statement,actors.a,a.tenant,'read',before),'BRIEF_WITHDRAWN_SOURCE');
 const noAction=`GRANT ALL ON exam_result TO vexa_backend;SET LOCAL ROLE vexa_backend;PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);`;assert.deepEqual(h.probe(noAction+`SELECT jsonb_build_array(public.brief_inputs_current(${q(a.tenant)}::uuid,${q(a.metric_snapshots.id)}::uuid,'[]')) INTO result;`).rows,[false],'BRIEF_INPUT_HELPER_MISSING_ACTION');const unscopedProjection=h.probe(noAction+`SELECT jsonb_build_array(public.brief_projection(${q(a.tenant)}::uuid,${q(a.metric_snapshots.id)}::uuid,${q(JSON.stringify(a.workspace_scope_bindings.filters))}::jsonb,'allOrders',ARRAY[${q(a.workspace_order_dimension_versions.id)}::uuid])) INTO result;`);assert.equal(unscopedProjection.code,'42501','BRIEF_PROJECTION_MISSING_ACTION');
 for(const [sig,args] of [['brief_binding_current(uuid,uuid)',`${q(a.tenant)}::uuid,${q(a.workspace_scope_bindings.id)}::uuid`],['brief_visible(uuid,uuid)',`${q(a.tenant)}::uuid,${q(a.weekly_briefs.id)}::uuid`],['brief_manifest_current(uuid,jsonb)',`${q(a.tenant)}::uuid,${q(JSON.stringify(a.weekly_briefs.input_manifest))}::jsonb`]]){const meta=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q('public.'+sig)}::regprocedure`);assert.equal(meta.definer,true);assert.ok(meta.config.includes('search_path=""'),'BRIEF_HELPER_SEARCH_PATH');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q('public.'+sig)},'EXECUTE')`),role==='vexa_backend'?'t':'f','BRIEF_HELPER_GRANT');const call=`SELECT jsonb_build_array(public.${sig.split('(')[0]}(${args})) INTO result;`;assert.deepEqual(backend(h,call,actors.viewer,a.tenant,'read').rows,[true],'BRIEF_HELPER_VIEWER_CURRENT');for(const[actor,tenant,action]of [[actors.b,a.tenant,'read'],[actors.dual,f.b.tenant,'read'],[actors.a,a.tenant,'materialize'],[actors.a,a.tenant,'configure']])assert.deepEqual(backend(h,call,actor,tenant,action).rows,[false],'BRIEF_HELPER_SCOPED');}
}

export function comparison(h,f,actors){
 const a=f.a,t=a.tenant,actor=actors.a,source={...a.source,id:randomUUID(),source_id:randomUUID(),window_start:'2025-12-01T00:00:00.000Z',window_end:'2026-01-01T00:00:00.000Z',watermark:'2026-01-01T00:00:00.000Z'},order={...a.economic_ledger_entries,id:randomUUID(),entity_id:randomUUID(),source_id:source.source_id,amount_minor:'5000',effective_at:'2025-12-02T00:00:00.000Z'},mapping={...a.workspace_order_dimension_versions,id:randomUUID(),ledger_row_id:order.id};
 h.sql('BEGIN;'+context(actor,t,'configure')+insert('economic_source_versions',source)+';'+insert('economic_ledger_entries',order)+';'+insert('workspace_order_dimension_versions',{...mapping,skus:'{'+mapping.skus.join(',')+'}'})+';COMMIT;');
 const scope={...a.metric_snapshots.provenance.scope,start:source.window_start,end:source.window_end},snap={...a.metric_snapshots,id:randomUUID(),scope_hash:hash(scope),input_hash:hash(randomUUID()),status:'draft',as_of:new Date().toISOString(),date_start:scope.start,date_end:scope.end,published_at:null,published_by:null,bundle_ref:null,content_hash:'0'.repeat(64),watermark:source.watermark,provenance:{...a.metric_snapshots.provenance,scope},input_manifest:{...a.metric_snapshots.input_manifest,selection:{scope,fxRateId:null},refs:[{table:'economic_source_versions',id:source.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hash(source)},{table:'economic_ledger_entries',id:order.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hash(order)}],watermarks:[{sourceId:source.source_id,version:1,watermark:source.watermark,complete:true,active:true}]}};
 const components=a.components.map(c=>({...c,id:randomUUID(),snapshot_id:snap.id}));h.sql('BEGIN;'+context(actor,t)+insert('metric_snapshots',snap)+';'+components.map(c=>insert('components',c)+';').join('')+`UPDATE metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id),status='published',published_at=clock_timestamp(),published_by=${q(actor.id)},bundle_ref='canonical:SYN-brief-prior' WHERE id=${q(snap.id)};COMMIT;`);
 const b0=a.workspace_scope_bindings,filters={...b0.filters,date_start:'2025-12-01',date_end:'2026-01-01',snapshot_id:snap.id},body={baseSnapshotId:snap.id,baseScopeHash:snap.scope_hash,filters,mappingIds:[mapping.id],problemVersions:[],version:b0.projection_version},binding={...b0,id:randomUUID(),base_snapshot_id:snap.id,base_scope_hash:snap.scope_hash,filters,mapping_ids:[mapping.id],problem_versions:[],canonical_input:canonical(body),scope_hash:hash(body)};h.sql('BEGIN;'+context(actor,t,'materialize')+insert('workspace_scope_bindings',{...binding,mapping_ids:'{'+binding.mapping_ids.join(',')+'}'})+';COMMIT;');
 const metrics=a.weekly_briefs.document.metrics.map(m=>{const result=backend(h,`SELECT jsonb_build_array(public.brief_metric(${q(t)}::uuid,${q(binding.id)}::uuid,${q(m.kind)})) INTO result;`,actor,t,'read');assert.equal(result.code,'00000',JSON.stringify(result));const old=result.rows[0].amountMinor;return {kind:m.kind,currency:m.currency,exponent:m.exponent,previousAmountMinor:old,currentAmountMinor:m.amount_minor,deltaMinor:old!==null&&m.amount_minor!==null?(BigInt(m.amount_minor)-BigInt(old)).toString():null};});
 assert.equal(metrics.find(m=>m.kind==='allOrders').deltaMinor,'5000','BRIEF_COMPARISON_EXACT_REAL_PRIOR');const document={...a.weekly_briefs.document,comparison:{status:'available',snapshotId:snap.id,scopeHash:binding.scope_hash,reasons:['SOME_METRICS_UNKNOWN'],metrics,causalClaim:false}},row=fresh(f,{document,comparison_binding_id:binding.id,input_manifest:{...a.weekly_briefs.input_manifest,comparisonBindingId:binding.id}});committed(h,actor,t,insert('weekly_briefs',row)+`;UPDATE brief_heads SET brief_id=${q(row.id)} WHERE ${where('brief_heads',a.brief_heads)}`);
 const statement=read('weekly_briefs',row);assert.equal(backend(h,statement,actors.viewer,t,'read').rows.length,1,'BRIEF_COMPARISON_POSITIVE');
 const withdrawn={...source,id:randomUUID(),version:2,active:false},prepare=`PERFORM set_config('request.jwt.claim.sub',${q(actor.id)},true);PERFORM set_config('vexa.tenant_id',${q(t)},true);PERFORM set_config('vexa.action','configure',true);${insert('economic_source_versions',withdrawn)};`;
 assert.equal(backend(h,read('weekly_briefs',a.weekly_briefs),actors.viewer,t,'read',prepare).rows.length,1,'BRIEF_CURRENT_SOURCE_UNCHANGED_CONTROL');denied(backend(h,statement,actors.viewer,t,'read',prepare),'BRIEF_WITHDRAWN_COMPARISON_SOURCE');
 const tampered=structuredClone(row.document);tampered.comparison.metrics.find(m=>m.kind==='allOrders').deltaMinor='0';const bad=seal({...row,id:randomUUID(),version:row.version+1,previous_id:row.id,document:tampered});assert.notEqual(backend(h,write(insert('weekly_briefs',bad)),actor,t,'import').code,'00000','BRIEF_COMPARISON_REHASHED_FAKE_DELTA');
 a.weekly_briefs=row;a.brief_heads={...a.brief_heads,brief_id:row.id};
}
export function claims(h,f,actors){const accepted=[];for(const [name,mutate]of [['nested_causal',d=>d.comparison.causalClaim=true],['forecast_fabricated',d=>d.forecast={status:'available',amountMinor:'3200',reason:'SYN invented recovered forecast without model'}],['global_causal',d=>d.causalClaim=true],['sent',d=>d.sent=true],['additive',d=>d.problemRowsAreAdditive=true],['recovered_metric',d=>d.metrics.find(m=>m.kind==='refunds').kind='causally_recovered_revenue']]){const doc=structuredClone(f.a.weekly_briefs.document);mutate(doc);const row=fresh(f,{document:doc}),result=backend(h,write(insert('weekly_briefs',row)),actors.a,f.a.tenant,'import');if(result.code==='00000')accepted.push(name);}assert.deepEqual(accepted,[],'BRIEF_REHASHED_UNSUPPORTED_CLAIMS:'+accepted.join(','));}
