import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {q,insert} from './matrix.mjs';import {read,write,denied} from './harness.mjs';import {backend} from './import-uploads/oracles.mjs';
export const tables=['problem_operational_evidence','problem_causal_versions'];export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
export function schema(h,fks){assert.deepEqual(present(h),tables);for(const table of tables){assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'CAUSAL_FORCE_RLS');assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t');for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),role==='vexa_backend'&&['SELECT','INSERT'].includes(action)?'t':'f','CAUSAL_GRANT:'+table+role+action);const keys=fks.filter(x=>x.table===table);assert.deepEqual(keys.map(x=>x.parent).sort(),['memberships','problems'],'CAUSAL_FK_SET');for(const key of keys)assert.ok(key.validated&&key.mapping.tenant_id==='tenant_id','CAUSAL_TENANT_FK');}}
export function seed(h,f,actors){const out={};for(const side of ['a','b']){const base=f[side],tenant=base.problems.tenant_id,e={id:randomUUID(),tenant_id:tenant,problem_id:base.problems.id,record_id:'SYN causal '+side,version:1,actor_id:actors[side].id,source_kind:'inspection',observed_at:'2026-01-01T00:00:00Z',report:'SYN independent physical inspection, no batch asserted.',digest:'c'.repeat(64),stance:'supports',status:'active',facts:{batch:null,carrier:null,sku:null},attested:true},claim={id:randomUUID(),tenant_id:tenant,problem_id:base.problems.id,version:1,actor_id:actors[side].id,symptom:'SYN smoke',probable_cause:null,state:'hypothesis',reason:'SYN human review',evidence_ids:'{}',facts:{batch:null,carrier:null,sku:null},critical_review:true,approved:true};h.sql(insert(tables[0],e)+';'+insert(tables[1],claim)+';');out[side]={...base,problem_operational_evidence:e,problem_causal_versions:claim,memberships:{user_id:actors[side].id}};}return out;}
export function access(h,f,actors){const tenant=f.a.problems.tenant_id;for(const table of tables){for(const actor of [null,...Object.values(actors)])denied(h.probe(read(table),actor),'CAUSAL_DIRECT_DENY');denied(h.probe('SET LOCAL ROLE service_role;'+read(table)),'CAUSAL_SERVICE_DENY');for(const who of ['a','analyst','operator','viewer','dual']){const r=backend(h,read(table),actors[who],tenant,'read');assert.equal(r.code,'00000');assert.equal(r.rows.length,1,'CAUSAL_MEMBER_READ:'+who);}for(const who of ['b','outsider'])assert.deepEqual(backend(h,read(table),actors[who],tenant,'read').rows,[],'CAUSAL_FOREIGN_READ');assert.deepEqual(backend(h,read(table),actors.a,tenant,'read',`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`).rows,[],'CAUSAL_REVOKED_READ');
 const reset=`ALTER TABLE ${table} DISABLE TRIGGER USER; DELETE FROM ${table}; ALTER TABLE ${table} ENABLE TRIGGER USER;`;
 for(const who of ['a','analyst','operator']){const row={...f.a[table],actor_id:actors[who].id};const r=backend(h,write(insert(table,row)),actors[who],tenant,'propose',reset);assert.equal(r.code,'00000','CAUSAL_POSITIVE_'+who+':'+JSON.stringify(r));assert.equal(r.rows[0].affected,1);}
 for(const who of ['viewer','outsider'])denied(backend(h,write(insert(table,{...f.a[table],actor_id:actors[who].id})),actors[who],tenant,'propose',reset),'CAUSAL_DENIED_INSERT');denied(backend(h,write(insert(table,{...f.a[table],actor_id:actors.b.id})),actors.a,tenant,'propose',reset),'CAUSAL_ACTOR_SPOOF');for(const action of ['UPDATE','DELETE'])denied(backend(h,write(action==='UPDATE'?`UPDATE ${table} SET version=99`:`DELETE FROM ${table}`),actors.a,tenant,'configure'),'CAUSAL_APPEND_ONLY');assert.equal(h.probe(write(`UPDATE ${table} SET version=99`)).code,'42501','CAUSAL_TRIGGER_APPEND_ONLY');
 }
 const claim={...f.a.problem_causal_versions,state:'confirmed',probable_cause:'SYN reviewed operational cause',evidence_ids:'{'+f.a.problem_operational_evidence.id+'}'},reset=`ALTER TABLE problem_causal_versions DISABLE TRIGGER USER;DELETE FROM problem_causal_versions;ALTER TABLE problem_causal_versions ENABLE TRIGGER USER;`;
 assert.equal(backend(h,write(insert('problem_causal_versions',claim)),actors.a,tenant,'approve',reset).code,'00000','CAUSAL_OWNER_CONFIRM');for(const who of ['operator','analyst','viewer']){const statement=write(insert('problem_causal_versions',{...claim,actor_id:actors[who].id}));const r=backend(h,statement,actors[who],tenant,'approve',reset);assert.ok(['42501','23514'].includes(r.code),'CAUSAL_CONFIRM_OWNER_ONLY:'+r.code);denied(backend(h,statement,actors[who],tenant,'approve',reset+'ALTER TABLE problem_causal_versions DISABLE TRIGGER USER;'),'CAUSAL_CONFIRM_RLS_INDEPENDENT_OF_TRIGGER');}assert.notEqual(backend(h,write(insert('problem_causal_versions',{...claim,evidence_ids:'{}'})),actors.a,tenant,'approve',reset).code,'00000','CAUSAL_SQL_CONFIRM_REQUIRES_EVIDENCE');assert.notEqual(backend(h,write(insert('problem_causal_versions',{...claim,evidence_ids:'{'+f.b.problem_operational_evidence.id+'}'})),actors.a,tenant,'approve',reset).code,'00000','CAUSAL_SQL_FOREIGN_EVIDENCE');}
export function fk(h,f,key){const row=f.a[key.table],make=value=>h.probe(`ALTER TABLE ${key.table} DISABLE TRIGGER USER;DELETE FROM ${key.table};${write(insert(key.table,value))}SET CONSTRAINTS ALL IMMEDIATE;`);assert.equal(make(row).code,'00000','CAUSAL_FK_POSITIVE:'+key.name);const bad={...row};for(const[col,ref]of Object.entries(key.mapping))if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];const negative=make(bad);assert.equal(negative.code,'23503','CAUSAL_FK_CROSS:'+key.name);assert.ok(negative.constraint);}

export function contributor(h,f,actors){const signature='public.causality_contributor_active(uuid,uuid)',p=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig,'returns',prorettype::regtype::text,'volatile',provolatile) FROM pg_proc WHERE oid=${q(signature)}::regprocedure`);assert.equal(p.definer,true,'CAUSAL_HELPER_DEFINER');assert.ok(p.config?.includes('search_path=""'),'CAUSAL_HELPER_FIXED_SEARCH_PATH');assert.equal(p.returns,'boolean');assert.equal(p.volatile,'s');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(signature)},'EXECUTE')`),role==='vexa_backend'?'t':'f','CAUSAL_HELPER_GRANTS:'+role);const tenant=f.a.problems.tenant_id,foreign=f.b.problems.tenant_id,call=(targetTenant,actorId)=>`SELECT jsonb_build_array(public.causality_contributor_active(${q(targetTenant)}::uuid,${q(actorId)}::uuid)) INTO result;`,check=(who,targetTenant,contributor,action,expected,prepare='')=>{const r=backend(h,call(targetTenant,actors[contributor].id),actors[who],tenant,action,prepare);assert.equal(r.code,'00000',JSON.stringify(r));assert.deepEqual(r.rows,[expected],'CAUSAL_HELPER_SCOPE:'+who+':'+contributor+':'+action);};for(const who of ['a','analyst','operator','viewer'])for(const contributor of ['a','analyst','operator'])check(who,tenant,contributor,'read',true);for(const action of ['read','propose','approve'])check('a',tenant,'analyst',action,true);for(const action of ['configure','import','execute','worker_dispatch',''])check('a',tenant,'analyst',action,false);check('outsider',tenant,'a','read',false);check('b',tenant,'a','read',false);check('a',foreign,'b','read',false);check('a',tenant,'b','read',false);check('a',tenant,'viewer','read',false);check('a',tenant,'analyst','read',false,`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`);check('a',tenant,'analyst','read',false,`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.analyst.id)};`);check('a',tenant,'analyst','read',false,`UPDATE memberships SET role='viewer' WHERE user_id=${q(actors.analyst.id)};`);
 for(const actor of [null,actors.a,actors.outsider])denied(h.probe(call(tenant,actors.a.id),actor),'CAUSAL_HELPER_DIRECT_DENIED');denied(h.probe('SET LOCAL ROLE service_role;'+call(tenant,actors.a.id)),'CAUSAL_HELPER_SERVICE_DENIED');
}
