import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {q,insert} from './matrix.mjs';import {read,write,denied} from './harness.mjs';import {backend} from './import-uploads/oracles.mjs';
export const tables=['economic_source_versions','economic_ledger_entries'];export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
export function schema(h,fks){assert.deepEqual(present(h),tables,'ECONOMIC_TABLES_REQUIRED');for(const table of tables){assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'ECONOMIC_FORCE_RLS');assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t');for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),role==='vexa_backend'&&['SELECT','INSERT'].includes(action)?'t':'f','ECONOMIC_GRANT:'+table+role+action);}
 const keys=fks.filter(x=>tables.includes(x.table));assert.equal(keys.length,3,'ECONOMIC_FK_COUNT');for(const [table,parent,mapping]of [[tables[0],'memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],[tables[1],'memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],[tables[1],tables[0],{tenant_id:'tenant_id',source_id:'source_id',source_version:'version'}]])assert.ok(keys.some(k=>k.table===table&&k.parent===parent&&k.validated&&JSON.stringify(Object.entries(k.mapping).sort())===JSON.stringify(Object.entries(mapping).sort())),'ECONOMIC_COMPOSITE_FK:'+table+parent);
 assert.equal(h.sql("SELECT atttypmod FROM pg_attribute WHERE attrelid='public.economic_ledger_entries'::regclass AND attname='amount_minor'"),'-1','ECONOMIC_NO_NUMERIC_SCALE_COERCION');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},'public.economic_append_guard()','EXECUTE')`),'f','ECONOMIC_TRIGGER_NOT_PUBLIC_RPC');}
const context=(actor,tenant)=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('request.jwt.claims',${q(JSON.stringify({sub:actor.id,role:'authenticated'}))},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action','configure',true);`;
export function seed(h,f,actors){const out={};for(const side of ['a','b']){const tenant=f[side].problems.tenant_id,source={id:randomUUID(),tenant_id:tenant,source_id:randomUUID(),version:1,actor_id:actors[side].id,name:'SYN economic '+side,evidence_type:'payment_ledger',active:true,complete:true,window_start:'2026-01-01T00:00:00Z',window_end:'2026-02-01T00:00:00Z',watermark:'2026-02-01T00:00:00Z',report:'SYN financial operational source, never ticket narrative.',report_hash:'c'.repeat(64),attested:true},entry={id:randomUUID(),tenant_id:tenant,entity_id:randomUUID(),source_id:source.source_id,source_version:1,revision:1,actor_id:actors[side].id,external_id:'SYN-refund-'+side,kind:'refund',effective_at:'2026-01-02T00:00:00Z',currency:'USD',exponent:2,basis:'SYN-net-no-tax',amount_minor:'900719925474099312345',status:'settled',order_id:null,reversal_of:null,details:{},report:'SYN financial event independently observed operationally.',report_hash:'d'.repeat(64),attested:true};h.sql('BEGIN;'+context(actors[side],tenant)+insert(tables[0],source)+';'+insert(tables[1],entry)+';COMMIT;');out[side]={[tables[0]]:source,[tables[1]]:entry,memberships:{user_id:actors[side].id},tenant};}return out;}
const fresh=(row,table)=>({...row,id:randomUUID(),...(table===tables[0]?{source_id:randomUUID(),version:1}:{entity_id:randomUUID(),external_id:'SYN-'+randomUUID(),revision:1})});
export function access(h,f,actors){for(const table of tables){const own=f.a[table],tenant=f.a.tenant,before=h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`);
 for(const actor of [null,...Object.values(actors)])denied(h.probe(read(table),actor),'ECONOMIC_DIRECT_DENIED:'+table);denied(h.probe('SET LOCAL ROLE service_role;'+read(table)),'ECONOMIC_SERVICE_DENIED');
 for(const who of ['a','analyst','operator','viewer','dual']){const r=backend(h,read(table),actors[who],tenant,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.id),[own.id],'ECONOMIC_OWN_READ:'+who);}for(const who of ['b','outsider'])denied(backend(h,read(table),actors[who],tenant,'read'),'ECONOMIC_FOREIGN_READ');denied(backend(h,read(table),actors.a,f.b.tenant,'read'),'ECONOMIC_FORGED_SELECTOR');denied(backend(h,read(table),actors.a,tenant,'read',`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`),'ECONOMIC_REVOKED_READ');
 const valid=fresh(own,table),pos=backend(h,write(insert(table,valid)),actors.a,tenant,'configure');assert.equal(pos.code,'00000','ECONOMIC_OWNER_WRITE:'+JSON.stringify(pos));assert.equal(pos.rows[0].affected,1);
 for(const who of ['viewer','operator','analyst','outsider','b'])denied(backend(h,write(insert(table,{...valid,actor_id:actors[who].id})),actors[who],tenant,'configure'),'ECONOMIC_OWNER_ONLY:'+who);
 denied(backend(h,write(insert(table,{...valid,actor_id:actors.b.id})),actors.a,tenant,'configure'),'ECONOMIC_ACTOR_SPOOF');denied(backend(h,write(insert(table,{...valid,tenant_id:f.b.tenant})),actors.a,tenant,'configure'),'ECONOMIC_FOREIGN_WRITE');denied(backend(h,write(insert(table,valid)),actors.a,tenant,'read'),'ECONOMIC_ACTION_FENCE');denied(backend(h,write(insert(table,valid)),actors.a,tenant,'configure',`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`),'ECONOMIC_REVOKED_WRITE');
 for(const action of ['UPDATE','DELETE']){const stmt=action==='UPDATE'?`UPDATE ${table} SET report='SYN malicious change of immutable source record' WHERE id=${q(own.id)}`:`DELETE FROM ${table} WHERE id=${q(own.id)}`;denied(backend(h,write(stmt),actors.a,tenant,'configure'),'ECONOMIC_APPEND_ONLY');assert.equal(h.probe(write(stmt)).code,'42501','ECONOMIC_TRIGGER_APPEND_ADMIN');}
 assert.equal(h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`),before,'ECONOMIC_NEGATIVE_ZERO_PERSISTED_EFFECT');}}
export function financial(h,f,actors){const table=tables[1],tenant=f.a.tenant,base=fresh(f.a[table],table),run=(row,prepare='')=>backend(h,write(insert(table,row)),actors.a,tenant,'configure',prepare);
 assert.equal(h.sql(`SELECT amount_minor::text FROM ${table} WHERE id=${q(f.a[table].id)}`),'900719925474099312345','ECONOMIC_EXACT_GT2POW53');
 assert.equal(run({...base,amount_minor:'1.2'}).code,'23514','ECONOMIC_FRACTION_REJECTED_NOT_ROUNDED');assert.equal(run({...base,amount_minor:null,status:'unknown'}).code,'00000','ECONOMIC_UNKNOWN_NOT_ZERO');assert.equal(run({...base,amount_minor:'0'}).code,'00000','ECONOMIC_OBSERVED_ZERO_ALLOWED');assert.equal(run({...base,amount_minor:'-1'}).code,'23514','ECONOMIC_REFUND_NEGATIVE_DENIED');assert.equal(run({...base,kind:'reversal',amount_minor:'-500',reversal_of:randomUUID()}).code,'00000','ECONOMIC_ORPHAN_INTAKE_PRESERVED');assert.equal(run({...base,kind:'reversal',amount_minor:'500',reversal_of:randomUUID()}).code,'23514','ECONOMIC_REVERSAL_SIGN_REQUIRED');assert.equal(run({...base,status:'recorded'}).code,'23514','ECONOMIC_SETTLEMENT_NOT_ORDER_STATE');assert.equal(run({...base,kind:'order',status:'recorded'}).code,'23514','ECONOMIC_SOURCE_KIND_REQUIRED');assert.equal(run({...base,attested:false}).code,'23514','ECONOMIC_ATTESTATION_REQUIRED');
 assert.equal(run({...base,source_version:99}).code,'23514','ECONOMIC_SOURCE_VERSION_STALE');assert.equal(run({...base,entity_id:f.a[table].entity_id,external_id:f.a[table].external_id}).code,'40001','ECONOMIC_ENTRY_CAS');assert.equal(run({...base,entity_id:f.a[table].entity_id,external_id:f.a[table].external_id,revision:2}).code,'00000','ECONOMIC_ENTRY_NEXT_REVISION_POSITIVE');assert.equal(run({...base,entity_id:f.a[table].entity_id,revision:2}).code,'23514','ECONOMIC_CANONICAL_IDENTITY_IMMUTABLE');
 const source={...f.a[tables[0]],id:randomUUID()},sourceRun=row=>backend(h,write(insert(tables[0],row)),actors.a,tenant,'configure');assert.equal(sourceRun(source).code,'40001','ECONOMIC_SOURCE_CAS');assert.equal(sourceRun({...source,version:2}).code,'00000','ECONOMIC_SOURCE_NEXT_VERSION_POSITIVE');assert.equal(sourceRun({...source,version:2,evidence_type:'order_export'}).code,'23514','ECONOMIC_SOURCE_KIND_IMMUTABLE');
 const prefix=insert(tables[0],{...source,version:2,active:false})+';';const inactive=backend(h,prefix+write(insert(table,{...base,source_version:2})),actors.a,tenant,'configure');assert.equal(inactive.code,'23514','ECONOMIC_INACTIVE_SOURCE_DENIED');}
export function fk(h,f,key){const make=value=>h.probe(`ALTER TABLE ${key.table} DISABLE TRIGGER USER;${write(insert(key.table,value))}SET CONSTRAINTS ALL IMMEDIATE;`),row=fresh(f.a[key.table],key.table);assert.equal(make(row).code,'00000','ECONOMIC_FK_POSITIVE:'+key.name);const bad={...row};for(const[col,ref]of Object.entries(key.mapping))if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];const r=make(bad);assert.equal(r.code,'23503','ECONOMIC_FK_CROSS:'+key.name);assert.ok(r.constraint,'ECONOMIC_FK_NAMED');}
