import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {q,insert} from './matrix.mjs';
import {read,write,denied} from './harness.mjs';
import {backend} from './import-uploads/oracles.mjs';
// Extended only after the author publishes the exact SQL contract. No dynamic
// discovery allowlist: unknown public tables continue to fail the external exam.
export const tables=['economic_problem_links','economic_order_aliases','economic_order_customers','economic_relation_coverage'];
export const present=h=>tables.filter(table=>h.sql(`SELECT to_regclass(${q('public.'+table)}) IS NOT NULL`)==='t');
export function schema(h,fks){
 assert.deepEqual(present(h),tables,'EXPOSURE_TABLES_REQUIRED');
 for(const table of tables){
  assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'EXPOSURE_FORCE_RLS:'+table);
  assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','EXPOSURE_TENANT_NOT_NULL');
  for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),role==='vexa_backend'&&['SELECT','INSERT'].includes(action)?'t':'f','EXPOSURE_GRANT:'+table+role+action);
 }
 const expected=[['economic_problem_links','problems',{tenant_id:'tenant_id',problem_id:'id'}],['economic_problem_links','economic_ledger_entries',{tenant_id:'tenant_id',ledger_row_id:'id'}],['economic_problem_links','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],['economic_order_aliases','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],['economic_order_aliases','economic_ledger_entries',{tenant_id:'tenant_id',alias_row_id:'id'}],['economic_order_aliases','economic_ledger_entries',{tenant_id:'tenant_id',canonical_row_id:'id'}],['economic_order_customers','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],['economic_order_customers','economic_ledger_entries',{tenant_id:'tenant_id',order_row_id:'id'}],['economic_relation_coverage','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}]];
 const keys=fks.filter(k=>tables.includes(k.table));assert.equal(keys.length,expected.length,'EXPOSURE_FK_COUNT');for(const[table,parent,mapping]of expected)assert.ok(keys.some(k=>k.table===table&&k.parent===parent&&k.validated&&JSON.stringify(Object.entries(k.mapping).sort())===JSON.stringify(Object.entries(mapping).sort())),'EXPOSURE_COMPOSITE_FK:'+table+parent);
}
const context=(actor,tenant)=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('request.jwt.claims',${q(JSON.stringify({sub:actor.id,role:'authenticated'}))},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action','configure',true);`;
export function seed(h,f,actors){const out={};for(const side of ['a','b']){
 const tenant=f[side].problems.tenant_id,source={id:randomUUID(),tenant_id:tenant,source_id:randomUUID(),version:1,actor_id:actors[side].id,name:'SYN exposure order source '+side,evidence_type:'order_export',active:true,complete:true,window_start:'2026-01-01T00:00:00Z',window_end:'2026-02-01T00:00:00Z',watermark:'2026-02-01T00:00:00Z',report:'SYN independent financial order export for SQL authorization tests.',report_hash:'e'.repeat(64),attested:true};
 const order={id:randomUUID(),tenant_id:tenant,entity_id:randomUUID(),source_id:source.source_id,source_version:1,revision:1,actor_id:actors[side].id,external_id:'SYN-order-'+side,kind:'order',effective_at:'2026-01-02T00:00:00Z',currency:'USD',exponent:2,basis:'SYN-net-no-tax',amount_minor:'10000',status:'recorded',order_id:null,reversal_of:null,details:{},report:'SYN verified operational order without narrative inference.',report_hash:'f'.repeat(64),attested:true};
 const second={...order,id:randomUUID(),entity_id:randomUUID(),external_id:'SYN-second-'+side};
 const problem={id:randomUUID(),tenant_id:tenant,severity:'low',cause_status:'unknown'},version={id:randomUUID(),tenant_id:tenant,problem_id:problem.id,version:1,provenance:{kind:'vector-problem-v1',fixture:'SYN SQL authorization only; pipeline tested separately259'}};
 const common={tenant_id:tenant,version:1,actor_id:actors[side].id,report:'SYN explicit human-reviewed economic relation or identity.',attested:true};
 const link={...common,id:randomUUID(),problem_id:problem.id,entity_id:order.entity_id,ledger_row_id:order.id,active:true};
 const alias={...common,id:randomUUID(),alias_entity_id:second.entity_id,canonical_entity_id:order.entity_id,alias_row_id:second.id,canonical_row_id:order.id,active:true};
 const customer={...common,id:randomUUID(),entity_id:order.entity_id,order_row_id:order.id,customer_key:'SYN-customer-1'};
 const coverage={...common,id:randomUUID(),scope_key:'a'.repeat(64),input_hash:'b'.repeat(64),scope:{start:'2026-01-01T00:00:00Z',end:'2026-02-01T00:00:00Z',timezone:'UTC',dateBasis:'occurred_at',currency:'USD',exponent:2,basis:'SYN-net-no-tax'},complete:true};
 h.sql('BEGIN;'+context(actors[side],tenant)+insert('problems',problem)+';'+insert('problem_versions',version)+';'+insert('economic_source_versions',source)+';'+insert('economic_ledger_entries',order)+';'+insert('economic_ledger_entries',second)+';'+insert(tables[0],link)+';'+insert(tables[1],alias)+';'+insert(tables[2],customer)+';'+insert(tables[3],coverage)+';COMMIT;');
 out[side]={tenant,source,order,second,version,economic_problem_links:link,economic_order_aliases:alias,economic_order_customers:customer,economic_relation_coverage:coverage,economic_ledger_entries:order,problems:problem,memberships:{user_id:actors[side].id}};
 }return out;}
export function access(h,f,actors){for(const table of tables){const tenant=f.a.tenant,own=f.a[table],next={...own,id:randomUUID(),version:2},before=h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`);
 for(const actor of [null,...Object.values(actors)])denied(h.probe(read(table),actor),'EXPOSURE_DIRECT_DENIED');denied(h.probe('SET LOCAL ROLE service_role;'+read(table)),'EXPOSURE_SERVICE_DENIED');
 for(const who of ['a','analyst','operator','viewer','dual']){const r=backend(h,read(table),actors[who],tenant,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.id),[own.id],'EXPOSURE_OWN_READ:'+who);}
 for(const who of ['b','outsider'])denied(backend(h,read(table),actors[who],tenant,'read'),'EXPOSURE_FOREIGN_READ');denied(backend(h,read(table),actors.a,f.b.tenant,'read'),'EXPOSURE_FORGED_SELECTOR');
 const positive=backend(h,write(insert(table,next)),actors.a,tenant,'configure');assert.equal(positive.code,'00000','EXPOSURE_OWNER_POSITIVE:'+JSON.stringify(positive));assert.equal(positive.rows[0].affected,1);
 for(const who of ['analyst','operator','viewer','b','outsider']){const statement=write(insert(table,{...next,actor_id:actors[who].id}));denied(backend(h,statement,actors[who],tenant,'configure'),'EXPOSURE_OWNER_ONLY:'+who);denied(backend(h,statement,actors[who],tenant,'configure',`ALTER TABLE ${table} DISABLE TRIGGER USER;`),'EXPOSURE_RLS_INDEPENDENT:'+who);}
 denied(backend(h,write(insert(table,{...next,actor_id:actors.b.id})),actors.a,tenant,'configure'),'EXPOSURE_ACTOR_SPOOF');denied(backend(h,write(insert(table,next)),actors.a,tenant,'read'),'EXPOSURE_ACTION_FENCE');
 const revoked=`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`;
 denied(backend(h,read(table),actors.a,tenant,'read',revoked),'EXPOSURE_REVOKED_READ');denied(backend(h,write(insert(table,next)),actors.a,tenant,'configure',revoked),'EXPOSURE_REVOKED_WRITE');
 for(const operation of ['UPDATE','DELETE']){const statement=operation==='UPDATE'?`UPDATE ${table} SET report='SYN unauthorized immutable mutation attempt' WHERE id=${q(own.id)}`:`DELETE FROM ${table} WHERE id=${q(own.id)}`;denied(backend(h,write(statement),actors.a,tenant,'configure'),'EXPOSURE_APPEND_ONLY');assert.equal(h.probe(write(statement)).code,'42501','EXPOSURE_TRIGGER_APPEND_ADMIN');}
 assert.equal(h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`),before,'EXPOSURE_NO_PERSISTED_NEGATIVE_EFFECT');
}}
export function identity(h,f,actors){const tenant=f.a.tenant,run=(table,row,prepare='')=>backend(h,write(insert(table,row)),actors.a,tenant,'configure',prepare);
 for(const table of tables){const row={...f.a[table],id:randomUUID()};assert.equal(run(table,row).code,'40001','EXPOSURE_CAS_STALE:'+table);assert.equal(run(table,{...row,version:2}).code,'00000','EXPOSURE_NEXT_VERSION_POSITIVE:'+table);assert.equal(run(table,{...row,version:2,attested:false}).code,'23514','EXPOSURE_ATTESTATION_REQUIRED');}
 const link={...f.a.economic_problem_links,id:randomUUID(),version:2};assert.equal(run(tables[0],{...link,active:false}).code,'00000','EXPOSURE_APPEND_UNDO_POSITIVE');assert.equal(run(tables[0],{...link,entity_id:randomUUID(),version:1}).code,'23514','EXPOSURE_ENTITY_LEDGER_MATCH');
 const alias={...f.a.economic_order_aliases,id:randomUUID(),version:2};assert.equal(run(tables[1],{...alias,active:false}).code,'00000','EXPOSURE_ALIAS_UNDO_POSITIVE');assert.equal(run(tables[1],{...alias,canonical_entity_id:alias.alias_entity_id,canonical_row_id:alias.alias_row_id}).code,'23514','EXPOSURE_ALIAS_SELF_DENIED');
 const cycle={...alias,version:1,alias_entity_id:alias.canonical_entity_id,canonical_entity_id:alias.alias_entity_id,alias_row_id:alias.canonical_row_id,canonical_row_id:alias.alias_row_id};assert.equal(run(tables[1],cycle).code,'23514','EXPOSURE_ALIAS_CYCLE_DENIED');
 const newOrder={...f.a.order,id:randomUUID(),revision:2,amount_minor:'10001'},prepare=`PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(tenant)},true);PERFORM set_config('vexa.action','configure',true);`+insert('economic_ledger_entries',newOrder)+';';
 assert.equal(run(tables[1],{...alias,canonical_row_id:newOrder.id},prepare).code,'23514','EXPOSURE_ALIAS_FINANCIAL_MISMATCH');assert.equal(run(tables[0],link,prepare).code,'23514','EXPOSURE_STALE_LEDGER_REVISION');assert.equal(run(tables[0],{...link,ledger_row_id:newOrder.id},prepare).code,'00000','EXPOSURE_CURRENT_LEDGER_REVISION_POSITIVE');
 const customer={...f.a.economic_order_customers,id:randomUUID(),version:2};assert.equal(run(tables[2],{...customer,customer_key:null}).code,'00000','EXPOSURE_CUSTOMER_WITHDRAW_POSITIVE');assert.equal(run(tables[2],{...customer,customer_key:'   '}).code,'23514','EXPOSURE_CUSTOMER_BLANK_DENIED');
 const coverage={...f.a.economic_relation_coverage,id:randomUUID(),version:2};assert.equal(run(tables[3],{...coverage,complete:false}).code,'00000','EXPOSURE_COVERAGE_RETRACT_POSITIVE');for(const scope of [{},{...coverage.scope,start:null},{...coverage.scope,currency:null},{...coverage.scope,exponent:1.2},{...coverage.scope,start:'2026-02-30T00:00:00Z'},{...coverage.scope,end:coverage.scope.start},{...coverage.scope,extra:'unapproved'}])assert.equal(run(tables[3],{...coverage,scope}).code,'23514','EXPOSURE_COVERAGE_REQUIRES_COMPLETE_SCOPE');
}
export function contributor(h,f,actors){const tenant=f.a.tenant,foreign=f.b.tenant,signature='public.economic_contributor_active(uuid,uuid)',recordSig='public.economic_record_current(uuid,uuid,text[])';
 for(const [sig,definer]of [[signature,true],[recordSig,false]]){const p=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig,'stable',provolatile='s') FROM pg_proc WHERE oid=${q(sig)}::regprocedure`);assert.equal(p.definer,definer,'EXPOSURE_HELPER_DEFINER');assert.ok(p.config.includes('search_path=""'),'EXPOSURE_HELPER_SEARCH_PATH');assert.equal(p.stable,true);for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(sig)},'EXECUTE')`),role==='vexa_backend'?'t':'f','EXPOSURE_HELPER_GRANT');}
 const call=(target,actor)=>`SELECT jsonb_build_array(public.economic_contributor_active(${q(target)}::uuid,${q(actor)}::uuid)) INTO result;`,check=(who,target,actor,action,expected,prepare='')=>{const r=backend(h,call(target,actor),actors[who],tenant,action,prepare);assert.equal(r.code,'00000',JSON.stringify(r));assert.deepEqual(r.rows,[expected],'EXPOSURE_CONTRIBUTOR_SCOPE:'+who+action);};
 for(const who of ['a','analyst','operator','viewer','dual'])check(who,tenant,actors.a.id,'read',true);for(const who of ['b','outsider'])check(who,tenant,actors.a.id,'read',false);for(const action of ['','propose','approve','execute','worker_dispatch'])check('a',tenant,actors.a.id,action,false);check('a',tenant,actors.a.id,'import',h.sql("SELECT to_regclass('public.economic_snapshot_heads') IS NOT NULL")==='t');check('a',foreign,actors.b.id,'read',false);check('a',tenant,actors.b.id,'read',false);check('a',tenant,actors.viewer.id,'read',false);
 check('dual',tenant,actors.a.id,'read',false,`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`);check('dual',tenant,actors.a.id,'read',false,`UPDATE memberships SET role='analyst' WHERE user_id=${q(actors.a.id)};`);check('a',tenant,actors.dual.id,'read',false,`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`);
 const record=`SELECT jsonb_build_array(public.economic_record_current(${q(tenant)}::uuid,${q(f.a.order.id)}::uuid,array['order'])) INTO result;`;assert.deepEqual(backend(h,record,actors.dual,tenant,'read').rows,[true],'EXPOSURE_CURRENT_ORDER_POSITIVE');assert.deepEqual(backend(h,record,actors.dual,tenant,'read',`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`).rows,[false],'EXPOSURE_ORDER_CONTRIBUTOR_REVOKED');
 const sourceNext={...f.a.source,id:randomUUID(),version:2,actor_id:actors.dual.id};const sourcePrepare=`PERFORM set_config('request.jwt.claim.sub',${q(actors.dual.id)},true);PERFORM set_config('vexa.tenant_id',${q(tenant)},true);PERFORM set_config('vexa.action','configure',true);`+insert('economic_source_versions',sourceNext)+';';assert.deepEqual(backend(h,record,actors.a,tenant,'read',sourcePrepare).rows,[true],'EXPOSURE_SOURCE_CONTRIBUTOR_POSITIVE');assert.deepEqual(backend(h,record,actors.a,tenant,'read',sourcePrepare+`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(tenant)} AND user_id=${q(actors.dual.id)};`).rows,[false],'EXPOSURE_SOURCE_CONTRIBUTOR_REVOKED');
 for(const actor of [null,actors.a,actors.outsider])denied(h.probe(call(tenant,actors.a.id),actor),'EXPOSURE_HELPER_DIRECT_DENIED');denied(h.probe('SET LOCAL ROLE service_role;'+call(tenant,actors.a.id)),'EXPOSURE_HELPER_SERVICE_DENIED');
}
export function fk(h,f,key){const original=f.a[key.table],row={...original,id:randomUUID(),version:original.version+1},probe=r=>h.probe(`ALTER TABLE ${key.table} DISABLE TRIGGER USER;${write(insert(key.table,r))}SET CONSTRAINTS ALL IMMEDIATE;`);assert.equal(probe(row).code,'00000','EXPOSURE_FK_POSITIVE:'+key.name);const bad={...row};for(const[col,ref]of Object.entries(key.mapping))if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];const r=probe(bad);assert.equal(r.code,'23503','EXPOSURE_FK_CROSS:'+key.name);assert.ok(r.constraint,'EXPOSURE_FK_NAMED');}
