import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {q,insert} from './matrix.mjs';
import {write,denied} from './harness.mjs';
import {backend} from './import-uploads/oracles.mjs';
export const tables=['intervention_events','intervention_results'];
export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
export const ownsFk=k=>tables.includes(k.table)||k.table==='interventions'&&['plan_id','last_actor_id','result_id'].some(c=>c in k.mapping);
export function schema(h,fks){
 assert.deepEqual(present(h),tables,'INTERVENTION_HISTORY_RESULT_TABLES_REQUIRED');
 for(const table of [...tables,'interventions','measurement_plans'])assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'INTERVENTION_FORCE_RLS:'+table);
 for(const table of tables){assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','INTERVENTION_REQUIRED_TENANT');for(const role of ['anon','authenticated','service_role'])for(const op of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(op)})`),'f','INTERVENTION_PRIVATE_GRANT:'+table+role+op);for(const op of ['UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege('vexa_backend',${q('public.'+table)},${q(op)})`),'f','INTERVENTION_HISTORY_APPEND_ONLY:'+table+op);}
 const keys=fks.filter(ownsFk);assert.equal(keys.length,11,'INTERVENTION_ELEVEN_NEW_TENANT_FKS');for(const k of keys)assert.ok(k.validated&&(k.parent==='organizations'?k.mapping.tenant_id==='id':k.mapping.tenant_id==='tenant_id'),'INTERVENTION_TENANT_FK:'+k.name);
}
export function scopedHelpers(h,f,actors){
 const a=f.a;
 for(const [signature,args]of [['intervention_member(uuid,uuid,text[])',`${q(a.tenant)}::uuid,${q(actors.a.id)}::uuid,ARRAY['owner']`],['intervention_authorized(uuid,uuid)',`${q(a.tenant)}::uuid,${q(a.interventions.id)}::uuid`],['intervention_inputs_current(uuid,uuid,jsonb)',`${q(a.tenant)}::uuid,${q(a.metric_snapshots.id)}::uuid,${q(JSON.stringify(a.recommendations.evidence_refs))}::jsonb`]]){
  const name=signature.split('(')[0],sig='public.'+signature,meta=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q(sig)}::regprocedure`);assert.equal(meta.definer,true,'INTERVENTION_HELPER_DEFINER');assert.ok(meta.config.includes('search_path=""'),'INTERVENTION_HELPER_SEARCH_PATH');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(sig)},'EXECUTE')`),role==='vexa_backend'?'t':'f','INTERVENTION_HELPER_GRANT');
  const statement=`SELECT jsonb_build_array(public.${name}(${args})) INTO result;`;const positive=backend(h,statement,actors.a,a.tenant,'read');assert.equal(positive.code,'00000',JSON.stringify(positive));assert.deepEqual(positive.rows,[true],'INTERVENTION_HELPER_CURRENT_POSITIVE:'+name);
  for(const [actor,tenant,action]of [[actors.b,a.tenant,'read'],[actors.dual,f.b.tenant,'read'],[actors.a,a.tenant,'configure'],[actors.a,a.tenant,'materialize']]){const bad=backend(h,statement,actor,tenant,action);assert.equal(bad.code,'00000');assert.deepEqual(bad.rows,[false],'INTERVENTION_HELPER_CAPABILITY_TENANT:'+name);}
 }
}
export function projection(h,f,actors){
 const a=f.a,b=f.b,filters=a.workspace_scope_bindings.filters,mapping=a.workspace_order_dimension_versions.id;
 const statement=(patch={},mids=[mapping],sid=a.metric_snapshots.id,tenant=a.tenant)=>`SELECT jsonb_build_array(public.intervention_projection(${q(tenant)}::uuid,${q(sid)}::uuid,${q(JSON.stringify({...filters,...patch}))}::jsonb,'allOrders',ARRAY[${mids.map(x=>q(x)+'::uuid').join(',')}]::uuid[])) INTO result;`;
 const good=backend(h,statement(),actors.a,a.tenant,'read');assert.equal(good.code,'00000',JSON.stringify(good));assert.equal(good.rows[0].amountMinor,'10000','INTERVENTION_SCOPED_EXACT_POSITIVE');assert.equal(good.rows[0].denominator,1,'INTERVENTION_ORDER_DENOMINATOR');
 const excluded=backend(h,statement({sku:['SKU-Z']}),actors.a,a.tenant,'read');assert.equal(excluded.code,'00000',JSON.stringify(excluded));assert.equal(excluded.rows[0].amountMinor,'0','INTERVENTION_KNOWN_NONMATCH_ZERO');assert.equal(excluded.rows[0].denominator,0);
 for(const [who,tenant]of [['b',a.tenant],['outsider',a.tenant],['dual',b.tenant]])assert.notEqual(backend(h,statement(),actors[who],tenant,'read').code,'00000','INTERVENTION_PROJECTION_TENANT');
 assert.notEqual(backend(h,statement({},[b.workspace_order_dimension_versions.id]),actors.a,a.tenant,'read').code,'00000','INTERVENTION_FOREIGN_MAPPING');
 for(const action of ['configure','materialize','import'])assert.notEqual(backend(h,statement(),actors.a,a.tenant,action).code,'00000','INTERVENTION_PROJECTION_ACTION');
 const source={...a.source,id:randomUUID(),version:a.source.version+1,active:false};
 const prepare=`PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);PERFORM set_config('vexa.action','configure',true);${insert('economic_source_versions',source)};`;
 const setup=h.probe(prepare+"SELECT jsonb_build_array('withdrawn') INTO result;");assert.equal(setup.code,'00000','INTERVENTION_SOURCE_WITHDRAWAL_SETUP:'+JSON.stringify(setup));
 assert.notEqual(backend(h,statement(),actors.a,a.tenant,'read',prepare).code,'00000','INTERVENTION_PROJECTION_CURRENT_SOURCE_REQUIRED');
 const revoked=`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(a.tenant)} AND user_id=${q(actors.a.id)};`;
 assert.notEqual(backend(h,statement(),actors.dual,a.tenant,'read',revoked).code,'00000','INTERVENTION_PROJECTION_CURRENT_CONTRIBUTOR_REQUIRED');
}
const context=(actor,tenant,action)=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action',${q(action)},true);`;
const value=x=>x===null?'NULL':q(typeof x==='object'?JSON.stringify(x):String(x));
const update=(i,actor,patch)=>`UPDATE interventions SET ${Object.entries({version:i.version+1,last_actor_id:actor.id,last_request_key:randomUUID(),last_fingerprint:'1'.repeat(64),reason:'SYN independently verified operational transition.',...patch}).map(([k,v])=>k+'='+value(v)).join(',')} WHERE tenant_id=${q(i.tenant_id)} AND id=${q(i.id)}`;
export function seed(h,recs,actors){const out={};for(const side of ['a','b']){const a=recs[side],actor=actors[side],start=new Date(Date.now()+3600000).toISOString(),end=new Date(Date.now()+7200000).toISOString(),plan={hypothesis:'SYN operational change may alter observed order exposure.',ownerId:actor.id,start,end,unit:'order',population:'SYN orders containing SKU-X; captured scope only.',outcome:'allOrders',controlPlan:'SYN none; descriptive before-after association only.',metricDefinitionVersion:a.metric_snapshots.policy_version,baselineSnapshotId:a.metric_snapshots.id,scopeHash:a.workspace_scope_bindings.scope_hash,maturityDays:0,concurrentChanges:'SYN no known concurrent changes; not a causal claim.'},row={id:randomUUID(),tenant_id:a.tenant,version:1,unit:plan.unit,population_ref:plan.population,date_start:start,date_end:end,intervention_id:a.interventions.id,baseline_ref:plan.baselineSnapshotId,provenance:{plan}};
 const probe=backend(h,write(insert('measurement_plans',row)),actor,a.tenant,'propose');assert.equal(probe.code,'00000','INTERVENTION_PLAN_POSITIVE:'+JSON.stringify(probe));h.sql('BEGIN;'+context(actor,a.tenant,'propose')+insert('measurement_plans',row)+';'+update(a.interventions,actor,{plan_id:row.id,measurement_ref:row.id,owner_id:actor.id,hypothesis:plan.hypothesis})+';COMMIT;');
 out[side]={...a,measurement_plans:h.json(`SELECT to_jsonb(p) FROM measurement_plans p WHERE id=${q(row.id)}`),interventions:h.json(`SELECT to_jsonb(i) FROM interventions i WHERE id=${q(a.interventions.id)}`),memberships:{user_id:actor.id}};
 out[side].intervention_events=h.json(`SELECT to_jsonb(e) FROM intervention_events e WHERE intervention_id=${q(a.interventions.id)} ORDER BY version DESC LIMIT 1`);
 }return out;}
export function states(h,f,actors){const a=f.a,i=a.interventions,p=a.measurement_plans;
 const approve=(patch={},who='a')=>backend(h,write(update(i,actors[who],{status:'approved',...patch})),actors[who],a.tenant,'approve');
 assert.deepEqual(approve().rows,[{affected:1}],'INTERVENTION_OWNER_APPROVES_PLAN');for(const who of ['viewer','analyst','operator','b','outsider'])denied(approve({},who),'INTERVENTION_APPROVAL_ROLE:'+who);
 for(const patch of [{version:i.version},{version:i.version+2},{plan_id:f.b.measurement_plans.id},{owner_id:actors.b.id},{hypothesis:'SYN forged hypothesis sneaked into the approval transition.'},{measurement_ref:f.b.measurement_plans.id},{baseline_ref:f.b.metric_snapshots.id},{provenance:{...i.provenance,scopeHash:'f'.repeat(64)}},{last_actor_id:actors.operator.id},{last_request_key:null},{reason:''}])assert.notEqual(approve(patch).code,'00000','INTERVENTION_APPROVAL_CAS_IMMUTABLE:'+JSON.stringify(patch));
 for(const target of ['active','measuring','closed'])assert.notEqual(backend(h,write(update(i,actors.a,{status:target})),actors.a,a.tenant,'execute').code,'00000','INTERVENTION_NO_SKIPPED_STATE:'+target);
 const next={...p,id:randomUUID(),version:2};assert.equal(backend(h,write(insert('measurement_plans',next)),actors.a,a.tenant,'propose').code,'00000','INTERVENTION_DRAFT_PLAN_VERSION_APPEND');
 for(const patch of [{provenance:{plan:{...p.provenance.plan,baselineSnapshotId:f.b.metric_snapshots.id}},baseline_ref:f.b.metric_snapshots.id},{provenance:{plan:{...p.provenance.plan,scopeHash:'f'.repeat(64)}}},{provenance:{plan:{...p.provenance.plan,metricDefinitionVersion:'SYN-invalid'}}},{provenance:{plan:{...p.provenance.plan,hypothesis:null}}},{provenance:{plan:{...p.provenance.plan,controlPlan:null}}},{provenance:{plan:{...p.provenance.plan,population:null}}},{provenance:{plan:{...p.provenance.plan,outcome:null}}},{provenance:{plan:{...p.provenance.plan,unit:null}}}])assert.notEqual(backend(h,write(insert('measurement_plans',{...next,...patch})),actors.a,a.tenant,'propose').code,'00000','INTERVENTION_PLAN_MANDATORY_FIELDS:'+JSON.stringify(patch));
}
const hex=()=>randomUUID().replaceAll('-','').repeat(2);
function committed(h,actor,tenant,action,sql){h.sql('BEGIN;'+context(actor,tenant,action)+sql+';COMMIT;');}
function current(h,table,id){return h.json(`SELECT to_jsonb(x) FROM ${table} x WHERE id=${q(id)}`);}
function financialSnapshot(h,a,workspace,actor,start,end,amount){
 const t=a.tenant,source={...workspace.source,id:randomUUID(),source_id:randomUUID(),version:1,window_start:start,window_end:end,watermark:new Date(Math.min(Date.parse(end),Date.now()-1)).toISOString()};committed(h,actor,t,'configure',insert('economic_source_versions',source));
 const order={...workspace.economic_ledger_entries,id:randomUUID(),entity_id:randomUUID(),source_id:source.source_id,external_id:'SYN-intervention-'+randomUUID(),effective_at:new Date(Math.min((Date.parse(start)+Date.parse(end))/2,Date.now()-10)).toISOString(),amount_minor:amount};committed(h,actor,t,'configure',insert('economic_ledger_entries',order));
 const mapping={...workspace.workspace_order_dimension_versions,id:randomUUID(),ledger_row_id:order.id,skus:'{SKU-X}'};committed(h,actor,t,'configure',insert('workspace_order_dimension_versions',mapping));
 const scope={...workspace.metric_snapshots.provenance.scope,start,end},refs=[{table:'economic_source_versions',id:source.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hex()},{table:'economic_ledger_entries',id:order.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hex()}];
 const snap={...a.metric_snapshots,id:randomUUID(),input_hash:hex(),scope_hash:hex(),date_start:start,date_end:end,as_of:h.sql("SELECT to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')"),watermark:source.watermark,status:'draft',published_by:null,published_at:null,bundle_ref:null,content_hash:'0'.repeat(64),provenance:{...a.metric_snapshots.provenance,scope},input_manifest:{...a.metric_snapshots.input_manifest,refs,watermarks:[{sourceId:source.source_id,version:1,watermark:source.watermark,complete:true,active:true}],selection:{scope,fxRateId:null}}};
 const cs=workspace.components.map(c=>({...c,id:randomUUID(),snapshot_id:snap.id}));committed(h,actor,t,'import',insert('metric_snapshots',snap)+';'+cs.map(c=>insert('components',c)).join(';')+`;UPDATE metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id),status='published',published_at=clock_timestamp(),published_by=${q(actor.id)},bundle_ref='canonical:SYN-intervention' WHERE id=${q(snap.id)}`);
 return {snapshot:current(h,'metric_snapshots',snap.id),source,order,mapping};
}
export async function lifecycle(h,f,recs,workspaces,actors){for(const side of ['a','b']){const a=f[side],actor=actors[side],now=Date.now(),baseline=financialSnapshot(h,recs[side],workspaces[side],actor,new Date(now-5000).toISOString(),new Date(now-4000).toISOString(),'9007199254740993');
 const p={...a.measurement_plans,id:randomUUID(),version:2,baseline_ref:baseline.snapshot.id,provenance:{plan:{...a.measurement_plans.provenance.plan,baselineSnapshotId:baseline.snapshot.id}}};committed(h,actor,a.tenant,'propose',insert('measurement_plans',p)+';'+update(a.interventions,actor,{plan_id:p.id,measurement_ref:p.id}));let i=current(h,'interventions',a.interventions.id);committed(h,actor,a.tenant,'approve',update(i,actor,{status:'approved'}));i=current(h,'interventions',i.id);
 for(const patch of [{hypothesis:'SYN illegally rewritten hypothesis after approval.'},{plan_id:a.measurement_plans.id},{baseline_ref:f[side==='a'?'b':'a'].metric_snapshots.id},{actual_start:'2020-01-01T00:00:00Z'}])assert.notEqual(backend(h,write(update(i,actor,{status:'active',actual_start:new Date().toISOString(),...patch})),actor,a.tenant,'execute').code,'00000','INTERVENTION_APPROVED_IMMUTABLE');
 const start=new Date().toISOString();committed(h,actor,a.tenant,'execute',update(i,actor,{status:'active',actual_start:start}));i=current(h,'interventions',i.id);committed(h,actor,a.tenant,'execute',update(i,actor,{status:'measuring',actual_end:new Date().toISOString()}));i=current(h,'interventions',i.id);
 assert.notEqual(backend(h,write(update(i,actor,{status:'closed'})),actor,a.tenant,'execute').code,'00000','INTERVENTION_CLOSE_REQUIRES_RESULT');
 const resultRow={id:randomUUID(),tenant_id:a.tenant,intervention_id:i.id,plan_id:p.id,post_snapshot_id:baseline.snapshot.id,actor_id:actor.id};assert.notEqual(backend(h,write(insert('intervention_results',resultRow)),actor,a.tenant,'execute').code,'00000','INTERVENTION_POST_BEFORE_EXECUTION_DENIED');
 const postStart=Date.now()+150,postEnd=postStart+1000;await new Promise(resolve=>setTimeout(resolve,Math.max(0,postEnd-Date.now()+30)));const post=financialSnapshot(h,recs[side],workspaces[side],actor,new Date(postStart).toISOString(),new Date(postEnd).toISOString(),'9007199254741000');resultRow.post_snapshot_id=post.snapshot.id;
 const positive=backend(h,insert('intervention_results',{...resultRow,result:{deltaMinor:'999999999',causallyAttributedIncrementalMargin:'999'}})+`;SELECT jsonb_build_array(ir.result) INTO result FROM intervention_results ir WHERE id=${q(resultRow.id)};`,actor,a.tenant,'execute');assert.equal(positive.code,'00000','INTERVENTION_REAL_MEASUREMENT_POSITIVE:'+JSON.stringify(positive));assert.equal(positive.rows[0].baselineAmountMinor,'9007199254740993','INTERVENTION_EXACT_BASELINE');assert.equal(positive.rows[0].postAmountMinor,'9007199254741000','INTERVENTION_EXACT_POST');assert.equal(positive.rows[0].deltaMinor,'7','INTERVENTION_EXACT_DELTA_NOT_CALLER');assert.equal(positive.rows[0].causallyAttributedIncrementalMargin,null,'INTERVENTION_NO_CAUSAL_SAVINGS');assert.equal(positive.rows[0].interpretation,'association-not-causal-savings');
 committed(h,actor,a.tenant,'execute',insert('intervention_results',resultRow)+';'+update(i,actor,{result_id:resultRow.id}));i=current(h,'interventions',i.id);const before=h.sql(`SELECT count(*) FROM intervention_events WHERE intervention_id=${q(i.id)}`);const close=backend(h,update(i,actor,{status:'closed'})+`;SELECT jsonb_build_array(status) INTO result FROM interventions WHERE id=${q(i.id)};`,actor,a.tenant,'execute');assert.equal(close.code,'00000','INTERVENTION_VALID_CLOSE:'+JSON.stringify(close));assert.deepEqual(close.rows,['closed']);assert.equal(h.sql(`SELECT count(*) FROM intervention_events WHERE intervention_id=${q(i.id)}`),before,'INTERVENTION_PROBE_ATOMIC_ROLLBACK');
 Object.assign(a,{interventions:i,measurement_plans:current(h,'measurement_plans',p.id),intervention_results:current(h,'intervention_results',resultRow.id),intervention_events:h.json(`SELECT to_jsonb(x) FROM intervention_events x WHERE intervention_id=${q(i.id)} ORDER BY version DESC LIMIT 1`),post_snapshot:post.snapshot,baseline_snapshot:baseline.snapshot,baselineFixture:baseline,postFixture:post});
 }return f;}
const only=(table,id)=>`SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') INTO result FROM ${table} x WHERE id=${q(id)};`;
export function access(h,f,actors){const a=f.a;for(const table of tables){const stmt=only(table,a[table].id);for(const who of [null,...Object.values(actors)])denied(h.probe(stmt,who),'INTERVENTION_BROWSER_PRIVATE');denied(h.probe('SET LOCAL ROLE service_role;'+stmt),'INTERVENTION_SERVICE_PRIVATE');for(const who of ['a','dual','viewer','analyst','operator']){const r=backend(h,stmt,actors[who],a.tenant,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.id),[a[table].id],'INTERVENTION_CURRENT_MEMBER_READ');}for(const who of ['b','outsider'])denied(backend(h,stmt,actors[who],a.tenant,'read'),'INTERVENTION_FOREIGN');denied(backend(h,stmt,actors.dual,f.b.tenant,'read'),'INTERVENTION_SELECTED_TENANT');for(const action of ['propose','approve','execute','configure','retain'])for(const op of ['UPDATE','DELETE'])denied(backend(h,write(op==='UPDATE'?`UPDATE ${table} SET id=id WHERE id=${q(a[table].id)}`:`DELETE FROM ${table} WHERE id=${q(a[table].id)}`),actors.a,a.tenant,action),'INTERVENTION_AUDIT_IMMUTABLE');}
 const fresh={...a.intervention_results,id:randomUUID()};for(const who of ['viewer','analyst','operator','b','outsider'])assert.notEqual(backend(h,write(insert('intervention_results',{...fresh,actor_id:actors[who].id})),actors[who],a.tenant,'execute').code,'00000','INTERVENTION_RESULT_EXECUTOR_ONLY');for(const action of ['read','propose','approve','configure','materialize','import'])assert.notEqual(backend(h,write(insert('intervention_results',fresh)),actors.a,a.tenant,action).code,'00000','INTERVENTION_RESULT_CAPABILITY_ONLY');
 for(const patch of [{post_snapshot_id:f.b.post_snapshot.id},{intervention_id:f.b.interventions.id},{plan_id:f.b.measurement_plans.id},{actor_id:actors.operator.id}])assert.notEqual(backend(h,write(insert('intervention_results',{...fresh,...patch})),actors.a,a.tenant,'execute').code,'00000','INTERVENTION_RESULT_FOREIGN_REF');
}
export function fk(h,f,k){const row=f.a[k.table],probe=patch=>h.probe(`ALTER TABLE ${k.table} DISABLE TRIGGER USER;${write(`UPDATE ${k.table} SET ${Object.entries(patch).map(([c,v])=>c+'='+value(v)).join(',')} WHERE id=${q(row.id)}`)}SET CONSTRAINTS ALL IMMEDIATE;`),same=Object.fromEntries(Object.keys(k.mapping).map(c=>[c,row[c]]));const good=probe(same);assert.equal(good.code,'00000','INTERVENTION_FK_POSITIVE:'+k.name+JSON.stringify(good));const bad={...same};for(const [col,parent]of Object.entries(k.mapping))if(k.parent==='organizations')bad[col]=randomUUID();else if(col!=='tenant_id')bad[col]=f.b[k.parent][parent];const no=probe(bad);assert.equal(no.code,'23503','INTERVENTION_FK_FOREIGN:'+k.name+JSON.stringify(no));assert.ok(no.constraint);}
export function partial(h,f,recs,workspaces,actors){const a=f.a,actor=actors.a,i=a.interventions,post=financialSnapshot(h,recs.a,workspaces.a,actor,a.post_snapshot.date_start,a.post_snapshot.date_end,null),row={id:randomUUID(),tenant_id:a.tenant,intervention_id:i.id,plan_id:i.plan_id,post_snapshot_id:post.snapshot.id,actor_id:actor.id};
 const result=backend(h,insert('intervention_results',row)+`;SELECT jsonb_build_array(r.result) INTO result FROM intervention_results r WHERE r.id=${q(row.id)};`,actor,a.tenant,'execute');assert.equal(result.code,'00000','INTERVENTION_PARTIAL_PERSISTIBLE:'+JSON.stringify(result));assert.equal(result.rows[0].postAmountMinor,null,'INTERVENTION_UNKNOWN_NOT_ZERO');assert.equal(result.rows[0].deltaMinor,null,'INTERVENTION_UNKNOWN_NO_DELTA');assert.equal(result.rows[0].postKnownSubtotalMinor,'0');assert.equal(result.rows[0].status,'partial');assert.ok(result.rows[0].reasons.includes('COVERAGE_INCOMPLETE'));assert.equal(result.rows[0].causallyAttributedIncrementalMargin,null);
 const attempt=insert('intervention_results',row)+';'+update(i,actor,{result_id:row.id})+';'+update({...i,version:i.version+1,result_id:row.id},actor,{status:'closed'});assert.notEqual(backend(h,write(attempt),actor,a.tenant,'execute').code,'00000','INTERVENTION_PARTIAL_CANNOT_CLOSE');
 const future=financialSnapshot(h,recs.a,workspaces.a,actor,new Date(a.post_snapshot.date_start).toISOString(),new Date(Date.now()+86400000).toISOString(),'10000');const immature=backend(h,`SELECT jsonb_build_array(public.intervention_result_compute(${q(a.tenant)}::uuid,${q(i.id)}::uuid,${q(future.snapshot.id)}::uuid)) INTO result;`,actor,a.tenant,'read');assert.equal(immature.code,'00000',JSON.stringify(immature));assert.equal(immature.rows[0].deltaMinor,null);assert.ok(immature.rows[0].reasons.includes('OBSERVATION_IMMATURE'),'INTERVENTION_MATURITY_EXPLICIT');
}
export function reopen(h,f,actors){const a=f.a,i=a.interventions,actor=actors.a,close=update(i,actor,{status:'closed'}),closed={...i,status:'closed',version:i.version+1},opening=update(closed,actor,{status:'measuring',result_id:null});
 const flow=close+`;PERFORM set_config('vexa.action','approve',true);`+opening;
 const positive=backend(h,flow+`;SELECT jsonb_build_array(status,result_id,plan_id,approval_content) INTO result FROM interventions WHERE id=${q(i.id)};`,actor,a.tenant,'execute');assert.equal(positive.code,'00000','INTERVENTION_REOPEN_OWNER_POSITIVE:'+JSON.stringify(positive));assert.equal(positive.rows[0],'measuring');assert.equal(positive.rows[1],null);assert.equal(positive.rows[2],i.plan_id);assert.deepEqual(positive.rows[3],i.approval_content,'INTERVENTION_REOPEN_ORIGINAL_APPROVAL');
 const reopened={...i,status:'measuring',version:i.version+2,result_id:null};assert.notEqual(backend(h,flow+`;PERFORM set_config('vexa.action','execute',true);`+write(update(reopened,actor,{status:'closed'})),actor,a.tenant,'execute').code,'00000','INTERVENTION_REOPEN_NEEDS_NEW_MEASUREMENT');
 const reuse=flow+`;PERFORM set_config('vexa.action','execute',true);`+update(reopened,actor,{result_id:i.result_id})+';'+write(update({...reopened,version:reopened.version+1,result_id:i.result_id},actor,{status:'closed'}));assert.notEqual(backend(h,reuse,actor,a.tenant,'execute').code,'00000','INTERVENTION_REOPEN_CANNOT_REUSE_OLD_RESULT');
 const fresh={...a.intervention_results,id:randomUUID(),actor_id:actor.id,measurement_cycle:0},newFlow=flow+`;PERFORM set_config('vexa.action','execute',true);`+insert('intervention_results',fresh)+';'+update(reopened,actor,{result_id:fresh.id})+';'+update({...reopened,version:reopened.version+1,result_id:fresh.id},actor,{status:'closed'})+`;SELECT jsonb_build_array(i.status,r.measurement_cycle,i.measurement_cycle) INTO result FROM interventions i JOIN intervention_results r ON r.tenant_id=i.tenant_id AND r.id=i.result_id WHERE i.id=${q(i.id)};`;const positiveFresh=backend(h,newFlow,actor,a.tenant,'execute');assert.equal(positiveFresh.code,'00000','INTERVENTION_REOPEN_NEW_RESULT_CAN_CLOSE:'+JSON.stringify(positiveFresh));assert.equal(positiveFresh.rows[0],'closed');assert.equal(positiveFresh.rows[1],positiveFresh.rows[2]);assert.ok(positiveFresh.rows[1]>i.measurement_cycle,'INTERVENTION_CYCLE_DATABASE_OWNED');
 assert.notEqual(backend(h,write(update(i,actor,{measurement_cycle:99})),actor,a.tenant,'execute').code,'00000','INTERVENTION_CALLER_CANNOT_FORGE_CYCLE');

}
export function financialCalibration(h,f,actors){const a=f.a,sql=`SELECT jsonb_build_array(public.intervention_result_compute(${q(a.tenant)}::uuid,${q(a.interventions.id)}::uuid,${q(a.post_snapshot.id)}::uuid)) INTO result;`,oracle=()=>{const r=backend(h,sql,actors.a,a.tenant,'read');assert.equal(r.code,'00000',JSON.stringify(r));assert.equal(r.rows[0].deltaMinor,'7','INTERVENTION_EXACT_DELTA_MUTANT');};const original=h.sql("SELECT pg_get_functiondef('public.intervention_result_compute(uuid,uuid,uuid)'::regprocedure)");const site="delta=(after_metric->>'amountMinor')::numeric-(before_metric->>'amountMinor')::numeric";assert.ok(original.includes(site),'INTERVENTION_DELTA_MUTANT_SITE');oracle();h.sql(original.replace(site,'delta=0'));try{assert.throws(oracle,e=>e.code==='ERR_ASSERTION'&&e.message.includes('INTERVENTION_EXACT_DELTA_MUTANT'),'INTERVENTION_DELTA_MUTANT_SEMANTIC_KILL');}finally{h.sql(original);}oracle();}
export function assignment(h,f,actors){const a=f.a,actor=actors.a,operator=actors.operator;let i=a.interventions;committed(h,actor,a.tenant,'approve',update(i,actor,{owner_id:operator.id}));i=current(h,'interventions',i.id);const result={...a.intervention_results,id:randomUUID(),actor_id:operator.id};committed(h,operator,a.tenant,'execute',insert('intervention_results',result)+';'+update(i,operator,{result_id:result.id}));i=current(h,'interventions',i.id);
 const revoke=`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(a.tenant)} AND user_id=${q(operator.id)};`,reassignment=update(i,actor,{owner_id:actors.dual.id});const good=backend(h,reassignment+`;SELECT jsonb_build_array(owner_id,approval_content,plan_id) INTO result FROM interventions WHERE id=${q(i.id)};`,actor,a.tenant,'approve',revoke);assert.equal(good.code,'00000','INTERVENTION_REMOVED_OPERATOR_CAN_BE_REASSIGNED:'+JSON.stringify(good));assert.equal(good.rows[0],actors.dual.id);assert.equal(good.rows[2],i.plan_id);assert.deepEqual(good.rows[1],i.approval_content,'INTERVENTION_REASSIGN_APPROVAL_FIXED');
 denied(backend(h,write(update(i,operator,{status:'closed'})),operator,a.tenant,'execute',revoke),'INTERVENTION_REVOKED_OPERATOR_CANNOT_EXECUTE');
 const source={...a.source,id:randomUUID(),version:a.source.version+1,active:false};const withdrawal=`PERFORM set_config('request.jwt.claim.sub',${q(actor.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);PERFORM set_config('vexa.action','configure',true);${insert('economic_source_versions',source)};`;
 const bad=backend(h,write(reassignment),actor,a.tenant,'approve',withdrawal);assert.ok(bad.code!=='00000'||bad.rows.length===0,'INTERVENTION_REASSIGN_CANNOT_REHABILITATE_WITHDRAWN_EVIDENCE');
 committed(h,actor,a.tenant,'approve',update(i,actor,{owner_id:actor.id}));a.interventions=current(h,'interventions',i.id);a.intervention_results=current(h,'intervention_results',result.id);a.intervention_events=h.json(`SELECT to_jsonb(x) FROM intervention_events x WHERE intervention_id=${q(i.id)} ORDER BY version DESC LIMIT 1`);
}
function refundSnapshot(h,f,workspaces,actor,unknown){const a=f.a,post=a.postFixture,source={...post.source,id:randomUUID(),source_id:randomUUID(),evidence_type:'payment_ledger',name:'SYN actual refund settlement ledger'};committed(h,actor,a.tenant,'configure',insert('economic_source_versions',source));const refund={...post.order,id:randomUUID(),entity_id:randomUUID(),source_id:source.source_id,external_id:'SYN-refund-'+randomUUID(),kind:'refund',status:'settled',amount_minor:'2000',order_id:post.order.entity_id},reversal={...refund,id:randomUUID(),entity_id:randomUUID(),external_id:'SYN-reversal-'+randomUUID(),kind:'reversal',status:unknown?'unknown':'settled',amount_minor:unknown?null:'-500',order_id:null,reversal_of:refund.entity_id};committed(h,actor,a.tenant,'configure',insert('economic_ledger_entries',refund)+';'+insert('economic_ledger_entries',reversal));
 const ref=(table,row)=>({table,id:row.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hex()}),snap={...post.snapshot,id:randomUUID(),input_hash:hex(),status:'draft',published_by:null,published_at:null,bundle_ref:null,content_hash:'0'.repeat(64),as_of:new Date().toISOString(),input_manifest:{...post.snapshot.input_manifest,refs:[...post.snapshot.input_manifest.refs,ref('economic_source_versions',source),ref('economic_ledger_entries',refund),ref('economic_ledger_entries',reversal)],watermarks:[...post.snapshot.input_manifest.watermarks,{sourceId:source.source_id,version:1,watermark:source.watermark,complete:true,active:true}]}};const cs=workspaces.a.components.map(c=>({...c,id:randomUUID(),snapshot_id:snap.id}));committed(h,actor,a.tenant,'import',insert('metric_snapshots',snap)+';'+cs.map(c=>insert('components',c)).join(';')+`;UPDATE metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id),status='published',published_at=clock_timestamp(),published_by=${q(actor.id)},bundle_ref='canonical:SYN-refund-measurement' WHERE id=${q(snap.id)}`);return snap;}
export function refunds(h,f,workspaces,actors){const a=f.a,query=sid=>backend(h,`SELECT jsonb_build_array(public.intervention_projection(${q(a.tenant)}::uuid,${q(sid)}::uuid,${q(JSON.stringify(a.measurement_plans.provenance.filters))}::jsonb,'refunds',ARRAY[${q(a.postFixture.mapping.id)}::uuid])) INTO result;`,actors.a,a.tenant,'read');const known=refundSnapshot(h,f,workspaces,actors.a,false),x=query(known.id);assert.equal(x.code,'00000','INTERVENTION_REFUND_PROJECTION:'+JSON.stringify(x));assert.equal(x.rows[0].amountMinor,'1500','INTERVENTION_REFUND_NET_OF_REVERSAL');assert.equal(x.rows[0].knownSubtotalMinor,'1500');assert.equal(x.rows[0].totalCount,1,'INTERVENTION_REVERSAL_NOT_EXTRA_REFUND_OBSERVATION');const unknown=refundSnapshot(h,f,workspaces,actors.a,true),y=query(unknown.id);assert.equal(y.code,'00000');assert.equal(y.rows[0].amountMinor,null,'INTERVENTION_UNKNOWN_REVERSAL_NOT_FULL_REFUND');assert.equal(y.rows[0].knownSubtotalMinor,null,'INTERVENTION_UNKNOWN_REVERSAL_BLOCKS_SUBTOTAL');}

export function mappingAuthorization(h,f,actors){
 const a=f.a,t=a.tenant,owner=actors.a,other=actors.dual;
 const context=(actor,action)=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('vexa.tenant_id',${q(t)},true),set_config('vexa.action',${q(action)},true);`;
 const m={...a.postFixture.mapping,id:randomUUID(),version:2,actor_id:other.id};h.sql('BEGIN;'+context(other,'configure')+insert('workspace_order_dimension_versions',m)+';COMMIT;');
 const result={id:randomUUID(),tenant_id:t,intervention_id:a.interventions.id,plan_id:a.measurement_plans.id,post_snapshot_id:a.post_snapshot.id,actor_id:owner.id};h.sql('BEGIN;'+context(owner,'execute')+insert('intervention_results',result)+`;UPDATE interventions SET version=version+1,result_id=${q(result.id)},last_actor_id=${q(owner.id)},last_request_key=${q(randomUUID())},last_fingerprint='${'3'.repeat(64)}',reason='SYN new canonical measurement with independently attested dimension.' WHERE id=${q(a.interventions.id)};COMMIT;`);
 const read=`SELECT coalesce(jsonb_agg(to_jsonb(r)),'[]') INTO result FROM intervention_results r WHERE id=${q(result.id)};`;
 const positive=backend(h,read,owner,t,'read');assert.equal(positive.code,'00000');assert.equal(positive.rows[0].id,result.id);assert.deepEqual(positive.rows[0].result.postProjection.mappingIds,[m.id]);
 const signature='public.intervention_result_mappings_current(uuid,jsonb)',meta=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q(signature)}::regprocedure`);assert.equal(meta.definer,true);assert.ok(meta.config.includes('search_path=""'),'INTERVENTION_MAPPING_HELPER_SEARCH_PATH');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(signature)},'EXECUTE')`),role==='vexa_backend'?'t':'f','INTERVENTION_MAPPING_HELPER_GRANT');
 const body=positive.rows[0].result,call=body=>`SELECT jsonb_build_array(public.intervention_result_mappings_current(${q(t)}::uuid,${q(JSON.stringify(body))}::jsonb)) INTO result;`,revoke=`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(t)} AND user_id=${q(other.id)};`;
 for(const [actor,tenant,action]of [[actors.b,t,'read'],[actors.dual,f.b.tenant,'read'],[owner,t,'configure'],[owner,t,'materialize']]){const bad=backend(h,call(body),actor,tenant,action);assert.equal(bad.code,'00000');assert.deepEqual(bad.rows,[false],'INTERVENTION_MAPPING_HELPER_SCOPED');}
 const swapped={...body,baselineSnapshotId:body.postSnapshotId,baselineProjection:body.postProjection,postSnapshotId:body.baselineSnapshotId,postProjection:body.baselineProjection};assert.deepEqual(backend(h,call(swapped),owner,t,'read').rows,[true],'INTERVENTION_BASELINE_MAPPING_POSITIVE');assert.deepEqual(backend(h,call(swapped),owner,t,'read',revoke).rows,[false],'INTERVENTION_REVOKED_BASELINE_MAPPING');
 for(const status of ['measuring','closed']){const stmt=write(`UPDATE interventions SET version=version+1,status=${q(status)},result_id=${q(result.id)},last_actor_id=${q(owner.id)},last_request_key=${q(randomUUID())},last_fingerprint='${'4'.repeat(64)}',reason='SYN mutation must not certify revoked financial mapping evidence.' WHERE id=${q(a.interventions.id)}`),bad=backend(h,stmt,owner,t,'execute',revoke);assert.ok(bad.code==='42501'||bad.code==='00000'&&bad.rows.length===0,'INTERVENTION_REVOKED_MAPPING_MUTATION:'+status+JSON.stringify(bad));}
 const denied=backend(h,read,owner,t,'read',`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(t)} AND user_id=${q(other.id)};`);assert.ok(denied.code==='42501'||denied.code==='00000'&&denied.rows.length===0,'INTERVENTION_REVOKED_MAPPING_RESULT_LEAK:'+JSON.stringify({code:denied.code,rows:denied.rows?.map(x=>x.id)}));
 a.interventions=current(h,'interventions',a.interventions.id);a.intervention_results=current(h,'intervention_results',result.id);
}
