import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {q,insert} from './matrix.mjs';
import {read,write,denied} from './harness.mjs';
import {backend} from './import-uploads/oracles.mjs';
export const tables=['economic_currency_versions','economic_fx_versions'];
export const present=h=>tables.filter(table=>h.sql(`SELECT to_regclass(${q('public.'+table)}) IS NOT NULL`)==='t');
export function schema(h,fks){
 assert.deepEqual(present(h),tables,'MONEY_TABLES_REQUIRED');
 for(const table of tables){
  assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'MONEY_FORCE_RLS:'+table);
  assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','MONEY_TENANT_NOT_NULL');
  for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),role==='vexa_backend'&&['SELECT','INSERT'].includes(action)?'t':'f','MONEY_GRANT:'+table+role+action);
 }
 const expected=[['economic_currency_versions','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],['economic_fx_versions','memberships',{tenant_id:'tenant_id',actor_id:'user_id'}],['economic_fx_versions','economic_currency_versions',{tenant_id:'tenant_id',base_catalog_id:'id'}],['economic_fx_versions','economic_currency_versions',{tenant_id:'tenant_id',quote_catalog_id:'id'}]];
 const keys=fks.filter(k=>tables.includes(k.table));assert.equal(keys.length,expected.length,'MONEY_FK_COUNT');for(const[table,parent,mapping]of expected)assert.ok(keys.some(k=>k.table===table&&k.parent===parent&&k.validated&&JSON.stringify(Object.entries(k.mapping).sort())===JSON.stringify(Object.entries(mapping).sort())),'MONEY_COMPOSITE_FK:'+table+parent);
 const signature='public.economic_money_config_guard()';const fn=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q(signature)}::regprocedure`);assert.equal(fn.definer,false,'MONEY_NO_PRIVILEGE_BYPASS');assert.ok(fn.config.includes('search_path=""'),'MONEY_SEARCH_PATH');for(const role of ['anon','authenticated','service_role'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(signature)},'EXECUTE')`),'f','MONEY_GUARD_EXECUTE');
}
const context=(actor,tenant)=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('request.jwt.claims',${q(JSON.stringify({sub:actor.id,role:'authenticated'}))},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action','configure',true);`;
export function seed(h,f,actors){const out={};for(const side of ['a','b']){
 const tenant=f[side].problems.tenant_id,common={tenant_id:tenant,version:1,active:true,actor_id:actors[side].id,source:'SYN independent rate publication',reference:'SYN manual approval reference',effective_date:'2026-01-01',report:'SYN owner approved catalog and exact rate; not a live market quote.',attested:true};
 const usd={...common,id:randomUUID(),currency:'USD',exponent:2},mxn={...common,id:randomUUID(),currency:'MXN',exponent:2};
 const rate={...common,id:randomUUID(),rate_id:randomUUID(),base:'USD',quote:'MXN',base_catalog_id:usd.id,quote_catalog_id:mxn.id,rate:'17.125',rounding:'half_even'};
 h.sql('BEGIN;'+context(actors[side],tenant)+insert(tables[0],usd)+';'+insert(tables[0],mxn)+';'+insert(tables[1],rate)+';COMMIT;');
 out[side]={tenant,usd,mxn,economic_currency_versions:usd,economic_fx_versions:rate,memberships:{user_id:actors[side].id}};
 }return out;}
export function access(h,f,actors){for(const table of tables){const tenant=f.a.tenant,own=f.a[table],next={...own,id:randomUUID(),version:2},before=h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`),expected=table===tables[0]?[f.a.usd.id,f.a.mxn.id].sort():[own.id];
 for(const actor of [null,...Object.values(actors)])denied(h.probe(read(table),actor),'MONEY_DIRECT_DENIED');denied(h.probe('SET LOCAL ROLE service_role;'+read(table)),'MONEY_SERVICE_DENIED');
 for(const who of ['a','analyst','operator','viewer','dual']){const r=backend(h,read(table),actors[who],tenant,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.id).sort(),expected,'MONEY_OWN_READ:'+who);}
 for(const who of ['b','outsider'])denied(backend(h,read(table),actors[who],tenant,'read'),'MONEY_FOREIGN_READ');denied(backend(h,read(table),actors.a,f.b.tenant,'read'),'MONEY_FORGED_SELECTOR');
 const positive=backend(h,write(insert(table,next)),actors.a,tenant,'configure');assert.equal(positive.code,'00000','MONEY_OWNER_POSITIVE:'+JSON.stringify(positive));assert.equal(positive.rows[0].affected,1);
 for(const who of ['analyst','operator','viewer','b','outsider']){const statement=write(insert(table,{...next,actor_id:actors[who].id}));denied(backend(h,statement,actors[who],tenant,'configure'),'MONEY_OWNER_ONLY:'+who);denied(backend(h,statement,actors[who],tenant,'configure',`ALTER TABLE ${table} DISABLE TRIGGER USER;`),'MONEY_RLS_INDEPENDENT:'+who);}
 denied(backend(h,write(insert(table,{...next,actor_id:actors.b.id})),actors.a,tenant,'configure'),'MONEY_ACTOR_SPOOF');denied(backend(h,write(insert(table,next)),actors.a,tenant,'read'),'MONEY_ACTION_FENCE');
 const revoked=`UPDATE memberships SET status='revoked' WHERE user_id=${q(actors.a.id)};`;denied(backend(h,read(table),actors.a,tenant,'read',revoked),'MONEY_REVOKED_READ');denied(backend(h,write(insert(table,next)),actors.a,tenant,'configure',revoked),'MONEY_REVOKED_WRITE');
 for(const operation of ['UPDATE','DELETE']){const statement=operation==='UPDATE'?`UPDATE ${table} SET report='SYN unauthorized immutable mutation attempt' WHERE id=${q(own.id)}`:`DELETE FROM ${table} WHERE id=${q(own.id)}`;denied(backend(h,write(statement),actors.a,tenant,'configure'),'MONEY_APPEND_ONLY');assert.equal(h.probe(write(statement)).code,'42501','MONEY_TRIGGER_APPEND_ADMIN');}
 assert.equal(h.sql(`SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM ${table} r`),before,'MONEY_NO_PERSISTED_NEGATIVE_EFFECT');
}}
export function versions(h,f,actors){const tenant=f.a.tenant,run=(table,row,prepare='',actor=actors.a)=>backend(h,write(insert(table,row)),actor,tenant,'configure',prepare);
 for(const table of tables){const row={...f.a[table],id:randomUUID()};assert.equal(run(table,row).code,'40001','MONEY_CAS_STALE');assert.equal(run(table,{...row,version:3}).code,'40001','MONEY_VERSION_NO_GAPS');assert.equal(run(table,{...row,version:2}).code,'00000','MONEY_NEXT_VERSION_POSITIVE');assert.equal(run(table,{...row,version:2,active:false}).code,'00000','MONEY_WITHDRAW_APPEND');for(const patch of [{attested:false},{report:'short'},{source:' '},{reference:' '},{effective_date:'2099-01-01'},{effective_date:'-infinity'}])assert.equal(run(table,{...row,version:2,...patch}).code,'23514','MONEY_PROVENANCE_VALIDATION:'+JSON.stringify(patch));}
 const curr={...f.a.usd,id:randomUUID(),version:2};for(const exponent of [-1,5])assert.equal(run(tables[0],{...curr,exponent}).code,'23514','MONEY_EXPONENT_RANGE');assert.equal(run(tables[0],{...curr,currency:'usd',version:1}).code,'23514','MONEY_CURRENCY_CODE');
 const rate={...f.a.economic_fx_versions,id:randomUUID(),version:2};for(const value of ['0','-1','NaN','1e2','1.' ,'0.'+'1'.repeat(37)])assert.equal(run(tables[1],{...rate,rate:value}).code,'23514','MONEY_RATE_INVALID:'+value);for(const rounding of ['ceil',''])assert.equal(run(tables[1],{...rate,rounding}).code,'23514','MONEY_ROUNDING_EXPLICIT');
 assert.equal(run(tables[1],{...rate,base:'MXN',quote:'USD',base_catalog_id:f.a.mxn.id,quote_catalog_id:f.a.usd.id}).code,'23514','MONEY_PAIR_IMMUTABLE');assert.equal(run(tables[1],{...rate,base_catalog_id:f.a.mxn.id}).code,'23514','MONEY_CATALOG_CURRENCY_MATCH');assert.equal(run(tables[1],{...rate,quote:'USD',quote_catalog_id:f.a.usd.id}).code,'23514','MONEY_DISTINCT_CURRENCIES');
 const exact='9007199254740993.123456789012345678901234567890123456';const result=backend(h,`${insert(tables[1],{...rate,rate:exact})} RETURNING jsonb_build_array(rate) INTO result;`,actors.a,tenant,'configure');assert.equal(result.code,'00000',JSON.stringify(result));assert.deepEqual(result.rows,[exact],'MONEY_RATE_NO_FLOAT_OR_ROUNDING');
 const prepare=row=>`PERFORM set_config('request.jwt.claim.sub',${q(row.actor_id)},true);PERFORM set_config('vexa.tenant_id',${q(tenant)},true);PERFORM set_config('vexa.action','configure',true);`+insert(tables[0],row)+';';
 for(const active of [true,false]){const next={...curr,active};assert.equal(run(tables[1],rate,prepare(next)).code,'23514','MONEY_STALE_CATALOG_DENIED');if(active)assert.equal(run(tables[1],{...rate,base_catalog_id:next.id},prepare(next)).code,'00000','MONEY_CURRENT_CATALOG_POSITIVE');}
 const second={...curr,actor_id:actors.dual.id},currentRate={...rate,base_catalog_id:second.id};assert.equal(run(tables[1],currentRate,prepare(second)).code,'00000','MONEY_OTHER_OWNER_CONTRIBUTOR_POSITIVE');assert.equal(run(tables[1],currentRate,prepare(second)+`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(tenant)} AND user_id=${q(actors.dual.id)};`).code,'23514','MONEY_CATALOG_CONTRIBUTOR_REVOKED');assert.equal(run(tables[1],currentRate,prepare(second)+`UPDATE memberships SET role='analyst' WHERE tenant_id=${q(tenant)} AND user_id=${q(actors.dual.id)};`).code,'23514','MONEY_CATALOG_CONTRIBUTOR_DOWNGRADED');
}
export function fk(h,f,key){const original=f.a[key.table],row={...original,id:randomUUID(),version:original.version+1},probe=r=>h.probe(`ALTER TABLE ${key.table} DISABLE TRIGGER USER;${write(insert(key.table,r))}SET CONSTRAINTS ALL IMMEDIATE;`);assert.equal(probe(row).code,'00000','MONEY_FK_POSITIVE:'+key.name);const bad={...row};for(const[col,ref]of Object.entries(key.mapping))if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];const r=probe(bad);assert.equal(r.code,'23503','MONEY_FK_CROSS:'+key.name);assert.ok(r.constraint,'MONEY_FK_NAMED');}
