import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {q,insert} from './matrix.mjs';
import {write,denied} from './harness.mjs';
import {backend} from './import-uploads/oracles.mjs';
export const tables=['notification_events','notification_inbox','notification_preferences'];
export const present=h=>tables.filter(t=>h.sql(`SELECT to_regclass(${q('public.'+t)}) IS NOT NULL`)==='t');
export const ownsFk=k=>tables.includes(k.table);
const where=(table,row)=>table==='notification_preferences'?`tenant_id=${q(row.tenant_id)} AND user_id=${q(row.user_id)} AND channel=${q(row.channel)} AND event_type=${q(row.event_type)}`:`tenant_id=${q(row.tenant_id)} AND id=${q(row.id)}`;
const read=(table,row)=>`SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') INTO result FROM public.${table} x WHERE ${where(table,row)};`;
const rejected=(r,label)=>{if(r.code==='23514'||r.code==='23503')return;denied(r,label);};
const context=(actor,t,action='notify')=>`SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('vexa.tenant_id',${q(t)},true),set_config('vexa.action',${q(action)},true);`;
export function schema(h,fks){
 assert.deepEqual(present(h),tables,'NOTIFICATION_THREE_CANONICAL_TABLES');
 for(const table of tables){assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'NOTIFICATION_FORCE_RLS:'+table);assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t');for(const role of ['anon','authenticated','service_role'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},${q('public.'+table)},${q(action)})`),'f','NOTIFICATION_PRIVATE_TABLE:'+table+role+action);for(const action of ['DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege('vexa_backend',${q('public.'+table)},${q(action)})`),'f','NOTIFICATION_MINIMAL_GRANT');assert.equal(h.sql(`SELECT has_table_privilege('vexa_backend',${q('public.'+table)},'INSERT')`),table==='notification_preferences'?'t':'f','NOTIFICATION_NO_PUBLIC_EMITTER');}
 const keys=fks.filter(ownsFk);assert.equal(keys.length,6,'NOTIFICATION_SIX_TENANT_FKS');for(const k of keys)assert.ok(k.validated&&(k.parent==='organizations'?k.mapping.tenant_id==='id':k.mapping.tenant_id==='tenant_id'),'NOTIFICATION_TENANT_FK:'+k.name);
 for(const table of tables){const columns=h.json(`SELECT jsonb_agg(column_name ORDER BY ordinal_position) FROM information_schema.columns WHERE table_schema='public' AND table_name=${q(table)}`);assert.ok(!columns.some(c=>/payload|email|phone|amount|body|html|customer/i.test(c)),'NOTIFICATION_NO_ARBITRARY_PII_PAYLOAD');}
}
export async function seed(h,base,actors,briefs){const out={};for(const side of ['a','b']){const b=briefs[side],t=b.tenant,items={};for(const key of side==='a'?['a','dual','viewer','analyst','operator']:['b']){const actor=actors[key],event={tenant_id:t,id:randomUUID(),type:'brief.available',resource_id:b.weekly_briefs.id},inbox={tenant_id:t,id:randomUUID(),event_id:event.id,user_id:actor.id},pref={tenant_id:t,user_id:actor.id,channel:'inapp',event_type:'*',enabled:false,version:1};h.sql('BEGIN;'+context(actor,t)+insert('notification_events',event)+';'+insert('notification_inbox',inbox)+';SET LOCAL ROLE vexa_backend;'+insert('notification_preferences',pref)+';COMMIT;');items[key]={event,inbox,pref};}const own=items[side];out[side]={...b,items,notification_events:own.event,notification_inbox:own.inbox,notification_preferences:own.pref,memberships:{tenant_id:t,user_id:actors[side].id},customers:base[side].customers,connections:base[side].connections,baseJob:base[side].jobs,baseImport:base[side].imports,interventions:base.interventions?.[side]?.interventions??base.recommendations?.[side]?.interventions,recommendationConnection:base.recommendations?.[side]?.connections};}
 out.invited=await h.user();h.sql(insert('memberships',{tenant_id:out.a.tenant,user_id:out.invited.id,role:'viewer',status:'invited',permissions_version:1}));return out;}
export function fk(h,f,k){const row=f.a[k.table],probe=values=>h.probe(`ALTER TABLE ${k.table} DISABLE TRIGGER USER;${write(`UPDATE ${k.table} SET ${Object.entries(values).map(([key,v])=>`${key}=${q(v)}`).join(',')} WHERE ${where(k.table,row)}`)}SET CONSTRAINTS ALL IMMEDIATE;`);const same=Object.fromEntries(Object.keys(k.mapping).map(col=>[col,row[col]]));assert.equal(probe(same).code,'00000','NOTIFICATION_FK_POSITIVE:'+k.name);const bad={...same};for(const[col,ref]of Object.entries(k.mapping))if(k.parent==='organizations')bad[col]=randomUUID();else if(col!=='tenant_id')bad[col]=f.b[k.parent][ref];const result=probe(bad);assert.equal(result.code,'23503','NOTIFICATION_FOREIGN_FK:'+k.name);assert.ok(result.constraint);}
export function access(h,f,actors){
 for(const key of ['a','dual','viewer','analyst','operator']){const {event,inbox,pref}=f.a.items[key];for(const [table,row]of [['notification_events',event],['notification_inbox',inbox],['notification_preferences',pref]]){const query=read(table,row),r=backend(h,query,actors[key],f.a.tenant,'read');assert.equal(r.code,'00000',JSON.stringify(r));assert.equal(r.rows.length,1,'NOTIFICATION_OWN_ROLE:'+key+table);for(const wrong of [...Object.keys(f.a.items).filter(x=>x!==key),'b','outsider'])denied(backend(h,query,actors[wrong],f.a.tenant,'read'),'NOTIFICATION_NOT_OTHER_USER:'+wrong);denied(backend(h,query,actors.dual,f.b.tenant,'read'),'NOTIFICATION_SELECTOR_BOUND');denied(backend(h,query,f.invited,f.a.tenant,'read'),'NOTIFICATION_INVITED_NO_ACCESS');for(const actor of [null,actors[key],actors.b])denied(h.probe(query,actor),'NOTIFICATION_AUTHENTICATED_PRIVATE');denied(h.probe('SET LOCAL ROLE service_role;'+query),'NOTIFICATION_SERVICE_PRIVATE');}}
 const row=f.a.items.viewer.inbox,query=read('notification_inbox',row);denied(backend(h,query,actors.viewer,f.a.tenant,'read',`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(f.a.tenant)} AND user_id=${q(actors.viewer.id)};`),'NOTIFICATION_REVOKED_CURRENT_MEMBER');
}
export function integrity(h,f,actors){const a=f.a,v=actors.viewer,row=a.items.viewer.inbox,pref=a.items.viewer.pref;
 const mark=backend(h,`UPDATE notification_inbox SET read_at=clock_timestamp() WHERE ${where('notification_inbox',row)};${read('notification_inbox',row)}`,v,a.tenant,'notify');assert.equal(mark.code,'00000',JSON.stringify(mark));assert.equal(mark.rows.length,1,'NOTIFICATION_VIEWER_READ_OWN');assert.ok(mark.rows[0].read_at);
 const repeat=backend(h,`UPDATE notification_inbox SET read_at=clock_timestamp() WHERE ${where('notification_inbox',row)};SELECT jsonb_build_array(read_at) INTO result FROM notification_inbox WHERE ${where('notification_inbox',row)};UPDATE notification_inbox SET read_at='2000-01-01' WHERE ${where('notification_inbox',row)};SELECT jsonb_build_array(result->>0,read_at::text) INTO result FROM notification_inbox WHERE ${where('notification_inbox',row)};`,v,a.tenant,'notify');assert.equal(repeat.code,'00000',JSON.stringify(repeat));assert.equal(Date.parse(repeat.rows[0]),Date.parse(repeat.rows[1]),'NOTIFICATION_READ_IDEMPOTENT_SERVER_CLOCK');
 for(const actor of [actors.a,actors.operator,actors.b])denied(backend(h,write(`UPDATE notification_inbox SET read_at=clock_timestamp() WHERE ${where('notification_inbox',row)}`),actor,a.tenant,'notify'),'NOTIFICATION_READ_OWN_ONLY');
 for(const action of ['read','import','configure','materialize','propose','approve','execute','retain'])denied(backend(h,write(`UPDATE notification_inbox SET read_at=clock_timestamp() WHERE ${where('notification_inbox',row)}`),v,a.tenant,action),'NOTIFICATION_READ_NOTIFY_ONLY:'+action);
 const positive=backend(h,`UPDATE notification_preferences SET enabled=true,version=2 WHERE ${where('notification_preferences',pref)} AND version=1;${read('notification_preferences',pref)}`,v,a.tenant,'notify');assert.equal(positive.code,'00000');assert.equal(positive.rows.length,1);assert.equal(positive.rows[0].version,2);
 const stale=backend(h,`UPDATE notification_preferences SET enabled=true,version=2 WHERE ${where('notification_preferences',pref)} AND version=1;${write(`UPDATE notification_preferences SET enabled=false,version=2 WHERE ${where('notification_preferences',pref)} AND version=1`)}`,v,a.tenant,'notify');assert.equal(stale.code,'00000');assert.deepEqual(stale.rows,[],'NOTIFICATION_STALE_CAS_NO_WRITE');
 for(const version of [1,3,0,-1])rejected(backend(h,write(`UPDATE notification_preferences SET enabled=true,version=${version} WHERE ${where('notification_preferences',pref)}`),v,a.tenant,'notify'),'NOTIFICATION_VERSION_STEP');
 for(const patch of [{channel:'sms'},{event_type:'crm.customer'},{version:2},{user_id:actors.a.id},{tenant_id:f.b.tenant}])rejected(backend(h,write(insert('notification_preferences',{...pref,event_type:'brief.available',...patch})),v,a.tenant,'notify'),'NOTIFICATION_PREFERENCE_INVALID');
 for(const table of tables){const r=a[table];denied(backend(h,write(`DELETE FROM ${table} WHERE ${where(table,r)}`),actors.a,a.tenant,'notify'),'NOTIFICATION_NO_DELETE');}
 for(const table of ['notification_events','notification_inbox']){const r={...a[table],id:randomUUID()};for(const action of ['notify','import','configure'])denied(backend(h,write(insert(table,r)),actors.a,a.tenant,action),'NOTIFICATION_NO_BACKEND_EMITTER');}
 for(const [user,label]of [[a.customers.id,'CUSTOMER'],[f.invited.id,'INVITED'],[actors.b.id,'FOREIGN'],[actors.outsider.id,'OUTSIDER']])rejected(h.probe(write(insert('notification_inbox',{...a.notification_inbox,id:randomUUID(),user_id:user}))),'NOTIFICATION_RECIPIENT_'+label);
 for(const patch of [{type:'membership.invited',resource_id:randomUUID()},{resource_id:f.b.weekly_briefs.id},{resource_id:randomUUID()},{type:'crm.customer',resource_id:a.customers.id}])rejected(h.probe(write(insert('notification_events',{...a.notification_events,id:randomUUID(),...patch}))),'NOTIFICATION_EVENT_REAL_TENANT_RESOURCE');
 for(const col of ['user_id','event_id','created_at'])denied(backend(h,write(`UPDATE notification_inbox SET ${col}=${q(col==='created_at'?'2000-01-01':randomUUID())} WHERE ${where('notification_inbox',row)}`),v,a.tenant,'notify'),'NOTIFICATION_READ_STATE_ONLY');
}
export function authorization(h,f,actors){const a=f.a,v=actors.viewer,row=a.items.viewer.inbox,query=read('notification_inbox',row);const source={...a.source,id:randomUUID(),version:a.source.version+1,active:false};const before=`PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);PERFORM set_config('vexa.action','configure',true);${insert('economic_source_versions',source)};`;
 denied(backend(h,query,v,a.tenant,'read',before),'NOTIFICATION_CURRENT_BRIEF_SOURCE');denied(backend(h,write(`UPDATE notification_inbox SET read_at=clock_timestamp() WHERE ${where('notification_inbox',row)}`),v,a.tenant,'notify',before),'NOTIFICATION_REVOKED_RESOURCE_NOT_MARKABLE');assert.equal(backend(h,read('notification_preferences',a.items.viewer.pref),v,a.tenant,'read',before).rows.length,1,'NOTIFICATION_RESOURCE_WITHDRAWAL_NOT_USER_REVOCATION');
 const functionList=[['notification_resource_read(uuid,uuid,text,uuid)',false],['notification_resource_current(uuid,uuid,text,uuid)',true],['notification_visible(uuid,uuid)',true],['notification_own(uuid,uuid)',true]];
 for(const [sig,runtime] of functionList){const meta=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q('public.'+sig)}::regprocedure`);assert.ok(meta.config.includes('search_path=""'),'NOTIFICATION_HELPER_SEARCH_PATH');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q('public.'+sig)},'EXECUTE')`),role==='vexa_backend'&&runtime?'t':'f','NOTIFICATION_HELPER_GRANT');}
 const call=`SELECT jsonb_build_array(public.notification_resource_current(${q(a.tenant)}::uuid,${q(v.id)}::uuid,'brief.available',${q(a.weekly_briefs.id)}::uuid),current_setting('vexa.action',true)) INTO result;`;
 for(const action of ['read','notify'])assert.deepEqual(backend(h,call,v,a.tenant,action).rows,[true,action],'NOTIFICATION_PRIVATE_READ_WRAPPER_RESTORES_ACTION');for(const action of ['import','configure','materialize','execute','retain',''])assert.deepEqual(backend(h,call,v,a.tenant,action).rows,[false,action],'NOTIFICATION_HELPER_CAPABILITY');
 const noAction=`GRANT ALL ON exam_result TO vexa_backend;SET LOCAL ROLE vexa_backend;PERFORM set_config('request.jwt.claim.sub',${q(v.id)},true);PERFORM set_config('vexa.tenant_id',${q(a.tenant)},true);`;
 const missing=h.probe(noAction+call);assert.equal(missing.code,'00000',JSON.stringify(missing));assert.deepEqual(missing.rows,[false,null],'NOTIFICATION_MISSING_ACTION_FAIL_CLOSED');
 for(const [t,u]of [[f.b.tenant,v.id],[a.tenant,actors.a.id]])assert.deepEqual(backend(h,`SELECT jsonb_build_array(public.notification_resource_current(${q(t)}::uuid,${q(u)}::uuid,'brief.available',${q(a.weekly_briefs.id)}::uuid)) INTO result;`,v,a.tenant,'notify').rows,[false],'NOTIFICATION_HELPER_NO_OTHER_PRINCIPAL');
}

export function resources(h,f,actors){const a=f.a,t=a.tenant;assert.ok(a.interventions,'NOTIFICATION_ASSIGNED_INTERVENTION_FIXTURE');const job={...a.baseJob,id:randomUUID(),input_hash:"SYN-notification-"+randomUUID(),import_id:a.baseImport.id};h.sql('BEGIN;'+context(actors.a,t,'import')+insert('jobs',job)+';COMMIT;');
 const cases=[['membership.welcome',actors.viewer.id,'viewer',true],['connection.attention',a.connections.id,'a',true],['connection.attention',a.connections.id,'viewer',false],['processing.failed',job.id,'a',true],['processing.failed',job.id,'analyst',true],['processing.failed',job.id,'viewer',false],['intervention.assigned',a.interventions.id,'a',true]];
 for(const [type,resource,key,allowed]of cases){const e={tenant_id:t,id:randomUUID(),type,resource_id:resource},n={tenant_id:t,id:randomUUID(),event_id:e.id,user_id:actors[key].id};h.sql(insert('notification_events',e)+';'+insert('notification_inbox',n)+';');const query=read('notification_inbox',n),r=backend(h,query,actors[key],t,'read');assert.equal(r.code,'00000',JSON.stringify(r));assert.equal(r.rows.length,allowed?1:0,'NOTIFICATION_RESOURCE_ROLE:'+type+key);if(type==='intervention.assigned'){rejected(h.probe(write(insert('notification_inbox',{...n,id:randomUUID(),user_id:actors.viewer.id}))),'NOTIFICATION_ASSIGNED_USER_REQUIRED');const before=`UPDATE connections SET status='disconnected' WHERE tenant_id=${q(t)} AND id=${q(a.recommendationConnection.id)};`;denied(backend(h,query,actors.a,t,'read',before),'NOTIFICATION_ASSIGNED_EVIDENCE_WITHDRAWAL');}if(type==='membership.welcome')rejected(h.probe(write(insert('notification_inbox',{...n,id:randomUUID(),user_id:actors.a.id}))),'NOTIFICATION_WELCOME_MATCHES_MEMBER');}
}
