import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {q,insert} from './matrix.mjs';import {read,write,denied} from './harness.mjs';import {backend} from './import-uploads/oracles.mjs';
export const tables=['economic_snapshot_heads'];export const present=h=>tables.filter(table=>h.sql(`SELECT to_regclass(${q('public.'+table)}) IS NOT NULL`)==='t');const hash=()=>createHash('sha256').update(randomUUID()).digest('hex');
export function schema(h,fks){assert.deepEqual(present(h),tables,'SNAPSHOT_HEADS_REQUIRED');for(const table of [...tables,'metric_snapshots','components']){assert.deepEqual(h.json(`SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid=${q('public.'+table)}::regclass`),[true,true],'SNAPSHOT_FORCE_RLS:'+table);assert.equal(h.sql(`SELECT attnotnull FROM pg_attribute WHERE attrelid=${q('public.'+table)}::regclass AND attname='tenant_id'`),'t','SNAPSHOT_TENANT_NOT_NULL');}
 for(const role of ['anon','authenticated','service_role','vexa_backend'])for(const action of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])assert.equal(h.sql(`SELECT has_table_privilege(${q(role)},'public.economic_snapshot_heads',${q(action)})`),(role==='authenticated'&&action==='SELECT'||role==='vexa_backend'&&['SELECT','INSERT','UPDATE'].includes(action))?'t':'f','SNAPSHOT_HEAD_GRANT:'+role+action);
 for(const column of ['amount_minor','known_subtotal_minor'])assert.deepEqual(h.json(`SELECT jsonb_build_array(atttypid::regtype::text,atttypmod) FROM pg_attribute WHERE attrelid='public.components'::regclass AND attname=${q(column)}`),['numeric',-1],'SNAPSHOT_EXACT_UNBOUNDED_NUMERIC');
 const expected=[['metric_snapshots','memberships',{tenant_id:'tenant_id',created_by:'user_id'}],['metric_snapshots','memberships',{tenant_id:'tenant_id',published_by:'user_id'}],['economic_snapshot_heads','metric_snapshots',{tenant_id:'tenant_id',snapshot_id:'id'}],['economic_snapshot_heads','organizations',{tenant_id:'id'}]];const extra=fks.filter(k=>k.table===tables[0]||k.table==='metric_snapshots'&&['created_by','published_by'].some(c=>c in k.mapping));assert.equal(extra.length,4,'SNAPSHOT_NEW_FK_COUNT');for(const[table,parent,mapping]of expected)assert.ok(extra.some(k=>k.table===table&&k.parent===parent&&k.validated&&JSON.stringify(Object.entries(k.mapping).sort())===JSON.stringify(Object.entries(mapping).sort())),'SNAPSHOT_COMPOSITE_FK:'+table+parent);
 for(const [name,definer,roles]of [['economic_snapshot_digest(uuid,uuid)',false,['vexa_backend']],['economic_snapshot_write_guard()',false,['vexa_backend']],['economic_snapshot_visible(uuid,uuid)',true,['authenticated','vexa_backend']]]){const signature='public.'+name;const fn=h.json(`SELECT jsonb_build_object('definer',prosecdef,'config',proconfig) FROM pg_proc WHERE oid=${q(signature)}::regprocedure`);assert.equal(fn.definer,definer,'SNAPSHOT_HELPER_PRIVILEGE');assert.ok(fn.config.includes('search_path=""'),'SNAPSHOT_HELPER_SEARCH_PATH');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`SELECT has_function_privilege(${q(role)},${q(signature)},'EXECUTE')`),roles.includes(role)?'t':'f','SNAPSHOT_HELPER_GRANT:'+name+role);}}
const context=(actor,tenant,action='import')=>`SET LOCAL ROLE vexa_backend;SELECT set_config('request.jwt.claim.sub',${q(actor.id)},true),set_config('request.jwt.claims',${q(JSON.stringify({sub:actor.id,role:'authenticated'}))},true),set_config('vexa.tenant_id',${q(tenant)},true),set_config('vexa.action',${q(action)},true);`;
const selectId=(table,id)=>`SELECT coalesce(jsonb_agg(to_jsonb(r)),'[]') INTO result FROM public.${table} r WHERE id=${q(id)};`;
const publication=(s,actor)=>`UPDATE public.metric_snapshots SET status='published',published_at=clock_timestamp(),published_by=${q(actor.id)},bundle_ref='canonical:'||content_hash WHERE id=${q(s.id)}`;
export function seed(h,f,actors){const out={};for(const side of ['a','b']){const tenant=f[side].metric_snapshots.tenant_id,actor=actors[side];
 const source={id:randomUUID(),tenant_id:tenant,source_id:randomUUID(),version:1,actor_id:actor.id,name:'SYN snapshot approved source',evidence_type:'order_export',active:true,complete:true,window_start:'2026-01-01T00:00:00Z',window_end:'2026-02-01T00:00:00Z',watermark:'2026-02-01T00:00:00Z',report:'SYN independent snapshot operational source; no live financial data.',report_hash:hash(),attested:true};h.sql('BEGIN;'+context(actor,tenant,'configure')+insert('economic_source_versions',source)+';COMMIT;');
 const scope={start:'2026-01-01T00:00:00.000Z',end:'2026-02-01T00:00:00.000Z',timezone:'UTC',dateBasis:'occurred_at',currency:'USD',exponent:2,basis:'net-no-tax'};
 const manifest={refs:[{table:'economic_source_versions',id:source.id,actorId:actor.id,authorized:true,active:true,sourceId:source.source_id,version:1,rowHash:hash()}],watermarks:[{sourceId:source.source_id,version:1,watermark:'2026-02-01T00:00:00.000Z',complete:true,active:true}],models:[],exposureInputHash:hash(),selection:{scope,fxRateId:null},policy:'economic-policy-f05-05-v1',schema:'economic-snapshot-v1'};
 const base={tenant_id:tenant,scope_hash:createHash('sha256').update(JSON.stringify({scope,fxRateId:null})).digest('hex'),input_hash:hash(),policy_version:manifest.policy,watermark:'2026-02-01T00:00:00Z',status:'draft',date_start:scope.start,date_end:scope.end,timezone:'UTC',currency:'USD',date_basis:'order',economic_schema_version:manifest.schema,as_of:'2026-02-01T00:00:00Z',content_hash:'0'.repeat(64),input_manifest:manifest,component_count:2,created_by:actor.id,provenance:{scope,fxRateId:null}};
 const snapshots=[];for(const published of [true,false]){const snap={...base,id:randomUUID(),input_hash:hash()},cs=[];for(const [metric,amount,known,total]of [['SYN-known','9'.repeat(39),1,1],['SYN-unknown',null,0,1]]){const id=randomUUID(),c={id,metric,label:metric,currency:'USD',exponent:2,amountMinor:amount,knownSubtotalMinor:amount,money:null,display:amount===null?'Total no disponible':amount+' USD',configurationStatus:'catalog_required',modeled:false,conversion:null};cs.push({id,tenant_id:tenant,snapshot_id:snap.id,metric,kind:'observed',amount_minor:amount,known_subtotal_minor:amount,currency:'USD',exponent:2,known_count:known,total_count:total,provenance:{component:c}});}h.sql('BEGIN;'+context(actor,tenant)+insert('metric_snapshots',snap)+';'+cs.map(c=>insert('components',c)+';').join('')+`UPDATE metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id) WHERE id=${q(snap.id)};`+(published?publication(snap,actor)+';':'')+'COMMIT;');const row=h.json(`SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(snap.id)}`);snapshots.push({...row,components:cs});}
 const head={tenant_id:tenant,scope_hash:base.scope_hash,snapshot_id:snapshots[0].id,version:1};h.sql('BEGIN;'+context(actor,tenant)+insert(tables[0],head)+';COMMIT;');out[side]={tenant,source,scope,published:snapshots[0],draft:snapshots[1],economic_snapshot_heads:head,metric_snapshots:snapshots[0],memberships:{user_id:actor.id}};}return out;}
export function visibility(h,f,actors){for(const table of ['metric_snapshots','components']){const pub=table==='components'?f.a.published.components[0]:f.a.published,draft=table==='components'?f.a.draft.components[0]:f.a.draft;
 for(const who of ['a','analyst','operator','viewer','dual']){denied(h.probe(selectId(table,pub.id),actors[who]),'SNAPSHOT_AUTHENTICATED_SERVER_ONLY:'+who);const b=backend(h,selectId(table,pub.id),actors[who],f.a.tenant,'read');assert.equal(b.code,'00000');assert.deepEqual(b.rows.map(x=>x.id),[pub.id],'SNAPSHOT_BACKEND_PUBLISHED_POSITIVE');}
 for(const who of ['a','dual']){denied(h.probe(selectId(table,draft.id),actors[who]),'SNAPSHOT_AUTHENTICATED_DRAFT_SERVER_ONLY');assert.equal(backend(h,selectId(table,draft.id),actors[who],f.a.tenant,'read').rows.length,1);}
 for(const who of ['viewer','analyst','operator']){denied(h.probe(selectId(table,draft.id),actors[who]),'SNAPSHOT_DRAFT_PRIVATE');denied(backend(h,selectId(table,draft.id),actors[who],f.a.tenant,'read'),'SNAPSHOT_BACKEND_DRAFT_PRIVATE');}
 for(const who of ['b','outsider']){denied(h.probe(selectId(table,pub.id),actors[who]),'SNAPSHOT_FOREIGN');denied(backend(h,selectId(table,pub.id),actors[who],f.a.tenant,'read'),'SNAPSHOT_BACKEND_FOREIGN');}denied(h.probe(selectId(table,pub.id),null),'SNAPSHOT_ANON');denied(h.probe('SET LOCAL ROLE service_role;'+selectId(table,pub.id)),'SNAPSHOT_SERVICE');denied(backend(h,selectId(table,pub.id),actors.dual,f.b.tenant,'read'),'SNAPSHOT_FORGED_SELECTOR');
 const revoke=`UPDATE memberships SET status='revoked' WHERE tenant_id=${q(f.a.tenant)} AND user_id=${q(actors.a.id)};`;denied(backend(h,selectId(table,pub.id),actors.dual,f.a.tenant,'read',revoke),'SNAPSHOT_CONTRIBUTOR_REVOKED');denied(backend(h,selectId(table,pub.id),actors.a,f.a.tenant,'read',revoke),'SNAPSHOT_READER_REVOKED');}
 for(const who of ['a','viewer','analyst','operator']){const r=h.probe(read(tables[0]),actors[who]);assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.snapshot_id),[f.a.published.id]);}for(const who of ['a','viewer','analyst','operator','dual']){const r=backend(h,read(tables[0]),actors[who],f.a.tenant,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.snapshot_id),[f.a.published.id],'SNAPSHOT_HEAD_BACKEND_MEMBER:'+who);}for(const who of ['b','outsider'])denied(backend(h,read(tables[0]),actors[who],f.a.tenant,'read'),'SNAPSHOT_HEAD_FOREIGN');}
const plain=s=>Object.fromEntries(Object.entries(s).filter(([k])=>k!=='components'));
export function metadata(h,f,actors){const d=f.a.draft,tenant=f.a.tenant,run=row=>backend(h,write(insert('metric_snapshots',row)),actors.a,tenant,'import');const fresh=()=>({...plain(d),id:randomUUID(),input_hash:hash(),published_by:null,published_at:null,bundle_ref:null});assert.equal(run(fresh()).code,'00000','SNAPSHOT_MANAGED_DRAFT_POSITIVE');
 for(const field of ['content_hash','input_manifest','component_count','as_of','created_by'])assert.equal(run({...fresh(),[field]:null}).code,'23514','SNAPSHOT_REQUIRED_METADATA:'+field);for(const patch of [{component_count:-1},{economic_schema_version:'unknown'},{as_of:'-infinity'},{status:'published',published_by:actors.a.id,published_at:'2026-02-01T00:00:00Z',bundle_ref:'fake'}])assert.equal(run({...fresh(),...patch}).code,'23514','SNAPSHOT_MANAGED_METADATA:'+JSON.stringify(patch));
 for(const manifest of [{},{...d.input_manifest,refs:null},{...d.input_manifest,models:{}},{...d.input_manifest,watermarks:'unknown'},{...d.input_manifest,selection:{}},{...d.input_manifest,selection:{...d.input_manifest.selection,scope:{...f.a.scope,currency:'MXN'}}},{...d.input_manifest,policy:'different'},{...d.input_manifest,schema:'different'}])assert.equal(run({...fresh(),input_manifest:manifest}).code,'23514','SNAPSHOT_MANIFEST_STRUCTURE');
 for(const who of ['analyst','viewer','operator'])denied(backend(h,write(insert('metric_snapshots',{...fresh(),created_by:actors[who].id})),actors[who],tenant,'import'),'SNAPSHOT_OWNER_STAGE_ONLY');denied(backend(h,write(insert('metric_snapshots',fresh())),actors.a,tenant,'configure'),'SNAPSHOT_IMPORT_CAPABILITY_ONLY');assert.equal(run({...fresh(),created_by:actors.dual.id}).code,'23514','SNAPSHOT_CREATOR_SPOOF');
 for(const patch of ["economic_schema_version=NULL","scope_hash='"+hash()+"'","input_hash='"+hash()+"'","policy_version='different'","as_of=as_of+interval '1 second'","provenance='{}'::jsonb","input_manifest='{}'::jsonb"]){const r=backend(h,write(`UPDATE metric_snapshots SET ${patch} WHERE id=${q(d.id)}`),actors.a,tenant,'import');assert.equal(r.code,'23514','SNAPSHOT_IDENTITY_IMMUTABLE:'+patch);}
 const component=f.a.draft.components[0];for(const column of ['amount_minor','known_subtotal_minor']){const row={...component,id:randomUUID(),[column]:'1.2'};assert.equal(backend(h,write(insert('components',row)),actors.a,tenant,'import').code,'23514','SNAPSHOT_FRACTION_REJECTED:'+column);}
 const exact=backend(h,`SELECT jsonb_build_array(amount_minor::text,known_subtotal_minor::text) INTO result FROM components WHERE id=${q(component.id)};`,actors.a,tenant,'read');assert.deepEqual(exact.rows,['9'.repeat(39),'9'.repeat(39)],'SNAPSHOT_AGGREGATE_OVER37_DIGITS_EXACT');const unknown=h.json(`SELECT jsonb_build_array(amount_minor,known_subtotal_minor,known_count,total_count) FROM components WHERE id=${q(d.components[1].id)}`);assert.deepEqual(unknown,[null,null,0,1],'SNAPSHOT_UNKNOWN_IS_NOT_ZERO');}
export function integrity(h,f,actors){const d=f.a.draft,p=f.a.published,tenant=f.a.tenant,run=stmt=>backend(h,write(stmt),actors.a,tenant,'import');assert.equal(run(publication(d,actors.a)).code,'00000','SNAPSHOT_COMPLETE_PUBLICATION_POSITIVE');
 assert.equal(run(`UPDATE metric_snapshots SET component_count=99 WHERE id=${q(d.id)};`+publication(d,actors.a)).code,'23514','SNAPSHOT_COMPONENT_MANIFEST_COUNT');assert.equal(run(`UPDATE metric_snapshots SET content_hash='${'f'.repeat(64)}' WHERE id=${q(d.id)};`+publication(d,actors.a)).code,'23514','SNAPSHOT_COMPONENT_DIGEST_REQUIRED');
 const mutation=`UPDATE components SET amount_minor=amount_minor+1 WHERE id=${q(d.components[0].id)};`;assert.equal(run(mutation+publication(d,actors.a)).code,'23514','SNAPSHOT_AMOUNT_IS_HASHED');
 for(const table of ['metric_snapshots','components']){const id=table==='metric_snapshots'?p.id:p.components[0].id;for(const operation of ['UPDATE','DELETE']){const stmt=operation==='UPDATE'?`UPDATE ${table} SET updated_at=updated_at+interval '1 second' WHERE id=${q(id)}`:`DELETE FROM ${table} WHERE id=${q(id)}`;const action=operation==='DELETE'?'retain':'import';const r=backend(h,write(stmt),actors.a,tenant,action);assert.ok(['23514','42501'].includes(r.code),'SNAPSHOT_PUBLISHED_IMMUTABLE:'+table+operation+JSON.stringify(r));}}
 const extra={...p.components[0],id:randomUUID()};assert.equal(run(insert('components',extra)).code,'23514','SNAPSHOT_PUBLISHED_NO_NEW_COMPONENT');
 const head=f.a.economic_snapshot_heads;assert.equal(run(insert(tables[0],{...head,scope_hash:hash(),snapshot_id:d.id})).code,'23514','SNAPSHOT_HEAD_DRAFT_DENIED');assert.equal(run(`UPDATE economic_snapshot_heads SET snapshot_id=${q(d.id)},version=version+1 WHERE tenant_id=${q(tenant)}`).code,'23514','SNAPSHOT_HEAD_NEVER_DRAFT');assert.equal(run(`UPDATE economic_snapshot_heads SET version=version WHERE tenant_id=${q(tenant)}`).code,'23514','SNAPSHOT_HEAD_CAS');assert.equal(run(`UPDATE economic_snapshot_heads SET version=version+1 WHERE tenant_id=${q(tenant)}`).code,'00000','SNAPSHOT_HEAD_CAS_POSITIVE');
 for(const who of ['analyst','viewer','operator'])denied(backend(h,write(`UPDATE economic_snapshot_heads SET version=version+1 WHERE tenant_id=${q(tenant)}`),actors[who],tenant,'import'),'SNAPSHOT_HEAD_OWNER_ONLY');
 const swap=h.probe(`DELETE FROM economic_snapshot_heads WHERE tenant_id=${q(f.b.tenant)};${write(`UPDATE economic_snapshot_heads SET tenant_id=${q(f.b.tenant)},snapshot_id=${q(f.b.published.id)},version=version+1 WHERE tenant_id=${q(tenant)}`)}`);assert.equal(swap.code,'23514','SNAPSHOT_HEAD_TENANT_IMMUTABLE_INDEPENDENT_FK');
 const before=h.sql(`SELECT to_jsonb(h) FROM economic_snapshot_heads h WHERE tenant_id=${q(tenant)}`);const rollback=run(publication(d,actors.a)+`;UPDATE economic_snapshot_heads SET snapshot_id=${q(d.id)},version=version+1 WHERE tenant_id=${q(tenant)};PERFORM 1/0`);assert.equal(rollback.code,'22012','SNAPSHOT_AFTER_COMPONENT_PUBLICATION_CRASH');assert.equal(h.sql(`SELECT to_jsonb(h) FROM economic_snapshot_heads h WHERE tenant_id=${q(tenant)}`),before,'SNAPSHOT_LAST_GOOD_HEAD_SURVIVES_CRASH');assert.equal(h.sql(`SELECT status FROM metric_snapshots WHERE id=${q(d.id)}`),'draft','SNAPSHOT_ATOMIC_ROLLBACK');}
export function withdrawal(h,f,actors){const source={...f.a.source,id:randomUUID(),version:2,active:false},tenant=f.a.tenant;const prepare=`PERFORM set_config('request.jwt.claim.sub',${q(actors.a.id)},true);PERFORM set_config('vexa.tenant_id',${q(tenant)},true);PERFORM set_config('vexa.action','configure',true);`+insert('economic_source_versions',source)+';';for(const table of ['metric_snapshots','components']){const id=table==='metric_snapshots'?f.a.published.id:f.a.published.components[0].id;denied(backend(h,selectId(table,id),actors.viewer,tenant,'read',prepare),'SNAPSHOT_WITHDRAWN_SOURCE_PRIVATE:'+table);}}
export function fk(h,f,key){const source=key.table===tables[0]?f.a.economic_snapshot_heads:plain(f.a.draft),row={...source};if(key.table===tables[0])row.scope_hash=hash();else{row.id=randomUUID();row.input_hash=hash();row.published_by=actorsNotNeeded(f.a);}
 const probe=r=>h.probe(`ALTER TABLE ${key.table} DISABLE TRIGGER USER;${write(insert(key.table,r))}SET CONSTRAINTS ALL IMMEDIATE;`);assert.equal(probe(row).code,'00000','SNAPSHOT_FK_POSITIVE:'+key.name);const bad={...row};for(const[col,ref]of Object.entries(key.mapping)){if(key.parent==='organizations')bad[col]=randomUUID();else if(col!=='tenant_id')bad[col]=f.b[key.parent][ref];}const result=probe(bad);assert.equal(result.code,'23503','SNAPSHOT_FK_CROSS:'+key.name);assert.ok(result.constraint,'SNAPSHOT_FK_NAMED');}
function actorsNotNeeded(side){return side.memberships.user_id;}

export function refreshDraftDigest(h,f,actors){h.sql('BEGIN;'+context(actors.a,f.a.tenant)+`UPDATE metric_snapshots SET content_hash=public.economic_snapshot_digest(tenant_id,id) WHERE id=${q(f.a.draft.id)};COMMIT;`);}

export function timezones(h,f,actors){const snap=f.a.published;for(const who of ['a','viewer','analyst','operator','dual'])for(const zone of ['UTC','America/Merida','Asia/Kolkata']){const r=backend(h,`SELECT jsonb_build_array(public.economic_snapshot_digest(${q(f.a.tenant)}::uuid,${q(snap.id)}::uuid)) INTO result;`,actors[who],f.a.tenant,'read',`SET LOCAL TIME ZONE ${q(zone)};`);assert.equal(r.code,'00000',JSON.stringify(r));assert.deepEqual(r.rows,[snap.content_hash],'SNAPSHOT_DIGEST_TIMEZONE_INDEPENDENT:'+who+':'+zone);}}
