import Link from 'next/link';
import { AccessError } from '../auth';
import { workspaceSession, workspaceService } from './server';
import { readWorkspace } from './data';
import { money, parseScope, type Resource } from './contracts';
import { DataState } from '../../components/workspace/data-state';
import { Filters } from '../../components/workspace/filters';
import { ActionForm } from '../../components/workspace/action-form';
export type Query = Promise<Record<string,string|string[]|undefined>>;
export function queryParams(raw:Record<string,string|string[]|undefined>){const p=new URLSearchParams();for(const [k,v] of Object.entries(raw))for(const x of Array.isArray(v)?v:v===undefined?[]:[v])if(x!=='')p.append(k,x);return p;}
const titles:Record<Resource,string>={metrics:'Resumen ejecutivo',problems:'Problemas de negocio',customers:'Historial del cliente',recommendations:'Recomendaciones',explorer:'Explorador de evidencia',interventions:'Intervenciones',briefs:'Brief ejecutivo'};
const descriptions:Record<Resource,string>={metrics:'Prioridades, exposición y cobertura del mismo snapshot. La exposición no equivale a pérdida ni es aditiva entre problemas.',problems:'Prioridades respaldadas por evidencia. Las causas probables siguen siendo hipótesis.',customers:'Identidad conocida, órdenes y evidencia autorizada. Una identidad desconocida no crea un cliente.',recommendations:'Acciones condicionadas a evidencia y a un responsable humano.',explorer:'Consulta de solo lectura. Sin evidencia verificable, el sistema se abstiene; no infiere causalidad.',interventions:'Baseline, hipótesis, responsable, plan y medición. Un cambio antes/después no demuestra ahorro causal.',briefs:'Prioridades y decisiones con corte, cobertura y versión. Generar un brief no envía correos.'};
export async function WorkspaceView({resource,id,searchParams,readOnly=false}:{resource:Resource;id?:string;searchParams:Query;readOnly?:boolean}){
 const raw=await searchParams,query=queryParams(raw);let request:ReturnType<typeof parseScope>;try{request=parseScope(query);}catch(error){return <><h1>{titles[resource]}</h1><DataState state={{kind:'error',code:error instanceof AccessError?error.code:'invalid_scope',message:'Alcance inválido. Revisa fechas, moneda, filtros y paginación.'}}/><Link href={resource==='metrics'?'/overview':'/'+resource+(id?'/'+encodeURIComponent(id):'')}>Restablecer filtros</Link></>;}
 const heading=()=><><p className="eyebrow">Workspace / {id?'Detalle':'Vista ejecutiva'}</p><h1>{id&&resource==='problems'?'Detalle del problema':titles[resource]}</h1><p className="intro">{descriptions[resource]}</p><Filters scope={request.scope}/></>;
 let session,bundle;
 try{const context=await workspaceSession();session=context.session;if(readOnly&&id&&(resource==='interventions'||resource==='briefs')){const canonical=await workspaceService(context.client,session.active.tenant_id).resourceScope({resource,id});for(const [key,value] of Object.entries(canonical)){if(value===null||query.has(key))continue;if(Array.isArray(value)){for(const v of value)query.append(key,v);}else query.set(key,['date_start','date_end'].includes(key)?value.slice(0,10):value);}request=parseScope(query);}bundle=await readWorkspace(workspaceService(context.client,session.active.tenant_id),session,resource,request,id??null);}
 catch(error){const code=error instanceof AccessError?error.code:'workspace_unavailable';return <>{heading()}<DataState state={{kind:'error',code,message:code==='resource_not_found'?'No existe un recurso accesible con este identificador.':'No se pudo consultar el workspace. Reintenta; si el problema continúa, solicita al administrador que revise la conexión y la configuración del servicio.'}}/></>;}
 const state=bundle.meta.state;const pinned=new URLSearchParams(query);if(bundle.meta.snapshot_id)pinned.set('snapshot_id',bundle.meta.snapshot_id);pinned.delete('cursor');const suffix='?'+pinned.toString();
 const canPropose=['owner','analyst','operator'].includes(session.active.role);
 return <>{heading()}<p className="snapshot">Snapshot: {bundle.meta.snapshot_id??'Sin snapshot publicado'} · Alcance: {bundle.meta.scope_hash}</p>{bundle.meta.critical_notice&&<div className="state-panel partial" role="alert"><strong>Revisión crítica, independiente de filtros</strong><p>{bundle.meta.critical_notice}</p></div>}
 <DataState state={state==='empty'?{kind:'empty'}:{kind:state,coverage:bundle.meta.coverage,watermark:bundle.meta.watermark}}>
 <div className="record-grid">{bundle.items.map(item=><article key={item.id} className="record-card"><header><span className="status">{item.status}</span><h2>{resource==='problems'&&!id?<Link href={'/problems/'+item.id+suffix}>{item.title}</Link>:item.title}</h2></header><p>{item.summary}</p>
 {item.metrics.length>0&&<dl className="metric-grid">{item.metrics.map((m,i)=><div key={i}><dt>{m.label}</dt><dd>{money(m)}<small>{m.kind} · Fuente: {m.source_ref}</small>{m.amount_minor===null&&m.known_subtotal!==null&&<p>Subtotal conocido: {money({...m,amount_minor:m.known_subtotal})}; no es el total.</p>}</dd></div>)}</dl>}
 <dl className="record-details">{item.details.map((d,i)=><div key={i}><dt>{d.label}</dt><dd>{d.value}</dd></div>)}<div><dt>Responsable</dt><dd>{item.owner??'Sin asignar'}</dd></div><div><dt>Versión</dt><dd>{item.version}</dd></div></dl>
 {item.problem_id&&<p><Link href={'/problems/'+item.problem_id+suffix}>Ver problema y desglose</Link></p>}{item.customer_id&&<p><Link href={'/customers/'+item.customer_id+suffix}>Ver cliente conocido</Link></p>}
 <details><summary>Evidencia y procedencia ({item.evidence.length})</summary>{item.evidence.length?item.evidence.map(e=><figure key={e.id}><blockquote>{e.quote}</blockquote><figcaption>{e.role==='internal'?'Nota interna':e.role==='agent'?'Agente':'Cliente'} · {e.source_ref} · Revisión {e.id}</figcaption></figure>):<p>Sin citas disponibles; no se confirma una causa.</p>}</details>
 {resource==='recommendations'&&canPropose&&<ActionForm endpoint={'/api/recommendations/'+item.id+'/interventions'} version={item.version} scope={pinned.toString()} kind="recommendation" disabledReason={item.evidence.length?undefined:"Falta evidencia publicada para proponer una intervención."}/>}
 {!readOnly&&resource==='interventions'&&item.status==='draft'&&canPropose&&<ActionForm endpoint={'/api/interventions/'+item.id+'/plan'} version={item.version} scope={pinned.toString()} kind="plan" owner={item.owner??''} baseline={bundle.meta.snapshot_id??''} planScope={item.details.find(d=>d.label==='Alcance del baseline')?.value??''}/>}
 { !readOnly&&resource==='interventions'&&['owner','operator'].includes(session.active.role)&&<ActionForm endpoint={'/api/interventions/'+item.id+'/transition'} version={item.version} scope={pinned.toString()} kind="intervention"/>}
 </article>)}</div></DataState>
 {resource==='explorer'&&<><p>No se genera una respuesta de IA sin un servicio de consulta y citas validado.</p><ActionForm endpoint="/api/explorer/query" version={1} scope={pinned.toString()} kind="explorer" disabledReason={bundle.meta.snapshot_id?undefined:"No hay snapshot publicado para consultar."}/></>}
 {!readOnly&&resource==='briefs'&&['owner','analyst'].includes(session.active.role)&&<ActionForm endpoint="/api/briefs" version={1} scope={pinned.toString()} kind="brief" disabledReason={bundle.meta.snapshot_id?undefined:"No hay snapshot publicado para generar un brief."}/>}
 {bundle.meta.next_cursor&&<Link className="page-next" href={'?'+new URLSearchParams([...pinned.entries(),['cursor',bundle.meta.next_cursor]])}>Página siguiente</Link>}
 </>;

}
