import {WorkspaceError,check,uuid,hash} from '../workspace-service/contracts.mjs';
import {createWorkspaceService,projection} from '../workspace-service/index.mjs';
import {createDetailService} from '../workspace-service/detail.mjs';
import {createSnapshotRepository} from '../metrics/snapshots.mjs';
import {EconomicError} from '../metrics/repository.mjs';
import {DomainError} from '../problems/contracts.mjs';
import {strict,text,instant,validatePlan,assertTransition} from './state.mjs';
const one=async(s,q,a=[])=>(await s.query(q,a)).rows[0],iso=x=>x?new Date(x).toISOString():null;
const tables=['economic_source_versions','economic_ledger_entries','economic_problem_links','economic_order_aliases','economic_order_customers','economic_relation_coverage'];
export function createInterventionRepository({database}){
 const tx=async(action,fn)=>{let own;try{return await database.transaction(action,async s=>{try{return await fn(s);}catch(e){if(e instanceof WorkspaceError||e instanceof EconomicError||e instanceof DomainError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}};
 const snapshots=createSnapshotRepository({database});
 async function raw(id){check(uuid(id),'intervention_not_found',404);return tx('read',async s=>{const r=await one(s,"SELECT * FROM public.interventions WHERE tenant_id=$1 AND id=$2 AND provenance->>'kind'='recommendation-draft-v1'",[s.tenantId,id]);check(r,'intervention_not_found',404);check((await one(s,'SELECT public.intervention_authorized($1,$2) AS ok',[s.tenantId,id])).ok,'intervention_evidence_unavailable',403);const p=r.plan_id?await one(s,'SELECT * FROM public.measurement_plans WHERE tenant_id=$1 AND id=$2',[s.tenantId,r.plan_id]):null;const plans=(await s.query('SELECT * FROM public.measurement_plans WHERE tenant_id=$1 AND intervention_id=$2 ORDER BY version',[s.tenantId,id])).rows;const history=(await s.query('SELECT * FROM public.intervention_events WHERE tenant_id=$1 AND intervention_id=$2 ORDER BY version',[s.tenantId,id])).rows;const results=(await s.query('SELECT * FROM public.intervention_results WHERE tenant_id=$1 AND intervention_id=$2 ORDER BY created_at,id',[s.tenantId,id])).rows;check(!r.result_id||results.some(x=>x.id===r.result_id),'measurement_evidence_unavailable',403);return {r,p,plans,history,results,role:s.role,userId:s.userId};});}
 async function authorized(id){const data=await raw(id),definition=data.r.provenance.definition;const q=new URLSearchParams(definition.provenance.query);q.set('detail_hash',definition.detail_hash);const detail=await createDetailService({database}).get({kind:'problem',id:definition.problem_id,query:q});await snapshots.get({snapshotId:data.p?.baseline_ref??data.r.baseline_ref});for(const result of data.results)await snapshots.get({snapshotId:result.post_snapshot_id});return {...data,detail};}
 async function verifyProjection(snapshotId,filters,metric,mappingIds,expected){const view=await snapshots.get({snapshotId});await tx('read',async s=>{const row=await one(s,'SELECT * FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,snapshotId]),st={};for(const table of tables){const ids=row.input_manifest.refs.filter(x=>x.table===table&&x.authorized&&x.active).map(x=>x.id);st[table]=ids.length?(await s.query(`SELECT * FROM public.${table} WHERE tenant_id=$1 AND id=ANY($2::uuid[])`,[s.tenantId,ids])).rows:[];check(st[table].length===ids.length,'projection_refs_unavailable',403);}const mappings=mappingIds.length?(await s.query('SELECT * FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,mappingIds])).rows:[];check(mappings.length===mappingIds.length,'projection_mapping_unavailable',403);for(const m of mappings)check((await one(s,"SELECT public.intervention_member($1,$2,array['owner']) AS ok",[s.tenantId,m.actor_id])).ok,'projection_actor_unavailable',403);const computed=projection(s,{row,view},st,mappings,filters);const result=metric==='exposure'?computed.exposure.global:computed[metric];check(result.amountMinor===expected.amountMinor&&result.knownSubtotalMinor===expected.knownSubtotalMinor,'measurement_projection_conflict',409);});}
 async function view(data){const {r,p,plans,history,results,role,userId,detail}=data;const metadata=await tx('read',async s=>({members:(await s.query('SELECT * FROM public.recommendation_members($1)',[s.tenantId])).rows,ids:(await s.query("SELECT id FROM public.metric_snapshots WHERE tenant_id=$1 AND status='published' AND economic_schema_version='economic-snapshot-v1' ORDER BY as_of DESC,id",[s.tenantId])).rows}));const context=await snapshots.get({snapshotId:r.baseline_ref}),options=[];for(const {id} of metadata.ids){let snap;try{snap=await snapshots.get({snapshotId:id});}catch(e){if([403,404].includes(e.status))continue;throw e;}const reasons=[];for(const k of ['currency','exponent','basis','timezone','dateBasis'])if(snap.scope[k]!==context.scope[k])reasons.push('SCOPE_MISMATCH');if(snap.versions.policy!==context.versions.policy||snap.versions.schema!==context.versions.schema)reasons.push('METRIC_VERSION_MISMATCH');options.push({id:snap.id,asOf:snap.asOf,start:snap.scope.start,end:snap.scope.end,currency:snap.scope.currency,exponent:snap.scope.exponent,basis:snap.scope.basis,scopeHash:snap.scopeHash,policyVersion:snap.versions.policy,eligible:reasons.length===0,reasons});}
 const ownerActive=metadata.members.some(x=>x.id===r.owner_id&&['owner','operator'].includes(x.role));const canExecute=ownerActive&&(role==='owner'||role==='operator'&&r.owner_id===userId);
 return {id:r.id,version:r.version,status:r.status,recommendationId:r.recommendation_id,recommendationVersion:r.recommendation_version,title:r.provenance.definition.title,hypothesis:r.hypothesis,ownerId:r.owner_id,baselineSnapshotId:p?.baseline_ref??r.baseline_ref,recommendationSnapshotId:r.baseline_ref,scopeHash:r.provenance.scopeHash,scope:detail.scope,metricDefinitionVersion:context.versions.policy,baselineOptions:options.map(x=>{const reasons=[...x.reasons,...(x.asOf<x.end?['BASELINE_INCOMPLETE']:[])];return {...x,eligible:reasons.length===0,reasons};}),plan:p?.provenance.plan??null,planVersion:p?.version??null,planHistory:plans.filter(x=>!p||x.version<=p.version).map(x=>({version:x.version,plan:x.provenance.plan,actorId:x.provenance.actorId,createdAt:iso(x.created_at)})),actualStart:iso(r.actual_start),actualEnd:iso(r.actual_end),reason:r.reason,history:history.filter(h=>h.version<=r.version).map(h=>({version:h.version,status:h.definition.status,reason:h.definition.reason,actorId:h.actor_id,requestKey:h.request_key,createdAt:iso(h.created_at)})),measurements:results.filter(x=>!r.result_id||x.created_at<=results.find(y=>y.id===r.result_id)?.created_at).map(x=>({id:x.id,...x.result,measuredAt:iso(x.created_at)})),members:metadata.members,snapshotOptions:options.map(x=>{const reasons=[...x.reasons,...(!r.actual_end||x.start<iso(r.actual_end)?['POST_BEFORE_IMPLEMENTATION']:[])];return {...x,eligible:reasons.length===0,reasons};}),currentResultId:r.result_id??null,canClose:canExecute&&r.status==='measuring'&&results.some(x=>x.id===r.result_id&&x.result.status==='complete'),canReopen:role==='owner'&&r.status==='closed',canAssign:role==='owner'&&!['closed','cancelled'].includes(r.status),canEditPlan:role!=='viewer'&&r.status==='draft',canApprove:role==='owner'&&r.status==='draft'&&!!p,canExecute,canCancel:role==='owner'&&!['closed','cancelled'].includes(r.status),executionEnabled:false,causalClaim:false};}
 function common(q,keys){strict(q,['id','expectedVersion','requestKey','reason',...keys]);check(uuid(q.id),'intervention_not_found',404);check(Number.isInteger(q.expectedVersion)&&q.expectedVersion>0&&text(q.requestKey,1,128)&&text(q.reason),'request_invalid');}
 async function mutate(q,action,operation,work){const initial=await authorized(q.id);check(action==='propose'?initial.role!=='viewer':action==='approve'?initial.role==='owner':initial.role==='owner'||initial.role==='operator'&&initial.r.owner_id===initial.userId,'role_insufficient',403);const fingerprint=hash({operation,...q});const replay=initial.history.find(h=>h.request_key===q.requestKey);if(replay){check(replay.fingerprint===fingerprint,'idempotency_conflict',409);initial.r=replay.definition;initial.p=replay.definition.plan_id?await tx('read',s=>one(s,'SELECT * FROM public.measurement_plans WHERE tenant_id=$1 AND id=$2',[s.tenantId,replay.definition.plan_id])):null;return view(initial);}let row;await tx(action,async s=>{await s.query('SELECT id FROM public.interventions WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[s.tenantId,q.id]);const replay=await one(s,'SELECT * FROM public.intervention_events WHERE tenant_id=$1 AND intervention_id=$2 AND request_key=$3',[s.tenantId,q.id,q.requestKey]);if(replay){check(replay.fingerprint===fingerprint,'idempotency_conflict',409);row=replay.definition;return;}const current=await one(s,'SELECT * FROM public.interventions WHERE tenant_id=$1 AND id=$2',[s.tenantId,q.id]);check(current&&current.version===q.expectedVersion,'version_conflict',409);check((await one(s,'SELECT public.intervention_authorized($1,$2) AS ok',[s.tenantId,q.id])).ok,'intervention_unavailable',403);const delta=await work(s,current);const values=[s.tenantId,q.id,q.expectedVersion,s.userId,q.requestKey,fingerprint,q.reason],sets=['version=version+1','last_actor_id=$4','last_request_key=$5','last_fingerprint=$6','reason=$7'];for(const [key,value] of Object.entries(delta)){values.push(value);sets.push(key+'=$'+values.length);}row=await one(s,`UPDATE public.interventions SET ${sets.join(',')} WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING *`,values);check(row,'version_conflict',409);});const data=await authorized(q.id);if(row.version!==data.r.version){data.r={...row,created_at:new Date(row.created_at),actual_start:row.actual_start,actual_end:row.actual_end};data.p=row.plan_id?await tx('read',s=>one(s,'SELECT * FROM public.measurement_plans WHERE tenant_id=$1 AND id=$2',[s.tenantId,row.plan_id])):null;}return view(data);}
 return {
 async list(input={}){strict(input,['query']);let context=null;if(input.query){check(input.query instanceof URLSearchParams,'scope_invalid');const q=new URLSearchParams(input.query);for(const k of ['resource','cursor','limit','format'])check(!q.has(k),'unsupported_filter');q.set('resource','problems');context=await createWorkspaceService({database}).query(q,{all:true});}const ids=await tx('read',async s=>(await s.query("SELECT id FROM public.interventions WHERE tenant_id=$1 AND provenance->>'kind'='recommendation-draft-v1' AND ($2::uuid IS NULL OR baseline_ref=$2 AND provenance->>'scopeHash'=$3) ORDER BY created_at DESC,id",[s.tenantId,context?.meta.snapshot_id??null,context?.meta.scope_hash??null])).rows);const items=[];let unavailableCount=0;for(const {id} of ids){try{items.push(await view(await authorized(id)));}catch(e){if([403,404].includes(e.status))unavailableCount++;else throw e;}}return {items,unavailableCount};},
 async get({id}){return view(await authorized(id));},
 async savePlan(q){common(q,['plan']);const plan=validatePlan(q.plan);await snapshots.get({snapshotId:plan.baselineSnapshotId});return mutate({...q,plan},'propose','plan',async(s,r)=>{check(r.status==='draft'&&plan.scopeHash===r.provenance.scopeHash,'plan_frozen',409);const v=await one(s,'SELECT coalesce(max(version),0)+1 AS version FROM public.measurement_plans WHERE tenant_id=$1 AND intervention_id=$2',[s.tenantId,r.id]);const row=await one(s,'INSERT INTO public.measurement_plans(tenant_id,version,unit,population_ref,date_start,date_end,intervention_id,baseline_ref,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[s.tenantId,v.version,plan.unit,plan.population,plan.start,plan.end,r.id,plan.baselineSnapshotId,JSON.stringify({plan})]);return {plan_id:row.id,measurement_ref:row.id,owner_id:plan.ownerId,hypothesis:plan.hypothesis};});},
 async transition(q){common(q,['target','actualStart','actualEnd']);check(typeof q.target==='string','target_invalid');if(q.actualStart!==undefined)check(instant(q.actualStart),'actual_start_invalid');if(q.actualEnd!==undefined)check(instant(q.actualEnd),'actual_end_invalid');check((q.target==='active'||q.actualStart===undefined)&&(q.target==='measuring'||q.actualEnd===undefined),'unexpected_actual_date');const before=await authorized(q.id);const reopening=before.r.status==='closed'&&q.target==='measuring';return mutate(q,reopening||['approved','cancelled'].includes(q.target)?'approve':'execute','transition',async(s,r)=>{assertTransition(r,q.target,s.role,s.userId);if(q.target==='active')check(q.actualStart,'actual_start_required',409);if(q.target==='measuring'&&r.status!=='closed')check(q.actualEnd,'actual_end_required',409);return {status:q.target,...(r.status==='closed'?{result_id:null}:{}),...(q.actualStart?{actual_start:q.actualStart}:{}),...(q.actualEnd?{actual_end:q.actualEnd}:{})};});},
 async assign(q){common(q,['ownerId']);check(uuid(q.ownerId),'owner_invalid');return mutate(q,'approve','assign',async(s,r)=>{check(s.role==='owner','owner_required',403);check(!['closed','cancelled'].includes(r.status)&&r.owner_id!==q.ownerId,'assignment_invalid',409);return {owner_id:q.ownerId};});},
 async measure(q){common(q,['postSnapshotId']);check(uuid(q.postSnapshotId),'snapshot_not_found',404);await snapshots.get({snapshotId:q.postSnapshotId});return mutate(q,'execute','measure',async(s,r)=>{check(r.status==='measuring','measurement_state_invalid',409);const result=await one(s,'INSERT INTO public.intervention_results(tenant_id,intervention_id,plan_id,post_snapshot_id,actor_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[s.tenantId,r.id,r.plan_id,q.postSnapshotId,s.userId]);const p=await one(s,'SELECT * FROM public.measurement_plans WHERE tenant_id=$1 AND id=$2',[s.tenantId,r.plan_id]);for(const [id,expected] of [[p.baseline_ref,result.result.baselineProjection],[q.postSnapshotId,result.result.postProjection]])await verifyProjection(id,p.provenance.filters,p.provenance.plan.outcome,expected.mappingIds,expected);return {result_id:result.id};});}
 };
}
