// Adapted from the reviewed laboratory intervention state machine (5fbf223).
// Durable CAS, idempotency and measurement authorization live in the repository/SQL.
import {check,uuid} from '../workspace-service/contracts.mjs';
export const transitions=Object.freeze({draft:Object.freeze(['approved','cancelled']),approved:Object.freeze(['active','cancelled']),active:Object.freeze(['measuring','cancelled']),measuring:Object.freeze(['closed','cancelled']),closed:Object.freeze(['measuring']),cancelled:Object.freeze([])});
export const text=(x,min=20,max=2000)=>typeof x==='string'&&x.trim()===x&&x.length>=min&&x.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(x);
export function instant(x){if(typeof x!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(x)||!Number.isFinite(Date.parse(x)))return false;return new Date(x).toISOString()===(x.includes('.')?x.replace(/\.(\d{1,3})Z$/,(_,d)=>'.'+d.padEnd(3,'0')+'Z'):x.replace('Z','.000Z'));}
export function strict(q,keys){check(q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>keys.includes(k)),'input_invalid');}
export function validatePlan(p){strict(p,['hypothesis','ownerId','start','end','unit','population','outcome','controlPlan','metricDefinitionVersion','baselineSnapshotId','scopeHash','maturityDays','concurrentChanges']);check(text(p.hypothesis)&&uuid(p.ownerId)&&instant(p.start)&&instant(p.end)&&Date.parse(p.start)<Date.parse(p.end)&&['order','customer'].includes(p.unit)&&text(p.population,10)&&['allOrders','exposure','refunds'].includes(p.outcome)&&text(p.controlPlan,10)&&text(p.metricDefinitionVersion,1,200)&&uuid(p.baselineSnapshotId)&&/^[a-f0-9]{64}$/.test(p.scopeHash)&&Number.isInteger(p.maturityDays)&&p.maturityDays>=0&&p.maturityDays<=365&&text(p.concurrentChanges,10),'plan_invalid');return {...p,start:new Date(p.start).toISOString(),end:new Date(p.end).toISOString()};}
export function assertTransition(current,target,role,userId){check(transitions[current.status]?.includes(target),'invalid_transition',409);if(current.status==='closed'||['approved','cancelled'].includes(target))check(role==='owner','owner_required',403);else check(role==='owner'||role==='operator'&&current.owner_id===userId,'assigned_operator_required',403);}
