import {check,canonical} from '../workspace-service/contracts.mjs';
import {formatMinorUnits} from '../metrics/money.mjs';
export const TEMPLATE='brief-observed-v1';
const cmp=(a,b)=>a<b?-1:a>b?1:0;
const minor=x=>x===null||typeof x==='string'&&x.length<=4096&&/^(0|-?[1-9]\d*)$/.test(x);
function metric(m,scope){check(m&&m.currency===scope.currency&&(scope.exponent===null||m.exponent===scope.exponent)&&Number.isInteger(m.exponent)&&m.exponent>=0&&m.exponent<=4&&minor(m.amount_minor)&&minor(m.known_subtotal),'brief_metric_scope_conflict',409);check(m.coverage&&Number.isSafeInteger(m.coverage.known_n)&&Number.isSafeInteger(m.coverage.eligible_n)&&m.coverage.known_n>=0&&m.coverage.eligible_n>=m.coverage.known_n,'brief_metric_coverage_invalid',409);}
export function buildBrief(input){
 const x=structuredClone(input);check(x.scope?.snapshot_id===x.snapshotId&&x.scope?.scope_hash===x.scopeHash,'brief_scope_conflict',409);
 check(Array.isArray(x.metrics)&&Array.isArray(x.problems)&&Array.isArray(x.actions),'brief_input_invalid');
 for(const m of x.metrics)metric(m,x.scope);for(const p of x.problems){for(const m of p.metrics)metric(m,x.scope);check(Array.isArray(p.evidence)&&p.evidence.length>0&&p.evidenceCount===p.evidence.length,'brief_evidence_required',409);p.evidence.sort((a,b)=>cmp(canonical(a),canonical(b)));p.metrics.sort((a,b)=>cmp(a.kind,b.kind));}
 check(new Set(x.problems.map(p=>p.id)).size===x.problems.length,'brief_problem_duplicate',409);
 const rank=(a,b)=>Number(b.rankingBasis==='published_priority')-Number(a.rankingBasis==='published_priority')||(a.rankingBasis==='published_priority'?(a.rank??Infinity)-(b.rank??Infinity):b.evidenceCount-a.evidenceCount)||cmp(a.id,b.id);
 x.problems.sort(rank);x.metrics.sort((a,b)=>cmp(a.kind,b.kind));x.actions.sort((a,b)=>cmp(a.kind,b.kind)||cmp(a.id,b.id)||a.version-b.version);
 const c=x.comparison;check(c&&['available','not_comparable','not_requested'].includes(c.status)&&c.causalClaim===false,'brief_comparison_invalid',409);
 for(const m of c.metrics){check(m.currency===x.scope.currency&&(x.scope.exponent===null||m.exponent===x.scope.exponent)&&minor(m.previousAmountMinor)&&minor(m.currentAmountMinor)&&minor(m.deltaMinor),'brief_comparison_scope_conflict',409);const current=x.metrics.find(v=>v.kind===m.kind);check(current&&current.amount_minor===m.currentAmountMinor,'brief_comparison_current_conflict',409);check(m.deltaMinor===(c.status==='available'&&m.currentAmountMinor!==null&&m.previousAmountMinor!==null?(BigInt(m.currentAmountMinor)-BigInt(m.previousAmountMinor)).toString():null),'brief_comparison_delta_conflict',409);}
 c.metrics.sort((a,b)=>cmp(a.kind,b.kind));c.reasons=[...new Set(c.reasons)].sort();
 return {templateVersion:TEMPLATE,snapshotId:x.snapshotId,scopeHash:x.scopeHash,baseScopeHash:x.baseScopeHash,scope:x.scope,asOf:x.asOf,watermark:x.watermark,coverage:x.coverage,metrics:x.metrics,top3:x.problems.slice(0,3),critical:x.problems.filter(p=>p.critical),actions:x.actions,comparison:c,limits:['Las filas por problema no son aditivas; la exposición global cuenta cada orden una sola vez.','Exposición no equivale a pérdida, ahorro ni ingreso recuperado.','Las citas acreditan evidencia conversacional, no causalidad ni importes contables.','La comparación describe una asociación entre cortes; no atribuye un efecto causal.',...(x.problems.some(p=>p.rankingBasis==='evidence_count')?['Sin ranking publicado aplicable: orden por número de citas autorizadas, con desempate por identificador; no es una probabilidad ni un ranking económico.']:[])],forecast:{status:'not_estimable',reason:'Este brief describe cifras observadas. No estima escenarios ni probabilidades a partir de citas.'},generatedBy:'deterministic-template-no-LLM',sent:false,problemRowsAreAdditive:false,causalClaim:false};
}
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function briefHtml(brief){
 const d=brief.document,money=m=>m.amount_minor===null?'Total desconocido'+(m.known_subtotal===null?'':'; subtotal conocido '+formatMinorUnits(m.known_subtotal,m.currency,m.exponent)):formatMinorUnits(m.amount_minor,m.currency,m.exponent);
 const metrics=rows=>'<ul>'+rows.map(m=>'<li>'+escape(m.label)+': '+escape(money(m))+' · cobertura '+escape(m.coverage.known_n)+'/'+escape(m.coverage.eligible_n)+'</li>').join('')+'</ul>';
 const problems=rows=>rows.map(p=>'<article><h3>'+escape(p.title)+'</h3><p>Problema '+escape(p.id)+' · versión '+escape(p.version)+'</p>'+metrics(p.metrics)+p.evidence.map(e=>'<blockquote>'+escape(e.quote)+'<footer>Extracción '+escape(e.runId)+' · revisión '+escape(e.messageRevisionId)+' · '+escape(e.role)+'</footer></blockquote>').join('')+'</article>').join('');
 return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Brief '+escape(brief.id)+'</title></head><body><main><h1>Brief observado · versión '+escape(brief.version)+'</h1><p>ID '+escape(brief.id)+' · contenido '+escape(brief.contentHash)+'</p><p>Snapshot '+escape(d.snapshotId)+' · alcance '+escape(d.scopeHash)+'</p><p>'+escape(d.scope.date_start)+' ≤ período &lt; '+escape(d.scope.date_end)+' · '+escape(d.scope.currency)+' · '+escape(d.scope.basis)+' · '+escape(d.scope.timezone)+'</p><p>SKU: '+escape(d.scope.sku.join(', ')||'Todos')+' · fuentes: '+escape(d.scope.source.join(', ')||'Todas')+' · corte '+escape(d.asOf)+' · watermark '+escape(d.watermark)+'</p><h2>Cifras observadas</h2>'+metrics(d.metrics)+'<h2>Tres problemas destacados</h2>'+problems(d.top3)+'<h2>Carril crítico independiente</h2>'+problems(d.critical)+'<h2>Acciones capturadas</h2><ul>'+d.actions.map(a=>'<li>'+escape(a.title)+' · '+escape(a.status)+' · versión '+escape(a.version)+'<p>'+escape(a.summary)+'</p></li>').join('')+'</ul><h2>Cambios observados</h2><p>'+escape(d.comparison.status)+' · '+escape(d.comparison.reasons.join(', '))+'</p><ul>'+d.comparison.metrics.map(m=>'<li>'+escape(m.kind)+': '+escape(m.deltaMinor===null?'Cambio no estimable':formatMinorUnits(m.deltaMinor,m.currency,m.exponent))+'</li>').join('')+'</ul><h2>Límites</h2><ul>'+d.limits.map(l=>'<li>'+escape(l)+'</li>').join('')+'</ul><p>'+escape(d.forecast.reason)+'</p><p>Generado con plantilla determinística. No enviado por correo.</p></main></body></html>';
}
