import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID,createHash} from 'node:crypto';
const controls=process.env.VEXA_CONTROL_ROOT??path.resolve(import.meta.dirname,'../..'),candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'VEXA_CANDIDATE required');
const {launch,candidateInputs}=await import(pathToFileURL(controls+'/tests/acceptance/support/F01-03/harness.mjs'));
const {backend}=await import(pathToFileURL(controls+'/tests/acceptance/support/F01-03/import-uploads/oracles.mjs'));
const q=v=>v===null?'NULL':`'${String(v).replaceAll("'","''")}'`,json=x=>q(JSON.stringify(x))+'::jsonb';
const source=fs.readFileSync(candidate+'/supabase/migrations/0029_notification_outbox.sql','utf8'),originalHash=createHash('sha256').update(source).digest('hex');
const results=[];let h;
const scope=(a,t,action)=>`select set_config('request.jwt.claim.sub',${q(a.id)},true) as ignored \\gset\nselect set_config('vexa.tenant_id',${q(t??'')},true) as ignored \\gset\nselect set_config('vexa.action',${q(action)},true) as ignored \\gset\nset local role vexa_backend;`;
const run=(a,t,action,statement)=>h.json('begin;'+scope(a,t,action)+statement+';commit;');
const probe=(a,t,action,statement,prepare='')=>backend(h,statement.trimEnd().replace(/;?$/,';'),a,t,action,prepare);
const ok=r=>{assert.equal(r.code,'00000',JSON.stringify(r));return r.rows;};
const denied=r=>assert.ok(r.code==='42501'||r.code==='00000'&&Array.isArray(r.rows)&&r.rows.length===0,JSON.stringify(r));
const policy=channel=>({channel,enabled:true,expectedVersion:0,intervalMs:1000,digestWindowMs:0,maxAttempts:5,lifetimeMs:86400000});
let a;
function fixture({channel='email',digestWindowMs=0}={}){const t=randomUUID();h.sql(`insert into organizations(id,name) values(${q(t)},'SYN F0609 gate410');insert into memberships(tenant_id,user_id,role,status) values ${[['owner','owner'],['worker','analyst'],['viewer','viewer'],['operator','operator']].map(([u,r])=>`(${q(t)},${q(a[u].id)},${q(r)},'active')`).join(',')};insert into worker_delegations(tenant_id,user_id,enabled) values(${q(t)},${q(a.worker.id)},true);`);const p={...policy(channel),digestWindowMs};run(a.owner,t,'configure',`select public.notification_policy_set(${json(p)})`);h.sql('begin;'+scope(a.viewer,t,'notify')+`insert into notification_preferences(tenant_id,user_id,channel,event_type,enabled,version) values(${q(t)},${q(a.viewer.id)},${q(channel)},'*',true,1),(${q(t)},${q(a.viewer.id)},${q(channel)},'membership.welcome',true,1);commit;`);return {t,channel,p};}
const enqueue=(f,eventId=randomUUID())=>{const payload={eventId,type:'membership.welcome',resourceId:a.viewer.id,userId:a.viewer.id,channel:f.channel};return {id:run(a.owner,f.t,'import',`select to_jsonb(public.notification_enqueue(${json(payload)}))`),payload};};
const claim=f=>run(a.worker,f.t,'import',"select coalesce(public.notification_claim(30000),'null'::jsonb)");
const begin=(f,c)=>run(a.worker,f.t,'import',`select public.notification_begin_send(${q(c.id)},${q(c.fencing_token)}::bigint,true)`);
const finish=(f,c,result)=>run(a.worker,f.t,'import',`select public.notification_finish(${q(c.id)},${q(c.fencing_token)}::bigint,${json(result)})`);
const proof=(f,c,decision='not_sent')=>({tenant_id:f.t,id:randomUUID(),job_id:c.id,fence:c.fencing_token,decision,idempotency_key:c.idempotency_key,provider_id:decision==='accepted'?'SYN_PROVIDER':null,proof_hash:'a'.repeat(64)});
const rec=(c,p)=>({id:c.id,expectedFence:c.fencing_token,decision:p.decision,evidenceId:p.id,requestKey:randomUUID(),idempotencyKey:c.idempotency_key,providerId:p.provider_id});
function insertProof(p){h.sql(`begin;set local role vexa_notification_verifier;insert into notification_reconciliation_evidence(${Object.keys(p).join(',')}) values(${Object.values(p).map(q).join(',')});commit;`);}
const functionSource=name=>{const start=source.indexOf('create function public.'+name+'('),end=source.indexOf('end $$;',start);assert.ok(start>=0&&end>start);return source.slice(start,end+7).replace('create function','create or replace function');};
async function group(t,name,fn){await t.test(name,async()=>{await fn();results.push(name);});}
test('inapp producer revocation after begin prevents local effect',async()=>{process.env.VEXA_F01_03_PORT_BASE??='58450';h=await launch({services:true});try{for(const ddl of candidateInputs(candidate))h.sql(ddl);a={};for(const k of ['owner','worker','viewer','operator','outsider'])a[k]=await h.user();const f=fixture({channel:'inapp'});h.sql(`insert into memberships(tenant_id,user_id,role,status) values(${q(f.t)},${q(a.outsider.id)},'owner','active');update notification_delivery_policies set actor_id=${q(a.outsider.id)} where tenant_id=${q(f.t)}`);enqueue(f);const c=claim(f);assert.equal(begin(f,c).kind,'ready');h.sql(`update memberships set status='revoked' where tenant_id=${q(f.t)} and user_id=${q(a.owner.id)}`);const done=finish(f,c,{kind:'accepted',providerId:'SYN_INAPP'});const count=Number(h.sql(`select count(*) from notification_inbox where tenant_id=${q(f.t)}`));if(process.env.VEXA_OUTBOX_SQL_REPORT)fs.writeFileSync(process.env.VEXA_OUTBOX_SQL_REPORT,JSON.stringify({done,count,sqlSHA256:originalHash},null,2));assert.equal(done.state,'suppressed','F0609_INAPP_PRODUCER_REVOKED');assert.equal(count,0,'F0609_INAPP_PRODUCER_REVOKED_NO_EFFECT');}finally{h.close();}});
