import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID,createHash} from 'node:crypto';
const controls=process.env.VEXA_CONTROL_ROOT??path.resolve(import.meta.dirname,'../..'),candidate=process.env.VEXA_CANDIDATE;assert.ok(candidate,'VEXA_CANDIDATE required');
const {launch,candidateInputs}=await import(pathToFileURL(controls+'/tests/acceptance/support/F01-03/harness.mjs'));
const {backend}=await import(pathToFileURL(controls+'/tests/acceptance/support/F01-03/import-uploads/oracles.mjs'));
const q=v=>v===null?'NULL':`'${String(v).replaceAll("'","''")}'`,json=x=>q(JSON.stringify(x))+'::jsonb';
const source=fs.readFileSync(candidate+'/supabase/migrations/0029_notification_outbox.sql','utf8'),originalHash=createHash('sha256').update(source).digest('hex');
const results=[];let h;
const scope=(a,t,action)=>`select set_config('request.jwt.claim.sub',${q(a.id)},true) as ignored \\gset\nselect set_config('vexa.tenant_id',${q(t??'')},true) as ignored \\gset\nselect set_config('vexa.action',${q(action)},true) as ignored \\gset\nset local role vexa_backend;`;
const run=(a,t,action,statement)=>h.json('begin;'+scope(a,t,action)+statement+';commit;');
const probe=(a,t,action,statement,prepare='')=>backend(h,statement.trimEnd().replace(/;?$/,';'),a,t,action,prepare);
const ok=r=>{assert.equal(r.code,'00000',JSON.stringify(r));return r.rows;};
const denied=r=>assert.ok(r.code==='42501'||r.code==='00000'&&Array.isArray(r.rows)&&r.rows.length===0,JSON.stringify(r));
const policy=channel=>({channel,enabled:true,expectedVersion:0,intervalMs:1000,digestWindowMs:0,maxAttempts:5,lifetimeMs:86400000});
let a;
function fixture({channel='email',digestWindowMs=0}={}){const t=randomUUID();h.sql(`insert into organizations(id,name) values(${q(t)},'SYN F0609 gate410');insert into memberships(tenant_id,user_id,role,status) values ${[['owner','owner'],['worker','analyst'],['viewer','viewer'],['operator','operator']].map(([u,r])=>`(${q(t)},${q(a[u].id)},${q(r)},'active')`).join(',')};insert into worker_delegations(tenant_id,user_id,enabled) values(${q(t)},${q(a.worker.id)},true);`);const p={...policy(channel),digestWindowMs};run(a.owner,t,'configure',`select public.notification_policy_set(${json(p)})`);h.sql('begin;'+scope(a.viewer,t,'notify')+`insert into notification_preferences(tenant_id,user_id,channel,event_type,enabled,version) values(${q(t)},${q(a.viewer.id)},${q(channel)},'*',true,1),(${q(t)},${q(a.viewer.id)},${q(channel)},'membership.welcome',true,1);commit;`);return {t,channel,p};}
const enqueue=(f,eventId=randomUUID())=>{const payload={eventId,type:'membership.welcome',resourceId:a.viewer.id,userId:a.viewer.id,channel:f.channel};return {id:run(a.owner,f.t,'import',`select to_jsonb(public.notification_enqueue(${json(payload)}))`),payload};};
const claim=f=>run(a.worker,f.t,'import',"select coalesce(public.notification_claim(30000),'null'::jsonb)");
const begin=(f,c)=>run(a.worker,f.t,'import',`select public.notification_begin_send(${q(c.id)},${q(c.fencing_token)}::bigint,true)`);
const finish=(f,c,result)=>run(a.worker,f.t,'import',`select public.notification_finish(${q(c.id)},${q(c.fencing_token)}::bigint,${json(result)})`);
const proof=(f,c,decision='not_sent')=>({tenant_id:f.t,id:randomUUID(),job_id:c.id,fence:c.fencing_token,decision,idempotency_key:c.idempotency_key,provider_id:decision==='accepted'?'SYN_PROVIDER':null,proof_hash:'a'.repeat(64)});
const rec=(c,p)=>({id:c.id,expectedFence:c.fencing_token,decision:p.decision,evidenceId:p.id,requestKey:randomUUID(),idempotencyKey:c.idempotency_key,providerId:p.provider_id});
function insertProof(p){h.sql(`begin;set local role vexa_notification_verifier;insert into notification_reconciliation_evidence(${Object.keys(p).join(',')}) values(${Object.values(p).map(q).join(',')});commit;`);}
const functionSource=name=>{const start=source.indexOf('create function public.'+name+'('),end=source.indexOf('end $$;',start);assert.ok(start>=0&&end>start);return source.slice(start,end+7).replace('create function','create or replace function');};
async function group(t,name,fn){await t.test(name,async()=>{await fn();results.push(name);});}
test('F06-09 independent SQL invariants on current full migration chain',async t=>{
 process.env.VEXA_F01_03_PORT_BASE??='58450';h=await launch({services:true});try{
 for(const ddl of candidateInputs(candidate))h.sql(ddl);
 a={};for(const k of ['owner','worker','viewer','operator','outsider'])a[k]=await h.user();
 await group(t,'six tables enforce RLS, tenant FKs and exact least privilege',()=>{const tables=['notification_delivery_policies','notification_outbox','notification_outbox_items','notification_dispatch_limits','notification_reconciliation_evidence','notification_reconciliations'];const schema=h.json(`select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'nonnull',a.attnotnull)) from pg_class c join pg_attribute a on a.attrelid=c.oid and a.attname='tenant_id' where c.oid=any(array[${tables.map(x=>q('public.'+x)+'::regclass').join(',')}])`);assert.equal(schema.length,6);for(const row of schema)assert.ok(row.rls&&row.force&&row.nonnull,row.name);
 const grants=h.json(`select jsonb_agg(jsonb_build_object('table',tb,'role',ro,'priv',pr,'allowed',has_table_privilege(ro,tb,pr))) from unnest(array[${tables.map(q).join(',')}])tb cross join unnest(array['anon','authenticated','service_role','vexa_backend','vexa_notification_verifier'])ro cross join unnest(array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])pr`);for(const g of grants){const allow=g.table==='notification_reconciliation_evidence'?g.role==='vexa_notification_verifier'&&['INSERT','SELECT'].includes(g.priv):g.role==='vexa_backend'&&g.priv==='SELECT';assert.equal(g.allowed,allow,JSON.stringify(g));}
 const fks=h.json(`select jsonb_agg(jsonb_build_object('child',c.conrelid::regclass::text,'parent',c.confrelid::regclass::text,'validated',c.convalidated,'mapping',(select jsonb_object_agg(a.attname,b.attname) from unnest(c.conkey,c.confkey)k(x,y) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.x join pg_attribute b on b.attrelid=c.confrelid and b.attnum=k.y))) from pg_constraint c where c.contype='f' and c.conrelid=any(array[${tables.map(x=>q(x)+'::regclass').join(',')}])`);assert.equal(fks.length,16);for(const fk of fks)assert.ok(fk.validated&&fk.mapping.tenant_id===(fk.parent==='organizations'?'id':'tenant_id'),JSON.stringify(fk));
 assert.equal(h.sql("select has_schema_privilege('vexa_notification_verifier','public','CREATE')"),'f');for(const role of ['anon','authenticated','service_role','vexa_backend'])assert.equal(h.sql(`select pg_has_role(${q(role)},'vexa_notification_verifier','MEMBER')`),'f');
 });
 await group(t,'event job and outbox roll back atomically and idempotent enqueue stays unique',()=>{const f=fixture();const e=randomUUID(),input={eventId:e,type:'membership.welcome',resourceId:a.viewer.id,userId:a.viewer.id,channel:'email'};const r=probe(a.owner,f.t,'import',`perform public.notification_enqueue(${json(input)});raise exception 'SYN410_FORCE_ROLLBACK';`);assert.equal(r.code,'P0001');assert.equal(h.sql(`select count(*) from notification_events where tenant_id=${q(f.t)}`),'0');assert.equal(h.sql(`select count(*) from jobs where tenant_id=${q(f.t)}`),'0');assert.equal(h.sql(`select count(*) from notification_outbox where tenant_id=${q(f.t)}`),'0');const x=enqueue(f,e),y=enqueue(f,e);assert.equal(x.id,y.id);assert.equal(h.sql(`select count(*) from notification_outbox_items where tenant_id=${q(f.t)}`),'1');assert.equal(probe(a.owner,f.t,'import',`select to_jsonb(public.notification_enqueue(${json({...input,resourceId:a.owner.id})})) into result`).code,'23505');});
 await group(t,'nonexistent receipt cannot release uncertainty, genuine receipt immutable and replay bound',()=>{const f=fixture();enqueue(f);const c=claim(f);assert.equal(begin(f,c).kind,'ready');assert.equal(finish(f,c,{kind:'uncertain'}).state,'uncertain');const p=proof(f,c),r=rec(c,p);const check=()=>assert.equal(probe(a.owner,f.t,'configure',`select public.notification_reconcile(${json(r)}) into result`).code,'42501','F0609_RECEIPT_UUID_NOT_EVIDENCE');check();
 // Causal regression mutant: remove only the new evidence check in this owned database, then restore.
 const sql=functionSource('notification_reconcile'),anchor=" if not exists(select 1 from public.notification_reconciliation_evidence where tenant_id=t and id=(p->>'evidenceId')::uuid and job_id=(p->>'id')::uuid and fence=(p->>'expectedFence')::bigint and decision=p->>'decision' and idempotency_key=p->>'idempotencyKey' and provider_id is not distinct from p->>'providerId') then raise insufficient_privilege;end if;";assert.ok(sql.includes(anchor));const fk=h.json(`select jsonb_build_object('name',conname,'def',pg_get_constraintdef(oid)) from pg_constraint where conrelid='notification_reconciliations'::regclass and confrelid='notification_reconciliation_evidence'::regclass`);try{h.sql(`alter table notification_reconciliations drop constraint ${fk.name}`);h.sql(sql.replace(anchor,''));assert.throws(check,e=>e.code==='ERR_ASSERTION'&&e.message.includes('F0609_RECEIPT_UUID_NOT_EVIDENCE'),'MUTANT_MUST_FAIL_SEMANTICALLY');}finally{h.sql(sql);h.sql(`alter table notification_reconciliations add constraint ${fk.name} ${fk.def}`);}check();
 denied(probe(a.owner,f.t,'configure',`insert into notification_reconciliation_evidence(tenant_id,id,job_id,fence,decision,idempotency_key,proof_hash) values(${q(f.t)},${q(p.id)},${q(c.id)},${q(c.fencing_token)},'not_sent',${q(c.idempotency_key)},${q(p.proof_hash)});result:='[]';`));insertProof(p);
 assert.equal(h.probe(`set local role vexa_notification_verifier;update notification_reconciliation_evidence set proof_hash=${q('b'.repeat(64))} where id=${q(p.id)};result:='[]';`).code,'42501');
 const accepted=run(a.owner,f.t,'configure',`select public.notification_reconcile(${json(r)})`);assert.equal(accepted.replayed,false);assert.equal(run(a.owner,f.t,'configure',`select public.notification_reconcile(${json(r)})`).replayed,true);assert.equal(probe(a.owner,f.t,'configure',`select public.notification_reconcile(${json({...r,decision:'accepted',providerId:'SYN_OTHER'})}) into result`).code,'23505');
 });
 await group(t,'preference optout between begin and finish suppresses inbox, mutant detected',()=>{const sql=functionSource('notification_finish');const beginMarker=" if st='accepted' and o.channel='inapp' then\n",start=sql.indexOf(beginMarker),end=sql.indexOf(" if st='accepted' and o.channel='inapp' then insert",start+1);assert.ok(start>0&&end>start);const mutant=sql.slice(0,start)+sql.slice(end);
 const check=()=>{const f=fixture({channel:'inapp'}),x=enqueue(f),c=claim(f);assert.equal(begin(f,c).kind,'ready');h.sql('begin;'+scope(a.viewer,f.t,'notify')+`update notification_preferences set enabled=false,version=version+1 where tenant_id=${q(f.t)} and event_type='*';commit;`);const done=finish(f,c,{kind:'accepted',providerId:'SYN_INAPP'});assert.equal(done.state,'suppressed','F0609_INAPP_REVALIDATES_OPT_OUT');assert.equal(h.sql(`select count(*) from notification_inbox where tenant_id=${q(f.t)} and event_id=${q(x.payload.eventId)}`),'0','F0609_INAPP_NO_EFFECT_AFTER_OPT_OUT');};check();try{h.sql(mutant);assert.throws(check,e=>e.code==='ERR_ASSERTION'&&e.message.includes('F0609_INAPP_REVALIDATES_OPT_OUT'));}finally{h.sql(sql);}check();
 });
 await group(t,'lease and fence survive pre-send recovery but uncertain never retries on TTL',()=>{const f=fixture();enqueue(f);const c=claim(f);assert.equal(claim(f),null);h.sql(`update jobs set lease_until=clock_timestamp()-interval '1 second' where tenant_id=${q(f.t)} and id=${q(c.id)}`);const c2=claim(f);assert.equal(c2.id,c.id);assert.ok(BigInt(c2.fencing_token)>BigInt(c.fencing_token));assert.equal(probe(a.worker,f.t,'import',`select public.notification_begin_send(${q(c.id)},${q(c.fencing_token)},true) into result`).code,'40001');assert.equal(begin(f,c2).kind,'ready');h.sql(`update jobs set lease_until=clock_timestamp()-interval '1 second',deadline=clock_timestamp()-interval '1 second' where tenant_id=${q(f.t)} and id=${q(c.id)}`);assert.equal(claim(f),null);assert.equal(h.sql(`select state from notification_outbox where tenant_id=${q(f.t)} and id=${q(c.id)}`),'uncertain');assert.equal(claim(f),null);assert.equal(h.sql(`select count(*) from dead_letters where tenant_id=${q(f.t)} and job_id=${q(c.id)} and reason='NOTIFICATION_UNCERTAIN'`),'1');});
 await group(t,'current policy, producer, recipient and delegation revalidate before effect',()=>{for(const scenario of ['policy','producer','recipient','delegation']){const f=fixture(),x=enqueue(f),c=claim(f);if(scenario==='producer'){h.sql(`insert into memberships(tenant_id,user_id,role,status) values(${q(f.t)},${q(a.outsider.id)},'owner','active');update notification_delivery_policies set actor_id=${q(a.outsider.id)} where tenant_id=${q(f.t)}`);}if(scenario==='policy')run(a.owner,f.t,'configure',`select notification_policy_set(${json({...policy('email'),enabled:false,expectedVersion:1})})`);else h.sql(scenario==='producer'?`update memberships set status='revoked' where tenant_id=${q(f.t)} and user_id=${q(a.owner.id)}`:scenario==='recipient'?`update memberships set status='revoked' where tenant_id=${q(f.t)} and user_id=${q(a.viewer.id)}`:`update worker_delegations set enabled=false where tenant_id=${q(f.t)}`);const r=probe(a.worker,f.t,'import',`select public.notification_begin_send(${q(c.id)},${q(c.fencing_token)},true) into result`);if(scenario==='delegation')denied(r);else assert.equal(ok(r).kind,scenario==='policy'?'blocked':'suppressed');assert.equal(h.sql(`select attempts from notification_outbox where tenant_id=${q(f.t)} and id=${q(x.id)}`),'0');}});
 await group(t,'quota stays reserved after uncertainty and retry obeys attempts budget',()=>{const f=fixture();enqueue(f);const c=claim(f);assert.equal(begin(f,c).kind,'ready');const limit=h.sql(`select next_allowed_at::text from notification_dispatch_limits where tenant_id=${q(f.t)}`);assert.equal(finish(f,c,{kind:'uncertain'}).state,'uncertain');assert.equal(h.sql(`select next_allowed_at::text from notification_dispatch_limits where tenant_id=${q(f.t)}`),limit);
 const ff=fixture();run(a.owner,ff.t,'configure',`select notification_policy_set(${json({...policy('email'),expectedVersion:1,maxAttempts:1})})`);enqueue(ff);const cc=claim(ff);assert.equal(begin(ff,cc).kind,'ready');assert.equal(finish(ff,cc,{kind:'retry',retryAfterMs:0}).state,'dead');assert.equal(claim(ff),null);
 });
 await group(t,'digest batches only before claim and emits accepted references',()=>{const f=fixture({channel:'inapp',digestWindowMs:1000}),one=enqueue(f),two=enqueue(f);assert.equal(one.id,two.id);h.sql(`update jobs set next_attempt_at=clock_timestamp()-interval '1 second' where tenant_id=${q(f.t)}`);const c=claim(f),third=enqueue(f);assert.notEqual(third.id,c.id);assert.equal(begin(f,c).count,2);assert.equal(finish(f,c,{kind:'accepted',providerId:'SYN_DIGEST'}).state,'accepted');assert.equal(h.sql(`select count(*) from notification_inbox where tenant_id=${q(f.t)}`),'2');});
 await group(t,'private metadata and new RPC boundaries isolate roles and tenants',()=>{const f=fixture();enqueue(f);const c=claim(f);begin(f,c);finish(f,c,{kind:'uncertain'});const read=table=>`select coalesce(jsonb_agg(to_jsonb(z)),'[]') into result from public.${table} z where tenant_id=${q(f.t)}`;
 for(const table of ['notification_outbox','notification_outbox_items','notification_delivery_policies','notification_dispatch_limits','attempts','dead_letters']){assert.ok(ok(probe(a.owner,f.t,'read',read(table))).length>0,table+' positive owner');assert.ok(ok(probe(a.worker,f.t,'read',read(table))).length>0,table+' positive worker');for(const role of ['viewer','operator','outsider'])denied(probe(a[role],f.t,'read',read(table)));denied(probe(a.owner,randomUUID(),'read',read(table)));for(const who of [null,a.owner,a.viewer])denied(h.probe(read(table)+';',who));}
 for(const statement of [`select public.notification_recipient_current(${q(f.t)},${q(a.viewer.id)},'membership.welcome',${q(a.viewer.id)},'email') into result`,`select public.notification_fence(${q(f.t)},${q(c.id)},${q(c.fencing_token)}) into result`,`update public.jobs set state='queued' where tenant_id=${q(f.t)} and id=${q(c.id)};result:='[]'`,`delete from public.notification_outbox where tenant_id=${q(f.t)};result:='[]'`])denied(probe(a.owner,f.t,'import',statement));
 const before=h.sql(`select count(*) from notification_events where tenant_id=${q(f.t)}`);denied(probe(a.viewer,f.t,'import',`select to_jsonb(public.notification_enqueue(${json({eventId:randomUUID(),type:'membership.welcome',resourceId:a.viewer.id,userId:a.viewer.id,channel:'email'})})) into result`));assert.equal(h.sql(`select count(*) from notification_events where tenant_id=${q(f.t)}`),before);
 });
 }finally{if(h)h.close();assert.equal(createHash('sha256').update(fs.readFileSync(candidate+'/supabase/migrations/0029_notification_outbox.sql')).digest('hex'),originalHash,'FROZEN_SQL_CHANGED');if(process.env.VEXA_OUTBOX_SQL_REPORT)fs.writeFileSync(process.env.VEXA_OUTBOX_SQL_REPORT,JSON.stringify({sqlSHA256:originalHash,completedGroups:results,scope:'owned local real Auth and PostgreSQL; no external sends',cleanup:'h.close completed'},null,2));}
});
