// Reuses the durable reservation and gateway contracts exercised by support/F04-budget.
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {boundedWait} from './guards.mjs';import {q} from './harness.mjs';import {logicalClock,digest} from './fixtures.mjs';
export async function budget({h,run,round}){
 const {createDurableBudgetRepository}=await import(pathToFileURL(path.join(h.built,'packages/gateway/durable-budget.mjs')));
 const make=async(cap,suffix)=>{const jobId=randomUUID(),window=`SYN-chaos42-${round}-${suffix}`;h.sql(`INSERT INTO jobs(id,tenant_id,type,state,input_ref,input_hash,version) VALUES(${q(jobId)},${q(h.A.tenant)},'extraction','running','SYN-chaos-budget',${q(randomUUID())},'SYN-v1')`);const repository=createDurableBudgetRepository({database:h.database(),purpose:'extraction',jobId,ownerToken:randomUUID()});await repository.configure({window,purpose:'all',limitMinor:cap});await repository.configure({window,purpose:'extraction',limitMinor:cap});return{repository,window,jobId};};
 const request=(s,amountMinor)=>({tenantId:h.A.tenant,taskKey:randomUUID(),window:s.window,amountMinor,fingerprint:digest(randomUUID()),tenantLimitMinor:'1000000',currency:'USD',exponent:6});
 await run('budget_concurrent_quota',async record=>{const s=await make('100','quota');const results=await Promise.all([s.repository.reserve(request(s,'80')),s.repository.reserve(request(s,'80'))]);assert.equal(results.filter(x=>x.acquired).length,1);assert.equal((await s.repository.reserve(request(s,'21'))).acquired,false);const rows=await s.repository.list({window:s.window});assert.equal(rows.length,1);assert.equal(rows[0].heldMinor,'80');assert.equal(rows[0].actualMinor,null);record.jobId=s.jobId;record.observed={admitted:1,denied:1,limitMinor:'100',heldMinor:'80',actualMinor:null};record.errors.push('BUDGET_EXHAUSTED');});
 await run('llm_timeout_uncertain',async record=>{const s=await make('1000000','timeout'),clock=logicalClock(),now=clock.now(),later=new Date(now+60000).toISOString();const {createGateway}=await import(pathToFileURL(path.join(h.built,'packages/gateway/index.mjs')));const endpoint={model:'synthetic/budget-model',provider:'synthetic/budget-provider',structuredOutput:true,dataCollection:'deny',zdr:true,residency:'eu',contextTokens:200000,privacyAttestation:{version:'SYN-private',residencyEnforced:true,expiresAt:later},pricing:{version:'SYN-pricing',validUntil:later,allChargesIncluded:true,inputMicroUsdPerToken:'1',outputMicroUsdPerToken:'1',overheadTokens:1024}};let calls=0,started=null,resolveStarted;const transportStarted=new Promise(resolve=>{resolveStarted=resolve;});const gateway=createGateway({clock,apiKey:'SYN-local-unusable',runtime:'enabled',budgetRepository:s.repository,catalog:{version:'SYN-catalog',fetchedAt:new Date(now).toISOString(),expiresAt:later,models:[{id:endpoint.model,contextTokens:200000,supportedParameters:['response_format']}]},modelsByRole:{extraction:[endpoint]},policy:{authorized:true,version:'SYN-policy',allowedModels:[endpoint.model],providers:[endpoint.provider],dataCollection:'deny',requireZdr:true,residency:'eu',maxAttempts:1,timeoutMs:10,maxOutputTokens:50,maxInputBytes:100000,maxResponseBytes:100000,maxCostPerCallMinor:'1000000',maxCostPerTaskMinor:'1000000',tenantLimitMinor:'1000000',window:s.window,currency:'USD',exponent:6},fetch:async()=>{calls++;started=h.sql(`SELECT count(*) FROM ai_budget_attempts a JOIN ai_budget_reservations r ON r.tenant_id=a.tenant_id AND r.id=a.reservation_id WHERE r.job_id=${q(s.jobId)} AND a.state='started'`);resolveStarted();return new Promise(()=>{});}});
 const pending=gateway.extract({tenantId:h.A.tenant,taskKey:randomUUID(),role:'extraction',taxonomy:['SYN'],revisions:[{tenant_id:h.A.tenant,message_revision_id:randomUUID(),role:'customer',text:'SYNTHETIC redacted input'}]});await boundedWait(transportStarted,10000,'SYN_TRANSPORT_START_TIMEOUT');clock.advance(10);const result=await pending;assert.equal(calls,1);assert.equal(started,'1');assert.equal(result.error.code,'timeout');assert.equal(result.billingState,'uncertain');const rows=await s.repository.list({window:s.window});assert.equal(rows.length,1);assert.equal(rows[0].state,'uncertain');assert.equal(rows[0].actualMinor,null);assert.ok(BigInt(rows[0].heldMinor)>0n);assert.equal((await s.repository.reserve(request(s,String(1000001n-BigInt(rows[0].heldMinor))))).acquired,false);record.budgetAttempts=h.json(`SELECT coalesce(jsonb_agg(jsonb_build_object('index',a.attempt_index,'state',a.state,'ceilingMinor',a.ceiling_minor::text,'reportedMinor',a.reported_minor::text,'httpStatus',a.http_status) ORDER BY a.attempt_index),'[]') FROM ai_budget_attempts a JOIN ai_budget_reservations r ON r.tenant_id=a.tenant_id AND r.id=a.reservation_id WHERE r.job_id=${q(s.jobId)}`);record.jobId=s.jobId;record.deadline={clock:'logical',timeoutMs:10,start:now,end:clock.now()};record.errors.push('timeout');record.observed={transport:'in-process synthetic; no HTTP',attemptCommittedBeforeTransport:true,calls,state:rows[0].state,heldMinor:rows[0].heldMinor,actualMinor:null,overBudgetDenied:true};});
}
