import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';import {performance} from 'node:perf_hooks';
import {q} from './harness.mjs';import {call,createImport,observed,digest} from './fixtures.mjs';
export async function retention({h,run,round,seed,notes}){
 await run('deleted_source_replay',async record=>{
  const api=async input=>{const response=await h.request(h.A,'/api/recovery',input);assert.equal(response.status,200,JSON.stringify(response.data));return response.data.data;};
  const version=Number(h.sql(`SELECT coalesce((SELECT version FROM retention_policies WHERE tenant_id=${q(h.A.tenant)}),0)`));await api({operation:'policy',expectedVersion:version,backupTtlSeconds:3600});const actor={...h.A,connection:randomUUID()};h.sql(`INSERT INTO connections(id,tenant_id,source,account_id) VALUES(${q(actor.connection)},${q(actor.tenant)},'csv',${q('SYN-chaos-retention-'+round)})`);
  const worker=await h.worker(),crash=await h.worker();notes.processes.push(worker.c.pid,crash.c.pid);
  try{
   const job=await createImport(h,worker,{seed,actor});record.jobId=job.id;record.fixtureHash=job.fixtureHash;assert.equal((await crash.barrier(true)).barrier,true);assert.equal(observed(h,job.id).rows.length,200);
   const source=h.json(`SELECT to_jsonb(s) FROM source_heads s WHERE connection_id=${q(actor.connection)} AND entity_type='message' ORDER BY external_id LIMIT 1`);assert.ok(source);const target={connectionId:actor.connection,entityType:'message',externalId:source.external_id};const preview=await api({operation:'preview',...target});assert.equal(h.sql(`SELECT count(*) FROM retention_ledger WHERE tenant_id=${q(actor.tenant)} AND connection_id=${q(actor.connection)}`),'0','PREVIEW_NO_EFFECT');await api({operation:'erase',token:preview.token,requestId:preview.requestId,confirmed:true});await crash.kill();
   const active=()=>h.json(`SELECT jsonb_build_object('messages',(SELECT count(*) FROM messages WHERE id=${q(source.id)} AND deleted_at IS NULL),'revisions',(SELECT count(*) FROM message_revisions WHERE message_id=${q(source.id)} AND (deleted_at IS NULL OR redacted_text IS NOT NULL OR text_ref NOT LIKE 'deleted:%')),'snapshots',(SELECT count(*) FROM source_revisions WHERE canonical_id=${q(source.id)} AND snapshot<>'[]'::jsonb),'ledger',(SELECT count(*) FROM retention_ledger WHERE tenant_id=${q(actor.tenant)} AND connection_id=${q(actor.connection)} AND entity_type='message' AND external_id=${q(source.external_id)}))`);
   assert.deepEqual(active(),{messages:0,revisions:0,snapshots:0,ledger:1});assert.equal(observed(h,job.id).job.state,'cancelled');const began=performance.now();assert.equal((await h.request(actor,`/api/jobs/${job.id}/replay`,{})).status,200);await call(worker,'consume');assert.deepEqual(active(),{messages:0,revisions:0,snapshots:0,ledger:1});
   const purge=await api({operation:'purge'});assert.equal(purge.complete,true);assert.equal(purge.remaining,0);assert.ok(purge.receipts.length>=1);assert.ok(purge.receipts.every(r=>r.status==='deleted'));const raw=h.sql(`SELECT object_path FROM imports WHERE id=${q(job.importId)}`);assert.equal(h.sql(`SELECT count(*) FROM storage.objects WHERE bucket_id='vexa-private' AND name=${q(raw)}`),'0','RAW_PHYSICALLY_REMOVED');
   const retry=await createImport(h,worker,{seed,actor});await call(worker,'consume');const outcome=observed(h,retry.id);assert.equal(outcome.rows.length,200);assert.equal(outcome.job.state,'partial');assert.equal(outcome.rows.filter(r=>r.code==='SOURCE_TOMBSTONED').length,1);assert.deepEqual(active(),{messages:0,revisions:0,snapshots:0,ledger:1});record.recoveryMs=performance.now()-began;record.deadline=outcome.job.deadline;record.errors.push('SOURCE_TOMBSTONED');record.observed={replayedJob:job.id,newIngestionJob:retry.id,rows:200,newIngestionState:outcome.job.state,tombstonedRejected:1,activeDeletedContent:0,ledgerEntries:1,rawStorage:'owner Auth/Storage HTTP purge complete; object metadata absent',purgedArtifacts:purge.receipts.length,tombstoneHash:digest(JSON.stringify(active()))};
  }finally{await crash.kill();await worker.kill();}
 });
}
