#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';import {performance} from 'node:perf_hooks';
import {prepareEvidence} from './guards.mjs';
import {retention} from './retention.mjs';
import {setup,q} from './harness.mjs';import {jobs} from './jobs.mjs';import {budget} from './budget.mjs';import {backlog,digest} from './fixtures.mjs';
let candidate,evidence,repetitions;
try{
 const args=process.argv.slice(2),value=name=>{const i=args.indexOf(name);return i<0?undefined:args[i+1];};
 assert.ok(args.includes('--synthetic-local'),'EXPLICIT_SYNTHETIC_LOCAL_REQUIRED');
 candidate=path.resolve(value('--candidate')??path.join(path.dirname(fileURLToPath(import.meta.url)),'../../..'));
 assert.ok(!process.env.VEXA_CI_JOURNAL&&!process.env.VEXA_CI_BROKER,'EXCLUSIVE_RESOURCE_JOURNAL_REQUIRED');
 for(const relative of ['packages/recovery/index.mjs','supabase/migrations/0035_retention_storage.sql'])assert.ok(fs.existsSync(path.join(candidate,relative)),'RETENTION_IMPLEMENTATION_REQUIRED');
 repetitions=Number(value('--repetitions')??'3');assert.ok(Number.isInteger(repetitions)&&repetitions>=1&&repetitions<=3,'REPETITIONS_INVALID');
 evidence=prepareEvidence(candidate,value('--evidence'));
}catch(error){console.error(JSON.stringify({status:'rejected',code:String(error.message).split('\n')[0]}));process.exit(1);}
const seed=42,report={version:1,scope:'Published durable core d723 + SQL38; LOCAL SYN only; F06-09 and unpublished notifications excluded; not acceptance',seed,repetitions,node:process.version,pid:process.pid,startedAt:new Date().toISOString(),clock:{fixtures:'seeded42',gateway:'manual UTC 2026-09-23',postgres:'real clock; expired lease/deadline explicitly set to year2000'},results:[],processes:[process.pid],pending:['independent functional gate','acceptance']};let h;
const write=()=>fs.writeFileSync(path.join(evidence,'chaos-report.json'),JSON.stringify(report,null,2)+'\n',{mode:0o600});write();console.log(JSON.stringify({event:'starting',pid:process.pid,evidence}));
try{h=await setup(candidate,evidence);const {seedDetail}=await import(pathToFileURL(path.join(candidate,'support/F06-detail/fixtures.mjs')));const fixture=await seedDetail(h);const snapshot=()=>h.json(`SELECT jsonb_build_object('snapshot',(SELECT to_jsonb(s) FROM metric_snapshots s WHERE id=${q(fixture.snapshot.id)}),'components',(SELECT coalesce(jsonb_agg(to_jsonb(c) ORDER BY c.id),'[]') FROM components c WHERE snapshot_id=${q(fixture.snapshot.id)}))`);const snapshotHash=digest(JSON.stringify(snapshot()));report.snapshot={id:fixture.snapshot.id,sha256:snapshotHash};
 for(let round=1;round<=repetitions;round++){
  const run=async(name,operation)=>{const started=performance.now(),record={round,name,seed,status:'running',startedAt:new Date().toISOString(),backlogBefore:backlog(h),errors:[],recoveryMs:null,deadline:null,expected:'durable invariants asserted against PostgreSQL'};report.results.push(record);write();try{await operation(record);if(record.jobId){const totals=h.json(`SELECT coalesce((SELECT jsonb_build_object('total',i.total,'accepted',i.accepted,'rejected',i.rejected,'duplicates',i.duplicates,'pending',i.pending) FROM imports i JOIN jobs j ON j.import_id=i.id WHERE j.id=${q(record.jobId)}),'null'::jsonb)`);if(totals){assert.equal(Number(totals.total),Number(totals.accepted)+Number(totals.rejected)+Number(totals.duplicates)+Number(totals.pending),'IMPORT_ACCOUNTING_COMPLETE');record.accounting=totals;}}assert.equal(digest(JSON.stringify(snapshot())),snapshotHash,'PUBLISHED_SNAPSHOT_MUST_REMAIN_IDENTICAL');record.snapshotUnchanged=true;record.status='pass';}catch(error){record.status='fail';record.failure={name:error.name,code:error.code??null,message:error.message,stack:error.stack};throw error;}finally{record.durationMs=performance.now()-started;try{record.backlogAfter=backlog(h);if(record.jobId)record.attempts=h.json(`SELECT coalesce(jsonb_agg(jsonb_build_object('number',attempt_number,'fence',fencing_token,'state',state,'error',error_code,'startedAt',started_at,'finishedAt',finished_at) ORDER BY attempt_number),'[]') FROM attempts WHERE job_id=${q(record.jobId)}`);}catch(error){record.backlogAfter=null;record.metricsError=error.message;if(record.status==='pass'){record.status='fail';write();throw error;}}write();console.log(JSON.stringify({event:'scenario',round,name,status:record.status,durationMs:record.durationMs}));}};
  await jobs({h,run,seed,round,notes:report});await budget({h,run,round});await retention({h,run,round,seed,notes:report});
 }
 for(const name of ['crash_postcommit','expired_lease','deleted_source_replay']){const rows=report.results.filter(r=>r.name===name);assert.equal(rows.length,repetitions);assert.equal(new Set(rows.map(r=>r.fixtureHash)).size,1,'REPEATED_FIXTURE_HASH:'+name);}report.completedRounds=Array.from({length:repetitions},(_,i)=>({round:i+1,passed:report.results.filter(r=>r.round===i+1&&r.status==='pass').length,expected:11}));assert.ok(report.completedRounds.every(r=>r.passed===r.expected));h.verifySources();report.measuredScenariosPassed=true;report.status='measured-pass-review-pending';
}catch(error){report.status='failed';report.failure={name:error.name,message:error.message,stack:error.stack};process.exitCode=1;}finally{if(h){try{await h.close();report.cleanup=JSON.parse(fs.readFileSync(path.join(evidence,'cleanup.json'),'utf8'));}catch(error){report.cleanupError=error.message;report.status='failed';process.exitCode=1;}}if(!report.cleanup&&fs.existsSync(path.join(evidence,'cleanup.json')))report.cleanup=JSON.parse(fs.readFileSync(path.join(evidence,'cleanup.json'),'utf8'));report.finishedAt=new Date().toISOString();write();console.log(JSON.stringify({event:'finished',status:report.status,evidence}));}
