// SYN-SNAPSHOT-265: only synthetic, explicitly attested operational fixture records.
export const scope={start:'2026-09-01T00:00:00.000Z',end:'2026-09-20T00:00:00.000Z',timezone:'UTC',dateBasis:'occurred_at',currency:'USD',exponent:2,basis:'net_order_excluding_tax_shipping'};
export const otherScope={...scope,start:'2026-08-01T00:00:00.000Z',end:'2026-08-20T00:00:00.000Z'};
export const source=()=>({operation:'source',expectedVersion:0,name:'SYN snapshot operational orders',evidenceType:'order_export',active:true,complete:true,windowStart:'2026-08-01T00:00:00.000Z',windowEnd:scope.end,watermark:scope.end,report:'SYN operational source reviewed by fixture owner, full declared two-month scope.',attested:true});
export const currency=code=>({operation:'currency',currency:code,exponent:2,expectedVersion:0,active:true,source:'SYN currency catalog',reference:'SYN explicit exponent source',date:'2026-09-01',report:'SYN owner reviewed exact monetary units and fixed source reference.',attested:true});
export const order=(s,id,amount,patch={})=>({operation:'record',sourceId:s.id,sourceVersion:s.version,expectedRevision:0,externalId:id,kind:'order',effectiveAt:'2026-09-12T12:00:00.000Z',currency:'USD',exponent:2,basis:scope.basis,amountMinor:amount,status:'recorded',orderId:null,reversalOf:null,details:{},report:'SYN immutable operational amount evidence, never generated from narrative.',attested:true,...patch});
export function parseCsv(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){value+='"';i++;}else quoted=false;}else value+=c;continue;}if(c==='"'){if(value)throw Error('CSV_UNEXPECTED_QUOTE');quoted=true;}else if(c===','){row.push(value);value='';}else if(c==='\r'||c==='\n'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('CSV_UNCLOSED_QUOTE');if(value||row.length){row.push(value);rows.push(row);}return rows;}

// Historical membership deliberately absent from the current problem version embeddingIds.
// Extraction and redacted evidence are real repositories; vector grouping is labelled synthetic.
export async function attachHistoricalExtraction(h,problem){const {fixtureFactory}=await import('../F04-causality/fixtures.mjs'),{randomUUID}=await import('node:crypto'),{insert}=await import('../../tests/acceptance/support/F01-03/matrix.mjs'),{q}=await import('./harness.mjs');const factory=await fixtureFactory(h),old=await factory('customer',h.A);await old.complete();const embeddingId=randomUUID();h.sql(`BEGIN;SELECT set_config('request.jwt.claim.sub',${q(h.A.id)},true),set_config('vexa.tenant_id',${q(h.A.tenant)},true),set_config('vexa.action','configure',true);`+insert('embeddings',{id:embeddingId,tenant_id:h.A.tenant,model_id:'SYN historical-vector',dim:3,version:'old',content:'SYN obsolete membership not in current problem version',embedding:'[0,1,0]',message_revision_id:old.span.message_revision_id})+';'+insert('problem_embedding_members',{tenant_id:h.A.tenant,embedding_id:embeddingId,problem_id:problem.id,extraction_run_id:old.prepared.runId,conversation_id:old.conversationId})+';COMMIT;');return old;}
