import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import '../../tests/acceptance/F01-03.test.mjs';
test('F05-05 snapshot migration mandatory',()=>{assert.ok(process.env.VEXA_CANDIDATE,'CANDIDATE_REQUIRED');assert.ok(fs.existsSync(path.join(process.env.VEXA_CANDIDATE,'supabase/migrations/0021_economic_snapshots.sql')),'SNAPSHOT_IMPLEMENTATION_MISSING');});

import {candidateInputs,launch} from '../../tests/acceptance/support/F01-03/harness.mjs';
import {seed,foreignKeys} from '../../tests/acceptance/support/F01-03/oracles.mjs';
import * as snapshots from '../../tests/acceptance/support/F01-03/snapshot-oracles.mjs';
test('F05-05 targeted canonical snapshot SQL',{timeout:300000},async t=>{const h=await launch({services:true});t.after(()=>{const cleanup=process.env.VEXA_F01_03_CLEANUP;try{if(cleanup)process.env.VEXA_F01_03_CLEANUP=cleanup+'.targeted';h.close();}finally{if(cleanup)process.env.VEXA_F01_03_CLEANUP=cleanup;}});for(const sql of candidateInputs(process.env.VEXA_CANDIDATE))h.sql(sql);const keys=foreignKeys(h);await t.test('schema grants exact numeric and four added FKs',()=>snapshots.schema(h,keys));const actors={};for(const key of ['a','b','dual','outsider','viewer','analyst','operator'])actors[key]=await h.user();const f=seed(h,actors),s=snapshots.seed(h,f,actors);await t.test('published positives private drafts tenant roles revocation',()=>snapshots.visibility(h,s,actors));await t.test('metadata required immutable scope and exact aggregate values',()=>snapshots.metadata(h,s,actors));await t.test('content digest publication rollback head CAS and history',()=>snapshots.integrity(h,s,actors));await t.test('digest identical across database session timezones',()=>snapshots.timezones(h,s,actors));await t.test('withdrawn evidence source hides published snapshot and components',()=>snapshots.withdrawal(h,s,actors));for(const key of keys.filter(k=>snapshots.tables.includes(k.table)||k.table==='metric_snapshots'&&['created_by','published_by'].some(c=>c in k.mapping)))await t.test('added FK same tenant positive and foreign negative '+key.name,()=>snapshots.fk(h,s,key));
 await t.test('causal amount omission digest mutant reaches financial assertion and restores',()=>{const original=h.sql("SELECT pg_get_functiondef('public.economic_snapshot_digest(uuid,uuid)'::regprocedure)"),needle="'amount', c.amount_minor,";const alternatives=[needle,"'amount',c.amount_minor,"];const target=alternatives.find(n=>original.includes(n));assert.ok(target,'SNAPSHOT_MUTANT_TARGET');snapshots.integrity(h,s,actors);h.sql(original.replace(target,''));snapshots.refreshDraftDigest(h,s,actors);try{assert.throws(()=>snapshots.integrity(h,s,actors),e=>e.code==='ERR_ASSERTION'&&e.message.includes('SNAPSHOT_AMOUNT_IS_HASHED'),'SNAPSHOT_DIGEST_MUTANT_SPECIFIC');}finally{h.sql(original);snapshots.refreshDraftDigest(h,s,actors);}snapshots.integrity(h,s,actors);});});
