"""Create initial phase dossiers and task graph. Run once; refuses overwrites."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PHASES=[
('F00','Datos, derechos y contratos','1–2',[],['docs/blueprint/'],
 'Consolidar fuentes y discrepancias; conseguir carta/NDA/autorización y fecha de migración; acordar piloto. Congelar contratos de API y fixtures sintéticos, escribir y revisar gates externos antes del loop.',
 ['Validar los 6 hashes/duraciones/transcripciones y marcar incertidumbres ASR.','Asignar sponsor de negocio, responsable de CRM, owner de privacidad y finanzas.','Definir cuentas dev/preview/prod propias de VEXA; no reutilizar producción Likida.','Crear fixtures dos tenants, clientes repetidos, orders/refunds/reversals, dos monedas, nulos, mensajes con instrucciones maliciosas.','Escribir gates de aceptación de cada tarea en tests/acceptance fuera de candidate y revisar contra PRD.'],
 ['Sin autorización de datos se puede construir con fixtures, no importar Senix.','Gold verdadero requiere etiquetas humanas; no inventar etiquetas y llamarlas humanas.','Acta y 30% siguen pendientes de revisión jurídica.']),
('F01','App, Auth, tenancy y CI','2–5',['F00'],['apps/web/','supabase/','packages/platform/'],
 'Crear Next.js TypeScript en Vercel-compatible runtime, Supabase Auth/Postgres/Storage y RLS por tenant; pipeline GitHub Actions con verificación separada.',
 ['Resolver versiones actuales desde documentación instalada/catálogos y fijar lockfile; no copiar latest de memoria.','Implementar login/logout, membership en DB y selector de organización sin confiar tenant_id del body.','SQL migrations con claves tenant-aware y RLS default deny; Storage privado.','Diseño base accesible, sidebar, navegación y estados vacío/error/stale/loading.','CI lint/typecheck/unit/SQL integration/build; secretos de preview mínimos, ninguna clave servicio al browser.'],
 ['Login de A no lista/lee/escribe B aun con IDs conocidos; membership revocada bloquea siguiente request.','Error DB da unavailable, no dashboard lleno de ceros.','Build y arranque local reales; CI remoto sólo se afirma al ejecutarse.']),
('F02','Importación y pipeline durable','4–8',['F01'],['packages/ingestion/','packages/jobs/','apps/web/src/','supabase/'],
 'CSV/Excel upload con mapeo visible, validación por fila, rechazo explicable y jobs reanudables. Resolver S04/S05 de cola vs Workflow antes del runtime productivo.',
 ['Definir límites de archivo/filas/tamaño descomprimido; impedir zip bombs y formularios ejecutables.','Carga directa Storage autorizada; registrar import+outbox atómicamente.','Preview de columnas, timezone/moneda explícita, row errors descargables sin CSV injection.','Canonicalizar fuente/IDs/revisiones, dedup único DB, cuarentena de ambiguos.','Worker por chunks con deadline, lease/fencing, checkpoint, backoff/429/cancelación y dead-letter.','Probar consumidor real y alarma de cola estancada; 202 no significa análisis completado.'],
 ['10K fixtures: accepted+rejected+duplicates cuadra con input; ningún truncamiento oculto.','Crash después de persistir antes de ack no duplica resultados.','Dos tenants/jobs concurrentes no comparten cache, payload ni referencias.']),
('F03','HubSpot, Zendesk y migración','6–12',['F02'],['packages/connectors/','apps/web/src/','supabase/'],
 'Dos adaptadores read-only producen SourceEnvelope común y preservan historial durante la migración del cliente.',
 ['S01 confirma versión de rutas/scopes HubSpot; recuperar mensajes reales no sólo propiedades de ticket.','S02 confirma subdominio, cursor y comments Zendesk, actualizado/borrado.','Guardar cursor sólo tras commit de página; manejar ventana de actualización y backfill con sobreposición deduplicada.','Preparar mapa aliases HubSpot→Zendesk con procedencia y ambigüedad, sin fusionar sólo por email/texto.','UI health: última sincronización, filas/cobertura, permisos revocados y plan de reconexión.','Comparar dataset antes/después con mismos filtros y pipeline versionado; visibilizar cambio de cobertura de canales.'],
 ['Stub paginado 429/401/timeout/deletes no pierde ni duplica casos.','Prueba real exige token y autorización; mocks no la sustituyen.','Refresh token/credential cifrado y redacted, revocación bloquea siguiente sync.']),
('F04','Gateway, clasificación y problemas','8–15',['F02'],['packages/intelligence/','packages/gateway/','packages/problems/','apps/web/src/','supabase/'],
 'Extraer señales con JSON schema y citas; problemas estables en el tiempo; modelos OpenRouter por rol y política, no un LLM que inventa finanzas.',
 ['Gateway valida modelos/rutas desde catálogo y política de retención/residencia antes de red.','Reserva atómica por tenant/job; errores con gasto incierto conservan reserva hasta conciliación.','Redactar PII, tratar tickets como datos sin autoridad, extraer issue/sentiment/intent/urgency/entities + spans y abstención.','Validar cada cita contra message_revision autorizada, enum y límites del schema.','Embeddings model/dim versionados, recuperación tenant-filtered, clustering incremental estable, outliers y split/merge revisables.','Separar síntoma, causa probable y confirmación operacional; no inventar batch/carrier/SKU.','Medir gold temporal humano: clasificación, calidad clusters, abstención, evidencia, costo y latencia; holdout no tuneable.'],
 ['Cita inexistente o de otro tenant rechazada aunque JSON válido.','Posible defecto de batería severo con poca evidencia visible para humano.','Modelo alternativo no relaja ZDR/residencia; no endpoint elegible bloquea job.']),
('F05','Dinero, snapshots y priorización','12–18',['F03','F04'],['packages/economics/','packages/metrics/','apps/web/src/','supabase/'],
 'Extender kernel financiero puro a ledger/consultas SQL y snapshots; ranking reproducible y con costos separados.',
 ['Leer contrato completo calidad/01 y kernel existente, no reescribir reglas por gusto.','Separar revenue exposure, refunds netos, replacement cost, costo modelado soporte y escenarios de future loss.','Unión global de órdenes/clientes/eventos entre problemas; filas no aditivas señaladas.','Minor units/Decimal, moneda/exponente/horizonte/FX versionados; unknown!=zero y coverage.','Publish snapshot atómico con scope_hash, versiones y watermark; export/UI mismo bundle.','Prioridad con carril crítico aparte, fórmula versionada y razones; normalización no oculta urgencias al cambiar set.'],
 ['Todos FIN-01..12 y contraejemplos de duplicación/moneda/reversal/periodos pasan.','Refresh sobre mismo snapshot produce mismo hash/cifras.','No LLM field alimenta dinero contable sin fuente validada.']),
('F06','Producto ejecutivo de ocho vistas','15–23',['F05'],['apps/web/','packages/recommendations/','packages/interventions/','packages/briefs/'],
 'Integrar overview/problems/detail/recommendations/explorer/customer/interventions/weekly brief con datos de servidor y operaciones reales.',
 ['Implementar filtros compartidos tenant+snapshot+scope sin joins que dupliquen dinero.','Detail navega cifra→componente→evento→evidencia, con estados de causa probable y cobertura.','Recomendación específica y condicionada, owner/estado/dismiss con razón e historial.','Explorer usa herramientas read-only allowlisted sobre vistas SQL seguras; pregunta ambigua pide alcance.','Intervención guarda baseline/hipótesis/owner/fechas y plan de medición antes de cambio.','Brief versionado basado en snapshots; envío email no implícito; vistas y export primero.','Revisión visual móvil/desktop, teclado, contraste y reducción movimiento; no copiar marcas.'],
 ['CEO encuentra top 3, evidencia y acción en ensayo cronometrado humano.','UI/API/export coinciden en mismo scope; filtros afectan todas las tarjetas.','404 vs 403 según política; ninguna ruta protege sólo con sidebar.']),
('F07','QA, resiliencia y piloto','22–27',['F06'],['apps/web/','packages/','supabase/'],
 'Ensayar defectos y operaciones, no sólo aumentar cobertura. Congelar cambio de scope y cerrar P0/P1 reales.',
 ['Revisar amenazas RLS/storage/vectores/exports/jobs e intentar cruce tenant con IDs conocidos.','Metamórficas: reordenar, duplicar, partir lotes, migrar identidad; mutación sobre dinero y autorización.','Caos: worker caído, lease vencido, quota LLM, DB caída, token revocado, dead-letter y replay.','Carga 10K/50K/150K fixtures; registrar hardware, versiones, concurrencia, p95 y costo, sin extrapolar linealmente sin medir.','Evaluación humano gold y sponsor de acción; ningún benchmark sustituye datos reales.','Runbooks cancelación, rollback, restore, datos borrados y eliminación de embeddings/backups conforme política.'],
 ['0 fallas críticas reproducibles abiertas; blockers explícitos, no skip tests.','Restore ensayado con fixture y tombstones; rollback no resucita datos eliminados.','Rendimiento y accesibilidad medidos en artefacto real, no solo checklist.']),
('F08','Release, pitch y entrega','28–30',['F07'],['docs/entrega/'],
 'Promover deployment aprobado y presentar tesis con evidencia honesta; separar demo sintética, piloto real y producción.',
 ['Preparar manifiesto release con SHA, migrations, config hashes, URLs y propietarios sin secretos.','Ejecutar smoke remoto del flujo completo, dos tenants, job durable y export.','Ensayar pitch de 5 minutos, demo grabada de respaldo y fixture claramente rotulado si feed falla.','Validar permiso de logo/datos/caso, rango financiero y supuestos antes de diapositivas.','Entregar guía usuario/operación/desarrollador, accesos revocables, backlog y fechas de próximos controles.','Congelar resultados y próximos experimentos: éxito del pitch no equivale a validación PMF.'],
 ['Desplegado SHA coincide; plan rollback probado; controles de acceso siguen activos.','No alegar ahorro causal, partnership o revenue sin respaldo.','Lo no implementado o no probado se presenta como roadmap/blocked.']),
]

def new(path,text):
 path.parent.mkdir(parents=True,exist_ok=True)
 with path.open('x') as f: f.write(text)

if __name__=='__main__':
 tasks=[]
 # The only initially executable gate is the pure economics kernel. Remaining
 # contracts are specified, but tests must be authored and frozen before autonomy.
 tasks.append({'id':'E00','depends_on':[],'allowed_paths':['packages/economics'],
 'acceptance':'tests/acceptance/economics.test.mjs','prompt':'orchestration/prompts/E00.md',
 'auto_accept':False,'requires_approval':False})
 new(ROOT/'orchestration/prompts/E00.md', '# E00 — verificar y endurecer kernel económico\nLee docs/blueprint/calidad/01-contrato-motor-financiero.md. Revisa packages/economics/index.mjs y corre el contrato externo. Corrige sólo defectos dentro de alcance del kernel; no simules una app terminada. Si ya cumple, reporta sin cambios. No modificar pruebas de aceptación.\n')
 for pid,title,days,deps,paths,objective,steps,gates in PHASES:
  body=f'# {pid} — {title}\n\nDías objetivo: {days}. Dependencias: {", ".join(deps) or "fuentes"}. Estado: especificado, no ejecutado.\n\n## Entrada obligatoria\nLee ../CONTEXTO-CANONICO.md, 00-BLUEPRINT-MAESTRO.md, 01-CONTRATOS-Y-DATOS.md y calidad/*.md pertinente. Consulta ../investigacion/integraciones/ para contratos y spikes. Si esta fase se abre en sesión nueva, estos archivos contienen el contexto necesario.\n\n## Resultado\n{objective}\n\n## Pasos\n'+''.join(f'{i+1}. {s}\n' for i,s in enumerate(steps))+'\n## Criterios observables\n'+''.join('- '+g+'\n' for g in gates)+'\n## Mapa de escritura\n'+''.join('- `'+p+'`\n' for p in paths)+'\nNo tocar private/, otros repos, credenciales, pruebas protegidas ni orquestador desde un candidato. Cambios de contratos/gates van en sesión de control, revisados antes de reanudar.\n\n## Evidencia que se entrega\nComando exacto, código de salida, expected/observed, SHA, fixture hash y ruta de log/screenshot. Estados pass/fail/blocked/not_run; tests faltantes no equivalen a pass.\n\n## Recuperación\nGuardar diagnóstico y candidate worktree. No incorporar fallo al baseline. Reanudar desde checkpoint; no reiniciar import ni recalcular historia silenciosamente. Tras dos intentos fallidos, escalar con reproducción mínima.\n'
  new(ROOT/f'docs/blueprint/{pid}.md',body)
  new(ROOT/f'orchestration/prompts/{pid}.md',f'# Implementador {pid}\n\nLee docs/blueprint/{pid}.md y los contratos que referencia. Ejecuta esa fase, no otras. Usa skills pertinentes ya instaladas: test-driven-development, depuracion-sistematica para fallos, evidencia para cierre; lee su SKILL antes de usar. No inventar contratos API ni dinero. Trabaja sólo en los paths permitidos por graph.json. Sin red/productivo en bucle; faltantes externos se reportan bloqueados.\n\nDevuelve: cubierto, no cubierto, archivos cambiados, comandos/salidas, bloqueos y siguiente acción. No digas listo sin evidencia.\n')
  tasks.append({'id':pid,'depends_on':deps or ['E00'],'allowed_paths':paths,'acceptance':f'tests/acceptance/{pid}.test.mjs','prompt':f'orchestration/prompts/{pid}.md','auto_accept':False,'requires_approval':pid in ['F00','F08']})
 new(ROOT/'orchestration/graph.json',json.dumps({'version':1,'provider':'codex-chatgpt','model':'gpt-6-astra','max_attempts_per_task':2,'turn_timeout_seconds':900,'concurrency':1,'tasks':tasks},indent=2)+'\n')
 print('Created',len(PHASES),'phase dossiers and',len(tasks),'graph tasks; missing acceptance gates intentionally block unattended execution.')
