"""Build a provenance registry from saved HTTP metadata, without fetching again."""
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'negocio/00-Fuentes'
used=set('census-susb-2022 census-receipts-2022 census-definitions census-ecommerce census-ecom-timeseries nrf-returns-2024 nrf-returns-2025 shopify-results-2025 shopify-financials-2025 marketsandmarkets-cx amvo-evo-2026 sentisum-pricing thematic-pricing gorgias-pricing-2026 gorgias-plans enterpret-series-a chattermill-series-b unitq-zendesk gorgias-series-c2 qualtrics-pressganey medallia-recap loop-pricing loop-series-b narvar-series-c ftc-security dreo-about ooni-about fellow-about caraway-about ourplace-home branch-home madein-home ruggable-home brumate-home burrow-home'.split())
rows=[]
for p in sorted((OUT/'web').glob('*.txt')):
 try:meta=json.loads(p.read_text().splitlines()[0])
 except (json.JSONDecodeError,IndexError):continue
 rows.append({'id':meta['source_id'],'url':meta['url'],'final_url':meta['final_url'],'http_status':meta['http_status'],'retrieved_at':meta['retrieved_at'],'sha256':meta['sha256'],'content_type':meta['content_type'],'used_in_analysis':meta['source_id'] in used,'saved_text':str(p.relative_to(OUT))})
with (OUT/'registro-fuentes.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
(OUT/'registro-fuentes.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n')
lines=['# Registro de fuentes y límites de lectura','\nCorte19-sep-2026UTC. URLs públicas abiertas; HTTP200 no garantiza contenido útil ni veracidad independiente. `used_in_analysis` significa que se empleó contenido específico, no que se auditó todo el documento/negocio. Fuentes de proveedores son declaraciones comerciales. Los reportes comerciales no equivalen a censo.\n',f'Se registraron **{len(rows)} intentos/capturas** y **{sum(r["used_in_analysis"] for r in rows)} fuentes usadas** en los capítulos (incluye páginas oficiales de marcas; no son todas estudios de mercado). Los fallos403/404 se conservan, no se cuentan como validación. Firecrawl402 se documenta en PLAN-INVESTIGACION; no se recargó ni se eludió cuota.\n','## Fuentes con respaldo local\n','| ID | HTTP | Usada | URL / captura |','|---|---:|---|---|']
for r in rows:lines.append(f'| {r["id"]} | {r["http_status"]} | {"Sí" if r["used_in_analysis"] else "No / exploración"} | [Original]({r["url"]}) · [Texto]({r["saved_text"]}) |')
lines+=['\n## Artefactos primarios estructurados\n- [Census XLSX original](census-receipts-2022.xlsx): hoja US 6-digit NAICS, bandas expresadas en miles USD, NAICS2017, año2022. SHA en registro y universo-census.json.\n- [Filas extraídas](../05-Precios-y-Finanzas/census-filas.csv) conservan número de fila original.\n- [PDF Shopify convertido a texto](web/shopify-financials-2025-extracted.txt): cifras en millones USD; PDF URL/hash en fuente shopify-financials-2025.\n- [PDF Census ecommerce convertido a texto](web/census-ecom-pdf-extracted.txt): URL/hash en fuente census-ecom-timeseries.\n- Catálogo de modelos utilizado: https://openrouter.ai/api/v1/models, copia local ../../docs/investigacion/fuentes/openrouter-candidatos.json desde proyecto; sus tarifas no son factura observada.\n','## Limitaciones materiales\n- GVR/Fortune y BLS:403, cifras no usadas. INEGI: respuesta200 demasiado escueta para un conteo; no se afirma haber extraído Censos Económicos mexicanos.\n- AMVO: resumen público; informe afiliados no accedido y año base de cifras de portada no inequívoco.\n- NRF: estimaciones/encuestas, no dinero neto perdido.2024y2025tienen denominadores distintos.\n- SUSB: firma definida por industria/geografía; no sumar categorías ni firmas como marcas. Bandas omitidas no son cero.\n- Gorgias: guía histórica/actualizada vs pricing vigente difieren en billing/paquetes; tabla comercial adopta /pricing y señala discrepancia.\n- No demos, cotizaciones negociadas, entrevistas o contratos completados.\n']
(OUT/'INDICE.md').write_text('\n'.join(lines))
print('sources',len(rows),'used',sum(r['used_in_analysis'] for r in rows))
