// All payloads in this file are SYNTHETIC, dedicated CC0-1.0 by VEXA. No customer data.
import test from 'node:test';
import assert from 'node:assert/strict';
import {implementation,options,context,token,rootPath,thread,message,json,server,collect,code} from './http.mjs';
const {createHubSpotAdapter:create}=await implementation();
const twoPages=(req,res,u)=>{
 if(u.pathname===rootPath){assert.equal(u.searchParams.get('association'),'TICKET','ASSOCIATION_REQUESTED');return json(res,u.searchParams.has('after')?{results:[thread('T2')]}:{results:[thread('T1')],paging:{next:{after:'THREAD-P2'}}});}
 if(u.pathname===`${rootPath}/T1/messages`)return json(res,u.searchParams.has('after')?{results:[message('M2',{type:'COMMENT',text:'SYNTHETIC internal',senders:[{actorId:'V-123'}]}),message('M3',{text:'SYNTHETIC agent',senders:[{actorId:'A-123'}]})]}:{results:[message('M1')],paging:{next:{after:'MESSAGE-P2'}}});
 if(u.pathname===`${rootPath}/T2/messages`)return json(res,{results:[message('M4',{conversationsThreadId:'T2',senders:[],text:'SYNTHETIC unknown'})]});
 throw new Error('UNEXPECTED_SYNTHETIC_PATH');
};
test('two thread pages and two message pages preserve roles revisions associations and scoped cursor',async()=>server(twoPages,async(fetch,seen)=>{
 const pages=await collect(create({...options,fetch}));assert.equal(pages.length,2,'THREAD_PAGE_COUNT');assert.equal(pages[0].checkpoint.cursor,'THREAD-P2','THREAD_CURSOR');assert.equal(pages[1].done,true);assert.equal(pages[1].checkpoint,null);
 const records=pages.flatMap(p=>p.records),messages=records.filter(r=>r.envelope.entity_type==='message');assert.deepEqual(messages.map(m=>m.envelope.external_id),['M1','M2','M3','M4'],'ALL_MESSAGE_PAGES');assert.deepEqual(messages.map(m=>m.role),['customer','internal','agent','unknown'],'ROLE_SEPARATION');assert.deepEqual(messages.map(m=>m.visibility),['public','internal','public','unknown'],'VISIBILITY_SEPARATION');
 for(const m of messages){assert.ok(m.envelope.source_revision,'SOURCE_REVISION');assert.equal(m.envelope.tenant_id,context.tenant_id);assert.equal(m.body_complete,true,'BODY_COMPLETE');assert.equal(m.associations[0].external_id,'9007199254740993123','OPAQUE_TICKET_ID');assert.ok(!m.text.includes('9007199254740993123'),'NO_ASSOCIATION_TEXT');}
 for(const r of records.filter(r=>r.envelope.entity_type!=='message'))assert.equal(r.text,null,'METADATA_NOT_MESSAGE_TEXT');
 assert.equal(seen.length,5,'READ_REQUEST_CARDINALITY');assert.equal(seen[2].query.after,'MESSAGE-P2','MESSAGE_CURSOR');assert.equal(seen[3].query.after,'THREAD-P2');
 const before=seen.length;await assert.rejects(()=>collect(create({...options,fetch,context:{...context,source_account_id:'SYNTHETIC-B'}}),{checkpoint:pages[0].checkpoint}),code('CHECKPOINT_SCOPE'));assert.equal(seen.length,before,'CROSS_SCOPE_NO_FETCH');
}));
test('checkpoint resumes only next thread page',async()=>server(twoPages,async(fetch,seen)=>{const first=await create({...options,fetch}).pages().next();seen.length=0;const rest=await collect(create({...options,fetch}),{checkpoint:first.value.checkpoint});assert.equal(rest.length,1);assert.deepEqual(seen.map(x=>x.path),[rootPath,`${rootPath}/T2/messages`]);assert.equal(seen[0].query.after,'THREAD-P2');}));
test('message content edit changes source revision; observation clock does not',async()=>{
 let body='SYNTHETIC first';await server((req,res,u)=>json(res,{results:u.pathname===rootPath?[thread('T1')]:[message('M1',{text:body})]}),async(fetch)=>{const read=async(clock=options.clock)=>(await collect(create({...options,fetch,clock})))[0].records.find(r=>r.envelope.entity_type==='message');const first=await read();const again=await read(()=>new Date('2026-09-21T00:00:00Z'));assert.equal(first.envelope.source_revision,again.envelope.source_revision,'REVISION_NOT_OBSERVATION_TIME');body='SYNTHETIC edited';assert.notEqual(first.envelope.source_revision,(await read()).envelope.source_revision,'EDIT_REVISION');});
});
for(const status of [401,403])test(`${status} blocks connection and next sync without retry`,async()=>server((req,res)=>json(res,{message:token},status),async(fetch,seen)=>{const a=create({...options,fetch,maxRetries:3});await assert.rejects(()=>collect(a),e=>{code('RECONNECT_REQUIRED')(e);assert.equal(e.state,'reconnect_required');return true;});await assert.rejects(()=>collect(a),code('RECONNECT_REQUIRED'));assert.equal(seen.length,1,'NO_AUTH_RETRY');}));
test('429 honors Retry-After and retries same page once',async()=>server((req,res,u,seen)=>seen.length===1?json(res,{},429,{'retry-after':'1'}):json(res,{results:[]}),async(fetch,seen)=>{const delays=[];await collect(create({...options,fetch,maxRetries:1,sleep:async ms=>delays.push(ms)}));assert.deepEqual(delays,[1000],'RETRY_AFTER');assert.equal(seen.length,2);assert.deepEqual(seen[0],seen[1]);}));
test('429 excessive Retry-After defers instead of early retry',async()=>server((req,res)=>json(res,{},429,{'retry-after':'60'}),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch,maxRetries:2,maxDelayMs:10})),code('RETRY_DEFERRED'));assert.equal(seen.length,1);}));
test('500 retry is bounded and redacted',async()=>server((req,res)=>json(res,{message:token},500),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch,maxRetries:2,sleep:async()=>{}})),code('HTTP_RETRY_EXHAUSTED'));assert.equal(seen.length,3,'BOUNDED_RETRY');}));
test('body timeout aborts stream and does not emit incomplete page',async()=>server((req,res)=>{res.writeHead(200,{'content-type':'application/json'});res.write('{"results":[');},async(fetch,seen)=>{const yielded=[];await assert.rejects(async()=>{for await(const p of create({...options,fetch,timeoutMs:35}).pages())yielded.push(p);},code('TIMEOUT'));assert.equal(seen.length,1);assert.equal(yielded.length,0,'NO_PARTIAL_BODY');}));
test('response byte limit is enforced',async()=>server((req,res)=>json(res,{results:[],padding:'x'.repeat(2048)}),async fetch=>{await assert.rejects(()=>collect(create({...options,fetch,maxResponseBytes:100})),code('RESPONSE_LIMIT'));}));
for(const link of ['https://foreign.invalid/?after=X','https://api.hubapi.com@foreign.invalid/?after=X',`${rootPath}?after=X&after=Y`,`${rootPath}?after=X&secret=oops`])test(`unsafe pagination link rejected ${link}`,async()=>server((req,res)=>json(res,{results:[],paging:{next:{after:'X',link}}}),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch})),code('UNSAFE_NEXT'));assert.equal(seen.length,1,'NO_FOREIGN_REQUEST');}));
test('302 redirect is never followed',async()=>server((req,res)=>{res.writeHead(302,{location:'https://foreign.invalid/private'});res.end();},async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch})),code('REDIRECT_BLOCKED'));assert.equal(seen.length,1);}));
test('thread cursor loop and page cap are visible failures',async()=>server((req,res)=>json(res,{results:[],paging:{next:{after:'REPEAT'}}}),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch})),code('CURSOR_LOOP'));assert.equal(seen.length,2);seen.length=0;await assert.rejects(()=>collect(create({...options,fetch,maxPages:1})),code('PAGE_LIMIT'));assert.equal(seen.length,1);}));
test('message subpage failure emits no outer checkpoint',async()=>server((req,res,u)=>u.pathname===rootPath?json(res,{results:[thread('T1')],paging:{next:{after:'THREAD-P2'}}}):u.searchParams.has('after')?json(res,{},503):json(res,{results:[message('M1')],paging:{next:{after:'MESSAGE-P2'}}}),async fetch=>{const emitted=[];await assert.rejects(async()=>{for await(const p of create({...options,fetch}).pages())emitted.push(p);},code('HTTP_RETRY_EXHAUSTED'));assert.equal(emitted.length,0,'NO_CHECKPOINT_BEFORE_COMPLETE_MESSAGES');}));
test('unsupported dated version and absent scope reject before transport',async()=>{let calls=0;const fetch=async()=>{calls++;throw Error(token);};assert.throws(()=>create({...options,fetch,version:'2026-09'}),code('CONTRACT_BLOCKED'));assert.throws(()=>create({...options,fetch,scopes:[]}),e=>{assert.ok(e.code);return true;});assert.equal(calls,0,'NO_UNVERIFIED_VERSION_PROBING');});
test('404 is an error and never an empty or deleted conversation',async()=>server((req,res)=>json(res,{},404),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch,maxRetries:2})),code('HTTP_ERROR'));assert.equal(seen.length,1);}));
test('message unsafe cursor cannot leave its thread resource',async()=>server((req,res,u)=>json(res,u.pathname===rootPath?{results:[thread('T1')]}:{results:[message('M1')],paging:{next:{after:'X',link:`https://api.hubapi.com${rootPath}/T2/messages?after=X`}}}),async(fetch,seen)=>{await assert.rejects(()=>collect(create({...options,fetch})),code('UNSAFE_NEXT'));assert.equal(seen.length,2);}));
test('missing body does not become semantic evidence',async()=>server((req,res,u)=>json(res,{results:u.pathname===rootPath?[thread('T1')]:[message('M1',{text:undefined,richText:'<script>SYNTHETIC</script>'})]}),async fetch=>{const p=(await collect(create({...options,fetch})))[0];const m=p.records.find(r=>r.envelope.entity_type==='message');assert.ok(m,'MISSING_BODY_RECORD_PRESERVED');assert.equal(m.text,null,'NO_HTML_AS_PLAIN_TEXT');assert.equal(m.body_complete,false,'MISSING_BODY_COVERAGE');}));
test('unknown actor types stay unknown and cannot become customer evidence',async()=>server((req,res,u)=>json(res,{results:u.pathname===rootPath?[thread('T1')]:['I-1','S-hubspot','L-1','E-synthetic@example.invalid','X-1'].map((actorId,i)=>message(`M${i}`,{senders:[{actorId}]}))}),async fetch=>{const ms=(await collect(create({...options,fetch})))[0].records.filter(r=>r.envelope.entity_type==='message');assert.equal(ms.length,5);assert.ok(ms.every(m=>m.role==='unknown'),'UNKNOWN_NOT_CUSTOMER');}));
test('truncated message retrieves original content before completing page',async()=>server((req,res,u)=>{if(u.pathname.endsWith('/original-content'))return json(res,{text:'SYNTHETIC complete original',richText:'<p>SYNTHETIC complete original</p>'});return json(res,{results:u.pathname===rootPath?[thread('T1')]:[message('M1',{truncationStatus:'TRUNCATED',text:'SYNTHETIC partial'})]});},async(fetch,seen)=>{const p=(await collect(create({...options,fetch})))[0];const m=p.records.find(r=>r.envelope.entity_type==='message');assert.equal(m.text,'SYNTHETIC complete original','ORIGINAL_CONTENT');assert.equal(m.body_complete,true,'ORIGINAL_BODY_COMPLETE');assert.equal(seen.length,3);assert.equal(seen[2].path,`${rootPath}/T1/messages/M1/original-content`);}));
test('ticket retrieval preserves metadata separately from message text',async()=>server((req,res,u)=>{if(u.pathname===rootPath)return json(res,{results:[thread('T1')]});if(u.pathname.endsWith('/messages'))return json(res,{results:[message('M1')]});assert.equal(u.pathname,'/crm/v3/objects/tickets/9007199254740993123');return json(res,{id:'9007199254740993123',createdAt:'2026-09-20T00:00:00Z',properties:{subject:'SYNTHETIC metadata',content:'SYNTHETIC NOT CONVERSATION'}});},async(fetch,seen)=>{const p=(await collect(create({...options,fetch,includeTickets:true,scopes:['conversations.read','tickets']})))[0];const ticket=p.records.find(r=>r.envelope.entity_type==='ticket');assert.ok(ticket,'TICKET_METADATA_PRESENT');assert.equal(ticket.text,null,'TICKET_CONTENT_NOT_MESSAGE');const messages=p.records.filter(r=>r.envelope.entity_type==='message');assert.equal(messages.length,1);assert.equal(messages[0].text,'SYNTHETIC café');assert.equal(seen.length,3);}));
test('notes associations paginate and preserve internal HTML as inert metadata',async()=>server((req,res,u)=>{if(u.pathname===rootPath)return json(res,{results:[thread('T1')]});if(u.pathname.endsWith('/messages'))return json(res,{results:[message('M1')]});if(u.pathname.endsWith('/associations/notes'))return json(res,u.searchParams.has('after')?{results:[{toObjectId:'N2'}]}:{results:[{toObjectId:'N1'}],paging:{next:{after:'NOTES-P2'}}});assert.match(u.pathname,/\/crm\/v3\/objects\/notes\/N[12]$/);return json(res,{id:u.pathname.split('/').at(-1),createdAt:'2026-09-20T00:00:00Z',properties:{hs_note_body:'<b>SYNTHETIC internal</b>'}});},async(fetch,seen)=>{const p=(await collect(create({...options,fetch,includeNotes:true,scopes:['conversations.read','tickets','crm.objects.contacts.read']})))[0],notes=p.records.filter(r=>r.envelope.entity_type==='note');assert.equal(notes.length,2,'ALL_NOTES_PAGES');for(const n of notes){assert.equal(n.role,'internal','CRM_NOTE_INTERNAL');assert.equal(n.visibility,'internal');assert.equal(n.conversation_id,null,'TICKET_NOT_THREAD_IDENTITY');assert.equal(n.text_format,'inert_html');assert.equal(n.associations[0].external_id,'9007199254740993123');}assert.equal(seen.length,6);assert.equal(p.coverage.notes_complete,true);}));
test('record limit stops nested collection without publishing a checkpoint',async()=>server(twoPages,async fetch=>{const emitted=[];await assert.rejects(async()=>{for await(const p of create({...options,fetch,maxRecords:1}).pages())emitted.push(p);},code('RECORD_LIMIT'));assert.equal(emitted.length,0);}));
test('record limit counts rejected messages before adding quarantine',async()=>server((req,res,u)=>json(res,{results:u.pathname===rootPath?[thread('T1')]:[null,null,null]}),async fetch=>{const emitted=[];await assert.rejects(async()=>{for await(const p of create({...options,fetch,maxRecords:2}).pages())emitted.push(p);},code('RECORD_LIMIT'));assert.equal(emitted.length,0,'REJECTED_MESSAGES_COUNT_TOWARD_LIMIT');}));
test('record limit counts malformed threads before adding quarantine',async()=>server((req,res)=>json(res,{results:[null,null,null]}),async fetch=>{const emitted=[];await assert.rejects(async()=>{for await(const p of create({...options,fetch,maxRecords:2}).pages())emitted.push(p);},code('RECORD_LIMIT'));assert.equal(emitted.length,0,'REJECTED_THREADS_COUNT_TOWARD_LIMIT');}));
