import test from 'node:test';
import assert from 'node:assert/strict';
import {createHubSpotAdapter} from './hubspot.mjs';
import {createCRMAdapterFactory,normalizeSyncRecord,runSync} from './sync.mjs';
import {contentHash} from '../ingestion/index.mjs';
const base='/conversations/v3/conversations/threads',epoch=Date.parse('2026-10-06T00:00:00Z');
const context={tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',source:'hubspot',source_account_id:'SYN-account'};
const cfg={context,token:'SYN-token',version:'v3',scopes:['conversations.read','tickets','crm.objects.contacts.read'],includeTickets:true,includeNotes:true,bounded:true,maxRetries:0,clock:()=>new Date(epoch)};
const thread=(id='T1')=>({id,createdAt:new Date(epoch).toISOString(),threadAssociations:{associatedTicketId:'K'+id}});
const msg=(id,threadId='T1',patch={})=>({id,conversationsThreadId:threadId,type:'MESSAGE',createdAt:new Date(epoch).toISOString(),text:'SYN clean message',truncationStatus:'NOT_TRUNCATED',senders:[{actorId:'V-SYN'}],...patch});
function provider(options={}){
 const calls=[],state={mutated:false,failOriginal:false,failNote:false,elapsed:0};
 const fetch=async raw=>{const u=new URL(raw);calls.push(u);state.elapsed+=options.latency??0;
  assert.equal(u.origin,'https://api.hubapi.com');assert.equal(u.username,'');assert.equal(u.hash,'');
  let data;const path=u.pathname,after=u.searchParams.get('after');
  if(path===base){assert.equal(u.searchParams.get('limit'),'1');if(after===null)data={results:[thread()],paging:{next:{after:'SYN-thread-2'}}};else if(after==='SYN-thread-2')data={results:[thread('T2')]};else data={results:[]};}
  else if(path===base+'/T1'||path===base+'/T2')data=thread(path.split('/').at(-1));
  else if(path.endsWith('/messages')){assert.equal(u.searchParams.get('limit'),'1');const tid=path.split('/').at(-2);if(tid==='T2')data={results:[]};else if(after===null)data={results:[msg('M1')],paging:{next:{after:'SYN-message-2'}}};else data={results:[msg('M2','T1',{truncationStatus:'TRUNCATED',text:'SYN truncated fallback forbidden'})]};}
  else if(path.endsWith('/original-content')){if(state.failOriginal)return new Response('{}',{status:500});data=options.original??{richText:'<p>SYN rich body<script>inert()</script></p>'};}
  else if(path.includes('/associations/notes')){assert.equal(u.searchParams.get('limit'),'1');if(path.includes('/KT2/'))data={results:[]};else data=after===null?{results:[{toObjectId:state.mutated?'OTHER':'N1'}],paging:{next:{after:'SYN-note-2'}}}:{results:[{toObjectId:'N2'}]};}
  else if(path.includes('/objects/notes/')){if(state.failNote)return new Response('{}',{status:500});data={id:path.split('/').at(-1),createdAt:new Date(epoch).toISOString(),properties:{hs_note_body:'<p>SYN inert note</p>'}};}
  else if(path.includes('/objects/tickets/'))data={id:path.split('/').at(-1),createdAt:new Date(epoch).toISOString(),properties:{subject:'SYN metadata'}};
  else throw Error('unexpected path '+path);
  if(options.transform)data=options.transform(data,u,state);
  return Response.json(data);
 };
 return {calls,state,fetch};
}
async function step(p,checkpoint=null,extra={}){const before=p.calls.length,a=createHubSpotAdapter({...cfg,fetch:p.fetch,...extra}),iterator=a.pages({checkpoint});try{const {value}=await iterator.next();assert.ok(value);assert.ok(p.calls.length-before<=2,'max two provider GETs per committed chunk');assert.ok(value.records.length+value.errors.length<=1,'small persistence page');assert.ok(Buffer.byteLength(JSON.stringify(value))<8*1024*1024);return value;}finally{await iterator.return();}}
async function all(p,extra={}){const pages=[];let checkpoint=null;for(let i=0;i<60;i++){const page=await step(p,checkpoint,extra);pages.push(page);if(page.done)return pages;checkpoint=page.checkpoint;}assert.fail('SYN traversal failed to terminate');}
const records=pages=>pages.flatMap(p=>p.records);
test('bounded traversal persists conversation before messages and visits every nested message/note without offset',async()=>{
 const p=provider(),pages=await all(p),r=records(pages);
 assert.deepEqual(r.map(x=>x.envelope.entity_type+':'+x.envelope.external_id),['thread:T1','message:M1','message:M2','ticket:KT1','note:N1','note:N2','thread:T2','ticket:KT2']);
 assert.equal(pages[0].checkpoint.version,2);assert.equal(pages[0].checkpoint.state.phase,'messages');
 assert.ok(pages.slice(0,-1).every(p=>!p.done&&!p.coverage.messages_complete&&!p.coverage.notes_complete));
 assert.equal(pages.at(-1).done,true);assert.equal(pages.at(-1).coverage.messages_complete,false);
 for(const page of pages){const serialized=JSON.stringify(page.checkpoint);assert.ok(!serialized.includes('SYN-token'));assert.ok(!serialized.includes('SYN clean'));assert.ok(!serialized.includes('rich body'));assert.ok(!serialized.includes('truncated fallback'));}
 const incomplete=r.find(x=>x.envelope.external_id==='M2');assert.equal(incomplete.text,null);assert.equal(incomplete.body_complete,false);assert.equal(normalizeSyncRecord(incomplete).code,'BODY_INCOMPLETE');assert.equal(incomplete.payload.original_content.richText,'<p>SYN rich body<script>inert()</script></p>');
});
test('richText-only original is retained incomplete in legacy mode too, without stopping the thread',async()=>{const p=provider();const a=createHubSpotAdapter({...cfg,bounded:false,threadIds:['T1'],fetch:async raw=>{const u=new URL(raw);u.searchParams.set('limit','1');return p.fetch(u.href);}});const pages=[];for await(const page of a.pages())pages.push(page);const row=records(pages).find(x=>x.envelope.external_id==='M2');assert.equal(row.text,null);assert.equal(row.body_complete,false);assert.equal(normalizeSyncRecord(row).code,'BODY_INCOMPLETE');assert.equal(pages[0].coverage.bodies_missing,1);});
test('plain original text remains complete and revision binds the original body',async()=>{const a=records(await all(provider({original:{text:'SYN full original',richText:'<p>ignored presentation</p>'}}))).find(x=>x.envelope.external_id==='M2');const b=records(await all(provider({original:{text:'SYN changed original'}}))).find(x=>x.envelope.external_id==='M2');assert.equal(a.text,'SYN full original');assert.equal(a.body_complete,true);assert.notEqual(a.envelope.source_revision,b.envelope.source_revision);});
test('original transport failure emits no proposed advance; resume retries same cursor and preserves all messages',async()=>{const p=provider();const t=await step(p),m=await step(p,t.checkpoint);const saved=structuredClone(m.checkpoint);p.state.failOriginal=true;await assert.rejects(step(p,saved),/HTTP_RETRY_EXHAUSTED/);assert.deepEqual(saved,m.checkpoint);p.state.failOriginal=false;const retry=await step(p,saved);assert.equal(retry.records[0].envelope.external_id,'M2');assert.equal(retry.checkpoint.state.phase,'ticket');});
test('note association is pinned by ID before separate GET despite mutation of the source list',async()=>{const p=provider();let cp=null,page;do{page=await step(p,cp);cp=page.checkpoint;}while(cp.state.phase!=='note');assert.equal(cp.state.noteId,'N1');p.state.mutated=true;const before=p.calls.length,next=await step(p,cp);assert.equal(p.calls[before].pathname,'/crm/v3/objects/notes/N1');assert.equal(next.records[0].envelope.external_id,'N1');assert.equal(next.checkpoint.state.innerAfter,'SYN-note-2');});
test('thread already captured is not replaced when mutable listing changes before messages',async()=>{let changed=false;const p=provider({transform:(data,u)=>u.pathname===base&&changed?{results:[thread('OUTSIDE')]}:data});const t=await step(p);changed=true;const m=await step(p,t.checkpoint);assert.equal(m.records[0].conversation_id,'T1');assert.equal(p.calls[1].pathname,base+'/T1/messages');});
test('replay of an uncommitted chunk preserves identity and source revision without advancing input checkpoint',async()=>{const p=provider(),first=await step(p),cp=structuredClone(first.checkpoint);const a=await step(p,cp),b=await step(p,cp);assert.equal(a.records[0].envelope.source_revision,b.records[0].envelope.source_revision);assert.equal(contentHash(a.checkpoint),contentHash(b.checkpoint));assert.deepEqual(cp,first.checkpoint);});
test('legacy v1 checkpoint resumes correct next root cursor and upgrades only after a successful chunk',async()=>{const p=provider(),first=await step(p),legacy={version:1,scope:first.checkpoint.scope,cursor:'SYN-thread-2'};const next=await step(p,legacy);assert.equal(next.records[0].envelope.external_id,'T2');assert.equal(next.checkpoint.version,2);assert.equal(p.calls.at(-1).searchParams.get('after'),'SYN-thread-2');});
test('selected IDs retain direct-only scope and nested v2 resume',async()=>{const p=provider(),pages=await all(p,{threadIds:['T1','T2']});assert.ok(!p.calls.some(u=>u.pathname===base));assert.deepEqual(records(pages).filter(r=>r.envelope.entity_type==='thread').map(r=>r.envelope.external_id),['T1','T2']);const cp=pages[0].checkpoint;await assert.rejects(step(p,cp,{threadIds:['T2','T1']}),/CHECKPOINT_SCOPE/);});
test('old non-bounded consumer rejects checkpoint v2 before network, so rollback cannot skip nested work',async()=>{const p=provider(),first=await step(p),before=p.calls.length;await assert.rejects(step(p,first.checkpoint,{bounded:false}),/CHECKPOINT_SCOPE/);assert.equal(p.calls.length,before);});
for(const [name,mutate] of [
 ['tenant',c=>{c.scope='f'.repeat(64);} ],['phase',c=>{c.state.phase='http';}],['foreign URL ID',c=>{c.state.threadId='https://evil.invalid';}],['path ID',c=>{c.state.threadId='../OTHER';}],['cursor control',c=>{c.state.innerAfter='bad\n';}],['oversized cursor',c=>{c.state.innerAfter='x'.repeat(4097);}],['negative counter',c=>{c.state.steps.messages=-1;}],['fake history',c=>{c.state.seen.messages=['not-hash'];}],['hidden body',c=>{c.state.body='SYN body';}],['unsupported version',c=>{c.version=3;}],['note mismatch phase',c=>{c.state.noteId='N1';}],['no thread',c=>{c.state.threadId=null;}]
])test('malformed/scoped checkpoint rejects before network: '+name,async()=>{const p=provider(),first=await step(p),cp=structuredClone(first.checkpoint);mutate(cp);const before=p.calls.length;await assert.rejects(step(p,cp),/CHECKPOINT_SCOPE/);assert.equal(p.calls.length,before);});
test('opaque cursor with URL characters is encoded on allowlisted path, never followed',async()=>{const p=provider({transform:(data,u)=>u.pathname.endsWith('/messages')?{results:[]}:data}),first=await step(p),cp=first.checkpoint;cp.state.innerAfter='https://evil.invalid/?x=1#fragment';cp.state.seen.messages=[contentHash(cp.state.innerAfter)];cp.state.steps.messages=1;await step(p,cp);assert.equal(p.calls.at(-1).origin,'https://api.hubapi.com');assert.equal(p.calls.at(-1).pathname,base+'/T1/messages');assert.equal(p.calls.at(-1).searchParams.get('after'),cp.state.innerAfter);});
test('malicious nested next URL and changed conversation fail without advancing',async()=>{for(const mutate of [(data,u)=>u.pathname.endsWith('/messages')?{results:[],paging:{next:{after:'SYN',link:'https://evil.invalid/?after=SYN'}}}:data,(data,u)=>u.pathname.endsWith('/messages')?{results:[msg('SYN-wrong','OTHER')]}:data]){const p=provider({transform:mutate}),t=await step(p);if(mutate===undefined)assert.fail();const cp=structuredClone(t.checkpoint);if(p.calls.length===1){try{const m=await step(p,cp);assert.equal(m.errors[0].code,'THREAD_MISMATCH');assert.equal(m.records.length,0);}catch(e){assert.equal(e.code,'UNSAFE_NEXT');}}assert.deepEqual(cp,t.checkpoint);}});
test('nested cursor loop survives separate executions and stops before a repeated chunk',async()=>{const p=provider({transform:(data,u)=>u.pathname.endsWith('/messages')?{results:[msg('SYN-'+(u.searchParams.get('after')??'first'))],paging:{next:{after:'SYN-loop'}}}:data});const t=await step(p),m=await step(p,t.checkpoint);await assert.rejects(step(p,m.checkpoint),/CURSOR_LOOP/);});
test('root cursor loop survives separate thread executions',async()=>{const p=provider({transform:(data,u)=>u.pathname===base?{results:[thread()],paging:{next:{after:'SYN-loop'}}}:u.pathname.endsWith('/messages')?{results:[]}:data});const t=await step(p,null,{includeNotes:false,includeTickets:false}),m=await step(p,t.checkpoint,{includeNotes:false,includeTickets:false});await assert.rejects(step(p,m.checkpoint,{includeNotes:false,includeTickets:false}),/CURSOR_LOOP/);});
test('provider over-limit page and record limits fail before proposing a checkpoint',async()=>{const p=provider({transform:(data,u)=>u.pathname===base?{results:[thread('T1'),thread('T2')]}:data});await assert.rejects(step(p),/PROVIDER_PAGE_LIMIT/);const q=provider(),iterator=createHubSpotAdapter({...cfg,fetch:q.fetch,maxRecords:1}).pages();await iterator.next();await assert.rejects(iterator.next(),/RECORD_LIMIT/);});
test('bounded chunks fit SYN 200ms GET latency and retain real 15s deadline rather than extending it',async()=>{const p=provider({latency:200});let cp=null,count=0;for(let i=0;i<30;i++){const page=await step(p,cp,{clock:()=>new Date(epoch+p.state.elapsed),deadlineMs:epoch+p.state.elapsed+15000});count++;if(page.done)break;cp=page.checkpoint;}assert.ok(count>1&&count<30);assert.ok(p.state.elapsed>0);});
function repository(){let state={id:'SYN-sync',done:false,checkpoint:null,version:0,context,window_spec:{fetchFrom:new Date(epoch).toISOString()}},failCommit=false;const committed=[],attempts=[],conversations=new Set(),seen=new Set();return {committed,attempts,set failCommit(v){failCommit=v;},get state(){return structuredClone(state);},async ensure(){return structuredClone(state);},async claim(){return {fence:1};},async current(){return structuredClone(state);},async beginAttempt(){return {attemptId:'SYN-attempt',connectionId:context.connection_id};},async finishAttempt(v){attempts.push(v);},async release(){},async commitPage({page}){if(failCommit)throw Error('SYN commit failed');for(const r of page.records){const n=normalizeSyncRecord(r);if(n.envelope?.entity_type==='conversation')conversations.add(n.envelope.external_id);if(n.envelope?.entity_type==='message')assert.ok(conversations.has(n.payload.conversation_external_id),'conversation persisted before message');const key=r.envelope.entity_type+':'+r.envelope.external_id+':'+r.envelope.source_revision;seen.add(key);}committed.push(structuredClone(page));state={...state,checkpoint:structuredClone(page.checkpoint),done:page.done,version:state.version+1};return structuredClone(state);},get unique(){return seen.size;}};}
const window={from:'2026-08-01T00:00:00Z',to:'2026-10-06T00:00:00Z',overlapSeconds:0,version:'SYN'};
async function run(repo,p,extra={}){return runSync({repository:repo,connectionId:context.connection_id,mode:'backfill',window,adapterFactory:createCRMAdapterFactory({...cfg,fetch:p.fetch}),maxPages:1,...extra});}
test('real factory and runSync use small durable chunks; restart/replay cannot advance before commit',async()=>{const p=provider(),repo=repository();const first=await run(repo,p);assert.equal(first.state,'continuation');assert.equal(repo.state.checkpoint.version,2);assert.equal(repo.committed.length,1);const cp=repo.state.checkpoint;repo.failCommit=true;await assert.rejects(run(repo,p),/SYN commit failed/);assert.deepEqual(repo.state.checkpoint,cp);repo.failCommit=false;for(let i=0;i<30&&!repo.state.done;i++)await run(repo,p);assert.equal(repo.state.done,true);assert.equal(repo.unique,8);assert.ok(repo.committed.every(p=>p.records.length+p.errors.length<=1));});
test('deadline after committed progress returns continuation without recording a failed attempt',async()=>{const p=provider(),repo=repository();let time=0;const factory=()=>({async *pages(){const first=await step(p);yield first;time=16000;throw Object.assign(Error('DEADLINE_EXCEEDED'),{code:'DEADLINE_EXCEEDED'});}});const result=await run(repo,p,{adapterFactory:factory,clock:()=>time,deadlineMs:15000,maxPages:5});assert.equal(result.state,'continuation');assert.equal(result.pages,1);assert.deepEqual(result.checkpoint,repo.state.checkpoint);assert.equal(repo.attempts.at(-1).outcome,'continuation');assert.equal(repo.attempts.at(-1).error,undefined);});
test('deadline without committed progress and actual provider failure still surface as failures',async()=>{for(const code of ['DEADLINE_EXCEEDED','HTTP_ERROR']){const repo=repository(),p=provider();const factory=()=>({async *pages(){throw Object.assign(Error(code),{code});}});await assert.rejects(run(repo,p,{adapterFactory:factory}),new RegExp(code));assert.equal(repo.committed.length,0);assert.equal(repo.attempts.at(-1).error.code,code);}});

for(const [code,time] of [['TIMEOUT',5000],['DEADLINE_EXCEEDED',5000],['NETWORK_ERROR',16000],['HTTP_ERROR',16000],['RECONNECT_REQUIRED',16000],['PROVIDER_SCHEMA',16000],['ABORTED',16000]])test('committed progress does not hide unrelated provider error: '+code+' at '+time,async()=>{const p=provider(),repo=repository();let now=0;const factory=()=>({async *pages(){yield await step(p);now=time;throw Object.assign(Error(code),{code});}});await assert.rejects(run(repo,p,{adapterFactory:factory,clock:()=>now,deadlineMs:15000,maxPages:5}),new RegExp(code));assert.equal(repo.committed.length,1);assert.equal(repo.attempts.at(-1).error.code,code);});
test('request timeout at exhausted execution deadline after durable progress is continuation',async()=>{const p=provider(),repo=repository();let now=0;const factory=()=>({async *pages(){yield await step(p);now=15000;throw Object.assign(Error('TIMEOUT'),{code:'TIMEOUT'});}});const result=await run(repo,p,{adapterFactory:factory,clock:()=>now,deadlineMs:15000,maxPages:5});assert.equal(result.state,'continuation');assert.equal(repo.attempts.at(-1).error,undefined);});
test('actual exhausted deadline with zero committed progress stays a failure',async()=>{const p=provider(),repo=repository();let now=0;const factory=()=>({async *pages(){now=16000;throw Object.assign(Error('DEADLINE_EXCEEDED'),{code:'DEADLINE_EXCEEDED'});}});await assert.rejects(run(repo,p,{adapterFactory:factory,clock:()=>now,deadlineMs:15000,maxPages:5}),/DEADLINE_EXCEEDED/);assert.equal(repo.committed.length,0);assert.equal(repo.attempts.at(-1).error.code,'DEADLINE_EXCEEDED');});

test('maxPages and maxRecords remain per invocation, not a new cap on full history',async()=>{const p=provider(),first=await step(p),cp=first.checkpoint;cp.state.steps.threads=20662;cp.state.totals.records=100001;cp.state.totals.rejected=1200;const next=await step(p,cp,{maxPages:1,maxRecords:1});assert.equal(next.records[0].envelope.external_id,'M1');assert.equal(next.checkpoint.state.totals.records,100002);assert.equal(next.checkpoint.state.steps.threads,20662);});
test('more than 20k previously seen thread cursors can resume without introducing a 10k cap',async()=>{const p=provider(),first=await step(p),cp=first.checkpoint;cp.state.phase='threads';cp.state.threadId=null;cp.state.ticketId=null;cp.state.seen.threads=Array.from({length:20662},(_,i)=>contentHash('SYN-past-'+i));cp.state.seen.threads.push(contentHash(cp.state.after));cp.state.steps.threads=20662;cp.state.totals.records=98908;const next=await step(p,cp,{maxPages:1});assert.equal(next.records[0].envelope.external_id,'T2');assert.equal(next.checkpoint.state.steps.threads,20663);assert.ok(Buffer.byteLength(JSON.stringify(next.checkpoint))<2*1024*1024);});
test('checkpoint byte cap rejects a oversized history before network rather than clearing loop protection',async()=>{const p=provider(),first=await step(p),cp=first.checkpoint;cp.state.seen.threads=Array.from({length:32000},(_,i)=>contentHash('SYN-past-'+i));const before=p.calls.length;await assert.rejects(step(p,cp),/CHECKPOINT_SCOPE/);assert.equal(p.calls.length,before);});

test('bounded mode never spends its chunk budget on hidden provider retries; the durable cursor retries next invocation',async()=>{const p=provider(),first=await step(p),cp=first.checkpoint;let calls=0,fail=true;const transport={calls:[],fetch:async raw=>{transport.calls.push(new URL(raw));calls++;return fail?new Response('{}',{status:429,headers:{'Retry-After':'1'}}):p.fetch(raw);}};await assert.rejects(step(transport,cp,{maxRetries:5,sleep:async()=>assert.fail('no hidden retry sleep')}),/HTTP_RETRY_EXHAUSTED/);assert.equal(calls,1);fail=false;const next=await step(transport,cp,{maxRetries:5});assert.equal(next.records[0].envelope.external_id,'M1');});
test('malformed original without text or richText remains a visible provider schema failure',async()=>{const p=provider({original:{attachment:'SYN unsupported'}}),first=await step(p),message=await step(p,first.checkpoint);await assert.rejects(step(p,message.checkpoint),/PROVIDER_SCHEMA/);});
test('notes cursor cycle is remembered across separate association and note chunks',async()=>{const p=provider({transform:(data,u)=>u.pathname.includes('/associations/notes')?{results:[{toObjectId:'N1'}],paging:{next:{after:'SYN-note-loop'}}}:data});let cp=null;for(let i=0;i<10;i++){const page=await step(p,cp);cp=page.checkpoint;if(cp.state.phase==='links'&&cp.state.innerAfter==='SYN-note-loop')break;}assert.equal(cp.state.phase,'links');await assert.rejects(step(p,cp),/CURSOR_LOOP/);});

for(const operation of ['current','commitPage'])test('repository '+operation+' TIMEOUT remains visible after deadline despite prior durable commit',async()=>{const p=provider(),repo=repository();let time=0,calls=0;const original=repo[operation];repo[operation]=async args=>{calls++;if(calls===(operation==='current'?3:2)){time=16000;throw Object.assign(Error('TIMEOUT'),{code:'TIMEOUT'});}return original(args);};const factory=()=>({async *pages(){const first=await step(p);yield first;yield await step(p,first.checkpoint);}});await assert.rejects(run(repo,p,{adapterFactory:factory,clock:()=>time,deadlineMs:15000,maxPages:5}),/TIMEOUT/);assert.equal(repo.committed.length,1);assert.equal(repo.state.version,1);assert.equal(repo.attempts.at(-1).error.code,'TIMEOUT');});
