import test from 'node:test';
import assert from 'node:assert/strict';
import {createHubSpotAdapter} from './hubspot.mjs';
const date='2026-10-05T12:00:00.000Z';
const cfg={context:{tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',source:'hubspot',source_account_id:'SYNTHETIC'},token:'SYNTHETIC',version:'v3',scopes:['conversations.read','tickets','crm.objects.contacts.read'],includeNotes:true,threadIds:['thread1']};
function adapter(link,requests=[]){return createHubSpotAdapter({...cfg,fetch:async input=>{const u=new URL(input);requests.push(u);let data;if(u.pathname.endsWith('/associations/notes'))data=u.searchParams.has('after')?{results:[{toObjectId:'n2'}]}:{results:[{toObjectId:'n1'}],paging:{next:{after:'next1',link}}};else if(u.pathname.includes('/objects/notes/'))data={id:u.pathname.split('/').at(-1),createdAt:date,properties:{hs_note_body:'SYNTHETIC note'}};else if(u.pathname.endsWith('/messages'))data={results:[]};else data={id:'thread1',createdAt:date,threadAssociations:{associatedTicketId:'ticket1'}};return new Response(JSON.stringify(data));}});}
async function collect(a){const pages=[];for await(const p of a.pages())pages.push(p);return pages;}
const alias='https://api.hubapi.com/crm/objects/v4/tickets/ticket1/associations/notes?limit=100&after=next1';
test('observed HubSpot note association link alias yields all notes using original allowlisted route',async()=>{const requests=[];const p=await collect(adapter(alias,requests));assert.deepEqual(p[0].records.filter(r=>r.envelope.entity_type==='note').map(r=>r.envelope.external_id),['n1','n2']);const next=requests.find(u=>u.searchParams.has('after'));assert.equal(next.pathname,'/crm/v4/objects/tickets/ticket1/associations/notes');assert.equal(next.searchParams.get('after'),'next1');assert.equal(p[0].coverage.notes_complete,true);});
for(const [name,link] of Object.entries({wrongTicket:alias.replace('ticket1','ticket2'),wrongAssociation:alias.replace('/notes?','/contacts?'),wrongHost:alias.replace('api.hubapi.com','evil.test'),http:alias.replace('https:','http:'),credentials:alias.replace('https://','https://user:pass@'),fragment:alias+'#x',differentLimit:alias.replace('limit=100','limit=200'),differentCursor:alias.replace('after=next1','after=next2'),duplicateLimit:alias+'&limit=100',unexpectedQuery:alias+'&account=other',encodedPath:alias.replace('/ticket1/','/%74icket1/')}))test('rejects alias with '+name+' before following cursor',async()=>{const requests=[];await assert.rejects(()=>collect(adapter(link,requests)),/UNSAFE_NEXT/);assert.ok(!requests.some(u=>u.searchParams.has('after')));});
