import test from 'node:test';
import assert from 'node:assert/strict';
import {createHubSpotAdapter} from './hubspot.mjs';
const base='/conversations/v3/conversations/threads',thread='SYN-thread',raw='U1lOLW1zZw%3D%3D',decoded='U1lOLW1zZw==';
const config={context:{tenant_id:'11111111-1111-4111-8111-111111111111',connection_id:'22222222-2222-4222-8222-222222222222',source:'hubspot',source_account_id:'SYN'},token:'SYN-token',version:'v3',scopes:['conversations.read'],threadIds:[thread],maxRetries:0};
const message=id=>({id,conversationsThreadId:thread,type:'MESSAGE',text:'SYN body',truncationStatus:'NOT_TRUNCATED',senders:[{actorId:'V-SYN'}]});
const alias='/conversations/conversations/v3/threads/'+thread+'/messages';
function provider({bounded=false,changeLink=x=>x,loop=false,cursor=raw}={}){const calls=[];return {calls,adapter:createHubSpotAdapter({...config,bounded,fetch:async input=>{const u=new URL(input);calls.push(u);if(u.pathname===base+'/'+thread)return Response.json({id:thread});assert.equal(u.pathname,base+'/'+thread+'/messages');const link='https://api.hubapi.com'+alias+'?limit='+(bounded?1:100)+'&archived=false&after='+cursor;if(!u.searchParams.has('after'))return Response.json({results:[message('M1')],paging:{next:{after:cursor,link:changeLink(link)}}});return Response.json({results:[message('M2')],...(loop?{paging:{next:{after:decoded,link:'https://api.hubapi.com'+alias+'?after='+encodeURIComponent(decoded)}}}:{})});}})};}
async function collect(adapter,checkpoint=null){const pages=[];for await(const p of adapter.pages({checkpoint}))pages.push(p);return pages;}
for(const bounded of [false,true])test('same-thread observed messages alias paginates safely, bounded='+bounded,async()=>{const p=provider({bounded}),pages=await collect(p.adapter);assert.deepEqual(pages.flatMap(p=>p.records.filter(r=>r.envelope.entity_type==='message').map(r=>r.envelope.external_id)),['M1','M2']);const next=p.calls.find(u=>u.searchParams.has('after'));assert.equal(next.searchParams.get('after'),decoded);assert.ok(next.href.includes('after='+raw));assert.ok(!next.href.includes('%253D'));assert.equal(next.pathname,base+'/'+thread+'/messages');});
test('v2 nested cursor resumes without re-reading thread or double encoding',async()=>{const a=provider({bounded:true}),it=a.adapter.pages();await it.next();const chunk=await it.next();await it.return();assert.equal(chunk.value.checkpoint.state.innerAfter,raw);const b=provider({bounded:true}),pages=await collect(b.adapter,chunk.value.checkpoint);assert.equal(b.calls.length,1);assert.equal(b.calls[0].searchParams.get('after'),decoded);assert.equal(pages[0].records[0].envelope.external_id,'M2');});
for(const [name,changeLink] of Object.entries({crossThread:x=>x.replace(thread,'OTHER'),originalContent:x=>x.replace('/messages?','/messages/M1/original-content?'),directThread:x=>x.replace('/messages?','?'),foreignHost:x=>x.replace('api.hubapi.com','evil.invalid'),http:x=>x.replace('https:','http:'),credentials:x=>x.replace('https://','https://user:pass@'),fragment:x=>x+'#SYN',changedLimit:x=>x.replace('limit=1','limit=2'),changedArchived:x=>x.replace('archived=false','archived=true'),duplicateAfter:x=>x+'&after='+raw,foreignQuery:x=>x+'&tenant=OTHER',differentCursor:x=>x.replace(raw,'OTHER%3D'),doubleEncoding:x=>x.replace(raw,raw.replaceAll('%','%25')),encodedPath:x=>x.replace(thread,'%53YN-thread')}))test('reject manipulated messages alias before next page: '+name,async()=>{const p=provider({bounded:true,changeLink}),it=p.adapter.pages();await it.next();await assert.rejects(it.next(),/UNSAFE_NEXT/);assert.equal(p.calls.length,2);});
test('nested loop detects encoded/plain equivalent cursor across v2 resume',async()=>{const p=provider({bounded:true,loop:true}),it=p.adapter.pages();await it.next();const first=await it.next();await it.return();const next=provider({bounded:true,loop:true});await assert.rejects(collect(next.adapter,first.value.checkpoint),/CURSOR_LOOP/);assert.equal(next.calls.length,1);});
