import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {createCRMWebhookBindings,createCRMWebhookHandler} from './webhooks.mjs';
const origin='https://vexa.example',now=Date.parse('2026-09-29T00:00:00Z');const hub={id:'SYN_hubspot_binding_0001',tenantId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',connectionId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',source:'hubspot',accountId:'123',appId:'456',secret:'SYN-HUBSPOT-SECRET-NOT-REAL-1234567890'},zen={...hub,id:'SYN_zendesk_binding_0002',connectionId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',source:'zendesk',accountId:'SYN-zendesk-account',secret:'SYN-ZENDESK-SECRET-NOT-REAL-1234567890'};delete zen.appId;
function request(binding,{body=Buffer.from(binding.source==='hubspot'?'[ {"portalId":123,"appId":456,"private":"SYN-CANARY-PII"} ]':'{"event":"ticket.updated","private":"SYN-CANARY-PII"}'),stamp=now,url=origin+'/api/webhooks/crm/'+binding.id,signUrl=url,headers={},method='POST'}={}){
 const t=binding.source==='hubspot'?String(stamp):new Date(stamp).toISOString();const h={'content-type':'application/json'};
 if(binding.source==='hubspot'){h['x-hubspot-request-timestamp']=t;h['x-hubspot-signature-v3']=createHmac('sha256',binding.secret).update('POST'+signUrl).update(body).update(t).digest('base64');}
 else{h['x-zendesk-webhook-signature-timestamp']=t;h['x-zendesk-webhook-signature']=createHmac('sha256',binding.secret).update(t).update(body).digest('base64');}
 return new Request(url,{method,headers:{...h,...headers},...(method==='POST'?{body}: {})});
}
function setup(extra={}){const calls=[];const handler=createCRMWebhookHandler({bindings:createCRMWebhookBindings(JSON.stringify([hub,zen]),origin),clock:()=>now,record:async x=>{calls.push(x);return{status:'accepted'};},...extra});return{calls,handler};}
for(const binding of [hub,zen])test(binding.source+' verifies signed raw bytes and only passes configured identity plus digest to persistence',async()=>{const f=setup(),response=await f.handler(request(binding));assert.equal(response.status,202);assert.equal(f.calls.length,1);assert.deepEqual(Object.keys(f.calls[0]).sort(),['binding','digest']);assert.equal(f.calls[0].binding.tenantId,hub.tenantId);assert.match(f.calls[0].digest,/^[0-9a-f]{64}$/);const body=await response.text();assert.equal(body.includes('SYN-CANARY'),false);assert.equal(body.includes(binding.secret),false);assert.match(response.headers.get('cache-control'),/private, no-store/);});
const cases={
 tampered_signature:b=>request(b,{headers:{[b.source==='hubspot'?'x-hubspot-signature-v3':'x-zendesk-webhook-signature']:'A'.repeat(43)+'='}}),
 stale:b=>request(b,{stamp:now-300001}),future:b=>request(b,{stamp:now+60001}),
 wrong_origin:b=>request(b,{url:'https://other.example/api/webhooks/crm/'+b.id}),query:b=>request(b,{url:origin+'/api/webhooks/crm/'+b.id+'?tenant=OTHER'}),
 missing_signature:b=>request(b,{headers:{[b.source==='hubspot'?'x-hubspot-signature-v3':'x-zendesk-webhook-signature']:''}}),
 oversized_declared:b=>request(b,{headers:{'content-length':'1048577'}}),compressed:b=>request(b,{headers:{'content-encoding':'gzip'}}),wrong_type:b=>request(b,{headers:{'content-type':'text/plain'}}),
 malformed_json:b=>request(b,{body:Buffer.from('{"SYN-CANARY-RAW":')}),invalid_utf8:b=>request(b,{body:Buffer.from([0xc0,0xaf])})
};for(const b of [hub,zen])for(const[name,make]of Object.entries(cases))test(b.source+' rejects '+name+' before DB',async()=>{const f=setup(),r=await f.handler(make(b));assert.ok(r.status>=400,r.status);assert.equal(f.calls.length,0);assert.equal((await r.text()).includes('SYN-CANARY'),false);});
test('HubSpot portal/app identity and URL signed scope cannot be reassigned',async()=>{for(const body of ['[{"portalId":999,"appId":456}]','[{"portalId":123,"appId":999}]','[{"portalId":123,"appId":456},{"portalId":999,"appId":456}]','[{"portalId":9007199254740993,"appId":456}]']){const f=setup(),r=await f.handler(request(hub,{body:Buffer.from(body)}));assert.equal(r.status,403);assert.equal(f.calls.length,0);}const f=setup(),r=await f.handler(request(hub,{signUrl:origin+'/api/webhooks/crm/other_callback_0001'}));assert.equal(r.status,401);assert.equal(f.calls.length,0);});
test('HubSpot retains exact whitespace in signature input',async()=>{const f=setup(),r=request(hub);const headers=new Headers(r.headers);const changed=new Request(r.url,{method:'POST',headers,body:JSON.stringify(JSON.parse(await r.text()))});assert.equal((await f.handler(changed)).status,401);assert.equal(f.calls.length,0);});
test('Zendesk secret cannot be reused for another server binding (signature does not bind URL)',()=>{assert.throws(()=>createCRMWebhookBindings(JSON.stringify([zen,{...zen,id:'SYN_other_binding_0003',connectionId:hub.connectionId,tenantId:'dddddddd-dddd-4ddd-8ddd-dddddddddddd'}]),origin));});
test('configuration rejects nonstrings, collisions, credentials in URLs and unknown fields',()=>{for(const rows of [[{...hub,id:1234567890123456}],[hub,hub],[{...zen,tenantId:'unknown'}],[{...hub,url:'https://arbitrary.example'}],[{...zen,secret:'short'}]])assert.throws(()=>createCRMWebhookBindings(JSON.stringify(rows),origin));for(const url of ['https://user:secret@vexa.example','http://vexa.example','https://vexa.example/path','https://vexa.example/'])assert.throws(()=>createCRMWebhookBindings(JSON.stringify([hub]),url));});
test('durable response is awaited; duplicate, rate limit and failure reported without secrets',async()=>{let release;const pending=new Promise(resolve=>{release=resolve;});const f=setup({record:async()=>{await pending;return{status:'accepted'};}});let done=false;const p=f.handler(request(zen)).then(r=>{done=true;return r;});await new Promise(r=>setTimeout(r,10));assert.equal(done,false);release();assert.equal((await p).status,202);for(const [status,http]of [['duplicate',200],['rate_limited',429],['unavailable',503]]){const g=setup({record:async()=>({status})}),response=await g.handler(request(zen));assert.equal(response.status,http);if(http===429)assert.equal(response.headers.get('retry-after'),'60');}const g=setup({record:async()=>{throw Error('SYN-SECRET-DATABASE-CANARY');}});const response=await g.handler(request(zen));assert.equal(response.status,503);assert.equal((await response.text()).includes('CANARY'),false);});
test('stream body cap and read deadline cancel without admission',async()=>{let cancelled=false;const large=new ReadableStream({start(c){c.enqueue(new Uint8Array(1048577));},cancel(){cancelled=true;}});const f=setup(),r=await f.handler(new Request(origin+'/api/webhooks/crm/'+zen.id,{method:'POST',headers:{'content-type':'application/json'},body:large,duplex:'half'}));assert.equal(r.status,413);assert.ok(cancelled);assert.equal(f.calls.length,0);cancelled=false;const stalled=new ReadableStream({pull(){return new Promise(()=>{});},cancel(){cancelled=true;}});const g=setup({readTimeoutMs:20}),s=await g.handler(new Request(origin+'/api/webhooks/crm/'+zen.id,{method:'POST',headers:{'content-type':'application/json'},body:stalled,duplex:'half'}));assert.equal(s.status,408);assert.ok(cancelled);assert.equal(g.calls.length,0);});
test('unsigned and unsupported methods do not create work',async()=>{const f=setup();assert.equal((await f.handler(new Request(origin+'/api/webhooks/crm/'+hub.id))).status,405);assert.equal(f.calls.length,0);assert.equal((await createCRMWebhookHandler({})(request(hub))).status,503);});
test('new signed delivery with identical body still wakes sync; exact retry has identical fingerprint',async()=>{for(const b of [hub,zen]){const f=setup();assert.equal((await f.handler(request(b))).status,202);assert.equal((await f.handler(request(b))).status,202);assert.equal((await f.handler(request(b,{stamp:now+1000}))).status,202);assert.equal(f.calls[0].digest,f.calls[1].digest);assert.notEqual(f.calls[0].digest,f.calls[2].digest);}});
