import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';
import {setup,q} from './harness.mjs';import {fixtureFactory} from './fixtures.mjs';import {syntheticConfig} from '../F04-extraction/config-fixture.mjs';
test('F04-05 durable problems isolated spaces stable identities and human revisions',{timeout:360000},async t=>{
 const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'vexa-problems237-'));fs.chmodSync(evidence,0o700);let h;
 try{
 h=await setup(process.env.VEXA_CANDIDATE,evidence);const fixture=await fixtureFactory(h),{createProblemRepository}=await import(pathToFileURL(path.join(h.built,'packages/problems/repository.mjs'))),{createProblemRuntime,createProblemConfigResolver}=await import(pathToFileURL(path.join(h.built,'packages/problems/runtime.mjs')));const requests=[],configured=new Set(),orders=new Map();
 function config(tenantId,{modelId='synthetic/model',version='SYN-space-v1',dimensions=3}={}){const c=syntheticConfig(tenantId);c.gateway.policy.allowedModels=[modelId];c.gateway.modelsByRole.extraction[0].model=modelId;return {tenantId,modelId,dimensions,version,threshold:0.2,gateway:{policy:c.gateway.policy,candidate:c.gateway.modelsByRole.extraction[0],catalog:{...c.gateway.catalog,models:[{id:modelId,dimensions,contextTokens:200000}]}}};}
 async function group({actor,vector=[1,0,0],space={},unknownCost=false}={}){const f=await fixture('customer',actor);await f.complete();if(!orders.has(f.a.tenant)){const oid=randomUUID();h.sql(`INSERT INTO orders(id,tenant_id,external_id,amount_minor,currency,exponent,occurred_at) VALUES(${q(oid)},${q(f.a.tenant)},'SYN-order237',10000,'USD',2,now())`);orders.set(f.a.tenant,oid);}h.sql(`UPDATE conversations SET order_id=${q(orders.get(f.a.tenant))} WHERE id=${q(f.conversationId)}`);const c=config(f.a.tenant,space),resolveConfig=createProblemConfigResolver(JSON.stringify([c])),repository=createProblemRepository({database:f.database});if(!configured.has(f.a.tenant)){await h.budgetModule.createDurableBudgetRepository({database:f.database,purpose:'embedding',jobId:f.jobId}).configure({purpose:'all',window:'SYN',limitMinor:'10000000'});await h.budgetModule.createDurableBudgetRepository({database:f.database,purpose:'embedding',jobId:f.jobId}).configure({purpose:'embedding',window:'SYN',limitMinor:'5000000'});configured.add(f.a.tenant);}const requestKey=randomUUID(),job=await repository.submit({extractionRunId:f.prepared.runId,requestKey,configHash:resolveConfig(f.a.tenant).hash});const worker=await h.actor('analyst',f.a.tenant);h.sql(`INSERT INTO worker_delegations(tenant_id,user_id,enabled) VALUES(${q(f.a.tenant)},${q(worker.id)},true)`);const runtime=createProblemRuntime({database:h.database(worker),resolveConfig,apiKey:'SYN-PROBLEMS-KEY',runtime:'enabled',fetch:async(url,init)=>{const body=JSON.parse(init.body);requests.push(body);assert.equal(JSON.stringify(body).includes('Ana Pérez'),false,'RAW_TRANSCRIPT_NOT_SENT');return Response.json({id:'SYN-EMBED',model:c.modelId,data:[{index:0,embedding:vector}],usage:{...(unknownCost?{}:{cost:'0.000020'}),prompt_tokens:20,total_tokens:20}});}});return {...f,repository,runtime,job,requestKey,resolveConfig,worker,config:c,run:async()=>{const result=await runtime.tick();assert.equal(result.state,'succeeded','DURABLE_EMBEDDING_SUCCESS:'+JSON.stringify(result));return result;}};}
 let A,B,first,second;
 await t.test('real extraction feeds redacted provider and persistent job replay does not duplicate',async()=>{A=await group();await A.run();first=(await A.repository.list())[0];assert.ok(first?.id);assert.equal(first.embeddingIds.length,1);assert.equal(first.outlier,true,'NEW_CLUSTER_REVIEW_OUTLIER');const replay=await A.repository.submit({extractionRunId:A.prepared.runId,requestKey:A.requestKey,configHash:A.resolveConfig(A.a.tenant).hash});assert.equal(replay.id,A.job.id);assert.equal((await A.runtime.tick()).state,'idle');assert.equal(requests.length,1);});
 await t.test('identical vector in B is filtered in SQL before distance and never returned to A',async()=>{B=await group();await B.run();const foreign=(await B.repository.list())[0],hits=await A.repository.retrieve({embeddingId:first.embeddingIds[0],limit:50});assert.ok(hits.length>0);assert.ok(hits.every(x=>!foreign.embeddingIds.includes(x.embeddingId)),'TENANT_VECTOR_PREFILTER');await assert.rejects(A.repository.retrieve({embeddingId:foreign.embeddingIds[0],limit:50}));});
 await t.test('incremental similar extraction preserves stable problem ID',async()=>{const f=await group({actor:A.a});await f.run();const items=await A.repository.list();assert.ok(items.some(x=>x.id===first.id),'STABLE_PROBLEM_ID');second=items.find(x=>x.id===first.id);assert.equal(second.embeddingIds.length,2,'INCREMENTAL_MEMBERSHIP');});
 await t.test('version space is isolated even with identical vectors',async()=>{const f=await group({actor:A.a,space:{version:'SYN-space-v2'}});await f.run();const hits=await A.repository.retrieve({embeddingId:first.embeddingIds[0],limit:50}),other=(await A.repository.list()).filter(x=>x.embeddingVersion==='SYN-space-v2').flatMap(x=>x.embeddingIds);assert.ok(other.length);assert.ok(hits.every(x=>!other.includes(x.embeddingId)),'SPACE_VERSION_FILTER');});
 for(const space of [{modelId:'synthetic/other-model'},{dimensions:4}])await t.test('model and dimensions create isolated SQL retrieval spaces '+JSON.stringify(space),async()=>{const f=await group({actor:A.a,space,vector:space.dimensions===4?[1,0,0,0]:[1,0,0]});await f.run();const newer=(await A.repository.list()).filter(x=>x.modelId!=='synthetic/model'||x.dimensions!==3).flatMap(x=>x.embeddingIds),hits=await A.repository.retrieve({embeddingId:first.embeddingIds[0],limit:50});assert.ok(newer.length);assert.ok(hits.every(x=>!newer.includes(x.embeddingId)),'MODEL_DIMENSION_FILTER');});
 for(const stage of ['before-network','after-network'])await t.test('SIGKILL worker recovery preserves durable boundary '+stage,async()=>{const f=await group(),sent=requests.length,child=await h.child(f.worker,{config:f.config,stage},'tick',[],{crash:true});assert.equal(child.signal,'SIGKILL','REAL_CHILD_KILLED');assert.equal(child.result.barrier,stage==='before-network'?'CLAIM_COMMITTED':'NETWORK_ATTEMPT_STARTED');h.sql(`UPDATE jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=${q(f.job.id)}`);const out=await f.runtime.tick();if(stage==='before-network'){assert.equal(out.state,'succeeded');assert.equal(requests.length,sent+1);}else{assert.equal(out.reason,'reconciliation_required');assert.equal(requests.length,sent);const held=h.json(`SELECT jsonb_build_object('held',held_minor::text,'actual',actual_minor,'state',state) FROM ai_budget_reservations WHERE job_id=${q(f.job.id)}`);assert.ok(BigInt(held.held)>0n);assert.equal(held.actual,null);assert.ok(['reserved','uncertain'].includes(held.state));}assert.equal((await f.runtime.tick()).state,'idle');});
 await t.test('missing provider cost remains uncertain without free retry',async()=>{const f=await group({unknownCost:true}),sent=requests.length,out=await f.runtime.tick();assert.equal(out.reason,'reconciliation_required');assert.equal(requests.length,sent+1);assert.equal((await f.runtime.tick()).state,'idle');const held=h.json(`SELECT jsonb_build_object('held',held_minor::text,'actual',actual_minor,'state',state) FROM ai_budget_reservations WHERE job_id=${q(f.job.id)}`);assert.equal(held.state,'uncertain');assert.equal(held.actual,null);assert.ok(BigInt(held.held)>0n);});
 await t.test('space oracle rejects a real SQL mutation removing version predicate',async()=>{const file=path.join(h.built,'packages/problems/repository.mjs'),mutant=path.join(h.built,'packages/problems/repository-mutant237.mjs'),original=fs.readFileSync(file,'utf8');assert.ok(original.includes('e.version=$5'),'MUTANT_TARGET_REQUIRED');fs.writeFileSync(mutant,original.replace('e.version=$5','$5::text IS NOT NULL'));try{const module=await import(pathToFileURL(mutant)),hits=await module.createProblemRepository({database:A.database}).retrieve({embeddingId:first.embeddingIds[0],limit:50}),old=new Set((await A.repository.list()).filter(x=>x.embeddingVersion==='SYN-space-v1').flatMap(x=>x.embeddingIds));assert.throws(()=>assert.ok(hits.every(x=>old.has(x.embeddingId)),'SPACE_VERSION_FILTER'),{code:'ERR_ASSERTION'},'MUTANT_MUST_FAIL_REAL_ORACLE');}finally{fs.rmSync(mutant);}});
 await t.test('split and merge CAS preserve immutable history and deduplicated provenance',async()=>{const before=await A.repository.detail({problemId:first.id}),body={operation:'split',parents:[{problemId:before.id,expectedVersion:before.version}],children:before.embeddingIds.map((id,i)=>({label:'SYN split '+i,embeddingIds:[id]})),reason:'SYN human review distinct causes',approved:true};const children=await A.repository.restructure(body);assert.equal(children.length,2);await assert.rejects(A.repository.restructure(body),undefined,'STALE_CAS_REPLAY');const retired=await A.repository.detail({problemId:first.id});assert.equal(retired.state,'retired');for(const snap of before.history)assert.deepEqual(retired.history.find(x=>x.id===snap.id),snap,'IMMUTABLE_SNAPSHOT');const merged=await A.repository.restructure({operation:'merge',parents:children.map(x=>({problemId:x.id,expectedVersion:x.version})),children:[{label:'SYN merged',embeddingIds:children.flatMap(x=>x.embeddingIds)}],reason:'SYN reviewed common cause',approved:true});assert.equal(merged.length,1);assert.equal(new Set(merged[0].embeddingIds).size,merged[0].embeddingIds.length);assert.deepEqual(merged[0].orderIds,[orders.get(A.a.tenant)],'KNOWN_ORDER_PROVENANCE_PRESERVED_ONCE');assert.equal(new Set(merged[0].orderIds).size,merged[0].orderIds.length,'NO_DOUBLE_ORDER');assert.deepEqual(new Set(merged[0].conversationIds),new Set(before.conversationIds));});
 await t.test('revoked source cannot influence future nearest-neighbor assignment',async()=>{const old=await group();await old.run();const prior=(await old.repository.list())[0];h.sql(`UPDATE connections SET status='disconnected' WHERE id=${q(old.a.connection)}`);assert.equal((await old.repository.list()).length,0,'OLD_SOURCE_HIDDEN');const next=await group({actor:old.a});await next.run();const member=h.sql(`SELECT problem_id FROM problem_embedding_members WHERE extraction_run_id=${q(next.prepared.runId)}`);assert.notEqual(member,prior.id,'REVOKED_VECTOR_MUST_NOT_INFLUENCE_ASSIGNMENT');assert.equal((await next.repository.list()).length,1,'NEW_VALID_EXTRACTION_VISIBLE');});
 await t.test('viewer cannot submit/restructure; revoked actor loses vector access',async()=>{const actor=await h.actor('viewer',A.a.tenant),viewer=createProblemRepository({database:h.database(actor)});await assert.rejects(viewer.submit({extractionRunId:A.prepared.runId,requestKey:randomUUID(),configHash:A.resolveConfig(A.a.tenant).hash}));h.sql(`UPDATE memberships SET status='revoked' WHERE user_id=${q(A.a.id)}`);await assert.rejects(A.repository.retrieve({embeddingId:first.embeddingIds[0]}));});
 await t.test('arbitrary driver status and domain-shaped code remain sanitized503',async()=>{const actor=await h.actor(),database=h.database(actor,{fault:{before(sql){if(sql.includes('DISTINCT ON(problem_id)'))throw Object.assign(Error('SYN driver private detail'),{status:404,code:'problem_not_found'});}}}),repository=createProblemRepository({database});await assert.rejects(repository.list(),e=>e.status===503&&e.code==='database_unavailable'&&!e.message.includes('private detail'),'DRIVER_SHAPE_NOT_TRUSTED');});
 h.verifySources();fs.writeFileSync(path.join(evidence,'requests.json'),JSON.stringify(requests),{mode:0o600});
 }finally{if(h)await h.close();console.log('F0405_DOMAIN_EVIDENCE:'+evidence);}
});
