import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';import {fork} from 'node:child_process';import {once} from 'node:events';
export const q=value=>"'"+String(value).replaceAll("'","''")+"'";
export async function setup(candidate,evidence){
 for(const relative of ['packages/intelligence/extraction-repository.mjs','supabase/migrations/0012_extraction_redaction.sql'])assert.ok(candidate&&fs.existsSync(path.join(candidate,relative)),'F04_BUDGET_IMPLEMENTATION_MISSING:'+relative);
 const driver=fs.mkdtempSync(path.join(os.tmpdir(),'f0403-driver-')),base=new URL('../../tests/acceptance/support/F03-sync/harness.mjs',import.meta.url);let h;const pools=new Set(),children=new Set();
 try{
  let code=fs.readFileSync(base,'utf8').replace("from '../../scaffold-copy.mjs'",'from '+JSON.stringify(new URL('../../scaffold-copy.mjs',base).href));
  code=code.replace(/new URL\('([^']+)',import.meta.url\)/g,(_,relative)=>'new URL('+JSON.stringify(new URL(relative,base).href)+')');
  code=code.replaceAll('58300','59623').replaceAll('58301','59624').replaceAll('58302','59625').replaceAll('f0303','f0403');
  code=code.replace("['packages/connectors','packages/platform'","['packages/problems','packages/gateway','packages/intelligence','packages/connectors','packages/platform'");
  code=code.replace('h.probe=infra.probe;','h.probe=infra.probe;h.realUser=()=>infra.user();h.auth=infra.http;');
  const moduleFile=path.join(driver,'harness.mjs');fs.writeFileSync(moduleFile,code);h=await(await import(pathToFileURL(moduleFile))).setup(candidate,evidence);
  const close=h.close.bind(h);h.close=async()=>{for(const pool of pools)await pool.end();for(const child of children)if(child.exitCode===null&&child.signalCode===null){const ended=once(child,'exit');child.kill('SIGKILL');await ended;}await close();fs.rmSync(driver,{recursive:true,force:true});};
  for(const name of ['problems','gateway','intelligence'])fs.cpSync(path.join(h.tmp,'packages',name),path.join(h.built,'packages',name),{recursive:true});
  const{default:pg}=await import(pathToFileURL(path.join(h.tmp,'node_modules/pg/lib/index.js')));const{createDatabase}=await import(pathToFileURL(path.join(h.built,'packages/platform/db.mjs')));h.budgetModule=await import(pathToFileURL(path.join(h.built,'packages/gateway/durable-budget.mjs')));
  h.actor=async(role='owner',tenant=randomUUID())=>{const account=await h.realUser(),actor={...account,tenant,role};h.sql(`INSERT INTO organizations(id,name) VALUES(${q(tenant)},'SYNTHETIC budget') ON CONFLICT DO NOTHING;INSERT INTO memberships(tenant_id,user_id,role,status) VALUES(${q(tenant)},${q(actor.id)},${q(role)},'active')`);return actor;};
  h.job=(actor,purpose='extraction')=>{const id=randomUUID();h.sql(`INSERT INTO jobs(id,tenant_id,type,state,input_ref,input_hash,version) VALUES(${q(id)},${q(actor.tenant)},${q(purpose)},'running','SYNTHETIC:budget-input',${q(randomUUID())},'SYN-v1')`);return id;};
  h.database=(actor,{fault}={})=>{const pool=new pg.Pool({...h.connection,max:3});pools.add(pool);const wrapped={async connect(){const connection=await pool.connect();return{release:()=>connection.release(),async query(sql,values){await fault?.before?.(sql,values,connection);try{return await connection.query(sql,values);}catch(error){fs.appendFileSync(path.join(evidence,'budget-sql-errors.jsonl'),JSON.stringify({sql,code:error.code,message:error.message})+'\n',{mode:0o600});throw error;}}};}};const identity={async getUser(){const result=await h.auth('auth','/user',actor.token);assert.equal(result.status,200,'REAL_AUTH_CURRENT_SESSION');return{id:result.data.id};},async memberships(){return[{tenant_id:actor.tenant,user_id:actor.id,role:actor.role,status:'active',permissions_version:1}];}};return createDatabase({identity,pool:wrapped,selectedTenant:actor.tenant});};
  h.budget=(actor,{purpose='extraction',jobId=h.job(actor,purpose),ownerToken=randomUUID(),fault}={})=>({repository:h.budgetModule.createDurableBudgetRepository({database:h.database(actor,{fault}),purpose,jobId,ownerToken}),purpose,jobId,ownerToken,actor});
  h.child=(actor,options,operation,args,{crash=false}={})=>new Promise((resolve,reject)=>{const env={PATH:process.env.PATH,F04_BUILD:h.built,F04_PG:path.join(h.tmp,'node_modules/pg/lib/index.js')};delete env.NODE_TEST_CONTEXT;const child=fork(new URL('./worker.mjs',import.meta.url),[],{execPath:process.execPath,execArgv:[],env,stdio:['ignore','ignore','ignore','ipc']});children.add(child);let result;const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('F04_BUDGET_CHILD_TIMEOUT'));},20000);child.on('message',message=>{result=message;if(message.barrier)child.kill('SIGKILL');});child.on('error',reject);child.on('exit',(code,signal)=>{clearTimeout(timer);children.delete(child);resolve({code,signal,result});});child.send({connection:h.connection,actor,options,operation,args,crash});});
  return h;
 }catch(error){if(h)await h.close();fs.rmSync(driver,{recursive:true,force:true});throw error;}
}
