import fs from 'node:fs';import path from 'node:path';import {randomUUID} from 'node:crypto';import os from 'node:os';import {pathToFileURL} from 'node:url';import {q} from './harness.mjs';
const evidence=process.env.F02_SQL_EVIDENCE;fs.mkdirSync(evidence,{recursive:true,mode:0o700});process.env.VEXA_CI_BROKER=randomUUID();process.env.VEXA_CI_JOURNAL=path.join(evidence,'resources.jsonl');fs.writeFileSync(process.env.VEXA_CI_JOURNAL,'',{mode:0o600});let h;const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'f02-sql007-'));
let source=fs.readFileSync(new URL('../F02-durable/isolated-infra.mjs',import.meta.url),'utf8').replace("'../ci/resources.mjs'",JSON.stringify(new URL('../ci/resources.mjs',import.meta.url).href)).replace("'../F01-03/matrix.mjs'",JSON.stringify(new URL('../F01-03/matrix.mjs',import.meta.url).href));for(const [a,b]of [['56327','58166'],['56328','58167'],['56329','58168']])source=source.replaceAll(a,b);fs.writeFileSync(path.join(tmp,'infra.mjs'),source);const {launch,candidateInputs}=await import(pathToFileURL(path.join(tmp,'infra.mjs')));
try{h=await launch({services:true});for(const ddl of candidateInputs(process.env.VEXA_CANDIDATE))h.sql(ddl);
const [A,B,U,V]=Array.from({length:4},()=>randomUUID());
h.sql(`INSERT INTO auth.users(id) VALUES(${q(U)}),(${q(V)}); INSERT INTO organizations(id,name) VALUES(${q(A)},'SYNTHETIC'),(${q(B)},'SYNTHETIC');INSERT INTO memberships(tenant_id,user_id,role,status) VALUES(${q(A)},${q(U)},'owner','active'),(${q(B)},${q(U)},'owner','active'),(${q(A)},${q(V)},'analyst','active'),(${q(B)},${q(V)},'analyst','active');`);
const prefix=`SET LOCAL ROLE vexa_backend; PERFORM set_config('request.jwt.claim.sub',${q(U)},true); PERFORM set_config('vexa.tenant_id',${q(A)},true); PERFORM set_config('vexa.action','configure',true); `;
const cases=[['cross_insert',`INSERT INTO worker_delegations VALUES(${q(B)},${q(V)},true,NULL)`],['change_tenant',`UPDATE worker_delegations SET tenant_id=${q(B)} WHERE tenant_id=${q(A)} AND user_id=${q(V)}`],['change_user',`UPDATE worker_delegations SET user_id=${q(U)} WHERE tenant_id=${q(A)} AND user_id=${q(V)}`]];
h.sql(`INSERT INTO worker_delegations VALUES(${q(A)},${q(V)},true,NULL)`);
const results=[];for(const [name,query]of cases){const statement=prefix+query+`; GET DIAGNOSTICS affected=ROW_COUNT; RESET ROLE; result=jsonb_build_object('affected',affected);`;const result=h.probe(statement);results.push({name,statement,result});console.log(name,result.code,result.rows);}
fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify(results,null,2));const violations=results.filter(r=>r.result.code==='00000'&&r.result.rows.affected>0);if(violations.length){fs.writeFileSync(path.join(evidence,'P1-007.md'),'P1 SQL tenant/identity boundaries: '+violations.map(r=>r.name).join(', ')+'. Real vexa_backend SQL; owner of A and B, selected A, configure. Each probe transaction rolled back. See results.json for full SQL and SQLSTATE. Product unchanged.');process.exitCode=1;}
}finally{if(h)h.close();fs.rmSync(tmp,{recursive:true,force:true});fs.writeFileSync(path.join(evidence,'cleanup.json'),JSON.stringify({ownResourcesRemoved:true}));}
