import test from 'node:test';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.VEXA_CANDIDATE;assert.ok(root,'EXPLICIT_CANDIDATE_REQUIRED');
const {adaptLedger}=await import(pathToFileURL(resolve(root,'packages/economics/adapter.mjs')));const {adaptMoneyMetric}=await import(pathToFileURL(resolve(root,'packages/metrics/money-adapter.mjs')));const {sumMoney}=await import(pathToFileURL(resolve(root,'packages/metrics/money.mjs')));
const scope={start:'2026-03-01T00:00:00Z',end:'2026-04-01T00:00:00Z',timezone:'UTC',dateBasis:'occurred_at',currency:'USD',exponent:2,basis:'gross_orders'},catalog={version:'SYN311',currencies:{USD:2,EUR:2}};
const row=(id,amountMinor,extra={})=>({id,externalId:id,tenantId:'SYN311-A',sourceAccount:'SYN-source',sourceRevision:'r1',evidenceRef:'e:'+id,basis:'gross_orders',provenance:'observed',occurredAt:'2026-03-12T00:00:00Z',recordedAt:'2026-03-13T00:00:00Z',currency:'USD',exponent:2,status:'recorded',amountMinor,...extra});
const input=orders=>({authorization:{tenantId:'SYN311-A',permissionsVersion:'v1'},snapshot:{tenantId:'SYN311-A',id:'SYN311-snapshot',asOf:'2026-04-02T00:00:00Z',sources:[{sourceAccount:'SYN-source',complete:true,watermark:'done'}]},scope,orders,events:[],links:[]});
const env=(l,id='metric')=>adaptMoneyMetric(l.metrics.allOrders,{tenantId:l.tenantId,catalog,scope:l.scope,metricId:id,additive:true,provenance:[{source:'SYN311',reference:id,version:'1'}]});
function seeded(){let x=42;return Array.from({length:31},(_,i)=>{x^=x<<13;x^=x>>>17;x^=x<<5;return row('o'+i,(100000000000000000001n+BigInt(x>>>0)).toString());});}
test('independent exact sum, permutation, disjoint partitions and metric replay',()=>{const rows=seeded(),expected=rows.reduce((s,r)=>s+BigInt(r.amountMinor),0n).toString();const original=input(rows),copy=structuredClone(original),full=adaptLedger(original);assert.equal(full.metrics.allOrders.amountMinor,expected,'INDEPENDENT_EXACT_SUM');assert.deepEqual(adaptLedger(input([...rows].reverse().concat(rows.slice(3,17)))),full,'RAW_REPLAY_DIGEST');assert.deepEqual(original,copy);
for(const n of [2,5,11]){const parts=Array.from({length:n},(_,j)=>rows.filter((_,i)=>i%n===j));assert.equal(new Set(parts.flat().map(x=>x.id)).size,31);const envelopes=parts.map((p,i)=>env(adaptLedger(input(p)),'part'+i));const result=sumMoney([...envelopes,envelopes[0]],{catalog});assert.equal(result.amount_minor,expected,'REPLAY_EXACT_VALUE');assert.deepEqual(result.coverage,{known_n:31,eligible_n:31});}});
test('unknown retains exact subtotal and coverage',()=>{const l=adaptLedger(input([row('k','999999999999999999999999999'),row('u',null)]));const m=env(l);assert.equal(m.amount_minor,null,'UNKNOWN_VALUE_ASSERTION');assert.equal(m.known_subtotal,'999999999999999999999999999','SUBTOTAL_PRECISION_ASSERTION');assert.deepEqual(m.coverage,{known_n:1,eligible_n:2});});
test('same-exponent foreign currency cannot be implicitly combined',()=>{const usd=env(adaptLedger(input([row('u','7')])),'usd');const eurInput=input([row('e','99',{currency:'EUR'})]);eurInput.scope={...scope,currency:'EUR'};const eur=env(adaptLedger(eurInput),'eur');assert.throws(()=>sumMoney([usd,eur],{catalog}),e=>e.code==='INCOMPATIBLE_MONEY_SCOPE','CURRENCY_ASSERTION');});
test('row authorization is checked before filters, not a SQL/RLS proof',()=>{for(const delta of [{currency:'EUR'},{status:'cancelled'},{occurredAt:'2026-02-01T00:00:00Z'}])assert.throws(()=>adaptLedger(input([row('foreign','17',{tenantId:'SYN311-B',...delta})])),e=>e.code==='TENANT_MISMATCH','TENANT_ASSERTION');});
test('resolved identity migration preserves independently known reversal and exposure',()=>{const i=input([row('o','101')]);i.events=[row('r','30',{kind:'refund',status:'settled'}),row('v','-9',{kind:'reversal',reversalOf:'r',status:'settled'})];i.links=[{tenantId:'SYN311-A',problemId:'p',orderId:'o',evidenceRef:'link',relationVersion:'1'}];const before=adaptLedger(i);for(const r of [...i.orders,...i.events]){r.id='new:'+r.id;r.externalId='new:'+r.externalId;r.sourceRevision='2';if(r.reversalOf)r.reversalOf='new:'+r.reversalOf;}i.links[0].orderId='new:o';const after=adaptLedger(i);assert.equal(after.metrics.refunds.amountMinor,'21','REVERSAL_MIGRATION_VALUE');assert.equal(after.metrics.exposure.global.amountMinor,'101');assert.notEqual(after.inputHash,before.inputHash);assert.equal(after.metrics.allOrders.amountMinor,'101');});
