// SYN-INTERVENTION286: real ingestion/extraction/snapshot/recommendation; no external execution.
import {randomUUID} from 'node:crypto';
import {seedRecommendations,scope,createReader} from '../F06-recommendations/fixtures.mjs';
export {scope,createReader};
export const reason='SYN authorized operational review of the fixed plan, current evidence and measurement limitations.';
export async function seedInterventions(h){
 const f=await seedRecommendations(h,async({ok,ledger})=>{const {dateBasis:_dateBasis,...economicQuery}=scope;const exposure=await ok(h.request(h.A,'/api/economics?'+new URLSearchParams(economicQuery)));await ledger({operation:'relationCoverage',scope,expectedInputHash:exposure.exposure.inputHash,expectedVersion:exposure.exposure.coverage?.version??0,complete:true,report:'SYN owner attests the exhaustive two-order relationship fixture; no unknown membership remains.',attested:true});});
 const query=new URLSearchParams({date_start:scope.start.slice(0,10),date_end:scope.end.slice(0,10),timezone:'UTC',date_basis:'occurred_at',currency:'USD',basis:scope.basis,snapshot_id:f.snapshot.id});const workspace=await f.ok(h.request(h.A,'/api/workspace?'+query+'&resource=problems'));query.set('scope_hash',workspace.meta.scope_hash);
 const recommendation=await f.ok(h.request(h.A,'/api/recommendations',{operation:'generate',query:query.toString(),problemId:f.p1.id,requestKey:randomUUID()}));
 const draft=await f.ok(h.request(h.A,'/api/recommendations/'+recommendation.id+'/interventions',{expectedVersion:recommendation.version,requestKey:randomUUID()}));
 return {...f,query,recommendation,draft};
}
export function planFor(f,ownerId,baseline=f.snapshot){const now=Date.now();return {hypothesis:'SYN A documented operational review may reduce repeated delivery contacts; no causal benefit is assumed.',ownerId,start:new Date(now).toISOString(),end:new Date(now+7*86400000).toISOString(),unit:'order',population:'SYN the explicitly captured authorized orders in this baseline scope, preserving overlaps.',outcome:'allOrders',controlPlan:'No randomized or comparable control; descriptive before-after association only.',metricDefinitionVersion:baseline.versions.policy,baselineSnapshotId:baseline.id,scopeHash:f.query.get('scope_hash'),maturityDays:0,concurrentChanges:'SYN none recorded; coverage, seasonality, migration and model changes must remain explicit.'};}
export async function measurementSnapshot(h,f,{start,end,amount,externalId}){
 const measurementScope={...scope,start,end};
 const src=await f.ok(h.request(h.A,'/api/economics',{operation:'source',sourceId:f.src.id,expectedVersion:f.src.version,name:'SYN intervention operational orders',evidenceType:'order_export',active:true,complete:true,windowStart:'2026-08-01T00:00:00.000Z',windowEnd:end,watermark:end,report:'SYN owner attests complete operational export through the elapsed measurement window.',attested:true}));f.src=src;
 const row=await f.ledger({operation:'record',sourceId:src.id,sourceVersion:src.version,expectedRevision:0,externalId,kind:'order',effectiveAt:new Date(Date.parse(start)+Math.floor((Date.parse(end)-Date.parse(start))/2)).toISOString(),currency:'USD',exponent:2,basis:scope.basis,amountMinor:amount,status:amount===null?'unknown':'recorded',orderId:null,reversalOf:null,details:{},report:'SYN observed operational amount for the real elapsed measurement interval; no narrative or causal inference.',attested:true});
 await f.ledger({operation:'link',problemId:f.p1.id,ledgerRowId:row.rowId,expectedVersion:0,active:true,report:'SYN operational relationship belongs to the same defined problem and population rule.',attested:true});
 const {dateBasis:_dateBasis,...economicQuery}=measurementScope;const view=await f.ok(h.request(h.A,'/api/economics?'+new URLSearchParams(economicQuery)));await f.ledger({operation:'relationCoverage',scope:measurementScope,expectedInputHash:view.exposure.inputHash,expectedVersion:view.exposure.coverage?.version??0,complete:true,report:'SYN exhaustive authorized review of all relationship records within this elapsed measurement scope.',attested:true});
 const draft=await f.ok(h.request(h.A,'/api/economic-snapshots',{operation:'stage',scope:measurementScope}));const snapshot=await f.ok(h.request(h.A,'/api/economic-snapshots',{operation:'publish',snapshotId:draft.id,expectedContentHash:draft.contentHash}));return {snapshot,row,scope:measurementScope};
}
