import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {launch,candidateInputs} from '../../tests/acceptance/support/F01-03/harness.mjs';
import {seed,foreignKeys} from '../../tests/acceptance/support/F01-03/oracles.mjs';
import * as history from '../../tests/acceptance/support/F01-03/source-history/oracles.mjs';
import * as snapshots from '../../tests/acceptance/support/F01-03/snapshot-oracles.mjs';
import * as workspace from '../../tests/acceptance/support/F01-03/workspace-oracles.mjs';
import * as recommendations from '../../tests/acceptance/support/F01-03/recommendation-oracles.mjs';
import * as intervention from '../../tests/acceptance/support/F01-03/intervention-oracles.mjs';
test('F06-05 SQL implementation required',()=>{assert.ok(fs.existsSync(path.join(process.env.VEXA_CANDIDATE,'supabase/migrations/0026_interventions.sql')),'INTERVENTION_SQL_IMPLEMENTATION_MISSING');});
test('F06-05 independent SQL state measurement and authorization',{timeout:300000},async t=>{
 const h=await launch({services:true});t.after(()=>{const c=process.env.VEXA_F01_03_CLEANUP;try{if(c)process.env.VEXA_F01_03_CLEANUP=c+'.targeted';h.close();}finally{if(c)process.env.VEXA_F01_03_CLEANUP=c;}});
 for(const sql of candidateInputs(process.env.VEXA_CANDIDATE))h.sql(sql);
 const keys=foreignKeys(h);
 await t.test('private FORCE RLS immutable history and tenant foreign keys',()=>intervention.schema(h,keys));
 const actors={};for(const key of ['a','b','dual','outsider','viewer','analyst','operator'])actors[key]=await h.user();
 const base=seed(h,actors);history.seedHistory(h,base);
 const snaps=snapshots.seed(h,base,actors),workspaces=await workspace.seed(h,base,actors,snaps),recs=await recommendations.seed(h,base,actors,workspaces);
 await t.test('exact scoped money and current source authorization',()=>intervention.projection(h,workspaces,actors));
 const f=intervention.seed(h,recs,actors);
 await t.test('plan state CAS roles and immutable approval content',()=>intervention.states(h,f,actors));
 let measured=false;await t.test('real ordered snapshot measurement exact delta and closed guard',async()=>{await intervention.lifecycle(h,f,recs,workspaces,actors);measured=true;});
 if(!measured)return;
 await t.test('removed operational owner recovery preserves plan and source authority',()=>intervention.assignment(h,f,actors));
 await t.test('refunds subtract real reversals and preserve unknown settlement',()=>intervention.refunds(h,f,workspaces,actors));
 await t.test('unknown partial and immature results cannot become savings or close',()=>intervention.partial(h,f,recs,workspaces,actors));
 await t.test('owner reopening preserves history and requires a fresh measurement',()=>intervention.reopen(h,f,actors));
 await t.test('financial zero-delta mutant is killed and original restored',()=>intervention.financialCalibration(h,f,actors));
 await t.test('captured dimension contributor revocation denies persisted result',()=>intervention.mappingAuthorization(h,f,actors));
 await t.test('audit privacy immutable history and result execution boundaries',()=>intervention.access(h,f,actors));
 for(const k of keys.filter(intervention.ownsFk))await t.test('intervention tenant FK '+k.name,()=>intervention.fk(h,f,k));
 await t.test('narrow helpers current role selected tenant and no service bypass',()=>intervention.scopedHelpers(h,recs,actors));
});
