import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {setup} from './harness.mjs';
const candidate=process.env.VEXA_CANDIDATE,evidence=process.env.VEXA_AUTH_BRAND_EVIDENCE;
assert.ok(candidate&&evidence);fs.mkdirSync(evidence,{recursive:true});
const listed=spawnSync('git',['ls-files','--cached','--others','--exclude-standard','-z'],{cwd:candidate,encoding:'utf8'});assert.equal(listed.status,0);const hash=file=>createHash('sha256').update(fs.readFileSync(path.join(candidate,file))).digest('hex');const inputs=Object.fromEntries(listed.stdout.split('\0').filter(Boolean).map(file=>[file,hash(file)]));fs.writeFileSync(path.join(evidence,'source-hashes.json'),JSON.stringify(inputs,null,2));
const h=await setup(candidate,evidence),checks=[];const pass=name=>{checks.push(name);console.log('PASS '+name);};
const q=value=>"'"+value.replaceAll("'","''")+"'";
async function message(email){for(let i=0;i<60;i++){const list=await(await fetch(h.mailURL+'/api/v1/messages')).json();const item=list.messages?.find(m=>m.To?.some(t=>t.Address===email));if(item)return await(await fetch(h.mailURL+'/api/v1/message/'+item.ID)).json();await new Promise(r=>setTimeout(r,100));}throw Error('LOCAL_MAIL_MISSING');}
function checkMail(mail){assert.match(mail.HTML,/VEXA/);assert.match(mail.HTML,/<h1 /);assert.match(mail.HTML,/background:#ffffff/);assert.ok(mail.Text?.includes('VEXA'),'PLAIN_TEXT_ALTERNATIVE');const link=mail.HTML.match(/href="([^"]+)"/)[1].replaceAll('&amp;','&');assert.equal(new URL(link).origin,'http://127.0.0.1:64601');return link;}
try{
 const browser=await h.launchBrowser(),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
 const owner=await h.user(),tenant=randomUUID();h.infra.sql(`INSERT INTO organizations(id,name)VALUES(${q(tenant)},'SYN Auth branding');INSERT INTO memberships(tenant_id,user_id,role,status)VALUES(${q(tenant)},${q(owner.userId)},'owner','active');NOTIFY pgrst,'reload schema';`);
 await page.goto(h.origin+'/login');await page.getByRole('button',{name:'Continuar con Google'}).waitFor();await page.getByRole('textbox',{name:'Correo',exact:true}).fill(owner.email);await page.getByRole('button',{name:'Solicitar enlace de acceso'}).click();await page.getByRole('status').waitFor();
 const mail=await message(owner.email),link=checkMail(mail);await page.screenshot({path:path.join(evidence,'login-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(evidence,'login-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});pass('login-browser-request-real-smtp-branded-html-text');
 const result=await fetch(link,{redirect:'manual'}),destination=result.headers.get('location');assert.equal(new URL(destination).origin,h.origin);assert.equal(new URL(destination).pathname,'/auth/email/complete');
 await page.goto(destination);await page.getByRole('button',{name:'Entrar al equipo',exact:true}).waitFor();assert.equal(new URL(page.url()).hash,'');await page.getByRole('button',{name:'Entrar al equipo',exact:true}).click();await page.waitForURL(h.origin+'/');assert.equal((await context.request.get(h.origin+'/')).status(),200);assert.equal((await context.cookies()).find(c=>c.name==='vexa_active_org')?.value,tenant);pass('magic-link-fragment-cleared-final-session-select-real-membership');
 const replay=await fetch(link,{redirect:'manual'});const invalid=new URL(replay.headers.get('location'));assert.ok(invalid.hash.includes('error'));const fresh=await browser.newContext(),freshPage=await fresh.newPage();await freshPage.goto(invalid.href);await freshPage.getByRole('alert').filter({hasText:'El enlace no es válido'}).waitFor();assert.equal((await fresh.cookies()).some(c=>c.name==='sb-127-auth-token'),false);pass('used-link-rejected-no-session');
 const csrf=await fetch(h.origin+'/auth/email/request',{method:'POST',headers:{'content-type':'application/json',origin:'https://foreign.example.test'},body:JSON.stringify({email:owner.email})});assert.equal(csrf.status,403);pass('cross-origin-request-denied');
 const email='invited-'+randomUUID()+'@example.test';const invite=await h.admin.auth.admin.inviteUserByEmail(email,{redirectTo:h.origin+'/auth/invitations/'+randomUUID()});assert.equal(invite.error,null);const inviteMail=await message(email);checkMail(inviteMail);assert.match(inviteMail.HTML,/Revisar invitación/);assert.doesNotMatch(inviteMail.HTML,/Aceptar invitación<\/a>/);pass('invitation-real-smtp-brand-keeps-explicit-team-acceptance');
 // Real issuer PKCE and callback with browser verifier, as used by the accepted Google callback.
 const pkceUser=await h.user(),pkceContext=await browser.newContext();await h.module.login(h,pkceContext,pkceUser.email,'/?tab=one');checkMail(await message(pkceUser.email));pass('real-local-pkce-mail-code-callback');
 const google=await context.request.post(h.origin+'/auth/google',{headers:{origin:h.origin},maxRedirects:0});assert.equal(google.status(),303);const oauth=new URL(google.headers().location);assert.equal(oauth.origin,'http://127.0.0.1:64601');assert.equal(oauth.pathname,'/auth/v1/authorize');assert.equal(oauth.searchParams.get('provider'),'google');assert.equal(oauth.searchParams.get('code_challenge_method'),'s256');assert.equal(oauth.searchParams.get('redirect_to'),h.origin+'/auth/callback');assert.match(oauth.searchParams.get('code_challenge'),/^[A-Za-z0-9_-]{43}$/);assert.ok((await context.cookies()).some(c=>c.name.endsWith('code-verifier')&&c.httpOnly&&c.sameSite==='Lax'));pass('google-start-pkce-s256-httpOnly-exact-callback-no-google-remote');
 const preview=await browser.newContext({viewport:{width:390,height:844},colorScheme:'dark'}),previewPage=await preview.newPage();await previewPage.setContent(mail.HTML.replace(/href="[^"]+"/g,'href="#"'));assert.equal(await previewPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await previewPage.screenshot({path:path.join(evidence,'email-mobile-dark.png'),fullPage:true});await previewPage.setViewportSize({width:1280,height:900});await previewPage.screenshot({path:path.join(evidence,'email-desktop.png'),fullPage:true});pass('email-responsive-browser-preview-light-dark-not-inbox-client-certification');
 await preview.close();await pkceContext.close();await fresh.close();await context.close();await browser.close();
 for(const [file,digest]of Object.entries(inputs))assert.equal(hash(file),digest,'INPUT_CHANGED:'+file);
 fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({node:process.version,checks,synthetic:true,remoteSends:0,googleRemote:false},null,2));
}finally{await h.close();}
