import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const fail=()=>{throw Object.assign(Error('RETENTION_OPERATION_REJECTED'),{status:400});};
const check=v=>{if(!v)fail();};
const strict=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k));
export const digest=value=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
const source=p=>{check(strict(p,['connectionId','entityType','externalId','requestId','confirmed'])&&uuid(p.connectionId)&&['message','conversation','customer'].includes(p.entityType)&&typeof p.externalId==='string'&&p.externalId.length>0&&p.externalId.length<=512);return structuredClone(p);};
const validateKey=k=>check(typeof k==='string'&&Buffer.byteLength(k)>=32);
/** Verify the complete signed ledger before any restore writes or transactional effects. */
export function verifyRecoveryLedger(document,{ledgerKey,expectedHash,notBefore,tenantId,clock=Date.now}={}){
 validateKey(ledgerKey);const saved=structuredClone(document),body=JSON.stringify(saved?.payload);
 check(typeof body==='string'&&typeof expectedHash==='string'&&/^[0-9a-f]{64}$/.test(expectedHash)&&saved.sha256===expectedHash&&digest(body)===expectedHash&&typeof saved.signature==='string'&&/^[0-9a-f]{64}$/.test(saved.signature));
 const signature=createHmac('sha256',ledgerKey).update(body).digest();check(timingSafeEqual(signature,Buffer.from(saved.signature,'hex'))&&saved.payload.schema==='retention-ledger-v1'&&uuid(tenantId)&&saved.payload.tenantId===tenantId&&Number.isSafeInteger(notBefore)&&Number.isSafeInteger(saved.payload.exportedAt)&&saved.payload.exportedAt>=notBefore&&saved.payload.exportedAt<=clock()+60000&&Array.isArray(saved.payload.events));
 const ids=new Set();for(const e of saved.payload.events){check(uuid(e.id)&&!ids.has(e.id));ids.add(e.id);source({connectionId:e.connection_id,entityType:e.entity_type,externalId:e.external_id,requestId:e.id,confirmed:true});}
 return saved;
}
/** Canonical database boundary derives tenant/user; callers never supply authority in JSON. */
export function createRecoveryRepository({database,storage,ledgerKey,clock=Date.now}={}){
 check(typeof database?.transaction==='function');
 const transaction=(action,fn)=>database.transaction(action,async s=>{check(s.role==='owner');return fn(s);});
 return Object.freeze({
  async policy({expectedVersion,backupTtlSeconds,activeErasure='immediate',businessHistory='retain-authorized-audit'}){
   check(Number.isInteger(expectedVersion)&&expectedVersion>=0&&Number.isInteger(backupTtlSeconds)&&backupTtlSeconds>0&&backupTtlSeconds<=31536000&&activeErasure==='immediate'&&businessHistory==='retain-authorized-audit');
   return transaction('retain',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':retention-policy']);const old=(await s.query('SELECT version FROM public.retention_policies WHERE tenant_id=$1',[s.tenantId])).rows[0];check((old?.version??0)===expectedVersion);const r=await s.query("INSERT INTO public.retention_policies(tenant_id,version,backup_ttl_seconds,active_erasure,business_history,actor_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id) DO UPDATE SET version=excluded.version,backup_ttl_seconds=excluded.backup_ttl_seconds,active_erasure=excluded.active_erasure,business_history=excluded.business_history,actor_id=excluded.actor_id,updated_at=clock_timestamp() RETURNING version,backup_ttl_seconds",[s.tenantId,expectedVersion+1,backupTtlSeconds,activeErasure,businessHistory,s.userId]);return r.rows[0];});
  },
  async preview(input){const p=source(input);return transaction('read',async s=>{const c=(await s.query('SELECT id FROM public.connections WHERE tenant_id=$1 AND id=$2',[s.tenantId,p.connectionId])).rows[0];check(c);return {source:p,policy:(await s.query('SELECT version,backup_ttl_seconds,active_erasure,business_history FROM public.retention_policies WHERE tenant_id=$1',[s.tenantId])).rows[0]??null,scope:'source_and_descendants',collateral:'whole_containing_raw_uploads',businessHistory:'retained_authorized_audit',externalCopies:'not_verified'};});},
  async erase(input){const p=source(input);check(uuid(p.requestId)&&p.confirmed===true);return transaction('retain',async s=>(await s.query('SELECT public.retention_erase($1::jsonb) AS result',[JSON.stringify(p)])).rows[0].result);},
  async registerArtifact(input){check(strict(input,['connectionId','entityType','sourceKey','class','objectPath','expiresAt'])&&uuid(input.connectionId)&&['message','conversation','customer'].includes(input.entityType)&&typeof input.sourceKey==='string'&&input.sourceKey.length>0&&['raw','cache','export','backup'].includes(input.class)&&typeof input.objectPath==='string'&&Number.isSafeInteger(input.expiresAt));const p=structuredClone(input);return transaction('retain',async s=>{check(p.objectPath.startsWith(s.tenantId+'/')&&!p.objectPath.split('/').includes('..')&&!/[\\\u0000-\u001f]/.test(p.objectPath));await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':'+p.connectionId]);const policy=(await s.query('SELECT backup_ttl_seconds FROM public.retention_policies WHERE tenant_id=$1',[s.tenantId])).rows[0];check(policy&&p.expiresAt>clock()&&p.expiresAt<=clock()+policy.backup_ttl_seconds*1000);const blocked=(await s.query('SELECT public.retention_source_deleted($1,$2,$3,$4) AS deleted',[s.tenantId,p.connectionId,p.entityType,p.sourceKey])).rows[0]?.deleted;const r=await s.query("INSERT INTO public.retention_artifacts(tenant_id,connection_id,entity_type,source_key,class,object_path,expires_at,status) VALUES($1,$2,$3,$4,$5,$6,to_timestamp($7::double precision/1000),$8) RETURNING id,status",[s.tenantId,p.connectionId,p.entityType,p.sourceKey,p.class,p.objectPath,p.expiresAt,blocked&&p.class!=='backup'?'pending':'active']);return r.rows[0];});},
  async purgeArtifacts({limit}={}){check(limit===undefined||Number.isInteger(limit)&&limit>=1&&limit<=25);check(typeof storage?.remove==='function'&&typeof storage?.exists==='function');const targets=await transaction('retain',async s=>(await s.query(limit===undefined?"UPDATE public.retention_artifacts SET status='pending' WHERE tenant_id=$1 AND status<>'deleted' AND (status='pending' OR expires_at<=clock_timestamp()) RETURNING id,tenant_id,object_path":"WITH picked AS (SELECT id FROM public.retention_artifacts WHERE tenant_id=$1 AND status<>'deleted' AND (status='pending' OR expires_at<=clock_timestamp()) ORDER BY id LIMIT $2 FOR UPDATE SKIP LOCKED) UPDATE public.retention_artifacts a SET status='pending' FROM picked p WHERE a.tenant_id=$1 AND a.id=p.id RETURNING a.id,a.tenant_id,a.object_path",limit===undefined?[s.tenantId]:[s.tenantId,limit])).rows);const receipts=[];for(const target of targets){try{await storage.remove(target.object_path);if(await storage.exists(target.object_path))throw Error('NOT_DELETED');await transaction('retain',s=>s.query("UPDATE public.retention_artifacts SET status='deleted',deleted_at=clock_timestamp() WHERE tenant_id=$1 AND id=$2 AND status='pending'",[s.tenantId,target.id]));receipts.push({id:target.id,status:'deleted'});}catch{receipts.push({id:target.id,status:'pending'});}}const remaining=await transaction('retain',async s=>Number((await s.query("SELECT count(*) AS n FROM public.retention_artifacts WHERE tenant_id=$1 AND status<>'deleted' AND (status='pending' OR expires_at<=clock_timestamp())",[s.tenantId])).rows[0].n));return {complete:remaining===0&&receipts.every(x=>x.status==='deleted'),remaining,receipts,externalCopies:'not_verified'};},
  async exportLedger(){validateKey(ledgerKey);return transaction('read',async s=>{const events=(await s.query('SELECT id,connection_id,entity_type,external_id,created_at FROM public.retention_ledger WHERE tenant_id=$1 ORDER BY created_at,id',[s.tenantId])).rows;const payload={schema:'retention-ledger-v1',tenantId:s.tenantId,exportedAt:clock(),events};const body=JSON.stringify(payload);return {payload,sha256:digest(body),signature:createHmac('sha256',ledgerKey).update(body).digest('hex')};});},
  async reapplyLedger(document,{expectedHash,notBefore}={}){
   const saved=verifyRecoveryLedger(document,{ledgerKey,expectedHash,notBefore,tenantId:document?.payload?.tenantId,clock});
   return transaction('retain',async s=>{check(saved.payload.tenantId===s.tenantId);const results=[];for(const e of saved.payload.events){check(uuid(e.id));const p=source({connectionId:e.connection_id,entityType:e.entity_type,externalId:e.external_id,requestId:e.id,confirmed:true});results.push((await s.query('SELECT public.retention_erase($1::jsonb) AS result',[JSON.stringify(p)])).rows[0].result);}return {reapplied:results.length,ledgerHash:expectedHash,state:'storage_reconciliation_required'};});
  },
 });
}
