import {createHmac,timingSafeEqual,randomUUID} from 'node:crypto';
import {createRecoveryRepository,digest} from './index.mjs';
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
class WebError extends Error{constructor(code,status){super(code);this.code=code;this.status=status;}}
const check=(ok,code='retention_input_invalid',status=400)=>{if(!ok)throw new WebError(code,status);};
const strict=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k));
const target=p=>{check(strict(p,['connectionId','entityType','externalId'])&&uuid(p.connectionId)&&['message','conversation','customer'].includes(p.entityType)&&typeof p.externalId==='string'&&p.externalId.length>0&&p.externalId.length<=512);return p;};
export function createRecoveryWeb({database,storage,ledgerKey,clock=Date.now}){
 const ready=typeof ledgerKey==='string'&&Buffer.byteLength(ledgerKey)>=32;
 const db={transaction:async(action,work)=>{let own;try{return await database.transaction(action,async s=>{try{check(s.role==='owner','role_insufficient',403);return await work(s);}catch(e){if(e instanceof WebError)own=e;else if(e.code==='P0002')own=new WebError('retention_source_not_found',404);else if(e.code==='54000')own=new WebError('retention_scope_limit',413);throw e;}});}catch(e){throw own??e;}}};
 const repo=createRecoveryRepository({database:db,storage,ledgerKey,clock}),scoped=s=>createRecoveryRepository({database:{transaction:async(_,work)=>work(s)},storage,ledgerKey,clock});
 const sign=payload=>{const body=Buffer.from(JSON.stringify(payload)).toString('base64url');return body+'.'+createHmac('sha256',ledgerKey).update('retention-preview-v1:'+body).digest('hex');};
 function decode(token){check(ready,'retention_configuration_required',503);check(typeof token==='string'&&token.length<8192);const [body,sig,...rest]=token.split('.');check(rest.length===0&&/^[a-f0-9]{64}$/.test(sig??''));const expected=createHmac('sha256',ledgerKey).update('retention-preview-v1:'+body).digest();check(timingSafeEqual(expected,Buffer.from(sig,'hex')),'retention_preview_invalid',409);let p;try{p=JSON.parse(Buffer.from(body,'base64url').toString());}catch{check(false);}return p;}
 const scope=async(s,p)=>{check(!(await s.query('SELECT public.retention_source_deleted($1,$2,$3,$4) AS deleted',[s.tenantId,p.connectionId,p.entityType,p.externalId])).rows[0].deleted,'retention_source_already_erased',409);const data=(await s.query('SELECT public.retention_web_scope($1::jsonb) AS scope',[JSON.stringify(p)])).rows[0].scope;check(data.policy,'retention_policy_required',409);return data;};
 return {
 async state(){return db.transaction('read',async s=>({ready,policy:(await s.query('SELECT version,backup_ttl_seconds AS "backupTtlSeconds" FROM public.retention_policies WHERE tenant_id=$1',[s.tenantId])).rows[0]??null,connections:(await s.query('SELECT id,source,account_id AS "accountId" FROM public.connections WHERE tenant_id=$1 ORDER BY id',[s.tenantId])).rows,artifacts:(await s.query('SELECT id,class,object_path AS path,status,expires_at AS "expiresAt" FROM public.retention_artifacts WHERE tenant_id=$1 ORDER BY status,id LIMIT 25',[s.tenantId])).rows,counts:(await s.query("SELECT count(*) FILTER(WHERE status='deleted')::integer AS deleted,count(*) FILTER(WHERE status<>'deleted' AND (status='pending' OR expires_at<=clock_timestamp()))::integer AS pending FROM public.retention_artifacts WHERE tenant_id=$1",[s.tenantId])).rows[0]}));},
 async sources({connectionId,entityType,cursor=null}){check(uuid(connectionId)&&['message','conversation','customer'].includes(entityType)&&(cursor===null||uuid(cursor)));return db.transaction('read',async s=>{check((await s.query('SELECT id FROM public.connections WHERE tenant_id=$1 AND id=$2',[s.tenantId,connectionId])).rows.length,'retention_source_not_found',404);if(cursor)check((await s.query('SELECT id FROM public.source_heads WHERE tenant_id=$1 AND connection_id=$2 AND entity_type=$3 AND id=$4',[s.tenantId,connectionId,entityType,cursor])).rows.length);const rows=(await s.query('SELECT id,external_id AS "externalId",state FROM public.source_heads WHERE tenant_id=$1 AND connection_id=$2 AND entity_type=$3 AND public.retention_source_deleted(tenant_id,connection_id,entity_type,external_id) IS NOT TRUE AND ($4::uuid IS NULL OR id>$4) ORDER BY id LIMIT 26',[s.tenantId,connectionId,entityType,cursor])).rows;return{items:rows.slice(0,25),nextCursor:rows.length>25?rows[24].id:null};});},
 async policy(input){check(strict(input,['expectedVersion','backupTtlSeconds'])&&Number.isInteger(input.expectedVersion)&&input.expectedVersion>=0&&Number.isInteger(input.backupTtlSeconds)&&input.backupTtlSeconds>=1&&input.backupTtlSeconds<=31536000);return db.transaction('retain',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':retention-policy']);const old=(await s.query('SELECT version FROM public.retention_policies WHERE tenant_id=$1',[s.tenantId])).rows[0];check((old?.version??0)===input.expectedVersion,'retention_policy_conflict',409);return scoped(s).policy(input);});},
 async preview(input){const p=target(input);check(ready,'retention_configuration_required',503);return db.transaction('retain',async s=>{const plan=await scope(s,p),requestId=randomUUID();await s.query('SAVEPOINT retention_preview');let simulated;try{simulated=await scoped(s).erase({...p,requestId,confirmed:true});}finally{await s.query('ROLLBACK TO SAVEPOINT retention_preview');await s.query('RELEASE SAVEPOINT retention_preview');}check(simulated.messages===plan.messages.length&&simulated.vectors===plan.vectors.length,'retention_scope_changed',409);const payload={tenantId:s.tenantId,userId:s.userId,target:p,scopeHash:digest(plan),requestId,expiresAt:clock()+300000};return{target:p,scope:plan,requestId,expiresAt:payload.expiresAt,token:sign(payload),wholeRawFiles:true,externalCopies:'not_verified',businessHistory:'retained_authorized_audit'};});},
 async erase(input){check(strict(input,['token','requestId','confirmed'])&&uuid(input.requestId)&&input.confirmed===true);const payload=decode(input.token);return db.transaction('retain',async s=>{check(payload.tenantId===s.tenantId&&payload.userId===s.userId&&payload.requestId===input.requestId,'retention_preview_invalid',409);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':retention-request:'+input.requestId]);const prior=(await s.query('SELECT actor_id,token_hash,result FROM public.retention_web_requests WHERE tenant_id=$1 AND request_id=$2',[s.tenantId,input.requestId])).rows[0];if(prior){check(prior.actor_id===s.userId&&prior.token_hash===digest(input.token),'retention_request_conflict',409);return prior.result;}
 check(Number.isSafeInteger(payload.expiresAt)&&payload.expiresAt>clock(),'retention_preview_expired',409);const plan=await scope(s,target(payload.target));check(digest(plan)===payload.scopeHash,'retention_scope_changed',409);const result=await scoped(s).erase({...payload.target,requestId:input.requestId,confirmed:true});check(result.messages===plan.messages.length&&result.vectors===plan.vectors.length,'retention_scope_changed',409);const redactions=(await s.query('SELECT public.retention_web_redactions($1) AS rows',[input.requestId])).rows[0].rows;check(digest(redactions.map(x=>[x.table,x.id,x.hash]))===digest(plan.derived.map(x=>[x.table,x.id,x.hash])),'retention_scope_changed',409);
 await s.query('INSERT INTO public.retention_web_requests(tenant_id,request_id,actor_id,token_hash,result) VALUES($1,$2,$3,$4,$5)',[s.tenantId,input.requestId,s.userId,digest(input.token),JSON.stringify(result)]);return result;});},
 async purge(){return repo.purgeArtifacts({limit:25});},
 async exportLedger(){check(ready,'retention_configuration_required',503);return repo.exportLedger();}
 };
}
