import {isDeepStrictEqual} from 'node:util';
export const windowSpec={from:'2026-01-01T00:00:00.000Z',to:'2026-09-01T00:00:00.000Z',overlapSeconds:60,version:'SYN-window-v1'};
export function record(ingestion,actor,id,{type='message',role='customer',conversation='T1',text='SYNTHETIC body',deleted=false,revision='r1'}={}){
 const context={tenant_id:actor.tenant,connection_id:actor.connection,source:actor.source,source_account_id:actor.account};
 const payload=type==='ticket'?{id,status:deleted?'deleted':'open',created_at:'2026-02-01T00:00:00.000Z',updated_at:'2026-02-02T00:00:00.000Z'}:{comment:{id,body:text,public:role!=='internal',created_at:'2026-02-01T01:00:00.000Z'},author_role:{user_id:'SYN-user',provider_role:role==='customer'?'end-user':role==='agent'?'agent':null}};
 return {envelope:ingestion.createEnvelope(context,{entity_type:type,external_id:id,source_revision:revision,occurred_at:'2026-02-01T01:00:00.000Z',observed_at:'2026-09-01T00:00:00.000Z',deleted_at:deleted?'2026-09-01T00:00:00.000Z':null,payload_ref:'source:SYNTHETIC'},payload),payload,provider_updated_at:'2026-02-02T00:00:00.000Z',role,type,text:type==='message'?text:null,visibility:role==='internal'?'internal':'public',body_complete:type==='message',conversation_id:type==='ticket'?id:conversation,deleted,tombstone:deleted,customer_id:null,sku:null,order_id:null,associations:[]};
}
export function page(records,cursor,{done=false,errors=[]}={}){return {records,errors,checkpoint:{version:1,scope:'SYN-opaque-scope',cursor},done,adapter_version:'vexa-zendesk-v2',coverage:{objects_read:records.length+errors.length,accepted:records.length,rejected:errors.length,messages_complete:errors.length===0,live_verified:false}};}
export function adapter(pages,{failAfter,visits=[]}={}){return {async *pages({checkpoint=null}={}){let i=checkpoint===null?0:pages.findIndex(p=>isDeepStrictEqual(p.checkpoint,checkpoint))+1;if(i===0&&checkpoint!==null)throw Error('SYN_CHECKPOINT_UNKNOWN');for(;i<pages.length;i++){visits.push(i);if(i===failAfter)throw Object.assign(Error('RATE_LIMITED'),{code:'RATE_LIMITED',retryAfter:1});yield pages[i];}}};}
