begin;
create table public.candidate_results(tenant_id uuid not null references public.organizations(id),id uuid not null,actor_id uuid not null,candidate_id text not null,config_hash text not null check(config_hash~'^[a-f0-9]{64}$'),envelope jsonb not null check(octet_length(envelope::text)<=16384),created_at timestamptz not null default clock_timestamp(),primary key(tenant_id,id),foreign key(tenant_id,actor_id) references public.memberships(tenant_id,user_id));
create table public.candidate_selections(tenant_id uuid not null references public.organizations(id),version integer not null check(version>0),actor_id uuid not null,candidate_id text,config_hash text not null check(config_hash~'^[a-f0-9]{64}$'),base_hash text not null check(base_hash~'^[a-f0-9]{64}$'),result_id uuid,operation text not null check(operation in('select','rollback')),target_version integer,reason text not null check(reason in('validated_evaluation','incident_recovery','quality_regression')),evidence_hash text not null check(evidence_hash~'^[a-f0-9]{64}$'),created_at timestamptz not null default clock_timestamp(),primary key(tenant_id,version),foreign key(tenant_id,actor_id) references public.memberships(tenant_id,user_id),foreign key(tenant_id,result_id) references public.candidate_results(tenant_id,id),check((candidate_id is null)=(result_id is null)));
create function public.candidate_guard() returns trigger language plpgsql security definer set search_path='' as $$declare latest integer;r public.candidate_results;target public.candidate_selections;begin
if TG_OP<>'INSERT' or current_setting('vexa.action',true) is distinct from 'configure' or NEW.tenant_id is distinct from nullif(current_setting('vexa.tenant_id',true),'')::uuid or NEW.actor_id is distinct from auth.uid() or public.vexa_member(NEW.tenant_id,array['owner']) is not true then raise insufficient_privilege;end if;
if TG_TABLE_NAME='candidate_results' then if NEW.candidate_id is distinct from NEW.envelope->'payload'->>'candidateId' or NEW.config_hash is distinct from NEW.envelope->'payload'->>'configHash' or NEW.tenant_id::text is distinct from NEW.envelope->'payload'->>'tenantId' then raise check_violation;end if;return NEW;end if;
perform pg_advisory_xact_lock(hashtextextended(NEW.tenant_id::text||':candidate-selection',0));select coalesce(max(version),0) into latest from public.candidate_selections where tenant_id=NEW.tenant_id;if NEW.version<>latest+1 then raise serialization_failure;end if;
if NEW.result_id is not null then select * into r from public.candidate_results where tenant_id=NEW.tenant_id and id=NEW.result_id;if r.id is null or r.candidate_id is distinct from NEW.candidate_id or r.config_hash is distinct from NEW.config_hash then raise check_violation;end if;end if;
if NEW.operation='select' and (NEW.result_id is null or NEW.target_version is not null) then raise check_violation;end if;
if latest>0 and NEW.base_hash is distinct from (select base_hash from public.candidate_selections where tenant_id=NEW.tenant_id and version=1) then raise check_violation;end if;
if NEW.operation='rollback' then
if NEW.target_version is null or NEW.target_version<0 or NEW.target_version>=NEW.version-1 then raise check_violation;end if;
if NEW.target_version=0 then if NEW.candidate_id is not null or NEW.config_hash is distinct from NEW.base_hash then raise check_violation;end if;
else select * into target from public.candidate_selections where tenant_id=NEW.tenant_id and version=NEW.target_version;if target.version is null or target.candidate_id is distinct from NEW.candidate_id or target.config_hash is distinct from NEW.config_hash or target.result_id is distinct from NEW.result_id then raise check_violation;end if;end if;end if;return NEW;end $$;
revoke all on function public.candidate_guard() from public,anon,authenticated,service_role,vexa_backend;
do $$declare n text;begin foreach n in array array['candidate_results','candidate_selections'] loop execute format('alter table public.%I enable row level security',n);execute format('alter table public.%I force row level security',n);execute format('revoke all on public.%I from public,anon,authenticated,service_role,vexa_backend',n);execute format('grant select,insert on public.%I to vexa_backend',n);execute format('create policy candidate_owner_read on public.%I for select to vexa_backend using(tenant_id=nullif(current_setting(''vexa.tenant_id'',true),'''')::uuid and public.vexa_member(tenant_id,array[''owner'']))',n);execute format('create policy candidate_owner_write on public.%I for insert to vexa_backend with check(public.vexa_backend_action(tenant_id,array[''configure'']) and public.vexa_member(tenant_id,array[''owner'']))',n);execute format('create trigger candidate_immutable before insert or update or delete on public.%I for each row execute function public.candidate_guard()',n);end loop;end $$;
create function public.candidate_active_config(t uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;begin
if t is distinct from nullif(current_setting('vexa.tenant_id',true),'')::uuid or public.vexa_member(t,array['owner','analyst']) is not true then raise insufficient_privilege;end if;
select jsonb_build_object('version',s.version,'candidateId',s.candidate_id,'configHash',s.config_hash,'envelope',r.envelope) into result from public.candidate_selections s left join public.candidate_results r on r.tenant_id=s.tenant_id and r.id=s.result_id where s.tenant_id=t order by s.version desc limit 1;return result;end $$;
revoke all on function public.candidate_active_config(uuid) from public,anon,authenticated,service_role;grant execute on function public.candidate_active_config(uuid) to vexa_backend;
commit;
