import {createHash} from 'node:crypto';
import {createWorkspaceService} from './index.mjs';
import {parseWorkspaceQuery,WorkspaceError,check,uuid,canonical,hash} from './contracts.mjs';
import {createSnapshotRepository} from '../metrics/snapshots.mjs';
import {EconomicError} from '../metrics/repository.mjs';
import {createEvidenceRepository} from '../intelligence/evidence-repository.mjs';
import {createCausalityRepository} from '../problems/causality.mjs';
import {DomainError} from '../problems/contracts.mjs';
import {identityKey} from '../ingestion/index.mjs';
import {detailId,financialEvent,projectDetailGraph} from './detail-graph.mjs';
const one=async(s,q,a=[])=>(await s.query(q,a)).rows[0],iso=x=>new Date(x).toISOString(),uniq=x=>[...new Set(x)].sort(),scoped=s=>({transaction:async(_a,fn)=>fn(s)});
const TYPES=['problem','customer','component','event','evidence'];
const TABLES=['economic_source_versions','economic_ledger_entries','economic_problem_links','economic_order_aliases','economic_order_customers','economic_relation_coverage'];
function requestInput({kind,id,query}){check(TYPES.includes(kind)&&uuid(id),'detail_id_invalid',404);check(query instanceof URLSearchParams,'detail_query_invalid');const shared=new URLSearchParams(query),extras={};for(const key of ['root_kind','root_id','component_id','event_id','detail_hash']){check(shared.getAll(key).length<=1,'duplicate_filter');extras[key]=shared.get(key);shared.delete(key);}check(!shared.has('resource')&&!shared.has('format')&&!shared.has('cursor')&&!shared.has('limit'),'unsupported_filter');const parsed=parseWorkspaceQuery(shared);check(parsed.scope.snapshot_id&&parsed.scope.scope_hash,'detail_scope_required');const rootKind=['problem','customer'].includes(kind)?kind:extras.root_kind,rootId=['problem','customer'].includes(kind)?id:extras.root_id;check(['problem','customer'].includes(rootKind)&&uuid(rootId),'detail_root_required');check(!extras.detail_hash||/^[a-f0-9]{64}$/.test(extras.detail_hash),'detail_hash_invalid');if(!['problem','customer'].includes(kind))check(extras.detail_hash,'detail_hash_required');if(['event','evidence'].includes(kind))check(uuid(extras.component_id),'component_required');if(kind==='evidence')check(uuid(extras.event_id),'event_required');shared.set('resource',rootKind==='problem'?'problems':'metrics');return {kind,id,query:shared,rootKind,rootId,...extras};}
async function sourceCustomer(s,customerId,revisionId=null){let row;if(revisionId)row=await one(s,"SELECT r.*,n.status AS connection_status,n.account_id FROM public.source_revisions r JOIN public.connections n ON n.tenant_id=r.tenant_id AND n.id=r.connection_id WHERE r.tenant_id=$1 AND r.canonical_id=$2 AND r.id=$3 AND r.entity_type='customer'",[s.tenantId,customerId,revisionId]);else row=await one(s,"SELECT r.*,n.status AS connection_status,n.account_id FROM public.source_heads h JOIN public.source_revisions r ON r.tenant_id=h.tenant_id AND r.id=h.selected_revision_id JOIN public.connections n ON n.tenant_id=r.tenant_id AND n.id=r.connection_id WHERE h.tenant_id=$1 AND h.id=$2 AND h.state IN('unique','selected') AND r.entity_type='customer'",[s.tenantId,customerId]);if(!row||row.connection_status!=='active')return null;if((await one(s,'SELECT public.retention_source_deleted($1,$2,$3,$4) AS deleted',[s.tenantId,row.connection_id,'customer',row.external_id]))?.deleted)return null;const key=identityKey({tenant_id:s.tenantId,connection_id:row.connection_id,source:row.provenance.source,source_account_id:row.account_id,entity_type:'customer',external_id:row.external_id});if(await one(s,'SELECT id FROM public.tombstones WHERE tenant_id=$1 AND (connection_id IS NULL OR connection_id=$2) AND deleted_source_key=ANY($3::text[]) LIMIT 1',[s.tenantId,row.connection_id,[customerId,row.id,row.external_id,key,createHash('sha256').update(key).digest('hex')]]))return null;const snap=row.snapshot.find(x=>x.table==='customers'&&x.row.id===customerId)?.row;check(snap,'customer_source_invalid',403);return {row,label:snap.display_name??snap.external_id,source:row.provenance.source};}
async function financialRows(s,row,binding){const result={exposureInputHash:row.input_manifest.exposureInputHash};for(const table of TABLES){const ids=row.input_manifest.refs.filter(r=>r.table===table&&r.authorized&&r.active).map(r=>r.id);result[table]=ids.length?(await s.query(`SELECT * FROM public.${table} WHERE tenant_id=$1 AND id=ANY($2::uuid[])`,[s.tenantId,ids])).rows:[];check(result[table].length===ids.length,'detail_captured_reference_unavailable',403);}result.dimensionMappings=binding.mapping_ids.length?(await s.query('SELECT * FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,binding.mapping_ids])).rows:[];return result;}
async function context(s,workspace){const snapshot=await createSnapshotRepository({database:scoped(s)}).get({snapshotId:workspace.meta.snapshot_id});const base=await one(s,'SELECT * FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,snapshot.id]);const binding=await one(s,'SELECT * FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,workspace.meta.scope_hash]);check(binding&&binding.base_snapshot_id===snapshot.id,'detail_scope_conflict',409);return {snapshot,base,binding,rows:await financialRows(s,base,binding)};}
async function prepareReceipt(s,ctx){await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-customer-identities']);const keys=uniq(ctx.rows.economic_order_customers.map(r=>r.customer_key).filter(Boolean));const ids=keys.length?(await s.query('SELECT DISTINCT ON(customer_key) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_customer_identity_versions WHERE tenant_id=$1 AND customer_key=ANY($2::text[]) ORDER BY customer_key,version DESC',[s.tenantId,keys])).rows:[];const identityIds=ids.filter(r=>r.active&&r.actor_active).map(r=>r.id).sort(),conversationRefs=[];
 for(const model of ctx.base.input_manifest.models){const run=await one(s,'SELECT conversation_id,created_at FROM public.extraction_runs WHERE tenant_id=$1 AND id=$2',[s.tenantId,model.id]);check(run,'detail_run_unavailable',403);const revisions=(await s.query("SELECT id FROM public.source_revisions WHERE tenant_id=$1 AND canonical_id=$2 AND entity_type='conversation' AND created_at<=$3 ORDER BY id",[s.tenantId,run.conversation_id,run.created_at])).rows;conversationRefs.push({runId:model.id,conversationId:run.conversation_id,sourceRevisionIds:revisions.map(r=>r.id)});}
 conversationRefs.sort((a,b)=>a.runId.localeCompare(b.runId));const body={workspaceBindingId:ctx.binding.id,baseSnapshotId:ctx.snapshot.id,scopeHash:ctx.binding.scope_hash,identityIds,conversationRefs,version:'workspace-detail-v1'};return {body,detailHash:hash(body)};}
async function readReceipt(s,ctx,detailHash){const receipt=await one(s,'SELECT * FROM public.workspace_detail_bindings WHERE tenant_id=$1 AND detail_hash=$2',[s.tenantId,detailHash]);check(receipt,'detail_not_found',404);check(receipt.workspace_binding_id===ctx.binding.id&&receipt.base_snapshot_id===ctx.snapshot.id&&receipt.scope_hash===ctx.binding.scope_hash,'detail_scope_conflict',409);check(hash({workspaceBindingId:receipt.workspace_binding_id,baseSnapshotId:receipt.base_snapshot_id,scopeHash:receipt.scope_hash,identityIds:receipt.identity_ids,conversationRefs:receipt.conversation_refs,version:'workspace-detail-v1'})===receipt.detail_hash,'detail_integrity_failed',409);
 const identities=receipt.identity_ids.length?(await s.query('SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_customer_identity_versions WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,receipt.identity_ids])).rows:[];check(identities.length===receipt.identity_ids.length,'customer_identity_unavailable',403);for(const row of identities){const current=await one(s,'SELECT active,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_customer_identity_versions WHERE tenant_id=$1 AND customer_key=$2 ORDER BY version DESC LIMIT 1',[s.tenantId,row.customer_key]);check(row.actor_active&&current?.active&&current.actor_active,'customer_identity_withdrawn',403);const customer=await sourceCustomer(s,row.customer_id,row.customer_revision_id);check(customer,'customer_source_unavailable',403);row.label=customer.label;row.source=customer.source;}
 return {receipt,identities};}
async function conversations(s,ctx,receipt,rootKind,rootId){let allowedRuns=new Set(ctx.base.input_manifest.models.map(r=>r.id));if(rootKind==='problem'){const pinned=ctx.binding.problem_versions.find(p=>p.problemId===rootId);check(pinned?.versionId,'problem_not_found',404);const v=await one(s,'SELECT provenance FROM public.problem_versions WHERE tenant_id=$1 AND id=$2 AND problem_id=$3',[s.tenantId,pinned.versionId,rootId]);check(v,'problem_not_found',404);const ids=v.provenance.snapshot.embeddingIds;const rows=(await s.query('SELECT extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1 AND embedding_id=ANY($2::uuid[])',[s.tenantId,ids])).rows;allowedRuns=new Set(rows.map(r=>r.extraction_run_id).filter(id=>allowedRuns.has(id)));}
 const out=new Map(),repo=createEvidenceRepository({database:scoped(s)});for(const ref of receipt.conversation_refs){if(!allowedRuns.has(ref.runId))continue;let run;try{run=await repo.get(ref.runId);}catch(e){if(e.message==='EVIDENCE_UNAVAILABLE')throw new WorkspaceError('detail_evidence_unavailable',403);throw e;}
 const revisions=ref.sourceRevisionIds.length?(await s.query('SELECT * FROM public.source_revisions WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,ref.sourceRevisionIds])).rows:[];check(revisions.length===ref.sourceRevisionIds.length&&revisions.every(r=>r.canonical_id===run.conversationId&&r.entity_type==='conversation'),'conversation_identity_unavailable',403);
 const customerIds=uniq(revisions.map(r=>r.related_customer_id).filter(Boolean)),customerId=revisions.length>0&&customerIds.length===1&&revisions.every(r=>r.related_customer_id===customerIds[0])?customerIds[0]:null;
 const row=revisions[0];const prior=out.get(run.conversationId)??{id:run.conversationId,source:row?.provenance.source??'unknown',label:row?.external_id??'Conversación sin identidad resuelta',state:run.state,customer_id:customerId,evidenceRunIds:[],citations:[]};prior.evidenceRunIds.push(run.runId);prior.citations.push(...run.issues.flatMap(issue=>issue.evidence).map(span=>({message_revision_id:span.message_revision_id,quote:span.quote,quote_hash:span.quote_hash,role:span.role})));if(prior.customer_id!==customerId)prior.customer_id=null;out.set(run.conversationId,prior);}
 return [...out.values()].filter(c=>rootKind!=='customer'||c.customer_id===rootId).map(c=>({...c,evidenceRunIds:uniq(c.evidenceRunIds),citations:[...new Map(c.citations.map(x=>[x.message_revision_id+':'+x.quote_hash,x])).values()]})).sort((a,b)=>a.id.localeCompare(b.id));}
const label={exposure:'Ingresos expuestos',allOrders:'Órdenes registradas',refunds:'Reembolsos liquidados',replacement:'Reposiciones observadas',supportModel:'Soporte modelado'};
function summaries(graph,ctx,rootKind,rootId,detailHash,record){return Object.entries(graph.metrics).map(([key,m])=>{let money={label:label[key],kind:key,amount_minor:m.amountMinor,known_subtotal:m.knownSubtotalMinor??null,currency:m.currency,exponent:m.exponent,source_ref:'detail:'+detailHash,status:m.status,coverage:{known_n:m.knownCount??0,eligible_n:m.totalCount??0},missing_reasons:m.missingReasons??[]};if(rootKind==='problem'&&key==='exposure')money={...record.metrics.find(x=>x.kind==='exposure')};return {id:detailId({detailHash,rootKind,rootId,metric:key}),metric:key,label:label[key],money,event_count:graph.eventRows[key].length,missing_reasons:money.missing_reasons};});}
export function createDetailService({database}){
 const tx=async(action,fn)=>{let own;try{return await database.transaction(action,async s=>{try{return await fn(s);}catch(e){if(e instanceof WorkspaceError||e instanceof EconomicError||e instanceof DomainError)own=e;throw e;}});}catch(e){if(own)throw own;throw e;}};
 return {
 async get(input){const request=requestInput(input),workspace=await createWorkspaceService({database}).query(request.query,{all:true});check(workspace.meta.snapshot_id,'snapshot_not_found',404);let detailHash=request.detail_hash;if(!detailHash){const prepared=await tx('read',async s=>{const ctx=await context(s,workspace);if(request.rootKind==='problem')check(workspace.items.some(r=>r.id===request.rootId),'problem_not_found',404);return prepareReceipt(s,ctx);});detailHash=prepared.detailHash;await tx('materialize',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-customer-identities']);const found=await one(s,'SELECT id FROM public.workspace_detail_bindings WHERE tenant_id=$1 AND detail_hash=$2',[s.tenantId,detailHash]);if(!found)await s.query('INSERT INTO public.workspace_detail_bindings(tenant_id,workspace_binding_id,base_snapshot_id,scope_hash,detail_hash,identity_ids,conversation_refs,canonical_input,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[s.tenantId,prepared.body.workspaceBindingId,prepared.body.baseSnapshotId,prepared.body.scopeHash,detailHash,prepared.body.identityIds,JSON.stringify(prepared.body.conversationRefs),canonical(prepared.body),s.userId]);});}
 return tx('read',async s=>{const ctx=await context(s,workspace),{receipt,identities}=await readReceipt(s,ctx,detailHash);let record=null;if(request.rootKind==='problem'){record=workspace.items.find(r=>r.id===request.rootId);check(record,'problem_not_found',404);}else check(identities.some(i=>i.customer_id===request.rootId),'customer_not_found',404);
 const graph=projectDetailGraph({tenantId:s.tenantId,snapshot:ctx.snapshot,binding:ctx.binding,rows:ctx.rows,identityLinks:identities,rootKind:request.rootKind,rootId:request.rootId}),components=summaries(graph,ctx,request.rootKind,request.rootId,detailHash,record);
 const shared={kind:request.kind,id:request.id,title:record?.title??identities.find(i=>i.customer_id===request.rootId)?.label??'Detalle financiero',snapshot_id:ctx.snapshot.id,scope_hash:ctx.binding.scope_hash,base_scope_hash:ctx.snapshot.scopeHash,detail_hash:detailHash,as_of:ctx.snapshot.asOf,detail_as_of:iso(receipt.created_at),state:workspace.meta.state,coverage:workspace.meta.coverage,scope:workspace.meta.scope};
 if(request.kind==='problem'){const customers=graph.customerKeys.map(key=>{const i=identities.find(i=>i.customer_key===key);return {customer_id:i?.customer_id??null,declaredKey:key,label:i?.label??key,identity:i?'approved_link':'unresolved'};});const ids=uniq(customers.map(c=>c.customer_id).filter(Boolean));let cause=null,reason=null;try{cause=await createCausalityRepository({database:scoped(s)}).get({problemId:request.rootId});}catch(e){if(e instanceof DomainError&&['source_unavailable','problem_not_found'].includes(e.message))reason='La evaluación causal actual no está disponible; las cifras mantienen el corte histórico.';else throw e;}return {...shared,kind:'problem',record,components,customers,conversations:await conversations(s,ctx,receipt,'problem',request.rootId),customer_id:ids.length===1&&customers.every(c=>c.customer_id!==null)?ids[0]:null,causality:{scope:'current_authorized',view:cause,unavailableReason:reason}};}
 if(request.kind==='customer')return {...shared,kind:'customer',customer:{id:request.rootId,label:shared.title,declaredKeys:identities.filter(i=>i.customer_id===request.rootId).map(i=>i.customer_key)},customer_id:request.rootId,orders:graph.orders.map(r=>({...financialEvent(r),customer_id:request.rootId})),conversations:await conversations(s,ctx,receipt,'customer',request.rootId),components};
 const componentId=request.kind==='component'?request.id:request.component_id,component=components.find(c=>c.id===componentId);check(component,'component_not_found',404);const events=graph.eventRows[component.metric];if(request.kind==='component')return {...shared,kind:'component',title:component.label,component,events:events.map(financialEvent)};
 const eventId=request.kind==='event'?request.id:request.event_id,event=events.find(e=>e.id===eventId);check(event,'event_not_found',404);if(request.kind==='event')return {...shared,kind:'event',title:event.external_id,event:financialEvent(event),evidence:[{id:event.id,kind:'financial_record',label:'Registro financiero aprobado y procedencia',eventId:event.id}]};
 check(request.id===event.id,'evidence_not_found',404);const source=ctx.rows.economic_source_versions.find(r=>r.source_id===event.source_id);check(source,'financial_source_unavailable',403);return {...shared,kind:'evidence',title:'Procedencia del registro '+event.external_id,evidence:{kind:'financial_record',id:event.id,event:financialEvent(event),record:{rowId:event.id,revision:event.revision,report:event.report,actorId:event.actor_id,recordedAt:iso(event.recorded_at)},source:{id:source.source_id,version:source.version,name:source.name,evidenceType:source.evidence_type,report:source.report,watermark:iso(source.watermark)},accountingAuthority:'approved_ledger_record',notice:'El importe procede del registro financiero aprobado. Las frases de conversaciones son contexto y no prueban un desembolso.'}};
 });},
 async customerBindings(){return tx('read',async s=>{const keys=(await s.query('SELECT DISTINCT customer_key FROM public.economic_order_customers WHERE tenant_id=$1 AND customer_key IS NOT NULL AND public.economic_contributor_active(tenant_id,actor_id) ORDER BY customer_key',[s.tenantId])).rows;const candidates=(await s.query('SELECT id FROM public.customers WHERE tenant_id=$1 ORDER BY id',[s.tenantId])).rows,customers=[];for(const c of candidates){const current=await sourceCustomer(s,c.id);if(current)customers.push({id:c.id,label:current.label,source:current.source});}const rows=(await s.query('SELECT DISTINCT ON(customer_key) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_customer_identity_versions WHERE tenant_id=$1 ORDER BY customer_key,version DESC',[s.tenantId])).rows;return {customers,declaredKeys:keys.map(k=>k.customer_key),bindings:rows.map(r=>({id:r.id,customerKey:r.customer_key,customerId:r.customer_id,version:r.version,active:r.active,valid:r.actor_active,report:r.actor_active?r.report:null,createdAt:iso(r.created_at)})),canWrite:s.role==='owner',notice:'Vínculo explícito con una identidad importada. Abre una nueva vista de identidad para aplicar el vínculo. Su corte de identidad es independiente del corte financiero; las vistas anteriores conservan sus referencias.'};});},
 async recordCustomerBinding(q){check(q&&typeof q==='object'&&!Array.isArray(q)&&Object.keys(q).every(k=>['customerKey','customerId','expectedVersion','active','report','attested'].includes(k))&&typeof q.customerKey==='string'&&q.customerKey.trim()===q.customerKey&&q.customerKey.length>0&&q.customerKey.length<=200&&!/[\u0000-\u001f\u007f]/.test(q.customerKey)&&uuid(q.customerId)&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&typeof q.active==='boolean'&&typeof q.report==='string'&&q.report.length>=20&&q.report.length<=4000&&q.attested===true,'customer_binding_invalid');return tx('configure',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-customer-identities']);const customer=await sourceCustomer(s,q.customerId);check(customer,'customer_not_found',404);const prior=await one(s,'SELECT max(version) AS version FROM public.workspace_customer_identity_versions WHERE tenant_id=$1 AND customer_key=$2',[s.tenantId,q.customerKey]);check((prior.version??0)===q.expectedVersion,'customer_binding_conflict',409);const row=await one(s,'INSERT INTO public.workspace_customer_identity_versions(tenant_id,customer_key,customer_id,customer_revision_id,version,actor_id,active,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) RETURNING *',[s.tenantId,q.customerKey,q.customerId,customer.row.id,q.expectedVersion+1,s.userId,q.active,q.report]);return {id:row.id,customerKey:row.customer_key,customerId:row.customer_id,version:row.version,active:row.active,valid:true,report:row.report,createdAt:iso(row.created_at)};});}
 };
}
