import type {WorkspaceScope} from './contracts.mjs';
import type {WorkspaceMetric,WorkspaceRecord} from './index.mjs';
import type {CauseView} from '../problems/causality.mjs';
export type DetailKind='problem'|'customer'|'component'|'event'|'evidence';
export type DetailContext={kind:DetailKind;id:string;query:URLSearchParams};
export type CustomerRef={customer_id:string|null;declaredKey:string;label:string;identity:'approved_link'|'unresolved'};
export type ConversationRef={id:string;source:string;label:string;state:'current'|'historical';customer_id:string|null;evidenceRunIds:string[];citations:{message_revision_id:string;quote:string;quote_hash:string;role:string}[]};
export type OrderSummary={id:string;entityId:string;externalId:string;amount_minor:string|null;currency:string;exponent:number;status:string;effectiveAt:string;customer_id:string|null};
export type ComponentSummary={id:string;metric:string;label:string;money:WorkspaceMetric;event_count:number;missing_reasons:string[]};
export type EventSummary={id:string;entityId:string;externalId:string;kind:string;amount_minor:string|null;currency:string;exponent:number;status:string;effectiveAt:string;orderId:string|null;reversalOf:string|null};
export type EvidenceRef={id:string;kind:'financial_record';label:string;eventId:string};
export type EvidenceDetail={kind:'financial_record';id:string;event:EventSummary;record:{rowId:string;revision:number;report:string;actorId:string;recordedAt:string};source:{id:string;version:number;name:string;evidenceType:string;report:string;watermark:string};accountingAuthority:'approved_ledger_record';notice:string};
export type DetailBase={kind:DetailKind;id:string;title:string;snapshot_id:string;scope_hash:string;base_scope_hash:string;detail_hash:string;as_of:string;detail_as_of:string;state:'empty'|'partial'|'stale'|'ready';coverage:string;scope:WorkspaceScope};
export type ProblemDetail=DetailBase & {kind:'problem';record:WorkspaceRecord;components:ComponentSummary[];customers:CustomerRef[];conversations:ConversationRef[];customer_id:string|null;causality:{scope:'current_authorized';view:CauseView|null;unavailableReason:string|null}};
export type CustomerDetail=DetailBase & {kind:'customer';customer:{id:string;label:string;declaredKeys:string[]};orders:OrderSummary[];conversations:ConversationRef[];components:ComponentSummary[];customer_id:string};
export type ComponentDetail=DetailBase & {kind:'component';component:ComponentSummary;events:EventSummary[]};
export type EventDetail=DetailBase & {kind:'event';event:EventSummary;evidence:EvidenceRef[]};
export type FinancialEvidenceDetail=DetailBase & {kind:'evidence';evidence:EvidenceDetail};
export type DetailView=ProblemDetail|CustomerDetail|ComponentDetail|EventDetail|FinancialEvidenceDetail;
export type CustomerBinding={id:string;customerKey:string;customerId:string;version:number;active:boolean;valid:boolean;report:string|null;createdAt:string};
export type CustomerBindingsView={customers:{id:string;label:string;source:string}[];declaredKeys:string[];bindings:CustomerBinding[];canWrite:boolean;notice:string};
export type CustomerBindingInput={customerKey:string;customerId:string;expectedVersion:number;active:boolean;report:string;attested:true};
export function createDetailService(options:{database:any}):{get(input:DetailContext):Promise<DetailView>;customerBindings():Promise<CustomerBindingsView>;recordCustomerBinding(input:CustomerBindingInput):Promise<CustomerBinding>};
