import {randomUUID} from 'node:crypto';
import {createSnapshotRepository} from '../metrics/snapshots.mjs';
import {createPriorityRepository} from '../metrics/priority.mjs';
import {adaptLedger} from '../economics/adapter.mjs';
import {EconomicError} from '../metrics/repository.mjs';
import {WorkspaceError,check,canonical,hash,uuid,parseWorkspaceQuery,canonicalScopeHash,cursorAuthHash,encodeCursor,decodeCursor} from './contracts.mjs';
const VERSION='workspace-projection-v1',one=async(s,q,a=[])=>(await s.query(q,a)).rows[0],iso=x=>new Date(x).toISOString();
const uniq=x=>[...new Set(x)].sort();
const scopedDb=s=>({transaction:async(_action,fn)=>fn(s)});
const filtersFor=(q,snapshot)=>({date_start:q.date_start.slice(0,10),date_end:q.date_end.slice(0,10),timezone:q.timezone,date_basis:q.date_basis,currency:q.currency,basis:q.basis,exponent:snapshot.scope.exponent,sku:uniq(q.sku),source:uniq(q.source),snapshot_id:snapshot.id});
const exposedScope=(f,scopeHash)=>({...f,date_start:f.date_start+'T00:00:00.000Z',date_end:f.date_end+'T00:00:00.000Z',scope_hash:scopeHash});
const scopeMatches=(q,snap)=>q.date_start.slice(0,10)===snap.scope.start.slice(0,10)&&q.date_end.slice(0,10)===snap.scope.end.slice(0,10)&&q.currency===snap.scope.currency&&q.basis===snap.scope.basis&&(q.exponent===null||q.exponent===snap.scope.exponent)&&q.timezone===snap.scope.timezone&&q.date_basis===snap.scope.dateBasis;
const nullMetric=(scope,reason)=>({amountMinor:null,knownSubtotalMinor:null,knownCount:0,totalCount:0,status:'unavailable',currency:scope.currency,exponent:scope.exponent,missingReasons:[reason]});
const metric=(m,label,kind,sourceRef)=>({label,kind,amount_minor:m.amountMinor,known_subtotal:m.knownSubtotalMinor,currency:m.currency,exponent:m.exponent,source_ref:sourceRef,status:m.status,coverage:{known_n:m.knownCount,eligible_n:m.totalCount},missing_reasons:m.missingReasons});
const componentMetric=c=>({amountMinor:c.amountMinor,knownSubtotalMinor:c.knownSubtotalMinor,currency:c.currency,exponent:c.exponent,status:c.money?.status??(c.amountMinor===null?'unavailable':'complete'),knownCount:c.money?.coverage.known_n??0,totalCount:c.money?.coverage.eligible_n??0,missingReasons:c.money?.missing_reasons??[]});
const tables=['economic_source_versions','economic_ledger_entries','economic_problem_links','economic_order_aliases','economic_order_customers','economic_relation_coverage'];
async function captured(s,row){const state={};for(const table of tables){const ids=row.input_manifest.refs.filter(r=>r.table===table&&r.authorized&&r.active).map(r=>r.id);state[table]=ids.length?(await s.query(`SELECT * FROM public.${table} WHERE tenant_id=$1 AND id=ANY($2::uuid[])`,[s.tenantId,ids])).rows:[];check(state[table].length===ids.length,'captured_evidence_unavailable',403);}return state;}
async function baseSnapshot(s,q){const repo=createSnapshotRepository({database:scopedDb(s)});let id=q.snapshot_id;if(!id){const rows=(await s.query("SELECT id FROM public.metric_snapshots WHERE tenant_id=$1 AND status='published' AND economic_schema_version='economic-snapshot-v1' AND provenance->'scope'->>'start'=$2 AND provenance->'scope'->>'end'=$3 AND provenance->'scope'->>'currency'=$4 AND provenance->'scope'->>'basis'=$5 AND ($6::integer IS NULL OR (provenance->'scope'->>'exponent')::integer=$6) ORDER BY published_at DESC,id DESC LIMIT 1",[s.tenantId,q.date_start.slice(0,10)+'T00:00:00.000Z',q.date_end.slice(0,10)+'T00:00:00.000Z',q.currency,q.basis,q.exponent])).rows;id=rows[0]?.id;}if(!id)return null;const view=await repo.get({snapshotId:id});check(view.status==='published','snapshot_not_published',403);check(scopeMatches(q,view),'snapshot_scope_conflict',409);return {view,row:await one(s,'SELECT * FROM public.metric_snapshots WHERE tenant_id=$1 AND id=$2',[s.tenantId,id])};}
async function binding(s,q,base){const f=filtersFor(q,base.view);let b;if(q.scope_hash){b=await one(s,'SELECT * FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,q.scope_hash]);check(b&&b.base_snapshot_id===base.view.id&&canonical(b.filters)===canonical(f),'workspace_scope_conflict',409);}else{
 await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-mappings']);const ids=base.row.input_manifest.refs.filter(r=>r.table==='economic_ledger_entries'&&r.authorized&&r.active).map(r=>r.id);
 const mappings=ids.length?(await s.query('SELECT DISTINCT ON(ledger_row_id) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 AND ledger_row_id=ANY($2::uuid[]) ORDER BY ledger_row_id,version DESC',[s.tenantId,ids])).rows:[];
 // An unavailable latest declaration never resurrects an older declaration.
 const mappingIds=mappings.filter(m=>m.actor_active).map(m=>m.id).sort();const problemVersions=[];for(const problemId of uniq(base.view.exposure.membership.map(l=>l.problemId))){const p=await one(s,"SELECT id FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 AND created_at<=$3 AND provenance->>'kind'='vector-problem-v1' ORDER BY version DESC LIMIT 1",[s.tenantId,problemId,base.view.asOf]);problemVersions.push({problemId,versionId:p?.id??null});}const body={baseSnapshotId:base.view.id,baseScopeHash:base.view.scopeHash,filters:f,mappingIds,problemVersions,version:VERSION};const scopeHash=canonicalScopeHash(body);
 b=await one(s,'SELECT * FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,scopeHash]);if(!b)return {pending:{tenantId:s.tenantId,baseSnapshotId:base.view.id,baseScopeHash:base.view.scopeHash,scopeHash,filters:f,mappingIds,problemVersions,canonicalInput:canonical(body)},row:null,mappings};}
 const mappings=b.mapping_ids.length?(await s.query('SELECT *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[s.tenantId,b.mapping_ids])).rows:[];check(mappings.length===b.mapping_ids.length&&mappings.every(m=>m.actor_active),'mapping_contributor_unavailable',403);check(canonicalScopeHash({baseSnapshotId:b.base_snapshot_id,baseScopeHash:b.base_scope_hash,filters:b.filters,mappingIds:b.mapping_ids,problemVersions:b.problem_versions,version:b.projection_version})===b.scope_hash,'binding_integrity_failed',409);return {row:b,mappings};}
async function historicalProblems(s,base,ids,bound){const result=new Map(),capturedRuns=new Set(base.row.input_manifest.models.map(m=>m.id));for(const id of ids){const pinned=bound.row.problem_versions.find(p=>p.problemId===id);const p=pinned?.versionId?await one(s,"SELECT * FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2 AND id=$3 AND provenance->>'kind'='vector-problem-v1'",[s.tenantId,id,pinned.versionId]):null;let valid=!!p;const embeddings=p?.provenance?.snapshot?.embeddingIds;valid=valid&&Array.isArray(embeddings)&&embeddings.length>0;if(valid){const members=(await s.query('SELECT embedding_id,extraction_run_id FROM public.problem_embedding_members WHERE tenant_id=$1 AND embedding_id=ANY($2::uuid[])',[s.tenantId,embeddings])).rows;valid=members.length===embeddings.length&&members.every(m=>capturedRuns.has(m.extraction_run_id));}check(valid,'historical_problem_evidence_unavailable',403);const latest=await one(s,'SELECT max(version) AS version FROM public.problem_versions WHERE tenant_id=$1 AND problem_id=$2',[s.tenantId,id]);result.set(id,{id,version:p.version,label:p.provenance.snapshot.label,valid:true,stale:latest.version!==p.version});}return result;}
export function projection(s,base,st,mappings,filters){
 const authorizedIds=new Set(base.row.input_manifest.refs.filter(r=>r.authorized&&r.active).map(r=>r.id));
 const sourceRows=st.economic_source_versions.filter(r=>authorizedIds.has(r.id)&&r.active),activeSources=new Set(sourceRows.map(r=>r.source_id));
 const rows=st.economic_ledger_entries.filter(r=>authorizedIds.has(r.id)&&activeSources.has(r.source_id));const byId=new Map(rows.map(r=>[r.entity_id,r]));
 const aliases=new Map(st.economic_order_aliases.filter(r=>authorizedIds.has(r.id)&&r.active).map(r=>[r.alias_entity_id,r.canonical_entity_id]));
 const canonicalId=id=>{const seen=new Set();while(aliases.has(id)){check(!seen.has(id),'captured_alias_cycle',409);seen.add(id);id=aliases.get(id);}return id;};
 const allOrders=new Map();for(const r of rows.filter(r=>r.kind==='order')){const id=canonicalId(r.entity_id);check(byId.has(id),'captured_alias_unavailable',409);allOrders.set(id,byId.get(id));}
 const mapByRow=new Map(mappings.map(m=>[m.ledger_row_id,m]));const selected=[],uncertain=[];const inScope=r=>r.currency===filters.currency&&r.exponent===filters.exponent&&r.basis===filters.basis&&iso(r.effective_at)>=base.view.scope.start&&iso(r.effective_at)<base.view.scope.end&&iso(r.recorded_at)<=base.view.asOf&&!['pending','cancelled'].includes(r.status);
 for(const r of allOrders.values()){if(!inScope(r))continue;const equivalents=rows.filter(e=>e.kind==='order'&&canonicalId(e.entity_id)===r.entity_id);const declarations=equivalents.map(e=>mapByRow.get(e.id)).filter(m=>m?.active);const skuSets=declarations.filter(m=>m.skus!==null).map(m=>uniq(m.skus));const sources=uniq(declarations.filter(m=>m.source!==null).map(m=>m.source));const skuKnown=skuSets.length>0&&new Set(skuSets.map(canonical)).size===1;const sourceKnown=sources.length===1;
 const skuMatch=!filters.sku.length?true:skuKnown?filters.sku.some(x=>skuSets[0].includes(x)):null,sourceMatch=!filters.source.length?true:sourceKnown?filters.source.includes(sources[0]):null;
 if(skuMatch===false||sourceMatch===false)continue;if(skuMatch===null||sourceMatch===null)uncertain.push(r);else selected.push(r);}
 const baseRow=r=>({id:r.entity_id,tenantId:s.tenantId,sourceAccount:r.source_id,externalId:r.external_id,sourceRevision:String(r.revision),occurredAt:iso(r.effective_at),recordedAt:iso(r.recorded_at),currency:r.currency,exponent:r.exponent,basis:r.basis,amountMinor:r.amount_minor===null?null:String(r.amount_minor),status:r.status,provenance:'approved_manual',evidenceRef:r.id});
 const selectedIds=new Set(selected.map(r=>r.entity_id));const links=[];for(const r of st.economic_problem_links.filter(r=>authorizedIds.has(r.id)&&r.active)){const e=byId.get(r.entity_id);if(e?.kind==='order'&&selectedIds.has(canonicalId(e.entity_id)))links.push({tenantId:s.tenantId,problemId:r.problem_id,orderId:canonicalId(e.entity_id),evidenceRef:r.id,relationVersion:String(r.version)});}
 const uniqueLinks=[...new Map(links.map(l=>[l.problemId+':'+l.orderId,l])).values()];
 const familySources=type=>sourceRows.filter(r=>r.evidence_type===type).map(r=>({sourceAccount:r.source_id,watermark:iso(r.watermark),complete:r.complete&&iso(r.window_start)<=base.view.scope.start&&iso(r.window_end)>=base.view.scope.end&&iso(r.watermark)>=base.view.scope.end}));
 const input={authorization:{tenantId:s.tenantId,permissionsVersion:'snapshot'},snapshot:{tenantId:s.tenantId,id:base.view.id,asOf:base.view.asOf,sources:familySources('order_export')},scope:base.view.scope,orders:selected.map(baseRow),events:[],links:uniqueLinks};const result=adaptLedger(input);
 const eventIds=new Set(rows.filter(r=>r.kind!=='order'&&r.order_id&&selectedIds.has(canonicalId(r.order_id))).map(r=>r.entity_id));let changed=true;while(changed){changed=false;for(const r of rows.filter(r=>r.kind==='reversal')){if(eventIds.has(r.entity_id)&&r.reversal_of&&!eventIds.has(r.reversal_of)){eventIds.add(r.reversal_of);changed=true;}if(eventIds.has(r.reversal_of)&&!eventIds.has(r.entity_id)){eventIds.add(r.entity_id);changed=true;}}}
 const refunds=adaptLedger({...input,snapshot:{...input.snapshot,sources:familySources('payment_ledger')},orders:[],links:[],events:rows.filter(r=>eventIds.has(r.entity_id)&&['refund','reversal'].includes(r.kind)).map(r=>({...baseRow(r),kind:r.kind,reversalOf:r.reversal_of}))}).metrics.refunds;
 const gate=(m,reason)=>({...m,amountMinor:null,status:m.knownSubtotalMinor===null?'unavailable':'partial',missingReasons:uniq([...m.missingReasons,reason])});
 const coverageUnknown=!st.economic_relation_coverage.some(r=>authorizedIds.has(r.id)&&r.complete&&r.input_hash===base.row.input_manifest.exposureInputHash&&canonical(r.scope)===canonical(base.view.scope));
 if(coverageUnknown){result.metrics.exposure.global=gate(result.metrics.exposure.global,'relation_coverage_unconfirmed');for(const k of Object.keys(result.metrics.exposure.byProblem))result.metrics.exposure.byProblem[k]=gate(result.metrics.exposure.byProblem[k],'relation_coverage_unconfirmed');}
 if(uncertain.length){result.metrics.allOrders=gate(result.metrics.allOrders,'DIMENSION_MEMBERSHIP_UNKNOWN');result.metrics.exposure.global=gate(result.metrics.exposure.global,'DIMENSION_MEMBERSHIP_UNKNOWN');for(const k of Object.keys(result.metrics.exposure.byProblem))result.metrics.exposure.byProblem[k]=gate(result.metrics.exposure.byProblem[k],'DIMENSION_MEMBERSHIP_UNKNOWN');}
 if(!familySources('order_export').length){result.metrics.allOrders.knownSubtotalMinor=null;result.metrics.exposure.global.knownSubtotalMinor=null;}
 const uncertainOrders=new Set(uncertain.map(r=>r.entity_id));const eventOrder=r=>{const seen=new Set();while(r&&!r.order_id&&r.kind==='reversal'&&r.reversal_of){if(seen.has(r.entity_id))return null;seen.add(r.entity_id);r=byId.get(r.reversal_of);}return r?.order_id?canonicalId(r.order_id):null;};const unknownEvents=rows.filter(r=>['refund','reversal'].includes(r.kind)&&inScope(r)&&!eventIds.has(r.entity_id)).some(r=>{const id=eventOrder(r);return !id||!allOrders.has(id)||uncertainOrders.has(id);});if(!familySources('payment_ledger').length)refunds.knownSubtotalMinor=null;
 return {...result.metrics,refunds:uncertain.length||unknownEvents?gate(refunds,'DIMENSION_MEMBERSHIP_UNKNOWN'):refunds,uncertain:uncertain.length,selectedCount:selected.length,problemIds:uniq([...uniqueLinks.map(l=>l.problemId),...st.economic_problem_links.filter(l=>authorizedIds.has(l.id)&&l.active&&uncertain.some(r=>canonicalId(l.entity_id)===r.entity_id)).map(l=>l.problem_id)])};
}
export function createWorkspaceService({database}){
 const tx=async(action,work)=>{let domain;try{return await database.transaction(action,async s=>{try{return await work(s);}catch(e){if(e instanceof WorkspaceError||e instanceof EconomicError)domain=e;throw e;}});}catch(e){if(domain)throw domain;throw e;}};
 const api={
 async query(query,{all=false}={}){const request=query instanceof URLSearchParams?parseWorkspaceQuery(query):query;const prepared=await tx('read',async s=>{const base=await baseSnapshot(s,request.scope);return base?binding(s,request.scope,base):null;});if(prepared?.pending){const p=prepared.pending;await tx('materialize',async s=>{check(s.tenantId===p.tenantId,'tenant_changed',403);await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-mappings']);const found=await one(s,'SELECT id FROM public.workspace_scope_bindings WHERE tenant_id=$1 AND scope_hash=$2',[s.tenantId,p.scopeHash]);if(!found)await s.query('INSERT INTO public.workspace_scope_bindings(tenant_id,base_snapshot_id,base_scope_hash,scope_hash,filters,projection_version,mapping_ids,problem_versions,canonical_input,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[s.tenantId,p.baseSnapshotId,p.baseScopeHash,p.scopeHash,JSON.stringify(p.filters),VERSION,p.mappingIds,JSON.stringify(p.problemVersions),p.canonicalInput,s.userId]);});request.scope={...request.scope,snapshot_id:p.baseSnapshotId,scope_hash:p.scopeHash};}else if(prepared)request.scope={...request.scope,snapshot_id:prepared.row.base_snapshot_id,scope_hash:prepared.row.scope_hash};return tx('read',async s=>{
 const q=request.scope,base=await baseSnapshot(s,q);if(!base)return {items:[],meta:{state:'empty',snapshot_id:null,base_snapshot_id:null,base_scope_hash:null,scope_hash:null,cursor_auth_hash:null,coverage:'Sin snapshot publicado para este alcance.',watermark:null,next_cursor:null,critical_notice:null,scope:q,mapping_manifest_id:null,can_manage:s.role==='owner'}};
 const bound=await binding(s,q,base),f=bound.row.filters,st=await captured(s,base.row),p=projection(s,base,st,bound.mappings,f),filtered=f.sku.length>0||f.source.length>0;
 const component=key=>base.view.components.find(c=>c.metric===key&&c.currency===f.currency&&!c.conversion);
 const choose=(key,m)=>!filtered&&component(key)?componentMetric(component(key)):m;
 const global=choose('exposure.global',p.exposure.global),orders=choose('allOrders',p.allOrders),refunds=choose('refunds',p.refunds);
 const ids=filtered?p.problemIds:uniq(base.view.exposure.membership.map(l=>l.problemId));const history=await historicalProblems(s,base,ids,bound);const stale=[...history.values()].some(p=>p.stale);
 const ref='workspace:'+bound.row.scope_hash,make=(id,title,version,problemId,metrics,valid=true)=>({id,title,summary:problemId?'Filas por problema no aditivas; el global usa la unión de órdenes.':'Importes del snapshot publicado. SKU selecciona órdenes que contienen el producto; no ventas por línea.',status:valid?(metrics.some(m=>m.amount_minor===null)?'partial':'ready'):'stale',version,owner:null,customer_id:null,problem_id:problemId,metrics,evidence:[],details:[{label:'Snapshot',value:base.view.id},{label:'Alcance derivado',value:bound.row.scope_hash},{label:'Asociaciones',value:'Declaradas y aprobadas por un propietario; no validación automática de CRM.'}]});
 let items;if(request.resource==='metrics')items=[make(base.view.id,'Resumen económico',1,null,[metric(global,'Ingresos expuestos','exposure',ref),metric(orders,'Órdenes registradas','allOrders',ref),metric(refunds,'Reembolsos liquidados','refunds',ref)])];else items=ids.map(id=>{const h=history.get(id),m=h.valid?choose('exposure.'+id,p.exposure.byProblem[id]??nullMetric(base.view.scope,'DIMENSION_MEMBERSHIP_UNKNOWN')):nullMetric(base.view.scope,'HISTORICAL_PROBLEM_VERSION_UNAVAILABLE');return make(id,h.label,h.version,id,[metric(m,'Ingresos expuestos','exposure',ref)],h.valid);}).sort((a,b)=>a.id.localeCompare(b.id));
 const authHash=cursorAuthHash(s,bound.row.scope_hash,base.view.id),expected={resource:request.resource,authHash,snapshotId:base.view.id,dataScopeHash:bound.row.scope_hash};const after=decodeCursor(request.cursor,expected);if(after){check(items.some(i=>i.id===after),'cursor_position_invalid',409);items=items.filter(i=>i.id>after);}const more=!all&&items.length>request.limit;items=all?items:items.slice(0,request.limit);
 const priorities=await createPriorityRepository({database:scopedDb(s)}).view({snapshotId:base.view.id});const critical=priorities.problemOptions.filter(p=>p.criticalLane).length;
 return {items,meta:{state:stale?'stale':!items.length?'empty':p.uncertain||items.some(r=>r.status==='partial')?'partial':'ready',snapshot_id:base.view.id,base_snapshot_id:base.view.id,base_scope_hash:base.view.scopeHash,scope_hash:bound.row.scope_hash,cursor_auth_hash:authHash,coverage:p.uncertain?`${p.uncertain} órdenes con pertenencia al filtro desconocida; subtotal de pertenencias confirmadas.`:stale?'La versión actual del problema cambió; esta vista conserva la historia y las cifras publicadas.':'Cobertura financiera según el snapshot; filas por problema no aditivas.',watermark:base.view.watermark,next_cursor:more?encodeCursor({after:items.at(-1).id,...expected}):null,critical_notice:critical?`${critical} señales críticas actuales autorizadas, independientes de los filtros y del importe del snapshot.`:null,scope:exposedScope(f,bound.row.scope_hash),mapping_manifest_id:bound.row.id,can_manage:s.role==='owner'}};
 });},
 async mappings(){return tx('read',async s=>{const orders=(await s.query("SELECT DISTINCT ON(entity_id) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.economic_ledger_entries WHERE tenant_id=$1 AND kind='order' ORDER BY entity_id,revision DESC",[s.tenantId])).rows;const valid=[];for(const r of orders)if((await one(s,"SELECT public.economic_record_current($1,$2,array['order']) AS valid",[s.tenantId,r.id])).valid)valid.push(r);const rows=(await s.query('SELECT DISTINCT ON(ledger_row_id) *,public.economic_contributor_active(tenant_id,actor_id) AS actor_active FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 ORDER BY ledger_row_id,version DESC',[s.tenantId])).rows;return {orders:valid.map(r=>({ledgerRowId:r.id,entityId:r.entity_id,externalId:r.external_id,currency:r.currency,exponent:r.exponent,amountMinor:r.amount_minor===null?null:String(r.amount_minor),sourceName:r.source_id})),mappings:rows.map(r=>({id:r.id,ledgerRowId:r.ledger_row_id,version:r.version,skus:r.actor_active?r.skus:null,source:r.actor_active?r.source:null,active:r.active,valid:r.actor_active,report:r.actor_active?r.report:null})),canWrite:s.role==='owner'};});},
 async recordMapping(q){check(q&&Object.keys(q).every(k=>['ledgerRowId','expectedVersion','skus','source','active','report','attested'].includes(k))&&uuid(q.ledgerRowId)&&Number.isInteger(q.expectedVersion)&&q.expectedVersion>=0&&(q.skus===null||Array.isArray(q.skus)&&q.skus.length<=100&&q.skus.every(x=>typeof x==='string'&&x.trim()===x&&x.length>0&&x.length<=100&&!/[\u0000-\u001f\u007f]/.test(x)))&&(q.source===null||['hubspot','zendesk','csv','excel'].includes(q.source))&&typeof q.active==='boolean'&&typeof q.report==='string'&&q.report.length>=20&&q.report.length<=4000&&q.attested===true,'mapping_input_invalid');return tx('configure',async s=>{await s.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[s.tenantId+':workspace-mappings']);const prior=await one(s,'SELECT max(version) AS version FROM public.workspace_order_dimension_versions WHERE tenant_id=$1 AND ledger_row_id=$2',[s.tenantId,q.ledgerRowId]);check((prior.version??0)===q.expectedVersion,'mapping_version_conflict',409);const r=await one(s,'INSERT INTO public.workspace_order_dimension_versions(tenant_id,ledger_row_id,version,actor_id,skus,source,active,report,attested) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) RETURNING *',[s.tenantId,q.ledgerRowId,q.expectedVersion+1,s.userId,q.skus===null?null:uniq(q.skus),q.source,q.active,q.report]);return {id:r.id,ledgerRowId:r.ledger_row_id,version:r.version,skus:r.skus,source:r.source,active:r.active,valid:true,report:r.report};});},
 };return api;
}
export function workspaceCsv(bundle){const headers=['snapshot_id','base_scope_hash','scope_hash','record_id','metric','currency','exponent','amount_minor','known_subtotal','status'];return [headers,...bundle.items.flatMap(r=>r.metrics.map(m=>[bundle.meta.snapshot_id,bundle.meta.base_scope_hash,bundle.meta.scope_hash,r.id,m.kind,m.currency,m.exponent,m.amount_minor,m.known_subtotal,m.status]))].map(row=>row.map(x=>'"'+(x===null?'':String(x)).replaceAll('"','""')+'"').join(',')).join('\r\n')+'\r\n';}
