import {randomUUID} from 'node:crypto';
import {NextRequest,NextResponse} from 'next/server';
import {createDatabase} from '@vexa/platform/db';
import {createSnapshotRepository,snapshotCsv} from '../../../../packages/metrics/snapshots.mjs';
import {serverPool} from './imports/server';
import {ACTIVE_ORG,AccessError,assertOrigin,config,identity,PRIVATE_HEADERS} from './auth';
import {requestAuth} from './auth-http';
export async function snapshotResponse(request:NextRequest,id?:string,exporting=false){let finish=(r:NextResponse)=>r;try{const configuration=config();if(!configuration)return NextResponse.json({contract_version:'f05-snapshots-v1',error:{code:'configuration_required',retryable:true,message:'La configuración del servidor de snapshots no está disponible.'},meta:{trace_id:randomUUID()}},{status:503,headers:PRIVATE_HEADERS});if(request.method==='POST')assertOrigin(request.headers.get('origin'),configuration.origin);const auth=requestAuth(request);finish=auth.finish;const repo=createSnapshotRepository({database:createDatabase({identity:identity(auth.client),pool:serverPool(),selectedTenant:request.cookies.get(ACTIVE_ORG)?.value})});const params=request.nextUrl.searchParams;let data;
 if(id){for(const key of params.keys())if(!['scopeHash',...(exporting?['format']:[])].includes(key)||params.getAll(key).length!==1)throw new AccessError(400,'unsupported_filter');if(exporting&&!params.get('scopeHash'))throw new AccessError(400,'snapshot_scope_required');data=await repo.get({snapshotId:id,...(params.has('scopeHash')?{scopeHash:params.get('scopeHash')!}:{})});if(exporting){if(data.status!=='published')throw new AccessError(409,'snapshot_not_published');const format=params.get('format');if(!['json','csv'].includes(format??''))throw new AccessError(400,'format_required');return finish(new NextResponse(format==='json'?JSON.stringify(data):snapshotCsv(data),{headers:{...PRIVATE_HEADERS,'Content-Type':format==='json'?'application/json':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="snapshot-${data.id}.${format}"`,'X-Snapshot-Id':data.id,'X-Snapshot-Scope':data.scopeHash,'X-Snapshot-Hash':data.contentHash}}));}}
 else if(request.method==='GET'){for(const key of params.keys())if(!['start','end','currency','exponent','basis','timezone','fxRateId'].includes(key)||params.getAll(key).length!==1)throw new AccessError(400,'unsupported_filter');const exponent=params.get('exponent');if(!exponent||!/^\d$/.test(exponent))throw new AccessError(400,'scope_required');data=await repo.latest({scope:{start:params.get('start')??'',end:params.get('end')??'',currency:params.get('currency')??'',exponent:Number(exponent),basis:params.get('basis')??'',timezone:params.get('timezone')??'UTC',dateBasis:'occurred_at'},...(params.has('fxRateId')?{fxRateId:params.get('fxRateId')!}:{})});}
 else {if(request.nextUrl.search)throw new AccessError(400,'unsupported_filter');const raw=await request.text();if(Buffer.byteLength(raw)>16384)throw new AccessError(400,'input_too_large');let parsed;try{parsed=JSON.parse(raw);}catch{throw new AccessError(400,'input_invalid');}if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new AccessError(400,'input_invalid');const {operation,...input}=parsed;if(operation==='stage')data=await repo.stage(input);else if(operation==='publish')data=await repo.publish(input);else throw new AccessError(400,'operation_invalid');}
 return finish(NextResponse.json({data},{headers:{...PRIVATE_HEADERS,Vary:'Cookie'}}));
 }catch(error){const e=error as {status?:number};const status=[400,401,403,404,409,503].includes(e.status??0)?e.status!:503;return finish(NextResponse.json({error:{code:'snapshot_request_failed',message:status===409?'El snapshot, su alcance o sus fuentes requieren revisión.':'No se pudo consultar o publicar el snapshot.'}},{status,headers:PRIVATE_HEADERS}));}}
