import test from 'node:test';import assert from 'node:assert/strict';import {adaptLedger} from './adapter.mjs';
const row=(id,amountMinor='10000')=>({id,tenantId:'SYN-A',sourceAccount:'SYN-account',externalId:id,sourceRevision:'1',occurredAt:'2026-09-10T00:00:00Z',recordedAt:'2026-09-11T00:00:00Z',currency:'USD',exponent:2,basis:'SYN-order-net-no-tax',amountMinor,status:'recorded',provenance:'observed',evidenceRef:'SYN-source:'+id});
const input=()=>({authorization:{tenantId:'SYN-A',permissionsVersion:'1'},snapshot:{tenantId:'SYN-A',id:'SYN-snapshot',asOf:'2026-10-01T00:00:00Z',sources:[{sourceAccount:'SYN-account',watermark:'SYN-w1',complete:true}]},scope:{start:'2026-09-01T00:00:00Z',end:'2026-10-01T00:00:00Z',timezone:'UTC',dateBasis:'occurred_at',currency:'USD',exponent:2,basis:'SYN-order-net-no-tax'},orders:[row('O1'),row('O2','20000'),row('O3',null)],events:[{...row('R1','2000'),kind:'refund',status:'settled',reversalOf:null},{...row('V1','-500'),kind:'reversal',status:'settled',reversalOf:'R1'}],links:[{tenantId:'SYN-A',orderId:'O1',problemId:'P1',evidenceRef:'SYN-link',relationVersion:'1'},{tenantId:'SYN-A',orderId:'O2',problemId:'P1',evidenceRef:'SYN-link',relationVersion:'1'},{tenantId:'SYN-A',orderId:'O1',problemId:'P2',evidenceRef:'SYN-link',relationVersion:'1'}]});
test('SYNTHETIC adapter exact exposure/refund and unknown remain separate',()=>{const b=adaptLedger(input());assert.equal(b.metrics.allOrders.amountMinor,null);assert.equal(b.metrics.allOrders.knownSubtotalMinor,'30000');assert.equal(b.metrics.exposure.global.amountMinor,'30000');assert.equal(b.metrics.exposure.byProblem.P2.amountMinor,'10000');assert.equal(b.metrics.refunds.amountMinor,'1500');assert.equal(b.metrics.exposure.problemRowsAreAdditive,false);});
test('canonical replay, immutable input and exact integer beyond2^53',()=>{const f=input();f.orders=[row('BIG','900719925474099312345')];f.links=[];const before=JSON.stringify(f),a=adaptLedger(f);assert.equal(a.metrics.allOrders.amountMinor,'900719925474099312345');f.events.reverse();f.events.push({...f.events[0]});assert.deepEqual(adaptLedger(f),a);const fresh=input(),copy=JSON.stringify(fresh);adaptLedger(fresh);assert.equal(JSON.stringify(fresh),copy);assert.equal(before.includes('900719925474099312345'),true);});
test('tenant/provenance/unit/status reject before exclusion; conflicts are unavailable',()=>{for(const [key,value,code]of [['tenantId','SYN-B','TENANT_MISMATCH'],['provenance','llm','FINANCIAL_PROVENANCE_REQUIRED'],['amountMinor',9007199254740992,'MINOR_UNITS_INVALID'],['status',undefined,'STATUS_REQUIRED']]){const f=input();f.orders[0][key]=value;f.orders[0].currency='EUR';assert.throws(()=>adaptLedger(f),e=>e.code===code);}const f=input();f.orders.push({...f.orders[0],amountMinor:'1'});assert.equal(adaptLedger(f).metrics.allOrders.status,'unavailable');});
test('incomplete empty neverzero; complete emptyzero and explicit recordedzero known',()=>{const f=input();f.orders=[];f.events=[];f.links=[];assert.equal(adaptLedger(f).metrics.allOrders.amountMinor,'0');f.snapshot.sources[0].complete=false;assert.equal(adaptLedger(f).metrics.allOrders.amountMinor,null);assert.equal(adaptLedger(f).metrics.refunds.amountMinor,null);f.snapshot.sources[0].complete=true;f.orders=[row('zero','0')];assert.equal(adaptLedger(f).metrics.allOrders.knownCount,1);});
test('period semiopen, late records and missing original cannot disappear aszero',()=>{const f=input();f.orders[0].occurredAt=f.scope.end;f.orders[0].recordedAt=f.scope.end;assert.equal(adaptLedger(f).metrics.exposure.global.amountMinor,'20000');f.events[0].occurredAt='2026-08-31T00:00:00Z';assert.equal(adaptLedger(f).metrics.refunds.status,'unavailable');assert.equal(adaptLedger(f).metrics.refunds.amountMinor,null);f.events[0].occurredAt='2026-09-10T00:00:00Z';f.events[1].amountMinor='-2500';assert.equal(adaptLedger(f).metrics.refunds.status,'unavailable');});
test('scope stable across snapshot refresh while input hash changes',()=>{const f=input(),a=adaptLedger(f);f.snapshot.id='SYN-new';f.snapshot.sources[0].watermark='SYN-w2';const b=adaptLedger(f);assert.equal(a.scopeHash,b.scopeHash);assert.notEqual(a.inputHash,b.inputHash);});

test('stable economic source identity excludes revision and impossible dates reject',()=>{const f=input();f.events.push({...f.events[0],id:'R2',sourceRevision:'2'});const result=adaptLedger(f);assert.equal(result.metrics.refunds.amountMinor,null);assert.equal(result.metrics.refunds.status,'unavailable');const d=input();d.orders[0].occurredAt='2026-02-30T00:00:00Z';assert.throws(()=>adaptLedger(d),e=>e.code==='RECORD_DATE_INVALID');d.orders[0].occurredAt='2026-09-10T00:00:00.1Z';assert.doesNotThrow(()=>adaptLedger(d));});

test('window after snapshot stays partial even with empty complete source',()=>{const f=input();f.orders=[];f.links=[];f.events=[];f.snapshot.asOf='2026-09-20T00:00:00Z';const out=adaptLedger(f);assert.equal(out.metrics.allOrders.amountMinor,null);assert.ok(out.metrics.allOrders.missingReasons.includes('WINDOW_INCOMPLETE'));});

test('special object property problem IDs remain own serializable metric rows',()=>{const f=input();for(const l of f.links)l.problemId='__proto__';const result=adaptLedger(f);assert.ok(Object.hasOwn(result.metrics.exposure.byProblem,'__proto__'));assert.equal(JSON.parse(JSON.stringify(result)).metrics.exposure.byProblem.__proto__.amountMinor,'30000');});
