import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {fixture,request,historyBytes} from './fixtures.mjs';import {q} from './harness.mjs';import {insert} from '../F01-03/matrix.mjs';
export async function domain(t,h){
 await t.test('human approved SYN crosswalk resolves A5 to4, undo restores5 without rewriting originals',async()=>{const f=fixture(h),r=h.aliasRepository(f.a),b=h.aliasRepository(f.b),before=historyBytes(h,f);assert.equal((await r.list()).length,5,'SYN_A_FIVE');const originalB=await b.list();const p=await r.propose(request(f));assert.equal(p.status,'proposed');assert.equal((await r.list()).length,5,'MATCHING_NEVER_AUTO_UNIONS');assert.equal(h.sql(`SELECT count(*) FROM external_aliases WHERE tenant_id=${q(f.a.tenant)}`),'0','PROPOSAL_NO_ALIAS_WRITE');const approved=await r.confirm(request(f));assert.equal(approved.approved_by,f.a.id,'SQL_ACTOR');assert.equal(approved.version,1);assert.equal((await r.list()).length,4,'SYN_A_FOUR_RESOLVED');assert.equal((await r.resolve({conversationId:f.ids.z142})).canonical_id,f.ids.h42);for(const key of ['z43','z44'])assert.equal((await r.resolve({conversationId:f.ids[key]})).canonical_id,f.ids[key],'UNRELATED_CASE_SEPARATE');assert.deepEqual(await b.list(),originalB,'B_UNCHANGED');assert.deepEqual(historyBytes(h,f),before,'ALIAS_ORIGINALS_INTACT');const undo=await r.undo({...request(f),expectedVersion:1});assert.equal(undo.operation,'undo');assert.equal(undo.version,2);assert.equal((await r.list()).length,5,'UNDO_RESTORES_FIVE');assert.deepEqual(historyBytes(h,f),before,'UNDO_HISTORY_IDENTICAL');const history=await r.history({sourceConversationId:f.ids.z142});assert.deepEqual(history.map(x=>x.operation),['confirm','undo'],'APPEND_ONLY_COMPENSATION');});
 await t.test('missing explicit approval, evidence and reason cannot bind identities',async()=>{const f=fixture(h),r=h.aliasRepository(f.a);for(const delta of [{approved:false},{approved:undefined},{evidenceRef:''},{evidenceRef:undefined},{reason:''}])await assert.rejects(r.confirm(request(f,delta)),undefined,'HUMAN_APPROVAL_REQUIRED');assert.equal((await r.list()).length,5);});
 await t.test('tenant and self/cycle conflicts reject atomically',async()=>{const f=fixture(h),r=h.aliasRepository(f.a);await assert.rejects(r.confirm(request(f,{targetConversationId:f.ids.b142})),undefined,'CROSS_TENANT_REJECT');await assert.rejects(r.confirm(request(f,{targetConversationId:f.ids.z142})),undefined,'SELF_REJECT');await r.confirm(request(f));await assert.rejects(r.confirm(request(f,{sourceConversationId:f.ids.h42,targetConversationId:f.ids.z142})),undefined,'CYCLE_REJECT');assert.equal((await r.list()).length,4);});
 await t.test('CAS protects competing human decisions and stale undo',async()=>{const f=fixture(h),r=h.aliasRepository(f.a);const outcomes=await Promise.allSettled([r.confirm(request(f)),r.confirm(request(f,{targetConversationId:f.ids.h99}))]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1,'CONCURRENT_ONE_WINNER');assert.equal(outcomes.filter(x=>x.status==='rejected').length,1);assert.equal((await r.history({sourceConversationId:f.ids.z142})).length,1);await assert.rejects(r.undo(request(f)),undefined,'STALE_UNDO_REJECT');assert.equal((await r.list()).length,4);});
 await t.test('SQL current membership defeats stale application role and actor spoof',async()=>{for(const kind of ['analyst','revoked']){const f=fixture(h),r=h.aliasRepository(f.a);h.sql(`UPDATE memberships SET ${kind==='revoked'?"status='revoked'":"role='analyst'"} WHERE user_id=${q(f.a.id)}`);await assert.rejects(r.confirm(request(f,{approved_by:f.b.id,actor:f.b.id})),undefined,'SQL_MEMBERSHIP_REVALIDATED');assert.equal(h.sql(`SELECT count(*) FROM external_aliases WHERE tenant_id=${q(f.a.tenant)}`),'0');}const f=fixture(h),r=h.aliasRepository(f.a);const row=await r.confirm(request(f,{approved_by:f.b.id}));assert.equal(row.approved_by,f.a.id,'CALLER_CANNOT_CHOOSE_APPROVER');});
 await t.test('source account provenance mismatch and ambiguous source head block aliases',async()=>{for(const kind of ['account','source','ambiguous']){const f=fixture(h),r=h.aliasRepository(f.a);if(kind==='ambiguous')h.sql(`INSERT INTO source_heads(id,tenant_id,connection_id,entity_type,external_id,version,state) VALUES(${q(f.ids.z142)},${q(f.a.tenant)},${q(f.zd.connection)},'conversation','142',1,'ambiguous')`);else h.sql(`UPDATE conversations SET provenance=provenance||${q(JSON.stringify({[kind==='account'?'account_id':'source']:'SYN-wrong'}))}::jsonb WHERE id=${q(f.ids.z142)}`);await assert.rejects(r.confirm(request(f)),undefined,'SOURCE_SCOPE_OR_AMBIGUITY_REJECT');}});
 await t.test('reconnect changing account cannot reinterpret existing source identities',async()=>{const f=fixture(h),r=h.aliasRepository(f.a);h.sql(`UPDATE connections SET account_id='SYN-OTHER-ACCOUNT' WHERE id=${q(f.zd.connection)}`);await assert.rejects(r.confirm(request(f)),undefined,'ACCOUNT_CHANGE_REJECT');});
 await t.test('legacy approvals block resolution until explicit fresh review and remain in history',async()=>{const f=fixture(h),r=h.aliasRepository(f.a),legacy={id:randomUUID(),tenant_id:f.a.tenant,source:'zendesk',account_id:f.zd.account,entity_type:'conversation',external_id:'142',canonical_id:f.ids.h42,approved_by:f.a.id,evidence_ref:'SYN-legacy-evidence',version:1};
 // Model a row retained from the pre-009 schema; only the disposable fixture administrator bypasses the new trigger.
 h.sql('ALTER TABLE external_aliases DISABLE TRIGGER alias_event_guard');try{h.sql(insert('external_aliases',legacy));}finally{h.sql('ALTER TABLE external_aliases ENABLE TRIGGER alias_event_guard');}
 const original=h.sql(`SELECT to_jsonb(a) FROM external_aliases a WHERE id=${q(legacy.id)}`);await assert.rejects(r.list(),undefined,'LEGACY_NOT_SILENTLY_IGNORED');await assert.rejects(r.resolve({conversationId:f.ids.z142}));const p=await r.propose(request(f));assert.equal(p.legacyUnresolved,true);assert.equal(p.expectedVersion,1);await r.confirm(request(f,{expectedVersion:1}));assert.equal((await r.list()).length,4);assert.equal((await r.history({sourceConversationId:f.ids.z142})).length,2,'LEGACY_HISTORY_VISIBLE');assert.equal(h.sql(`SELECT to_jsonb(a) FROM external_aliases a WHERE id=${q(legacy.id)}`),original,'LEGACY_ROW_IMMUTABLE');});
 await t.test('simultaneous opposite edges cannot create a cycle',async()=>{const f=fixture(h),r=h.aliasRepository(f.a);const outcomes=await Promise.allSettled([r.confirm(request(f)),r.confirm(request(f,{sourceConversationId:f.ids.h42,targetConversationId:f.ids.z142}))]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1,'CONCURRENT_GRAPH_CYCLE_BLOCKED');assert.equal((await r.list()).length,4);});
 await t.test('non-read-committed snapshots cannot commit opposite approvals or undo',async()=>{
  const f=fixture(h);let arrivals=0,release;const barrier=new Promise(resolve=>{release=resolve;});
  const repository=()=>h.aliases.createAliasRepository({database:h.repository(f.a,{fault:{async after(text,values,client){
   if(text==='BEGIN')await client.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
   if(text.startsWith('SELECT tenant_id,user_id')){if(++arrivals===2)release();await barrier;}
  }}}).database});
  const outcomes=await Promise.allSettled([repository().confirm(request(f)),repository().confirm(request(f,{sourceConversationId:f.ids.h42,targetConversationId:f.ids.z142}))]);
  assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,0,'RR_ALIAS_APPROVALS_MUST_NOT_COMMIT');
  assert.equal(h.sql(`SELECT count(*) FROM external_aliases WHERE tenant_id=${q(f.a.tenant)}`),'0','RR_ALIAS_ROLLBACK');
  const normal=h.aliasRepository(f.a);await normal.confirm(request(f));
  for(const isolation of ['REPEATABLE READ','SERIALIZABLE','READ UNCOMMITTED']){
   const restricted=h.aliases.createAliasRepository({database:h.repository(f.a,{fault:{async after(text,values,client){if(text==='BEGIN')await client.query('SET TRANSACTION ISOLATION LEVEL '+isolation);}}}).database});
   await assert.rejects(restricted.undo(request(f,{expectedVersion:1})),undefined,'ISOLATION_UNDO_REJECT');
  }
  assert.equal((await normal.history({sourceConversationId:f.ids.z142})).length,1,'UNSUPPORTED_UNDO_NO_EVENT');
  await normal.undo(request(f,{expectedVersion:1}));assert.equal((await normal.list()).length,5,'RC_UNDO_PRESERVED');
 });
}
