import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fixture} from './fixtures.mjs';import {q} from './harness.mjs';import {randomUUID} from 'node:crypto';import * as aliases from '../F01-03/aliases/oracles.mjs';import {foreignKeys} from '../F01-03/oracles.mjs';import {backend} from '../F01-03/import-uploads/oracles.mjs';import {read,write,denied} from '../F01-03/harness.mjs';import {insert} from '../F01-03/matrix.mjs';
export async function security(t,h){const syn=fixture(h),actors={a:syn.a,b:syn.b};for(const key of ['analyst','operator','viewer'])actors[key]=h.actor(key,syn.a.tenant);actors.outsider=h.actor();actors.dual=h.actor('owner',syn.a.tenant);h.sql(`INSERT INTO memberships(tenant_id,user_id,role,status) VALUES(${q(syn.b.tenant)},${q(actors.dual.id)},'owner','active')`);const f={};for(const side of ['a','b']){const actor=actors[side];f[side]={conversations:h.json(`SELECT to_jsonb(c) FROM conversations c WHERE id=${q(side==='a'?syn.ids.h42:syn.ids.b142)}`),connections:h.json(`SELECT to_jsonb(c) FROM connections c WHERE id=${q(actor.connection)}`),memberships:h.json(`SELECT to_jsonb(m) FROM memberships m WHERE user_id=${q(actor.id)}`)};}aliases.seed(h,f,actors);
 await t.test('009 existing-table schema, live SQL roles, tuple scope and every FK',()=>{aliases.schema(h,foreignKeys(h));aliases.access(h,f,actors);for(const fk of foreignKeys(h).filter(k=>k.table===aliases.table))aliases.fk(h,f,fk);});
 await t.test('mutants are rejected by approval, tenant isolation and append-only oracles',()=>{const row=f.a.external_aliases,A=row.tenant_id;const cycles=[];const cycle=(name,oracle,change,restore)=>{oracle();h.sql(change);try{assert.throws(oracle,undefined,'MUTANT_MUST_FAIL:'+name);}finally{h.sql(restore);}oracle();cycles.push(name+':0-1-0');};const next={...row,id:randomUUID(),version:2,previous_version:1,operation:'undo',canonical_id:row.source_conversation_id,approved_by:null};
 cycle('approval_required',()=>{assert.notEqual(backend(h,write(insert('external_aliases',next)),actors.a,A,'configure').code,'00000','MUTANT_AUTO_ALIAS_APPROVAL');},'ALTER TABLE external_aliases DISABLE TRIGGER alias_event_guard','ALTER TABLE external_aliases ENABLE TRIGGER alias_event_guard');
 cycle('selected_tenant_isolation',()=>{const r=backend(h,read('external_aliases'),actors.dual,A,'read');assert.equal(r.code,'00000');assert.deepEqual(r.rows.map(x=>x.id),[row.id],'MUTANT_CROSS_TENANT_ALIAS');},'CREATE POLICY synthetic_alias_leak ON external_aliases FOR SELECT TO vexa_backend USING(true)','DROP POLICY synthetic_alias_leak ON external_aliases');
 cycle('destructive_history_delete',()=>denied(backend(h,write(`DELETE FROM external_aliases WHERE id=${q(row.id)}`),actors.a,A,'retain'),'MUTANT_DESTRUCTIVE_UNDO'),'GRANT DELETE ON external_aliases TO vexa_backend; ALTER TABLE external_aliases DISABLE TRIGGER alias_event_guard','ALTER TABLE external_aliases ENABLE TRIGGER alias_event_guard; REVOKE DELETE ON external_aliases FROM vexa_backend');
 fs.writeFileSync(path.join(h.evidence,'mutants.json'),JSON.stringify(cycles),{mode:0o600});});
}
